// Actual browser self-check and deterministic capture entry. Does not submit any request.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname, mode=process.argv[2]||'diagnostic', support=path.join(dir,'diagnostic_support');
fs.mkdirSync(support,{recursive:true});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const identity=p=>({path:p.replace(/\\/g,'/'),bytes:fs.statSync(p).size,sha256:hash(p)});
const binding=JSON.parse(fs.readFileSync(dir+'/input-binding.json','utf8'));
const payload=JSON.parse(fs.readFileSync(dir+'/derived-copy-map.json','utf8')).payload;
const observations=[],failures=[];
const assert=(id,condition,detail,type='ACTUAL_RUNTIME')=>{const r={id,pass:!!condition,evidence_type:type,detail};observations.push(r);if(!condition)failures.push(r)};
const url=scenario=>pathToFileURL(path.join(dir,(scenario==='full'?'index':scenario)+'.html')).href;
const geometric=()=>{
 const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&s.display!=='none'&&!e.closest('[hidden]')&&(!e.closest('details:not([open])')||e.tagName==='SUMMARY'||e.closest('summary'))};
 const controls=[...document.querySelectorAll('a,button,summary')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {label:e.innerText.trim(),w:r.width,h:r.height,x:r.x,right:r.right}});
 const overflow=[...document.querySelectorAll('body *')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.x<-.5||r.right>innerWidth+.5}).map(e=>({tag:e.tagName,cls:e.className,text:e.innerText?.slice(0,60)}));
 const clipped=[...document.querySelectorAll('main *')].filter(visible).filter(e=>{const s=getComputedStyle(e);return (s.overflowX==='hidden'||s.overflowY==='hidden'||s.textOverflow==='ellipsis'||s.webkitLineClamp!=='none')&&(e.scrollHeight>e.clientHeight+1||e.scrollWidth>e.clientWidth+1)}).map(e=>e.outerHTML.slice(0,150));
 return {viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,header:document.querySelector('header').getBoundingClientRect().height,controls,overflow,clipped,fonts:document.fonts.check('16px Inter'),images:[...document.images].map(i=>({loaded:i.complete&&i.naturalWidth>0,w:i.width,h:i.height})),modules:[...document.querySelectorAll('[data-module]')].map(e=>e.dataset.module),open:[...document.querySelectorAll('.app-grades')].map(d=>d.open),headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>({tag:e.tagName,text:e.textContent})),groups:[...document.querySelectorAll('.app-collection')].map(e=>({name:e.querySelector('h3').textContent,scope:e.querySelector('.app-scope p').textContent,grades:[...e.querySelectorAll('.app-grades li')].map(l=>l.textContent),links:e.querySelectorAll('.app-grade-link').length,cta:e.querySelector('.app-collection-action')?.innerText||null}))};
};
async function load(page,scenario,scriptEnabled=true){await page.goto(url(scenario));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode().catch(()=>{}))));if(scriptEnabled)await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function openAll(page){for(const d of await page.locator('.app-grades').all())if(await d.getAttribute('open')===null)await d.locator('summary').click();}
async function capture(page,options){await page.evaluate(()=>scrollTo(0,0));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.screenshot(options);}
async function geom(page,id){const r=await page.evaluate(geometric);assert(id,r.scrollWidth<=r.viewport&&r.overflow.length===0&&r.clipped.length===0&&r.controls.every(c=>c.w>=43.99&&c.h>=43.99)&&r.fonts&&r.images.every(i=>i.loaded)&&r.header===(r.viewport>=1101?84:64),r);return r;}
(async()=>{
 const browser=await chromium.launch({headless:true});
 try{
 if(mode==='diagnostic'){
  for(const [scenario,cfg]of Object.entries(binding.scenarios))for(const width of [1440,768,390]){
   const page=await browser.newPage({viewport:{width,height:900},deviceScaleFactor:1});
   await load(page,scenario);const base=await geom(page,scenario+'-'+width+'-geometry');
   assert(scenario+'-'+width+'-module-order',JSON.stringify(base.modules)===JSON.stringify(['M1','M2','M3',...(cfg.supports.length?['M4']:[]),...(cfg.rfq?['M5']:[])]),base.modules);
   assert(scenario+'-'+width+'-relationships',JSON.stringify(base.groups.map(g=>[g.name,g.scope,g.grades]))===JSON.stringify(payload.groups.map(g=>[g.name,g.scope,g.grades])),base.groups);
   const semantics=await page.evaluate(()=>({h1:document.querySelectorAll('h1').length,intro:document.querySelector('.app-intro').innerText,plain:[...document.querySelectorAll('.app-grade-plain')].map(e=>({tag:e.tagName,tabindex:e.getAttribute('tabindex'),href:e.getAttribute('href')})),rfq:[...document.querySelectorAll('.app-rfq')].map(a=>a.getAttribute('href')),supports:[...document.querySelectorAll('.app-supports h3')].map(e=>e.innerText),appCta:[...document.querySelectorAll('.app-collection-action a')].map(a=>a.dataset.owner),current:[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].map(e=>e.textContent),footerCurrent:document.querySelectorAll('footer [aria-current]').length,schema:JSON.parse(document.querySelector('[type="application/ld+json"]').textContent),leak:/\b(CURRENT|Coming soon|APP-000|PROVISIONAL|NOT_PASS|DRAFT)\b/.test(document.body.innerText)}));
   const variant=cfg.apps.length?(cfg.grades.length?'both':'apps'):(cfg.grades.length?'grades':'neither');
   assert(scenario+'-'+width+'-conditional-semantics',semantics.h1===1&&semantics.intro===payload.intro[variant]&&semantics.plain.every(p=>p.tag==='SPAN'&&p.tabindex===null&&p.href===null)&&semantics.rfq.length===(cfg.rfq?2:0)&&semantics.rfq.every(h=>h==='/request-a-quote/')&&JSON.stringify(semantics.appCta)===JSON.stringify(cfg.apps)&&semantics.supports.length===cfg.supports.length&&!semantics.leak&&semantics.footerCurrent===0&&semantics.current.every(t=>t==='Applications')&&((semantics.schema['@graph'].find(n=>n['@type']==='ItemList')?.numberOfItems||0)===cfg.apps.length),semantics);
   await page.screenshot({path:path.join(support,scenario+'-'+width+'-default.png'),fullPage:true});
   if(width===390){assert(scenario+'-390-initial-disclosures',base.open.every(v=>v===false),base.open);await openAll(page);await geom(page,scenario+'-390-expanded-geometry');await page.screenshot({path:path.join(support,scenario+'-390-expanded.png'),fullPage:true});}
   const expected=['Home','›','Applications',payload.hero.title,payload.hero.body,payload.hero.primary,...(cfg.rfq?['Request a Quote']:[]),payload.hero.choose,...payload.groups.map(g=>g.name),payload.moduleHeadings[0],payload.intro[variant],...payload.groups.flatMap(g=>[g.name,g.scope,g.label,...g.grades,...(g.id&&cfg.apps.includes(g.id)?[g.cta]:[])]),payload.moduleHeadings[1],...payload.steps.flatMap(s=>[s.title,s.body]),...(cfg.supports.length?[payload.moduleHeadings[2],...payload.supports.filter(s=>cfg.supports.includes(s.id)).flatMap(s=>[s.name,s.body,s.cta])]:[]),...(cfg.rfq?[payload.moduleHeadings[3],...payload.final,'Request a Quote']:[])].join(' ').replace(/\s+/g,' ').trim();
   const actual=(await page.locator('main').innerText()).replace(/\s+/g,' ').trim();assert(scenario+'-'+width+'-bidirectional-full-copy',actual===expected,{expected,actual});
   if(scenario==='full'){
    await load(page,scenario);
    for(const g of payload.groups){await page.locator('.app-local-nav a[href="#'+g.anchor+'"]').click();const r=await page.locator('#'+g.anchor).evaluate(e=>({top:e.getBoundingClientRect().top,heading:e.querySelector('h3').getBoundingClientRect().top,open:e.querySelector('details').open,hash:location.hash}));assert('anchor-'+width+'-'+g.anchor,r.heading>=0&&r.heading<900&&r.hash==='#'+g.anchor&&(width!==390||!r.open),r);}
    await page.locator('.app-grades').first().locator('summary').focus();const before=await page.locator('.app-grades').first().getAttribute('open');await page.keyboard.press('Enter');const after=await page.locator('.app-grades').first().getAttribute('open');assert('keyboard-disclosure-'+width,before!==after,{before,after,aria:await page.locator('.app-grades').first().locator('summary').getAttribute('aria-labelledby')});
    await page.evaluate(()=>{window.__captured=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(a&&a.getAttribute('href')?.startsWith('/')){e.preventDefault();window.__captured.push({href:a.getAttribute('href'),text:a.innerText,search:location.search});}})});
    await page.locator('.app-rfq').last().click();const nav=await page.evaluate(()=>window.__captured.at(-1));assert('rfq-source-only-intent-'+width,nav.href==='/request-a-quote/'&&!nav.href.includes('?'),{nav,semanticSource:'APP-000',transport:'DEFERRED_TO_GATE8_RECEIVER_OWNER; local fixture does not choose transport or submit',selectionState:'No page selection controls, storage or query-prefill code'},'LOCAL_SIMULATION');
    if(width<1101){
     await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();let m=await page.evaluate(()=>({focus:document.activeElement.textContent,locked:document.body.style.overflow,background:document.querySelector('main').inert,open:!document.querySelector('.mobileNav').hidden}));assert('menu-open-'+width,m.open&&m.focus==='Home'&&m.locked==='hidden'&&m.background,m);
     await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let f=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');let last=await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement);assert('menu-focus-loop-'+width,f&&last,{tabToToggle:f,shiftToLast:last});
     await page.keyboard.press('Escape');let closed=await page.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,inert:document.querySelector('main').inert,overflow:document.body.style.overflow,focus:document.activeElement.className}));assert('menu-escape-'+width,closed.hidden&&!closed.inert&&closed.overflow===''&&closed.focus==='menuButton',closed);
     await page.locator('.menuButton').click();await page.locator('.mobileNav a').nth(3).click();closed=await page.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,inert:document.querySelector('main').inert,overflow:document.body.style.overflow,focus:document.activeElement.className}));assert('menu-link-exit-'+width,closed.hidden&&!closed.inert&&closed.overflow===''&&closed.focus==='menuButton',closed);
     await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});await page.waitForFunction(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow==='');assert('menu-desktop-breakpoint-'+width,true,'Actual resize closed overlay and restored background; waited for actual media-query event');await page.setViewportSize({width,height:900});
    }
    await page.locator('#cookie-trigger').click();const first=await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');const last=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');const loop=await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement);await geom(page,'cookie-open-'+width);await page.locator('[data-cookie-close]').click();const returned=await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement);assert('cookie-loop-exit-'+width,first&&last&&loop&&returned,{first,last,loop,returned});
   }
   await page.close();
  }
  for(const width of [1440,768,390]){
   const page=await browser.newPage({viewport:{width,height:900},javaScriptEnabled:false});await load(page,'full',false);const r=await geom(page,'no-js-'+width);assert('no-js-content-'+width,r.groups.reduce((n,g)=>n+g.grades.length,0)===30&&r.open.every(Boolean),r.groups);await page.locator('.app-grades').first().locator('summary').click();assert('no-js-native-disclosure-'+width,await page.locator('.app-grades').first().getAttribute('open')===null,'Native disclosure toggled without script');await page.close();
  }
  for(const width of [1440,768,390]){
   const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await load(page,'full');await openAll(page);await page.evaluate(()=>{const sizes=[...document.querySelectorAll('main,main *')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);for(const [e,size]of sizes)e.style.fontSize=(size*2)+'px'});await geom(page,'font-enlargement-200-'+width);await page.screenshot({path:path.join(support,'font-enlargement-'+width+'.png'),fullPage:true});await page.close();
  }
  const page=await browser.newPage({viewport:{width:720,height:450}});await load(page,'full');await openAll(page);await geom(page,'desktop-200-percent-reflow-720');await page.close();
  const result={mode:'SELF_CHECK',author:'/root/app000_gate4_author',createdAt:new Date().toISOString(),renderer:await browser.version(),source:binding.outputs.map(x=>identity(x.path)),observations,failures,status:failures.length?'PREFLIGHT_REQUIRED_REPAIR':'RUNTIME_CHECKS_PASS_PENDING_VISUAL_READ'};
  fs.writeFileSync(path.join(support,'runtime-observations.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,assertions:observations.length,failures:failures.map(f=>({id:f.id,detail:f.detail}))},null,2));if(failures.length)process.exitCode=1;
 }else if(mode==='formal'){
  const freeze=JSON.parse(fs.readFileSync(dir+'/freeze-record.json','utf8'));for(const f of freeze.files)if(hash(f.path)!==f.sha256)throw Error('Frozen source drift: '+f.path);
  fs.mkdirSync(dir+'/approval_core',{recursive:true});
  const captures=[...[1440,768,390].map(width=>({scenario:'full',width,state:'default'})),...[1440,768,390].map(width=>({scenario:'constrained',width,state:'default'})),{scenario:'full',width:390,state:'expanded'},{scenario:'mixed',width:390,state:'expanded'},{scenario:'full',width:390,state:'menu'}];
  const assets=[];
  for(const c of captures){const page=await browser.newPage({viewport:{width:c.width,height:900},deviceScaleFactor:1});await load(page,c.scenario);if(c.state==='expanded')await openAll(page);if(c.state==='menu')await page.locator('.menuButton').click();const p=dir+'/approval_core/APP-000_G4_'+c.scenario+'_'+c.width+'_'+c.state+'_V1.0.png';await capture(page,{path:p,fullPage:c.state!=='menu'});const dim=fs.readFileSync(p);assets.push({...identity(p),role:'approval_core',logicalViewport:{width:c.width,height:900},physical:{width:dim.readUInt32BE(16),height:dim.readUInt32BE(20)},scale:1,scenario:c.scenario,state:c.state,evidenceType:'STATIC_VISUAL_FROM_ACTUAL_RUNTIME'});await page.close();}
  fs.writeFileSync(dir+'/evidence-index.json',JSON.stringify({pageId:'APP-000',version:'V1.0',author:'/root/app000_gate4_author',status:'FROZEN_CANDIDATE_NOT_APPROVED',freeze:identity(dir+'/freeze-record.json'),renderer:await browser.version(),assets,diagnostic_support:support.replace(/\\/g,'/'),requiredFindings:'See author self-check; independent review remains required.'},null,2));console.log(JSON.stringify({status:'FORMAL_CAPTURES_SAVED',assets},null,2));
 }else throw Error('Unknown mode '+mode);
 }finally{await browser.close()}
})().catch(e=>{fs.writeFileSync(path.join(support,'runtime-error-'+Date.now()+'.json'),JSON.stringify({error:String(e),observations,failures},null,2));console.error(e);process.exitCode=1});
