const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='D:/23MySec',base=root+'/pages/resources/india-trade',out=base+'/04_planning/gate4-v0.1';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
fs.mkdirSync(out+'/approval_core',{recursive:true});fs.mkdirSync(out+'/diagnostic_support',{recursive:true});
let source=fs.readFileSync(base+'/04_planning/gate3-v0.1/RES-TRADE-IN_GATE3_WIREFRAME_V0.1.html','utf8');
source=source.replace("dependencies/Inter-Variable.ttf","../../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf");
const css=`
/* Gate 4 visual application; shared Chrome and body markup remain owner-derived. */
body{color:#334155}main{padding-top:40px;padding-bottom:72px}main h1,main h2,main h3,main strong{color:#062B5B}main h1{font-size:54px;line-height:1.12;letter-spacing:-1.7px;max-width:1080px;margin-bottom:30px}main h2{font-size:36px;line-height:1.2;letter-spacing:-.8px;max-width:1000px}main h3{font-size:26px;font-weight:600}main p,main li{font-size:18px;line-height:1.65}.module{padding:48px 0;border-color:#D9E2EC}.module-1{border-bottom:2px solid #D9E2EC}.module-1 p:nth-of-type(2){padding:22px 24px;border-left:4px solid #008078;background:#F5F8FB;border-radius:0 10px 10px 0}.module-1 p:nth-of-type(4),.module-1 p:nth-of-type(6){font-size:16px}.module-1 p:nth-of-type(3) a,.module-8 p:first-of-type a{border-radius:7px}.module-1 p:nth-of-type(3) a strong,.module-8 p:first-of-type a strong{color:#fff}.module-1 p:nth-of-type(5) a{border-radius:7px}main a:hover{color:#062B5B}.module-1 p:nth-of-type(3) a:hover,.module-8 p:first-of-type a:hover{background:#062B5B;border-color:#062B5B;color:#fff}.module-1 p:nth-of-type(5) a:hover{background:#F5F8FB}main th{background:#062B5B;color:#fff}main td{border-color:#D9E2EC}main tbody tr:nth-child(even){background:#F5F8FB}main table{font-variant-numeric:tabular-nums}main td:first-child{font-weight:600;color:#062B5B}.table-2 td:last-child{font-weight:600;color:#062B5B}.module-3 li::marker,.module-5 li::marker,.module-7 li::marker{color:#008078}.module-8 h3{border-top:1px solid #D9E2EC;padding-top:28px}.module-8 li{font-size:16px}.module-8>p:last-child{padding:20px 24px;background:#F5F8FB;border-radius:10px;font-size:16px}
@media(max-width:1100px){main{padding-top:32px;padding-bottom:56px}main h1{font-size:44px;letter-spacing:-1.1px}main h2{font-size:32px}.module{padding:40px 0}main p,main li{font-size:17px}main .table-2 tbody tr{padding:4px 20px;border-radius:10px;border-color:#D9E2EC}main .table-2 td::before{color:#062B5B}main .table-2 td:first-child{border-bottom:2px solid #D9E2EC}.table-2 td:last-child{font-size:18px}}
@media(max-width:600px){main{padding-top:24px;padding-bottom:44px}main h1{font-size:34px;line-height:1.16;letter-spacing:-.7px}main h2{font-size:28px;line-height:1.23;letter-spacing:-.45px}.module{padding:34px 0}main p,main li{font-size:16px;line-height:1.65}.module-1 p:nth-of-type(2){padding:18px 18px}.module-1 p:nth-of-type(3) a,.module-8 p:first-of-type a{text-align:center;justify-content:center}main table tbody tr{border-radius:10px;border-color:#D9E2EC}main table td::before{color:#062B5B}.module-8>p:last-child{padding:18px}.module-8 h3{font-size:24px}}
`;
source=source.replace('</style>',css+'</style>');
const src=out+'/RES-TRADE-IN_GATE4_COMPLETE_VISUAL_V0.1.html';fs.writeFileSync(src,source);
const inputs=[
'AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.4.md','docs/architecture/GATE_WORKFLOW_V3.2.md','docs/architecture/PAGE_GATE_1_4_STANDARD_V2.2.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.8.md','agents/gate4-complete-visual/agent.md','skills/brand-applied-visual-design/SKILL.md','skills/full-page-visual-composition/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/gate4-self-check.md','skills/layout-interaction-verification/references/core-risk-model.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CONTRACT_V1.2.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE_3_4_6_DELEGATED_CLOSURE_AUTHORITY_V1.0.md','docs/architecture/PAGE_REGISTRY_V0.2.md','research/keyword/11_page_keyword_master.csv','docs/page-playbooks/RESOURCE_PLAYBOOK_V0.1.md','docs/page-briefs/RES-TRADE-IN_INDIA_TITANIUM_DIOXIDE_TRADE_UPDATE_BRIEF_V0.1.md','docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','brand/visual/TIO2_MALAYSIA_PRIMARY_CTA_ACCESSIBILITY_ADDENDUM_V1.0.md','brand/logo/production/PRODUCTION_SVG_LOGO_MANIFEST_V1.0.md','docs/architecture/GLOBAL_HEADER_FOOTER_SPEC_V0.5.md','docs/architecture/GLOBAL_FOOTER_LEGAL_UTILITY_ADDENDUM_V1.0.md','docs/architecture/LEGAL_PRIVACY_NO_TERMS_TITAN_PATTERN_DECISION_V1.0.md','pages/legal-privacy/05_review/SHARED-CONSENT_CURRENT_GATE9_BASELINE_MANIFEST_V1.1.md','pages/legal-privacy/05_review/LEGAL_PRIVACY_CONV_DOC_POST_GATE9_CURRENT_AUTHORITY_MANIFEST_V1.3.md',
'pages/resources/india-trade/RES-TRADE-IN_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md',...['CONTENT_SKELETON_V0.1','FULL_BUYER_CLEAN_COPY_V0.2','CONTENT_CONTRACT_V0.1'].map(x=>'pages/resources/india-trade/04_planning/RES-TRADE-IN_GATE2_'+x+'.md'),'pages/resources/india-trade/04_planning/gate3-v0.1/RES-TRADE-IN_GATE3_WIREFRAME_V0.1.html','pages/resources/india-trade/04_planning/gate3-v0.1/freeze-record.json','pages/resources/india-trade/04_planning/gate3-v0.1/design-report.md','pages/resources/india-trade/05_review/RES-TRADE-IN_GATE3_TO_GATE4_HANDOFF_V0.1.md','pages/resources/india-trade/01_research/evidence/RES-TRADE-IN_GATE2_FRESH_OFFICIAL_RECHECK_2026-09-07.md','pages/resources/india-trade/05_review/RES-TRADE-IN_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md'];
const pkg=root+'/docs/architecture/gate3-shared-consumer-v0.2',shared=JSON.parse(fs.readFileSync(pkg+'/consumer-package.json'));
const data={page_id:'RES-TRADE-IN',workset_id:'RES-TRADE-IN-G4-WS-20260907-01',actual_author:'/root/gate4_india_trade_execute',dispatch_id:'G4-REMAINING-8-EXEC-01/RES-TRADE-IN',authorization:{control_id:'G4-REMAINING-8-EXEC-01',source:root+'/docs/architecture/GATE4_REMAINING_EIGHT_EXECUTION_CONTROL_V1.0.md',scope:'Gate 4 execution only; stop frozen ready for Gate 5; no review, closure, Gate 6 or development/publication',note:'Batch progress source is mutable; dispatch scope fixed by current explicit parent instruction.'},inputs:inputs.map(p=>id(root+'/'+p)),dependencies:[id(pkg+'/consumer-package.json'),...shared.files.map(f=>id(pkg+'/'+f.path)),...['primary-horizontal','reverse-monochrome'].map(n=>id(root+'/brand/logo/candidates/v0.1/tio2-malaysia-'+n+'-v0.1.svg'))],design_source:src};
fs.writeFileSync(out+'/input-index.json',JSON.stringify(data,null,2));console.log(JSON.stringify(id(src)));
