const fs=require('fs'),crypto=require('crypto');const deps='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';const {chromium}=require(deps+'/playwright');
const base='D:/23MySec/pages/resources/india-trade/04_planning/gate4-v0.1',src=base+'/RES-TRADE-IN_GATE4_COMPLETE_VISUAL_V0.1.html';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const out={mode:'INITIAL',author:'/root/gate4_india_trade_execute',sourceSha256:sha(src),browser:browser.version(),widths:[],errors:[],requests:[]};
for(const width of [1440,768,390]){const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:1});await context.route('**/*',r=>{if(r.request().url().startsWith('file:'))r.continue();else{out.requests.push(r.request().url());r.abort()}});const page=await context.newPage();page.on('pageerror',e=>out.errors.push(e.message));await page.goto('file:///'+src);await page.evaluate(()=>document.fonts.ready);const row={width,geometry:await page.evaluate(()=>{const visible=e=>!!e.getClientRects().length;const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,w:r.width,h:r.height}};return {dpr:devicePixelRatio,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,fontLoaded:document.fonts.check('18px Inter'),fontStatus:[...document.fonts].map(f=>({family:f.family,status:f.status})),images:[...document.images].map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0})),modules:[...document.querySelectorAll('main section')].map(e=>({name:e.querySelector('h1,h2').textContent,rect:rect(e)})),controls:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.textContent,rect:rect(e),href:e.getAttribute('href')})),overflow:[...document.querySelectorAll('body *')].filter(visible).filter(e=>{let r=e.getBoundingClientRect();return r.right>innerWidth+1||r.left< -1}).map(e=>({tag:e.tagName,class:e.className,rect:rect(e)})),mainText:document.querySelector('main').innerText,tableRows:[...document.querySelectorAll('main table')].map(t=>[...t.querySelectorAll('tbody tr')].map(r=>[...r.children].map(c=>c.textContent))),headerHeight:document.querySelector('.header').getBoundingClientRect().height,clipped:[...document.querySelectorAll('main p,main li,main td,main h1,main h2')].filter(e=>e.scrollHeight>e.clientHeight+2).map(e=>({text:e.textContent,rect:rect(e)}))}}),actions:[]};
if(process.argv[2]==='sample'){if(width===1440)await page.locator('.module-1').screenshot({path:base+'/diagnostic_support/4a-hero-1440.png'});if(width===390)await page.locator('.table-2 tbody tr').nth(4).screenshot({path:base+'/diagnostic_support/4a-path5-390.png'});out.widths.push(row);await context.close();continue;}
await page.locator('.module-1 p:nth-of-type(3) a').click();row.actions.push({name:'primary local route',intents:await page.evaluate(()=>window.localNavigationIntents)});
if(width<1101){await page.locator('.menuButton').click();row.actions.push({name:'menu enter',open:await page.locator('.mobileNav').isVisible(),active:await page.evaluate(()=>document.activeElement.textContent),inert:await page.locator('main').evaluate(e=>e.inert)});await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');row.actions.push({name:'menu forward trap',active:await page.evaluate(()=>document.activeElement.className)});await page.keyboard.press('Shift+Tab');row.actions.push({name:'menu reverse trap',active:await page.evaluate(()=>document.activeElement.textContent)});await page.keyboard.press('Escape');row.actions.push({name:'menu escape restore',hidden:await page.locator('.mobileNav').isHidden(),active:await page.evaluate(()=>document.activeElement.className),inert:await page.locator('main').evaluate(e=>e.inert)});await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/resources/"]').click();row.actions.push({name:'menu select close',hidden:await page.locator('.mobileNav').isHidden(),active:await page.evaluate(()=>document.activeElement.className)});await page.locator('.menuButton').click();await page.locator('.menuButton').click();row.actions.push({name:'menu button close',hidden:await page.locator('.mobileNav').isHidden()});}
await page.locator('#cookie-trigger').click();row.actions.push({name:'cookie enter',open:await page.locator('.cookie-layer').isVisible(),active:await page.evaluate(()=>document.activeElement.textContent)});await page.keyboard.press('Shift+Tab');row.actions.push({name:'cookie reverse trap',active:await page.evaluate(()=>document.activeElement.textContent)});await page.keyboard.press('Tab');row.actions.push({name:'cookie forward trap',active:await page.evaluate(()=>document.activeElement.textContent)});await page.keyboard.press('Escape');row.actions.push({name:'cookie escape restore',hidden:await page.locator('.cookie-layer').isHidden(),active:await page.evaluate(()=>document.activeElement.id)});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();row.actions.push({name:'cookie close restore',hidden:await page.locator('.cookie-layer').isHidden(),active:await page.evaluate(()=>document.activeElement.id)});
await page.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});await page.mouse.move(0,0);await page.screenshot({path:base+'/diagnostic_support/initial-'+width+'.png',fullPage:true});out.widths.push(row);await context.close();}
fs.writeFileSync(base+'/diagnostic_support/'+(process.argv[2]==='sample'?'4a-observations':'runtime-observations')+'.json',JSON.stringify(out,null,2));await browser.close();console.log(JSON.stringify(out.widths.map(r=>({width:r.width,height:r.geometry.height,overflow:r.geometry.overflow,small:r.geometry.controls.filter(c=>c.rect.w<44||c.rect.h<44),clipped:r.geometry.clipped,actions:r.actions})),null,2));})();
