const fs=require('fs'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec/',base=root+'pages/resources/uk-trade/04_planning/gate4-v0.1/',out=__dirname;
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
const identity=p=>{let b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}};
const input=json(base+'input-index.json'),freeze=json(base+'freeze-record.json'),evidence=json(base+'evidence-index.json');
const observations={reviewer:'/root/g5_trade_uk',author:input.actual_author,dispatch_id:'G5-9PAGE-REVIEW-20260907-01/RES-TRADE-UK/INITIAL',time:new Date().toISOString(),source:identity(input.design_source),bundle:freeze.freeze_id,indexes:['input-index.json','evidence-index.json','freeze-record.json','preflight-record.json'].map(p=>identity(base+p)),identity_checks:[],runtime:[],requests:[],errors:[]};
function walk(o,origin){if(!o||typeof o!=='object')return;if(o.path&&o.sha256){let a;try{a=identity(o.path);observations.identity_checks.push({origin,...a,expected_sha256:o.sha256,expected_bytes:o.bytes,match:a.sha256===o.sha256&&(o.bytes===undefined||a.bytes===o.bytes)});}catch(e){observations.identity_checks.push({origin,path:o.path,error:e.message,match:false})}}for(const v of Object.values(o))if(typeof v==='object')walk(v,origin)}
walk(input,'input-index');walk(freeze,'freeze-record');walk(evidence,'evidence-index');
observations.pngs=evidence.assets.map(a=>{let b=fs.readFileSync(a.path);return {path:a.path,width:b.readUInt32BE(16),height:b.readUInt32BE(20),match:b.readUInt32BE(16)===a.physical_width&&b.readUInt32BE(20)===a.physical_height}});
observations.methods=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.9.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE5_GATE6_ACCEPTANCE_CONTRACT_V1.0.md'].map(p=>identity(root+p));
const html=read(input.design_source),g3=read(input.gate3[0].path),norm=s=>s.replace(/\r/g,'').trim();
observations.source_relation={body_same:norm(html.split('<body>')[1])===norm(g3.split('<body>')[1]),shared_css:html.includes(read(root+'docs/architecture/gate3-shared-consumer-v0.2/shared-chrome.css').trim()),shared_script:norm(html).includes(norm(read(root+'docs/architecture/gate3-shared-consumer-v0.2/shared-chrome-behavior.js')))};
const plain=s=>s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/\*\*|`/g,'').replace(/\s+/g,' ').trim();
const b=read(input.approved_inputs.find(x=>x.role==='B').path).split('\n---\n')[1].trim(),blocks=[];
for(const part of b.split(/\n\s*\n/)){if(/^#{1,3} /.test(part)){let m=part.match(/^(#{1,3}) (.*)$/s);blocks.push({tag:'h'+m[1].length,text:plain(m[2])})}else if(part.startsWith('|'))part.split('\n').filter(l=>!/^\|[- :|]+\|$/.test(l)).forEach((r,i)=>r.split('|').slice(1,-1).forEach(t=>blocks.push({tag:i?'td':'th',text:plain(t)})));else if(part.startsWith('- '))part.split('\n').forEach(l=>blocks.push({tag:'li',text:plain(l.slice(2))}));else blocks.push({tag:'p',text:plain(part)})}
const expectedLinks=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:plain(m[1]),href:m[2]}));
let browser;
(async()=>{browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});observations.browser=await browser.version();
for(const width of [1440,768,390]){const ctx=await browser.newContext({viewport:{width,height:width===390?844:900},deviceScaleFactor:1});await ctx.route(/^https?:/,r=>{observations.requests.push(r.request().url());return r.abort()});const p=await ctx.newPage();p.on('pageerror',e=>observations.errors.push(e.message));await p.goto('file:///'+input.design_source);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(x=>x.decode()))});
const r={width,dpr:await p.evaluate(()=>devicePixelRatio),checks:{}};observations.runtime.push(r);const check=(n,v)=>r.checks[n]=v;
const actual=await p.locator('main').evaluate(e=>[...e.querySelectorAll('h1,h2,h3,p,li,th,td')].map(x=>({tag:x.tagName.toLowerCase(),text:x.textContent.replace(/\s+/g,' ').trim()})));
check('full_ordered_copy',JSON.stringify(actual)===JSON.stringify(blocks));r.block_count=actual.length;
r.links=await p.locator('main a').evaluateAll(es=>es.map(e=>({text:e.textContent.trim(),href:e.getAttribute('href')})));check('all_body_targets',JSON.stringify(r.links)===JSON.stringify(expectedLinks));
r.geometry=await p.evaluate(()=>{let vis=e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0;return {width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,header:document.querySelector('header').offsetHeight,font:document.fonts.check('16px Inter'),footerBottom:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,targets:[...document.querySelectorAll('a,button')].filter(vis).map(e=>({label:e.textContent.trim(),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})),overflow:[...document.querySelectorAll('main *')].filter(e=>!e.closest('thead')&&vis(e)&&(e.scrollWidth>e.clientWidth+1||e.getBoundingClientRect().left<0||e.getBoundingClientRect().right>innerWidth+1)).map(e=>e.outerHTML.slice(0,200)),clips:[...document.querySelectorAll('main *')].filter(e=>!e.closest('thead')&&vis(e)&&(['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis')).map(e=>e.tagName),tables:[...document.querySelectorAll('table')].map(t=>({rows:t.tBodies[0].rows.length,cells:[...t.querySelectorAll('td')].map(e=>({label:e.dataset.label,header:document.getElementById(e.getAttribute('headers')).textContent,before:getComputedStyle(e,'::before').content,display:getComputedStyle(e).display}))})),modules:[...document.querySelectorAll('main section')].map(e=>({title:e.querySelector('h1,h2').textContent,top:e.getBoundingClientRect().top+scrollY,bottom:e.getBoundingClientRect().bottom+scrollY})),nav:[...document.querySelectorAll('header nav')].map(e=>({name:e.ariaLabel,display:getComputedStyle(e).display,current:[...e.querySelectorAll('[aria-current]')].map(a=>a.textContent)}))}});
check('geometry',r.geometry.width===width&&r.geometry.header===(width===1440?84:64)&&Math.abs(r.geometry.height-r.geometry.footerBottom)<2&&!r.geometry.overflow.length&&!r.geometry.clips.length&&r.geometry.font);check('all_targets_44',r.geometry.targets.every(t=>t.width>=44&&t.height>=44));check('table_relations',r.geometry.tables.every(t=>t.cells.every(c=>c.label===c.header&&(width!==390||c.before==='"'+c.label+'"'))));check('capture_extent',r.geometry.height===evidence.assets.find(a=>a.logical_width===width&&a.state==='full').physical_height);
// Every body target exercised; prototype intercepts navigation. No receiver is claimed.
r.intents=[];for(let i=0;i<expectedLinks.length;i++){await p.locator('main a').nth(i).click();r.intents.push(await p.evaluate(()=>localNavigationIntents.at(-1)))}check('body_intents',r.intents.every((v,i)=>v.href===expectedLinks[i].href&&Object.keys(v.context).length===0));
await p.locator('main a').first().focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');r.focus=await p.locator('main a').first().evaluate(e=>({active:e===document.activeElement,outline:getComputedStyle(e).outlineWidth,color:getComputedStyle(e).outlineColor}));check('keyboard_focus',r.focus.active&&r.focus.outline==='3px');r.normal=await p.locator('main a').first().evaluate(e=>({fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));await p.locator('main a').first().hover();r.hover=await p.locator('main a').first().evaluate(e=>({fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));check('hover',r.hover.bg==='rgb(6, 43, 91)');
const restored=()=>p.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.body.style.overflow===''&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert));
if(width<1101){await p.locator('.menuButton').focus();await p.keyboard.press('Enter');check('menu_enter',await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));check('menu_isolation',await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert)));await p.locator('main a').first().evaluate(e=>e.focus());check('background_focus_blocked',await p.evaluate(()=>document.activeElement.closest('.mobileNav')!==null));await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');check('menu_forward_loop',await p.locator('.menuButton').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check('menu_reverse_loop',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check('menu_escape_return',await restored()&&await p.locator('.menuButton').evaluate(e=>e===document.activeElement));await p.locator('.menuButton').click();await p.locator('.menuButton').click();check('menu_close',await restored());r.menuTargets=await p.locator('.mobileNav a').evaluateAll(es=>es.map(e=>({text:e.textContent,href:e.getAttribute('href')})));let select=[];for(let i=0;i<8;i++){await p.locator('.menuButton').click();await p.locator('.mobileNav a').nth(i).focus();await p.keyboard.press('Enter');select.push(await restored()&&await p.evaluate(h=>localNavigationIntents.at(-1).href===h,r.menuTargets[i].href))}check('all_menu_selections',select.every(Boolean));await p.locator('.menuButton').click();await p.setViewportSize({width:1200,height:900});check('breakpoint_restore',await restored());await p.setViewportSize({width,height:width===390?844:900});}
await p.locator('#cookie-trigger').focus();await p.keyboard.press('Enter');check('cookie_enter',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('main a').first().evaluate(e=>e.focus());check('cookie_background_focus_blocked',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check('cookie_reverse_loop',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check('cookie_forward_loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));check('cookie_targets_44',await p.locator('.cookie-actions>*').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)));await p.locator('.cookie-layer a').click();check('cookie_policy_intent',await p.evaluate(()=>localNavigationIntents.at(-1).href==='/cookie-policy/'));await p.locator('[data-cookie-close]').click();await p.waitForTimeout(50);check('cookie_close_return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');await p.waitForTimeout(50);check('cookie_escape_return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await p.locator('dialog').evaluate(e=>e.open));await ctx.close();}
const z=await browser.newPage({viewport:{width:720,height:450},deviceScaleFactor:2});await z.goto('file:///'+input.design_source);observations.zoomEquivalent=await z.evaluate(()=>({cssWidth:innerWidth,dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth}));await z.close();await browser.close();
observations.source_after=identity(input.design_source);observations.failures=observations.runtime.flatMap(r=>Object.entries(r.checks).filter(([k,v])=>!v).map(([k])=>`${r.width}: ${k}`));fs.writeFileSync(out+'/observations.json',JSON.stringify(observations,null,2));console.log(JSON.stringify({failures:observations.failures,identity_mismatches:observations.identity_checks.filter(x=>!x.match),source_relation:observations.source_relation,requests:observations.requests,errors:observations.errors,heights:observations.runtime.map(r=>[r.width,r.geometry.height])},null,2));
})().catch(async e=>{observations.error=e.stack;fs.writeFileSync(out+'/observations-failed.json',JSON.stringify(observations,null,2));if(browser)await browser.close();console.error(e);process.exitCode=1});
