// TARGETED SELF_CHECK for R01. Catches wrapping, clipping, geometry/semantics regressions.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,prior=path.resolve(dir,'../d32-gate4-v0.1'),red=process.argv.includes('--red'),probe12=process.argv.includes('--probe12'),source=path.join(red?prior:dir,'market-visual.html');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),checks=[],rows=[],check=(id,pass,detail)=>checks.push({id,pass:!!pass,detail});
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({deviceScaleFactor:1}),old=await browser.newPage({deviceScaleFactor:1});
const snapshot=()=>{const e=document.querySelector('.rootHero .heroText>.eyebrow'),h=document.querySelector('h1'),c=getComputedStyle(e),hc=getComputedStyle(h),r=document.createRange();r.selectNodeContents(e);const rects=[...r.getClientRects()].filter(x=>x.width);const b=e.getBoundingClientRect(),hero=document.querySelector('.rootHero');return {text:e.textContent,font:c.fontSize,weight:c.fontWeight,spacing:c.letterSpacing,transform:c.textTransform,color:c.color,lines:new Set(rects.map(x=>Math.round(x.y))).size,textWidth:Math.max(...rects.map(x=>x.width)),boxWidth:b.width,contained:rects.every(x=>x.left>=b.left-.1&&x.right<=b.right+.1),h1:hc.fontSize,h1Lines:Math.round(h.getBoundingClientRect().height/parseFloat(hc.lineHeight)),padding:getComputedStyle(hero).padding,overflow:document.documentElement.scrollWidth-innerWidth,body:document.querySelector('main').innerText,links:[...document.querySelectorAll('a')].map(x=>[x.textContent,x.getAttribute('href')]),boxes:[...document.querySelectorAll('header,.rootHero,main .section,footer')].map(x=>{let q=x.getBoundingClientRect();return [q.x,q.y,q.width,q.height]}),small:[...document.querySelectorAll('a,button')].filter(x=>x.getClientRects().length).filter(x=>{let b=x.getBoundingClientRect();return b.width<44||b.height<44}).map(x=>x.textContent),loaded:document.fonts.check('12px Inter')&&[...document.images].every(x=>x.complete&&x.naturalWidth)};};
for(const width of [320,340,341,374,375,390,768,1024,1440]){for(const p of [page,old]){await p.setViewportSize({width,height:1000});await p.goto(pathToFileURL(p===page?source:path.join(prior,'market-visual.html')).href);await p.evaluate(()=>document.fonts.ready);if(probe12&&p===page)await p.addStyleTag({content:'@media(max-width:340px){.rootHero .heroText>.eyebrow{font-size:12px!important}}'});await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}const a=await page.evaluate(snapshot),b=await old.evaluate(snapshot);rows.push({width,current:a,prior:b});
check(width+':eyebrow one line',a.lines===1,a);check(width+':complete text contained',a.contained&&a.text==='Destination market navigation');check(width+':approved typography',a.font===(width<=340?'11px':width<=374?'12px':b.font)&&a.weight==='700'&&a.transform==='uppercase'&&a.color===b.color&&Math.abs(parseFloat(a.spacing)/parseFloat(a.font)-.08)<.0001);check(width+':H1 unchanged',a.h1===b.h1&&a.h1Lines===b.h1Lines&&(width!==1024||a.h1Lines===2)&&(width!==320||a.h1Lines===3));check(width+':padding unchanged',a.padding===b.padding);check(width+':copy and action ownership unchanged',a.body===b.body&&JSON.stringify(a.links)===JSON.stringify(b.links));check(width+':no overflow and targets loaded',a.overflow===0&&!a.small.length&&a.loaded);if(width>374)check(width+':whole page geometry unchanged',JSON.stringify(a.boxes)===JSON.stringify(b.boxes));
await page.locator('.primary').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');check(width+':primary focus',await page.locator('.primary').evaluate(e=>e.matches(':focus-visible')&&getComputedStyle(e).outlineStyle!=='none'));await page.locator('.primary').hover();check(width+':hover preserved',await page.locator('.primary').evaluate(e=>getComputedStyle(e).backgroundColor==='rgb(0, 108, 102)'));
}
const original=fs.readFileSync(path.join(prior,'market-visual.html'),'utf8'),actual=fs.readFileSync(source,'utf8');check('markup unchanged except stylesheet bindings',red||actual.replace('href="../d32-gate4-v0.1/visual.css"','href="visual.css"').replace('<link rel="stylesheet" href="root-narrow-projection.css">','')===original);
const result={time:new Date().toISOString(),mode:probe12?'DIAGNOSTIC_12PX_HYPOTHESIS_NO_FILE_MUTATION':red?'EXPECTED_RED':'TARGETED_SELF_CHECK',source:source,sha256:sha(source),renderer:await browser.version(),dpr:1,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks,rows};fs.mkdirSync(path.join(dir,'diagnostic_support'),{recursive:true});fs.writeFileSync(path.join(dir,'diagnostic_support',probe12?'narrow-12px-probe.json':red?'narrow-red.json':'narrow-green.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>!x.pass).map(x=>x.id),eyebrows:rows.map(x=>({width:x.width,font:x.current.font,lines:x.current.lines,textWidth:x.current.textWidth,box:x.current.boxWidth}))}));await browser.close();process.exitCode=result.failed?1:0;})();
