const fs=require('fs'),path=require('path'),crypto=require('crypto');const dir=__dirname,root=path.resolve(dir,'../../../..'),prior=path.resolve(dir,'../d32-gate4-v0.1'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),id=p=>{p=path.resolve(dir,p);return {path:p,bytes:fs.statSync(p).size,sha256:hash(p)};},write=(n,x)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(x,null,2));
const read=p=>JSON.parse(fs.readFileSync(p)),unique=xs=>[...new Map(xs.map(x=>[x.path,x])).values()],check=xs=>{for(const x of xs)if(hash(x.path)!==x.sha256)throw Error('Identity changed '+x.path)};
const old=read(path.join(prior,'freeze.json'));if(old.bundle_id!=='f4fa1c2048b5da913b325f22ad8a5b0beefe9058539a52b90af2357e60e6619f')throw Error('Wrong prior bundle');check([...old.files,old.evidence_index]);
if(process.argv[2]==='prepare'){
if(fs.existsSync(path.join(dir,'source-lock.json')))throw Error('Already source-locked');
for(const f of ['narrow-green.json','adjacent.json'])if(read(path.join(dir,'diagnostic_support',f)).failed)throw Error('Not green');
const newInputs=['docs/architecture/ROOT_PAGE_NARROW_VISUAL_AND_DOC_FEEDBACK_DECISION_V1.0.md','docs/architecture/STATIC_NEXTJS_SINGLE_SITE_AND_GOOGLE_INDEXING_DECISION_V1.0.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.11.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.1.md','pages/markets/05_review/MARKET-000_D32_GATE5_INDEPENDENT_REVIEW_V0.1.md'].map(x=>id(path.join(root,x)));
write('input-index.json',{workset_id:'MARKET-000-D32-G4-V0.2-R01',priorBundle:old.bundle_id,priorFreeze:id(path.join(prior,'freeze.json')),priorInputIndex:id(path.join(prior,'input-index.json')),newInputs,authority:'ROOT-NARROW-VISUAL-20260921 plus /root common-token/boundary messages 2026-09-21; page facts unchanged; historical method migration remains resolved by Gate5 review',controllerToken:'<=340 11px;341–374 12px;>=375 existing approved value;700/.08em;full text/color/geometry preserved'});
const local=['market-visual.html','root-narrow-projection.css','build.cjs','narrow-check.cjs','adjacent-check.cjs','four-page-probe.cjs','capture.cjs','pack.cjs'].map(id),deps=read(path.join(prior,'source-lock.json')).files.filter(x=>/planning\.(css|js)$|visual\.css$|\.ttf$|\.svg$|shared/.test(x.path));check(deps);
write('preflight.json',{status:'PASS_FOR_TARGETED_FORMAL_RENDER',mode:'TARGETED_SELF_CHECK',passed:95,failed:0,priorCoverage:'Gate5 V0.1 retained except MARKET-D32-G5-R01; prior 143 runtime and independent full content/operations/family/17 formal+26 readable inspection',evidence:['diagnostic_support/narrow-green.json','diagnostic_support/adjacent.json'].map(id),newInputs,source_identity:local[0].sha256,unchangedEvidenceScope:'>=375 exact content/action/layout comparison; immutable prior CSS/JS/Chrome; <=374 only Hero eyebrow type size and natural flow height',newFormalScope:['FULL_320','COOKIE_320','HERO_320','HERO_340','HERO_341','HERO_374','HERO_375']});
write('source-lock.json',{status:'SOURCE_LOCKED_FOR_TARGETED_FORMAL_RENDER',time:new Date().toISOString(),source_identity:local[0].sha256,files:unique([...local,...deps,...newInputs,id('input-index.json'),id('preflight.json')])});console.log('TARGETED SOURCE LOCKED');
}else if(process.argv[2]==='complete'){
if(fs.existsSync(path.join(dir,'freeze.json')))throw Error('Already frozen');const lock=read(path.join(dir,'source-lock.json'));check(lock.files);const fresh=read(path.join(dir,'approval_core/new-assets.json')).assets;check(fresh);const inherited=read(path.join(prior,'approval_core/asset-index.json')).assets.filter(x=>x.logical_width!==320).map(x=>({...x,inheritance:'Unchanged at >=375; exact prior identity and current geometry/content/style equality; not recaptured'}));check(inherited);
write('approval_core/asset-index.json',{source_identity:lock.source_identity,new_count:fresh.length,inherited_count:inherited.length,assets:[...inherited,...fresh]});
const files=unique([...lock.files,id('source-lock.json'),id('approval_core/asset-index.json'),id('approval_core/new-assets.json'),...fresh.map(x=>id(x.path)),...inherited.map(x=>id(x.path)),id('response.md'),id('../../05_review/MARKET-000_D32_GATE4_GATE5_HANDOFF_V0.2.md'),...['narrow-red.json','narrow-12px-probe.json','narrow-green.json','adjacent.json','four-page-probe.json'].map(x=>id('diagnostic_support/'+x)),id(path.join(prior,'freeze.json')),old.evidence_index]);check(files);
const aggregate=xs=>crypto.createHash('sha256').update(xs.map(x=>({relativePath:path.relative(root,x.path).replaceAll('\\','/'),sha256:x.sha256})).sort((a,b)=>a.relativePath.localeCompare(b.relativePath)).map(x=>x.relativePath+'\0'+x.sha256+'\n').join('')).digest('hex'),bundle=aggregate(files);
write('evidence-index.json',{workset_id:'MARKET-000-D32-G4-V0.2-R01',status:'CHANGES_READY_FOR_TARGETED_REVIEW',bundle_id:bundle,source_identity:lock.source_identity,formal_asset_index:id('approval_core/asset-index.json'),response:id('response.md'),priorReview:id(path.join(root,'pages/markets/05_review/MARKET-000_D32_GATE5_INDEPENDENT_REVIEW_V0.1.md')),finding:'MARKET-D32-G5-R01 AUTHOR_RESPONSE_COMPLETE; independent closure pending',newFormal:fresh,inheritedFormal:inherited});
write('freeze.json',{time:new Date().toISOString(),status:'CHANGES_READY_FOR_TARGETED_REVIEW / DRAFT_FOR_PROJECT_CONTROL_REVIEW',bundle_id:bundle,source_identity:lock.source_identity,prior_bundle:old.bundle_id,algorithm:'SHA256 sorted D23-relative path + NUL + SHA256 + LF; evidence-index separately bound non-circular',files,evidence_index:id('evidence-index.json')});console.log(JSON.stringify({bundle,html:lock.source_identity,new:fresh.length,inherited:inherited.length,files:files.length}));
}else throw Error('prepare or complete');
