const fs=require('fs'),crypto=require('crypto'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/resources/uk-trade/04_planning/gate4-v0.1',source=out+'/RES-TRADE-UK_GATE4_COMPLETE_VISUAL_V0.1.html';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const ready=async p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
let browser,results=[],requests=[];const check=(name,ok,details)=>{results.push({name,ok,details});if(!ok)throw Error(name)};
const bpath=out+'/../RES-TRADE-UK_GATE2_FULL_BUYER_CLEAN_COPY_V0.3.md';
const plain=s=>s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/\*\*|`/g,'').replace(/\s+/g,' ').trim();
const b=fs.readFileSync(bpath,'utf8').split('\n---\n')[1].trim();let blocks=[];
for(const v of b.split(/\n\s*\n/)){if(/^#{1,3} /.test(v)){let m=v.match(/^(#{1,3}) (.*)$/s);blocks.push({tag:'h'+m[1].length,text:plain(m[2])})}else if(v.startsWith('|')){let rows=v.split('\n').filter(l=>!/^\|[- :|]+\|$/.test(l));rows.forEach((r,j)=>r.split('|').slice(1,-1).forEach(t=>blocks.push({tag:j===0?'th':'td',text:plain(t)})))}else if(v.startsWith('- ')){v.split('\n').forEach(l=>blocks.push({tag:'li',text:plain(l.slice(2))}))}else blocks.push({tag:'p',text:plain(v)})}
const links=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:plain(m[1]),href:m[2]}));
async function restore(p){return p.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.body.style.overflow===''&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert))}
async function main(){browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const mode=process.argv[2]||'initial';
if(mode==='inspect'){const w=Number(process.argv[3]),start=Number(process.argv[4]),count=Number(process.argv[5]);const p=await browser.newPage({viewport:{width:w,height:950},deviceScaleFactor:1});await p.goto('file:///'+source);await ready(p);const height=await p.evaluate(()=>document.documentElement.scrollHeight);for(let i=start;i<start+count&&i*850<height;i++){await p.evaluate(y=>scrollTo(0,y),i*850);const y=await p.evaluate(()=>scrollY);console.log(JSON.stringify({width:w,y,height,image:(await p.screenshot({animations:'disabled'})).toString('base64')}))}await browser.close();return}
if(mode==='formal'){const pre=JSON.parse(fs.readFileSync(out+'/preflight-record.json'));check('preflight binding',pre.status==='PASS_FOR_FORMAL_RENDER'&&pre.source.sha256===id(source).sha256);const assets=[];for(const w of [1440,768,390]){const h=w===390?844:900,p=await browser.newPage({viewport:{width:w,height:h},deviceScaleFactor:1});await p.goto('file:///'+source);await ready(p);await p.mouse.move(0,0);async function shot(state,fullPage){const path=out+'/approval_core/RES-TRADE-UK_G4_'+w+'-'+state+'.png';await p.screenshot({path,fullPage,animations:'disabled'});const buf=fs.readFileSync(path);assets.push({...id(path),role:state==='full'?'complete-page':'key-state',evidence_type:'STATIC_VISUAL',logical_width:w,logical_height:h,dpr:1,physical_width:buf.readUInt32BE(16),physical_height:buf.readUInt32BE(20),state,source_sha256:id(source).sha256})}await shot('full',true);if(w<1101){await p.locator('.menuButton').click();await shot('menu',false);await p.keyboard.press('Escape')}await p.locator('#cookie-trigger').click();await shot('cookie',false);await p.close()}fs.writeFileSync(out+'/evidence-index.json',JSON.stringify({workset_id:'RES-TRADE-UK-G4-WORKSET-01',source:id(source),browser:await browser.version(),assets,diagnostic_support:['diagnostic_support/runtime.json','diagnostic_support/4a-1440.png','diagnostic_support/4a-390.png'],capture_check:'PENDING'},null,2));await browser.close();console.log(JSON.stringify({formal_assets:assets.length}));return}
for(const w of [1440,768,390]){const context=await browser.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1});await context.route(/^https?:/,r=>{requests.push(r.request().url());return r.abort()});const p=await context.newPage();await p.goto('file:///'+source);await ready(p);
const actual=await p.locator('main').evaluate(e=>[...e.querySelectorAll('h1,h2,h3,p,li,th,td')].map(n=>({tag:n.tagName.toLowerCase(),text:n.textContent.replace(/\s+/g,' ').trim()})));check(w+' approved B ordered equality',JSON.stringify(actual)===JSON.stringify(blocks),{blocks:actual.length});check(w+' approved B links',JSON.stringify(await p.locator('main a').evaluateAll(es=>es.map(e=>({text:e.textContent,href:e.getAttribute('href')}))))===JSON.stringify(links));
const geometry=await p.evaluate(()=>{const visible=e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0;return {width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,footer:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,header:document.querySelector('header').getBoundingClientRect().height,font:document.fonts.check('16px Inter'),targets:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),overflow:[...document.querySelectorAll('main *')].filter(e=>!e.closest('thead')&&visible(e)&&(e.scrollWidth>e.clientWidth+1||e.getBoundingClientRect().left<0||e.getBoundingClientRect().right>innerWidth)).map(e=>({tag:e.tagName,text:e.textContent.slice(0,100)})),clipping:[...document.querySelectorAll('main *')].filter(e=>!e.closest('thead')&&(['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis')).map(e=>e.tagName),cells:[...document.querySelectorAll('td')].map(e=>({label:e.dataset.label,header:document.getElementById(e.getAttribute('headers')).textContent,display:getComputedStyle(e).display,before:getComputedStyle(e,'::before').content})),modules:[...document.querySelectorAll('main section')].map(e=>({title:e.querySelector('h1,h2').textContent,top:e.getBoundingClientRect().top+scrollY,bottom:e.getBoundingClientRect().bottom+scrollY}))}});
check(w+' geometry',geometry.width===w&&Math.abs(geometry.footer-geometry.height)<2&&geometry.header===(w===1440?84:64)&&geometry.font,geometry);check(w+' 44 by 44',geometry.targets.every(t=>t.w>=44&&t.h>=44));check(w+' no clipped body',!geometry.overflow.length&&!geometry.clipping.length);check(w+' table associations',geometry.cells.every(c=>c.label===c.header&&(w===390?c.display==='block'&&c.before==='"'+c.label+'"':c.display==='table-cell')));
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();check(w+' local intent '+i,await p.evaluate(href=>localNavigationIntents.at(-1).href===href&&Object.keys(localNavigationIntents.at(-1).context).length===0,links[i].href))}
await p.locator('main a').first().focus();check(w+' focus visible',await p.locator('main a').first().evaluate(e=>getComputedStyle(e).outlineWidth==='3px'));await p.locator('main a').first().hover();check(w+' primary hover',await p.locator('main a').first().evaluate(e=>getComputedStyle(e).backgroundColor==='rgb(6, 43, 91)'));
if(w<1101){const menu=p.locator('.mobileNav'),toggle=p.locator('.menuButton');await toggle.click();check(w+' menu enter and isolation',await p.evaluate(()=>document.activeElement.textContent==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'));await menu.locator('a').last().focus();await p.keyboard.press('Tab');check(w+' menu forward trap',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(w+' menu reverse trap',await menu.locator('a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(w+' menu escape return',await restore(p)&&await toggle.evaluate(e=>e===document.activeElement));await toggle.click();await toggle.click();check(w+' menu close',await restore(p));for(let i=0;i<8;i++){await toggle.click();const href=await menu.locator('a').nth(i).getAttribute('href');await menu.locator('a').nth(i).click();check(w+' menu selection '+i,await restore(p)&&await p.evaluate(h=>localNavigationIntents.at(-1).href===h,href))}await toggle.click();await p.setViewportSize({width:1200,height:900});check(w+' breakpoint restore',await restore(p));await p.setViewportSize({width:w,height:w===390?844:900})}
await p.locator('#cookie-trigger').click();check(w+' Cookie enter',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(w+' Cookie reverse',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(w+' Cookie forward',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));check(w+' Cookie targets',await p.locator('.cookie-actions>*').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)));await p.locator('[data-cookie-close]').click();check(w+' Cookie close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');check(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!(await p.locator('dialog').evaluate(e=>e.open)));await context.close()}
const lum=h=>{const a=h.match(/\w\w/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};const colors=[['008078','ffffff'],['008078','f5f8fb'],['062b5b','ffffff'],['334155','f5f8fb'],['ffffff','031b3a']].map(([a,b])=>({fg:a,bg:b,ratio:(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05)}));check('text and focus color pairs',colors.every(c=>c.ratio>=4.5),colors);
const zoom=await browser.newPage({viewport:{width:720,height:450},deviceScaleFactor:2});await zoom.goto('file:///'+source);await ready(zoom);check('200 percent equivalent layout',await zoom.evaluate(()=>document.documentElement.scrollWidth===720&&[...document.querySelectorAll('main td')].every(e=>e.scrollWidth<=e.clientWidth+1)),{method:'1440x900 physical area at 200% equivalent: 720x450 CSS viewport, DPR2. Browser zoom UI and physical device untested.'});await zoom.close();check('no external requests',requests.length===0,requests);
const record={workset_id:'RES-TRADE-UK-G4-WORKSET-01',actual_author:'/root/gate4_uk_trade_execute',mode:'SELF_CHECK INITIAL',source:id(source),copy:id(bpath),browser:await browser.version(),viewports:[1440,768,390],dpr:1,results,requests,evidence_types:['ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION'],status:'RUNTIME_PASS_PENDING_VISUAL_READBACK',time:new Date().toISOString()};fs.writeFileSync(out+'/diagnostic_support/runtime.json',JSON.stringify(record,null,2));await browser.close();console.log(JSON.stringify({status:record.status,checks:results.length,source:record.source}));}
main().catch(async e=>{fs.writeFileSync(out+'/diagnostic_support/failure-'+Date.now()+'.json',JSON.stringify({error:e.stack,results},null,2));if(browser)await browser.close();console.error(e);process.exitCode=1});
