const fs=require('fs'),c=require('crypto'),d='D:/23MySec/pages/resources/uk-trade/04_planning/gate4-v0.1',review=d+'/../../05_review';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:c.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const inputs=JSON.parse(fs.readFileSync(d+'/input-index.json')),pre=JSON.parse(fs.readFileSync(d+'/preflight-record.json')),e=JSON.parse(fs.readFileSync(d+'/evidence-index.json')),runtime=JSON.parse(fs.readFileSync(d+'/diagnostic_support/runtime.json'));
let checks=[];function check(name,ok){checks.push({name,ok});if(!ok)throw Error(name)}
function verify(x){const a=id(x.path);check(x.path,a.bytes===x.bytes&&a.sha256===x.sha256)}
for(const a of [inputs.authority_manifest,...inputs.approved_inputs,...inputs.gate3,...inputs.authorities,inputs.shared_consumer,...inputs.shared_files,...inputs.dependencies,pre.source,pre.input_index,pre.runtime,pre.design_report])verify(a);
for(const a of e.assets){verify(a);const b=fs.readFileSync(a.path);check(a.path+' dimensions',b.readUInt32BE(16)===a.physical_width&&b.readUInt32BE(20)===a.physical_height&&a.logical_width===a.physical_width&&a.dpr===1);check(a.path+' frozen source',a.source_sha256===pre.source.sha256)}
check('three full pages',e.assets.filter(a=>a.state==='full').length===3);check('five states',e.assets.filter(a=>a.state!=='full').length===5);
const old=fs.readFileSync(inputs.gate3[0].path,'utf8'),now=fs.readFileSync(pre.source.path,'utf8');check('approved body and shared behavior unchanged',old.slice(old.indexOf('<body>'))===now.slice(now.indexOf('<body>')));check('original shared style retained',now.includes(old.match(/<style>([\s\S]*?)<\/style>/)[1]));check('runtime required checks',runtime.results.every(x=>x.ok));
e.capture_check={status:'PASS',actual_author:'/root/gate4_uk_trade_execute',scope:'CAPTURE_CHECK only; no repeated content/interaction/geometry run',full_overviews_opened:3,readable_saved_asset_windows:{1440:[0,1750,3500,5250],768:[0,1750,3500,5250,7000],390:[0,1750,3500,5250,7000,8750,10500]},window_height:1850,window_overlap:100,key_states_opened:5,findings:[],observation:'All formal PNGs opened. Full images first opened for capture extent; display downscaling then addressed with in-memory native crops of existing assets. No duplicate screenshots or crop files saved. Font, state, focus, Footer extent and image/source correspondence match INITIAL.'};
e.diagnostic_support=[...['4a-1440.png','4a-390.png'].map(n=>({...id(d+'/diagnostic_support/'+n),role:'4A-risk-sample',evidence_type:'STATIC_VISUAL'})),{...id(d+'/diagnostic_support/runtime.json'),role:'INITIAL-observations',evidence_type:'ACTUAL_RUNTIME / SOURCE_INSPECTION / LOCAL_SIMULATION'}];
e.findings=[];save(d+'/evidence-index.json',e);const eid=id(d+'/evidence-index.json');
const self=review+'/RES-TRADE-UK_GATE4_EXECUTION_SELF_CHECK_V0.1.md',handoff=review+'/RES-TRADE-UK_GATE4_TO_GATE5_HANDOFF_V0.1.md';
save(self,`# RES-TRADE-UK Gate 4 Execution Self-check V0.1

Date: 2026-09-07. Workset: RES-TRADE-UK-G4-WORKSET-01. Actual author: /root/gate4_uk_trade_execute. Mode: SELF_CHECK INITIAL + CAPTURE_CHECK. Status: GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW. This is execution self-check only; independent review and Gate closure have not been performed.

Source: ${pre.source.path}; ${pre.source.bytes} bytes; SHA-256 ${pre.source.sha256}.
Evidence index: ${eid.path}; ${eid.bytes} bytes; SHA-256 ${eid.sha256}.
Freeze ID: RES-TRADE-UK-G4-FREEZE-01, in ../04_planning/gate4-v0.1/freeze-record.json.

One complete self-check covered all 87 ordered B blocks and 11 body links, 7 modules, 3 tables with 4/3/4 data rows, 5 cumulative scope items and 8 shipment inputs. Actual browser checks: ${runtime.results.length}, failures 0. Chrome ${runtime.browser}; logical 1440×900, 768×900 and 390×844; DPR1; loaded Inter and original production SVGs. Source-derived body and shared markup/behavior are exactly equal to the approved Gate 3 body; only page visual CSS changed. Current input identity was freshly checked during finalization.

STATIC_VISUAL: complete pages were read to Footer through 30 overlapping in-memory native viewports. Formal assets were opened as overviews then read through 16 native asset windows, with all 5 key states separately opened. Status and timeline rows preserve their labels, source boundaries and conditional meanings on mobile. All code/CAS/date values remain visible. No cropped text, collision or unexplained blank area was observed. The only durable diagnostic images are the two 4A risk samples; no full diagnostic or segment image set was created.

ACTUAL_RUNTIME: body/viewport geometry, 44×44 targets, Inter loading, table associations, visible focus and main-CTA hover; Menu enter/forward/reverse loop/Escape/Close/select/breakpoint and background inert restoration; Cookie open/focus loops/Close/Escape/return. All checks passed. 200% equivalent layout geometry uses 720×450 CSS at DPR2; actual browser zoom UI is not claimed. Pure color pairs meet 4.5:1. Main links are teal on white/light, primary white on functional teal, outlined official link Navy on white. No document icon, status color or imagery suggests a duty outcome.

LOCAL_SIMULATION: 11 body href intents and mobile menu destinations were exercised with navigation intercepted. No submission exists and no external requests were made. These observations do not prove a destination is live or receives data.

Findings: 0 unresolved required findings; no source revision after initial composition. N/A: form, FAQ, calculator, error, selection and submission-result states because approved A/B/C contain none. All 8 formal PNGs are approval_core (3 complete, 2 menu, 3 Cookie); full byte/dimension identities are in the single evidence index.

Critical boundaries preserved: investigation is not a finding; registration is not a rate; written rutile/80%/CAS/PRC scope and 8A60/8A61; conditional up-to-90-day retrospective wording; indicative timetable and separate evidence periods; GB/NI and at-risk context; Malaysia-origin does not determine customs treatment. UK procurement remains primary, TRA secondary, Product/RFQ supporting. All source labels and the approved 7 September 2026 review date persist.

Unverified: new official legal refresh, official link uptime/currentness, production routes/receivers/receipt, real Cookie storage/network, production SEO/Schema/scope, physical devices, browser zoom UI, other browsers and screen-reader speech. Resource owner must recheck law before implementation/publication within 30 days or two business days of relevant events. Production and real receiver checks belong to Gate 8/9 and the corresponding shared/page owners. Gate 5 review remains separate; Gate 6–10 and publishing are outside this execution.
`);
save(handoff,`# RES-TRADE-UK Gate 4 → Gate 5 Handoff V0.1

Status: GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW. Compatible handoff state: COMPLETE_VISUAL_FROZEN / READY_FOR_REVIEW. Lifecycle submission: DRAFT_FOR_PROJECT_CONTROL_REVIEW. review_stage: GATE5_INDEPENDENT_VISUAL_REVIEW. Authority and execution_dispatch_id: G4-REMAINING-8-EXEC-01. This handoff follows the active GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md and current Gate4 baseline V1.8. Gate 5 is the single final independent visual review performed in a separate task; no approval round is added.

Page: RES-TRADE-UK; /resources/uk-titanium-dioxide-anti-dumping-investigation/; EN; site_scope=tio2-my. Workset: RES-TRADE-UK-G4-WORKSET-01. bundle_id: RES-TRADE-UK-G4-FREEZE-01. Actual execution author and task: /root/gate4_uk_trade_execute. Reviewer must be a different actual author. The controller supplies review_dispatch_id, independent reviewer identity and permitted review output paths in its review dispatch; the executor does not assign or fabricate them.

Role/methods: Gate4 Complete Visual Agent V1.4; common contract V1.2; brand-applied-visual-design V0.4, full-page-visual-composition V0.4 and layout-interaction-verification V0.8 with gate4-self-check reference. Exact current identities and original user control record are bound by input-index.json. Stop after this frozen delivery; no Gate closure, Gate6 or publication. Pre-capture governance identities are retained in diagnostic_support/input-index-before-handoff-sync.json and preflight-before-handoff-sync.json; the V1.8/AgentV1.4/shared-handoff-contract alignment changes records only, with no source, dependency, visual rule or screenshot change.

Read in order: ../04_planning/gate4-v0.1/input-index.json → design-report.md → preflight-record.json → evidence-index.json → freeze-record.json → this page's execution self-check. Existing Manifest V0.5 remains the current upstream pointer and is unchanged by the executor.

Freeze ID: RES-TRADE-UK-G4-FREEZE-01. Source: ${pre.source.path}; ${pre.source.bytes} bytes; ${pre.source.sha256}. Evidence index: ${eid.bytes} bytes; ${eid.sha256}. The freeze record binds exact index, preflight, source/dependencies and this handoff/self-check. Machine result is in diagnostic_support/final-identity-check.json.

View/start: open the source HTML directly in local Chrome (file URL); no install, build, server or deployment is required. Relative dependencies/Inter-Variable.ttf and the two absolute D:/23MySec production-logo paths in input-index.json must be readable. Capture environment: Chrome ${runtime.browser}; 1440×900, 768×900 and 390×844 CSS; DPR1; Inter confirmed loaded. Default Menu/Cookie closed; state PNGs use viewport capture. View full PNGs at 100% and scroll to Footer; diagnostic_support/read-capture.cjs can emit 1850px-high native crop windows of the saved PNG without rerendering. Evidence assets and the 106 runtime observations map through evidence-index.json. No external destination or production backend is required for visual review.

Native command provenance: diagnostic_support/check.cjs performed INITIAL runtime assertions once, and its formal mode captured approval_core after preflight; diagnostic_support/finalize.cjs performed identity/dimension checks and built this freeze. Do not rerun these write-producing commands during review. The final-identity-check.json result records exact checked paths and dimensions; runtime.json records browser assertions. Machine, ACTUAL_RUNTIME, STATIC_VISUAL and LOCAL_SIMULATION scopes and exclusions are stated in the self-check. Visual rules and 4A samples are mapped in design-report.md and evidence-index.json.

Changes from Gate 3: body visual parameters only—Navy heading/table hierarchy, soft Hero/code/conditional surfaces, consistent functional teal actions, typography/spacing. Seven modules, all copy, all table columns/mobile records, actions and shared owner payload remain unchanged. Three full pages plus Menu at 768/390 and Cookie at 1440/768/390: 8 formal PNGs. Two retained 4A risk images only; no redundant diagnostic page/state set.

Findings: none unresolved. Review directly from these frozen assets. New screenshot triggers: suspicious source identity, actual render inconsistency, specific Finding or explicit new task requirement; no default re-creation of the full set. Review evidence belongs to the independent review location; do not write into this frozen execution index.

Carry forward: preserve investigation/registration/measures distinction, cumulative scope/codes and 8A60/8A61, conditional retrospective wording, indicative timetable/evidence periods, GB/NI, source/date and owner limits. Resource owner performs fresh official recheck before implementation/publication; current legal refresh was not performed here. Market/Product/RFQ and Global Chrome/Consent owners retain live routes, receiver/receipt and real consent requirements for Gate 8/9. Browser/device/screen-reader, production SEO/Schema/scope and publication remain unverified. This handoff grants no Gate approval, closure, Gate 6 or external action.
`);
const freeze={freeze_id:'RES-TRADE-UK-G4-FREEZE-01',workset_id:inputs.workset_id,status:'GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW',actual_author:'/root/gate4_uk_trade_execute',time:new Date().toISOString(),source:pre.source,input_index:id(d+'/input-index.json'),evidence_index:eid,preflight:id(d+'/preflight-record.json'),design_report:id(d+'/design-report.md'),self_check:id(self),handoff:id(handoff),dependencies:inputs.dependencies,render_conditions:pre.render_conditions,approval_core_images:8,diagnostic_images:2,findings:[],independent_review:'NOT_PERFORMED',gate_closure:'NOT_PERFORMED',next:'Separate authorized Gate5 task'};save(d+'/freeze-record.json',freeze);
for(const x of [freeze.source,freeze.input_index,freeze.evidence_index,freeze.preflight,freeze.design_report,freeze.self_check,freeze.handoff,...freeze.dependencies])verify(x);
save(d+'/diagnostic_support/final-identity-check.json',{status:'PASS',checked_at:new Date().toISOString(),freeze:id(d+'/freeze-record.json'),checks,failures:checks.filter(x=>!x.ok).length,formal_images:8,formal_dimensions:e.assets.map(x=>({state:x.state,width:x.physical_width,height:x.physical_height})),no_repeated_runtime:true});console.log(JSON.stringify({status:freeze.status,source:freeze.source,input_index:freeze.input_index,evidence_index:eid,freeze:id(d+'/freeze-record.json'),self_check:freeze.self_check,handoff:freeze.handoff,checks:checks.length,failures:0,formal_images:8,diagnostic_images:2},null,2));
