// Read-only execution SELF-CHECK. Output stays in this evidence directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'),{pathToFileURL}=require('url');
const{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',out=__dirname,candidate=root+'/pages/products/chloride-process/04_planning/gate3-v0.1',source=candidate+'/PRODUCT-PROC-CL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',copy=root+'/pages/products/chloride-process/04_planning/PRODUCT-PROC-CL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md';
const norm=s=>s.replace(/\s+/g,' ').trim(),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const raw=fs.readFileSync(copy,'utf8').split('--- BEGIN BUYER CLEAN COPY ---')[1].split('--- END BUYER CLEAN COPY ---')[0].trim();
const blocks=raw.split(/\r?\n\s*\r?\n/),headings=[],paragraphs=[];
for(const x of blocks){if(/^## B-0[2-5] — /.test(x))headings.push(norm(x.replace(/^## B-\d+ — /,'')));else if(/^#{1,3} /.test(x)&&!/^## B-/.test(x))headings.push(norm(x.replace(/^#+ /,'')));else if(!x.startsWith('#')&&!x.startsWith('[')&&!x.startsWith('**')&&x!=='CHLORIDE-PROCESS TIO2 GRADES')paragraphs.push(norm(x));}
const links=[...raw.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({label:m[1],href:m[2]}));
const expected={headings,paragraphs,links,eyebrow:'CHLORIDE-PROCESS TIO2 GRADES'};
const E={role:'EXECUTION_SELF_CHECK_NOT_INDEPENDENT_REVIEW',source,sourceSha256:hash(source),copy,copySha256:hash(copy),expected,widths:[],interactions:[],snapshots:[],findings:[],requests:[],errors:[]};
const url=pathToFileURL(source).href,fragment='#explore-chloride-process-grades',target='#explore-chloride-process-grades';
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});E.renderer=await browser.version();const p=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});await p.route(/^https?:/,r=>{E.requests.push(r.request().url());r.abort()});
const ready=async page=>page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()))});
async function shot(page,name,clip){const f=path.join(out,name+'.png');await page.screenshot({path:f,fullPage:!!clip,...(clip?{clip}:{})});const b=fs.readFileSync(f);E.snapshots.push({path:f,bytes:b.length,sha256:hash(f),physical:{width:b.readUInt32BE(16),height:b.readUInt32BE(20)},logicalViewport:page.viewportSize(),scale:name.includes('at2x')?2:1});}
async function checkAnchor(page,width,kind){const observed=await page.evaluate(()=>{const t=document.getElementById('explore-chloride-process-grades'),r=t.getBoundingClientRect();return {hash:location.hash,focused:document.activeElement===t,top:r.top,bottom:r.bottom,viewportHeight:innerHeight,scrollY,text:t.textContent}});assert.equal(observed.hash,fragment);assert.equal(observed.focused,true);assert(observed.top>=0&&observed.bottom<=observed.viewportHeight);assert(observed.scrollY>0);E.interactions.push({width,type:kind,observed});await shot(page,kind+'-'+width);}
try{for(const width of[1440,768,390]){await p.setViewportSize({width,height:1000});await p.goto(url);await ready(p);
const actual=await p.evaluate(()=>({headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>e.textContent.replace(/\s+/g,' ').trim()),paragraphs:[...document.querySelectorAll('main p')].map(e=>e.textContent.replace(/\s+/g,' ').trim()),links:[...document.querySelectorAll('main a')].map(a=>({label:a.textContent.trim(),href:a.getAttribute('href')})),eyebrow:document.querySelector('.cl-eyebrow').textContent}));assert.deepEqual(actual,expected);
const geometry=await p.evaluate(()=>{const visible=e=>e.getClientRects().length&&!e.closest('[hidden],[inert]')&&getComputedStyle(e).visibility!=='hidden';const controls=[...document.querySelectorAll('a,button')].filter(visible).map(e=>({label:e.textContent.trim()||e.getAttribute('aria-label'),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));return{scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,header:document.querySelector('header').getBoundingClientRect().height,font:document.fonts.check('17px Inter'),controls,small:controls.filter(c=>c.w<44||c.h<44),overflow:[...document.querySelectorAll('main *,header *,footer *')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5}).map(e=>e.tagName+':'+e.textContent.slice(0,70)),grades:[...document.querySelectorAll('.cl-grade')].map(e=>({name:e.querySelector('h3').textContent,summary:e.querySelector('p').textContent,url:e.querySelector('a').getAttribute('href'),top:e.getBoundingClientRect().top,height:e.getBoundingClientRect().height})),modules:[...document.querySelectorAll('.cl-module')].map(e=>e.id),prohibited:document.querySelectorAll('main form,main table,main details,main input,main select').length,editorialLeak:/B-0[0-5]|Primary action:|Secondary action:|BEGIN BUYER/.test(document.querySelector('main').innerText),current:[...document.querySelectorAll('.desktopNav,.mobileNav')].map(e=>({count:e.querySelectorAll('[aria-current=page]').length,text:e.querySelector('[aria-current=page]').textContent,display:getComputedStyle(e).display})),colors:[...document.querySelectorAll('main a')].map(e=>({label:e.textContent,color:getComputedStyle(e).color,border:getComputedStyle(e).borderColor,background:getComputedStyle(e).backgroundColor}))};});
E.widths.push({width,actual,geometry});assert.equal(geometry.scrollWidth,width);assert.deepEqual(geometry.overflow,[]);assert.deepEqual(geometry.small,[]);assert.equal(geometry.prohibited,0);assert.equal(geometry.editorialLeak,false);assert.equal(geometry.modules.length,5);assert.equal(geometry.grades.length,8);assert.equal(geometry.header,width===1440?84:64);assert.equal(geometry.font,true);for(const s of geometry.current){assert.equal(s.count,1);assert.equal(s.text,'Products');}
for(let y=0,n=1;y<geometry.height;y+=750,n++)await shot(p,'full-'+width+'-segment-'+n,{x:0,y,width,height:Math.min(850,geometry.height-y)});
await p.locator('a[href="'+fragment+'"]').click();await checkAnchor(p,width,'anchor-click');await p.goto(url);await ready(p);await p.locator('a[href="'+fragment+'"]').focus();await p.keyboard.press('Enter');await checkAnchor(p,width,'anchor-enter');await p.goto(url+fragment);await ready(p);await p.waitForFunction(()=>document.activeElement.id==='explore-chloride-process-grades');await checkAnchor(p,width,'anchor-direct');
await p.goto(url);await ready(p);for(const a of await p.locator('main a:not([href^="#"])').all())await a.click();const recorded=await p.evaluate(()=>window.planningNavigation);const expectedIntents=links.filter(a=>!a.href.startsWith('#')).map(a=>({...a,...(['/request-a-quote/','/request-documents/'].includes(a.href)?{context:{source_page_id:'PRODUCT-PROC-CL'}}:{})}));assert.deepEqual(recorded,expectedIntents);E.interactions.push({width,type:'ordinary-link-intents',recorded,scope:'No destination requested; source-only attribution is local instrumentation, no receiver/preselection proof'});
await p.goto(url);await ready(p);await p.locator('#cl-01 .cl-action a').first().focus();await shot(p,'body-cta-focus-'+width);await p.locator('#cl-01 .cl-action a').first().blur();await p.locator('#cl-01 .cl-action a').first().hover();await shot(p,'body-cta-hover-'+width);
if(width!==1440){await p.locator('.menuButton').click();assert.equal(await p.locator('.menuButton').textContent(),'Close');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Home');assert.equal(await p.evaluate(()=>document.body.style.overflow),'hidden');await p.locator('main a').first().evaluate(e=>e.focus());assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Home');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Request a Quote');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await shot(p,'menu-'+width+'-focus-close');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Menu');for(let i=0;i<8;i++){await p.locator('.menuButton').click();await p.locator('.mobileNav a').nth(i).click();assert.equal(await p.locator('.mobileNav').isVisible(),false);assert.equal(await p.evaluate(()=>document.querySelector('main').inert),false);assert.equal(await p.evaluate(()=>document.body.style.overflow),'');}await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:1000});assert.equal(await p.locator('.mobileNav').isVisible(),false);assert.equal(await p.evaluate(()=>document.querySelector('main').inert),false);await p.setViewportSize({width,height:1000});E.interactions.push({width,type:'mobile-menu',result:'open/Close/Home focus; backward and forward cycle; background focus blocked; body overflow locked/restored; Escape return; each of 8 links closes/restores; crossing to desktop closes/restores'});}
await p.locator('#cookie-trigger').click();assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await p.locator('main a').first().evaluate(e=>e.focus());assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Read Cookie Policy');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await shot(p,'cookie-'+width+'-focus-close');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'cookie-trigger');await p.locator('#cookie-trigger').click();await p.locator('.cookie-layer button').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'cookie-trigger');E.interactions.push({width,type:'cookie',result:'minimal shared layer; focus, background isolation, Tab wrap, Escape/Close return locally verified'});
const nojs=await browser.newPage({viewport:{width,height:1000},javaScriptEnabled:false});await nojs.route(/^https?:/,r=>{E.requests.push(r.request().url());r.abort()});await nojs.goto(url);await ready(nojs);const fallback=await nojs.evaluate(()=>({headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>e.textContent),links:[...document.querySelectorAll('main a')].map(e=>({label:e.textContent,href:e.getAttribute('href')})),grades:document.querySelectorAll('.cl-grade').length,width:document.documentElement.scrollWidth}));assert.deepEqual(fallback.headings,headings);assert.deepEqual(fallback.links,links);assert.equal(fallback.grades,8);assert.equal(fallback.width,width);await nojs.locator('a[href="'+fragment+'"]').click();await checkAnchor(nojs,width,'nojs-anchor-click');await nojs.goto(url+fragment);await ready(nojs);await checkAnchor(nojs,width,'nojs-anchor-direct');E.interactions.push({width,type:'no-js-content-and-links',fallback,scope:'all main content and actual href remain; outbound destinations not clicked'});await nojs.close();
}
const zoom=await browser.newPage({viewport:{width:720,height:500},deviceScaleFactor:2,reducedMotion:'reduce'});await zoom.goto(url);await ready(zoom);assert.equal(await zoom.evaluate(()=>document.documentElement.scrollWidth),720);await zoom.locator('a[href="'+fragment+'"]').click();await shot(zoom,'reflow-200pct-anchor-720-css-at2x');await zoom.locator('.menuButton').click();await shot(zoom,'reflow-200pct-menu-720-css-at2x');await zoom.keyboard.press('Escape');await zoom.locator('#cookie-trigger').click();await shot(zoom,'reflow-200pct-cookie-720-css-at2x');E.interactions.push({type:'200%-equivalent-reflow',logical:'720x500',physical:'1440x1000',scale:2,reducedMotion:await zoom.evaluate(()=>matchMedia('(prefers-reduced-motion:reduce)').matches),limitation:'CSS viewport/DPR emulation, not actual browser-UI zoom or real device'});await zoom.close();
assert.equal(hash(source),E.sourceSha256);const renders=JSON.parse(fs.readFileSync(candidate+'/render-evidence.json','utf8'));assert.equal(renders.sourceSha256,E.sourceSha256);for(const a of renders.exports){assert.equal(hash(a.path),a.sha256);assert.equal(fs.statSync(a.path).size,a.bytes);}E.renderedIdentity=renders.exports;
}catch(e){E.errors.push(e.stack);process.exitCode=1;}finally{fs.writeFileSync(out+'/measurements-and-actions.json',JSON.stringify(E,null,2));await browser.close();console.log(JSON.stringify({sourceSha256:E.sourceSha256,widths:E.widths.map(w=>({width:w.width,height:w.geometry.height,small:w.geometry.small,overflow:w.geometry.overflow})),actions:E.interactions.length,snapshots:E.snapshots.length,errors:E.errors}));}})();
