// Independent Gate 5 design review. Reads author sources; writes only this review directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=__dirname,root=path.resolve(out,'../../../..'),candidate=path.join(root,'pages/documents/04_planning/d32-gate4-v0.1');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),parse=p=>JSON.parse(fs.readFileSync(p));
const assertions=[],observations=[],identities=[];
const check=(id,pass,actual)=>assertions.push({id,pass:!!pass,actual});
const norm=s=>s.replace(/\s+/g,' ').trim();
function bind(row,group){const exists=fs.existsSync(row.path),actual=exists?{bytes:fs.statSync(row.path).size,sha256:sha(row.path)}:null;identities.push({group,...row,actual,pass:exists&&actual.bytes===row.bytes&&actual.sha256===row.sha256.toLowerCase()});}
const freeze=parse(path.join(candidate,'freeze.json')), assets={files:freeze.files};
const lock=parse(path.join(candidate,'source-lock.json')), evidence=parse(path.join(candidate,'evidence-index.json'));
for(const r of freeze.files)bind(r,'freeze_bundle');
for(const r of [...lock.sources,...lock.dependencies])bind(r,'source_lock');
check('all_frozen_identities_match',identities.every(r=>r.pass),identities.filter(r=>!r.pass));
const digest=crypto.createHash('sha256').update(JSON.stringify(freeze.files)).digest('hex');
check('bundle_digest',digest===freeze.bundle_id&&digest==='922b8b6ecc9c16e3b773c25f513c548b35d4552df72ed4e1635e30e68ecf7615',digest);
check('freeze_identity',sha(path.join(candidate,'freeze.json'))==='cd906fd54f77cfb29de11f9f4497a94177d11babfd3ea3eab3622fc0072892f4');
const source=path.join(candidate,'DOC-000_D32_structure.html'),html=fs.readFileSync(source,'utf8');
check('submitted_source_identity',sha(source)==='2fa09d30d87870645752cde4f085d5113b63c97ef333534d184416d8cb6f0723');
check('evidence_inventory',evidence.evidence.length===48&&evidence.evidence.filter(r=>r.role==='FORMAL').length===18);
for(const row of evidence.evidence){const b=fs.readFileSync(row.path);check('image_'+path.basename(row.path),b.length===row.bytes&&sha(row.path)===row.sha256&&b.readUInt32BE(16)===row.width&&b.readUInt32BE(20)===row.height&&row.dpr===1&&row.source_identity===sha(source),{width:row.width,height:row.height,role:row.role});}
const prior=path.join(root,'pages/documents/04_planning/d32-gate3-v0.2');
for(const f of ['DOC-000_D32_structure.html','DOC-000_D32_structure.css','DOC-000_D32_behavior.js'])check('closed_G3_parity_'+f,sha(path.join(candidate,f))===sha(path.join(prior,f)));
const {renderSharedChrome}=require(path.join(root,'docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs'));
const shared=renderSharedChrome({currentPageId:'DOC-000',primaryLogoSrc:pathToFileURL(path.join(root,'brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg')).href,reverseLogoSrc:pathToFileURL(path.join(root,'brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg')).href});
check('shared_consumer_exact_snapshot',['header','footer','dialog','style','behavior'].every(k=>html.includes(shared[k])));
const heroSource=path.join(root,'pages/documents/04_planning/visual-designs/doc-root-page-hero-v1.0/doc-root-page-hero-preview-v1.0.html');
const approvedSvg=fs.readFileSync(heroSource,'utf8').match(/<svg viewBox="0 0 310 220"[\s\S]*?<\/svg>/)[0];
check('approved_hero_media_unchanged',html.includes(approvedSvg),{source:heroSource,sha256:sha(heroSource)});
const B=fs.readFileSync(path.join(root,'pages/documents/04_planning/DOC-000_CONTENT_ARCHITECTURE_V0.10.md'),'utf8');
const expectedTables=[...B.matchAll(/^\| `([^`]+)` \| `([^`]+)` \|$/gm)].map(m=>[m[1],m[2]]);
const faq=expectedTables.slice(-6),scenarios=expectedTables.slice(0,3),groups=expectedTables.slice(3,7);
const grades=['M-350','M-510','M-896','M-996','M-2196','M-895','M-200','M-108','M-210','M-340','M-886','M-52','M-2377','CR-901'];
const fixed={h1:'Documents for Product & Supplier Qualification',hero:'Request technical, safety, quality, COA, origin and supplier-qualification documentation for the titanium dioxide grade your team is evaluating.',note:'Requests are currently handled in English.',selector:'Select the product grade the documents relate to. It will be prefilled on the request form and can be changed before submission.',why:'Documentation can differ by product and review purpose. Submitting a request helps match the materials to the selected grade and the information your team needs. Availability and applicable scope are confirmed during review.',closing:'Select the product grade the documents relate to. We’ll carry it into the request form, where you can choose the document types you need.'};
const headings=[fixed.h1,'Select a Product Grade','How It Works','Supporting Your Review Process','Documentation You Can Request','Why Documents Are Provided on Request','Buyer Questions','Ready to Request Documents?'];
(async()=>{
 const browser=await chromium.launch({headless:true});
 for(const width of [1440,1024,768,390,320]){
  const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(source).href);await p.evaluate(()=>document.fonts.ready);
  const prefix=width+'_',url=p.url();
  const data=await p.evaluate(()=>{const h=document.querySelector('h1'),s=getComputedStyle(h),controls=[...document.querySelectorAll('a,button,select')].filter(e=>e.checkVisibility()).map(e=>({label:e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));return {title:document.title,description:document.querySelector('meta[name="description"]')?.content||null,headings:[...document.querySelectorAll('main > section')].map(e=>e.querySelector('h1,h2')?.textContent),text:document.querySelector('main').textContent,visible:document.querySelector('main').innerText,controls,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,headerHeight:document.querySelector('header').getBoundingClientRect().height,h1:{size:s.fontSize,weight:s.fontWeight,lines:Math.round(h.getBoundingClientRect().height/parseFloat(s.lineHeight))},media:{visible:document.querySelector('.doc-illustration').checkVisibility(),ariaHidden:document.querySelector('.doc-illustration').getAttribute('aria-hidden')},leaves:[...document.querySelectorAll('main h1,main h2,main h3,main p,main button,main a')].filter(e=>e.checkVisibility()).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {text:e.textContent.trim(),left:r.left,right:r.right,w:r.width,h:r.height,textOverflow:s.textOverflow,overflow:s.overflow,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight}}),images:[...document.images].map(i=>i.complete&&i.naturalWidth>0),current:[...document.querySelectorAll('header [aria-current="page"]')].map(e=>e.textContent),legal:[...document.querySelectorAll('.legalUtilities a')].map(e=>e.getAttribute('href'))}});
  observations.push({viewport:[width,1000],...data});
  if(width===1440)check('approved_seo_title_preserved',data.title==='Documents for Product Qualification | TiO2 Malaysia',{expected:'Documents for Product Qualification | TiO2 Malaysia',actual:data.title});
  check(prefix+'module_order',JSON.stringify(data.headings)===JSON.stringify(headings),data.headings);
  check(prefix+'permanent_copy',Object.values(fixed).every(t=>norm(data.text).includes(t)));
  check(prefix+'scenario_pairs',JSON.stringify(await p.locator('[data-scenario]').evaluateAll(xs=>xs.map(e=>[e.querySelector('h3').textContent,e.querySelector('p').textContent])))===JSON.stringify(scenarios));
  check(prefix+'group_pairs',JSON.stringify(await p.locator('[data-group]').evaluateAll(xs=>xs.map(e=>[e.querySelector('h3').textContent,e.querySelector('p').textContent])))===JSON.stringify(groups));
  check(prefix+'lightweight_steps',await p.locator('ol.doc-steps > li').count()===3&&await p.locator('ol.doc-steps article').count()===0);
  const stepText=await p.locator('.doc-steps').innerText();check(prefix+'steps_complete',['Identify Your Review Need','Choose product evaluation, quality and supplier qualification, or origin review.','Select a Product Grade','Choose the titanium dioxide grade the documents should relate to.','Request Documents','Continue with the grade prefilled, select the document types you need, and submit your request.'].every(t=>norm(stepText).includes(t)));
  check(prefix+'no_fake_inventory',await p.locator('main form,main input,main a[download],main a[href$=".pdf"],[data-scenario] a,[data-scenario] button,[data-group] a,[data-group] button').count()===0&&!/Find Documents|Download|Coming Soon|CURRENT|PENDING|DOC-000|D32|inventory|Other Documentation/.test(data.visible));
  check(prefix+'schema_forbidden_absent',!/<script[^>]+application\/ld\+json/i.test(html)&&!html.includes('DigitalDocument'));
  check(prefix+'geometry',data.scrollWidth===width&&data.controls.every(c=>c.w>=44&&c.h>=44)&&data.leaves.every(x=>x.left>=0&&x.right<=width+1&&x.w>0&&x.h>0&&x.textOverflow!=='ellipsis'&&(!['hidden','clip'].includes(x.overflow)||x.scrollHeight<=x.clientHeight+2)),{overflow:data.scrollWidth-width,small:data.controls.filter(c=>c.w<44||c.h<44),badLeaves:data.leaves.filter(x=>x.left<0||x.right>width+1)});
  check(prefix+'shared_assembly',data.current.length===2&&data.current.every(x=>x==='Documents')&&data.headerHeight===(width===1440?84:64)&&data.images.every(Boolean)&&JSON.stringify(data.legal)===JSON.stringify(['/privacy-policy/','/ms/privacy-policy/','/cookie-policy/']));
  check(prefix+'hero_binding',data.h1.size===(width>=1024?'56px':width===768?'44px':'36px')&&data.h1.weight==='700'&&data.h1.lines===(width===1440?2:width===1024?3:width===768?2:width===390?3:4)&&data.media.visible&&data.media.ariaHidden==='true'&&await p.locator('[data-component="RootPageHero"]').getAttribute('data-variant')==='hub-light',data.h1);
  check(prefix+'shared_H1_max_three_lines',data.h1.lines<=3,data.h1);
  check(prefix+'initial_grade',await p.locator('#product-grade').inputValue()===''&&JSON.stringify(await p.locator('#product-grade option').evaluateAll(x=>x.slice(1).map(e=>e.value)))===JSON.stringify(grades)&&await p.locator('#product-grade option').count()===15);
  check(prefix+'native_direct_hero',await p.locator('[data-hero-action]').evaluate(e=>e.tagName==='A'&&e.getAttribute('href')==='/request-documents/'));
  check(prefix+'initial_continue_operable',await p.locator('#continue-request').isVisible()&&await p.locator('#continue-request').getAttribute('aria-disabled')!=='true'&&await p.locator('#continue-request').isEnabled());
  const position=()=>p.locator('#continue-request').evaluate(e=>e.getBoundingClientRect().top+scrollY);const before=await position();
  await p.locator('#faq-question-2').click();await p.locator('#continue-request').focus();await p.keyboard.press('Enter');
  check(prefix+'empty_validation',p.url()===url&&await p.locator('#grade-error').innerText()==='Select a product grade to continue.'&&await p.locator('#product-grade').evaluate(e=>e===document.activeElement&&e.getAttribute('aria-invalid')==='true'&&e.getAttribute('aria-describedby').split(' ').includes('grade-error')));
  const after=await position();check(prefix+'stable_validation_slot',Math.abs(after-before)<1,{beforeDocumentY:before,afterDocumentY:after,delta:after-before,error:await p.locator('#grade-error').evaluate(e=>({height:e.getBoundingClientRect().height,lineHeight:getComputedStyle(e).lineHeight,text:e.textContent})),select:await p.locator('#product-grade').evaluate(e=>({documentY:e.getBoundingClientRect().top+scrollY,focused:e===document.activeElement}))});
  check(prefix+'unrelated_state_preserved',await p.locator('#faq-question-2').getAttribute('aria-expanded')==='true');await p.locator('#faq-question-2').click();
  for(const grade of grades){await p.locator('#product-grade').selectOption(grade);check(prefix+'grade_'+grade,await p.locator('#continue-request').getAttribute('href')==='/request-documents/?product='+grade&&await p.locator('#closing-action').getAttribute('href')==='/request-documents/?product='+grade&&await p.locator('#grade-selected').innerText()==='Selected product grade: '+grade&&await p.locator('#grade-error').innerText()==='');}
  await p.locator('#product-grade').selectOption('');await p.locator('#closing-action').focus();await p.keyboard.press('Enter');check(prefix+'closing_empty_focus_no_navigation',p.url()===url&&await p.locator('#product-grade').evaluate(e=>e===document.activeElement)&&await p.locator('#closing-action').innerText()==='Select a Product Grade');
  check(prefix+'FAQ_initial_DOM_and_collapsed',await p.locator('.faq-answer').count()===6&&await p.locator('.faq-answer:visible').count()===0);
  for(let i=0;i<6;i++){const button=p.locator('.faq-question').nth(i);await button.focus();await p.keyboard.press(i%2?'Space':'Enter');const pair=await p.locator('.faq-item').nth(i).evaluate(e=>[e.querySelector('button').childNodes[0].textContent,e.querySelector('.faq-answer p').textContent]);check(prefix+'faq_'+(i+1),JSON.stringify(pair)===JSON.stringify(faq[i])&&await p.locator('.faq-answer:visible').count()===1&&await button.evaluate(e=>e===document.activeElement&&e.getAttribute('aria-expanded')==='true'&&document.getElementById(e.getAttribute('aria-controls')).getAttribute('aria-labelledby')===e.id));check(prefix+'faq_'+(i+1)+'_fully_visible',await p.locator('.faq-answer').nth(i).evaluate(e=>{const r=e.getBoundingClientRect();return e.checkVisibility()&&r.left>=0&&r.right<=innerWidth&&e.scrollHeight<=e.clientHeight+1}));}
  await p.locator('.faq-question').last().click();
  if(width!==1440){const m=p.locator('.menuButton');await m.click();check(prefix+'menu_open_focus_inert',await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement)&&await p.locator('main').evaluate(e=>e.inert)&&await p.locator('footer').evaluate(e=>e.inert));await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');check(prefix+'menu_forward_loop',await m.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(prefix+'menu_reverse_loop',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(prefix+'menu_escape_restores',await m.evaluate(e=>e===document.activeElement)&&await p.locator('main').evaluate(e=>!e.inert)&&await p.locator('body').evaluate(e=>e.style.overflow===''));await m.click();await p.locator('.mobileNav a[href="/documents/"]').evaluate(e=>e.addEventListener('click',ev=>ev.preventDefault(),{once:true}));await p.locator('.mobileNav a[href="/documents/"]').click();check(prefix+'menu_choice_restores',await m.getAttribute('aria-expanded')==='false'&&await p.locator('main').evaluate(e=>!e.inert));await m.click();await p.setViewportSize({width:1440,height:1000});await p.waitForFunction(()=>document.querySelector('.menuButton').getAttribute('aria-expanded')==='false');check(prefix+'menu_breakpoint_restores',await p.locator('main').evaluate(e=>!e.inert));await p.setViewportSize({width,height:1000});}
  await p.locator('#cookie-trigger').click();check(prefix+'cookie_opens_first_focus',await p.locator('dialog').isVisible()&&await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(prefix+'cookie_reverse',await p.locator('.cookie-actions a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(prefix+'cookie_forward',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(prefix+'cookie_return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await p.locator('dialog').isVisible());check(prefix+'no_runtime_errors',errors.length===0,errors);
  await p.close();
 }
 await browser.close();
 for(const r of assets.files)check('readonly_'+path.basename(r.path),sha(r.path)===r.sha256);
 const result={reviewer:'/root/res_root_d32',mode:'INDEPENDENT_REVIEW',gate:5,time:new Date().toISOString(),candidateSource:source,sourceSha256:sha(source),bundleSha256:digest,browser:'Bundled Playwright Chromium headless',evidenceTypes:['SOURCE_INSPECTION','ACTUAL_RUNTIME_PLANNING_ONLY','STATIC_VISUAL author formal assets opened separately'],assertions,identities,observations,passed:assertions.filter(x=>x.pass).length,failed:assertions.filter(x=>!x.pass).length,limitations:['No author script executed or candidate file edited.','No network navigation, receiver, real submission, development repository or production claim.','Menu link default was intercepted solely to remain on local test document.','No repeated full-page raster exports created.']};
 fs.writeFileSync(path.join(out,'observations.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:assertions.filter(x=>!x.pass),identityRows:identities.length},null,2));process.exitCode=result.failed?1:0;
})().catch(e=>{console.error(e.stack);process.exitCode=2});
