// Reviewer-only diagnostic. Candidate and shared sources are strictly read-only.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../../../..'),candidate=path.join(root,'pages/documents/04_planning/d32-gate4-v0.1');
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const inputs=read(path.join(candidate,'input-index.json')),archive=read(path.join(root,'90_archive/project-governance/2026-09-21-gate3-gate4-merge/file-changes.json'));
const bindings=inputs.inputs.map(r=>{const current=sha(r.path),rel=r.path.replace('D:/23MySec/',''),backup=archive[rel]?.backup;return {...r,current,match:current===r.sha256,archive:backup||null,archiveMatch:backup?sha(path.join(root,backup))===r.sha256:false};});
const lum=rgb=>rgb.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);
const ratio=(a,b)=>{const la=lum(a),lb=lum(b);return (Math.max(la,lb)+.05)/(Math.min(la,lb)+.05)};
(async()=>{const browser=await chromium.launch({headless:true}),views=[];
for(const width of [1440,1024,768,390,320]){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});await p.goto(pathToFileURL(path.join(candidate,'DOC-000_D32_structure.html')).href);await p.evaluate(()=>document.fonts.ready);
const states=[];const collect=async state=>states.push({state,...await p.evaluate(()=>{const sel=s=>document.querySelector(s),rect=s=>{const r=sel(s).getBoundingClientRect();return {y:r.top+scrollY,width:r.width,height:r.height}},style=s=>{const c=getComputedStyle(sel(s));return {color:c.color,background:c.backgroundColor,font:c.fontSize,line:c.lineHeight}};return {cta:rect('#continue-request'),selector:rect('#grade-selector'),error:rect('#grade-error'),errorStyle:style('#grade-error'),errorText:sel('#grade-error').textContent,selectionText:sel('#grade-selected').textContent,primary:style('[data-hero-action]'),body:style('body'),h1:style('h1'),columns:Object.fromEntries(['.root-hero','.doc-selector','.doc-steps','.doc-scenarios','.doc-groups'].map(s=>[s,getComputedStyle(sel(s)).gridTemplateColumns])),overflow:document.documentElement.scrollWidth-innerWidth,dpr:devicePixelRatio,fontReady:document.fonts.status};})});
await collect('empty');await p.locator('#continue-request').click();await collect('error');await p.locator('#product-grade').selectOption('M-2196');await collect('selected');await p.locator('#product-grade').selectOption('');await collect('cleared');views.push({width,states});await p.close();}
const browserVersion=browser.version();await browser.close();const colors={body_on_white:ratio([51,65,85],[255,255,255]),body_on_light:ratio([51,65,85],[245,248,251]),navy_on_white:ratio([6,43,91],[255,255,255]),teal_on_white:ratio([0,128,120],[255,255,255]),white_on_teal:ratio([255,255,255],[0,128,120]),error_on_white:ratio([180,35,24],[255,255,255])};
const result={reviewer:'/root/res_root_d32',time:new Date().toISOString(),browserVersion,source:sha(path.join(candidate,'DOC-000_D32_structure.html')),bindings,bindingsResolved:bindings.every(r=>r.match||r.archiveMatch),views,colors,colorBasis:'Computed runtime foreground/solid backgrounds checked against source; WCAG relative luminance; borders and decorative SVG excluded.',candidateUnchanged:sha(path.join(candidate,'freeze.json'))==='cd906fd54f77cfb29de11f9f4497a94177d11babfd3ea3eab3622fc0072892f4'};
fs.writeFileSync(path.join(__dirname,'supplement.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({inputs:bindings.length,liveMatches:bindings.filter(r=>r.match).length,archivedMatches:bindings.filter(r=>!r.match&&r.archiveMatch).length,bindingsResolved:result.bindingsResolved,browserVersion,colors,ctaPositions:views.map(v=>({width:v.width,states:v.states.map(s=>[s.state,s.cta.y,s.error.height])})),candidateUnchanged:result.candidateUnchanged},null,2));})();
