const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',page=root+'/pages/system/404',out=page+'/04_planning/gate3-v0.1';
const shared=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
for(const d of ['approval_core','dependencies','diagnostic_support/render'])fs.mkdirSync(out+'/'+d,{recursive:true});
if(fs.existsSync(out+'/freeze-record.json'))throw Error('candidate already frozen');
const inputs=[
 ['A',page+'/04_planning/SYS-404_GATE2_CONTENT_SKELETON_INHERITANCE_MAP_V0.1.md'],
 ['B',page+'/04_planning/SYS-404_GATE2_FULL_BUYER_CLEAN_COPY_V0.1.md'],
 ['C',page+'/04_planning/SYS-404_GATE2_CONTENT_CONTRACT_V0.1.md'],
 ['Gate2 closure',page+'/05_review/SYS-404_GATE2_USER_APPROVAL_AND_CLOSURE_V0.1.md'],
 ['Brief',root+'/docs/page-briefs/SYS-404_PAGE_NOT_FOUND_BRIEF_V0.1.md'],
 ['Approved design',root+'/docs/superpowers/specs/2026-09-08-404-thank-you-pages-design-v0.1.md'],
 ['Current manifest',page+'/SYS-404_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md']
].map(([role,p])=>({...id(p),role}));
const pkg=JSON.parse(fs.readFileSync(shared+'/consumer-package.json','utf8'));
const sharedFiles=pkg.files.map(f=>{const a=id(shared+'/'+f.path);if(a.sha256!==f.sha256)throw Error('shared hash '+f.path);return {...a,role:f.role}});
for(const f of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(shared+'/'+f,out+'/dependencies/'+f);
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg';
const reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';
const binding={pageId:'SYS-404',dispatch:'G3-SYS404-EXEC-20260908-01',status:'IN_PROGRESS',route:'RUNTIME_FALLBACK',siteScope:'tio2-my',navigationMapping:'NONE',approvedInputs:inputs,sharedConsumer:{...id(shared+'/consumer-package.json'),packageId:pkg.packageId,version:pkg.version},sharedFiles,dependencies:[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(id),runtimeBoundary:'LOCAL_PLANNING_ONLY'};
save(out+'/input-binding.json',binding);
save(out+'/task-input-card.md',`# SYS-404 Gate 3 task input card\n\n- Dispatch: \`G3-SYS404-EXEC-20260908-01\`\n- Status: \`IN_PROGRESS\`; stop at \`DRAFT_FOR_PROJECT_CONTROL_REVIEW\`.\n- Approved sequence: shared Header → eyebrow → H1 → body → two Primary actions → three Supporting actions → shared Footer.\n- Viewports: 1440, 768, 390 logical CSS pixels, DPR 1.\n- Shared source: neutral consumer V0.2; SYS-404 has zero current navigation links per surface.\n- Risks: compact body must still reach the complete Footer; all five actions must remain distinct, wrapped and at least 44×44; Menu and Cookie Settings must exit and restore focus; no search, FAQ, form, recommendation, redirect, or invented state.\n- Runtime: actual HTTP 404, route resolution, analytics and production link availability remain downstream dependencies.\n`);
const chrome=require(shared+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'HOME-001',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
// The package requires an allowed currentPageId. SYS-404 is explicitly unmapped, so only the
// generated current marker is neutralized after generation; all owner markup remains unchanged.
chrome.header=chrome.header.replace(/ aria-current="page"/g,'');
const body=`<main id="main-content"><section class="recovery" aria-labelledby="page-title"><p class="eyebrow">404 · PAGE NOT FOUND</p><h1 id="page-title">Let’s help you find what you need.</h1><p class="intro">The page you’re looking for may have moved or is no longer available. You can continue by exploring our titanium dioxide products, requesting technical documents, or contacting our team.</p><nav class="primary-actions" aria-label="Primary recovery actions"><a href="/products/">Explore Products</a><a href="/">Go to Homepage</a></nav><nav class="supporting-actions" aria-label="Supporting recovery actions"><a href="/request-documents/">Request Documents</a><a href="/contact/">Contact Our Team</a><a href="/request-a-quote/">Request a Quote</a></nav></section></main>`;
const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#102d46;background:#fff}main{min-height:520px;padding:72px 40px 88px;display:grid;place-items:center}.recovery{width:min(820px,100%);text-align:center}.eyebrow{margin:0 0 18px;color:#526673;font-size:14px;line-height:1.5;font-weight:700;letter-spacing:.12em}.recovery h1{margin:0 auto 22px;max-width:720px;color:#062b5b;font-size:48px;line-height:1.12;letter-spacing:-1.2px}.intro{max-width:720px;margin:0 auto;color:#334155;font-size:18px;line-height:1.65}.primary-actions,.supporting-actions{display:flex;flex-wrap:wrap;justify-content:center;gap:14px}.primary-actions{margin-top:34px}.supporting-actions{margin-top:18px}.recovery nav a{min-width:44px;min-height:48px;padding:12px 20px;display:inline-flex;align-items:center;justify-content:center;border-radius:6px;font-size:16px;font-weight:650;text-decoration:none}.primary-actions a{border:1px solid #008078;background:#008078;color:#fff}.primary-actions a:nth-child(2){background:#fff;color:#008078}.supporting-actions a{min-height:44px;padding:10px 16px;border:1px solid #008078;background:#fff;color:#008078}.recovery a:focus-visible{outline:3px solid #008078;outline-offset:3px}@media(max-width:1100px){main{min-height:500px;padding:64px 32px 76px}.recovery h1{font-size:42px}}@media(max-width:560px){main{min-height:480px;padding:48px 20px 60px}.recovery{text-align:left}.recovery h1{font-size:35px;letter-spacing:-.7px}.intro{font-size:16px}.primary-actions,.supporting-actions{display:grid;grid-template-columns:1fr;gap:12px}.primary-actions{margin-top:28px}.supporting-actions{margin-top:14px}.recovery nav a{width:100%;text-align:center}}`;
const behavior=`window.localNavigationIntents=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();window.localNavigationIntents.push({href:a.getAttribute('href'),type:'LOCAL_NAVIGATION_INTENT_ONLY',context:{}});});`;
const source=out+'/SYS-404_GATE3_WIREFRAME_V0.1.html';
save(source,'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex, follow"><title>Page Not Found | TiO2 Malaysia</title><style>'+chrome.style+'\n'+css+'</style></head><body>'+chrome.header+body+chrome.footer+chrome.dialog+'<script>'+chrome.behavior+'\n'+behavior+'</script></body></html>');
save(out+'/design-report.md',`# SYS-404 Gate 3 responsive structure report V0.1\n\n## Input and scope\n\nThe exact input identities are in \`input-binding.json\`. This source consumes Shared Global Chrome Gate 3 Consumer V0.2. Because its API requires a mapped navigation key, generation uses \`HOME-001\` only to create the owner markup and then removes the two generated \`aria-current\` attributes. This realizes the approved SYS-404 zero-current contract without copying another page or changing shared sources.\n\n## Structure decisions\n\nThe short recovery message occupies one centered reading block between complete shared Chrome and Footer. The two approved Primary actions remain a separate group before the three Supporting actions. At 390 all five actions become full-width single-column controls; wording, order, targets and hierarchy remain exact. At 768 the groups wrap independently. No page-local image, form, search, FAQ, recommendation, redirect or error variant is added.\n\nCurrent type, spacing and basic colors are readable planning parameters. Gate 4 owns complete visual refinement while preserving the approved structure, order and action hierarchy.\n\n## Runtime boundary\n\nThe source intercepts links only as local navigation-intent evidence. It does not send requests. HTTP 404 delivery, valid-route non-interception, destination availability, sitemap/robots enforcement, analytics sanitization and site-scope isolation remain DEP01–DEP07 for Gate 6/8/9.\n`);
console.log(JSON.stringify({source:id(source),inputs:inputs.length,sharedFiles:sharedFiles.length},null,2));
