const fs=require('fs'),crypto=require('crypto');
const{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base="D:/23MySec/pages/markets/india",src=base+"/04_planning/gate4-v1.0",out="D:\\23MySec\\pages\\markets\\india\\05_review\\gate4-independent-review-v1.0",entry=src+"/MARKET-IN-001_GATE4_COMPLETE_VISUAL_V1.0.html",url="file:///"+entry;
const read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim();
const rawInv=json(src+'/approval_core/export-inventory.json'),inv={assets:rawInv.assets.map(x=>({...x,path:src+'/approval_core/'+x.file,relativePath:x.file,logicalViewport:{width:Number(x.file.match(/_(1440|768|390)_/)[1])},state:x.state==='NORMAL_FULL_PAGE'?'normal':x.state}))};
const identity={records:[rawInv.source,...inv.assets].map(x=>({path:x.path,match:hash(x.path)===x.sha256&&read(x.path).length===x.bytes,actualSha256:hash(x.path)})),pngDimensions:inv.assets.map(x=>({path:x.path,w:read(x.path).readUInt32BE(16),h:read(x.path).readUInt32BE(20),match:read(x.path).readUInt32BE(16)===(x.logicalViewport.width===390?780:x.logicalViewport.width)}))};fs.writeFileSync(out+'/identity.json',JSON.stringify(identity,null,2));
const b=read(base+'/04_planning/MARKET-IN-001_GATE2_FULL_BUYER_CLEAN_COPY_V0.1.md').toString().replace(/<!--[\s\S]*?-->/g,'').trim();
const plain=t=>norm(t.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/\*\*/g,''));
const expected={headings:b.split('\n').filter(l=>/^#{1,3} /.test(l)).map(l=>plain(l.replace(/^#+ /,''))),paragraphs:b.split(/\r?\n\s*\r?\n/).filter(l=>!/^#|^\||^\d+\.|^- |^\[Home\]/.test(l)).map(plain),list:b.split('\n').filter(l=>/^(?:\d+\.|-) /.test(l)).map(l=>plain(l.replace(/^(?:\d+\.|-) /,''))),table:b.split('\n').filter(l=>l.startsWith('|')&&!/^\|---/.test(l)).map(l=>l.split('|').slice(1,-1).map(plain)),links:[...b.matchAll(/\[([^\]]+)\]\(([^)]*)\)/g)].map(x=>({text:x[1],href:x[2]}))};
async function copy(p){const actual=await p.evaluate(()=>{const n=t=>t.replace(/\s+/g,' ').trim(),arr=s=>[...document.querySelectorAll(s)].map(e=>n(e.textContent));return{headings:arr('main h1,main h2,main h3'),paragraphs:arr('main p'),list:arr('main li'),table:[...document.querySelectorAll('.evidenceTable tr')].map(tr=>[...tr.children].map(td=>{const c=td.cloneNode(true);c.querySelectorAll('.cellLabel').forEach(l=>l.remove());return n(c.textContent)})),links:[...document.querySelectorAll('main a')].map(e=>({text:n(e.textContent),href:e.getAttribute('href')}))}});return{actual,expected,matches:Object.fromEntries(Object.keys(expected).map(k=>[k,JSON.stringify(expected[k])===JSON.stringify(actual[k])]))}}
const lum=c=>{const a=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};const ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const desc=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();let n=e,bg=s.backgroundColor;while(bg==='rgba(0, 0, 0, 0)'&&n.parentElement){n=n.parentElement;bg=getComputedStyle(n).backgroundColor}return{text:e.innerText?.trim()||e.getAttribute('aria-label'),href:e.getAttribute('href'),tag:e.tagName,id:e.id,fg:s.color,bg,border:[s.borderColor,s.borderWidth],outline:[s.outlineColor,s.outlineWidth,s.outlineOffset,s.outlineStyle],font:[s.fontFamily,s.fontSize,s.fontWeight,s.lineHeight],hover:e.matches(':hover'),focused:e===document.activeElement,focusVisible:e.matches(':focus-visible'),focusSurface:(()=>{let n=Number.parseFloat(s.outlineOffset)<0?e:e.parentElement;while(n&&getComputedStyle(n).backgroundColor==='rgba(0, 0, 0, 0)')n=n.parentElement;return n?getComputedStyle(n).backgroundColor:'rgb(255, 255, 255)'})(),rects:[...e.getClientRects()].map(q=>({x:q.x,y:q.y+scrollY,w:q.width,h:q.height})),box:{x:r.x,y:r.y+scrollY,w:r.width,h:r.height},viewportY:r.y}};
const active=p=>p.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.innerText?.trim().slice(0,80),href:document.activeElement.getAttribute('href')}));
const result={evidenceType:'ACTUAL_RUNTIME',widths:[],errors:[],network:[],expectedCopy:expected};
async function states(p,loc){const records=[];for(let i=0;i<await loc.count();i++){const a=loc.nth(i);if(!await a.isVisible())continue;await p.mouse.move(0,0);await p.evaluate(()=>document.activeElement.blur());const normal=await a.evaluate(desc);await a.hover();const hover=await a.evaluate(desc);await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');const focus=await a.evaluate(desc);for(const x of[normal,hover,focus]){x.ratio=ratio(x.fg,x.bg);x.focusRatio=ratio(x.outline[0],x.focusSurface)};records.push({normal,hover,focus})}return records}
async function ready(p,target=url){await p.goto(target);await p.evaluate(()=>document.fonts.ready)}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();for(const width of[1440,768,390]){const p=await browser.newPage({viewport:{width,height:width===390?844:900},deviceScaleFactor:width===390?2:1});p.on('pageerror',e=>result.errors.push(e.message));await p.route('**/*',r=>{if(/^https?:/.test(r.request().url())){result.network.push(r.request().url());return r.abort()}return r.continue()});await ready(p);const row={width};row.copy=await copy(p);
row.normal=await p.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}},stat=e=>{const s=getComputedStyle(e);return{text:e.textContent,box:box(e),font:s.font,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}};return{scrollWidth:document.documentElement.scrollWidth,header:box(document.querySelector('header')),images:[...document.images].map(e=>({src:e.getAttribute('src'),loaded:e.complete&&e.naturalWidth>0,box:box(e)})),current:[...document.querySelectorAll('[aria-current]')].map(e=>({text:e.textContent,href:e.getAttribute('href')})),paragraphs:[...document.querySelectorAll('main p')].map(stat),applications:[...document.querySelectorAll('.contexts article')].map(e=>({box:box(e),heading:stat(e.querySelector('h3')),links:[...e.querySelectorAll('a')].map(a=>({text:a.textContent,href:a.getAttribute('href'),box:box(a)}))})),headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(stat)}});
const cdp=await p.context().newCDPSession(p);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'.module-1 p'});row.actualFonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});await cdp.detach();
await p.mouse.move(0,0);row.normalRenderMatches=[];for(const asset of inv.assets.filter(a=>a.logicalViewport.width===width&&a.state==='normal')){await p.evaluate(()=>scrollTo(0,0));const shot=await p.screenshot({clip:asset.clip,fullPage:true});row.normalRenderMatches.push({path:asset.relativePath,byteMatch:Buffer.from(shot).equals(read(asset.path))})};row.controls=await states(p,p.locator('header a,header button,main a,footer a,footer button'));
await ready(p);for(const a of await p.locator('main a:not([href^="#"])').all())await a.click();row.navigation={evidenceType:'LOCAL_SIMULATION',records:await p.evaluate(()=>window.localNavigation)};
await ready(p);if(width<1101){const t=p.locator('.menuButton');await t.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');row.menu={entry:await active(p),hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),inert:await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].map(s=>({s,inert:document.querySelector(s).inert}))),overflow:await p.evaluate(()=>document.body.style.overflow)};await p.locator('main a').first().evaluate(e=>e.focus());row.menu.backgroundFocus=await active(p);await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');row.menu.forward=await active(p);await p.keyboard.press('Shift+Tab');row.menu.backward=await active(p);row.menu.states=await states(p,p.locator('.mobileNav a,.menuButton'));await p.keyboard.press('Escape');row.menu.escape={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p),inert:await p.locator('main').evaluate(e=>e.inert)};await t.press('Enter');await t.press('Enter');row.menu.close={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p)};await t.press('Enter');await p.locator('.mobileNav a[href="/products/"]').click();row.menu.selection={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p),record:await p.evaluate(()=>window.localNavigation.at(-1))};await t.press('Enter');await p.setViewportSize({width:1440,height:1000});await p.waitForFunction(()=>document.querySelector('.mobileNav').hidden);row.menu.breakpoint={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),inert:await p.locator('main').evaluate(e=>e.inert),overflow:await p.evaluate(()=>document.body.style.overflow),active:await active(p)};await p.setViewportSize({width,height:width===390?844:900})}
const ct=p.locator('#cookie-trigger');await ct.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');row.cookie={entry:await active(p),opened:await p.locator('dialog').evaluate(e=>e.open)};await p.locator('main a').first().evaluate(e=>e.focus());row.cookie.backgroundFocus=await active(p);await p.keyboard.press('Shift+Tab');row.cookie.backward=await active(p);await p.keyboard.press('Tab');row.cookie.forward=await active(p);row.cookie.states=await states(p,p.locator('dialog button,dialog a'));await p.keyboard.press('Escape');row.cookie.escape={closed:await p.locator('dialog').evaluate(e=>!e.open),active:await active(p)};await ct.press('Enter');await p.locator('dialog button').click();row.cookie.close={closed:await p.locator('dialog').evaluate(e=>!e.open),active:await active(p)};
const nojs=await browser.newPage({viewport:{width,height:1000},javaScriptEnabled:false});await nojs.route('**/*',r=>/^https?:/.test(r.request().url())?r.abort():r.continue());await ready(nojs);row.noJS=await copy(nojs);await nojs.close();await p.close();result.widths.push(row);fs.writeFileSync(out+'/runtime.json',JSON.stringify(result,null,2));console.log(JSON.stringify({width,copy:row.copy.matches,scrollWidth:row.normal.scrollWidth,heroMatch:row.heroImageByteMatch,controls:row.controls.length,lowContrast:row.controls.filter(x=>x.normal.text&&Math.min(x.normal.ratio,x.hover.ratio,x.focus.ratio)<4.5).map(x=>x.normal.text),focusFailed:row.controls.filter(x=>!x.focus.focusVisible).map(x=>x.normal.text),nojs:row.noJS.matches}));}await browser.close();console.log(JSON.stringify({identities:identity.records.length,identityFailed:identity.records.filter(x=>!x.match).length,dimensionsFailed:identity.pngDimensions.filter(x=>!x.match).length,errors:result.errors,network:result.network}));})().catch(e=>{fs.writeFileSync(out+'/failure.txt',String(e.stack));console.error(e);process.exit(1)});

