// Independent Gate 5 audit. Candidate and every upstream file are read-only.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../../../..'),base='pages/applications/04_planning/d32-gate4-v0.1/';
const read=p=>fs.readFileSync(path.join(root,p)),json=p=>JSON.parse(read(p));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const identity=p=>{const b=read(p);return {path:p,bytes:b.length,sha256:hash(b)}};
const checks=[];function check(id,pass,detail){checks.push({id,pass:!!pass,detail})}
const normalize=s=>s.replace(/\s+/g,' ').trim();
const expectedBundle='sha256:8275ccefa106ffca6186651b705f9a77bee9fe2a17a90981a3ecd2182a5ad618';
const freeze=json(base+'freeze.json'),lock=json(base+'source-lock.json'),evidence=json(base+'evidence-index.json'),inputs=json(base+'input-index.json');
function identities(group,items){for(const a of items){const b=identity(a.path);check(group+':'+a.path,b.bytes===a.bytes&&b.sha256===a.sha256,b)}}
identities('member',freeze.members);identities('dispatch',freeze.dispatch_inputs||[]);identities('input',lock.inputs);identities('dependency',lock.dependencies);identities('source',freeze.source_identity);
check('bundle-independent',expectedBundle===freeze.bundle_id&&expectedBundle==='sha256:'+hash(JSON.stringify(freeze.members.map(a=>identity(a.path)))),freeze.bundle_id);
check('inventory-count',freeze.members.length===30&&lock.inputs.length===35&&lock.dependencies.length===10&&evidence.formal_evidence.length===14,{members:freeze.members.length,inputs:lock.inputs.length,dependencies:lock.dependencies.length,formal:evidence.formal_evidence.length});
for(const a of evidence.formal_evidence){const b=read(a.path),v=identity(a.path);check('formal:'+a.path,v.sha256===a.sha256&&v.bytes===a.bytes&&b.readUInt32BE(16)===a.physical_width&&b.readUInt32BE(20)===a.physical_height&&a.physical_width===a.logical_width*a.dpr,{...v,width:b.readUInt32BE(16),height:b.readUInt32BE(20),dpr:a.dpr})}
const html=read(base+'application-visual.html').toString(),g3=read('pages/applications/04_planning/d32-gate3-v0.2/application-planning.html').toString();
check('closed-g3-body-parity',html.split('<body>')[1].split('</body>')[0]===g3.split('<body>')[1].split('</body>')[0],'Exact content between body tags; diff has only head visual.css inclusion and terminal newline outside body');
check('lock-and-evidence-source',JSON.stringify(lock.source)===JSON.stringify(freeze.source_identity)&&JSON.stringify(evidence.source_identity)===JSON.stringify(freeze.source_identity),freeze.source_identity);
check('input-index-parity',JSON.stringify(inputs.inputs)===JSON.stringify(lock.inputs)&&JSON.stringify(inputs.dependencies)===JSON.stringify(lock.dependencies),'Input and dependency rows compared');
const formal=json(base+'formal-render.json');check('capture-source-binding',JSON.stringify(formal.captures)===JSON.stringify(evidence.formal_evidence)&&JSON.stringify(formal.source_lock)===JSON.stringify(identity(base+'source-lock.json')),{browser:formal.browser,dpr:formal.dpr,captureCount:formal.captures.length});
const shared=require(path.join(root,'docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs')).renderSharedChrome({currentPageId:'APP-000',primaryLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf'});
for(const key of ['header','footer','dialog','style','behavior'])check('shared-exact:'+key,html.replace(/\r\n/g,'\n').includes(shared[key].replace(/\r\n/g,'\n')),key+' matches owner renderer output exactly');
const authorVerifier=require('child_process').execFileSync(process.execPath,[path.join(root,base,'finalize.cjs'),'--verify'],{encoding:'utf8'});
check('readonly-verifier',authorVerifier.includes('PASS'),authorVerifier.trim());
const visible=e=>!!(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden');
const relations=[['M-350','M-510','M-896','M-996','M-2196','M-895','M-52','M-2377'],['M-350','M-510','M-200','M-108','M-210','M-340','M-886','M-2377'],['M-510','M-200','M-108','M-210','M-340','M-886','M-2377'],['M-350','M-510','M-52','M-2377'],['M-350','M-2377'],['CR-901']];
async function metrics(p){return p.evaluate(()=>{const vis=e=>!!e.getClientRects().length;const els=s=>[...document.querySelectorAll(s)].filter(vis);const rect=e=>{const r=e.getBoundingClientRect();return {text:e.textContent.trim().slice(0,55),x:r.x,y:r.y,w:r.width,h:r.height}};const h=document.querySelector('h1'),s=getComputedStyle(h);return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,modules:els('[data-module]').length,collections:els('[data-collection]').length,steps:els('[data-evaluation-step]').length,grades:els('[data-grade-link]').length,plain:els('[data-grade-plain]').length,application:els('[data-application-action]').length,procurement:els('[data-procurement-card]').length,bodyRfq:els('[data-body-rfq]').length,sharedRfq:els('.headerRfq,.footerRfq').length,anchors:els('.heroLinks a').length,sentence:document.querySelector('[data-route-sentence]').textContent,small:els('a,button').filter(e=>!e.classList.contains('skip')).map(rect).filter(r=>r.w<43.9||r.h<43.9),overflow:els('main *,footer *,header *').map(rect).filter(r=>r.w>0&&(r.x<-.5||r.x+r.w>innerWidth+.5)),h1:{size:s.fontSize,weight:s.fontWeight,lines:h.getBoundingClientRect().height/parseFloat(s.lineHeight)},grids:['.rootHero','.applicationGrid','.steps','.procurementGrid'].map(q=>getComputedStyle(document.querySelector(q)).gridTemplateColumns.split(' ').length),font:document.fonts.check('16px Inter'),noForms:!document.querySelector('form'),badRoutes:els('main a').map(e=>e.getAttribute('href')).filter(h=>!h||h==='javascript:'||h.includes('?')),neutral:els('[data-grade-plain]').every(e=>{const s=getComputedStyle(e);return s.borderTopWidth==='0px'&&s.backgroundColor==='rgba(0, 0, 0, 0)'&&e.tagName==='SPAN'&&!e.hasAttribute('tabindex')})}})}
(async()=>{const browser=await chromium.launch({headless:true});const runtimeErrors=[];const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});const p=await context.newPage();p.on('pageerror',e=>runtimeErrors.push(e.message));const url=pathToFileURL(path.join(root,base,'application-visual.html')).href;
const open=async width=>{await p.setViewportSize({width,height:1000});await p.goto(url);await p.evaluate(()=>document.fonts.ready)};
await open(1440);
const bodyText=await p.evaluate(()=>{const walker=document.createTreeWalker(document.querySelector('main'),NodeFilter.SHOW_TEXT);let n,out=[];while(n=walker.nextNode()){const e=n.parentElement;if(e.closest('.eyebrow,.stepNumber')||!e.getClientRects().length)continue;out.push(n.textContent)}return out.join(' ')});
let buyer=read('pages/applications/04_planning/APP-000_GATE2_FULL_BUYER_CLEAN_COPY_V1.0.md').toString().split('Home › Applications')[1].split('\n---')[0];buyer='Home › Applications'+buyer;buyer=buyer.replace(/<a[^>]*><\/a>/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^[#]+\s*/gm,'').replace(/^\d+\.\s*/gm,'').replace(/^-\s*/gm,'').replace(/\*\*/g,'').replace(/ · /g,' ');
check('buyer-copy-bidirectional',normalize(bodyText)===normalize(buyer),{actual:normalize(bodyText),expected:normalize(buyer),excluded:'Shared RootPageHero eyebrow and three approved step numerals only'});
const actualRelations=await p.locator('[data-collection]').evaluateAll(es=>es.map(e=>[...e.querySelectorAll('[data-grade-link]')].map(e=>e.textContent.trim())));check('six-collections-thirty-relations',JSON.stringify(actualRelations)===JSON.stringify(relations),actualRelations);
check('no-process-faq',await p.locator('[data-module*="PROCESS"],[data-module*="FAQ"],details').count()===0,'Current five-module approved structure');
const targets=await p.evaluate(()=>({grades:[...document.querySelectorAll('[data-grade-link]')].map(e=>({text:e.textContent.trim(),href:e.getAttribute('href')})),applications:[...document.querySelectorAll('[data-application-action]')].map(e=>({owner:e.dataset.ownerPageId,href:e.getAttribute('href')})),procurement:[...document.querySelectorAll('.procurementCard a')].map(e=>e.getAttribute('href')),rfq:[...document.querySelectorAll('[data-body-rfq]')].map(e=>e.getAttribute('href'))}));
check('grade-targets',targets.grades.every(e=>e.href==='/products/'+e.text.toLowerCase()+'/'),targets.grades);
check('application-owner-targets',JSON.stringify(targets.applications)===JSON.stringify([['APP-COAT','coatings'],['APP-PLAS','plastics'],['APP-MB','masterbatch'],['APP-INK','printing-inks'],['APP-PAPER','paper']].map(([owner,x])=>({owner,href:'/applications/titanium-dioxide-for-'+x+'/'}))),targets.applications);
check('procurement-rfq-targets',JSON.stringify(targets.procurement)===JSON.stringify(['/products/','/documents/','/markets/'])&&targets.rfq.every(x=>x==='/request-a-quote/'),targets);
const teal=await p.locator('main a').evaluateAll(es=>es.map(e=>{const s=getComputedStyle(e);return {text:e.textContent.trim(),color:s.color,bg:s.backgroundColor,border:s.borderTopColor,borderWidth:s.borderTopWidth}}));check('functional-teal',teal.every(s=>(s.color==='rgb(0, 128, 120)'||s.color==='rgb(255, 255, 255)'&&s.bg==='rgb(0, 128, 120)')&&(s.borderWidth==='0px'||s.border==='rgb(0, 128, 120)')),teal);
for(const width of [1440,1024,768,390,320]){await open(width);const m=await metrics(p);check('layout:'+width,m.scrollWidth<=width&&m.overflow.length===0&&m.small.length===0,m);check('type-grid:'+width,m.font&&m.h1.size===(width>=1024?'56px':width>=768?'44px':'36px')&&m.h1.weight==='700'&&m.h1.lines<=3.02&&JSON.stringify(m.grids)===JSON.stringify(width>=1024?[2,2,3,3]:width>=768?[1,2,3,3]:[1,1,1,1]),{h1:m.h1,grids:m.grids,font:m.font});
for(const state of ['full','grade-only','application-only','none']){await p.evaluate(s=>window.appPlanning.setScenario(s),state);const x=await metrics(p),g=state==='full'||state==='grade-only',a=state==='full'||state==='application-only',n=state==='none';const sentence=state==='full'?'Open a grade page for product information, or explore an application for guidance on what to evaluate.':state==='grade-only'?'Open a grade page for product information.':state==='application-only'?'Explore an application for guidance on what to evaluate.':'';check('route:'+width+':'+state,x.collections===6&&x.steps===3&&x.anchors===6&&x.grades===(g?30:0)&&x.plain===(g?0:30)&&x.application===(a?5:0)&&x.procurement===(n?0:3)&&x.bodyRfq===(n?0:2)&&x.sharedRfq===2&&x.modules===(n?3:5)&&x.sentence===sentence&&x.neutral&&x.badRoutes.length===0&&x.noForms&&x.overflow.length===0&&x.small.length===0,x)}
}
for(const width of [1024,768,390,320]){await open(width);await p.locator('.menuButton').click();let m=await p.evaluate(()=>({links:[...document.querySelectorAll('.mobileNav a')].map(e=>e.textContent.trim()),entry:document.activeElement===document.querySelector('.mobileNav a'),inert:['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert),expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),current:document.querySelectorAll('.mobileNav [aria-current="page"]').length}));check('menu-open:'+width,m.links.length===8&&m.entry&&m.inert&&m.expanded==='true'&&m.current===1,m);
await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');check('menu-forward-trap:'+width,await p.locator('.menuButton').evaluate(e=>document.activeElement===e),'Last navigation link Tab returns to Close');await p.keyboard.press('Shift+Tab');check('menu-backward-trap:'+width,await p.locator('.mobileNav a').last().evaluate(e=>document.activeElement===e),'Close Shift+Tab returns to last link');await p.keyboard.press('Escape');check('menu-escape:'+width,await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.activeElement===document.querySelector('.menuButton')&&!document.querySelector('main').inert&&document.body.style.overflow===''),'Closed, inert cleared, focus returned');
await p.locator('.menuButton').click();await p.locator('.menuButton').click();check('menu-close:'+width,await p.locator('.menuButton').evaluate(e=>e.getAttribute('aria-expanded')==='false'&&document.activeElement===e),'Close button');}
await open(390);await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:1000});await p.waitForFunction(()=>document.querySelector('.mobileNav').hidden);check('menu-desktop-resize',await p.evaluate(()=>!document.querySelector('main').inert&&document.body.style.overflow===''),'Resize dismisses overlay');
await open(390);await p.locator('.menuButton').click();await p.locator('.mobileNav a').first().evaluate(e=>e.addEventListener('click',event=>event.preventDefault()));await p.locator('.mobileNav a').first().click();check('menu-selection-dismiss',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.activeElement===document.querySelector('.menuButton')),'Actual link click, navigation default suppressed only to avoid real request');
for(const width of [1440,768,390,320]){await open(width);await p.locator('#cookie-trigger').click();const c=await p.locator('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return {open:e.open,modal:e.matches(':modal'),entry:document.activeElement===e.querySelector('button'),w:r.width,x:r.x,y:r.y,h:r.height,innerWidth,innerHeight,label:e.getAttribute('aria-labelledby'),description:e.getAttribute('aria-describedby')}});check('cookie-open:'+width,c.open&&c.modal&&c.entry&&c.x>=0&&c.x+c.w<=width&&c.y>=0&&c.y+c.h<=1000&&c.label==='cookie-title'&&c.description==='cookie-body',c);await p.keyboard.press('Shift+Tab');check('cookie-backward-trap:'+width,await p.locator('dialog a').evaluate(e=>document.activeElement===e),'Close Shift+Tab to policy');await p.keyboard.press('Tab');check('cookie-forward-trap:'+width,await p.locator('[data-cookie-close]').evaluate(e=>document.activeElement===e),'Policy Tab to Close');await p.keyboard.press('Escape');await p.waitForFunction(()=>document.activeElement===document.querySelector('#cookie-trigger'));check('cookie-escape:'+width,await p.locator('dialog').evaluate(e=>!e.open),'Native Escape and trigger focus return');await p.locator('#cookie-trigger').click();await p.locator('[data-cookie-close]').click();await p.waitForFunction(()=>document.activeElement===document.querySelector('#cookie-trigger'));check('cookie-close:'+width,await p.locator('dialog').evaluate(e=>!e.open),'Close and trigger focus return');}
await open(390);for(const a of ['#application-selector','#application-coatings','#application-plastics','#application-masterbatch','#application-printing-inks','#application-paper','#application-specialty-materials']){await p.locator('a[href="'+a+'"]').first().click();await p.waitForFunction(a=>{const y=document.querySelector(a).getBoundingClientRect().top;return y>=0&&y<150},a);const v=await p.locator(a).evaluate(e=>({y:e.getBoundingClientRect().top,hash:location.hash}));check('anchor:'+a,v.hash===a&&v.y>=0&&v.y<150,v)}
for(const [width,selector] of [[390,'.heroText .primary'],[768,'[data-grade-link]'],[390,'[data-application-action]'],[390,'.procurementCard a'],[390,'.heroLinks a']]){await open(width);await p.keyboard.press('Tab');await p.locator(selector).first().focus();const s=await p.locator(selector).first().evaluate(e=>{const s=getComputedStyle(e);return {focused:document.activeElement===e,color:s.outlineColor,width:s.outlineWidth,style:s.outlineStyle}});check('focus:'+width+':'+selector,s.focused&&parseFloat(s.width)>=2&&s.style!=='none',s)}
await open(1440);for(const selector of ['.heroText .primary','.heroLinks a','[data-grade-link]']){await p.mouse.move(0,0);const before=await p.locator(selector).first().evaluate(e=>({bg:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));await p.locator(selector).first().hover();const after=await p.locator(selector).first().evaluate(e=>({bg:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));check('hover:'+selector,JSON.stringify(before)!==JSON.stringify(after),{before,after})}
for(const width of [390,320]){const ctx=await browser.newContext({javaScriptEnabled:false,viewport:{width,height:1000}});const q=await ctx.newPage();await q.goto(url);await q.evaluate(()=>document.fonts.ready);const m=await metrics(q);check('no-js:'+width,m.collections===6&&m.steps===3&&m.grades===30&&m.application===5&&m.procurement===3&&m.bodyRfq===2&&m.overflow.length===0&&m.scrollWidth<=width,m);await ctx.close()}
await open(720);const zoom=await metrics(p);check('logical-200pct-reflow',zoom.scrollWidth<=720&&zoom.overflow.length===0&&zoom.collections===6&&zoom.small.length===0,{...zoom,method:'1440 CSS-pixel desktop at 200% represented by 720 CSS-pixel layout viewport; not a native browser zoom claim'});
await open(390);await p.evaluate(()=>{const els=[...document.querySelectorAll('main h1,main h2,main h3,main p,main a,main span')];const sizes=els.map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);sizes.forEach(([e,s])=>e.style.fontSize=s*2+'px')});const enlarged=await metrics(p);check('text-200pct',enlarged.scrollWidth<=390&&enlarged.overflow.length===0&&enlarged.small.length===0&&enlarged.collections===6,{...enlarged,method:'Temporary in-memory page-owned text font-size doubling; no candidate writes'});
check('browser-errors',runtimeErrors.length===0,runtimeErrors);identities('post-review-member',freeze.members);identities('post-review-source',freeze.source_identity);identities('post-review-dependency',lock.dependencies);
const result={reviewer:'/root/app_gate5_independent_review',mode:'INDEPENDENT_REVIEW / INITIAL',dispatch:'APP000-D32-G5-INITIAL-20260920-01',created_at:new Date().toISOString(),bundle:freeze.bundle_id,source:freeze.source_identity,environment:{node:process.version,chromium:browser.version(),transport:'Local file, DPR 1, no external route requests'},author_verifier:authorVerifier.trim(),formal_visual_review:{count:14,method:'Each original PNG viewed at native pixel width; long pages covered by overlapping in-memory crops, never saved',home_comparison:[1440,768,390],additional_saved_screenshots:0},checks,summary:{assertions:checks.length,pass:checks.filter(c=>c.pass).length,fail:checks.filter(c=>!c.pass).length}};
fs.writeFileSync(path.join(__dirname,'observations.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));console.log(JSON.stringify(checks.filter(c=>!c.pass),null,2));await browser.close();process.exitCode=result.summary.fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
