const fs = require('fs'), path = require('path'), crypto = require('crypto');
const mods = 'C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {chromium} = require(mods+'playwright'), sharp = require(mods+'sharp'), {marked} = require(mods+'marked');
const root='D:/23MySec', work=root+'/pages/applications/paper/04_planning/gate4-v0.1', source=work+'/APP-PAPER_GATE4_COMPLETE_VISUAL_V0.1.html';
const ident=p=>{let b=fs.readFileSync(p);return {path:p.replaceAll('\\','/'),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}};
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const out={dispatch_id:'G5-9PAGE-REVIEW-20260907-01/APP-PAPER/INITIAL',reviewer:'/root/g5_paper',author:'/root/gate4_paper_execute',mode:'INDEPENDENT_REVIEW',review_scope:'INITIAL',started_at:new Date().toISOString(),source_identity:ident(source),checks:[],file_audit:[],viewports:[],panels:[],new_persistent_screenshots:0};
const check=(name,pass,observed,type='ACTUAL_RUNTIME')=>out.checks.push({name,pass,observed,evidence_type:type});
const norm=s=>s.replace(/\s+/g,'');
async function audit(obj,origin){if(Array.isArray(obj)){for(const v of obj)await audit(v,origin);return}if(!obj||typeof obj!=='object')return;if(obj.path&&obj.sha256){let actual;try{actual=ident(obj.path)}catch(e){actual={error:e.message}}let item={origin,expected:obj,actual,pass:actual.sha256===obj.sha256.toLowerCase()&&(obj.bytes===undefined||obj.bytes===actual.bytes)};if(obj.path.endsWith('.png')&&!actual.error){let m=await sharp(obj.path).metadata();item.physical={width:m.width,height:m.height};if(obj.physical)item.pass&&=m.width===obj.physical.width&&m.height===obj.physical.height;}out.file_audit.push(item);}for(const [k,v]of Object.entries(obj))if(v&&typeof v==='object')await audit(v,origin);}
async function geom(page){return page.evaluate(()=>{const vis=e=>e.checkVisibility({checkOpacity:true,checkVisibilityCSS:true})&&e.getBoundingClientRect().width>2&&e.getBoundingClientRect().height>2&&!e.closest('thead');const rect=e=>{let r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};const els=[...document.querySelectorAll('main *,header *,footer *,dialog *')].filter(vis);const controls=[...document.querySelectorAll('a,button')].filter(vis).filter(e=>!e.closest('[hidden]')).map(e=>({label:e.textContent.trim()||e.getAttribute('aria-label'),...rect(e)}));const clipped=els.filter(e=>{let s=getComputedStyle(e);return ((['hidden','clip'].includes(s.overflowX)&&e.scrollWidth>e.clientWidth+1)||(['hidden','clip'].includes(s.overflowY)&&e.scrollHeight>e.clientHeight+1)||s.textOverflow==='ellipsis')}).map(e=>e.outerHTML.slice(0,150));const overflow=els.filter(e=>{let r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5}).map(e=>e.outerHTML.slice(0,150));return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,dpr:devicePixelRatio,fontReady:document.fonts.check('16px Inter'),images:[...document.images].map(e=>({src:e.src,loaded:e.complete&&e.naturalWidth>0,...rect(e)})),header:rect(document.querySelector('header')),footer:rect(document.querySelector('footer')),controls,clipped,overflow,modules:[...document.querySelectorAll('[data-module]')].map(e=>({id:e.dataset.module,heading:e.querySelector('h1,h2').textContent,...rect(e)})),links:[...document.querySelectorAll('main a')].map(e=>({text:e.textContent,href:e.getAttribute('href')})),tables:[...document.querySelectorAll('main table')].map(e=>({class:e.closest('section').className,tbodyDisplay:getComputedStyle(e.tBodies[0]).display,columns:getComputedStyle(e.tBodies[0]).gridTemplateColumns,rows:[...e.tBodies[0].rows].map(r=>({cells:[...r.cells].map(c=>({label:c.dataset.label,text:c.textContent,...rect(c),labelStyle:getComputedStyle(c,'::before').content})),style:['backgroundColor','borderColor','borderRadius','fontSize','fontWeight'].map(k=>getComputedStyle(r)[k])}))})),formCount:document.querySelectorAll('main form,input,select,details').length,canonicalCount:document.querySelectorAll('link[rel=canonical],script[type="application/ld+json"]').length};});}
async function focusStyle(page,sel){await page.locator(sel).first().focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return page.locator(sel).first().evaluate(e=>{let s=getComputedStyle(e);return {active:document.activeElement===e,visible:e.matches(':focus-visible'),outline:s.outline,offset:s.outlineOffset,color:s.color,background:s.backgroundColor}})}
(async()=>{
 for(const f of ['APP-PAPER_GATE4_FREEZE_RECORD_V0.1.json','APP-PAPER_GATE4_INPUT_INDEX_V0.1.json','APP-PAPER_GATE4_EVIDENCE_INDEX_V0.1.json','APP-PAPER_GATE4_FORMAL_OBSERVATIONS_V0.1.json'])await audit(read(work+'/'+f),f);
 out.binding={freeze:ident(work+'/APP-PAPER_GATE4_FREEZE_RECORD_V0.1.json'),input:ident(work+'/APP-PAPER_GATE4_INPUT_INDEX_V0.1.json'),evidence:ident(work+'/APP-PAPER_GATE4_EVIDENCE_INDEX_V0.1.json'),methods:['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.9.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE5_GATE6_ACCEPTANCE_CONTRACT_V1.0.md'].map(p=>ident(root+'/'+p))};
 for(const [w,n,cols,h]of [[1440,4,1,2200],[768,2,2,2450],[390,2,3,2450]]){let orig=work+`/approval_core/APP-PAPER_GATE4_${w}_FULL_FORMAL_V0.1.png`,meta=await sharp(orig).metadata();for(let i=0;i<n;i++)for(let c=0;c<cols;c++){let y=(i*cols+c)*h;if(y>=meta.height)continue;let height=Math.min(h,meta.height-y),panel=work+`/diagnostic_support/READ_PANEL_${w}_${i+1}.png`;let a=await sharp(orig).extract({left:0,top:y,width:w,height}).removeAlpha().raw().toBuffer(),b=await sharp(panel).extract({left:c*w,top:0,width:w,height}).removeAlpha().raw().toBuffer();out.panels.push({panel,column:c+1,source_y:y,height,width:w,pixels_identical:a.equals(b)});}}
 check('read_panels_complete_exact_pixels',out.panels.every(p=>p.pixels_identical),out.panels,'SOURCE_INSPECTION');
 const html=fs.readFileSync(source,'utf8'), g3=fs.readFileSync(root+'/pages/applications/paper/04_planning/gate3-v0.3/APP-PAPER_GATE3_RESPONSIVE_WIREFRAME_V0.3.html','utf8');
 check('approved_gate3_main_unchanged',html.match(/<main[\s\S]*?<\/main>/)[0]===g3.match(/<main[\s\S]*?<\/main>/)[0],ident(root+'/pages/applications/paper/04_planning/gate3-v0.3/APP-PAPER_GATE3_RESPONSIVE_WIREFRAME_V0.3.html'),'SOURCE_INSPECTION');
 const shared=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'APP-000',primaryLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg'});
 check('owner_payload_exact',['header','footer','dialog','style','behavior'].every(k=>html.includes(shared[k])),Object.keys(shared),'SOURCE_INSPECTION');
 const md=fs.readFileSync(root+'/pages/applications/paper/04_planning/APP-PAPER_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').split('<!-- BUYER_COPY_START -->')[1].split('<!-- BUYER_COPY_END -->')[0], expected=marked.parse(md);
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});out.browser=browser.version();
 const url=require('url').pathToFileURL(source).href;
 for(const vp of [{width:1440,height:1000},{width:768,height:1024},{width:390,height:844}]){
 const ctx=await browser.newContext({viewport:vp,deviceScaleFactor:1,reducedMotion:'reduce'}),page=await ctx.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.evaluate(()=>document.fonts.ready);
 const content=await page.evaluate(expected=>{let d=new DOMParser().parseFromString(expected,'text/html');return {expected:d.body.textContent,actual:document.querySelector('main').textContent,expectedLinks:[...d.querySelectorAll('a')].map(e=>({text:e.textContent,href:e.getAttribute('href')}))}},expected), g=await geom(page);out.viewports.push({viewport:vp,geometry:g});
 check(`${vp.width}_B_complete_text_links`,norm(content.expected)===norm(content.actual)&&JSON.stringify(content.expectedLinks)===JSON.stringify(g.links),{text_equal:norm(content.expected)===norm(content.actual),links:g.links});
 check(`${vp.width}_geometry`,!g.overflow.length&&!g.clipped.length&&g.scrollWidth===vp.width&&g.controls.every(c=>c.width>=43.99&&c.height>=43.99),g);
 check(`${vp.width}_content_counts_assets`,g.modules.length===11&&g.tables.map(t=>t.rows.length).join(',')==='4,4,2'&&g.links.length===15&&g.images.every(i=>i.loaded)&&g.fontReady&&g.dpr===1,{moduleCount:g.modules.length,rows:g.tables.map(t=>t.rows.length),links:g.links.length,font:g.fontReady,images:g.images,header:g.header,forms:g.formCount,canonical:g.canonicalCount});
 check(`${vp.width}_grade_neutrality`,JSON.stringify(g.tables[2].rows[0].style)===JSON.stringify(g.tables[2].rows[1].style)&&g.tables[2].rows.map(r=>r.cells[0].text).join(',')==='M-350,M-2377',g.tables[2]);
 let scroll=[];for(let y=0;y<g.height;y+=vp.height-100){await page.evaluate(y=>scrollTo(0,y),y);scroll.push(await page.evaluate(()=>({y:scrollY,bottom:scrollY+innerHeight,visibleModules:[...document.querySelectorAll('[data-module]')].filter(e=>{let r=e.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).map(e=>e.dataset.module)})));}out.viewports.at(-1).runtime_scroll_coverage=scroll;
 for(const sel of ['#define-the-paper-result-and-system','#grades-to-review']){await page.evaluate(()=>scrollTo(0,0));await page.locator(`.heroActions a[href="${sel}"]`).click();let a=await page.locator(sel).first().evaluate(e=>({top:e.getBoundingClientRect().top,hash:location.hash,outline:getComputedStyle(e).outline}));check(`${vp.width}_anchor_${sel}`,a.hash===sel&&a.top>=0&&a.top<80,a);}
 for(const sel of ['.heroActions a:first-child','.heroActions a:last-child','.grades a','.request-paths a','.sources a']){let loc=page.locator(sel).first();await loc.hover();let hover=await loc.evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));let focus=await focusStyle(page,sel+(sel.includes(':')?'':':first-of-type'));check(`${vp.width}_state_${sel}`,focus.active&&focus.visible&&focus.outline.includes('3px'),{hover,focus});}
 if(vp.width<1101){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();let entry=await page.evaluate(()=>({focus:document.activeElement.textContent,expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),inert:[...document.querySelectorAll('main,footer,.logoLink,.headerRfq')].every(e=>e.inert),current:document.querySelector('.mobileNav [aria-current]').textContent,links:[...document.querySelectorAll('.mobileNav a')].map(e=>({text:e.textContent,href:e.getAttribute('href')}))}));check(`${vp.width}_menu_entry`,entry.focus==='Home'&&entry.inert&&entry.current==='Applications'&&entry.expanded==='true',entry);
 await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let forward=await page.locator('.menuButton').evaluate(e=>document.activeElement===e);await page.keyboard.press('Shift+Tab');let backward=await page.locator('.mobileNav a').last().evaluate(e=>document.activeElement===e);let overlay=await geom(page);check(`${vp.width}_menu_loops_targets`,forward&&backward&&overlay.controls.every(c=>c.width>=44&&c.height>=44),{forward,backward,controls:overlay.controls});await page.keyboard.press('Escape');check(`${vp.width}_menu_escape`,await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.activeElement===document.querySelector('.menuButton')&&!document.querySelector('main').inert),'Escape close and trigger return');
 await page.locator('.menuButton').click();await page.locator('.mobileNav a').first().evaluate(e=>e.addEventListener('click',ev=>ev.preventDefault(),{once:true}));await page.locator('.mobileNav a').first().click();check(`${vp.width}_menu_selection`,await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert),'Actual click; navigation default prevented for local-only test','LOCAL_SIMULATION');
 await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:1000});check(`${vp.width}_menu_breakpoint`,await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''),'Desktop breakpoint closure');await page.setViewportSize(vp);}
 await page.locator('#cookie-trigger').click();let cookie=await page.evaluate(()=>({open:document.querySelector('dialog').open,focus:document.activeElement.hasAttribute('data-cookie-close'),rect:document.querySelector('dialog').getBoundingClientRect().toJSON()}));await page.keyboard.press('Shift+Tab');let back=await page.locator('.cookie-actions a').evaluate(e=>document.activeElement===e);await page.keyboard.press('Tab');let fw=await page.locator('[data-cookie-close]').evaluate(e=>document.activeElement===e);await page.locator('.headerRfq').evaluate(e=>e.focus());let blocked=await page.evaluate(()=>document.activeElement.closest('dialog')!==null);let dg=await geom(page);check(`${vp.width}_cookie_entry_loop_background`,cookie.open&&cookie.focus&&back&&fw&&blocked,{cookie,back,fw,blocked,controls:dg.controls.filter(c=>c.label==='Close'||c.label==='Read Cookie Policy')});await page.keyboard.press('Escape');check(`${vp.width}_cookie_escape_restore`,await page.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement.id==='cookie-trigger'),'Escape restores trigger');await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();check(`${vp.width}_cookie_close_restore`,await page.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement.id==='cookie-trigger'),'Close restores trigger');check(`${vp.width}_errors`,errors.length===0,errors);await ctx.close();
 }
 const ctx=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:false,reducedMotion:'reduce'}),p=await ctx.newPage();await p.goto(url);let nojs=await p.evaluate(()=>({text:document.querySelector('main').textContent,links:document.querySelectorAll('main a').length,modules:document.querySelectorAll('[data-module]').length}));check('noJS_core_content',nojs.links===15&&nojs.modules===11,nojs);await ctx.close();
 const rc=await browser.newContext({viewport:{width:720,height:1000},reducedMotion:'reduce'}),rp=await rc.newPage();await rp.goto(url);await rp.evaluate(()=>document.fonts.ready);let reflow=await geom(rp);check('720_effective_reflow_proxy',reflow.scrollWidth===720&&!reflow.clipped.length&&!reflow.overflow.length,{...reflow,limit:'viewport reflow proxy only; not actual browser 200% zoom'});await rc.close();await browser.close();
 out.finished_at=new Date().toISOString();out.summary={checks:out.checks.length,failed:out.checks.filter(c=>!c.pass).map(c=>c.name),fileReferences:out.file_audit.length,fileMismatches:out.file_audit.filter(c=>!c.pass).map(c=>({path:c.expected.path,expected:c.expected.sha256,actual:c.actual.sha256})),source_unchanged:ident(source).sha256===out.source_identity.sha256};fs.writeFileSync(__dirname+'/observations.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out.summary,null,2));
})().catch(e=>{out.failure=e.stack;fs.writeFileSync(__dirname+'/observations.json',JSON.stringify(out,null,2));console.error(e);process.exitCode=1});

