const fs=require('fs'),crypto=require('crypto'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),sharp=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='D:/23MySec/99_workspace/gate3-skill-validation-2026-09-07',cand=root+'/specimen-d',out=root+'/review-d/evidence',copy=JSON.parse(fs.readFileSync(root+'/copy.json')),manifest=JSON.parse(fs.readFileSync(cand+'/assets.json'));
const id=f=>({bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});const result={source:id(cand+'/source.html'),assets:[],views:[],network:[]};
async function same(a,b){const x=await sharp(a).raw().toBuffer({resolveWithObject:true}),y=await sharp(b).raw().toBuffer({resolveWithObject:true});return x.info.width===y.info.width&&x.info.height===y.info.height&&x.data.equals(y.data)}
async function snapshot(p){return p.evaluate(()=>{const r=e=>{const b=e.getBoundingClientRect();return {width:b.width,height:b.height,y:b.y+scrollY}};const s=document.querySelector('#record'),q=document.querySelector('#quantity'),d=document.querySelector('dialog');return {focus:document.activeElement.id||document.activeElement.tagName,hasFocus:document.hasFocus(),inside:!!document.activeElement.closest('dialog'),modal:d.matches(':modal'),open:d.open,hash:location.hash,scrollY,scrollWidth:document.documentElement.scrollWidth,width:innerWidth,select:{...r(s),value:s.value,whiteSpace:getComputedStyle(s).whiteSpace,overflow:getComputedStyle(s).overflow,scrollWidth:s.scrollWidth,clientWidth:s.clientWidth},quantity:{...r(q),value:q.value,error:!document.querySelector('#quantity-error').hidden},summary:!document.querySelector('#form-summary').hidden,success:!document.querySelector('#confirmation').hidden,context:document.querySelector('#context').value,privacy:{...r(document.querySelector('.privacy-line')),overflow:getComputedStyle(document.querySelector('.privacy-line')).overflow,link:r(document.querySelector('.privacy-line a'))}}})}
const settled=async p=>p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
(async()=>{for(const a of manifest.assets){const f=cand+'/'+a.path,m=await sharp(f).metadata(),i=id(f);result.assets.push({path:a.path,...i,width:m.width,height:m.height,dpr:a.dpr,hashMatch:i.sha256===a.sha256,bytesMatch:i.bytes===a.bytes,sourceMatch:a.sourceSha256===result.source.sha256})}
const b=await chromium.launch({headless:true});result.browser=b.version();for(const width of [1440,768,390]){const p=await b.newPage({viewport:{width,height:900},deviceScaleFactor:1});await p.route('**/*',r=>{if(!r.request().url().startsWith('file:')){result.network.push(r.request().url());return r.abort()}return r.continue()});await p.goto('file:///'+cand+'/source.html');const v={width,initial:await snapshot(p),pixel:{}};await p.screenshot({path:out+'/'+width+'-initial.png',fullPage:true});v.pixel.initial=await same(out+'/'+width+'-initial.png',cand+'/'+width+'-initial.png');await p.locator('form').screenshot({path:out+'/'+width+'-initial-form.png'});
if(width!==1440){v.menu={links:[],forward:[],backward:[]};await p.locator('#menu').click();v.menu.entry=await snapshot(p);for(let i=0;i<7;i++){await p.keyboard.press('Tab');v.menu.forward.push(await snapshot(p))}await p.locator('#close-menu').focus();for(let i=0;i<7;i++){await p.keyboard.press('Shift+Tab');v.menu.backward.push(await snapshot(p))}await p.locator('#close-menu').focus();v.menu.background=await p.evaluate(()=>{document.querySelector('#name').focus();return document.activeElement.id});await p.keyboard.press('Escape');await settled(p);v.menu.escape=await snapshot(p);await p.locator('#menu').click();await p.locator('#close-menu').click();await settled(p);v.menu.close=await snapshot(p);
for(let i=0;i<5;i++){await p.locator('#menu').click();const a=p.locator('#menu-dialog a').nth(i),href=await a.getAttribute('href');await a.click();await settled(p);const observed=await snapshot(p),target=await p.evaluate(h=>{const e=document.querySelector(h),r=e.getBoundingClientRect();return {top:r.top,documentY:r.top+scrollY,expectedScroll:Math.min(r.top+scrollY,document.documentElement.scrollHeight-innerHeight)}},href);v.menu.links.push({href,observed,target});if(i===1)await p.screenshot({path:out+'/'+width+'-after-comparison-link.png'});}
await p.goto('file:///'+cand+'/source.html');await p.locator('#menu').click();await p.screenshot({path:out+'/'+width+'-menu.png'});if(width===390)v.pixel.menu=await same(out+'/390-menu.png',cand+'/390-menu.png');await p.keyboard.press('Escape');await settled(p);
}
if(width===390){for(const s of await p.locator('details summary').all())await s.click();await p.screenshot({path:out+'/390-expanded.png',fullPage:true});v.pixel.expanded=await same(out+'/390-expanded.png',cand+'/390-expanded.png');await p.locator('#submit').click();await p.screenshot({path:out+'/390-invalid.png',fullPage:true});v.pixel.invalid=await same(out+'/390-invalid.png',cand+'/390-invalid.png');v.empty=await snapshot(p);await p.locator('#name').fill('Example Person');await p.locator('#email').fill('example@example.invalid');await p.locator('#quantity').fill('0.5');await p.locator('#submit').click();await p.screenshot({path:out+'/390-success.png',fullPage:true});v.pixel.success=await same(out+'/390-success.png',cand+'/390-success.png');
await p.locator('#record').selectOption({label:copy.records[1].name});await p.locator('#context').fill('Retained test context');await p.locator('#quantity').fill('0');await p.locator('#submit').click();v.betaError=await snapshot(p);await p.locator('form').screenshot({path:out+'/390-beta-error-form.png'});await p.locator('#quantity').fill('0.001');await p.locator('#submit').click();v.betaSuccess=await snapshot(p);await p.locator('form').screenshot({path:out+'/390-beta-success-form.png'});await p.locator('#record').screenshot({path:out+'/390-beta-selected.png'});await p.locator('#record').selectOption({label:copy.form.unsure});v.reset=await snapshot(p);await p.locator('.privacy-line a').click();v.privacyNavigation=await snapshot(p);
}
result.views.push(v);await p.close();}await b.close();fs.writeFileSync(out+'/observations.json',JSON.stringify(result,null,2));console.log(JSON.stringify({source:result.source,assets:result.assets,views:result.views.map(v=>({width:v.width,pixel:v.pixel,menu:v.menu?{links:v.menu.links.map(l=>({href:l.href,focus:l.observed.focus,open:l.observed.open,scroll:l.observed.scrollY,target:l.target})),forwardTrapped:v.menu.forward.every(s=>s.inside&&s.hasFocus),backwardTrapped:v.menu.backward.every(s=>s.inside&&s.hasFocus),escape:v.menu.escape.focus,close:v.menu.close.focus}:null,betaError:v.betaError,betaSuccess:v.betaSuccess}))},null,2));})();
