const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const pageRoot=path.resolve(__dirname,'../..'),candidate=path.join(pageRoot,'04_planning/gate5-v0.1'),out=__dirname;
fs.mkdirSync(out,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const json=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const checks=[]; const add=(id,pass,actual)=>checks.push({id,pass,actual});
const freeze=json(path.join(candidate,'approval_core/source-freeze.json'));
for(const x of [...freeze.sourceIdentity,...freeze.inputIdentity]){const b=fs.readFileSync(x.path);add('identity:'+path.relative(pageRoot,x.path),b.length===x.bytes&&sha(b)===x.sha256,{bytes:b.length,sha256:sha(b)});}
const inv=json(path.join(candidate,'approval_core/export-inventory.json'));
const records=Array.isArray(inv)?inv:(inv.captures||inv.exports||inv.assets||inv.records||[]);
add('formal-inventory-count',records.length===18,records.length);
for(const x of records){const p=path.resolve(candidate,x.relativePath||x.path);const b=fs.readFileSync(p);add('formal:'+path.basename(p),b.length===x.bytes&&sha(b)===x.sha256,{bytes:b.length,sha256:sha(b)});}
const htmlPath=path.join(candidate,freeze.entry);
const required=[
'Chloride Process Titanium Dioxide','Explore eight Malaysia-origin chloride-process titanium dioxide grades for applications including coatings, plastics, masterbatch, printing inks and paper. Open a grade page for product-specific information, or share your application and purchasing requirements for a quotation.',
'What the Chloride Process Tells You','At a high level, the chloride route converts titanium-bearing feedstock to titanium tetrachloride (TiCl4), purifies the intermediate and oxidizes it to form titanium dioxide. The base pigment then goes through further finishing and treatment to create individual commercial grades.','The process label helps identify how the base pigment was formed. It does not, by itself, determine how a grade will perform in your formulation or process. Grade-specific product information and application-relevant evaluation still matter.',
'Explore Chloride-Process Grades','These eight TiO2 Malaysia grades are classified as chloride-process products. Because application needs can overlap, compare the grades relevant to your formulation and process, then open the individual product pages for product-specific information.',
'How to Evaluate a Chloride-Process Grade','1. Define the intended system','2. Review the exact Grade','3. Validate and collect the needed information',
'Discuss Your Chloride-Process TiO2 Requirement','Ready to discuss a Grade, or still narrowing the list? Tell us the product or Grade you are evaluating—or choose Not sure / Need help—together with your application, quantity and destination. Our team will review your requirements and contact you using the details provided.'
];
const grades=[
['M-350','Excellent hue and high gloss with strong hiding power.','/products/m-350/'],
['M-510','TMP/TME-free multi-application grade with high brightness and durability.','/products/m-510/'],
['M-896','Superior weather resistance with high gloss and excellent opacity for demanding exterior coatings.','/products/m-896/'],
['M-895','High-opacity, high-gloss coatings grade with good weather resistance.','/products/m-895/'],
['M-200','High-durability exterior plastics grade with strong anti-chalking performance.','/products/m-200/'],
['M-210','High hiding power and easy dispersion for polyolefin masterbatch.','/products/m-210/'],
['M-340','High whiteness with strong high-temperature anti-yellowing performance.','/products/m-340/'],
['M-886','Bright-white plastics grade with excellent dispersion and processability.','/products/m-886/']
];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});
for(const vp of [{w:1440,h:1000,d:1},{w:768,h:1000,d:1},{w:390,h:844,d:2}]){
 const ctx=await browser.newContext({viewport:{width:vp.w,height:vp.h},deviceScaleFactor:vp.d}); const p=await ctx.newPage(); const net=[],errors=[];
 await p.route(/^https?:/i,r=>{net.push(r.request().url());r.abort();}); p.on('pageerror',e=>errors.push(String(e))); await p.goto(pathToFileURL(htmlPath).href); await p.evaluate(()=>document.fonts.ready);
 const actual=await p.evaluate(()=>({text:document.body.innerText.replace(/\s+/g,' ').trim(),scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,title:document.title,description:document.querySelector('meta[name=description]')?.content,canonical:document.querySelector('link[rel=canonical]')?.href,robots:document.querySelector('meta[name=robots]')?.content,h1:[...document.querySelectorAll('h1')].map(x=>x.textContent.trim()),current:[...document.querySelectorAll('nav[aria-label="Primary navigation"] [aria-current=page],nav[aria-label="Mobile navigation"] [aria-current=page]')].map(x=>x.textContent.trim()),font:getComputedStyle(document.body).fontFamily,controls:[...document.querySelectorAll('a,button')].filter(x=>{const r=x.getBoundingClientRect();return r.width&&r.height&&getComputedStyle(x).visibility!=='hidden'}).map(x=>({t:x.textContent.trim(),w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})),order:[...document.querySelectorAll('main section')].map(x=>x.id),pageId:document.body.dataset.pageId,siteScope:document.body.dataset.siteScope,grades:[...document.querySelectorAll('.cl-grade')].map(x=>[x.querySelector('h3').textContent.trim(),x.querySelector('p').textContent.trim(),x.querySelector('a').getAttribute('href')])}));
 add(`${vp.w}:no-overflow`,actual.scrollWidth===actual.clientWidth,actual); add(`${vp.w}:h1`,actual.h1.length===1&&actual.h1[0]==='Chloride Process Titanium Dioxide',actual.h1); add(`${vp.w}:content`,required.every(x=>actual.text.includes(x)),required.filter(x=>!actual.text.includes(x))); add(`${vp.w}:modules`,JSON.stringify(actual.order)===JSON.stringify(['cl-01','cl-02','cl-03','cl-04','cl-05']),actual.order); add(`${vp.w}:grades`,JSON.stringify(actual.grades)===JSON.stringify(grades),actual.grades); add(`${vp.w}:targets`,actual.controls.every(x=>x.w>=43.9&&x.h>=43.9),actual.controls.filter(x=>x.w<43.9||x.h<43.9)); add(`${vp.w}:meta`,actual.title==='Chloride Process Titanium Dioxide | TiO2 Malaysia'&&actual.description==='Explore eight Malaysia-origin chloride-process titanium dioxide grades, understand what the process label means, and review product information or request a quote.'&&actual.canonical==='https://tio2malaysia.com/products/chloride-process-titanium-dioxide/'&&actual.robots==='noindex,nofollow',actual); add(`${vp.w}:current`,actual.current.filter(x=>x==='Products').length===2,actual.current); add(`${vp.w}:identity`,actual.pageId==='PRODUCT-PROC-CL'&&actual.siteScope==='tio2-my',{pageId:actual.pageId,siteScope:actual.siteScope}); add(`${vp.w}:font`,/Inter/.test(actual.font),actual.font); add(`${vp.w}:network-errors`,net.length===0&&errors.length===0,{net,errors});
 const shot=await p.screenshot({fullPage:true}); const formal=records.find(x=>(x.logicalViewport?.width||x.logicalWidth||x.viewportWidth)===vp.w&&x.state==='default-full'); add(`${vp.w}:independent-raster-match`,!!formal&&sha(shot)===formal.sha256,{actual:sha(shot),formal:formal?.sha256}); fs.writeFileSync(path.join(out,`root-default-${vp.w}.png`),shot);
 await p.getByRole('link',{name:'Explore Chloride Grades'}).click(); const anchor=await p.evaluate(()=>({hash:location.hash,focus:document.activeElement?.id,top:document.getElementById('explore-chloride-process-grades').getBoundingClientRect().top})); await p.keyboard.press('Tab'); anchor.nextTab=await p.evaluate(()=>document.activeElement?.textContent?.trim()); add(`${vp.w}:anchor`,anchor.hash==='#explore-chloride-process-grades'&&anchor.focus==='explore-chloride-process-grades'&&anchor.top>80&&anchor.top<112&&anchor.nextTab==='View M-350',anchor);
 await p.getByRole('link',{name:'Request Documents'}).click(); await p.getByRole('link',{name:'Request a Quote',exact:true}).last().click(); const nav=await p.evaluate(()=>window.planningNavigation.slice(-2)); add(`${vp.w}:downstream-context`,nav.length===2&&nav[0].href==='/request-documents/'&&nav[0].context?.source_page_id==='PRODUCT-PROC-CL'&&nav[1].href==='/request-a-quote/'&&nav[1].context?.source_page_id==='PRODUCT-PROC-CL',nav);
 if(vp.w<1101){await p.evaluate(()=>{history.replaceState(null,'',location.pathname);document.activeElement?.blur();scrollTo(0,321)}); await p.waitForTimeout(50); const before=await p.evaluate(()=>scrollY); await p.evaluate(()=>document.querySelector('.menuButton').click()); const menuOpen=await p.evaluate(()=>({expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),active:document.activeElement?.textContent?.trim(),mainInert:document.querySelector('main').inert,footerInert:document.querySelector('footer').inert,overflow:document.body.style.overflow,scrollY})); add(`${vp.w}:menu-open`,menuOpen.expanded==='true'&&menuOpen.active==='Home'&&menuOpen.mainInert&&menuOpen.footerInert&&menuOpen.overflow==='hidden'&&Math.abs(menuOpen.scrollY-before)<2,menuOpen); await p.keyboard.press('Escape'); await p.waitForTimeout(50); const menuClose=await p.evaluate(()=>({expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),active:document.activeElement?.textContent?.trim(),mainInert:document.querySelector('main').inert,overflow:document.body.style.overflow,scrollY})); menuClose.before=before; add(`${vp.w}:menu-close`,menuClose.expanded==='false'&&menuClose.active==='Menu'&&!menuClose.mainInert&&menuClose.overflow===''&&Math.abs(menuClose.scrollY-before)<2,menuClose);}
 await p.getByRole('button',{name:'Cookie Settings'}).click(); add(`${vp.w}:cookie-open`,await p.getByRole('dialog').isVisible()&&(await p.evaluate(()=>document.activeElement?.textContent?.trim()))==='Close',await p.evaluate(()=>document.activeElement?.textContent?.trim())); await p.keyboard.press('Escape'); add(`${vp.w}:cookie-close`,!(await p.getByRole('dialog').isVisible())&&(await p.evaluate(()=>document.activeElement?.id))==='cookie-trigger',await p.evaluate(()=>document.activeElement?.id));
 await ctx.close(); }
 await browser.close(); const result={reviewedAt:new Date().toISOString(),freezeId:freeze.freezeId,sourceCombination:freeze.sourceCombinationSha256,scope:'Root independent identity, content, grade order and URLs, geometry, metadata, same-page anchor, source attribution, shared overlays and deterministic raster check; all formal and readable-segment assets separately opened by root.',checks,pass:checks.every(x=>x.pass),failures:checks.filter(x=>!x.pass)}; fs.writeFileSync(path.join(out,'root-verification.json'),JSON.stringify(result,null,2)+'\n'); console.log(JSON.stringify({total:checks.length,pass:result.pass,failures:result.failures},null,2)); if(!result.pass)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1;});
