const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const dep='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {chromium}=require(dep+'playwright'),sharp=require(dep+'sharp');
const root='D:/23MySec',dir=root+'/pages/resources/brazil-trade',out=dir+'/05_review/gate5-independent-v0.1',candidate=dir+'/04_planning/gate4-v0.1',source=candidate+'/RES-TRADE-BR_GATE4_FULL_VISUAL_V0.1.html';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')); const obs={reviewer:'/root/g5_trade_br',author:'/root/gate4_brazil_trade_execute',mode:'INDEPENDENT_REVIEW',scope:'INITIAL',at:new Date().toISOString(),source:id(source),identity:[],viewports:[],runtime:[],errors:[]};
const record=(name,pass,detail={})=>obs.runtime.push({name,pass,detail});
(async()=>{
 const index=read(candidate+'/input-index.json'),freeze=read(candidate+'/freeze-record.json'),evidence=read(candidate+'/evidence-index.json');
 const entries=[...index.inputs,...index.shared_files,...index.dependencies,...freeze.frozen_files,...freeze.dependencies,...freeze.shared_files];
 for(const e of [...new Map(entries.map(e=>[e.path,e])).values()]){try{const actual=id(e.path);obs.identity.push({expected:e,actual,pass:actual.sha256===e.sha256&&actual.bytes===e.bytes});}catch(err){obs.identity.push({expected:e,pass:false,error:String(err)})}}
 obs.evidence=[];for(const a of evidence.approval_core){const actual=id(a.path),m=await sharp(a.path).metadata();obs.evidence.push({path:a.path,actual,width:m.width,height:m.height,pass:actual.sha256===a.sha256&&actual.bytes===a.bytes&&m.width===a.physical_size.width&&m.height===a.physical_size.height,logical:a.logical_viewport,dpr:a.dpr,state:a.state});}
 obs.method_identity=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.9.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE5_GATE6_ACCEPTANCE_CONTRACT_V1.0.md'].map(p=>id(root+'/'+p));
 obs.bundle=freeze.bundle_id; obs.index_identity=id(candidate+'/evidence-index.json');obs.freeze_identity=id(candidate+'/freeze-record.json');
 const g3=fs.readFileSync(dir+'/04_planning/gate3-v0.1/RES-TRADE-BR_GATE3_WIREFRAME_V0.1.html','utf8'),html=fs.readFileSync(source,'utf8');
 record('Approved G3 complete main markup preserved',g3.match(/<main>[\s\S]*?<\/main>/)[0]===html.match(/<main>[\s\S]*?<\/main>/)[0]);
 for(const tag of ['header','footer','script'])record('G3 shared '+tag+' preserved',g3.match(new RegExp('<'+tag+'[\\s\\S]*?</'+tag+'>'))[0]===html.match(new RegExp('<'+tag+'[\\s\\S]*?</'+tag+'>'))[0]);
 const {marked}=await import(pathToFileURL(dep+'marked/lib/marked.esm.js').href);
 const md=fs.readFileSync(dir+'/04_planning/RES-TRADE-BR_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').split('\n---\n')[1];
 const expectedHtml=marked.parse(md);
 const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});obs.browser=await b.version();
 for(const width of [1440,768,390]){
  const p=await b.newPage({viewport:{width,height:900},deviceScaleFactor:1});await p.route(/^https?:/,r=>r.abort());p.on('pageerror',e=>obs.errors.push(String(e)));await p.goto(pathToFileURL(source).href);await p.evaluate(()=>document.fonts.ready);
  const data=await p.evaluate(expectedHtml=>{
   const norm=s=>s.replace(/\s+/g,' ').trim(),doc=new DOMParser().parseFromString(expectedHtml,'text/html'),tags='h1,h2,h3,p,li,th,td';
   const expected=[...doc.querySelectorAll(tags)].map(e=>norm(e.textContent)),actual=[...document.querySelectorAll('main '+tags.split(',').join(',main '))].map(e=>norm(e.textContent));
   const visible=e=>e.getClientRects().length&&!e.closest('[hidden]');
   const controls=[...document.querySelectorAll('a,button')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return {label:norm(e.textContent)||e.getAttribute('aria-label'),href:e.getAttribute('href'),w:r.width,h:r.height}});
   const clip=[...document.querySelectorAll('main *')].filter(visible).filter(e=>!e.closest('thead')).filter(e=>{const s=getComputedStyle(e);return ((e.scrollWidth>e.clientWidth+2)&&['hidden','clip'].includes(s.overflowX))||((e.scrollHeight>e.clientHeight+2)&&['hidden','clip'].includes(s.overflowY))}).map(e=>({tag:e.tagName,text:norm(e.textContent).slice(0,120)}));
   const outside=[...document.querySelectorAll('main p,main li,main h1,main h2,main h3,main td')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5}).map(e=>norm(e.textContent));
   const links=[...document.querySelectorAll('main a')].map(a=>({label:norm(a.textContent),href:a.getAttribute('href')}));const expectedLinks=[...doc.querySelectorAll('a')].map(a=>({label:norm(a.textContent),href:a.getAttribute('href')}));
   return {width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,font:document.fonts.check('16px Inter'),blocks:actual.length,contentEqual:JSON.stringify(expected)===JSON.stringify(actual),contentDiff:actual.filter((a,i)=>a!==expected[i]),links,linksEqual:JSON.stringify(links)===JSON.stringify(expectedLinks),controls,clip,outside,tableRows:[...document.querySelectorAll('main table')].map(t=>t.tBodies[0].rows.length),tableLabels:[...document.querySelectorAll('td')].every(td=>td.dataset.label===document.getElementById(td.getAttribute('headers')).textContent),modulePositions:[...document.querySelectorAll('.module,footer')].map(e=>({name:e.className,y:e.getBoundingClientRect().y,height:e.getBoundingClientRect().height})),headers:document.querySelector('header').getBoundingClientRect().height};
  },expectedHtml);obs.viewports.push(data);record(width+' content/links and geometry',data.contentEqual&&data.linksEqual&&data.scrollWidth===width&&data.font&&data.clip.length===0&&data.outside.length===0&&data.controls.every(x=>x.w>=44&&x.h>=44)&&data.tableLabels,data);
  const anchors=p.locator('main a');for(let i=0;i<await anchors.count();i++){await anchors.nth(i).click();}record(width+' all body link activations',JSON.stringify((await p.evaluate(()=>localNavigationIntents)).map(x=>x.href))===JSON.stringify(data.links.map(x=>x.href)),{count:data.links.length,type:'LOCAL_SIMULATION',intents:await p.evaluate(()=>localNavigationIntents)});
  await p.evaluate(()=>window.scrollTo(0,0));const primary=p.locator('.module-1 p:nth-of-type(3) a');await primary.hover();const hover=await primary.evaluate(e=>({background:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));await p.mouse.move(0,0);await primary.focus();const focus=await primary.evaluate(e=>({outline:getComputedStyle(e).outline,offset:getComputedStyle(e).outlineOffset,visible:e.matches(':focus-visible')}));record(width+' primary hover/focus',hover.background==='rgb(6, 43, 91)'&&focus.visible&&focus.outline.includes('3px'),{hover,focus});
  if(width<1101){
   await p.locator('.menuButton').click();record(width+' menu entry/inert',await p.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'));
   await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');record(width+' menu forward cycle',await p.locator('.menuButton').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');record(width+' menu reverse cycle',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));
   await p.locator('main a').first().evaluate(e=>e.focus());record(width+' menu background focus blocked',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');record(width+' menu Escape return',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.activeElement===document.querySelector('.menuButton')));
   await p.locator('.menuButton').click();await p.locator('.menuButton').click();record(width+' menu button close',await p.locator('.mobileNav').evaluate(e=>e.hidden));
   for(let i=0;i<8;i++){await p.locator('.menuButton').click();const a=p.locator('.mobileNav a').nth(i),href=await a.getAttribute('href');await a.click();record(width+' menu selection '+i,await p.evaluate(href=>document.querySelector('.mobileNav').hidden&&localNavigationIntents.at(-1).href===href,href),{href,type:'ACTUAL_RUNTIME / navigation intent LOCAL_SIMULATION'});}
   await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:900});await p.waitForTimeout(60);record(width+' menu breakpoint exit',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width,height:900});
  }
  await p.locator('#cookie-trigger').click();record(width+' Cookie entry',await p.evaluate(()=>document.querySelector('dialog').open&&document.activeElement===document.querySelector('[data-cookie-close]')));await p.keyboard.press('Shift+Tab');record(width+' Cookie reverse cycle',await p.locator('dialog a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');record(width+' Cookie forward cycle',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('main a').first().evaluate(e=>e.focus());record(width+' Cookie background focus blocked',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('dialog a').click();record(width+' Cookie policy intent',await p.evaluate(()=>localNavigationIntents.at(-1).href==='/cookie-policy/'));
  await p.keyboard.press('Escape');await p.waitForTimeout(50);record(width+' Cookie Escape/return',await p.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement.id==='cookie-trigger'));await p.locator('#cookie-trigger').click();await p.locator('[data-cookie-close]').click();await p.waitForTimeout(50);record(width+' Cookie Close/return',await p.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement.id==='cookie-trigger'));
  await p.close();
 }
 const z=await b.newPage({viewport:{width:720,height:450},deviceScaleFactor:1});await z.route(/^https?:/,r=>r.abort());await z.goto(pathToFileURL(source).href);await z.evaluate(()=>document.fonts.ready);obs.zoom_equivalence={evidence_type:'LOCAL_SIMULATION',viewport:'720x450 corresponds to layout viewport for 1440x900 at 200%; not native browser zoom',geometry:await z.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,innerWidth,height:document.documentElement.scrollHeight}))};await z.locator('.menuButton').click();await z.locator('.mobileNav a').last().focus();obs.zoom_equivalence.menuLast=await z.locator('.mobileNav a').last().boundingBox();await z.keyboard.press('Escape');await z.locator('#cookie-trigger').click();obs.zoom_equivalence.dialog=await z.locator('dialog').boundingBox();await b.close();
 obs.source_after=id(source);obs.summary={identityMismatches:obs.identity.filter(x=>!x.pass),evidenceFailures:obs.evidence.filter(x=>!x.pass),runtimeFailures:obs.runtime.filter(x=>!x.pass),checks:obs.runtime.length};fs.writeFileSync(out+'/observations.json',JSON.stringify(obs,null,2)+'\n');console.log(JSON.stringify(obs.summary,null,2));
})().catch(e=>{obs.failure=String(e.stack);fs.writeFileSync(out+'/observations-incomplete.json',JSON.stringify(obs,null,2));console.error(e);process.exit(1)});
