const fs=require('fs'),crypto=require('crypto'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/documents/certificate-of-origin',src=base+'/04_planning/gate4-v0.1',out=__dirname,read=p=>fs.readFileSync(p),j=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex');
const inv=j(src+'/approval_core/asset-inventory.json'),freeze=j(src+'/approval_core/source-freeze.json'),exportList=j(src+'/approval_core/export-inventory.json');
const result={finalInventorySha:hash(src+'/approval_core/asset-inventory.json'),finalInventoryExpected:'7cbd3854475728e80dc00513abc28f1eb30e289ec79a1e5762de4bddec6586fb',identities:[...inv.files,inv.selfCheck,...freeze.dependencies,...freeze.inputs,...exportList.assets].map(x=>({path:x.path,match:read(x.path).length===x.bytes&&hash(x.path)===x.sha256})),widths:[]};
const entry=src+'/DOC-COO_GATE4_VISUAL_SAMPLES_V0.1.html';
const geom=()=>[...document.querySelectorAll('header,main,main section,.applicationGroup,footer,main h1,main h2,main h3,main p,main li')].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{tag:e.tagName,id:e.id,x:r.x,y:r.y,w:r.width,h:r.height,font:s.font,color:s.color}});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});for(const width of[1440,768,390]){const p=await browser.newPage({viewport:{width,height:width===390?844:900}});await p.route('**/*',r=>/^https?:/.test(r.request().url())?r.abort():r.continue());await p.goto('file:///'+entry);await p.evaluate(()=>document.fonts.ready);const g4=await p.evaluate(geom),row={width,navigation:[]};
for(const a of await p.locator('header .logoLink,.desktopNav a,.headerRfq,footer a').all())if(await a.isVisible())await a.click();
if(width<1101)for(let i=0;i<8;i++){await p.locator('.menuButton').click();await p.locator('.mobileNav a').nth(i).click()}
await p.locator('#cookie-trigger').click();await p.locator('dialog a').click();row.navigation=await p.evaluate(()=>window.__navigationIntents);await p.keyboard.press('Escape');
await p.goto('file:///'+base+'/04_planning/gate3-v0.1/DOC-COO_GATE3_RESPONSIVE_WIREFRAME_V0.1.html');await p.evaluate(()=>document.fonts.ready);const g3=await p.evaluate(geom);row.geometryAndTypographyEqual=JSON.stringify(g3)===JSON.stringify(g4);row.geometryCount=g3.length;row.geometryDifference=g3.filter((x,i)=>JSON.stringify(x)!==JSON.stringify(g4[i]));await p.close();result.widths.push(row)}await browser.close();fs.writeFileSync(out+'/final-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify({inventory:result.finalInventorySha===result.finalInventoryExpected,identityCount:result.identities.length,identityFailures:result.identities.filter(x=>!x.match),widths:result.widths.map(x=>({width:x.width,geometry:x.geometryAndTypographyEqual,navigation:x.navigation.length,diff:x.geometryDifference}))},null,2))})().catch(e=>{console.error(e);process.exit(1)});


