const fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const base='D:/23MySec/pages/markets/belgium',out=base+'/04_planning/gate3-v0.1',id='MARKET-EU-BE',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:hash(p)}),save=(p,x)=>fs.writeFileSync(p,JSON.stringify(x,null,2));
const inputPath=out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',b=read(inputPath),preflightPath=out+'/'+id+'_GATE3_PREFLIGHT_RECORD_V0.1.json',freezePath=out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json';
if(process.argv[2]==='preflight'){
const r=read(out+'/diagnostic_support/render-r1/runtime-checks.json');if(r.failed.length||r.errors.length)throw Error('Runtime not clean');for(const f of [...Object.values(b.approvedInputs),...b.dependencies,...b.sharedConsumer.files,...Object.values(b.sharedConsumer.owners),...b.methods])if(hash(f.path)!==f.sha256)throw Error('Input mismatch '+f.path);
save(out+'/diagnostic_support/preflight-visual-readback.json',{role:'EXECUTION_SELF_CHECK',type:'STATIC_VISUAL',time:new Date().toISOString(),source:identity(source),openedOverviewsAndStates:r.images,openedClips:fs.readdirSync(out+'/diagnostic_support/render-r1').filter(n=>n.startsWith('clip-')).map(n=>identity(out+'/diagnostic_support/render-r1/'+n)),findings:[],observations:['Complete Hero to Footer visible at all three widths, with no clipping/collision/abnormal fixed blank region.','Product category qualification remains two linked paragraphs, without extra offer/local manufacturing inference.','Coatings, Plastics and Masterbatch, Import and Distribution have distinct title/text associations; the following Product review is outside all three blocks.','Documents preserves exact COO once, one Grade cardinality, unknown/additional Grade instructions, and three ordered actions including tertiary EU overview.','Four RFQ bullets and after-submit human review/contact sentence remain complete.','All eight menu entries and current Markets marker visible at both narrow widths; three minimal Cookie states show complete text and two actions.']});
save(out+'/diagnostic_support/helper-recovery.json',{failure:'first-helper-failure.json',result:'RESOLVED',evidence:identity(out+'/diagnostic_support/build-result.json'),description:'Renamed CommonJS wrapper-binding conflict before any HTML existed. Corrected build and first fresh diagnostic passed; no candidate layout repair.'});
save(preflightPath,{status:'PASS_FOR_FORMAL_RENDER',role:'EXECUTION_PREFLIGHT_NOT_INDEPENDENT_APPROVAL',time:new Date().toISOString(),candidate:identity(source),approvedInputs:b.approvedInputs,dependencies:b.dependencies,sharedConsumer:b.sharedConsumer,inputBinding:identity(inputPath),checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks','functionalColors'].map(k=>[k,'PASS'])),formalExportsGenerated:false,evidence:[identity(out+'/diagnostic_support/render-r1/runtime-checks.json'),identity(out+'/diagnostic_support/preflight-visual-readback.json')],browser:r.browser,viewports:r.viewports,scale:1,findings:[],unmeasured:['native browser zoom','assistive technology/physical devices/cross-browser','production routes and actual receiving behavior']});
const result=JSON.parse(cp.execFileSync(process.execPath,['D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs',preflightPath],{encoding:'utf8'}));save(out+'/diagnostic_support/preflight-checker-result.json',result);console.log(JSON.stringify(result));
}
if(process.argv[2]==='freeze'){
const p=read(preflightPath),check=read(out+'/diagnostic_support/preflight-checker-result.json');if(check.status!=='PASS_FOR_FORMAL_RENDER'||p.candidate.sha256!==hash(source))throw Error('Invalid preflight');if(fs.existsSync(out+'/approval_core')&&fs.readdirSync(out+'/approval_core').length)throw Error('Premature formal image');
save(freezePath,{status:'FROZEN_FOR_PROJECT_CONTROL_REVIEW',role:'EXECUTION_FREEZE_NOT_GATE_APPROVAL',frozenAt:new Date().toISOString(),source:identity(source),approvedInputs:b.approvedInputs,sharedConsumer:b.sharedConsumer,dependencies:b.dependencies,preflight:identity(preflightPath),inputBinding:identity(inputPath),formalExportsExistedAtFreeze:false});console.log(JSON.stringify(read(freezePath).source));
}
