const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',page=root+'/pages/resources/uk-trade',out=page+'/04_planning/gate3-v0.1',shared=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
for(const d of ['approval_core','dependencies','diagnostic_support/render'])fs.mkdirSync(out+'/'+d,{recursive:true});if(fs.existsSync(out+'/freeze-record.json'))throw Error('frozen');
const inputs=[['A','04_planning/RES-TRADE-UK_GATE2_CONTENT_SKELETON_V0.1.md','ed18eee4d49fa82e6e9ab6e6e18d9aa1f91dc2bac0f8081b1bb0cc9ded24dac0'],['B','04_planning/RES-TRADE-UK_GATE2_FULL_BUYER_CLEAN_COPY_V0.3.md','e2df4ca206fc64e984f57d6171b3037d665f279c786405a4081ebb2e63c7ac97'],['C','04_planning/RES-TRADE-UK_GATE2_CONTENT_CONTRACT_V0.3.md','4646c0b0f5ddf52065b574f82a1d2ae18dda2718c0eea1041f61a5cc7875e330'],['Review','05_review/RES-TRADE-UK_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md','d731cd838fbf16bf80bf6d23a0f635aab3625de544ffcea7aa9105c70e8e290e']].map(([role,p,sha])=>{const a=id(page+'/'+p);if(a.sha256!==sha)throw Error(role+' hash');return {...a,role}});
const pkg=JSON.parse(fs.readFileSync(shared+'/consumer-package.json','utf8')),sharedFiles=pkg.files.map(f=>{const a=id(shared+'/'+f.path);if(a.sha256!==f.sha256)throw Error(f.path+' hash');return {...a,role:f.role}});
const authorities=['AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md','research/keyword/11_page_keyword_master.csv','docs/architecture/PAGE_REGISTRY_V0.2.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.0.md','docs/architecture/PAGE_GATE_1_5_STANDARD_V1.1.md','docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','docs/architecture/GATE2_FIVE_RESOURCE_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md','docs/architecture/GATE3_FIVE_RESOURCE_SERIAL_CONTROL_V1.2.md','docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md','agents/gate3-execution/agent.md','skills/responsive-wireframe-design/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/responsive-wireframe-design/references/preflight-freeze-evidence.md','skills/layout-interaction-verification/references/core-risk-model.md','docs/superpowers/specs/2026-09-07-gate3-to-gate4-handoff-contract-v0.1.md','docs/page-playbooks/RESOURCE_PLAYBOOK_V0.1.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','docs/page-briefs/RES-TRADE-UK_UK_TITANIUM_DIOXIDE_TRADE_UPDATE_BRIEF_V0.1.md','pages/resources/uk-trade/RES-TRADE-UK_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md','pages/resources/uk-trade/01_research/evidence/RES-TRADE-UK_GATE2_FRESH_OFFICIAL_RECHECK_2026-09-07.md','pages/conversion/request-a-quote/04_planning/CONV-RFQ_CURRENT_GATE_BASELINE_MANIFEST_V2.8.md',...Object.values(pkg.authority).map(p=>p.slice(root.length+1))].map(p=>id(root+'/'+p));
for(const f of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(shared+'/'+f,out+'/dependencies/'+f);const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';
const binding={pageId:'RES-TRADE-UK',status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',plannedUrl:'/resources/uk-titanium-dioxide-anti-dumping-investigation/',currentPageId:'RES-000',approvedInputs:inputs,authorities,sharedConsumer:{...id(shared+'/consumer-package.json'),version:pkg.version,packageId:pkg.packageId},sharedFiles,dependencies:[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(id)};save(out+'/input-binding.json',binding);
save(out+'/task-input-card.md','# RES-TRADE-UK Gate3 task input card\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. G3-5RESOURCE-SERIAL-01 page 3 only. Current Manifest V0.4; approved A V0.1/B V0.3/C V0.3/review V0.1 hashes computed in input-binding.json.\n\nSeven modules: Hero → status → written scope/codes → possible later consequences and indicative timetable → eight shipment inputs → four separate checks → procurement/official-source continuation. Three real tables; no form/FAQ/calculator/rate selector/result. Real states: three full pages, two Menu states, three Cookie states.\n\nResources current via neutral Shared Consumer V0.2; approved original Logo paths and durable font/license. No business-page template. Output this directory and this page05_review self-check/evidence only. Root/current methods/shared owners already read and unchanged in this serial session are inherited; page sources/current queue are freshly read and all identities recomputed.\n\nRisks: active investigation is not a finding; registration is not a rate; dated no-amount discovery remains bounded; exact rutile/80%/CAS/codes/8A60-8A61 scope; possible up-to-90-days liability only if definitive remedy; nonbinding timetable; GB/NI at-risk branch; no shipment/customs result from Malaysia origin. Preserve30-day/event-trigger freshness before implementation/publication.\n\nWorkflow: input card → diagnostic/browser and actual visual hard preflight → PASS_FOR_FORMAL_RENDER validator → freeze → first formal8 exports → actual image readback/self-check → independent review. No next page/Gate4.\n');
save(out+'/design-report.md','# RES-TRADE-UK design method report\n\nDESIGN_IN_PROGRESS. Applying responsive-wireframe-design V0.2 and layout-interaction-verification V0.2. Three tables retain semantic headers on desktop/tablet; mobile row records repeat the approved column labels to preserve long answer/timetable/GB-NI associations. Actual readability will determine preflight.\n');
const copy=fs.readFileSync(inputs.find(a=>a.role==='B').path,'utf8').split('\n---\n')[1].trim();
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),plain=s=>s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/\*\*|`/g,''),inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
let html='',sectionCount=0,tableCount=0,blocks=[],tables=[];
for(const b of copy.split(/\n\s*\n/)){if(/^#{1,3} /.test(b)){const m=b.match(/^(#{1,3}) (.*)$/s),n=m[1].length;if(n<3){if(sectionCount)html+='</section>';sectionCount++;html+=`<section class="module module-${sectionCount}">`;}html+=`<h${n}>${inline(m[2])}</h${n}>`;blocks.push({tag:'h'+n,text:plain(m[2])});}
else if(b.startsWith('|')){const rows=b.split('\n').filter(l=>!/^\|[- :|]+\|$/.test(l)).map(l=>l.split('|').slice(1,-1).map(x=>x.trim()));tableCount++;tables.push(rows.map(r=>r.map(plain)));html+=`<table class="table-${tableCount}" role="table"><thead role="rowgroup"><tr role="row">`;rows[0].forEach((t,i)=>{html+=`<th scope="col" role="columnheader" id="table-${tableCount}-col-${i}">${inline(t)}</th>`;blocks.push({tag:'th',text:plain(t)})});html+='</tr></thead><tbody role="rowgroup">';for(const row of rows.slice(1)){html+='<tr role="row">';row.forEach((t,i)=>{html+=`<td role="cell" headers="table-${tableCount}-col-${i}" data-label="${esc(plain(rows[0][i]))}">${inline(t)}</td>`;blocks.push({tag:'td',text:plain(t)})});html+='</tr>';}html+='</tbody></table>';}
else if(b.startsWith('- ')){html+='<ul>';for(const line of b.split('\n')){const t=line.slice(2);html+='<li>'+inline(t)+'</li>';blocks.push({tag:'li',text:plain(t)})}html+='</ul>';}
else{html+='<p>'+inline(b)+'</p>';blocks.push({tag:'p',text:plain(b)})}}
html+='</section>';const links=[...copy.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:plain(m[1]),href:m[2]}));save(out+'/diagnostic_support/expected-copy.json',{source:inputs.find(a=>a.role==='B'),blocks,links,tables,modules:sectionCount});
const chrome=require(shared+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'RES-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#102d46;background:white}main{max-width:1200px;margin:auto;padding:28px 40px 64px}main .module{max-width:960px;margin:auto;padding:38px 0;border-bottom:1px solid #d7e1e7}main .module:first-child{padding-top:12px}main .module:last-child{border:0;padding-bottom:0}main h1{font-size:46px;line-height:1.15;letter-spacing:-1.4px;margin:0 0 24px}main h2{font-size:30px;line-height:1.25;margin:0 0 24px;letter-spacing:-.5px}main h3{font-size:22px;margin:26px 0 18px}main p,main li{font-size:17px;line-height:1.65;margin:0 0 18px}main ul{padding-left:25px;margin:22px 0}main li{padding-left:6px}main code{font:inherit;font-variant-numeric:tabular-nums}main a{display:inline-flex;align-items:center;min-height:44px;min-width:44px;max-width:100%;color:#008078;text-underline-offset:4px;font-weight:600;overflow-wrap:anywhere}main a:focus-visible{outline:3px solid #008078;outline-offset:3px}main .module-1 p:nth-of-type(3) a,main .module-7 p:first-of-type a{padding:12px 20px;background:#008078;border:1px solid #008078;color:white;text-decoration:none}main .module-1 p:nth-of-type(5) a{padding:11px 20px;border:1px solid #008078;text-decoration:none}main table{width:100%;table-layout:fixed;border-collapse:collapse;margin:22px 0 26px;font-size:16px;line-height:1.6}main th,main td{border:1px solid #cbd8e0;padding:16px;text-align:left;vertical-align:top;overflow-wrap:break-word}main th{background:#eff4f6;font-weight:600}main .table-1 th:first-child{width:32%}main .table-2 th:first-child{width:25%}main .table-2 th:nth-child(2){width:23%}main .table-3 th:first-child{width:26%}main .table-3 th:nth-child(2){width:37%}@media(max-width:1100px){main{padding:24px 32px 48px}main .module{padding:32px 0}main h1{font-size:40px}main th,main td{padding:14px}}@media(max-width:600px){main{padding:20px 20px 40px}main .module{padding:30px 0}main h1{font-size:34px;letter-spacing:-.8px}main h2{font-size:27px}main p,main li{font-size:16px;line-height:1.65}main .module-1 a{width:100%;justify-content:center}main li{padding-left:1px}main table,main tbody,main tr,main td{display:block;width:100%}main thead{position:absolute;width:1px;height:1px;overflow:clip;clip-path:inset(50%)}main tbody tr{margin:0 0 20px;border:1px solid #cbd8e0;padding:4px 16px;background:#fff}main td{border:0;padding:12px 0}main td+td{border-top:1px solid #e0e7eb}main td::before{content:attr(data-label);display:block;font-size:14px;font-weight:700;line-height:1.4;margin-bottom:6px;color:#526673}main table{font-size:16px;line-height:1.65}}`;
const behavior=`window.localNavigationIntents=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();window.localNavigationIntents.push({href:a.getAttribute('href'),context:{},type:'LOCAL_NAVIGATION_INTENT_ONLY'});});`;
const source=out+'/RES-TRADE-UK_GATE3_WIREFRAME_V0.1.html';save(source,'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UK Titanium Dioxide Anti-Dumping Investigation | TiO2 Malaysia</title><style>'+chrome.style+'\n'+css+'</style></head><body>'+chrome.header+'<main>'+html+'</main>'+chrome.footer+chrome.dialog+'<script>'+chrome.behavior+'\n'+behavior+'</script></body></html>');console.log(JSON.stringify({source:id(source),blocks:blocks.length,links:links.length,tables:tables.map(t=>t.length-1),modules:sectionCount},null,2));
