const fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const out='D:/23MySec/pages/resources/uk-trade/04_planning/gate3-v0.1',id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
if(fs.existsSync(out+'/freeze-record.json'))throw Error('already frozen');
const binding=read(out+'/input-binding.json'),runtime=read(out+'/diagnostic_support/render/runtime.json');
for(const x of [...binding.approvedInputs,...binding.authorities,...binding.sharedFiles,...binding.dependencies,binding.sharedConsumer,runtime.source]){const a=id(x.path);if(a.sha256!==x.sha256||a.bytes!==x.bytes)throw Error('identity drift '+x.path)}
if(runtime.status!=='PASS'||runtime.results.some(r=>r.status!=='PASS')||fs.readdirSync(out+'/approval_core').length)throw Error('preflight blocked');
const visual={status:'PASS',role:'EXECUTION_SELF_CHECK',source:runtime.source,observedAt:new Date().toISOString(),actualOpened:runtime.images.map(x=>id(x.path)),coverage:'Three whole-page overviews, all 33 native readable overlapping segments (1440:8,768:10,390:15), and five Menu/Cookie state images individually opened with view_image. Initial tool output lost at context boundary was not counted and was reopened.',observations:['All seven sections and full Footer visible at all widths.','All three tables preserve complete row relationships; mobile records repeat original labels and retain all long answers, dates and conditions.','Scope codes, shipment inputs, GB/NI branch, six official sources and last-reviewed text legible.','Primary procurement and secondary official-case actions remain distinct. Menu current Resources and Cookie actions legible with approved functional colors.'],findings:[]};save(out+'/diagnostic_support/visual-preflight.json',visual);
const preflight={pageId:'RES-TRADE-UK',status:'PASS_FOR_FORMAL_RENDER',candidate:id(runtime.source.path),formalExportsGenerated:false,checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks'].map(k=>[k,'PASS'])),dependencies:binding.dependencies,sharedConsumer:binding.sharedConsumer,inputBinding:id(out+'/input-binding.json'),runtime:id(out+'/diagnostic_support/render/runtime.json'),visual:id(out+'/diagnostic_support/visual-preflight.json'),viewports:[1440,768,390],evidenceTypes:['SOURCE_CHECK','ACTUAL_RUNTIME','ACTUAL_IMAGE_READBACK','LOCAL_SIMULATION'],notApplicable:['Page form, FAQ, rate calculator, selector and success states are absent from approved B.'],unresolvedFindings:[],createdAt:new Date().toISOString()};save(out+'/preflight-record.json',preflight);
const result=cp.spawnSync(process.execPath,['D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs',out+'/preflight-record.json'],{encoding:'utf8'});fs.writeFileSync(out+'/diagnostic_support/preflight-validator.json',result.stdout);if(result.status!==0)throw Error(result.stdout+result.stderr);
const freeze={pageId:'RES-TRADE-UK',status:'FROZEN_FOR_FORMAL_RENDER',submissionStatus:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',frozenAt:new Date().toISOString(),source:id(runtime.source.path),inputBinding:id(out+'/input-binding.json'),approvedInputs:binding.approvedInputs,sharedConsumer:binding.sharedConsumer,sharedFiles:binding.sharedFiles,dependencies:binding.dependencies,preflight:id(out+'/preflight-record.json'),validator:id(out+'/diagnostic_support/preflight-validator.json'),formalExportsExistedAtFreeze:false};save(out+'/freeze-record.json',freeze);console.log(JSON.stringify(freeze.source));
