const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),page=path.resolve(out,'../..').replaceAll('\\','/');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const id=p=>({path:p.replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)}),write=(n,j)=>fs.writeFileSync(out+'/'+n,JSON.stringify(j,null,2)+'\n');
const index=JSON.parse(fs.readFileSync(out+'/evidence-index.json')),input=JSON.parse(fs.readFileSync(out+'/input-index.json')),freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json'));
const visual={date:new Date().toISOString(),observer:'gate4_nl_complete execution agent (not independent reviewer)',evidenceType:'STATIC_VISUAL',method:'Actually opened all inherited PNGs via view_image original detail, then opened three new full-page overviews. Full-page views resized by display; readable content checked in inherited regions, whose current same-clip renders match exactly.',records:[...index.inherited,...index.new].map(a=>({path:a.path,sha256:a.sha256,opened:true,judgment:a.state==='normal'||a.state==='normal complete page'?'Full supplied content and its context readable in original-scale regions; no visual clipping or unexpected blank section; complete overview supplies page rhythm.':'Named hover/focus/Menu/Cookie visual state visible; actual behavior recorded separately.'}))};
write('diagnostic_support/visual-readback.json',visual);
index.visualReadback=id(out+'/diagnostic_support/visual-readback.json');index.authorSelfCheck=id(out+'/REPORT.md');index.workset=id(out+'/WORKSET.md');index.methodEvidenceClasses=['STATIC_VISUAL','ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION'];index.uniqueImages=45;index.newImages=3;index.inheritedImages=42;
write('evidence-index.json',index);
const records=[...input.inputs,...input.designSource,...index.inherited,...index.new,freeze.inputIndex,...freeze.preflight,freeze.inheritedEvidence,...index.operationEvidence].map(a=>({path:a.path,expectedBytes:a.bytes,expectedSha256:a.sha256,...id(a.path),match:a.bytes===fs.statSync(a.path).size&&a.sha256===sha(a.path)}));
const files=['WORKSET.md','REPORT.md','input-index.json','evidence-index.json','approval_core/source-freeze.json','diagnostic_support/inheritance-identity.json','diagnostic_support/visual-readback.json','diagnostic_support/preflight-runtime-checks.json','diagnostic_support/complete-preflight.json','diagnostic_support/runtime-check.cjs','diagnostic_support/complete-evidence.cjs','diagnostic_support/prepare-workset.cjs','diagnostic_support/finalize.cjs'];
const supplementalOwner='D:/23MySec/pages/legal-privacy/05_review/LEGAL_PRIVACY_CONV_DOC_POST_GATE9_CURRENT_AUTHORITY_MANIFEST_V1.3.md';
const oldFreeze=JSON.parse(fs.readFileSync(input.priorApprovedFreeze.path)),ownerEntry=oldFreeze.inputs.find(x=>x.path===supplementalOwner);
if(ownerEntry)records.push({path:ownerEntry.path,expectedSha256:ownerEntry.sha256,...id(ownerEntry.path),match:sha(ownerEntry.path)===ownerEntry.sha256&&fs.statSync(ownerEntry.path).size===ownerEntry.bytes});
const receipt={worksetId:'NL-G4-COMPLETE-20260907-V01',freezeId:freeze.freezeId,date:new Date().toISOString(),status:'AUTHOR_INTEGRITY_CHECK_COMPLETE / NOT_INDEPENDENT_REVIEW',counts:{inheritedImages:42,newImages:3,totalUniqueImages:45,identityRecords:records.length,identityErrors:records.filter(x=>!x.match).length},files:files.map(n=>id(out+'/'+n)),manifest:id(page+'/MARKET-EU-NL_CURRENT_GATE_BASELINE_MANIFEST_V0.8.md'),records,supplementalOwnerReadback:{...id(supplementalOwner),boundThroughPriorApprovedFreeze:!!ownerEntry,comment:'Shared legal owner remains unchanged; exact input inherited via the old approved freeze, additionally actually read during current completion.'},limitations:'Hashes prove identity only. Final independent review/user decision still pending; see REPORT.md.'};
write('approval_core/final-receipt.json',receipt);
// Read the saved files back and resolve their local Markdown links.
let linkErrors=[];for(const f of [out+'/REPORT.md',out+'/WORKSET.md',page+'/MARKET-EU-NL_CURRENT_GATE_BASELINE_MANIFEST_V0.8.md']){let s=fs.readFileSync(f,'utf8');for(const m of s.matchAll(/\]\(([^)]+)\)/g)){if(/^(https?:|#)/.test(m[1]))continue;let p=path.resolve(path.dirname(f),m[1]);if(!fs.existsSync(p))linkErrors.push({file:f,target:m[1]});}}
console.log(JSON.stringify({counts:receipt.counts,linkErrors,freeze:id(out+'/approval_core/source-freeze.json'),evidenceIndex:id(out+'/evidence-index.json'),report:id(out+'/REPORT.md'),manifest:receipt.manifest,receipt:id(out+'/approval_core/final-receipt.json')}));
if(receipt.counts.identityErrors||linkErrors.length)process.exitCode=1;
