const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),root='D:/23MySec',mode=process.argv[2]||'preflight';
const target='D:/23MySec/pages/markets/netherlands/04_planning/gate4-v0.2/MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.2.html',g3=root+'/pages/markets/netherlands/04_planning/gate3-v0.1/MARKET-EU-NL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const evidence=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/preflight';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});
const records=[],assets=[],errors=[],norm=s=>s.replace(/\s+/g,' ').replace(/\s+([.,;:])/g,'$1').trim();
function check(name,pass,data,type='ACTUAL_RUNTIME'){records.push({name,pass:!!pass,evidenceType:type,data});if(!pass)errors.push(name);}
const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);
const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{let x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function metrics(loc){return loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();function surface(node){while(node){let v=getComputedStyle(node).backgroundColor;if(v!=='rgba(0, 0, 0, 0)'&&v!=='transparent')return v;node=node.parentElement;}return'rgb(255, 255, 255)';}return{text:e.innerText,href:e.getAttribute('href'),fg:s.color,bg:surface(e),outline:s.outlineColor,outlineStyle:s.outlineStyle,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:surface(parseFloat(s.outlineOffset)>=0?e.parentElement:e),border:s.borderTopColor,borderWidth:parseFloat(s.borderTopWidth),font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,width:r.width,height:r.height,x:r.x,y:r.y,focus:e.matches(':focus-visible'),hover:e.matches(':hover'),textDecoration:s.textDecorationLine,background:s.backgroundColor};});}
async function keyboardFocus(page,loc){await page.mouse.move(0,0);await loc.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return loc.evaluate(e=>e===document.activeElement&&e.matches(':focus-visible'));}
async function controls(page,selector,label,w){let list=page.locator(selector);for(let i=0;i<await list.count();i++){let loc=list.nth(i);if(!await loc.isVisible())continue;await loc.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.evaluate(()=>document.activeElement.blur());let normal=await metrics(loc);let normalRatio=normal.text.trim()?contrast(normal.fg,normal.bg):null;check(`${w}/${label}/${i}/normal`,normal.width>=44&&normal.height>=44&&(!normalRatio||normalRatio>=4.5),{...normal,textContrast:normalRatio});await loc.hover();let hover=await metrics(loc);let hoverRatio=hover.text.trim()?contrast(hover.fg,hover.bg):null;check(`${w}/${label}/${i}/hover`,hover.hover&&hover.width===normal.width&&hover.height===normal.height&&(!hoverRatio||hoverRatio>=4.5),{...hover,textContrast:hoverRatio});let reached=await keyboardFocus(page,loc),focus=await metrics(loc);let focusRatio=contrast(focus.outline,focus.outlineBg);check(`${w}/${label}/${i}/keyboard`,reached&&focus.outlineWidth>=3&&focusRatio>=3,{...focus,outlineContrast:focusRatio});}}
async function shot(){ /* Unchanged formal region/state images are inherited; no duplicate export. */ }
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),version=browser.version();try{
if(mode==='formal'){const f=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json'));for(const a of[...f.inputs,...f.dependencies])check('freeze '+a.path,sha(a.path)===a.sha256&&fs.statSync(a.path).size===a.bytes,a,'SOURCE_INSPECTION');}
const original=fs.readFileSync(g3,'utf8'),candidate=fs.readFileSync(target,'utf8'),restored=candidate.replace('<span class="sourceReference"><span class="sourceLead">The </span>','The ').replace('(VVVF)</a></span> groups','(VVVF)</a> groups');
check('G3 main/script/style restored identity',['main','script','style'].every(tag=>JSON.stringify(restored.match(new RegExp('<'+tag+'[>][\\s\\S]*?</'+tag+'>','g')))===JSON.stringify(original.match(new RegExp('<'+tag+'[>][\\s\\S]*?</'+tag+'>','g')))),{g3:sha(g3),candidate:sha(target)},'SOURCE_INSPECTION');
const neutral=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:'dependencies/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'dependencies/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'dependencies/Inter-Variable.ttf'});check('Consumer V0.2 exact assembly',['header','footer','dialog','style','behavior'].every(k=>candidate.includes(neutral[k])),{currentPageId:'MARKET-000'},'SOURCE_INSPECTION');
const B=fs.readFileSync(root+'/pages/markets/netherlands/04_planning/MARKET-EU-NL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,''),expected=norm(B.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#+\s*/gm,'').replace(/^-\s*/gm,''));
for(const w of[1440,768,390]){let context=await browser.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage(),external=[];await context.route(/^https?:/,r=>{external.push(r.request().url());return r.abort()});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(target).href);await page.evaluate(()=>document.fonts.ready);
const actual=await page.locator('main').evaluate(e=>{const w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode.textContent);return a.join(' ')});check(`${w}/complete B`,norm(actual)===expected,{actual:norm(actual),expected});
const layout=await page.evaluate(()=>{const box=e=>{let r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}};return{modules:[...document.querySelectorAll('main section')].map(e=>e.dataset.module),prompts:[...document.querySelectorAll('.prompts>div')].map(e=>({title:e.querySelector('h3').textContent,rect:box(e),heading:box(e.querySelector('h3')),text:box(e.querySelector('p')),copy:e.querySelector('p').textContent})),coo:(document.querySelector('main').textContent.match(/A Certificate of Origin is available upon request\./g)||[]).length,rfqItems:document.querySelectorAll('[data-module="NL-05"] li').length,scrollWidth:document.documentElement.scrollWidth,formMedia:document.querySelectorAll('main form,main img,main input,main select').length,clipped:[...document.querySelectorAll('main *')].filter(e=>['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis').length}});
check(`${w}/five modules and facts`,JSON.stringify(layout.modules)===JSON.stringify(['NL-01','NL-02','NL-03','NL-04','NL-05'])&&layout.coo===1&&layout.rfqItems===4&&layout.formMedia===0,layout);
check(`${w}/application associations`,JSON.stringify(layout.prompts.map(x=>x.title))===JSON.stringify(['Coatings','Printing Inks','Plastics and Masterbatch'])&&layout.prompts.every((r,i)=>w===1440?r.rect.y===layout.prompts[0].rect.y&&(!i||r.rect.x>layout.prompts[i-1].rect.x):w===768?r.heading.y===r.text.y&&r.heading.x<r.text.x&&(!i||r.rect.y>layout.prompts[i-1].rect.y):r.heading.y<r.text.y&&(!i||r.rect.y>layout.prompts[i-1].rect.y)),layout.prompts);
check(`${w}/no overflow or truncation`,layout.scrollWidth===w&&!layout.clipped,layout);const vvvf=page.locator('.sourceReference a');check(`${w}/VVVF exact label and target`,await vvvf.textContent()==='Vereniging van Verf- en Drukinktfabrikanten (VVVF)'&&await vvvf.getAttribute('href')==='https://www.vvvf.nl/brancheorganisatie',{});
let font=await page.evaluate(()=>({ready:document.fonts.check('18px Inter'),images:[...document.images].every(e=>e.complete&&e.naturalWidth>0)}));check(`${w}/font logos`,font.ready&&font.images,font);
const cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'main h1'});const fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(`${w}/actual Inter`,fonts.fonts.some(f=>f.familyName.includes('Inter')&&f.isCustomFont),fonts);
await controls(page,'header a,header button,main a,footer a,footer button','page',w);
for(const selector of['main a','.headerRfq,.footerRfq']){let links=page.locator(selector);for(let i=0;i<await links.count();i++){let a=links.nth(i);await a.click();let href=await a.getAttribute('href'),intent=await page.evaluate(()=>window.__navigationIntents.at(-1));let expectedContext=href==='/request-a-quote/'?{source_page_id:'MARKET-EU-NL',destination_country:{value:'Netherlands',visible:true,editable:true}}:href==='/request-documents/'?{source_page_id:'MARKET-EU-NL'}:null;check(`${w}/${selector}/intent/${i}`,intent.href===href&&JSON.stringify(intent.context)===JSON.stringify(expectedContext)&&intent.kind==='LOCAL_SIMULATION_NOT_RECEIVED',intent,'LOCAL_SIMULATION');}}
if(w<1101){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();check(`${w}/menu entry`,await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement),{});check(`${w}/menu isolation`,await page.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'),{});await controls(page,'.menuButton,.mobileNav a','menu',w);await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let cycle=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');check(`${w}/menu cycle`,cycle&&await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});if(mode==='formal'){await page.evaluate(()=>scrollTo(0,0));await shot(page,w,'menu-focus',{focusSelector:'.mobileNav a[aria-current]',state:'Actual Markets keyboard focus in open Menu'});}await page.keyboard.press('Escape');check(`${w}/menu escape`,await page.locator('.menuButton').evaluate(e=>e===document.activeElement)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();check(`${w}/menu selection`,await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});let change=await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,restored:!document.querySelector('main').inert,focus:document.activeElement.tagName}));check(`${w}/desktop breakpoint`,change.closed&&change.restored,change);await page.setViewportSize({width:w,height:w===390?844:900});}
await page.locator('#cookie-trigger').click();check(`${w}/cookie entry`,await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(page,'.cookie-actions>*','cookie',w);await page.locator('[data-cookie-close]').focus();await page.keyboard.press('Shift+Tab');let cy=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');check(`${w}/cookie cycle`,cy&&await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await page.locator('main a').first().evaluate(e=>e.focus());check(`${w}/cookie modal isolation`,await page.locator('dialog').evaluate(e=>e.contains(document.activeElement)),{});if(mode==='formal')await shot(page,w,'cookie-focus',{focusSelector:'[data-cookie-close]',state:'Actual Close keyboard focus in Cookie'});await page.keyboard.press('Escape');check(`${w}/cookie escape`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();await page.waitForTimeout(50);check(`${w}/cookie Close return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),{});
const regions=[['hero','[data-module="NL-01"]',true],['applications','[data-module="NL-02"]'],['products','[data-module="NL-03"]'],['documents','[data-module="NL-04"]'],['rfq','[data-module="NL-05"]'],['footer','footer']];
for(const[name,selector,fromTop]of regions)if(mode==='formal'||['applications','documents','footer'].includes(name)||w===390&&name==='hero')await shot(page,w,name,{selector,fromTop});
if(mode==='formal'&&w===1440){await page.locator('.hero .action a[href="/request-a-quote/"]').scrollIntoViewIfNeeded();await shot(page,w,'primary-hover',{hoverSelector:'.hero .action a[href="/request-a-quote/"]',state:'Actual Hero primary RFQ hover; adjacent Products retained'});}
check(`${w}/no external requests`,!external.length,{external});await context.close();}
}catch(e){errors.push(e.stack);}await browser.close();const data={date:new Date().toISOString(),mode,source:id(target),runtime:{node:process.version,chrome:version,playwright:'1.62.1',headless:true,scale:1,externalRequestsAllowed:false},records,errors,assets,scope:'Netherlands merged Gate4 complete current runtime; inherited unchanged source; actual UI and simulated outbound contexts only'};fs.writeFileSync(out+'/diagnostic_support/'+mode+'-runtime-checks.json',JSON.stringify(data,null,2));if(mode==='formal')fs.writeFileSync(out+'/approval_core/export-inventory.json',JSON.stringify({freezeId:'NL-G4-V02-SOURCE-01',date:new Date().toISOString(),assets},null,2));console.log(JSON.stringify({mode,records:records.length,errors,assets:assets.map(x=>({path:x.relativePath,width:x.pixelWidth,height:x.pixelHeight}))}));if(errors.length)process.exitCode=1;})();
