const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {execFileSync} = require('node:child_process');
const {pathToFileURL} = require('node:url');
const modules = 'C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium} = require(path.join(modules,'playwright'));
const root = 'D:/23MySec';
const base = path.join(root,'pages/home/04_planning/visual-designs/home-root-page-hero-v1.3');
const current = path.join(base,'homepage-root-page-hero-preview-v1.3.html');
const old = path.join(root,'pages/home/04_planning/visual-designs/home-root-page-hero-v1.1/homepage-root-page-hero-preview-v1.1.html');
const approved = path.join(root,'pages/home/04_planning/visual-designs/home-applications-aligned-v1.1/homepage-applications-aligned-preview-v1.1.html');
const hash = b => crypto.createHash('sha256').update(b).digest('hex').toUpperCase();
const git = p => execFileSync('git',['show','ed10dd7:'+path.relative(root,p).split(path.sep).join('/')],{cwd:root,maxBuffer:20000000});
const html=fs.readFileSync(current,'utf8');
const body=s=>s.match(/<body>[\s\S]*<\/body>/)[0];
const result={review_id:'HOME-ROOT-HERO-G5-IVR-01',date:new Date().toISOString(),frozen_commit:execFileSync('git',['rev-parse','ed10dd7'],{cwd:root,encoding:'utf8'}).trim(),node:process.version,evidence_class:'ACTUAL_RUNTIME_LOCAL_PROTOTYPE',files:[],dependencies:[],body:{},runtime:[]};
const freeze=JSON.parse(fs.readFileSync(path.join(base,'freeze-record.json'),'utf8'));
for(const f of freeze.files){const p=path.join(base,f.path),b=fs.readFileSync(p);result.files.push({...f,actualBytes:b.length,actualSha256:hash(b),dimensions:f.width?[b.readUInt32BE(16),b.readUInt32BE(20)]:null,matchesFreeze:b.length===f.bytes&&hash(b)===f.sha256&&(!f.width||(b.readUInt32BE(16)===f.width&&b.readUInt32BE(20)===f.height)),matchesCommit:b.equals(git(p))});}
result.freezeUnchanged=fs.readFileSync(path.join(base,'freeze-record.json')).equals(git(path.join(base,'freeze-record.json')));
for(const ref of [...html.matchAll(/(?:src="|url\(")([^"#]+)"/g)].map(m=>m[1]).filter((v,i,a)=>a.indexOf(v)===i)){const p=path.resolve(base,ref),b=fs.readFileSync(p);result.dependencies.push({reference:ref,path:p,bytes:b.length,sha256:hash(b),matchesCommit:b.equals(git(p))});}
for(const [name,p] of [['previous_v1_1',old],['approved_applications_aligned_v1_1',approved]]){const b=body(fs.readFileSync(p,'utf8'));result.body[name]={sha256:hash(b),currentSha256:hash(body(html)),exactBodyEqual:b===body(html)};}
(async()=>{const browser=await chromium.launch({headless:true});result.browser=browser.version();
for(const [width,height] of [[1440,900],[768,1400],[390,1500],[767,1400],[1023,900],[1024,900],[350,1200],[561,1200]]){
const page=await browser.newPage({viewport:{width,height},deviceScaleFactor:1,colorScheme:'light',reducedMotion:'reduce'});const failures=[];page.on('requestfailed',r=>failures.push({url:r.url(),reason:r.failure()}));
await page.goto(pathToFileURL(current).href);await page.evaluate(()=>document.fonts.ready);
const observation=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};};const describe=s=>{const e=document.querySelector(s),c=getComputedStyle(e);return {rect:rect(e),fontSize:c.fontSize,fontWeight:c.fontWeight,lineHeight:c.lineHeight,columns:c.gridTemplateColumns,padding:c.padding,border:c.borderWidth,radius:c.borderRadius,background:c.backgroundColor,backgroundImage:c.backgroundImage,shadow:c.boxShadow};};
const shell=document.querySelector('.hero-shell'),before=getComputedStyle(shell,'::before');
return {viewport:[innerWidth,innerHeight],dpr:devicePixelRatio,fontLoaded:document.fonts.check('16px Inter'),scrollWidths:[document.documentElement.scrollWidth,document.body.scrollWidth],header:describe('.global-header'),shell:describe('.hero-shell'),h1:describe('h1'),h1Text:document.querySelector('h1').innerText,intro:document.querySelector('.hero-copy p:not(.eyebrow)').innerText,media:describe('.hero-media'),mediaLoaded:[document.querySelector('.hero-media img').complete,document.querySelector('.hero-media img').naturalWidth],before:{display:before.display,content:before.content},actions:[...document.querySelectorAll('.hero-actions a')].map(e=>({text:e.textContent,href:e.getAttribute('href'),rect:rect(e),color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor})),start:describe('.start-here'),startLinks:[...document.querySelectorAll('.start-card')].map(e=>({text:e.innerText,href:e.getAttribute('href'),rect:rect(e)})),nonHeroShells:[...document.querySelectorAll('main .shell:not(.hero-shell)')].map(e=>({module:e.closest('[data-module]')?.dataset.module,rect:rect(e)})),horizontalEscapes:[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<-.5||r.right>innerWidth+.5)}).map(e=>e.tagName+'.'+e.className)};});
observation.h1Lines=Math.round(observation.h1.rect.height/parseFloat(observation.h1.lineHeight));
if([1440,768,390,767].includes(width)){await page.waitForTimeout(200);const name=freeze.files.find(f=>f.width===width).path;const buffer=await page.screenshot({fullPage:false,animations:'disabled'});observation.liveRenderMatchesFrozenPNG=buffer.equals(fs.readFileSync(path.join(base,name)));if(width!==767){const previous=path.join(root,'pages/home/04_planning/visual-designs/home-root-page-hero-v1.2',name.replace('V1.3','V1.2'));observation.reusedPNGEqualsPrevious=fs.readFileSync(path.join(base,name)).equals(fs.readFileSync(previous));}}
await page.evaluate(()=>{window.reviewActivations=[];document.querySelectorAll('.hero-actions a').forEach(e=>e.addEventListener('click',ev=>{ev.preventDefault();window.reviewActivations.push({text:e.textContent,href:e.getAttribute('href'),trusted:ev.isTrusted});}));});
await page.locator('.hero-actions a').first().focus();await page.keyboard.press('Tab');observation.tabToSecond=await page.evaluate(()=>document.activeElement===document.querySelectorAll('.hero-actions a')[1]);
observation.focusStyle=await page.locator('.hero-actions a').nth(1).evaluate(e=>{const c=getComputedStyle(e);return {outline:c.outline,offset:c.outlineOffset}});
await page.keyboard.press('Enter');await page.keyboard.press('Shift+Tab');await page.keyboard.press('Enter');observation.activations=await page.evaluate(()=>window.reviewActivations);
observation.requestFailures=failures;const priorPage=await browser.newPage({viewport:{width,height},deviceScaleFactor:1,colorScheme:'light',reducedMotion:'reduce'});await priorPage.goto(pathToFileURL(old).href);await priorPage.evaluate(()=>document.fonts.ready);observation.previousNonHeroShells=await priorPage.evaluate(()=>[...document.querySelectorAll('main .shell:not(.hero-shell)')].map(e=>{const r=e.getBoundingClientRect();return {module:e.closest('[data-module]')?.dataset.module,x:r.x,width:r.width,height:r.height}}));await priorPage.close();result.runtime.push(observation);await page.close();}
await browser.close();
const provenance=freeze.capture_provenance,authorRuntime=JSON.parse(fs.readFileSync(path.join(base,provenance.runtime_record),'utf8'));result.captureProvenance={scriptHashEqual:hash(fs.readFileSync(path.join(base,provenance.script)))===provenance.script_sha256,runtimeHashEqual:hash(fs.readFileSync(path.join(base,provenance.runtime_record)))===provenance.runtime_record_sha256,browserEqual:provenance.browser===authorRuntime.browser,playwrightEqual:provenance.playwright===authorRuntime.playwright,authorMode:authorRuntime.mode,captures:authorRuntime.captures,viewportCount:authorRuntime.inspections.length};result.externalDependencyChecks=freeze.external_dependencies.map(f=>{const b=fs.readFileSync(path.resolve(base,f.path));return {path:f.path,matchesFreeze:b.length===f.bytes&&hash(b)===f.sha256}});fs.writeFileSync(path.join(__dirname,'HOME-ROOT-HERO-G5-IVR-01-recheck-v1.2-runtime.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exit(1)});
