const fs=require('fs'),crypto=require('crypto'),sharp=require('sharp');
const root='D:/23MySec',page=`${root}/pages/markets/italy`,gate=`${page}/04_planning/gate4-v0.1`,review=`${page}/05_review/gate4-complete-independent-v0.1`,out=`${page}/05_review/gate4-project-control-v0.1`;
fs.mkdirSync(out,{recursive:true});
const paths={input:`${gate}/MARKET-EU-IT_GATE4_INPUT_INDEX_V0.1.json`,workset:`${gate}/MARKET-EU-IT_GATE4_WORKSET_V0.1.json`,freeze:`${gate}/MARKET-EU-IT_GATE4_FREEZE_RECORD_V0.1.json`,evidence:`${gate}/MARKET-EU-IT_GATE4_EVIDENCE_INDEX_V0.1.json`,independent:`${review}/REVIEW.md`,reviewIndex:`${review}/review-evidence-index.json`};
const ident=p=>{const b=fs.readFileSync(p);return{path:p,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}};
const exact=x=>{if(!x?.path||!fs.existsSync(x.path))return{declared:x,exists:false,exact:false};const actual=ident(x.path);return{declared:x,exists:true,actual,exact:x.bytes===actual.bytes&&x.sha256===actual.sha256}};
(async()=>{const input=JSON.parse(fs.readFileSync(paths.input)),freeze=JSON.parse(fs.readFileSync(paths.freeze)),evidence=JSON.parse(fs.readFileSync(paths.evidence)),reviewIndex=JSON.parse(fs.readFileSync(paths.reviewIndex));
 const inputs=input.inputs.map(exact);const freezeParts=[freeze.source,freeze.input_index,freeze.workset,freeze.preflight,freeze.direction_check,freeze.runtime_verification,freeze.static_visual_readback,...freeze.dependencies].map(exact);const top=[evidence.source,evidence.freeze,evidence.input_index].map(exact);const reviewRecords=reviewIndex.records.filter(x=>x.path!==paths.reviewIndex).map(exact);const reviewImages=reviewIndex.independent_images.map(exact),contactSheets=reviewIndex.contact_sheets.map(exact);
 const images=[];for(const x of evidence.images){const a=exact(x),m=a.exists?await sharp(x.path).metadata():{};const declared=Number.isFinite(x.physical_width)&&Number.isFinite(x.physical_height)&&Number.isFinite(x.dpr);images.push({...a,state:x.state,logical_width:x.logical_width,declaredDimensions:declared?[x.physical_width,x.physical_height,x.dpr]:null,actualDimensions:a.exists?[m.width,m.height]:null,dimensionStatus:!declared?'NOT_DECLARED':(m.width===x.physical_width&&m.height===x.physical_height&&x.dpr===1?'EXACT':'MISMATCH')})}
 const result={page_id:'MARKET-EU-IT',workset_id:evidence.workset_id,freeze_id:evidence.freeze_id,audited_at:new Date().toISOString(),records:Object.fromEntries(Object.entries(paths).map(([k,p])=>[k,ident(p)])),status_checks:{workset_status:JSON.parse(fs.readFileSync(paths.workset)).status,executor_evidence_status:evidence.status,independent_review_status:reviewIndex.status,required_findings:reviewIndex.required_findings},frozen_inputs:{exact:inputs.filter(x=>x.exact).length,total:inputs.length,mismatches:inputs.filter(x=>!x.exact)},freeze_components:{exact:freezeParts.filter(x=>x.exact).length,total:freezeParts.length,mismatches:freezeParts.filter(x=>!x.exact)},evidence_top_pointers:{exact:top.filter(x=>x.exact).length,total:top.length,mismatches:top.filter(x=>!x.exact)},executor_images:{identity_exact:images.filter(x=>x.exact).length,total:images.length,identity_mismatches:images.filter(x=>!x.exact),dimensions_declared:images.filter(x=>x.dimensionStatus!=='NOT_DECLARED').length,dimensions_exact:images.filter(x=>x.dimensionStatus==='EXACT').length,dimension_mismatches:images.filter(x=>x.dimensionStatus==='MISMATCH'),dimensions_not_declared:images.filter(x=>x.dimensionStatus==='NOT_DECLARED')},independent_records:{exact:reviewRecords.filter(x=>x.exact).length,total:reviewRecords.length,mismatches:reviewRecords.filter(x=>!x.exact)},independent_images:{exact:reviewImages.filter(x=>x.exact).length,total:reviewImages.length,mismatches:reviewImages.filter(x=>!x.exact)},contact_sheets:{exact:contactSheets.filter(x=>x.exact).length,total:contactSheets.length,mismatches:contactSheets.filter(x=>!x.exact)}};
 fs.writeFileSync(`${out}/identity-audit.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({records:result.records,checks:result.status_checks,inputs:`${result.frozen_inputs.exact}/${result.frozen_inputs.total}`,freeze:`${result.freeze_components.exact}/${result.freeze_components.total}`,top:`${result.evidence_top_pointers.exact}/${result.evidence_top_pointers.total}`,images:`${result.executor_images.identity_exact}/${result.executor_images.total}`,dimensions:`${result.executor_images.dimensions_exact}/${result.executor_images.dimensions_declared}`,dimensionMismatches:result.executor_images.dimension_mismatches.map(x=>({path:x.declared.path,declared:x.declaredDimensions,actual:x.actualDimensions})),dimensionsNotDeclared:result.executor_images.dimensions_not_declared.map(x=>({path:x.declared.path,actual:x.actualDimensions})),reviewRecords:`${result.independent_records.exact}/${result.independent_records.total}`,reviewImages:`${result.independent_images.exact}/${result.independent_images.total}`,contactSheets:`${result.contact_sheets.exact}/${result.contact_sheets.total}`},null,2))})();
