// PROTOTYPE_ONLY: page slot projection. D32 owns the single production RootPageHero and Chrome.
const fs=require('fs'),path=require('path');
const {renderSharedChrome}=require('../../../../docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs');
const out=__dirname,upstream=path.resolve(out,'../MARKET-000_CONTENT_ARCHITECTURE_V0.1.md');
const text=fs.readFileSync(upstream,'utf8'),blocks=[...text.split('## 5.')[0].matchAll(/```text\s*\n([\s\S]*?)```/g)].map(x=>x[1].trim());
const esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const b=i=>esc(blocks[i]);const p=i=>`<p data-copy="${i}">${b(i)}</p>`;const heading=(eye,title)=>`<p class="eyebrow" data-copy="${eye}">${b(eye)}</p><h2 data-copy="${title}">${b(title)}</h2>`;
const columns=indices=>indices.map(i=>{const [title,...body]=blocks[i].split('\n');return `<article class="textCard" data-copy="${i}"><h3>${esc(title)}</h3><p>${esc(body.join(' '))}</p></article>`}).join('');
const action=(label,href,type='market')=>`<a class="textAction ${type==='support'?'supportAction':''}" data-ready-action="${type}" href="${href}">${esc(label)}</a>`;
const chrome=renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf'});
const countries=blocks[12].split('\n');const qa=[...text.matchAll(/#### Q([1-6])\. (.+)\r?\n/g)].map(m=>m[2].trim());
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Markets for Titanium Dioxide Procurement | TiO2 Malaysia</title><style>${chrome.style}</style><link rel="stylesheet" href="planning.css"></head><body><a class="skip" href="#main">Skip to content</a>${chrome.header}<main id="main" tabindex="-1"><div class="wrap"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span>Markets</span></nav>
<section class="rootHero" data-component="RootPageHero" data-variant="hub-light" data-module="HERO" aria-labelledby="page-title"><div class="heroText"><p class="eyebrow" data-copy="0">${b(0)}</p><h1 id="page-title" data-copy="1">${b(1)}</h1>${p(2)}<div class="actions"><a class="primary" data-copy="3" href="#destination-selector">${b(3)}</a></div></div><aside class="heroIndex" aria-label="Destination market summary"><p class="eyebrow">${b(5)}</p><ul><li>European Union</li><li>United Kingdom</li><li>India</li><li>Brazil</li></ul></aside></section></div>
<section class="band" id="destination-selector" data-module="DESTINATION_SELECTOR"><div class="wrap section">${heading(5,6)}${p(7)}<div class="destinationGrid"><article class="euPanel"><h3>${b(8)}</h3>${p(9)}${action(blocks[10],'/markets/european-union/')}<h4>${b(11)}</h4><button id="eu-toggle" aria-controls="eu-countries" aria-expanded="true" hidden>Hide EU country destinations</button><ul id="eu-countries">${countries.map(name=>`<li>${action(name,'/markets/'+name.toLowerCase()+'/')}</li>`).join('')}</ul></article><div class="marketRail">${[['United Kingdom',14,15,'united-kingdom'],['India',16,17,'india'],['Brazil',18,19,'brazil']].map(([name,body,label,slug])=>`<article class="marketCard"><h3>${name}</h3>${body===18?'<p data-delta="Brazil">Use the Brazil path when your next procurement questions need a Brazil-specific market context.</p>':p(body)}${action(blocks[label],'/markets/'+slug+'/')}</article>`).join('')}</div></div></div></section>
<section class="wrap section" data-module="MARKET_CHOICE_GUIDE">${heading(20,21)}${p(22)}<div class="threeColumns">${columns([23,24,25])}</div><div class="directAnswer">${p(26)}</div></section>
<section class="band" data-module="PROCUREMENT_PATHS"><div class="wrap section">${heading(27,28)}${p(29)}<div class="threeColumns">${[30,31,32].map((i,n)=>columns([i]).replace('</article>',action(['Explore Products','Explore Applications','Review Documents'][n],['/products/','/applications/','/documents/'][n],'support')+'</article>')).join('')}</div></div></section>
<section class="wrap section trade" data-module="TRADE_BOUNDARY">${heading(33,34)}${p(35)}${action('Review Resources','/resources/','support')}</section>
<section class="band" data-module="BUYER_QUESTIONS"><div class="wrap section">${heading(37,38)}<div class="questions">${qa.map((q,n)=>`<article data-question><h3>${esc(q)}</h3>${p(39+n)}</article>`).join('')}</div></div></section></main>${chrome.footer}${chrome.dialog}<script>${chrome.behavior}</script><script src="planning.js"></script></body></html>`;
fs.writeFileSync(path.join(out,'market-planning.html'),html);
fs.writeFileSync(path.join(out,'content-map.json'),JSON.stringify({page_id:'MARKET-000',site_scope:'tio2-my',role:'PROTOTYPE_ONLY',source:upstream,copy_blocks:blocks.map((value,index)=>({index,value})),applied_approved_deltas:{source:'MARKET-000_FULL_VISUAL_DESIGN_V0.4.md §2–4; Brief §2 rows 20–23',removed:[4,36,45,46,47,48,49,50],brazil:'Use the Brazil path when your next procurement questions need a Brazil-specific market context.',added:'Review Resources'},module_order:['HERO','DESTINATION_SELECTOR','MARKET_CHOICE_GUIDE','PROCUREMENT_PATHS','TRADE_BOUNDARY','BUYER_QUESTIONS'],production_owner:'D32 shared RootPageHero + Global Chrome; this projection is not a new component implementation'},null,2));
console.log('Built complete MARKET-000 PROTOTYPE_ONLY projection');
