const fs=require('fs'),path=require('path'),crypto=require('crypto');const {pathToFileURL}=require('url');const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,formal=process.argv.includes('--formal'),target=path.join(dir,formal?'approval_core':'diagnostic_support/segments');fs.mkdirSync(target,{recursive:true});
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
(async()=>{if(formal){const freeze=JSON.parse(fs.readFileSync(path.join(dir,'freeze.json'),'utf8'));for(const x of freeze.sources)if(hash(x.path)!==x.sha256)throw Error('Frozen source changed: '+x.path);}
const browser=await chromium.launch({headless:true}),page=await browser.newPage();const assets=[];
async function shot(name,options){const file=path.join(target,name+'.png');await page.screenshot({path:file,...options});const bytes=fs.readFileSync(file);assets.push({path:file,bytes:bytes.length,sha256:hash(file),logical_width:page.viewportSize().width,physical_width:bytes.readUInt32BE(16),physical_height:bytes.readUInt32BE(20),scale:1,state:name});}
for(const width of [1440,768,390]){await page.setViewportSize({width,height:1000});await page.goto(pathToFileURL(path.join(dir,'market-planning.html')).href);await page.evaluate(()=>document.fonts.ready);
if(formal){await shot(`MARKET-000_D32_G3_FULL_${width}`,{fullPage:true});if(width!==1440){await page.locator('.menuButton').click();await shot(`MARKET-000_D32_G3_MENU_${width}`,{fullPage:false});await page.keyboard.press('Escape');}if(width===390){await page.locator('#eu-toggle').click();await page.locator('.euPanel').scrollIntoViewIfNeeded();await shot('MARKET-000_D32_G3_EU_EXPANDED_390',{fullPage:false});await page.locator('#cookie-trigger').click();await shot('MARKET-000_D32_G3_COOKIE_390',{fullPage:false});await page.keyboard.press('Escape');}}
else{if(width===390)await page.locator('#eu-toggle').click();const height=await page.locator('body').evaluate(e=>e.scrollHeight);for(let y=0;y<height;y+=900){await page.evaluate(y=>scrollTo(0,y),y);await shot(`${width}-${y}`,{fullPage:false});}}
}
if(formal){for(const state of ['none','eu-only','support-only']){await page.goto(pathToFileURL(path.join(dir,'market-planning.html')).href+'?state='+state);await page.evaluate(()=>document.fonts.ready);await page.locator('#eu-toggle').click();await shot(`MARKET-000_D32_G3_${state.toUpperCase()}_390`,{fullPage:true});}}
fs.writeFileSync(path.join(target,'asset-index.json'),JSON.stringify({timestamp:new Date().toISOString(),evidence_type:'STATIC_VISUAL; route modes are LOCAL_SIMULATION',renderer:await browser.version(),assets},null,2));console.log(JSON.stringify({formal,assets:assets.length,target}));await browser.close();})();
