const fs=require('fs'),crypto=require('crypto'),out='D:/23MySec/pages/products/sulfate-process/04_planning/gate3-v0.1',id='PRODUCT-PROC-SU',review='D:/23MySec/pages/products/sulfate-process/05_review',evidence=review+'/'+id+'_GATE3_EXECUTION_EVIDENCE_V0.1',read=p=>JSON.parse(fs.readFileSync(p)),ident=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));fs.mkdirSync(evidence,{recursive:true});const formalPath=evidence+'/formal-runtime.json';fs.renameSync(out+'/approval_core/runtime.json',formalPath);const r=read(formalPath),d=read(out+'/diagnostic_support/render/runtime.json'),f=read(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json'),b=read(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json');function verify(v){if(!v||typeof v!=='object')return;if(v.path&&v.sha256){const a=ident(v.path);if(a.sha256!==v.sha256.toLowerCase()||(v.bytes!=null&&a.bytes!==v.bytes))throw Error('Identity changed '+v.path)}for(const x of Object.values(v))if(typeof x==='object')verify(x)}verify(b);verify(f);verify(r.source);verify(r.assets);if(r.status!=='PASS')throw Error('Formal runtime failed');const matches=r.assets.map(a=>({formal:ident(a.path),diagnostic:d.assets.find(x=>x.state===a.state&&x.logicalViewport.width===a.logicalViewport.width),identical:a.sha256===d.assets.find(x=>x.state===a.state&&x.logicalViewport.width===a.logicalViewport.width).sha256}));if(matches.some(x=>!x.identical))throw Error('Formal pixels differ');save(evidence+'/formal-visual-observation.json',{at:new Date().toISOString(),role:'EXECUTION_SELF_CHECK',source:f.source,actualOpenedFormalAssets:r.assets,diagnosticPixelMatches:matches,nativeReadableCoverage:ident(out+'/diagnostic_support/preflight-visual-observation.json'),observations:['All eight formal PNGs actually opened. Full-page overviews are supplemented by 19 native readable clips of byte-identical diagnostics, not treated as readable-only thumbnails.','All content through copyright is visible at three widths; five Grade records remain neutral and complete.','Two menu and three Cookie formal images match actual runtime states and remain readable.'],unresolvedFindings:[]});
const report=out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md',self=review+'/'+id+'_GATE3_EXECUTION_SELF_CHECK_V0.1.md';
fs.writeFileSync(report,`# Sulfate Gate 3 design method report

DRAFT_FOR_PROJECT_CONTROL_REVIEW. PRODUCT-PROC-SU, EN, Process aggregation, /products/sulfate-process-titanium-dioxide/, site_scope=tio2-my. This is the last authorized serial page under G3-8PAGE-SERIAL-01 V1.7. Execution output does not grant independent review PASS, Gate closure or Gate 4 authority.

Input card and actual identity binding preceded the fresh candidate. The current Manifest V0.5 and administrative module-count correction V0.1 supersede the initial V0.4 binding, preserved under diagnostic_support. Approved A V0.1, B V0.2, C V0.1, Brief V0.2 and Gate 2 review retain exact approved hashes. C's historical B V0.1 pointer is superseded by the current Manifest/review binding to B V0.2. The corrected structure is five body modules, with Breadcrumb before and Shared Footer after. The historical Playbook's M-2377 hold is superseded by approved PRODUCT relationship V0.3 and this Brief; no old hold or old link-suppression rule is reintroduced.

| B location | Structure and key choice |
|---|---|
| Breadcrumb / Hero | Editorial labels are omitted; complete breadcrumb, H1 and lead remain. Primary Explore Sulfate Grades is an ordinary #sulfate-grades link; RFQ is secondary. Mobile actions stack. |
| What the Sulfate Process Tells You | Definition, category limitation, FTC general-process source qualification and 6 September 2026 review date stay together before the directory. No plant or comparative claim. |
| Explore Sulfate Grades | Five equal-status vertical records, neutral order M-996/M-2196/M-108/M-52/M-2377. Desktop name/summary/action columns become tablet name/body rows with action beneath the summary, then mobile stacks. Exact summaries and URLs stay attached; no ranking or comparative values. Closing qualification stays outside the last record. |
| Continue Your Evaluation | Three discrete heading/body/action groups: Application, Documents, Compare Production Routes. Both Documents paragraphs and the light comparison-guide handoff remain complete. No comparison conclusion is added. |
| Request a Quote | Exact unknown-Grade and Additional Requirements instructions; CTA followed by approved after-submit expectation. No page form or result state. |

The Agent V0.2 and both V0.2 Skills were read and actually applied. responsive-wireframe-design supplied input mapping, fresh neutral assembly, three independent layouts, diagnostic risk inspection, hard preflight and freeze-before-export. layout-interaction-verification supplied the separately saved core/risk execution self-check, actual browser operations and actual image inspection. Method identities are in the binding, and the Skill preflight checker result is saved. Unchanged common root/governance/brand/Chrome/legal inputs already read in this execution session were reused under the root rule.

Shared Header/Footer/Cookie are generated solely from neutral Shared Consumer V0.2 with currentPageId=PRODUCT-000. No Chloride or other business page supplied markup, styles or dependencies. Shared owner authority remains unchanged; production primary/reverse SVGs are direct original references, while Inter and its license have durable local copies. Main functional links, outline controls, focus and primary CTA use #008078. Ordinary links preserve approved hrefs; the local recorder prevents navigation and records only internal source_page_id for RFQ/Documents. No Grade/Application preselection, invented query or optional process text is injected. The optional editable process-context permission is not exercised.

Finding SU-G3-01: first diagnostic candidate omitted page base font/margin, yielding computed Times New Roman and default 8px margin. It was found during actual image viewing and computed-style inspection despite other runtime checks passing. Initial source and diagnostics are preserved. Page-local Inter font, margin 0 and box-sizing reset corrected the omission; all three widths were rerendered and rechecked. Inter loaded/font, full footer geometry and 19 native clips plus menu/Cookie/anchor views confirm the correction. No shared or approved source changed. The earlier runtime PASS was never promoted to preflight approval.

Hard preflight and checker PASS_FOR_FORMAL_RENDER preceded freeze at ${f.frozenAt}. Frozen source: ${f.source.bytes} bytes; SHA-256 ${f.source.sha256}. Approved inputs, shared source/files, dependencies and preflight hash were bound while approval_core was empty. Only afterward were eight formal PNGs first generated. All eight were opened and match the inspected revised diagnostics byte-for-byte; full-page heights 3534/4410/5386. The inventory lists exact dimensions/bytes/hashes. Nineteen native clips and three anchor screenshots remain diagnostic support; source, eight formal PNGs and final identity/review records are approval core.

Unresolved Findings: 0 in execution. Unverified: real destination routes/receiving/prefill/email, production canonical/indexing/Schema, current external FTC PDF availability/content revalidation, live cookie inventory, native 200% browser zoom, assistive technology, real touch devices and non-Chrome engines. No external request was sent. These local planning results do not establish production readiness; stop for independent project-control review.
`);
fs.writeFileSync(self,`# PRODUCT-PROC-SU Gate 3 execution self-check V0.1

DRAFT_FOR_PROJECT_CONTROL_REVIEW. Execution self-check using layout-interaction-verification V0.2; not independent project-control PASS or user approval. Source ${f.source.path}, ${f.source.bytes} bytes, SHA-256 ${f.source.sha256}. Chrome ${r.browser}; logical 1440×900, 768×900, 390×844; DPR 1. Complete formal pages 1440×3534, 768×4410, 390×5386.

| Fixed core | Evidence and result |
|---|---|
| Freeze identity | SOURCE_INSPECTION: actual Manifest V0.5/correction, A/B/C/Brief/review/authorization and neutral shared files/owners/dependencies verified before freeze and handoff. Frozen source unchanged; formal exports first generated after freeze. PASS. |
| Content and relationships | ACTUAL_RUNTIME: normalized complete public B equals visible main bidirectionally at all three widths; editorial metadata/Breadcrumb/Hero labels excluded, public headings/prose/links preserved. All ordered label/href pairs, five exact Grade relations, five body modules and three evaluation groups verified. STATIC_VISUAL: all revised content through footer read in 19 native clips. PASS. |
| Geometry and font | ACTUAL_RUNTIME: no horizontal overflow or clipping containers; every visible action target at least 44×44. SU-G3-01 repair confirms Inter loaded, computed Inter and zero body margin at three widths; legal/copyright inside document height. STATIC_VISUAL: no collision, truncation or abnormal fixed gaps. PASS after repair. |
| Shared assembly | SOURCE_INSPECTION/ACTUAL_RUNTIME: neutral V0.2 and PRODUCT-000, Products current, fixed RFQ, original approved SVGs, current footer/legal/consent and functional Teal. No other business-page dependency. PASS. |
| Overlays | ACTUAL_RUNTIME: Menu first Home focus, both focus loops, Esc/Close, eight selection exits, background inert/restoration, actual wheel lock/unlock and desktop-breakpoint exit at 768/390. Three Cookie dialogs: Close first focus, loops, policy href, Close/Esc trigger return. STATIC_VISUAL: five formal states opened. PASS. |
| Actions | ACTUAL_RUNTIME: three-width #sulfate-grades click/Enter scroll and focus to Grade-section H2; next Tab reaches View M-996; direct fragment works. With JavaScript disabled, complete B and all five ordinary Grade links remain; ordinary fragment navigation reaches heading. LOCAL_SIMULATION: all other links record exact href only, RFQ/Documents add internal source_page_id only; no Grade/Application prefill or query. No external request. PASS for local intent; production acceptance untested. |
| Complete visual coverage | STATIC_VISUAL: three revised full-page overviews, 19 overlapping native clips, two menus, three Cookie and three anchor views inspected. All eight formal images opened; hashes exactly match revised diagnostics so native readable coverage applies to unchanged formal pixels. PASS. |

Four risk conclusions:

1. Hardest reading: the general FTC source note and long Documents cardinality conditions. Three-width native clips preserve general-route qualification and date adjacent to the source, one Grade/multiple document types, additional candidates as context and separate per-Grade requests. The source is not visually presented as evidence for a plant or Grade performance.
2. Most failure-prone operation: Hero anchor followed by keyboard navigation, and shared overlays. Actual click/Enter/direct-fragment/no-JS checks and next-Tab-to-first-Grade passed; menus and Cookie restore focus/background. Form empty/error/submitting/success states are NOT_APPLICABLE because B/C authorize no local form. Receiving-form behavior remains untested.
3. Riskiest responsive conversion: five neutral directory records and three evaluation groups become mobile stacks. Exact names, summaries, URLs and group ownership persist; M-996 and M-2196 have equal treatment, no ranking, badges or difference block. M-2377 stays in the five-Grade set without Rubber/Specialty taxonomy. Approved Compare Production Routes remains a light guide handoff; no route superiority or category-derived property is added.
4. Unresolved Findings: 0. SU-G3-01 is resolved in execution self-check; initial source/diagnostics and separate recheck are retained. Production destination routes/prefill/receiving/email, canonical/indexing/Schema, live cookies and FTC source freshness/availability were not tested. Neither were native 200% browser zoom, assistive technology, physical touch hardware or non-Chrome engines. Subsequent owner/implementation verification retains these responsibilities; no Gate 4/development/approval is granted.

The administrative count ambiguity was resolved by project control's bound correction and Manifest V0.5, without changes to approved A/B/C. All five approved summaries and neutral ordering were checked against B and current relationship boundaries; no independent new factual research or expansion occurred. Tables, FAQ, selectors, content media and selection/result states are NOT_APPLICABLE. The in-document anchor is real navigation, not an invented Grade selection state.

Evidence: ${evidence}/formal-runtime.json and formal-visual-observation.json; ${out}/diagnostic_support holds detailed runtime, revised clips/states, initial candidate/diagnostics, SU-G3-01 and recheck, preflight checker and binding history. Core assets and report identities are in the asset inventory. Reports were saved and read back, formal images actually opened. Coverage is not a score and execution self-check does not replace independent review. Stop here.
`);
const records=['TASK_INPUT_CARD','INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD','DESIGN_METHOD_REPORT'].map(n=>({...ident(out+'/'+id+'_GATE3_'+n+'_V0.1.'+(['INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD'].includes(n)?'json':'md')),role:'approval_core'}));records.push({...ident(self),role:'approval_core'});const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:id,source:{...f.source,role:'approval_core'},formalAssets:r.assets,records,sharedConsumer:b.sharedConsumer,dependencies:b.dependencies,diagnosticSupport:{design:out+'/diagnostic_support',execution:evidence},frozenAt:f.frozenAt,resolvedFindings:['SU-G3-01'],unresolvedFindings:[],notVerified:['Production routes/receivers/prefill/email/canonical/indexing/Schema/live cookie inventory','External FTC source availability or fresh content review','Native 200% zoom, assistive technology, real touch devices and other browser engines']};save(out+'/'+id+'_GATE3_ASSET_INVENTORY_V0.1.json',inventory);verify(inventory);verify(f);verify(b);save(evidence+'/final-identity-check.json',{at:new Date().toISOString(),status:'PASS',source:f.source,formalAssetsVerified:r.assets.length,formalDiagnosticPixelsIdentical:true,recordsVerified:records.length,unresolvedFindings:[]});console.log(JSON.stringify({source:f.source,report,self,inventory:out+'/'+id+'_GATE3_ASSET_INVENTORY_V0.1.json',formalAssets:r.assets.map(a=>({path:a.path,bytes:a.bytes,dimensions:a.physicalPixels}))},null,2));
