const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),binding=JSON.parse(fs.readFileSync(out+'/DOC-COO_GATE3_INPUT_BINDING_V0.1.json')),source=binding.candidate.path;
const formal=process.argv[2]==='formal',target=formal?out+'/approval_core':__dirname+'/candidate-v0.1-r2',sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');fs.mkdirSync(target,{recursive:true});
if(formal){const f=JSON.parse(fs.readFileSync(out+'/DOC-COO_GATE3_FREEZE_RECORD_V0.1.json'));if(f.candidate.sha256!==sha(source))throw Error('Frozen source mismatch');}
const b=fs.readFileSync(binding.inputs.B.path,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim();
const norm=s=>s.replace(/\s+/g,' ').replace(/\s+([,.;:])/g,'$1').trim();
const expected=norm(b.replace(/^\|[-| ]+\|$/gm,'').replace(/^#{1,3} /gm,'').replace(/^\d+\. /gm,'').replace(/^- /gm,'').replaceAll('|',' ').replace(/\*\*([^*]+)\*\*/g,' $1 ').replace(/\[([^\]]+)\]\(([^)]+)\)/g,' $1 '));
const links=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({label:m[1],href:m[2]}));
const tableLines=b.split(/\r?\n/).filter(l=>l.startsWith('|')),tableExpected=tableLines.filter((l,i)=>i!==1).map(l=>l.split('|').slice(1,-1).map(s=>s.trim().replaceAll('**','')));
const results=[],assets=[],network=[],errors=[];let engine;
const check=(key,passed,actual)=>results.push({key,status:passed?'PASS':'FAIL',actual});
const save=()=>fs.writeFileSync(target+'/runtime-checks.json',JSON.stringify({source:{path:source,bytes:fs.statSync(source).size,sha256:sha(source)},mode:formal?'formal':'diagnostic',at:new Date().toISOString(),engine,evidenceTypes:['ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION'],results,failures:results.filter(r=>r.status==='FAIL'),network,errors,assets},null,2));
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});engine={browser:browser.version(),node:process.version,playwright:require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json').version};try{
for(const width of [1440,768,390]){
 const height=width===390?844:900,ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});await ctx.route(/^https?:/,r=>{network.push(r.request().url());r.abort()});
 const page=await ctx.newPage();page.on('pageerror',e=>errors.push(String(e)));await page.goto(pathToFileURL(source).href);
 const settle=async()=>page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});await settle();
 const shot=async(state,full=false)=>{const file=target+'/'+(formal?`DOC-COO_GATE3_${width}_${state.toUpperCase()}_V0.1.png`:`${width}-${state}.png`);await page.screenshot({path:file,fullPage:full});assets.push({path:file,logicalWidth:width,viewportHeight:height,state,bytes:fs.statSync(file).size,sha256:sha(file)});};
 const content=await page.locator('main').evaluate(main=>{const c=main.cloneNode(true);c.querySelectorAll('.cellLabel').forEach(n=>n.remove());const w=document.createTreeWalker(c,NodeFilter.SHOW_TEXT),t=[];while(w.nextNode())t.push(w.currentNode.textContent);return t.join(' ')});
 check(width+' B canonical full content incl comparison headings',norm(content)===expected,{expected,actual:norm(content)});
 const actualLinks=await page.locator('main a').evaluateAll(ns=>ns.map(n=>({label:n.textContent,href:n.getAttribute('href')})));check(width+' exact B links in order',JSON.stringify(actualLinks)===JSON.stringify(links),actualLinks);
 const table=await page.locator('.evidenceTable').evaluate(t=>({heads:[...t.querySelectorAll('thead th')].map(n=>n.textContent),rows:[...t.querySelectorAll('tbody tr')].map(row=>[...row.querySelectorAll('.cellValue')].map(n=>({text:n.textContent,visible:!!n.getClientRects().length,x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height}))),labels:[...t.querySelectorAll('.cellLabel')].filter(n=>n.getClientRects().length).map(n=>n.textContent)}));
 check(width+' table exact objects/fields/row order',JSON.stringify([table.heads,...table.rows.map(row=>row.map(n=>n.text))])===JSON.stringify(tableExpected)&&table.rows.flat().every(n=>n.visible&&n.w>0&&n.h>0),table);
 check(width+' responsive table label relationships',width>1000?table.labels.length===0:JSON.stringify(table.labels)===JSON.stringify(Array(3).fill(tableExpected[0]).flat()),table.labels);
 const geom=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,modules:[...document.querySelectorAll('main section')].map(n=>n.id),headings:[...document.querySelectorAll('main h1,main h2')].map(n=>n.textContent),hiddenBody:[...document.querySelectorAll('main p,main li,main .cellValue')].filter(n=>!n.getClientRects().length).length,controls:[...document.querySelectorAll('a,button')].filter(n=>n.getClientRects().length).map(n=>({label:n.textContent||n.getAttribute('aria-label'),width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height,left:n.getBoundingClientRect().left,right:n.getBoundingClientRect().right})),forms:document.querySelectorAll('main form,main input,main select,main details').length}));
 check(width+' six modules all visible no horizontal overflow',geom.scroll<=width&&geom.hiddenBody===0&&geom.modules.length===6&&geom.headings.length===6&&geom.forms===0,geom);
 check(width+' every default target 44x44',geom.controls.every(n=>n.width>=43.99&&n.height>=43.99&&n.left>=-0.01&&n.right<=width+.01),geom.controls.filter(n=>n.width<43.99||n.height<43.99||n.left<-.01||n.right>width+.01));
 check(width+' no excluded company availability claim',!await page.locator('main').evaluate(n=>/A Certificate of Origin is available upon request|available for every|guaranteed issuance/.test(n.textContent)),null);
 const risk=await page.evaluate(()=>({comparisonScope:document.querySelector('#coo-02>p:last-child').textContent,context:document.querySelector('#coo-03').textContent,traceability:document.querySelector('#coo-04').textContent,request:document.querySelector('#coo-05').textContent,source:document.querySelector('#coo-06').textContent,current:[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].map(n=>n.textContent),functional:[...document.querySelectorAll('main a')].map(n=>({label:n.textContent,color:getComputedStyle(n).color,bg:getComputedStyle(n).backgroundColor}))}));
 check(width+' comparison qualifier/context/traceability/request/source relationship',risk.comparisonScope.includes('certificate alone does not decide')&&risk.context.includes('Country / Region is for your company location.')&&risk.traceability.includes('One does not automatically establish the other.')&&risk.request.includes('one Product Grade per submission')&&risk.request.includes('submission does not confirm certificate issuance or a customs outcome.')&&risk.source.includes('10 October 2025')&&risk.source.includes('5 January 2026')&&risk.source.includes('7 September 2026'),risk);
 check(width+' Documents current / functional colors',risk.current.join(',')==='Documents,Documents'&&risk.functional.every(n=>n.color===(n.label==='Request Origin Documentation'?'rgb(255, 255, 255)':'rgb(0, 128, 120)')),null);
 await shot('full',true);if(!formal){fs.mkdirSync(target+'/segments',{recursive:true});for(let y=0,i=1;y<geom.height;y+=750,i++)await page.screenshot({path:target+`/segments/${width}-${String(i).padStart(2,'0')}.png`,fullPage:true,clip:{x:0,y,width,height:Math.min(900,geom.height-y)}});}
 for(let i=0;i<links.length;i++){await page.locator('main a').nth(i).click();const intent=await page.evaluate(()=>window.__navigationIntents.at(-1));const expectedContext=links[i].label==='Request Origin Documentation'?{prefill:{document_types:['origin_supplier_qualification']},source_context:{page_id:'DOC-COO'}}:null;check(width+' local navigation '+i,intent.href===links[i].href&&JSON.stringify(intent.context)===JSON.stringify(expectedContext)&&intent.receiverExecuted===false,intent);}
 const outside=links.filter(n=>n.href.startsWith('https:'));check(width+' two correctly attributed official links',outside.length===2&&outside.every(n=>n.href==='https://www.customs.gov.my/en/business/facilitation/rules-of-origin-roo/faq-rules-of-origin'),outside);
 if(width<1101){
  const state=()=>page.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),label:document.querySelector('.menuButton').textContent,active:document.activeElement.textContent,overflow:document.body.style.overflow,inert:[...document.querySelectorAll('main,footer,.logoLink,.headerRfq')].map(n=>n.inert),y:scrollY}));
  await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();let s=await state();check(width+' menu enters/focus/isolates',!s.hidden&&s.active==='Home'&&s.label==='Close'&&s.overflow==='hidden'&&s.inert.every(Boolean),s);await shot('menu');
  check(width+' menu target/color sizes',await page.locator('.mobileNav a,.menuButton').evaluateAll(ns=>ns.every(n=>n.getBoundingClientRect().width>=44&&n.getBoundingClientRect().height>=44))&&await page.locator('.menuButton').evaluate(n=>getComputedStyle(n).borderTopColor==='rgb(0, 128, 120)'),null);
  await page.keyboard.press('Shift+Tab');check(width+' menu shift to Close',await page.locator('.menuButton').evaluate(n=>n===document.activeElement),null);await page.keyboard.press('Shift+Tab');check(width+' menu reverse cycle',await page.locator('.mobileNav a').last().evaluate(n=>n===document.activeElement),null);await page.keyboard.press('Tab');check(width+' menu forward cycle',await page.locator('.menuButton').evaluate(n=>n===document.activeElement),null);
  await page.mouse.move(width-10,700);await page.mouse.wheel(0,400);await page.waitForTimeout(100);check(width+' menu body scroll locked',(await state()).y===0,await state());await page.keyboard.press('Escape');s=await state();check(width+' Escape restores focus/background',s.hidden&&s.active==='Menu'&&s.inert.every(n=>!n)&&s.overflow==='',s);await page.mouse.wheel(0,350);await page.waitForTimeout(100);check(width+' body scroll restored',(await state()).y>0,await state());
  for(let i=0;i<8;i++){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();const href=await page.locator('.mobileNav a').nth(i).getAttribute('href');await page.locator('.mobileNav a').nth(i).click();s=await state();check(width+' menu link closes '+i,s.hidden&&s.inert.every(n=>!n)&&s.overflow===''&&(await page.evaluate(()=>window.__navigationIntents.at(-1).href))===href,s);}
  await page.locator('.menuButton').click();await page.locator('.menuButton').click();check(width+' Close action',(await state()).hidden,null);await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height});await settle();s=await state();check(width+' desktop crossing closes/restores',s.hidden&&s.inert.every(n=>!n)&&s.overflow==='',s);await page.setViewportSize({width,height});await settle();
 }
 await page.locator('#cookie-trigger').click();await settle();check(width+' Cookie enters Close focus',await page.locator('[data-cookie-close]').evaluate(n=>n===document.activeElement),null);await shot('cookie');
 const cookie=await page.locator('.cookie-layer').evaluate(n=>({visible:n.open,x:n.getBoundingClientRect().x,y:n.getBoundingClientRect().y,right:n.getBoundingClientRect().right,bottom:n.getBoundingClientRect().bottom,controls:[...n.querySelectorAll('a,button')].map(a=>({w:a.getBoundingClientRect().width,h:a.getBoundingClientRect().height,color:getComputedStyle(a).color,border:getComputedStyle(a).borderTopColor}))}));check(width+' Cookie geometry/44/color',cookie.visible&&cookie.x>=0&&cookie.y>=0&&cookie.right<=width&&cookie.bottom<=height&&cookie.controls.every(c=>c.w>=44&&c.h>=44&&c.color==='rgb(0, 128, 120)'&&c.border==='rgb(0, 128, 120)'),cookie);
 await page.keyboard.press('Shift+Tab');check(width+' Cookie reverse cycle',await page.locator('.cookie-layer a').evaluate(n=>n===document.activeElement),null);await page.keyboard.press('Tab');check(width+' Cookie forward cycle',await page.locator('[data-cookie-close]').evaluate(n=>n===document.activeElement),null);await page.keyboard.press('Escape');await settle();check(width+' Cookie Escape returns trigger',await page.locator('#cookie-trigger').evaluate(n=>n===document.activeElement),null);
 await page.locator('#cookie-trigger').click();await page.locator('.cookie-layer a').click();check(width+' Cookie policy href',(await page.evaluate(()=>window.__navigationIntents.at(-1).href))==='/cookie-policy/',null);await page.locator('[data-cookie-close]').click();await settle();check(width+' Cookie Close restores focus',await page.locator('#cookie-trigger').evaluate(n=>n===document.activeElement),null);
 await page.locator('main a').first().focus();await page.keyboard.press('Tab');check(width+' body focus visible',await page.evaluate(()=>getComputedStyle(document.activeElement).outlineColor)==='rgb(0, 128, 120)',null);
 await page.emulateMedia({reducedMotion:'reduce'});check(width+' reduced motion preference',await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),null);
 await ctx.close();save();
}
check('No HTTP/S attempts or script errors',network.length===0&&errors.length===0,{network,errors});
}catch(e){errors.push(e.stack);check('Execution complete',false,e.stack);process.exitCode=1}finally{save();await browser.close()}
console.log(JSON.stringify({report:target+'/runtime-checks.json',engine,assets:assets.length,failures:results.filter(r=>r.status==='FAIL')},null,2));if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();
