const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),prefix=out+'/DOC-COO_GATE3_',diag=__dirname+'/candidate-v0.1-r2',read=p=>JSON.parse(fs.readFileSync(p)),write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));
const id=p=>({path:p.replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const binding=read(prefix+'INPUT_BINDING_V0.1.json'),mode=process.argv[2],review='D:/23MySec/pages/documents/certificate-of-origin/05_review',evidence=review+'/DOC-COO_GATE3_EXECUTION_EVIDENCE_V0.1';
if(mode==='preflight'){
const runtime=read(diag+'/runtime-checks.json');if(runtime.failures.length||runtime.errors.length||runtime.network.length)throw Error('Unresolved runtime preflight');
const segments=fs.readdirSync(diag+'/segments').map(n=>({ ...id(diag+'/segments/'+n),previouslyViewedUnchanged:id(diag+'/segments/'+n).sha256===id(__dirname+'/candidate-v0.1/segments/'+n).sha256 }));
const visual={at:new Date().toISOString(),type:'STATIC_VISUAL',source:id(binding.candidate.path),status:'EXECUTOR_PRE_FLIGHT_VISUAL_COMPLETE',coverage:'Three full diagnostic PNGs opened for whole-page composition. All 23 overlapping native-size segment positions (6 desktop,7 tablet,10 mobile) reviewed. Six r2 segments byte-identical to already viewed first candidate; remaining affected segments reopened. Five shared state screenshots individually opened.',segments,findings:[{id:'DOC-COO-G3-01',location:'Official Source / 390 / inline external source link',severity:'MINOR',expected:'Sentence punctuation follows its source link in normal reading flow',actual:'Original inline-flex long link forced a leading period on the next line',impact:'Awkward source sentence reading',resolution:'Natural inline external links with vertical hit padding preserve original labels/punctuation and measured 44px targets; all affected layouts rechecked',acceptance:'No isolated punctuation; exact copy/href; 44px; no clipping or other geometry regression',status:'RESOLVED_BEFORE_FREEZE'}],openFindings:[]};write(__dirname+'/visual-preflight.json',visual);
const deps=[...Object.values(binding.inputs),...binding.sharedConsumer.files,...binding.sharedConsumer.owners,...binding.dependencies];for(const d of deps)if(id(d.path).sha256!==d.sha256)throw Error('Dependency changed '+d.path);
const preflight={status:'PASS_FOR_FORMAL_RENDER',executor:'Gate3 execution agent; not independent review',at:new Date().toISOString(),candidate:id(binding.candidate.path),approvedInputs:binding.inputs,dependencies:deps,sharedConsumer:binding.sharedConsumer,checks:{approvedInputsMatch:'PASS',durableDependencies:'PASS',sharedConsumerNeutral:'PASS',contentRelationshipsMatch:'PASS',threeViewportsVisible:'PASS',touchTargets44:'PASS',mobileMenuExit:'PASS',applicableStates:'PASS',pageSpecificRisks:'PASS',functionalColors:'PASS'},formalExportsGenerated:false,evidence:{runtime:id(diag+'/runtime-checks.json'),visual:id(__dirname+'/visual-preflight.json')},rendering:{...runtime.engine,deviceScaleFactor:1,logicalViewports:[{width:1440,height:900},{width:768,height:900},{width:390,height:844}],network:'local file only; zero HTTP/S attempts'},tableConversion:'1440 three columns; 768 named record and two labeled fields; 390 three labeled fields stacked. Repeated labels equal B table headers only.',notApplicable:'No page form, query-driven UI, FAQ, selector, download or conditional state under current approved B/C. Receiver prefill/Back/Forward behavior remains an owner dependency.',unmeasured:['Production receiver prefill/edit/remove/required fields and receipt','Native browser zoom; physical devices; screen-reader speech; other engines','Production URL, external freshness, actual cookie/storage, SEO and publication']};write(prefix+'PREFLIGHT_RECORD_V0.1.json',preflight);console.log(JSON.stringify({preflight:prefix+'PREFLIGHT_RECORD_V0.1.json',status:preflight.status}));
}
if(mode==='freeze'){
const p=prefix+'PREFLIGHT_RECORD_V0.1.json',pre=read(p);if(pre.status!=='PASS_FOR_FORMAL_RENDER'||pre.formalExportsGenerated!==false)throw Error('No preflight PASS');for(const d of [pre.candidate,...pre.dependencies])if(id(d.path).sha256!==d.sha256)throw Error('Frozen input mismatch '+d.path);if(fs.existsSync(out+'/approval_core'))throw Error('Formal directory exists before freeze');
const f={pageId:'DOC-COO',status:'FROZEN_FOR_FORMAL_RENDER',frozenAt:new Date().toISOString(),candidate:id(binding.candidate.path),approvedInputs:binding.inputs,sharedConsumer:binding.sharedConsumer,dependencies:binding.dependencies,preflight:id(p),inputBinding:id(prefix+'INPUT_BINDING_V0.1.json'),formalExportsExistedAtFreeze:false};write(prefix+'FREEZE_RECORD_V0.1.json',f);console.log(JSON.stringify(f.candidate));
}
if(mode==='handoff'){
const f=read(prefix+'FREEZE_RECORD_V0.1.json'),runtime=read(out+'/approval_core/runtime-checks.json'),diagnostic=read(diag+'/runtime-checks.json');if(runtime.failures.length||runtime.errors.length||runtime.network.length||runtime.source.sha256!==f.candidate.sha256)throw Error('Formal validation failed');
fs.mkdirSync(evidence,{recursive:true});fs.renameSync(out+'/approval_core/runtime-checks.json',evidence+'/formal-runtime-checks.json');
const assets=runtime.assets.map(a=>{const b=fs.readFileSync(a.path),d=diagnostic.assets.find(x=>x.logicalWidth===a.logicalWidth&&x.state===a.state);return {...id(a.path),state:a.state,logicalWidth:a.logicalWidth,pixelWidth:b.readUInt32BE(16),pixelHeight:b.readUInt32BE(20),deviceScaleFactor:1,sourceSha256:f.candidate.sha256,diagnosticByteIdentical:d.sha256===id(a.path).sha256,viewed:'Individually opened after formal export; matching diagnostics support complete native-size segment reading'}});if(assets.some(a=>!a.diagnosticByteIdentical))throw Error('Formal images differ from viewed diagnostics');
write(evidence+'/formal-visual-readback.json',{at:new Date().toISOString(),type:'STATIC_VISUAL',source:f.candidate,formalAssets:assets,coverage:'All 8 formal assets individually opened after export; 3 full pages and 5 states. Hash equality to viewed diagnostics establishes 23 overlapping native-size segment coverage through Footer. No unresolved visual finding.',openFindings:[]});
const fulls=assets.filter(a=>a.state==='full').map(a=>a.pixelWidth+'×'+a.pixelHeight).join(', ');
const report=`# DOC-COO Gate 3 design method report V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Date: 2026-09-07. Executor: Gate3 execution agent, G3-8PAGE-SERIAL-01 item 2 only. Method execution and self-review do not constitute independent approval.

Applied responsive-wireframe-design V0.2 and its preflight/freeze/evidence reference. Agent V0.2, verification Skill V0.2, method baseline V1.2 and serial control V1.1 were explicitly read. Task input card and INPUT_BINDING give exact A V0.1/B V0.2/C V0.1, Brief V0.3, approvals, receiver and shared sources. B excludes only its control comment. No other business page was read/copied as a template; neutral renderSharedChrome V0.2 generated the shared assembly with currentPageId=DOC-000.

| Module | Structural choice and preserved relationship |
|---|---|
| coo-01 Hero | Approved eyebrow, full long H1 and direct answer before any action; known/unknown Grade explanation and Products link precede primary Origin request. |
| coo-02 Evidence comparison | 1440 has the original three-column table. 768 presents each evidence name above two parallel fields. 390 stacks every field. Each field label repeats its exact approved table header; there are no invented summaries or dropped qualifiers. The certificate/customs limitation and official link follow all three rows. |
| coo-03 Request context | Four ordered details in a two-column desktop/tablet grid and one mobile column; exact Additional Requirements routing and Country / Region company-location explanation remain after the list. |
| coo-04 Origin/traceability | Full two-paragraph distinction stays separate from evidence comparison and does not imply a company traceability capability. |
| coo-05 Preparation | Five preparation bullets, incomplete-context help, single-Grade/multi-document disclosure, primary Origin request and exact submission boundary, then lower-weight Document Hub. |
| coo-06 Source | Exact official attribution, two source dates, 7 September 2026 reviewed date and general-guidance limitation. No new regulatory finding or issuing claim. |

The reading measure is bounded independently of the comparison width. No imagery, certificate facsimile, seal, inventory, download, form, FAQ, selector or availability badge is introduced. Six module headings and all 8 B links remain exact. The comparison row/cell data are checked separately from the full-content comparison so mobile header repetition cannot hide a relationship error.

Current brand/CTA/Chrome/legal owners remain authoritative. Functional main links, focus and actions use #008078, primary white on #008078; original primary/reverse production SVGs are referenced. Shared style/behavior are embedded unchanged from the neutral renderer, with identical durable Inter/font-license copies. The source has no temporary or other-page dependency.

Inheritance: serial V1.1 supplies current Gate3 authority despite historical NOT_AUTHORIZED strings in V0.6/A/Brief. Final approved B/C supersede candidate architecture and copy in A/Brief. Site-wide Malaysia-origin authority supersedes the historical blanket hold, but B does not use that claim and DOC-COO does not gain the excluded COO-availability proposition. Document Playbook V0.3 is an unapproved Hub-specific design and is not used to import Finder/Results, destination fields or its module order. Current C/CONV-DOC control prefill and company location. Root complete-site rule supersedes earlier route-unavailable omission designs: no conditional readiness control or query UI exists on this approved page, so no fake unavailable/held state is made.

Both Origin actions record LOCAL_SIMULATION semantics: prefill.document_types=[origin_supplier_qualification] and source_context.page_id=DOC-COO, with no Grade, destination, scheme or transaction prefill and no invented query. These records are not receiver API implementation. Their visible/editable/removable reception, required Grade validation and Back/Forward/revisit behavior remain CONV-DOC responsibilities. All 8 main links were actually clicked locally, including the two exact RMCD hrefs; no HTTP/S request occurred.

Hard preflight preceded freeze and check-preflight-record.mjs returned PASS_FOR_FORMAL_RENDER. Formal rendering followed the saved freeze. Chrome ${runtime.engine.browser}, Playwright ${runtime.engine.playwright}, Node ${runtime.engine.node}, DPR1; viewports1440×900,768×900,390×844. Formal full pages: ${fulls}; menu768×900/390×844; Cookie1440×900/768×900/390×844. All8 formal PNGs were opened individually. Twenty-three overlapping native-size segments cover through Footer; formal/diagnostic PNG bytes match.

One visual finding DOC-COO-G3-01 was resolved before freeze: long inline-flex source link forced leading punctuation onto a new line at390. Natural inline wrapping with target padding retains original text and44px measurements. First source and screenshots are preserved; all affected segments and three-width runtime were rechecked. No runtime preflight failure was encountered; no current open execution Finding.

Frozen source: ${f.candidate.path}; ${f.candidate.bytes} bytes; SHA-256 ${f.candidate.sha256}; frozen ${f.frozenAt}. INPUT_BINDING, PREFLIGHT_RECORD, FREEZE_RECORD and ASSET_INVENTORY bind exact identities. Formal approval_core contains only current assets; detailed runs, segments and the first candidate are diagnostic_support.

Four risk results: hardest reading is the evidence comparison, with all three object/field relationships retained and labels visible after conversion; hardest operation is shared-overlay exit and contextual request semantics, verified locally while receiver behavior remains untested; highest responsive risk is table-to-record conversion and all source text/punctuation, verified in all three layouts; remaining limits are native browser zoom, physical devices, screen-reader table narration, non-Chrome engines, actual receiver/routes/cookie technology, current external-source re-research and production SEO/publication. These are not represented as successes. No Gate4, other page or development work occurred.
`;
fs.writeFileSync(prefix+'DESIGN_METHOD_REPORT_V0.1.md',report);
const self=`# DOC-COO Gate 3 execution self-check V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Date: 2026-09-07. Role: Gate3 execution. No independent project-control PASS, user approval or Gate closure is granted here.

Applied layout-interaction-verification V0.2 and references/core-risk-model.md. The separate responsive-wireframe-design V0.2 method report, original B/C and current inputs were read with actual source, runtime output and images. Fixed core coverage plus DOC-COO-specific relationships determine this result; assertion counts are not a quality measure.

| Core | Evidence and executor conclusion |
|---|---|
| Identity | SOURCE_INSPECTION: approved input/package hashes rechecked before freeze; source ${f.candidate.bytes} bytes / ${f.candidate.sha256}. Freeze saved before first formal export. Eight PNGs bind that source and match current viewed diagnostics byte-for-byte. |
| Content | ACTUAL_RUNTIME + STATIC_VISUAL: exact full B, six headings/modules, eight ordered label/href pairs, three comparison records and all9 fields, four context details, five preparation bullets and the source dates. Only approved table headers repeat on narrow views. No forbidden availability/company/customs claim, field or download is added. |
| Geometry | ACTUAL_RUNTIME + STATIC_VISUAL: full1440/768/390 to Footer, no horizontal overflow or hidden body, no clipping/collision/abnormal fixed blank found. Default, Menu and Cookie controls at least44×44. Long external labels wrap naturally. |
| Shared consumer | SOURCE_INSPECTION + ACTUAL_RUNTIME: neutralV0.2 / Documents active / original SVGs / fixedRFQ / exact Footer/legal/no_optional_analytics text. Durable font/license, owner-bound embedded CSS/behavior; no business-page template or temporary render dependency. |
| Menu | ACTUAL_RUNTIME at768/390: Home firstfocus, Tab/Shift+Tab cycle, Escape/Close and all8 selections close, background inert/wheel lock and recovery, cross1440 breakpoint closure. |
| Cookie/focus | ACTUAL_RUNTIME allthree widths: Close firstfocus, both Tab cycle directions, Escape/Close return to Footer trigger, exact local policy href, geometry and functional color. Body keyboard focus is visible; reduced-motion preference checked. |
| Navigation | LOCAL_SIMULATION: every B link clicked, both Origin actions record exact C prefill/source attribution, ordinary links no context. No query invented and no destination request executed. |
| Visual completeness | STATIC_VISUAL: 8 formal assets individually opened after freeze; full files plus23 readable overlapping segments through Footer. Current and diagnostic export hashes agree. |

| DOC-COO risk | Actual result / limit |
|---|---|
| Preferential/non-preferential/other proof | Exact three objects, relevance and verification text remain paired; no universal certificate suggestion. Table headers repeat as field labels at768/390 and source limitation remains below the comparison. Screen-reader table narration not tested. |
| Origin versus traceability | Distinction precedes preparation; neither creates IKHLAS batch/order capability. No certificate image, seal or download affordance implies issuance. |
| Request context and incomplete Grade | Hero and preparation retain start-without-preselection versus select-before-submit distinction. One Grade/multiple documents remains visible. Destination/scheme/references route to Additional Requirements; company Country / Region stays distinct. Actual receiver editing/removal/validation/history is untested. |
| Official attribution and action hierarchy | Two exact RMCD links with general-definition scope, information date10October2025, update5January2026 and reviewed7September2026 are retained. Origin request primary, Products/Hub secondary; submission is review only, never issuance/customs success. |

Hard preflight and schema checker passed before freeze; frozen formal runtime has no failed check, pageerror or HTTP/S attempt. DOC-COO-G3-01 (leading punctuation after long source link at390) was fixed before freeze and rechecked across affected three-width text flow; original source and diagnostic images remain preserved. No current unresolved execution Finding.

Not applicable: local forms/FAQ/selectors/downloads/query or readiness states are absent from approved B/C; historical examples do not justify adding them. No artificial page state is exported. Production readiness and receiver histories remain handoff dependencies under the current root complete-site rule.

Not tested: production URL/canonical/indexing and receiver release; actual document-type prefill visibility/editability/removal, Grade validation, Back/Forward/direct receiver revisit, submission/receipt; physical-device touch, native browser200%zoom, assistive speech and Firefox/Safari; actual analytics/cookie/storage technologies; new external-source freshness or destination-specific legal conclusions. Exact approved source dates are preserved, not newly researched. No Gate4/development/other page work occurred.

Formal files: ${out}/approval_core. Source/report/input/preflight/freeze/inventory: ${out}. Formal runtime and visual readback: ${evidence}. Earlier candidate, images,23segment positions and helpers: ${out}/diagnostic_support. Reports, source identities and final inventory are read back before handoff.
`;fs.writeFileSync(review+'/DOC-COO_GATE3_EXECUTION_SELF_CHECK_V0.1.md',self);
const inventory={pageId:'DOC-COO',status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',at:new Date().toISOString(),approval_core:{source:f.candidate,assets,records:['INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD'].map(n=>id(prefix+n+'_V0.1.json')).concat(['TASK_INPUT_CARD','DESIGN_METHOD_REPORT'].map(n=>id(prefix+n+'_V0.1.md'))),selfCheck:id(review+'/DOC-COO_GATE3_EXECUTION_SELF_CHECK_V0.1.md'),dependencies:binding.dependencies,sharedConsumer:binding.sharedConsumer},diagnostic_support:{path:__dirname.replaceAll('\\','/'),formalRuntime:id(evidence+'/formal-runtime-checks.json'),formalVisual:id(evidence+'/formal-visual-readback.json'),resolved:['DOC-COO-G3-01'],openFindings:[]},scope:'Gate3 execution complete; independent project control review pending; no Gate4 authority'};write(prefix+'ASSET_INVENTORY_V0.1.json',inventory);
console.log(JSON.stringify({source:f.candidate,assets:assets.map(a=>({path:a.path,width:a.pixelWidth,height:a.pixelHeight,bytes:a.bytes,sha256:a.sha256})),report:prefix+'DESIGN_METHOD_REPORT_V0.1.md',selfCheck:review+'/DOC-COO_GATE3_EXECUTION_SELF_CHECK_V0.1.md',inventory:prefix+'ASSET_INVENTORY_V0.1.json'},null,2));
}
