const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),root='D:/23MySec',mode=process.argv[2]||'preflight';
const target=out+'/MARKET-EU-ES_GATE4_VISUAL_SAMPLES_V0.1.html',g3=root+'/pages/markets/spain/04_planning/gate3-v0.1/MARKET-EU-ES_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const evidence=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/preflight';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});
const records=[],assets=[],errors=[],norm=s=>s.replace(/\s+/g,' ').trim();
function check(name,pass,data,type='ACTUAL_RUNTIME'){records.push({name,pass:!!pass,evidenceType:type,data});if(!pass)errors.push(name);}
const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);
const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{let x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function metrics(loc){return loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();function surface(node){while(node){let v=getComputedStyle(node).backgroundColor;if(v!=='rgba(0, 0, 0, 0)'&&v!=='transparent')return v;node=node.parentElement;}return'rgb(255, 255, 255)';}return{text:e.innerText,href:e.getAttribute('href'),fg:s.color,bg:surface(e),outline:s.outlineColor,outlineStyle:s.outlineStyle,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:surface(parseFloat(s.outlineOffset)>=0?e.parentElement:e),border:s.borderTopColor,borderWidth:parseFloat(s.borderTopWidth),font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,width:r.width,height:r.height,x:r.x,y:r.y,focus:e.matches(':focus-visible'),hover:e.matches(':hover'),textDecoration:s.textDecorationLine,background:s.backgroundColor};});}
async function keyboardFocus(page,loc){await page.mouse.move(0,0);await loc.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return loc.evaluate(e=>e===document.activeElement&&e.matches(':focus-visible'));}
async function controls(page,selector,label,w){let list=page.locator(selector);for(let i=0;i<await list.count();i++){let loc=list.nth(i);if(!await loc.isVisible())continue;await loc.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.evaluate(()=>document.activeElement.blur());let normal=await metrics(loc);let normalRatio=normal.text.trim()?contrast(normal.fg,normal.bg):null;check(`${w}/${label}/${i}/normal`,normal.width>=44&&normal.height>=44&&(!normalRatio||normalRatio>=4.5),{...normal,textContrast:normalRatio});await loc.hover();let hover=await metrics(loc);let hoverRatio=hover.text.trim()?contrast(hover.fg,hover.bg):null;check(`${w}/${label}/${i}/hover`,hover.hover&&hover.width===normal.width&&hover.height===normal.height&&(!hoverRatio||hoverRatio>=4.5),{...hover,textContrast:hoverRatio});let reached=await keyboardFocus(page,loc),focus=await metrics(loc);let focusRatio=contrast(focus.outline,focus.outlineBg);check(`${w}/${label}/${i}/keyboard`,reached&&focus.outlineWidth>=3&&focusRatio>=3,{...focus,outlineContrast:focusRatio});}}
async function shot(page,w,name,{selector,fromTop=false,state='normal',focusSelector,hoverSelector}={}){
 let dest=evidence+'/'+w+'-'+name+'.png';if(fs.existsSync(dest))throw Error('Refuse overwrite '+dest);
 if(focusSelector)await keyboardFocus(page,page.locator(focusSelector));
 if(hoverSelector)await page.locator(hoverSelector).hover();
 let capture,clip;
 if(selector&&!focusSelector&&!hoverSelector){await page.evaluate(()=>window.scrollTo(0,0));let r=await page.locator(selector).boundingBox();let top=fromTop?0:Math.max(0,Math.floor(r.y)-8);let bottom=Math.ceil(r.y+r.height)+8;let docHeight=await page.evaluate(()=>document.documentElement.scrollHeight);clip={x:0,y:top,width:w,height:Math.min(docHeight,bottom)-top};capture=await page.screenshot({path:dest,fullPage:true,clip});}
 else capture=await page.screenshot({path:dest});
 let actual=hoverSelector?await metrics(page.locator(hoverSelector)):focusSelector?await metrics(page.locator(focusSelector)):null;
 if(hoverSelector)check(`${w}/${name}/capture-hover`,actual.hover,actual);
 if(focusSelector)check(`${w}/${name}/capture-focus`,actual.focus,actual);
 assets.push({...id(dest),pixelWidth:capture.readUInt32BE(16),pixelHeight:capture.readUInt32BE(20),logicalViewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,state,region:selector||'actual viewport',clip:clip||null,sourceSha256:sha(target),sourceFreeze:mode==='formal'?'ES-G4-V01-SOURCE-01':'PREFLIGHT_NOT_FROZEN'});
}
(async()=>{fs.mkdirSync(evidence,{recursive:true});let browser=await chromium.launch({channel:'chrome',headless:true});let version=browser.version();
try{
 if(mode==='formal'){const freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json'));for(const item of [...freeze.dependencies,...freeze.inputs])check('freeze '+item.path,sha(item.path)===item.sha256&&fs.statSync(item.path).size===item.bytes,item,'SOURCE_INSPECTION');}
 const original=fs.readFileSync(g3,'utf8'),candidate=fs.readFileSync(target,'utf8');
 check('G3 main/script/inline style identity',candidate.match(/<main>[\s\S]*?<\/main>/)[0]===original.match(/<main>[\s\S]*?<\/main>/)[0]&&JSON.stringify(candidate.match(/<script>[\s\S]*?<\/script>/g))===JSON.stringify(original.match(/<script>[\s\S]*?<\/script>/g))&&JSON.stringify(candidate.match(/<style>[\s\S]*?<\/style>/g))===JSON.stringify(original.match(/<style>[\s\S]*?<\/style>/g)),{g3:sha(g3),candidate:sha(target)},'SOURCE_INSPECTION');
 const neutral=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:'dependencies/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'dependencies/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'dependencies/Inter-Variable.ttf'});
 check('Consumer V0.2 exact embedded assembly',['header','footer','dialog','style','behavior'].every(k=>candidate.includes(neutral[k])),{package:'TIO2MY-GATE3-SHARED-CONSUMER-002',slots:['header','footer','dialog','style','behavior']},'SOURCE_INSPECTION');
 const B=fs.readFileSync(root+'/pages/markets/spain/04_planning/MARKET-EU-ES_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').split('<!-- BUYER_COPY_START -->')[1].split('<!-- BUYER_COPY_END -->')[0];
 const expected=norm(B.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#+\s*/gm,'').replace(/^-\s*/gm,''));
 for(const w of [1440,768,390]){let context=await browser.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage(),external=[];page.on('pageerror',e=>errors.push(e.message));await context.route(/^https?:/,r=>{external.push(r.request().url());return r.abort()});await page.goto(pathToFileURL(target).href);await page.evaluate(()=>document.fonts.ready);
 check(`${w}/exact approved B`,norm(await page.locator('main').innerText())===expected,{expected,rendered:norm(await page.locator('main').innerText())});
 check(`${w}/four modules`,JSON.stringify(await page.locator('main section').evaluateAll(es=>es.map(e=>e.id)))===JSON.stringify(['es-01','es-02','es-03','es-04']),{});
 let layouts=await page.evaluate(()=>{let groups=[...document.querySelectorAll('.applicationGroup')].map(e=>{let r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,text:e.innerText}});let clips=[...document.querySelectorAll('main *')].filter(e=>{let s=getComputedStyle(e);return ['hidden','clip'].includes(s.overflowY)||s.textOverflow==='ellipsis'||s.webkitLineClamp!=='none'&&s.webkitLineClamp!=='0'}).map(e=>e.outerHTML.slice(0,100));return{groups,clips,scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth,mainWidth:document.querySelector('main').getBoundingClientRect().width,bullets:document.querySelectorAll('#es-04 li').length,coo:document.querySelectorAll('.originStatement').length};});
 check(`${w}/geometry and peers`,layouts.scrollWidth===w&&!layouts.clips.length&&layouts.bullets===4&&layouts.coo===1&&(w===390?layouts.groups[1].y>layouts.groups[0].y&&layouts.groups[0].x===layouts.groups[1].x:layouts.groups[0].y===layouts.groups[1].y&&layouts.groups[0].width===layouts.groups[1].width),layouts);
 const cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');let doc=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'main h1'});let fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(`${w}/actual font`,fonts.fonts.some(x=>x.familyName==='Inter'&&x.isCustomFont),fonts);check(`${w}/logos loaded`,await page.locator('img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)),{});
 await controls(page,'header .headerInner a,header .headerInner button,main a,footer a,footer button','normal-page',w);
 let links=page.locator('main a');for(let i=0;i<await links.count();i++){let loc=links.nth(i),href=await loc.getAttribute('href');await loc.click();let intent=await page.evaluate(()=>window.__navigationIntents.at(-1));check(`${w}/local intent/${i}`,intent.href===href&&(href!=='/request-a-quote/'||intent.context.destination_country==='Spain'&&intent.context.destination_editable===true)&&(href!=='/request-documents/'||Object.keys(intent.context).join()==='source_page_id'),intent,'LOCAL_SIMULATION');}
 if(w<1101){await page.evaluate(()=>window.scrollTo(0,0));await page.locator('.menuButton').click();check(`${w}/menu entry`,await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement),{});check(`${w}/menu isolation`,await page.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'),{});await controls(page,'.menuButton,.mobileNav a','open-menu',w);await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let cycle=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');check(`${w}/menu cycle`,cycle&&await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});if(mode==='formal'){await page.evaluate(()=>window.scrollTo(0,0));await shot(page,w,'menu-focus',{focusSelector:'.mobileNav a[aria-current]',state:'menu open; keyboard focus Markets'});}await page.keyboard.press('Escape');check(`${w}/menu escape return`,await page.locator('.menuButton').evaluate(e=>e===document.activeElement&&e.textContent==='Menu')&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();check(`${w}/menu selection closes`,await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});let breakpoint=await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,backgroundRestored:!document.querySelector('main').inert,focus:document.activeElement.tagName}));check(`${w}/menu desktop breakpoint`,breakpoint.closed&&breakpoint.backgroundRestored,breakpoint);await page.setViewportSize({width:w,height:w===390?844:900});}
 await page.locator('#cookie-trigger').click();check(`${w}/cookie entry`,await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(page,'.cookie-actions > *','cookie',w);await page.locator('[data-cookie-close]').focus();await page.keyboard.press('Shift+Tab');let cycle=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');check(`${w}/cookie cycle`,cycle&&await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await page.locator('main .primary').first().evaluate(e=>e.focus());check(`${w}/cookie native background isolation`,await page.locator('.cookie-layer').evaluate(e=>e.contains(document.activeElement)),{});if(mode==='formal')await shot(page,w,'cookie-focus',{focusSelector:'[data-cookie-close]',state:'Cookie Settings open; actual keyboard focus Close'});await page.keyboard.press('Escape');check(`${w}/cookie escape return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();check(`${w}/cookie Close return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});
 await page.evaluate(()=>document.activeElement.blur());await page.mouse.move(0,0);
 const normalRegions=[['hero','#es-01',true],['applications','#es-02'],['documents','#es-03'],['rfq','#es-04'],['footer','footer']];
 for(const [name,selector,fromTop]of normalRegions){if(mode==='formal'||w===1440&&name==='hero'||w===768&&name==='applications'||w===390&&['documents','rfq'].includes(name))await shot(page,w,name,{selector,fromTop});}
 if(mode==='formal'){
 await page.locator('#es-03').scrollIntoViewIfNeeded();await shot(page,w,'document-hub-hover',{hoverSelector:'#es-03 a[href="/documents/"]',state:'actual supporting hover on #F5F8FB'});
 if(w===1440){await page.evaluate(()=>window.scrollTo(0,0));await shot(page,w,'primary-hover',{hoverSelector:'#es-01 .primary',state:'actual primary hover; white on #008078; underline'});}
 if(w===768){await page.locator('#es-02').scrollIntoViewIfNeeded();await shot(page,w,'application-focus',{focusSelector:'#es-02 a[href="/applications/titanium-dioxide-for-masterbatch/"]',state:'actual keyboard focus; Masterbatch path'});}
 if(w===390){await page.locator('#es-04 .related').scrollIntoViewIfNeeded();await shot(page,w,'related-hover',{hoverSelector:'#es-04 .related a:last-child',state:'actual EU Trade Update hover'});await page.locator('#es-03').scrollIntoViewIfNeeded();await shot(page,w,'document-hub-focus',{focusSelector:'#es-03 a[href="/documents/"]',state:'actual supporting keyboard focus'});await page.locator('#cookie-trigger').scrollIntoViewIfNeeded();await shot(page,w,'footer-focus',{focusSelector:'#cookie-trigger',state:'actual Footer keyboard focus; white ring on Deep Navy'});}
 }
 check(`${w}/no external requests`,external.length===0,{external});await context.close();
 }
}catch(e){errors.push(e.stack);}
await browser.close();const result={date:new Date().toISOString(),mode,source:id(target),runtime:{node:process.version,playwright:require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json').version,chrome:version,headless:true,scale:1,externalRequestsAllowed:false},records,errors,assets,scope:'Local representative Gate4 visual regions and actual local interactions; no production receiver or Gate5 approval'};fs.writeFileSync(out+'/diagnostic_support/'+mode+'-runtime-checks.json',JSON.stringify(result,null,2));if(mode==='formal')fs.writeFileSync(out+'/approval_core/export-inventory.json',JSON.stringify({freezeId:'ES-G4-V01-SOURCE-01',date:new Date().toISOString(),assets},null,2));console.log(JSON.stringify({mode,records:records.length,errors,assets:assets.map(a=>({file:a.relativePath,width:a.pixelWidth,height:a.pixelHeight}))}));if(errors.length)process.exitCode=1;
})();
