const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/markets/brazil/04_planning/gate3-en-v0.1',id='MARKET-BR-EN',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',formal=process.argv.includes('--formal'),dest=out+(formal?'/approval_core':'/diagnostic_support/render');fs.mkdirSync(dest,{recursive:true});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim(),log=[],assets=[];const test=(name,value,data)=>{log.push({name,status:value?'PASS':'FAIL',data});if(!value)throw Error(name)};
const b=fs.readFileSync(out+'/../'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'').trim(),plain=norm(b.replace(/^#{1,3} /gm,'').replace(/^- /gm,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1')),links=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:m[1],href:m[2]}));
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
const save=async(p,w,h,state)=>{const file=dest+'/'+(formal?`${id}_GATE3_${w}_${state.toUpperCase()}_V0.1.png`:`diagnostic-${w}-${state}.png`);await p.screenshot({path:file,fullPage:state==='full'});const buf=fs.readFileSync(file);assets.push({path:file,bytes:buf.length,sha256:hash(file),logicalViewport:{width:w,height:h},physicalPixels:{width:buf.readUInt32BE(16),height:buf.readUInt32BE(20)},dpr:1,state,role:formal?'approval_core':'diagnostic_support'});};
(async()=>{if(formal){const f=JSON.parse(fs.readFileSync(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json'));test('frozen source hash',hash(source)===f.source.sha256);}
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']}),external=[];
try{for(const w of [1440,768,390]){const h=w===390?844:900,context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await context.route(/^https?:/,r=>{external.push(r.request().url());r.abort()});const p=await context.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
test(w+' exact visible B',norm(await p.locator('main').innerText())===plain);test(w+' labels href order',JSON.stringify(await p.locator('main a').evaluateAll(a=>a.map(e=>({text:e.textContent,href:e.getAttribute('href')}))))===JSON.stringify(links));
const geometry=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('a,button')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent.trim(),width:r.width,height:r.height}}),clipped:[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return ['hidden','clip'].includes(s.overflow)||s.textOverflow==='ellipsis'}).length}));test(w+' geometry and 44px',geometry.scrollWidth<=w&&geometry.clipped===0&&geometry.targets.every(t=>t.width>=43.99&&t.height>=43.99),geometry);
const relationships=await p.evaluate(()=>({modules:[...document.querySelectorAll('main section')].map(e=>e.dataset.module),applications:[...document.querySelectorAll('.applications article')].map(e=>({heading:e.querySelector('h3').textContent,paragraphs:e.querySelectorAll('p').length,href:e.querySelector('a').getAttribute('href')})),coo:[...document.querySelectorAll('main p')].filter(e=>e.textContent==='A Certificate of Origin is available upon request.').length,trade:document.querySelector('.m4').innerText,tradeLinks:[...document.querySelectorAll('.m4 a')].map(a=>a.getAttribute('href')),rfqItems:document.querySelectorAll('.m5 li').length,forms:document.querySelectorAll('main form,main input,main select,main button,main details,main table').length}));
test(w+' Brazil page relationships',relationships.modules.join()==='BR-EN-01,BR-EN-02,BR-EN-03,BR-EN-04,BR-EN-05'&&relationships.applications.length===3&&relationships.applications.every((a,i)=>a.paragraphs===1&&a.href===['/applications/titanium-dioxide-for-coatings/','/applications/titanium-dioxide-for-plastics/','/applications/titanium-dioxide-for-masterbatch/'][i])&&relationships.coo===1&&relationships.trade.includes('6 September 2026')&&relationships.tradeLinks.join()==='/resources/brazil-titanium-dioxide-anti-dumping-duty/'&&relationships.rfqItems===5&&relationships.forms===0,relationships);
test(w+' current navigation and teal',await p.evaluate(()=>[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].every(e=>e.textContent==='Markets')&&getComputedStyle(document.querySelector('main a')).color==='rgb(0, 128, 120)'&&getComputedStyle(document.querySelector('main .primary')).backgroundColor==='rgb(0, 128, 120)')); 
await save(p,w,h,'full');if(!formal)for(let y=0,n=1;y<geometry.height;y+=750,n++)await p.screenshot({path:dest+`/clip-${w}-${String(n).padStart(2,'0')}.png`,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,geometry.height-y)}});
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();const actual=await p.evaluate(()=>window.localNavigation.at(-1)),href=links[i].href;test(w+' main local link '+i,actual.href===href&&!href.includes('?')&&(href!=='/request-a-quote/'||(actual.context.destination_country==='Brazil'&&actual.context.destination_context_visible_editable===true&&Object.keys(actual.context).length===3))&&(href!=='/request-documents/'||Object.keys(actual.context).join()==='source_page_id')&&(!href.startsWith('/applications/')||Object.keys(actual.context).length===0),actual);}
await p.evaluate(()=>scrollTo(0,0));if(w<1101){const toggle=p.locator('.menuButton');await toggle.click();test(w+' menu first focus',await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));await save(p,w,h,'menu');test(w+' menu inert lock',await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert)&&document.body.style.overflow==='hidden'));
await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');test(w+' menu Tab loop',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');test(w+' menu reverse loop',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.mouse.move(w-5,h-10);await p.mouse.wheel(0,300);await p.waitForTimeout(100);test(w+' wheel lock',await p.evaluate(()=>scrollY===0));await p.keyboard.press('Escape');test(w+' Escape restore',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''&&document.activeElement===document.querySelector('.menuButton')));await p.mouse.wheel(0,300);await p.waitForTimeout(100);test(w+' wheel restore',await p.evaluate(()=>scrollY>0));await p.evaluate(()=>scrollTo(0,0));await toggle.click();await toggle.click();test(w+' Close',await p.locator('.mobileNav').evaluate(e=>e.hidden));
for(let i=0;i<8;i++){await toggle.click();await p.locator('.mobileNav a').nth(i).click();test(w+' menu selection '+i,await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert)&&document.body.style.overflow===''));}
await toggle.click();await p.setViewportSize({width:1440,height:h});await ready(p);test(w+' desktop breakpoint',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width:w,height:h});await ready(p);}
await p.locator('#cookie-trigger').click();await ready(p);test(w+' Cookie focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await save(p,w,h,'cookie');test(w+' Cookie colors/44px',await p.locator('.cookie-actions>*').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>=44&&r.height>=44&&s.color==='rgb(0, 128, 120)'&&s.borderTopColor==='rgb(0, 128, 120)'})));
await p.keyboard.press('Shift+Tab');test(w+' Cookie reverse',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');test(w+' Cookie forward',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('.cookie-layer a').click();test(w+' Cookie policy',(await p.evaluate(()=>window.localNavigation.at(-1))).href==='/cookie-policy/');await p.locator('[data-cookie-close]').click();await ready(p);test(w+' Cookie Close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');await ready(p);test(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await context.close();}
test('No external request',external.length===0,external);fs.writeFileSync(dest+'/runtime.json',JSON.stringify({status:'PASS',generatedAt:new Date().toISOString(),source:{path:source,bytes:fs.statSync(source).size,sha256:hash(source)},browser:browser.version(),log,assets},null,2));console.log(JSON.stringify({status:'PASS',assets:assets.length,source:hash(source)}));
}catch(e){fs.writeFileSync(dest+'/failure-'+Date.now()+'.json',JSON.stringify({status:'FAIL',error:e.stack,log},null,2));throw e}finally{await browser.close()}})();
