const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',base=root+'/pages/markets/brazil',out=base+'/04_planning/gate3-en-v0.1',id='MARKET-BR-EN',neutral=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const identity=path=>({path,bytes:fs.statSync(path).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex')}),write=(p,x)=>fs.writeFileSync(p,typeof x==='string'?x:JSON.stringify(x,null,2));
fs.mkdirSync(out+'/dependencies',{recursive:true});fs.mkdirSync(out+'/approval_core',{recursive:true});
const inputs={manifest:base+'/'+id+'_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md',A:base+'/04_planning/'+id+'_GATE2_CONTENT_SKELETON_V0.1.md',B:base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md',C:base+'/04_planning/'+id+'_GATE2_CONTENT_CONTRACT_V0.1.md',review:base+'/05_review/'+id+'_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md',brief:root+'/docs/page-briefs/MARKET-BR-EN_BRAZIL_ENGLISH_BRIEF_V0.2.md',claims:base+'/01_research/'+id+'_GATE1_CLAIM_EVIDENCE_REGISTER_V0.2.csv',authorization:root+'/docs/architecture/GATE3_EIGHT_PAGE_SERIAL_CONTROL_V1.5.md',approval:root+'/docs/architecture/GATE2_EIGHT_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md',baseline:root+'/docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md',agent:root+'/agents/gate3-execution/agent.md',designSkill:root+'/skills/responsive-wireframe-design/SKILL.md',verificationSkill:root+'/skills/layout-interaction-verification/SKILL.md',handoff:root+'/docs/superpowers/specs/2026-09-07-gate3-to-gate4-handoff-contract-v0.1.md'};
const approvedInputs=Object.fromEntries(Object.entries(inputs).map(([k,p])=>[k,identity(p)]));
for(const [k,hash] of Object.entries({A:'4581c354515c3175b8820c02db67385f525e7671a846ff303afe136ad3177b63',B:'28f505fbd2cb5e77ea8be0b6a12b03a94c68d057e97b7db431aaa1635765a216',C:'e686bd11bbe5c8ecdd2a2fa5deaa05a2987f018cc8dbbb8e2cf022542a299d5b',review:'d77c6154fe9e252cb3b6f7cfeade1d2b87e9361b54f918c3f2319715e8af6373'}))if(approvedInputs[k].sha256!==hash)throw Error('Approved identity '+k);
const pkg=JSON.parse(fs.readFileSync(neutral+'/consumer-package.json'));const sharedFiles=pkg.files.map(f=>({...identity(neutral+'/'+f.path),role:f.role}));pkg.files.forEach((f,i)=>{if(f.sha256!==sharedFiles[i].sha256)throw Error('Shared '+f.path)});
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';
for(const name of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(neutral+'/'+name,out+'/dependencies/'+name);
const shared=require(neutral+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
write(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',{status:'DIAGNOSTIC_CANDIDATE_NOT_FROZEN',createdAt:new Date().toISOString(),approvedInputs,sharedConsumer:{...identity(neutral+'/consumer-package.json'),version:pkg.version,packageId:pkg.packageId,currentPageId:'MARKET-000'},sharedFiles,owners:Object.fromEntries(Object.entries(pkg.authority).map(([k,p])=>[k,identity(p)])),dependencies:[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(identity)});
write(out+'/'+id+'_GATE3_TASK_INPUT_CARD_V0.1.md',`# Brazil English Gate 3 input card\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. MARKET-BR-EN, EN, /markets/brazil/, Market procurement landing page. Serial batch G3-8PAGE-SERIAL-01 V1.5 item6 only; stop for independent control review, no PT/Sulfate/Gate4. Current Manifest V0.4 + A V0.1 / B V0.2 / C V0.1 / Brief V0.2; exact identities in input binding JSON. Current serial authority supplements older Manifest Gate3-not-authorized row; approved B V0.2 supersedes C historical B V0.1 link without changing C meaning.\n\nModule map: BR-EN-01 Hero → BR-EN-02 Product/Application review → BR-EN-03 Documents → BR-EN-04 dated Trade Resource handoff → BR-EN-05 Brazil RFQ preparation. All visible main copy comes from B. Risks: application/paragraph/link triplets; unknown and supplementary Grades; exact COO once; date 6 September2026 belongs Resource, no imported legal outcome; RFQ Grade/Application unknown choices and MT/destination checklist.\n\nShared neutral V0.2: MARKET-000, approved original production SVGs, current legal no_optional_analytics. Three full pages1440/768/390, Menu768/390, Cookieall3 atDPR1. No page form, FAQ, selector, anchor or success/error state.\n\nOutput/report: ${out}/${id}_GATE3_DESIGN_METHOD_REPORT_V0.1.md. Self-check: ${base}/05_review/${id}_GATE3_EXECUTION_SELF_CHECK_V0.1.md. Writes only this English planning directory and English review/evidence. RFQ records source/Brazil destination intention only; visibility/editability remains receiver obligation; DOC source attribution only; no constructed query or actual navigation.\n`);
write(out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md','# Brazil English design method report\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. Input card established; fresh neutral candidate under construction. No preflight or formal export claimed.\n');
const blocks=fs.readFileSync(inputs.B,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim().split(/\r?\n\s*\r?\n/).map(s=>s.trim());
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');
let html='<nav class="breadcrumb" aria-label="Breadcrumb">'+inline(blocks.shift())+'</nav>',section=0;
for(let i=0;i<blocks.length;i++){let s=blocks[i];if(/^#{1,2} /.test(s)){if(section)html+='</section>';section++;let h=s.startsWith('# ')?1:2;html+=`<section class="module m${section}" data-module="BR-EN-0${section}"><h${h}>${inline(s.replace(/^#+ /,''))}</h${h}>`;}
else if(s.startsWith('### ')){html+='<div class="applications">';while(blocks[i]?.startsWith('### ')){html+='<article><h3>'+inline(blocks[i].slice(4))+'</h3><p>'+inline(blocks[i+1])+'</p><div class="application-link">'+inline(blocks[i+2])+'</div></article>';i+=3;}i--;html+='</div>';}
else if(s.startsWith('- '))html+='<ul>'+s.split(/\r?\n/).map(x=>'<li>'+inline(x.slice(2))+'</li>').join('')+'</ul>';
else if(/^\[[^\]]+\]\([^)]+\)$/.test(s)){html+='<div class="actions">';while(/^\[[^\]]+\]\([^)]+\)$/.test(blocks[i]||'')){let a=inline(blocks[i]);if(blocks[i].includes('](/request-a-quote/)'))a=a.replace('<a ','<a class="primary" ');html+=a;i++;}i--;html+='</div>';}
else html+='<p>'+inline(s)+'</p>';}
html+='</section>';
const css=`*{box-sizing:border-box}body{margin:0;background:#fff;color:#334155;font-family:Inter,Arial,sans-serif}main{font-size:17px;line-height:1.7}main .breadcrumb{max-width:1120px;margin:auto;padding:22px 0;font-size:14px;color:#516174}main a{display:inline-flex;min-width:44px;min-height:44px;align-items:center;color:#008078;text-underline-offset:4px}main a:focus-visible{outline:3px solid #008078;outline-offset:3px}main .module{padding:56px max(32px,calc((100% - 1120px)/2));border-top:1px solid #d9e2ec}main .m1{background:#f3f7fa;padding-top:40px;padding-bottom:52px}main .m5{background:#f3f7fa}main h1,main h2,main h3{color:#062b5b;line-height:1.2;margin:0 0 22px}main h1{font-size:48px;letter-spacing:-.025em;max-width:900px}main h2{font-size:32px;max-width:900px}main h3{font-size:22px;margin-bottom:16px}main p{max-width:880px;margin:0 0 22px}main .m1 p{font-size:20px;max-width:900px}main .actions{display:flex;flex-wrap:wrap;gap:16px;margin:26px 0 8px}main .actions a{min-height:50px;border:1px solid #008078;border-radius:6px;padding:12px 20px;justify-content:center;font-size:16px;font-weight:600;line-height:1.5;text-decoration:none}main .actions .primary{background:#008078;color:white}main .applications{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px;margin:30px 0}main .applications article{display:flex;flex-direction:column;border-top:2px solid #cbd5e1;padding-top:24px;min-width:0}main .applications p{margin-bottom:16px}main .application-link{margin-top:auto}main .application-link a{font-size:16px;font-weight:600}main ul{max-width:880px;padding-left:24px;margin:24px 0}main li{padding-left:8px;margin:12px 0}@media(max-width:1100px){main .breadcrumb{padding:18px 32px}main h1{font-size:40px}main .module{padding:44px 32px}main .applications{grid-template-columns:1fr;gap:24px}main .applications article{display:grid;grid-template-columns:175px minmax(0,1fr);gap:0 24px}main .applications .application-link{grid-column:2}}@media(max-width:560px){main{font-size:16px;line-height:1.7}main .breadcrumb{padding:16px 20px}main .module{padding:36px 20px}main h1{font-size:34px}main h2{font-size:28px}main h3{font-size:22px}main .m1 p{font-size:18px}main .applications article{display:block}main .actions{gap:12px}main .actions a{width:100%}}`;
const js=`window.localNavigation=[];document.addEventListener('click',event=>{const a=event.target.closest('a[href]');if(!a)return;event.preventDefault();const href=a.getAttribute('href');let context={};if(href==='/request-a-quote/')context={source_page_id:'MARKET-BR-EN',destination_country:'Brazil',destination_context_visible_editable:true};if(href==='/request-documents/')context={source_page_id:'MARKET-BR-EN'};window.localNavigation.push({href,context,evidence:'LOCAL_SIMULATION'});});`;
const source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';write(source,'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Titanium Dioxide Supplier Brazil | TiO2 Malaysia</title><style>'+shared.style+'\n'+css+'</style></head><body>'+shared.header+'<main>'+html+'</main>'+shared.footer+shared.dialog+'<script>'+shared.behavior+'\n'+js+'</script></body></html>');write(out+'/diagnostic_support/build-result.json',{source:identity(source),at:new Date().toISOString()});console.log(JSON.stringify(identity(source)));
