const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),oldroot=path.resolve(root,'../gate4-v0.1');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2));
const identity=p=>{const b=fs.readFileSync(p);return {path:p.replaceAll('\\','/'),relativePath:path.relative(root,p).replaceAll('\\','/'),bytes:b.length,sha256:hash(p),...(p.endsWith('.png')?{physicalWidth:b.readUInt32BE(16),physicalHeight:b.readUInt32BE(20)}:{})}};
const freeze=read(path.join(root,'approval_core/source-freeze.json')),exp=read(path.join(root,'approval_core/export-inventory.json')),pre=read(path.join(root,'diagnostic_support/preflight-observations.json')),run=read(path.join(root,'diagnostic_support/runtime-observations.json'));
const checks=[...freeze.dependencies,...freeze.inputs,...exp.captures,...pre.captures].map(x=>({path:x.path,expected:x.sha256,actual:hash(x.path),matches:hash(x.path)===x.sha256}));
if(checks.some(x=>!x.matches))throw Error('Frozen identity mismatch');
if(exp.sourceFreezeSha256!==hash(path.join(root,'approval_core/source-freeze.json')))throw Error('Export freeze mismatch');
const oldInv=read(path.join(oldroot,'asset-inventory.json'));
const historyChecks=oldInv.files.map(x=>({path:x.path,expected:x.sha256,actual:hash(x.path),matches:x.sha256===hash(x.path)}));
historyChecks.push({path:path.join(oldroot,'asset-inventory.json'),expected:'dc40becfb64fca745c4a2681a124cf49ecf5ff9c07ad014b13254326b2fef9ce',actual:hash(path.join(oldroot,'asset-inventory.json')),matches:hash(path.join(oldroot,'asset-inventory.json'))==='dc40becfb64fca745c4a2681a124cf49ecf5ff9c07ad014b13254326b2fef9ce'});
if(historyChecks.some(x=>!x.matches))throw Error('V0.1 history changed');
const oldCss=fs.readFileSync(path.join(oldroot,'visual-rules.css'),'utf8'),css=fs.readFileSync(path.join(root,'visual-rules.css'),'utf8');
if(!css.startsWith(oldCss))throw Error('V0.1 CSS prefix changed');
if(hash(path.join(root,freeze.entry))!==hash(path.join(oldroot,'MARKET-EU-PL_GATE4_VISUAL_SAMPLES_V0.1.html')))throw Error('HTML changed');
write('diagnostic_support/repair-source-inspection.json',{evidenceType:'SOURCE_INSPECTION',htmlByteIdentical:true,oldCssPrefixByteIdentical:true,onlyCssAddition:css.slice(oldCss.length),v01HistoricalFiles:historyChecks,normalGeometryComparison:'v01-v02-geometry-comparison.json'});
const imagePaths=[...exp.captures.map(x=>x.path),...pre.captures.map(x=>x.path),...fs.readdirSync(path.join(root,'diagnostic_support/preflight-attempt1')).filter(x=>x.endsWith('.png')).map(x=>path.join(root,'diagnostic_support/preflight-attempt1',x))];
const visual=imagePaths.map(p=>{let observation;
 if(p.includes('preflight-attempt1'))observation='Actually opened; Product Review retained prior test focus. Preserved diagnostic, not the final normal-state sample. Renderer resets state before final representative captures.';
 else if(p.includes('support-hover'))observation='Affected full link label and pale hover background visible; viewport edges may cut surrounding sections. Actual hover reconfirmed after screenshot. 1440/768 EU view also retains prior Document Hub focus, a real simultaneous state.';
 else if(p.includes('support-keyboard-focus'))observation='Full affected mobile hit area and teal outline visible; actual focus-visible confirmed after screenshot. No label clipping.';
 else if(p.includes('product-review'))observation='Both full application contexts readable with equal level, complete qualification and common browse action. Normal representative capture has no leftover focus.';
 else if(p.includes('documents'))observation='All three complete document paragraphs and both actions readable; unknown-grade alternative and ordinary COO sentence remain intact.';
 else if(p.includes('hero'))observation='Supplier answer, complete origin/procurement paragraph and request/browse hierarchy readable; Header fits. Explicit hero-focus image shows actual primary focus.';
 else if(p.includes('material'))observation='Complete TiO2 raw material versus finished white masterbatch paragraph readable.';
 else if(p.includes('final-rfq'))observation='Full unknown/multiple-grade and human contact guidance readable; full EU label remains subordinate.';
 else if(p.includes('footer'))observation='Complete Footer navigation/legal controls and reverse Logo readable without clipping.';
 else if(p.includes('menu'))observation='All eight menu rows readable; actual Home focus distinct from current Markets marker.';
 else if(p.includes('cookie'))observation='Complete no-optional-Analytics explanation and both controls fit on opaque dialog; Close focus visible.';
 return {...identity(p),evidenceType:'STATIC_VISUAL',inspection:'Actually opened with tools.view_image(detail=original) and read at exported size',observation,limit:'Displayed state only; behavior requires runtime records; not full Gate5 page approval'};
});
write('diagnostic_support/visual-observations.json',{date:new Date().toISOString(),freezeId:freeze.freezeId,formalImages:26,correctedPreflightImages:4,preservedPreflightImages:4,images:visual});
write('diagnostic_support/final-readback-receipt.json',{date:new Date().toISOString(),status:'FIX_IMPLEMENTED_PENDING_INDEPENDENT_REINSPECTION',freezeId:freeze.freezeId,sourceAndInputAndPngChecks:checks,oldHistoryChecks:historyChecks,exportFreezeBinding:true,formalPngCount:26,formalActualReadback:26,correctedPreflightActualReadback:4,preservedPreflightActualReadback:4,reportsReadBack:['MARKET-EU-PL_GATE4_VISUAL_DIRECTION_AND_METHOD_REPORT_V0.2.md','MARKET-EU-PL_GATE4_IR01_REPAIR_RESPONSE_V0.2.md','../../05_review/MARKET-EU-PL_GATE4_EXECUTION_SELF_CHECK_V0.2.md'],runtimeRecordCount:run.records.length,failedRuntimeAssertions:run.records.filter(x=>x.ok===false).length,sourceMutationAfterFreeze:false,limits:'Executor checks only. Initial IR01 remains independently open pending reinspection; S01 unchanged.'});
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(d,x.name)):[path.join(d,x.name)])}
const files=walk(root).filter(p=>path.basename(p)!=='asset-inventory.json').sort().map(p=>({...identity(p),role:p.includes('diagnostic_support')?'DIAGNOSTIC_SUPPORT':p.endsWith('.md')?'FORMAL_REPORT':'FORMAL_CORE'}));
files.push({...identity(path.resolve(root,'../../05_review/MARKET-EU-PL_GATE4_EXECUTION_SELF_CHECK_V0.2.md')),role:'EXECUTION_SELF_CHECK'});
const supplemental=identity('D:/23MySec/docs/architecture/GLOBAL_HEADER_FOOTER_SPEC_V0.4.md');
write('asset-inventory.json',{date:new Date().toISOString(),freezeId:freeze.freezeId,status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',findingStatus:'IR01_FIXED_IN_CANDIDATE_PENDING_INDEPENDENT_REINSPECTION',entry:freeze.entry,files,externalDependencies:freeze.dependencies.filter(x=>x.relativePath.startsWith('../')),frozenInputs:freeze.inputs,supplementalAuthority:[supplemental],notes:'26 newly rendered formal PNGs bind V0.2 source. Existing approved G3 CSS/font and Logo SVGs are relative dependencies; JSON snapshots and G3 HTML are provenance. No fresh shared package was copied. Archived preflight-attempt1 JSON retains its original paths as historical attempt data; inventory records relocated archive files. All V0.1 artifacts unchanged. This inventory omits its own recursive hash; handoff supplies it.'});
const inv=read(path.join(root,'asset-inventory.json'));for(const f of inv.files)if(hash(f.path)!==f.sha256)throw Error('Inventory readback mismatch');
console.log(JSON.stringify({files:files.length,pngs:files.filter(x=>x.path.endsWith('.png')).length,frozenChecks:checks.length,unchangedHistoricalFiles:historyChecks.length,sourceFreezeHash:hash(path.join(root,'approval_core/source-freeze.json')),exportInventoryHash:hash(path.join(root,'approval_core/export-inventory.json')),assetInventoryHash:hash(path.join(root,'asset-inventory.json'))},null,2));
