const fs=require('fs'),crypto=require('crypto');
const{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/products/chloride-process',src=base+'/04_planning/gate4-v0.1',out=base+'/05_review/gate4-project-control-v0.1/independent-review',entry=src+'/PRODUCT-PROC-CL_GATE4_VISUAL_SAMPLES_V0.1.html',url='file:///'+entry;
const read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim();
const freeze=json(src+'/approval_core/source-freeze.json'),inv=json(src+'/approval_core/export-inventory.json');
const records=[...freeze.dependencies,...freeze.inputs,...inv.captures];const identity={freezeId:freeze.freezeId,freezeBinding:hash(src+'/approval_core/source-freeze.json')===inv.sourceFreezeSha256,records:records.map(x=>({path:x.path,sha256:hash(x.path),match:hash(x.path)===x.sha256&&read(x.path).length===x.bytes})),pngDimensions:inv.captures.map(x=>{const b=read(x.path);return{path:x.path,w:b.readUInt32BE(16),h:b.readUInt32BE(20),match:b.readUInt32BE(16)===x.physicalWidth&&b.readUInt32BE(20)===x.physicalHeight}})};
const html=read(entry).toString(),g3=read(base+'/04_planning/gate3-v0.1/PRODUCT-PROC-CL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html').toString();identity.mainSourceSame=g3.split('<main>')[1].split('</main>')[0]===html.split('<main>')[1].split('</main>')[0];identity.interactionSourceSame=g3.split('<script>')[1]===html.split('<script>')[1];fs.writeFileSync(out+'/identity.json',JSON.stringify(identity,null,2));
const b=read(base+'/04_planning/PRODUCT-PROC-CL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md').toString().split('--- BEGIN BUYER CLEAN COPY ---')[1].split('--- END BUYER CLEAN COPY ---')[0];
const expected=norm(b.split('\n').map(l=>{if(/^## B-0[01]/.test(l)||/^\*\*Eyebrow/.test(l))return'';return l.replace(/^## B-\d+ — /,'').replace(/^#{1,3} /,'').replace(/\*\*(?:Primary action|Secondary action):\*\* /,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1')}).join(' '));
const expectedLinks=[...b.matchAll(/\[([^\]]+)\]\(([^)]*)\)/g)].map(x=>({text:x[1],href:x[2]}));
const lum=c=>{const a=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};const ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const desc=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();let n=e,bg=s.backgroundColor;while(bg==='rgba(0, 0, 0, 0)'&&n.parentElement){n=n.parentElement;bg=getComputedStyle(n).backgroundColor}return{text:e.innerText?.trim()||e.getAttribute('aria-label'),href:e.getAttribute('href'),tag:e.tagName,id:e.id,fg:s.color,bg,border:[s.borderColor,s.borderWidth],outline:[s.outlineColor,s.outlineWidth,s.outlineOffset,s.outlineStyle],font:[s.fontFamily,s.fontSize,s.fontWeight,s.lineHeight],hover:e.matches(':hover'),focused:e===document.activeElement,focusVisible:e.matches(':focus-visible'),box:{x:r.x,y:r.y+scrollY,w:r.width,h:r.height},viewportY:r.y}};
const active=p=>p.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.innerText?.trim().slice(0,80),href:document.activeElement.getAttribute('href')}));
const result={evidenceType:'ACTUAL_RUNTIME',widths:[],errors:[],network:[],expectedCopy:expected};
async function states(p,loc){const records=[];for(let i=0;i<await loc.count();i++){const a=loc.nth(i);if(!await a.isVisible())continue;await p.mouse.move(0,0);await p.evaluate(()=>document.activeElement.blur());const normal=await a.evaluate(desc);await a.hover();const hover=await a.evaluate(desc);await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');const focus=await a.evaluate(desc);for(const x of[normal,hover,focus])x.ratio=ratio(x.fg,x.bg);records.push({normal,hover,focus})}return records}
async function ready(p,target=url){await p.goto(target);await p.evaluate(()=>document.fonts.ready)}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();for(const width of[1440,768,390]){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});p.on('pageerror',e=>result.errors.push(e.message));await p.route('**/*',r=>{if(/^https?:/.test(r.request().url())){result.network.push(r.request().url());return r.abort()}return r.continue()});await ready(p);const row={width};row.copy={actual:norm(await p.locator('main').innerText()),expectedLinks,actualLinks:await p.locator('main a').evaluateAll(es=>es.map(e=>({text:e.textContent.trim(),href:e.getAttribute('href')})))};row.copy.equal=row.copy.actual===expected;row.copy.linksEqual=JSON.stringify(row.copy.actualLinks)===JSON.stringify(expectedLinks);
row.normal=await p.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}},stat=e=>{const s=getComputedStyle(e);return{text:e.textContent,box:box(e),font:s.font,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}};return{scrollWidth:document.documentElement.scrollWidth,header:box(document.querySelector('header')),images:[...document.images].map(e=>({src:e.getAttribute('src'),loaded:e.complete&&e.naturalWidth>0,box:box(e)})),current:[...document.querySelectorAll('[aria-current]')].map(e=>({text:e.textContent,href:e.getAttribute('href')})),paragraphs:[...document.querySelectorAll('main p')].map(stat),grades:[...document.querySelectorAll('.cl-grade')].map(e=>({box:box(e),name:stat(e.querySelector('h3')),summary:stat(e.querySelector('p')),link:stat(e.querySelector('a')),href:e.querySelector('a').getAttribute('href'),grid:getComputedStyle(e).gridTemplateColumns})),headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(stat)}});
const cdp=await p.context().newCDPSession(p);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'.cl-hero-copy p'});row.actualFonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});await cdp.detach();
await p.mouse.move(0,0);row.heroImageByteMatch=Buffer.from(await p.locator('#cl-01').screenshot()).equals(read(src+'/approval_core/'+width+'-hero.png'));row.controls=await states(p,p.locator('header a,header button,main a,footer a,footer button'));
await ready(p);const primary=p.locator('#cl-01 a[href^="#"]');await primary.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');row.anchor={keyboard:await p.locator('#explore-chloride-process-grades').evaluate(desc),hash:await p.evaluate(()=>location.hash)};await p.keyboard.press('Tab');row.anchor.next=await active(p);await ready(p,url+'#explore-chloride-process-grades');row.anchor.direct=await p.locator('#explore-chloride-process-grades').evaluate(desc);await p.keyboard.press('Tab');row.anchor.directNext=await active(p);
await ready(p);for(const a of await p.locator('main a:not([href^="#"])').all())await a.click();row.navigation={evidenceType:'LOCAL_SIMULATION',records:await p.evaluate(()=>window.planningNavigation)};
await ready(p);if(width<1101){const t=p.locator('.menuButton');await t.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');row.menu={entry:await active(p),hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),inert:await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].map(s=>({s,inert:document.querySelector(s).inert}))),overflow:await p.evaluate(()=>document.body.style.overflow)};await p.locator('main a').first().evaluate(e=>e.focus());row.menu.backgroundFocus=await active(p);await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');row.menu.forward=await active(p);await p.keyboard.press('Shift+Tab');row.menu.backward=await active(p);row.menu.states=await states(p,p.locator('.mobileNav a,.menuButton'));await p.keyboard.press('Escape');row.menu.escape={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p),inert:await p.locator('main').evaluate(e=>e.inert)};await t.press('Enter');await t.press('Enter');row.menu.close={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p)};await t.press('Enter');await p.locator('.mobileNav a[href="/products/"]').click();row.menu.selection={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),active:await active(p),record:await p.evaluate(()=>window.planningNavigation.at(-1))};await t.press('Enter');await p.setViewportSize({width:1440,height:1000});await p.waitForFunction(()=>document.querySelector('.mobileNav').hidden);row.menu.breakpoint={hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),inert:await p.locator('main').evaluate(e=>e.inert),overflow:await p.evaluate(()=>document.body.style.overflow),active:await active(p)};await p.setViewportSize({width,height:1000})}
const ct=p.locator('#cookie-trigger');await ct.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');await p.keyboard.press('Enter');row.cookie={entry:await active(p),opened:await p.locator('dialog').evaluate(e=>e.open)};await p.locator('main a').first().evaluate(e=>e.focus());row.cookie.backgroundFocus=await active(p);await p.keyboard.press('Shift+Tab');row.cookie.backward=await active(p);await p.keyboard.press('Tab');row.cookie.forward=await active(p);row.cookie.states=await states(p,p.locator('dialog button,dialog a'));await p.keyboard.press('Escape');row.cookie.escape={closed:await p.locator('dialog').evaluate(e=>!e.open),active:await active(p)};await ct.press('Enter');await p.locator('dialog button').click();row.cookie.close={closed:await p.locator('dialog').evaluate(e=>!e.open),active:await active(p)};
const nojs=await browser.newPage({viewport:{width,height:1000},javaScriptEnabled:false});await nojs.route('**/*',r=>/^https?:/.test(r.request().url())?r.abort():r.continue());await ready(nojs);row.noJS={copyEqual:norm(await nojs.locator('main').innerText())===expected,gradeLinks:await nojs.locator('.cl-grade a').count()};await nojs.locator('#cl-01 a[href^="#"]').click();row.noJS.click={hash:await nojs.evaluate(()=>location.hash),target:await nojs.locator('#explore-chloride-process-grades').evaluate(desc)};await nojs.keyboard.press('Tab');row.noJS.next=await active(nojs);await ready(nojs,url+'#explore-chloride-process-grades');row.noJS.direct=await nojs.locator('#explore-chloride-process-grades').evaluate(desc);await nojs.close();await p.close();result.widths.push(row);fs.writeFileSync(out+'/runtime.json',JSON.stringify(result,null,2));console.log(JSON.stringify({width,copy:row.copy.equal,links:row.copy.linksEqual,scrollWidth:row.normal.scrollWidth,heroMatch:row.heroImageByteMatch,controls:row.controls.length,lowContrast:row.controls.filter(x=>x.normal.text&&Math.min(x.normal.ratio,x.hover.ratio,x.focus.ratio)<4.5).map(x=>x.normal.text),focusFailed:row.controls.filter(x=>!x.focus.focusVisible).map(x=>x.normal.text),anchor:row.anchor.next,nojs:row.noJS.copyEqual}));}await browser.close();console.log(JSON.stringify({identities:identity.records.length,identityFailed:identity.records.filter(x=>!x.match).length,dimensionsFailed:identity.pngDimensions.filter(x=>!x.match).length,errors:result.errors,network:result.network}));})().catch(e=>{fs.writeFileSync(out+'/failure.txt',String(e.stack));console.error(e);process.exit(1)});
