// Independent ABOUT Gate3 read-only review; no author mutation scripts invoked.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../../../..'),candidate=path.join(root,'pages/about-contact/04_planning/d32-gate3-v0.2'),prior=path.join(root,'pages/about-contact/04_planning/d32-gate3-v0.1');
const read=f=>fs.readFileSync(f,'utf8'),json=f=>JSON.parse(read(f)),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const checks=[],observations={},check=(id,pass,detail)=>checks.push({id,pass:!!pass,detail});
const aggregate=rs=>crypto.createHash('sha256').update(rs.map(r=>r.relativePath+' '+r.sha256+'\n').sort().join('')).digest('hex');
const b=json(path.join(candidate,'bundle-manifest.json')),f=json(path.join(candidate,'freeze.json')),inputs=json(path.join(candidate,'input-identities.json'));
for(const r of b.approvalCore)check('core:'+r.relativePath,hash(r.path)===r.sha256&&fs.statSync(r.path).size===r.bytes);
check('bundle recomputed',aggregate(b.approvalCore)===b.bundleSha256,{actual:aggregate(b.approvalCore),expected:b.bundleSha256});
check('source set recomputed',aggregate(f.sources)===f.sourceSetSha256,f.sourceSetSha256);
observations.inputDrift=[];
for(const r of f.dependencies){const actual=hash(r.path);if(actual!==r.sha256&&r.relativePath==='01_PROJECT_INDEX.md'){observations.inputDrift.push({path:r.path,frozen:r.sha256,actual,classification:'CONCURRENT_SHARED_NAVIGATION_DRIFT / NON_PAGE_INPUT / NON_BLOCKING',authority:'Controller /root explicit review ruling 2026-09-21; reviewer read current Index and git diff; no ABOUT input change'});}else check('dependency:'+r.relativePath,actual===r.sha256,{actual,expected:r.sha256});}
for(const r of b.approvalCore.filter(r=>r.path.endsWith('.png'))){const data=fs.readFileSync(r.path);check('PNG:'+path.basename(r.path),data.readUInt32BE(16)===r.width&&data.readUInt32BE(20)===r.height,{w:r.width,h:r.height});}
for(const name of ['ABOUT-001_D32_GATE3.html','about.css','about.js','build.cjs','verify.cjs','shared-snapshot.css','shared-snapshot.js','media-projection.css'])check('v01 unchanged:'+name,hash(path.join(candidate,name))===hash(path.join(prior,name)));
check('old freeze preserved',json(path.join(prior,'freeze.json')).sourceSetSha256==='abbc8a54b299cabbe5d449f99c9175de1c78d948ef8689e3b7d7c9a7e1c3a3bf');
check('capture condition no sleep',read(path.join(candidate,'capture.cjs')).includes('requestAnimationFrame(()=>requestAnimationFrame(resolve))')&&!/setTimeout|waitForTimeout/.test(read(path.join(candidate,'capture.cjs'))));
const html=read(path.join(candidate,'ABOUT-001_D32_GATE3.html')),sharedDir=path.join(root,'docs/architecture/gate3-shared-consumer-v0.2');
const shared=require(path.join(sharedDir,'render-shared-chrome.cjs')).renderSharedChrome({currentPageId:'ABOUT-001',primaryLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf'});
for(const k of ['header','footer','dialog'])check('neutral owner '+k,html.includes(shared[k]));
check('neutral owner CSS',read(path.join(candidate,'shared-snapshot.css'))===shared.style);check('neutral owner behavior',read(path.join(candidate,'shared-snapshot.js'))===shared.behavior);
const sm=read(path.join(root,'pages/about-contact/06_handoff/ABOUT-001_GATE7_CONTENT_SEO_GEO_SCHEMA_SOURCE_MAP_V0.1.md'));
const content=sm.split('## 2. Approved Visible Content Records')[1].split('## 3. Inline Link Marks')[0];
const approved=[...content.matchAll(/`([^`]+)`/g)].map(x=>x[1]).filter(s=>!s.startsWith('/')&&!s.startsWith('Organization')&&!['name','description','location','areaServed'].includes(s));
const expectedH2=['Who We Are','Why Malaysia Matters','What We Do','Markets We Serve','Applications We Support','How We Work','Documentation & Transparency','Company Facts','Discuss Your Titanium Dioxide Requirements'];
const meta='Learn about IKHLAS TITANIUM (MALAYSIA) SDN. BHD., a Malaysia-based rutile TiO2 manufacturer with product documentation and export coordination through Port Klang.';
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({deviceScaleFactor:1}),errors=[];page.on('pageerror',e=>errors.push(e.message));const uri=pathToFileURL(path.join(candidate,'ABOUT-001_D32_GATE3.html')).href;observations.renderer=await browser.version();observations.geometry=[];
for(const width of [1440,768,390]){await page.setViewportSize({width,height:960});await page.goto(uri);await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const body=await page.locator('main').innerText();
for(const s of approved)check(`${width}:content:${s.slice(0,46)}`,body.includes(s),s);
check(width+':order',JSON.stringify(await page.locator('main h2').allTextContents())===JSON.stringify(expectedH2));
check(width+':no public disclosure or unapproved fields',!/(company-provided|company-reported|Source: mytio2|Reviewed 1|independently audited|legalName|ISO|certified QMS|registration number|CURRENT|PENDING|DO_NOT_RENDER)/i.test(body));
check(width+':title',await page.title()==='Malaysia Titanium Dioxide Manufacturer | TiO2 Malaysia');check(width+':meta',await page.locator('meta[name=description]').getAttribute('content')===meta);check(width+':no hidden schema expansion',await page.locator('script[type="application/ld+json"],[itemscope]').count()===0);
check(width+':relative canonical and noindex',await page.locator('link[rel=canonical]').getAttribute('href')==='/about/'&&(await page.locator('meta[name=robots]').getAttribute('content')).includes('noindex'));
check(width+':corporate slot',await page.locator('[data-component=RootPageHero][data-variant=corporate-light][data-ownership=PROTOTYPE_ONLY]').count()===1);
check(width+':inline owners',await page.locator('.about-support p').first().locator('a[href="/applications/"]').count()===5&&await page.locator('main a[href="/products/"]').count()===2&&await page.locator('.about-support a[href="/"]').count()===1);
check(width+':fallback and document owners',await page.locator('#markets a').evaluateAll(es=>es.length===5&&es.every(e=>e.getAttribute('href')==='/markets/'))&&await page.locator('#applications a').evaluateAll(es=>es.length===5&&es.every(e=>e.getAttribute('href')==='/applications/'))&&await page.locator('#documentation a[href="/documents/"]').count()===2&&await page.locator('#documentation a[href="/request-documents/"]').count()===1);
check(width+':body cta owners',await page.locator('.about-actions a').evaluateAll(es=>es.length===4&&es.every(e=>e.getAttribute('href')===(e.textContent==='Contact Us'?'/contact/':'/request-a-quote/'))));
check(width+':media semantics',await page.locator('svg.about-crop').evaluateAll(es=>es.length===10&&es.every(e=>e.getAttribute('preserveAspectRatio')==='xMidYMid slice'&&(e.getAttribute('aria-hidden')==='true'||e.getAttribute('aria-label'))))&&await page.locator('.about-composite[aria-hidden=true]').count()===1);
check(width+':no form or actual download',await page.locator('form,a[download]').count()===0);check(width+':About current',await page.locator('.desktopNav [aria-current=page]').getAttribute('href')==='/about/'&&await page.locator('.mobileNav [aria-current=page]').getAttribute('href')==='/about/');check(width+':fixed RFQ',await page.locator('.headerRfq').isVisible()&&await page.locator('.footerRfq').getAttribute('href')==='/request-a-quote/');
const g=await page.evaluate(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden',cs=e=>getComputedStyle(e),r=e=>e.getBoundingClientRect();return {width:innerWidth,scroll:document.documentElement.scrollWidth,dpr:devicePixelRatio,small:[...document.querySelectorAll('a,button')].filter(visible).filter(e=>r(e).width<44||r(e).height<44).map(e=>e.textContent),clip:[...document.querySelectorAll('main p,main dt,main dd,main h1,main h2,main h3')].filter(visible).filter(e=>e.scrollWidth>e.clientWidth+1||['hidden','clip'].includes(cs(e).overflowY)&&e.scrollHeight>e.clientHeight+1).map(e=>e.textContent),h1:{font:cs(document.querySelector('h1')).fontSize,spacing:cs(document.querySelector('h1')).letterSpacing,lines:Math.round(r(document.querySelector('h1')).height/parseFloat(cs(document.querySelector('h1')).lineHeight))},images:[...document.images].every(e=>e.complete&&e.naturalWidth>0),font:document.fonts.check('16px Inter'),heroPad:cs(document.querySelector('.about-hero-layout')).paddingLeft}});observations.geometry.push(g);
check(width+':geometry',g.scroll===width&&g.clip.length===0,g);check(width+':44targets',g.small.length===0,g.small);check(width+':resources',g.images&&g.font);check(width+':Hero geometry',g.heroPad===(width===1440?'56px':width===768?'40px':'24px')&&g.h1.font===(width===1440?'56px':width===768?'44px':'36px')&&g.h1.spacing==='normal'&&g.h1.lines<=(width===390?4:3),g.h1);
await page.locator('.about-actions a').first().focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');check(width+':focus visible',await page.locator('.about-actions a').first().evaluate(e=>e.matches(':focus-visible')&&getComputedStyle(e).outlineWidth==='3px'));
if(width!==1440){await page.locator('.menuButton').click();check(width+':menu enter/isolate',await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement)&&await page.evaluate(()=>[document.querySelector('main'),document.querySelector('footer'),document.querySelector('.logoLink'),document.querySelector('.headerRfq')].every(e=>e.inert)));await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');check(width+':menu loop',await page.locator('.menuButton').evaluate(e=>e===document.activeElement));await page.keyboard.press('Shift+Tab');check(width+':menu reverse',await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');check(width+':menu escape/return',await page.locator('.mobileNav').isHidden()&&await page.locator('.menuButton').evaluate(e=>e===document.activeElement)&&await page.locator('main').evaluate(e=>!e.inert));await page.locator('.menuButton').click();await page.evaluate(()=>document.querySelector('.mobileNav').addEventListener('click',e=>e.preventDefault(),{once:true}));await page.locator('.mobileNav a[href="/about/"]').click();check(width+':menu selection exit',await page.locator('.mobileNav').isHidden()&&await page.locator('main').evaluate(e=>!e.inert));await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:960});await page.waitForFunction(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert);check(width+':resize recover',await page.locator('footer').evaluate(e=>!e.inert));await page.setViewportSize({width,height:960});}
await page.locator('#cookie-trigger').click();check(width+':cookie entry',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await page.keyboard.press('Shift+Tab');check(width+':cookie reverse',await page.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');check(width+':cookie forward',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));check(width+':consent no analytics',/No optional Analytics/.test(await page.locator('#cookie-body').innerText())&&await page.locator('script[src*="google"],script[src*="gtm"]').count()===0);await page.keyboard.press('Escape');check(width+':cookie return',await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));
}
for(const state of ['partial','restricted']){await page.goto(uri+'?evidence='+state);const text=await page.locator('main').innerText();check(state+':scale absent',!/(35,000|over 30 countries|200 factory customers)/.test(text));check(state+':no UI placeholders',!/(unavailable|restricted|pending|—)/i.test(text));if(state==='restricted'){check(state+':capability absent',!/(Taiping|Port Klang|REACH|COA|COO)/.test(text));check(state+':meta atomic',await page.locator('meta[name=description]').count()===0&&await page.title()==='About TiO2 Malaysia');}check(state+':remaining owners',await page.locator('.headerRfq').isVisible()&&await page.locator('#final a').count()===2);}
await page.goto(uri);const contrast=await page.evaluate(()=>{const lum=s=>s.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);function bg(e){while(e){const b=getComputedStyle(e).backgroundColor;if(b!=='rgba(0, 0, 0, 0)'&&b!=='transparent')return b;e=e.parentElement}return 'rgb(255,255,255)'}return [...document.querySelectorAll('main p,main h1,main h2,main h3,main a,main dt,main dd')].filter(e=>e.getClientRects().length).map(e=>{let s=getComputedStyle(e),a=lum(s.color),b=lum(bg(e)),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);return {text:e.textContent.slice(0,60),ratio,threshold:parseFloat(s.fontSize)>=24||parseFloat(s.fontSize)>=18.66&&parseInt(s.fontWeight)>=700?3:4.5}})});observations.contrast=contrast;check('actual solid text contrast',contrast.every(r=>r.ratio>=r.threshold),contrast.filter(r=>r.ratio<r.threshold));check('browser errors absent',errors.length===0,errors);
for(const r of b.approvalCore)check('read-only retention:'+path.basename(r.path),hash(r.path)===r.sha256);
await browser.close();const result={reviewer:'/root/market_root_d32',time:new Date().toISOString(),candidateManifest:'ABOUT-001_D32_GATE3_CANDIDATE_MANIFEST_V0.2.md',bundle:b.bundleSha256,sourceSet:f.sourceSetSha256,html:b.htmlSha256,passed:checks.filter(r=>r.pass).length,failed:checks.filter(r=>!r.pass).length,checks,observations};fs.writeFileSync(path.join(__dirname,'independent-results.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(r=>!r.pass),navigationDrift:observations.inputDrift},null,2));process.exitCode=result.failed?1:0;})().catch(e=>{console.error(e);process.exit(1)});
