const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/resources/eu-trade/04_planning/gate4-v0.1/';
const out=__dirname+'/observations.json';
const identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const result={reviewer:'/root/g5_trade_eu',author:'/root/gate4_eu_trade_execute',dispatch_id:'G5-9PAGE-REVIEW-20260907-01/RES-TRADE-EU/INITIAL',at:new Date().toISOString(),identities:[],viewports:[],errors:[],screenshotsSaved:0};
function verify(o,category){if(!o||typeof o!=='object')return;if(o.path&&o.sha256){try{let a=identity(o.path);let ok=a.sha256===o.sha256&&(o.bytes===undefined||a.bytes===o.bytes);if(o.physicalWidth){let b=fs.readFileSync(o.path);a.dimensions=[b.readUInt32BE(16),b.readUInt32BE(20)];ok=ok&&a.dimensions[0]===o.physicalWidth&&a.dimensions[1]===o.physicalHeight;}result.identities.push({category,...a,expected:o.sha256,ok});}catch(e){result.identities.push({category,path:o.path,ok:false,error:String(e)})}}for(const v of Object.values(o))if(typeof v==='object')verify(v,category);}
for(const f of ['freeze-record.json','evidence-index.json','input-index.json'])verify(JSON.parse(fs.readFileSync(base+f)),f);
result.coreFiles=['freeze-record.json','evidence-index.json','input-index.json'].map(f=>identity(base+f));
result.methodFiles=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md'].map(f=>identity('D:/23MySec/'+f));
const source=base+'RES-TRADE-EU_GATE4_COMPLETE_VISUAL_V0.1.html';
const original=fs.readFileSync(source,'utf8');const g3=fs.readFileSync(base.replace('gate4-v0.1/','gate3-v0.1/')+'RES-TRADE-EU_GATE3_WIREFRAME_V0.1.html','utf8');result.postStyleIdentical=original.split('</style>')[1]===g3.split('</style>')[1];
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});result.browser=await browser.version();
for(const width of [1440,768,390]){const ctx=await browser.newContext({viewport:{width,height:width===390?844:900},deviceScaleFactor:1});await ctx.route(/^https?:/,r=>r.abort());const p=await ctx.newPage();p.on('pageerror',e=>result.errors.push(String(e)));await p.goto(pathToFileURL(source).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(x=>x.decode()))});
const v={width,geometry:await p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,w:r.width,h:r.height}};return{dpr:devicePixelRatio,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,font:document.fonts.check('16px Inter'),headHeight:document.querySelector('header').offsetHeight,modules:[...document.querySelectorAll('main section')].map(e=>({module:e.dataset.module,...rect(e)})),controls:[...document.querySelectorAll('a,button')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent.trim(),href:e.getAttribute('href'),...rect(e)})),cells:[...document.querySelectorAll('th,td')].map(e=>({text:e.textContent,...rect(e),font:getComputedStyle(e).fontSize,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth})),clipped:[...document.querySelectorAll('main *')].filter(e=>e.clientWidth&&e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,text:e.textContent.slice(0,100),sw:e.scrollWidth,cw:e.clientWidth})),links:[...document.querySelectorAll('main a')].map(e=>({text:e.textContent,href:e.getAttribute('href')})),text:document.querySelector('main').innerText,images:[...document.images].map(e=>({src:e.src,loaded:e.complete&&e.naturalWidth>0}))}}),actions:[]};
const act=async(name,fn)=>{try{v.actions.push({name,result:await fn()})}catch(e){v.actions.push({name,error:String(e)})}};
const focus=()=>p.evaluate(()=>({tag:document.activeElement.tagName,cls:document.activeElement.className,text:document.activeElement.textContent.trim(),outline:getComputedStyle(document.activeElement).outline}));
await act('primary hover',async()=>{await p.locator('.module-1 a').first().hover();return p.locator('.module-1 a').first().evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}))});
await act('secondary keyboard focus',async()=>{await p.locator('.module-1 a').first().focus();await p.keyboard.press('Tab');return focus()});
if(width<1101){await act('menu entry, background isolation, keyboard cycle and scroll lock',async()=>{await p.locator('.menuButton').focus();await p.keyboard.press('Enter');const entry=await focus();const isolation=await p.evaluate(()=>[...document.querySelectorAll('main,footer,.logoLink,.headerRfq')].map(e=>e.inert));await p.keyboard.press('Shift+Tab');const toggle=await focus();await p.keyboard.press('Shift+Tab');const last=await focus();await p.keyboard.press('Tab');const loop=await focus();const y=await p.evaluate(()=>scrollY);await p.mouse.move(380,600);await p.mouse.wheel(0,400);await p.waitForTimeout(100);return{entry,isolation,toggle,last,loop,scrollLocked:y===await p.evaluate(()=>scrollY)}});
await act('menu Escape returns focus',async()=>{await p.keyboard.press('Escape');return{hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),focus:await focus(),backgroundRestored:await p.locator('main').evaluate(e=>!e.inert)}});
await act('menu Close returns focus',async()=>{await p.locator('.menuButton').click();await p.locator('.menuButton').click();return{hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),focus:await focus()}});
await act('every menu link local intent and close',async()=>{let obs=[];for(let i=0;i<8;i++){await p.locator('.menuButton').click();const a=p.locator('.mobileNav a').nth(i);const href=await a.getAttribute('href');await a.click();obs.push({href,hidden:await p.locator('.mobileNav').evaluate(e=>e.hidden),intent:await p.evaluate(()=>localNavigationIntents.at(-1))})}return obs});
await act('open menu desktop breakpoint exit',async()=>{await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:900});await p.waitForTimeout(100);let o=await p.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,inert:document.querySelector('main').inert,overflow:document.body.style.overflow}));await p.setViewportSize({width,height:width===390?844:900});return o});}
await act('cookie entry, cycle, background isolation, Escape return',async()=>{await p.locator('#cookie-trigger').focus();await p.keyboard.press('Enter');let entry=await focus();await p.keyboard.press('Shift+Tab');let last=await focus();await p.keyboard.press('Tab');let loop=await focus();await p.locator('.headerRfq').evaluate(e=>e.focus());let isolated=await p.locator('.cookie-layer').evaluate(e=>e.contains(document.activeElement));await p.keyboard.press('Escape');return{entry,last,loop,isolated,closed:await p.locator('dialog').evaluate(e=>!e.open),returnFocus:await focus()}});
await act('cookie Close return and policy intent',async()=>{await p.locator('#cookie-trigger').click();await p.locator('[data-cookie-close]').click();let returned=await focus();await p.locator('#cookie-trigger').click();await p.locator('.cookie-actions a').click();let intent=await p.evaluate(()=>localNavigationIntents.at(-1));await p.keyboard.press('Escape');return{returned,intent}});
await act('all visible body and shared links local intent',async()=>{let obs=[];const all=p.locator('a');for(let i=0;i<await all.count();i++){let a=all.nth(i);if(!await a.isVisible())continue;let href=await a.getAttribute('href');await a.click();obs.push({href,intent:await p.evaluate(()=>localNavigationIntents.at(-1))})}return obs});
v.footer=await p.locator('footer').evaluate(e=>({text:e.innerText,bottom:e.getBoundingClientRect().bottom+scrollY}));result.viewports.push(v);await ctx.close();}
await browser.close();result.finalSource=identity(source);fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({output:out,identityMismatches:result.identities.filter(x=>!x.ok),errors:result.errors,viewports:result.viewports.map(v=>({width:v.width,height:v.geometry.height,clipped:v.geometry.clipped,shortControls:v.geometry.controls.filter(c=>c.w<43.99||c.h<43.99),actionErrors:v.actions.filter(x=>x.error)}))}));})().catch(e=>{result.errors.push(String(e));fs.writeFileSync(out,JSON.stringify(result,null,2));console.error(e);process.exitCode=1});
