// Local D23 design evidence only. Never writes prior candidate or development trees.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,old=path.resolve(dir,'../d32-gate4-v0.1'),repo=path.resolve(dir,'../../../..'),mode=process.argv[2];
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),rec=p=>({path:p.replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:hash(p)}),read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const write=(name,obj)=>{const p=path.join(dir,name);if(fs.existsSync(p))throw Error('Do not overwrite '+p);fs.writeFileSync(p,JSON.stringify(obj,null,2)+'\n')};
const prior=read(old+'/freeze.json'),oldLock=read(old+'/source-lock.json');
const checkPrior=()=>{if(prior.files.some(f=>hash(f.path)!==f.sha256||fs.statSync(f.path).size!==f.bytes))throw Error('Prior frozen file drift');};
async function open(browser,base,width){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});await p.goto(pathToFileURL(base+'/DOC-000_D32_structure.html').href);await p.evaluate(()=>document.fonts.ready);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));return p;}
const checkLock=()=>{const l=read(dir+'/source-lock.json');if([...l.sources,...l.dependencies].some(f=>hash(f.path)!==f.sha256))throw Error('Locked source changed');return l};
async function boxes(p){return p.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.checkVisibility()).map(e=>{const r=e.getBoundingClientRect();return {key:e.tagName+'#'+e.id+'.'+e.className,x:r.x,y:r.y+scrollY,w:r.width,h:r.height,text:e.childElementCount?null:e.textContent}}));}
(async()=>{checkPrior();
if(mode==='preflight'){
 const checks=[],test=(id,pass,actual)=>checks.push({id,pass,actual});
 test('74 prior frozen members intact',prior.files.length===74,true);
 for(const name of ['DOC-000_D32_structure.html','DOC-000_D32_behavior.js'])test('byte identity '+name,hash(dir+'/'+name)===hash(old+'/'+name),hash(dir+'/'+name));
 const before=fs.readFileSync(old+'/DOC-000_D32_structure.css','utf8'),after=fs.readFileSync(dir+'/DOC-000_D32_structure.css','utf8');
 test('only approved narrow feedback CSS delta',after.startsWith(before.trimEnd())&&after.slice(before.trimEnd().length).trim()==='/* D23 design-only feedback reservation; ROOT-NARROW-VISUAL-20260921 §4. */\n@media(max-width:340px){.doc-selector #grade-error{min-height:3.3em}}','Shared/body rules otherwise exact');
 test('targeted green',read(dir+'/green.json').failed===0,read(dir+'/green.json').passed);test('full existing author suite',read(dir+'/diagnostic_support/GREEN.json').status==='PASS',read(dir+'/diagnostic_support/GREEN.json').results.length);
 const browser=await chromium.launch({headless:true});for(const width of [1440,1024,768,390,320]){const a=await open(browser,old,width),b=await open(browser,dir,width),aa=await boxes(a),bb=await boxes(b),diff=bb.map((v,i)=>({old:aa[i],now:v})).filter(x=>JSON.stringify(x.old)!==JSON.stringify(x.now));
 if(width>340)test(width+' entire visible main geometry unchanged',diff.length===0,diff);else{const bad=diff.filter(x=>x.old.key!==x.now.key||x.old.text!==x.now.text||x.old.x!==x.now.x||x.old.w!==x.now.w||Math.abs(x.now.y-x.old.y)>22.3||(!['SECTION#grade-selector.doc-section doc-width doc-selector','DIV#.doc-selector-controls','P#grade-error.'].includes(x.now.key)&&x.old.h!==x.now.h));test('320 only feedback height and downstream flow offset',bad.length===0,{changed:diff.length,bad,differences:diff});}
 const hero=await b.locator('.root-hero').evaluate(e=>({overflow:document.documentElement.scrollWidth>innerWidth,eyebrowLines:Math.round(e.querySelector('.doc-eyebrow').getBoundingClientRect().height/parseFloat(getComputedStyle(e.querySelector('.doc-eyebrow')).lineHeight))}));test(width+' no overflow / eyebrow remains one line',!hero.overflow&&hero.eyebrowLines===1,hero);await a.close();await b.close();}
 const rendering={browser:browser.version(),viewport_height:1000,deviceScaleFactor:1,reducedMotion:'reduce',font_wait:'document.fonts.ready + two animation frames',evidence:'D23 file:// prototype'};await browser.close();
 write('preflight.json',{passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length,checks,rendering});if(checks.some(c=>!c.pass))throw Error('Preflight fail');
 const sources=['DOC-000_D32_structure.html','DOC-000_D32_structure.css','DOC-000_D32_behavior.js','DOC-000_D32_verify.cjs','r02-check.cjs','evidence.cjs','design-change.md','red.json','green.json','preflight.json','diagnostic_support/GREEN.json'].map(n=>rec(dir+'/'+n));
 const authority=['docs/architecture/ROOT_PAGE_NARROW_VISUAL_AND_DOC_FEEDBACK_DECISION_V1.0.md','docs/architecture/STATIC_NEXTJS_SINGLE_SITE_AND_GOOGLE_INDEXING_DECISION_V1.0.md','pages/documents/05_review/DOC-000_D32_GATE5_INDEPENDENT_REVIEW_V0.1.md'].map(n=>rec(repo+'/'+n));
 write('source-lock.json',{locked_at:new Date().toISOString(),html:rec(dir+'/DOC-000_D32_structure.html'),sources,dependencies:oldLock.dependencies,authority,prior_freeze:rec(old+'/freeze.json'),prior_bundle:prior.bundle_id,rendering});console.log(JSON.stringify({preflight:checks.length,failed:0}));
}
if(mode==='capture'){
 const lock=checkLock(),browser=await chromium.launch({headless:true}),evidence=[];fs.mkdirSync(dir+'/formal',{recursive:true});
 async function shot(p,name,state,selector){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const out=dir+'/formal/'+name+'.png';if(fs.existsSync(out))throw Error('Image exists');if(selector)await p.locator(selector).screenshot({path:out});else await p.screenshot({path:out,fullPage:name.startsWith('FULL')});const buf=fs.readFileSync(out);evidence.push({...rec(out),width:buf.readUInt32BE(16),height:buf.readUInt32BE(20),viewport:p.viewportSize(),dpr:await p.evaluate(()=>devicePixelRatio),state,source_lock:rec(dir+'/source-lock.json')});}
 const p=await open(browser,dir,320);await shot(p,'FULL_320','initial full');await shot(p,'INITIAL_320','initial','#grade-selector');await p.locator('#continue-request').click();await shot(p,'ERROR_320','no grade / error / focus select','#grade-selector');await p.locator('#product-grade').selectOption('M-2196');await shot(p,'SELECTED_320','M-2196 selected','#grade-selector');await p.locator('#product-grade').selectOption('');await shot(p,'CLEARED_320','selection cleared','#grade-selector');await p.evaluate(()=>scrollTo(0,1250));await shot(p,'FLOW_320','new selector to following content readable');await p.close();
 const q=await open(browser,dir,390);await q.locator('#continue-request').click();await shot(q,'ERROR_390','unchanged390 error regression','#grade-selector');await q.close();await browser.close();checkLock();
 const oldIndex=read(old+'/evidence-index.json'),superseded=['FULL_320.png','ERROR_320.png','SELECTED_320.png','ERROR_390.png'];
 write('evidence-index.json',{timestamp:new Date().toISOString(),source_lock:rec(dir+'/source-lock.json'),new_evidence:evidence,inherited_index:rec(old+'/evidence-index.json'),inherited_formal:oldIndex.evidence.filter(e=>e.role==='FORMAL'&&!superseded.includes(path.basename(e.path))),superseded_old_formal:superseded,inherited_readable:oldIndex.evidence.filter(e=>e.role==='READABLE_SUPPORT'&&e.viewport.width!==320),prior320_readable_role:'Original content-reading evidence only; not current absolute-coordinate screenshots',inheritance:'Byte-identical HTML/JS/dependencies; >340 exact runtime geometry; 320 unaffected element sizes and only feedback/downstream translation. See preflight and design-change.'});console.log(JSON.stringify({new_images:evidence.length,formal:6,readable:1,inherited_formal:14,inherited_readable:22}));
}
if(mode==='freeze'){
 const lock=checkLock(),index=read(dir+'/evidence-index.json');if(!fs.existsSync(dir+'/capture-check.md'))throw Error('Actual image inspection required');
 const img=index.new_evidence.map(e=>{const b=fs.readFileSync(e.path);return {path:e.path,pass:hash(e.path)===e.sha256&&b.readUInt32BE(16)===e.width&&b.readUInt32BE(20)===e.height&&e.dpr===1}});if(img.some(e=>!e.pass))throw Error('Evidence changed');write('machine-check.json',{passed:img.length,failed:0,checks:img,prior74_unchanged:true});
 const files=[...lock.sources,...lock.dependencies,...lock.authority,lock.prior_freeze,index.inherited_index,...index.inherited_formal.map(e=>rec(e.path)),...index.inherited_readable.map(e=>rec(e.path)),...index.new_evidence.map(e=>rec(e.path)),...['source-lock.json','evidence-index.json','capture-check.md','machine-check.json','DOC-000_D32_GATE4_GATE5_HANDOFF_V0.2.md'].map(n=>rec(dir+'/'+n))].sort((a,b)=>a.path.localeCompare(b.path));
 const bundle_id=crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex');write('freeze.json',{freeze_id:'DOC000-D32-G4-V02',status:'CHANGES_READY_FOR_TARGETED_REVIEW',author:'/root/doc_root_d32',bundle_id,bundle_algorithm:'SHA256(UTF8(JSON.stringify(files))); sorted path.localeCompare; {path,bytes,sha256}',files,source_identity:hash(dir+'/DOC-000_D32_structure.html'),css_identity:hash(dir+'/DOC-000_D32_structure.css'),prior_bundle:prior.bundle_id,decision:'ROOT-NARROW-VISUAL-20260921',new_formal:6,new_readable:1,inherited_formal:14,inherited_readable:22,reviewer_valid_coverage_retained:410,findings_for_independent_recheck:['DOC-D32-G5-R01','DOC-D32-G5-R02'],timestamp:new Date().toISOString()});console.log(JSON.stringify({bundle_id,html:hash(dir+'/DOC-000_D32_structure.html'),css:hash(dir+'/DOC-000_D32_structure.css'),freeze:rec(dir+'/freeze.json')},null,2));
}
})().catch(e=>{console.error(e);process.exitCode=1});
