// D23 prototype verifier only. Detects feedback expansion that displaces Continue.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,prior=path.resolve(dir,'../d32-gate4-v0.1'),mode=process.argv[2],candidate=mode==='red'?prior:dir;
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),checks=[],states=[];
const check=(id,pass,actual)=>checks.push({id,pass:!!pass,actual});
const grades=['M-350','M-510','M-896','M-996','M-2196','M-895','M-200','M-108','M-210','M-340','M-886','M-52','M-2377','CR-901'];
async function geometry(p){return p.evaluate(()=>{const rect=s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,w:r.width,h:r.height}};return {button:rect('#continue-request'),error:rect('#grade-error'),selector:rect('#grade-selector'),text:document.querySelector('#grade-error').textContent,focus:document.activeElement.id,overflow:document.documentElement.scrollWidth>innerWidth,invalid:document.querySelector('#product-grade').getAttribute('aria-invalid'),href:document.querySelector('#continue-request').getAttribute('href'),errorAssociated:document.querySelector('#product-grade').getAttribute('aria-describedby').includes('grade-error'),errorClipped:document.querySelector('#grade-error').scrollWidth>document.querySelector('#grade-error').clientWidth,faq:document.querySelector('.faq-question').getAttribute('aria-expanded')}});}
(async()=>{const browser=await chromium.launch({headless:true});
for(const width of [1440,1024,768,390,341,340,320]){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});await p.goto(pathToFileURL(candidate+'/DOC-000_D32_structure.html').href);await p.evaluate(()=>document.fonts.ready);const url=p.url();
await p.locator('.faq-question').first().click();const samples=[];samples.push({state:'initial',...await geometry(p)});await p.locator('#continue-request').click();samples.push({state:'error',...await geometry(p)});
check(width+':complete error/focus/no navigation',samples[1].text==='Select a product grade to continue.'&&samples[1].focus==='product-grade'&&samples[1].invalid==='true'&&samples[1].errorAssociated&&!samples[1].errorClipped&&p.url()===url,samples[1]);
await p.locator('#product-grade').selectOption('M-2196');samples.push({state:'selected',...await geometry(p)});await p.locator('#product-grade').selectOption('');samples.push({state:'cleared',...await geometry(p)});
check(width+':four-state Continue stability',samples.every(s=>Math.abs(s.button.y-samples[0].button.y)<.1&&s.button.x===samples[0].button.x),samples.map(s=>({state:s.state,y:s.button.y,errorHeight:s.error.h})));
check(width+':unrelated FAQ retained',samples.every(s=>s.faq==='true'),samples.map(s=>s.faq));check(width+':no overlap/overflow/target loss',samples.every(s=>!s.overflow&&s.button.h>=44&&s.button.w>=44&&s.error.y+s.error.h<=s.button.y),samples.map(s=>s.button));
check(width+':clearing restores neutral',samples[3].text===''&&samples[3].invalid===null&&samples[3].href==='#grade-selector',samples[3]);
for(const grade of grades){await p.locator('#product-grade').selectOption(grade);check(width+':route '+grade,await p.locator('#continue-request').getAttribute('href')==='/request-documents/?product='+grade&&await p.locator('#closing-action').getAttribute('href')==='/request-documents/?product='+grade,await p.locator('#continue-request').getAttribute('href'));}
const hero=await p.locator('h1').evaluate(e=>({text:e.textContent,size:getComputedStyle(e).fontSize,weight:getComputedStyle(e).fontWeight,lines:Math.round(e.getBoundingClientRect().height/parseFloat(getComputedStyle(e).lineHeight))}));check(width+':unchanged H1 presentation',hero.text==='Documents for Product & Supplier Qualification'&&hero.weight==='700'&&(width!==320||hero.size==='36px'&&hero.lines===4),hero);states.push({width,samples,hero});await p.close();}
await browser.close();const result={mode,source_sha256:hash(candidate+'/DOC-000_D32_structure.html'),css_sha256:hash(candidate+'/DOC-000_D32_structure.css'),browser:'Chromium',timestamp:new Date().toISOString(),passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length,checks,states};fs.writeFileSync(dir+'/'+mode+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({mode,passed:result.passed,failed:result.failed,failures:checks.filter(c=>!c.pass)},null,2));process.exitCode=result.failed?1:0;})();
