const fs=require('fs'),path=require('path'),crypto=require('crypto'),out=path.resolve(__dirname,'..').replaceAll('\\','/'),prior=out.replace('gate4-v0.2','gate4-v0.1'),root='D:/23MySec',sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});if(fs.existsSync(out+'/approval_core/source-freeze.json'))throw Error('Frozen');const prev=JSON.parse(fs.readFileSync(prior+'/approval_core/source-freeze.json')),review=root+'/pages/markets/netherlands/05_review/gate4-project-control-v0.1/independent-review/report.md';if(sha(review)!=='81c6a4efe86fa8068040b9f14086287f19229b7c0a7bc38bb334d1b37fa99d2d')throw Error('Independent report identity');
const allowedDrift=['D:/23MySec/AGENTS.md','D:/23MySec/PROJECT_CONTEXT.md','D:/23MySec/02_DIRECTORY_GUIDE.md'];for(const x of prev.inputs)if(sha(x.path)!==x.sha256&&!allowedDrift.includes(x.path))throw Error('Unexpected input drift');
const inputs=[...new Set([...prev.inputs.map(x=>x.path),...['GATE_WORKFLOW_V2.0.md','PAGE_GATE_1_5_STANDARD_V1.2.md','PROJECT_GOVERNANCE_DETAILS_V1.1.md'].map(x=>root+'/docs/architecture/'+x),review,...['MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html','visual-direction.css','approval_core/source-freeze.json','approval_core/export-inventory.json','approval_core/asset-inventory.json','MARKET-EU-NL_GATE4_VISUAL_DIRECTION_AND_METHOD_REPORT_V0.1.md'].map(x=>prior+'/'+x),root+'/pages/markets/netherlands/05_review/MARKET-EU-NL_GATE4_EXECUTION_SELF_CHECK_V0.1.md'])].map(id);
const target=out+'/MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.2.html';if(sha(target)!==sha(prior+'/MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html'))throw Error('Unexpected markup change');const dependencies=['MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.2.html','visual-direction.css',...fs.readdirSync(out+'/dependencies').map(x=>'dependencies/'+x)].map(x=>id(out+'/'+x));
for(const f of['preflight-runtime-checks.json','preflight-source-probe.json','revision-target-checks.json'])if(JSON.parse(fs.readFileSync(out+'/diagnostic_support/'+f)).errors.length)throw Error('Preflight failed');
const pics=fs.readdirSync(out+'/diagnostic_support/preflight').filter(x=>x.endsWith('.png')).map(x=>({...id(out+'/diagnostic_support/preflight/'+x),viewed:'Actually opened with tools.view_image original after 1px vertical separation and before freeze',observation:x.includes('document-')?'Normal sentence flow, exact label, immediate period outside target, actual hover/inset focus, readable neighbor text.':x.includes('footer')?'Complete normal Footer; no focus/hover residual.':'Complete named native region/state, unchanged applicable content.'}));if(pics.length!==37)throw Error('Unexpected coverage');
fs.writeFileSync(out+'/approval_core/preflight-record.json',JSON.stringify({date:new Date().toISOString(),status:'AUTHOR_PREFLIGHT_PASS / INDEPENDENT_RECHECK_PENDING',dependencies,observations:pics,evidence:['preflight-runtime-checks.json','preflight-source-probe.json','revision-target-checks.json'].map(x=>id(out+'/diagnostic_support/'+x)),history:'V0.1 preserved failed. V0.2 attempt-01 zero-margin candidate preserved; 25-point pass did not catch mobile half-pixel adjacent target overlap; continuous1936-point check required1px vertical separation.'},null,2));
fs.writeFileSync(out+'/diagnostic_support/source-derivation.json',JSON.stringify({prior:id(prior+'/MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html'),candidate:id(target),htmlBytesEqual:true,cssPrior:id(prior+'/visual-direction.css'),cssCurrent:id(out+'/visual-direction.css'),onlyChange:'NL-04 ordinary paragraph links: margin8px ->1px 0; padding-inline3px; position:relative; outline-offset:-3px. Original vertical-align:middle retained. All labels/hrefs/punctuation unchanged.',authority:'Root targeted REV-01 instruction in thread after independent NL-G4-IR01; no other scope authorized.'},null,2));
fs.writeFileSync(out+'/approval_core/source-freeze.json',JSON.stringify({freezeId:'NL-G4-V02-SOURCE-01',date:new Date().toISOString(),status:'SOURCE_FROZEN_AFTER_AUTHOR_PREFLIGHT / DRAFT_FOR_PROJECT_CONTROL_REVIEW',entry:'MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.2.html',dependencies,inputs,preflight:id(out+'/approval_core/preflight-record.json'),scope:'REV-01/NL-G4-IR01 only. HTML bytes equal V0.1, new CSS and all newly captured PNG form V0.2 combination. Current root workflowV2.0/standardV1.2/governanceV1.1 override legacy flow references only. Old failed frozen combination preserved; no Gate5.'},null,2));console.log(JSON.stringify({freeze:id(out+'/approval_core/source-freeze.json'),dependencies:dependencies.slice(0,2),inputs:inputs.length}));
