const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const sharp=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='D:/23MySec/99_workspace/gate3-skill-validation-2026-09-07',cand=root+'/specimen-a',out=root+'/review-a/evidence';
const copy=JSON.parse(fs.readFileSync(root+'/copy.json')),manifest=JSON.parse(fs.readFileSync(cand+'/assets.json'));
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const result={source:{path:cand+'/source.html',bytes:fs.statSync(cand+'/source.html').size,sha256:hash(cand+'/source.html')},assets:[],viewports:[],interactions:{},network:[]};
async function snap(page,name){await page.screenshot({path:out+'/'+name+'.png',fullPage:true});}
async function geometry(page){return page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('a,button,input,select,textarea,summary')].filter(e=>e.checkVisibility()).map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,id:e.id,text:e.textContent.trim().slice(0,80),x:r.x,y:r.y+scrollY,width:r.width,height:r.height}}),overflow:[...document.querySelectorAll('body *')].filter(e=>e.checkVisibility()&&e.getBoundingClientRect().width>0&&e.scrollWidth>e.clientWidth+1).map(e=>({tag:e.tagName,id:e.id,cls:e.className,scroll:e.scrollWidth,client:e.clientWidth,overflow:getComputedStyle(e).overflow})),sections:[...document.querySelectorAll('main>section,footer')].map(e=>{const r=e.getBoundingClientRect();return {id:e.id||e.tagName,y:r.y+scrollY,height:r.height}})}));}
(async()=>{
for(const a of manifest.assets){const f=cand+'/'+a.path,m=await sharp(f).metadata();result.assets.push({...a,actualBytes:fs.statSync(f).size,actualSha256:hash(f),pixelWidth:m.width,pixelHeight:m.height,sourceHashMatches:a.sourceSha256===result.source.sha256});for(let y=0,i=0;y<m.height;y+=950,i++){await sharp(f).extract({left:0,top:y,width:m.width,height:Math.min(1100,m.height-y)}).png().toFile(out+'/'+a.path.replace('.png','')+'-part'+i+'.png');}}
const browser=await chromium.launch({headless:true});result.browser=browser.version();
for(const width of [1440,768,390]){
 const page=await browser.newPage({viewport:{width,height:900},deviceScaleFactor:1});await page.route('**/*',r=>{if(!r.request().url().startsWith('file:')){result.network.push(r.request().url());return r.abort();}return r.continue();});await page.goto('file:///'+cand+'/source.html');
 const initial=await geometry(page);await snap(page,width+'-runtime-initial');
 const rendered=await sharp(out+'/'+width+'-runtime-initial.png').raw().toBuffer({resolveWithObject:true}),supplied=await sharp(cand+'/'+width+'-initial.png').raw().toBuffer({resolveWithObject:true});
 const same=rendered.info.width===supplied.info.width&&rendered.info.height===supplied.info.height&&rendered.data.equals(supplied.data);
 const content=await page.evaluate(copy=>{const norm=s=>s.replace(/\s+/g,' ').trim(),txt=s=>norm(document.querySelector(s).textContent);return {hero:txt('h1')===copy.hero.title&&txt('#overview p')===copy.hero.text,records:[...document.querySelectorAll('.record')].map((el,i)=>({name:norm(el.querySelector('h3').textContent)===copy.records[i].name,metrics:[...el.querySelectorAll('dt')].map(e=>norm(e.textContent)),values:[...el.querySelectorAll('dd')].map(e=>norm(e.textContent)),note:norm(el.querySelector('.record-note').textContent)===copy.notes[i]})),reading:[...document.querySelectorAll('#reading>article,#reading>details')].map((el,i)=>({title:norm(el.querySelector('h3,summary').textContent)===copy.sections[i].title,text:norm(el.querySelector('p').textContent)===copy.sections[i].text,initialOpen:el.tagName==='ARTICLE'||el.open})),form:Object.fromEntries(['name','email','quantity','record','context'].map(id=>[id,txt('label[for="'+id+'"]')===copy.form[id]])),privacy:txt('.privacy-line')===norm(copy.form.privacyPrefix+copy.form.privacyLink+copy.form.privacySuffix),selectOptions:[...document.querySelector('#record').options].map(o=>o.textContent),links:[...document.querySelectorAll('a')].map(e=>({text:norm(e.textContent),href:e.getAttribute('href')}))}},copy);
 for(const s of await page.locator('details summary').all())await s.click();const expanded=await geometry(page);await snap(page,width+'-runtime-expanded');
 result.viewports.push({width,initial,content,pixelIdenticalInitial:same,renderedSize:rendered.info,suppliedSize:supplied.info,expanded});
 if(width===390){
  await page.locator('#menu').click();const entry=await page.evaluate(()=>({focus:document.activeElement.id,open:document.querySelector('dialog').open,aria:document.querySelector('#menu').getAttribute('aria-expanded')}));await snap(page,'390-runtime-menu');
  const tabs=[];for(let i=0;i<9;i++){await page.keyboard.press('Tab');tabs.push(await page.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.textContent.trim(),inDialog:!!document.activeElement.closest('dialog')})));}
  await page.locator('#close-menu').focus();await page.keyboard.press('Shift+Tab');const reverse=await page.evaluate(()=>({tag:document.activeElement.tagName,text:document.activeElement.textContent.trim(),inDialog:!!document.activeElement.closest('dialog')}));
  const bg=await page.evaluate(()=>{document.querySelector('#name').focus();return {focus:document.activeElement.id,inDialog:!!document.activeElement.closest('dialog')}});
  await page.keyboard.press('Escape');const escape=await page.evaluate(()=>({focus:document.activeElement.id,open:document.querySelector('dialog').open,aria:document.querySelector('#menu').getAttribute('aria-expanded')}));
  await page.locator('#menu').click();await page.locator('#close-menu').click();const close=await page.evaluate(()=>({focus:document.activeElement.id,open:document.querySelector('dialog').open}));
  await page.locator('#menu').click();await page.locator('#menu-dialog a[href="#comparison"]').click();const nav=await page.evaluate(()=>({hash:location.hash,open:document.querySelector('dialog').open,focus:document.activeElement.id}));
  result.interactions.menu={entry,tabs,reverse,bg,escape,close,nav};
  await page.locator('#submit').click();result.interactions.empty=await page.evaluate(()=>({focus:document.activeElement.id,summary:!document.querySelector('#form-summary').hidden,errors:['name','email','quantity'].map(id=>({id,shown:!document.querySelector('#'+id+'-error').hidden,describedBy:document.querySelector('#'+id).getAttribute('aria-describedby'),invalid:document.querySelector('#'+id).getAttribute('aria-invalid')}))}));
  await page.locator('#name').fill('Example Reader');await page.locator('#email').fill('invalid');await page.locator('#quantity').fill('0');await page.locator('#context').fill('Line one\nLine two with retained example context.');await page.locator('#record').selectOption({label:copy.records[1].name});await page.locator('#submit').click();await snap(page,'390-runtime-invalid');await page.locator('form').screenshot({path:out+'/invalid-form.png'});result.interactions.invalid=await page.evaluate(()=>({focus:document.activeElement.id,values:[...document.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,value:e.value})),quantityError:document.querySelector('#quantity-error').textContent,summary:document.querySelector('#form-summary').textContent}));
  await page.locator('#email').fill('reader@example.invalid');await page.locator('#quantity').fill('0.001');await page.locator('#submit').click();await page.locator('form').screenshot({path:out+'/positive-small-quantity.png'});result.interactions.smallPositive=await page.evaluate(()=>({value:document.querySelector('#quantity').value,min:document.querySelector('#quantity').min,rangeUnderflow:document.querySelector('#quantity').validity.rangeUnderflow,errorShown:!document.querySelector('#quantity-error').hidden,confirmation:!document.querySelector('#confirmation').hidden,focus:document.activeElement.id}));
  await page.locator('#quantity').fill('1.25');await page.locator('#submit').click();await snap(page,'390-runtime-success');await page.locator('form').screenshot({path:out+'/success-form.png'});result.interactions.success=await page.evaluate(()=>({visible:!document.querySelector('#confirmation').hidden,text:document.querySelector('#confirmation').textContent,summaryHidden:document.querySelector('#form-summary').hidden,values:[...document.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,value:e.value}))}));
  await page.locator('#record').selectOption({label:copy.form.unsure});result.interactions.resetSelection=await page.locator('#record').inputValue();
 }
 await page.close();
}
await browser.close();fs.writeFileSync(out+'/audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify({source:result.source,assets:result.assets.map(a=>({path:a.path,bytesMatch:a.bytes===a.actualBytes,hashMatch:a.sha256===a.actualSha256,sourceHashMatches:a.sourceHashMatches,width:a.pixelWidth,height:a.pixelHeight})),viewports:result.viewports.map(v=>({width:v.width,pixelIdenticalInitial:v.pixelIdenticalInitial,overflow:v.initial.overflow,undersized:v.initial.targets.filter(t=>t.width<44||t.height<44)})),interactions:result.interactions},null,2));
})();
