const fs=require('fs');const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const sharp=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='D:/23MySec/99_workspace/gate3-skill-validation-2026-09-07',out=root+'/review-a/evidence',url='file:///'+root+'/specimen-a/source.html';
(async()=>{const b=await chromium.launch({headless:true});const result={menus:[],states:[],prefixPixels:{}};
for(const width of [390,768]){const p=await b.newPage({viewport:{width,height:900}});await p.goto(url);await p.locator('#menu').focus();await p.keyboard.press('Enter');const state=()=>p.evaluate(()=>({tag:document.activeElement.tagName,id:document.activeElement.id,text:document.activeElement.tagName==='BODY'?'BODY':document.activeElement.textContent.trim(),documentHasFocus:document.hasFocus(),inDialog:!!document.activeElement.closest('dialog'),open:document.querySelector('dialog').open}));const entry=await state();const backgroundAttempt=await p.evaluate(()=>{document.querySelector('#name').focus();return {id:document.activeElement.id,tag:document.activeElement.tagName}});const cycle=[];for(let i=0;i<8;i++){await p.keyboard.press('Tab');cycle.push(await state())}await p.keyboard.press('Escape');const escape=await state();await p.locator('details summary').first().focus();await p.keyboard.press('Enter');const keyboardOpen=await p.locator('details').first().getAttribute('open');await p.keyboard.press('Space');const keyboardClosed=await p.locator('details').first().getAttribute('open');
result.menus.push({width,entry,backgroundAttempt,cycle,escape,keyboardOpen,keyboardClosed});await p.close();}
const copy=JSON.parse(fs.readFileSync(root+'/copy.json'));const p=await b.newPage({viewport:{width:390,height:900}});await p.goto(url);const selectors={'comparisonTitle':'#comparison h2','readingTitle':'#reading h2','form.title':'#request h2','form.intro':'#request>p','form.submit':'#submit','form.errorSummary':'#form-summary','form.nameError':'#name-error','form.emailError':'#email-error','form.quantityError':'#quantity-error','form.success':'#confirmation','privacy.title':'#privacy h2','privacy.text':'#privacy p'};result.copyChecks=[];for(const [key,sel]of Object.entries(selectors)){const expected=key.split('.').reduce((a,k)=>a[k],copy),actual=await p.locator(sel).textContent();result.copyChecks.push({key,match:expected===actual})}
for(const s of await p.locator('details summary').all())await s.click();await p.screenshot({path:out+'/recreated-expanded.png',fullPage:true});await p.locator('#submit').click();await p.screenshot({path:out+'/recreated-invalid.png',fullPage:true});await p.locator('#name').fill('Example Person');await p.locator('#email').fill('example@example.invalid');await p.locator('#quantity').fill('0.5');await p.locator('#submit').click();await p.screenshot({path:out+'/recreated-success.png',fullPage:true});
for(const s of ['expanded','invalid','success']){const a=await sharp(root+'/specimen-a/390-'+s+'.png').raw().toBuffer({resolveWithObject:true}),c=await sharp(out+'/recreated-'+s+'.png').raw().toBuffer({resolveWithObject:true});result.states.push({state:s,sameSize:a.info.width===c.info.width&&a.info.height===c.info.height,pixelIdentical:a.data.equals(c.data)});}
for(const s of ['invalid','success']){const a=await sharp(root+'/specimen-a/390-'+s+'.png').extract({left:0,top:0,width:390,height:6650}).raw().toBuffer(),c=await sharp(root+'/specimen-a/390-expanded.png').extract({left:0,top:0,width:390,height:6650}).raw().toBuffer();result.prefixPixels[s]={height:6650,identical:a.equals(c)}}
result.finalGeometry=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,width:innerWidth,visibleClippingStyles:[...document.querySelectorAll('body *')].filter(e=>e.checkVisibility()&&['hidden','clip'].includes(getComputedStyle(e).overflow)).map(e=>e.tagName+'#'+e.id),selectedLabel:document.querySelector('select').value}));await b.close();fs.writeFileSync(out+'/supplement.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})();
