const fs=require('fs'),path=require('path'),crypto=require('crypto');
const sharp=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const d=__dirname,read=n=>JSON.parse(fs.readFileSync(path.join(d,n))),id=p=>{const b=fs.readFileSync(p);return {path:p.replaceAll('\\','/'),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}},write=(n,v)=>fs.writeFileSync(path.join(d,n),JSON.stringify(v,null,2));
(async()=>{
const i=read('APP-PAPER_GATE4_INPUT_INDEX_V0.1.json'),pre=read('APP-PAPER_GATE4_PREFLIGHT_V0.1.json'),formal=read('APP-PAPER_GATE4_FORMAL_OBSERVATIONS_V0.1.json'),initial=read('APP-PAPER_GATE4_INITIAL_OBSERVATIONS_V0.1.json'),checks=[];
function check(name,pass,observed){checks.push({name,pass,observed});}
for(const item of [...i.inputs,...i.dependencies]){const a=id(item.path);check('input_identity:'+item.path,a.sha256===item.sha256&&a.bytes===item.bytes,a);}
check('source_lock',id(i.design_source).sha256===pre.source_identity.sha256&&pre.source_identity.sha256===formal.source_identity.sha256);
check('chronology',pre.recorded_at<formal.started_at&&formal.started_at<formal.completed_at,{preflight:pre.recorded_at,capture_started:formal.started_at,capture_finished:formal.completed_at});
for(const img of formal.images){const a=id(img.path),m=await sharp(img.path).metadata();check('png_identity:'+path.basename(img.path),a.bytes===img.bytes&&a.sha256===img.sha256&&m.width===img.physical.width&&m.height===img.physical.height&&img.dpr===1&&m.width===img.logical_viewport.width&&img.source_sha256===pre.source_identity.sha256,{...a,width:m.width,height:m.height,dpr:img.dpr});if(!img.full_page)check('state_extent:'+path.basename(img.path),m.height===img.logical_viewport.height);}
for(const width of [1440,768,390]){const img=formal.images.find(x=>x.state==='FULL'&&x.logical_viewport.width===width);check('full_source_and_readable_coverage_'+width,img.sha256===initial.images.find(x=>x.state==='FULL'&&x.logical_viewport.width===width).sha256&&img.physical.height===initial.viewports.find(x=>x.width===width).height);}
check('source_grade3_main_markup',fs.readFileSync(i.design_source,'utf8').match(/<main[\s\S]*?<\/main>/)[0]===fs.readFileSync('D:/23MySec/pages/applications/paper/04_planning/gate3-v0.3/APP-PAPER_GATE3_RESPONSIVE_WIREFRAME_V0.3.html','utf8').match(/<main[\s\S]*?<\/main>/)[0]);
check('approved_B_identity',i.inputs.find(x=>x.path.endsWith('APP-PAPER_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md')).sha256==='14a77a04347e78b7ad080cd9d8b7f6251692450380216506e6e0745724012542');
const audit={mode:'CAPTURE_CHECK_AND_MACHINE_IDENTITY',created_at:new Date().toISOString(),workset_id:i.workset_id,source_identity:id(i.design_source),checks,count:checks.length,failures:checks.filter(x=>!x.pass),pass:checks.every(x=>x.pass),formal_images_opened:11,full_readable_coverage:'Eight original-DPR lossless reading panels viewed during INITIAL; formal full images byte-identical and separately opened.',overlay_capture_note:'Formal states opened by pointer; initial states after keyboard operations show focus-visible rings. Both inspected; source unchanged.',tool:'Node filesystem+crypto and sharp PNG metadata; actual Edge DPR supplied by formal run'};
write('APP-PAPER_GATE4_CAPTURE_MACHINE_AUDIT_V0.1.json',audit);if(!audit.pass)throw Error(JSON.stringify(audit.failures));
const coreNames=['APP-PAPER_GATE4_INPUT_INDEX_V0.1.json','APP-PAPER_GATE4_COMPLETE_VISUAL_V0.1.html','APP-PAPER_GATE4_WORKSET_AND_VISUAL_RULES_V0.1.md','APP-PAPER_GATE4_PREFLIGHT_V0.1.json','APP-PAPER_GATE4_FORMAL_OBSERVATIONS_V0.1.json','APP-PAPER_GATE4_CAPTURE_MACHINE_AUDIT_V0.1.json'];
const diagNames=['APP-PAPER_GATE4_INITIAL_OBSERVATIONS_V0.1.json','APP-PAPER_GATE4_TARGETED_OBSERVATIONS_V0.1.json','APP-PAPER_GATE4_BUILD_V0.1.cjs','APP-PAPER_GATE4_VERIFY_CAPTURE_V0.1.cjs','APP-PAPER_GATE4_TARGETED_VERIFY_V0.1.cjs','APP-PAPER_GATE4_FINALIZE_V0.1.cjs'];
const self=path.resolve(d,'../../05_review/APP-PAPER_GATE4_EXECUTION_SELF_CHECK_V0.1.md');
const evidence={page_id:'APP-PAPER',workset_id:i.workset_id,freeze_id:'APP-PAPER-G4-FREEZE-V0.1',source_identity:id(i.design_source),approval_core:[...coreNames.map(n=>id(path.join(d,n))),id(self),...formal.images],diagnostic_support:[...diagNames.map(n=>id(path.join(d,n))),...fs.readdirSync(path.join(d,'diagnostic_support')).map(n=>id(path.join(d,'diagnostic_support',n)))],dependencies:i.dependencies,reader_entry:'APP-PAPER_GATE4_COMPLETE_VISUAL_V0.1.html; formal FULL PNGs; diagnostic READ_PANEL_1440_1-4,768_1-2,390_1-2 are consecutive vertical slices tiled only for reading, not page designs.',evidence_categories:{images:'STATIC_VISUAL',initial_and_targeted:'ACTUAL_RUNTIME with separately noted SOURCE_INSPECTION and 720px reflow proxy',external_navigation:'LOCAL_BOUNDARY_ONLY: one menu navigation was prevented locally to inspect close behavior; no receiver tested'},required_findings:[],created_at:new Date().toISOString()};
write('APP-PAPER_GATE4_EVIDENCE_INDEX_V0.1.json',evidence);
const freeze={page_id:'APP-PAPER',workset_id:i.workset_id,freeze_id:'APP-PAPER-G4-FREEZE-V0.1',bundle_id:'APP-PAPER-G4-BUNDLE-V0.1',status:'GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW',technical_status:'COMPLETE_VISUAL_FROZEN / READY_FOR_REVIEW',lifecycle_mapping:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',review_stage:'GATE5_INDEPENDENT_VISUAL_REVIEW',actual_author:i.actual_author,dispatch_id:i.dispatch_id,authorization_snapshot:id(path.join(d,'G4_REMAINING_8_EXEC_01_AUTHORIZATION_SNAPSHOT_V0.1.md')),source_identity:id(i.design_source),input_index:id(path.join(d,'APP-PAPER_GATE4_INPUT_INDEX_V0.1.json')),evidence_index:id(path.join(d,'APP-PAPER_GATE4_EVIDENCE_INDEX_V0.1.json')),preflight:id(path.join(d,'APP-PAPER_GATE4_PREFLIGHT_V0.1.json')),capture_machine_audit:id(path.join(d,'APP-PAPER_GATE4_CAPTURE_MACHINE_AUDIT_V0.1.json')),self_check:id(self),dependencies:i.dependencies,render_conditions:pre.render_conditions,effective_self_check_assertions:101,executed_assertions:105,machine_checks:audit.count,formal_pngs:11,required_findings:[],frozen_at:new Date().toISOString(),stop:'No independent review, closure, Gate6, development or publication'};
write('APP-PAPER_GATE4_FREEZE_RECORD_V0.1.json',freeze);
const finalChecks=[];for(const x of [freeze.source_identity,freeze.input_index,freeze.evidence_index,freeze.preflight,freeze.capture_machine_audit,freeze.self_check,...evidence.approval_core,...evidence.diagnostic_support,...evidence.dependencies]){const a=id(x.path);finalChecks.push({path:x.path,pass:a.bytes===x.bytes&&a.sha256===x.sha256});}
const receipt={created_at:new Date().toISOString(),freeze_identity:id(path.join(d,'APP-PAPER_GATE4_FREEZE_RECORD_V0.1.json')),count:finalChecks.length,failures:finalChecks.filter(x=>!x.pass),pass:finalChecks.every(x=>x.pass),checks:finalChecks};write('APP-PAPER_GATE4_FINAL_IDENTITY_AUDIT_V0.1.json',receipt);console.log(JSON.stringify({capture_checks:audit.count,final_identity_checks:receipt.count,pass:receipt.pass,freeze:receipt.freeze_identity}));
})();
