const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,source=path.join(dir,'APP-PAPER_GATE4_COMPLETE_VISUAL_V0.1.html');
const results={mode:'TARGETED',author:'/root/gate4_paper_execute',started_at:new Date().toISOString(),source_sha256:crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),reason:'Correct two validation expectations, supplement overlay target geometry and actual page hover/focus coverage. No design source changes; initial 86 valid checks retained.',checks:[]};
const check=(name,pass,observed)=>results.checks.push({name,pass,observed});
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});await page.goto(pathToFileURL(source).href);await page.evaluate(()=>document.fonts.ready);
const font=await page.evaluate(()=>Math.min(...[...document.querySelectorAll('main p:not(.heroActions p),main li,main td,main a')].map(e=>parseFloat(getComputedStyle(e).fontSize))));check(width+'_readable_font_corrected',font>=14,font);
await page.locator('.heroActions a').first().hover();check(width+'_hero_hover',await page.locator('.heroActions a').first().evaluate(e=>getComputedStyle(e).backgroundColor==='rgb(0, 100, 94)'));await page.mouse.move(width-1,0);await page.locator('.heroActions a').first().focus();check(width+'_hero_focus',await page.locator('.heroActions a').first().evaluate(e=>getComputedStyle(e).outlineWidth==='3px'&&getComputedStyle(e).outlineColor==='rgb(255, 255, 255)'));
if(width!==1440){await page.locator('.menuButton').click();const small=await page.locator('.mobileNav a,.menuButton').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width<44||r.height<44}).map(e=>e.textContent));check(width+'_menu44',!small.length,small);await page.keyboard.press('Escape');}
await page.locator('#cookie-trigger').click();const small=await page.locator('.cookie-actions>*').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width<44||r.height<44}).map(e=>e.textContent));check(width+'_cookie44',!small.length,small);await page.close();}
const nojs=await browser.newPage({viewport:{width:390,height:844},javaScriptEnabled:false});await nojs.goto(pathToFileURL(source).href);const counts={modules:await nojs.locator('main section').count(),links:await nojs.locator('main a').count()};check('nojs_core_content_corrected',counts.modules===11&&counts.links===15,counts);await nojs.close();await browser.close();results.pass=results.checks.every(c=>c.pass);results.completed_at=new Date().toISOString();fs.writeFileSync(path.join(dir,'APP-PAPER_GATE4_TARGETED_OBSERVATIONS_V0.1.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({checks:results.checks.length,failures:results.checks.filter(c=>!c.pass)}));})();
