const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec/99_workspace/gate4-method-validation-2026-09-07',src=root+'/design-v1',out=root+'/review-a';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const inventory=JSON.parse(fs.readFileSync(src+'/asset-inventory.json','utf8'));
const files=['index.html','styles.css','app.js','assets/Inter-Variable.ttf',...fs.readdirSync(src+'/exports').map(x=>'exports/'+x)];
const identities=files.map(p=>{const b=fs.readFileSync(src+'/'+p),a=inventory.assets.find(a=>a.path===p);return{path:p,bytes:b.length,sha256:sha(b),inventoryMatches:a&&a.sha256===sha(b)&&a.bytes===b.length,...(p.endsWith('.png')?{width:b.readUInt32BE(16),height:b.readUInt32BE(20)}:{})}});
const question='How should I interpret the measurement condition for this reference?';
const obs=[];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});
for(const width of [1440,768,390]){const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1});const blocked=[];await context.route('**/*',route=>/^https?:/.test(route.request().url())?(blocked.push(route.request().url()),route.abort()):route.continue());const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file:///'+src+'/index.html');await p.evaluate(()=>document.fonts.ready);
async function snapshot(state,region='request'){const d=await p.evaluate(()=>{const get=s=>document.querySelector(s),box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}},shown=e=>!!(e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden');return{scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,fontLoaded:document.fonts.check('16px Inter'),fontFaces:[...document.fonts].map(f=>({family:f.family,status:f.status})),active:document.activeElement.id||document.activeElement.textContent,record:get('#record-value').textContent,question:get('#question').value,errorVisible:shown(get('#record-error')),error:get('#record-error').textContent,resultVisible:shown(get('#result')),result:get('#result').innerText,selectedName:get('#selected-name').textContent,listOpen:shown(get('#record-options')),selected:[...document.querySelectorAll('[aria-selected=true]')].map(e=>e.dataset.value),controls:[...document.querySelectorAll('a,button,textarea')].filter(shown).map(e=>({text:e.textContent,id:e.id,...box(e),font:getComputedStyle(e).fontSize,outline:getComputedStyle(e).outline,fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor,border:getComputedStyle(e).borderColor})),figureVisible:shown(get('#illustration')),orientationCopy:box(get('.orientation-copy')),content:get('main').innerText};});obs.push({width,state,...d});await p.locator('#'+region).screenshot({path:out+'/'+width+'-'+region+'-'+state+'.png'});return d}
await snapshot('initial','orientation');await snapshot('initial','comparison');await snapshot('initial');
await p.locator('a[href="#comparison"]').click();obs.push({width,state:'comparison-anchor',hash:await p.evaluate(()=>location.hash)});await p.locator('a[href="#request"]').click();obs.push({width,state:'request-anchor',hash:await p.evaluate(()=>location.hash)});
await p.locator('#question').fill(question);await p.locator('button[type=submit]').focus();await p.keyboard.press('Enter');await snapshot('missing-record-focus');
await p.keyboard.press('ArrowDown');await p.keyboard.press('ArrowDown');await snapshot('list-open-beta-focus');await p.keyboard.press('Enter');await snapshot('beta-selected');
await p.keyboard.press('Tab');obs.push({width,state:'tab-from-record',active:await p.evaluate(()=>document.activeElement.id)});await p.keyboard.press('Tab');await p.keyboard.press('Enter');await snapshot('beta-success');
await p.locator('#record').click();await p.locator('[data-value=gamma]').click();await snapshot('changed-gamma');await p.locator('button[type=submit]').click();await p.locator('#clear').click();await snapshot('cleared-success');
await p.locator('button[type=submit]').click();await p.locator('#clear').click();await snapshot('cleared-error');
await p.locator('#record').focus();await p.keyboard.press('End');await p.keyboard.press('Home');obs.push({width,state:'home-option',active:await p.evaluate(()=>document.activeElement.dataset.value)});await p.keyboard.press('End');obs.push({width,state:'end-option',active:await p.evaluate(()=>document.activeElement.dataset.value)});await p.keyboard.press('Escape');obs.push({width,state:'escape',active:await p.evaluate(()=>document.activeElement.id),hidden:await p.locator('#record-options').isHidden()});
await p.keyboard.press('Space');await p.keyboard.press('Tab');obs.push({width,state:'tab-dismiss',active:await p.evaluate(()=>document.activeElement.id),hidden:await p.locator('#record-options').isHidden()});
await p.locator('#record').click();await p.locator('[data-value=alpha]').click();await p.locator('#question').fill('');await p.locator('button[type=submit]').click();await snapshot('optional-question');
await p.goto('file:///'+src+'/index.html?media=absent');await p.evaluate(()=>document.fonts.ready);await snapshot('media-absent','orientation');obs.push({width,blocked,errors});await context.close();}
const lum=c=>{const v=c.match(/\w\w/g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return v[0]*.2126+v[1]*.7152+v[2]*.0722},ratio=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
fs.writeFileSync(out+'/observations.json',JSON.stringify({renderer:await browser.version(),identities,observations:obs,contrast:[['008078','FFFFFF'],['008078','F5F8FB'],['062B5B','FFFFFF'],['334155','FFFFFF'],['334155','F5F8FB'],['8C2532','FFFFFF']].map(([a,b])=>({a,b,ratio:ratio(a,b)}))},null,2));await browser.close();console.log(JSON.stringify({images:fs.readdirSync(out).filter(p=>p.endsWith('.png')).length,assets:identities.length,mismatches:identities.filter(x=>!x.inventoryMatches)}));})().catch(e=>{console.error(e);process.exit(1)});
