const fs=require('fs'),path=require('path'),crypto=require('crypto');
const deps='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {chromium}=require(deps+'playwright'),sharp=require(deps+'sharp'),{marked}=require(deps+'marked');
const root='D:/23MySec',pageRoot=root+'/pages/applications/printing-inks',base=pageRoot+'/04_planning/gate4-v0.1',out=__dirname;
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const identity=p=>{let b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:sha(b)}};
const freeze=read(base+'/APP-INK_GATE4_FREEZE_RECORD_V0.1.json'),inputs=read(freeze.input_index.path),ev=read(freeze.evidence_index.path);
const results={page_id:'APP-INK',dispatch_id:'G5-9PAGE-REVIEW-20260907-01/APP-INK/INITIAL',author:'/root/gate4_printing_inks_execute',reviewer:'/root/g5_inks',mode:'INDEPENDENT_REVIEW',review_scope:'INITIAL',at:new Date().toISOString(),freeze_id:freeze.freeze_id,bundle_id:freeze.bundle_id,source:identity(freeze.source_identity.path),identities:[],runtime:[],temporary_crops:[],persistent_screenshots:0};
function audit(obj,origin){if(!obj||typeof obj!=='object')return;if(obj.path&&obj.sha256){let actual;try{actual=identity(obj.path)}catch(e){actual={error:String(e)}}results.identities.push({origin,expected:obj,actual,match:actual.sha256===obj.sha256.toLowerCase()&&(obj.bytes===undefined||obj.bytes===actual.bytes)});}for(const [k,v]of Object.entries(obj))if(v&&typeof v==='object')audit(v,origin+'/'+k)}
audit(freeze,'freeze');audit(inputs,'inputs');audit(ev,'evidence');
results.bundle_recomputed=sha([freeze.source_identity.sha256,freeze.input_index.sha256,freeze.evidence_index.sha256,...freeze.dependencies.map(x=>x.sha256)].join('|'));
results.methods=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.9.md'].map(p=>identity(root+'/'+p));
async function main(){
 for(const e of ev.approval_core){const m=await sharp(e.path).metadata();results.identities.push({origin:'PNG',path:e.path,expected:e.physical,actual:{width:m.width,height:m.height},match:e.physical.width===m.width&&e.physical.height===m.height});if(e.state==='FULL'){fs.mkdirSync(out+'/read-cache',{recursive:true});let step=e.physical.width===1440?1550:1650;for(let y=0;y<m.height;y+=step){let height=Math.min(step+120,m.height-y),p=out+'/read-cache/'+e.logical_viewport.width+'-'+y+'.png';await sharp(e.path).extract({left:0,top:y,width:m.width,height}).toFile(p);results.temporary_crops.push({path:p,original:e.path,y,height,evidence_type:'STATIC_VISUAL',purpose:'Temporary native-scale reading crop, not new capture'});}}}
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});results.browser=browser.version();
 const copy=fs.readFileSync(pageRoot+'/04_planning/APP-INK_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').split('<!-- BUYER_COPY_START -->')[1].split('<!-- BUYER_COPY_END -->')[0];
 for(const [w,h]of [[1440,1000],[768,1024],[390,844]]){
  const ctx=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto('file:///'+freeze.source_identity.path);await p.evaluate(()=>document.fonts.ready);
  const r={width:w,height:h,evidence_type:'ACTUAL_RUNTIME',errors,geometry:await p.evaluate(()=>{const rect=e=>{let r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};const visible=e=>!!e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden';return {dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,scrollHeight:document.documentElement.scrollHeight,font:[...document.fonts].map(x=>({family:x.family,status:x.status})),header:rect(document.querySelector('header')),modules:[...document.querySelectorAll('[data-module]')].map(e=>({id:e.dataset.module,...rect(e)})),targets:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.innerText,...rect(e)})),clipped:[...document.querySelectorAll('main p,main li,main td,main a,main h1,main h2,.requestCard')].filter(visible).filter(e=>e.scrollWidth>e.clientWidth+1||e.scrollHeight>e.clientHeight+1).map(e=>({tag:e.tagName,text:e.innerText,overflow:getComputedStyle(e).overflow,...rect(e)})),records:[...document.querySelectorAll('.documents-matrix tbody tr')].map(e=>[...e.cells].map(c=>({label:c.dataset.label,text:c.innerText}))),grades:[...document.querySelectorAll('.grades tbody tr')].map(e=>({text:e.innerText,...rect(e)})),request:[...document.querySelectorAll('.requestCard')].map(e=>({text:e.innerText,...rect(e)})),bodyLinks:[...document.querySelectorAll('main a')].map(e=>({text:e.innerText,href:e.getAttribute('href')})),forms:document.querySelectorAll('form,input,select,textarea').length,footer:rect(document.querySelector('footer')),headingCount:document.querySelectorAll('h1').length}})};
  r.copy=await p.evaluate(html=>{const d=document.createElement('div');d.innerHTML=html;const actual=document.querySelector('main').cloneNode(true);actual.querySelector('.breadcrumb').remove();actual.querySelector('.eyebrow').remove();const norm=s=>s.replace(/\s/g,'');return {match:norm(d.textContent)===norm(actual.textContent),expectedCharacters:norm(d.textContent).length,actualCharacters:norm(actual.textContent).length,links:[...d.querySelectorAll('a')].map(a=>({text:a.textContent,href:a.getAttribute('href')}))}},marked.parse(copy));
  r.anchors=[];for(const s of ['.primaryAction','.secondaryAction']){await p.locator(s).click();await p.waitForTimeout(350);r.anchors.push(await p.evaluate(sel=>{const id=document.querySelector(sel).hash;return {selector:sel,hash:location.hash,targetTop:document.querySelector(id).getBoundingClientRect().top}},s));}
  await p.goto('file:///'+freeze.source_identity.path);await p.evaluate(()=>document.fonts.ready);r.bodyFocus=[];const count=await p.locator('main a').count();for(let i=0;i<100&&r.bodyFocus.length<count;i++){await p.keyboard.press('Tab');const f=await p.evaluate(()=>{const e=document.activeElement;return e.matches('main a')?{text:e.innerText,href:e.getAttribute('href'),focusVisible:e.matches(':focus-visible'),outline:getComputedStyle(e).outline}:null});if(f&&!r.bodyFocus.some(x=>x.href===f.href&&x.text===f.text))r.bodyFocus.push(f);}
  const focus=()=>p.evaluate(()=>({text:document.activeElement.innerText,tag:document.activeElement.tagName,focusVisible:document.activeElement.matches(':focus-visible')}));
  if(w<1101){r.menu={};await p.locator('.menuButton').click();r.menu.initial=await focus();await p.keyboard.press('Shift+Tab');r.menu.toToggle=await focus();await p.keyboard.press('Shift+Tab');r.menu.backwardWrap=await focus();await p.keyboard.press('Tab');r.menu.forwardWrap=await focus();r.menu.isolation=await p.evaluate(()=>{document.querySelector('main a').focus();return {mainInert:document.querySelector('main').inert,footerInert:document.querySelector('footer').inert,activeInBackground:!!document.activeElement.closest('main,footer'),overflow:document.body.style.overflow}});await p.keyboard.press('Escape');r.menu.escape=await p.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),focus:document.activeElement.className,mainInert:document.querySelector('main').inert,overflow:document.body.style.overflow}));await p.locator('.menuButton').click();await p.evaluate(()=>document.querySelector('.mobileNav').addEventListener('click',e=>e.preventDefault(),{once:true}));await p.locator('.mobileNav a[href="/applications/"]').click();r.menu.selection=await p.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,focus:document.activeElement.className}));r.menu.selection_evidence_type='LOCAL_SIMULATION: navigation default prevented only; actual menu close handler ran';await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:1000});r.menu.breakpoint=await p.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,mainInert:document.querySelector('main').inert,overflow:document.body.style.overflow}));await p.setViewportSize({width:w,height:h});}
  r.cookie={};await p.locator('#cookie-trigger').click();r.cookie.initial=await focus();await p.keyboard.press('Shift+Tab');r.cookie.backwardWrap=await focus();await p.keyboard.press('Tab');r.cookie.forwardWrap=await focus();r.cookie.isolation=await p.evaluate(()=>{document.querySelector('main a').focus();return !!document.activeElement.closest('main,footer')});r.cookie.geometry=await p.locator('.cookie-layer').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight}});await p.keyboard.press('Escape');r.cookie.escape=await p.evaluate(()=>({open:document.querySelector('dialog').open,focus:document.activeElement.id}));await p.locator('#cookie-trigger').click();await p.locator('[data-cookie-close]').click();r.cookie.click=await p.evaluate(()=>({open:document.querySelector('dialog').open,focus:document.activeElement.id}));
  r.styles={};for(const s of ['.primaryAction','.secondaryAction','.sources a','.headerRfq','.footerRfq']){await p.locator(s).first().hover();r.styles[s]=await p.locator(s).first().evaluate(e=>{const c=getComputedStyle(e);return {color:c.color,background:c.backgroundColor,outline:c.outline,font:c.fontFamily,fontSize:c.fontSize,lineHeight:c.lineHeight}})}
  r.scroll=[];for(let y=0;y<r.geometry.scrollHeight;y+=h-100){await p.evaluate(y=>scrollTo(0,y),y);r.scroll.push(await p.evaluate(()=>({y:scrollY,bottom:scrollY+innerHeight,modules:[...document.querySelectorAll('[data-module]')].filter(e=>{const r=e.getBoundingClientRect();return r.top<innerHeight&&r.bottom>0}).map(e=>e.dataset.module)})))}
  await p.emulateMedia({reducedMotion:'reduce'});r.reducedMotion=await p.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior);results.runtime.push(r);await ctx.close();
 }
 const nojs=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:false});const np=await nojs.newPage();await np.goto('file:///'+freeze.source_identity.path);results.nojs={modules:await np.locator('[data-module]').count(),links:await np.locator('main a').count(),textLength:(await np.locator('main').innerText()).length};await nojs.close();await browser.close();
 fs.writeFileSync(out+'/observations.json',JSON.stringify(results,null,2));console.log(JSON.stringify({identityClaims:results.identities.length,mismatches:results.identities.filter(x=>!x.match),bundleMatch:results.bundle_recomputed===freeze.bundle_sha256,viewports:results.runtime.map(r=>({width:r.width,copy:r.copy.match,links:r.bodyFocus.length,small:r.geometry.targets.filter(t=>t.width<43.99||t.height<43.99),clipped:r.geometry.clipped,errors:r.errors})),crops:results.temporary_crops.map(x=>x.path)},null,2));
}
main().catch(e=>{fs.writeFileSync(out+'/failed-run.json',JSON.stringify({error:e.stack,partial:results},null,2));console.error(e);process.exitCode=1});
