const fs=require('fs'),crypto=require('crypto');const deps='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';const {chromium}=require(deps+'playwright');
const root='D:/23MySec',pageRoot=root+'/pages/applications/printing-inks',src=pageRoot+'/04_planning/gate4-v0.1/APP-INK_GATE4_COMPLETE_VISUAL_V0.1.html',out=__dirname;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const result={reason:'Resolve initial 350 ms anchor observations taken before smooth-scroll completion; complete keyboard activation, active-state and shared-byte checks. No page change.',source_sha256:sha(fs.readFileSync(src)),evidence_type:'ACTUAL_RUNTIME',viewports:[]};for(const [w,h] of [[1440,1000],[768,1024],[390,844]]){const c=await b.newContext({viewport:{width:w,height:h},deviceScaleFactor:1}),p=await c.newPage();await p.goto('file:///'+src);await p.evaluate(()=>document.fonts.ready);let r={width:w,anchors:[]};for(const s of ['.primaryAction','.secondaryAction']){await p.locator(s).click();await p.waitForFunction(sel=>Math.abs(document.querySelector(document.querySelector(sel).hash).getBoundingClientRect().top-20)<2,s,{timeout:10000});r.anchors.push(await p.evaluate(sel=>({selector:sel,hash:location.hash,top:document.querySelector(document.querySelector(sel).hash).getBoundingClientRect().top}),s));}
 if(w<1101){await p.locator('.menuButton').focus();await p.keyboard.press('Enter');r.keyboardMenu=await p.evaluate(()=>({active:document.activeElement.innerText,focusVisible:document.activeElement.matches(':focus-visible'),current:[...document.querySelectorAll('.mobileNav [aria-current]')].map(e=>e.innerText),targets:[...document.querySelectorAll('.mobileNav a')].map(e=>{let r=e.getBoundingClientRect();return {text:e.innerText,width:r.width,height:r.height}})}));await p.locator('.menuButton').click();r.menuClickExit=await p.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,focus:document.activeElement.className,mainInert:document.querySelector('main').inert}));}else r.desktopCurrent=await p.locator('.desktopNav [aria-current]').innerText();
 await p.locator('#cookie-trigger').focus();await p.keyboard.press('Enter');r.keyboardCookie=await p.evaluate(()=>({active:document.activeElement.innerText,focusVisible:document.activeElement.matches(':focus-visible'),targets:[...document.querySelectorAll('.cookie-actions>*')].map(e=>{let r=e.getBoundingClientRect();return {text:e.innerText,width:r.width,height:r.height}})}));await p.keyboard.press('Escape');r.heading=await p.locator('h1').evaluate(e=>{const r=e.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(e);return {box:{width:r.width,height:r.height},textRects:[...range.getClientRects()].map(r=>({width:r.width,height:r.height})),overflow:getComputedStyle(e).overflow}});
 r.defaultStyles=await p.evaluate(()=>{let selectors=['.primaryAction','.secondaryAction','.breadcrumb a','.eyebrow','.sources a','.documents-matrix td::before','.grades td::before'];return selectors.map(sel=>{let parts=sel.split('::'),e=document.querySelector(parts[0]),s=getComputedStyle(e,parts[1]?'::'+parts[1]:null);return {selector:sel,color:s.color,background:s.backgroundColor,fontSize:s.fontSize}})});
 r.settledScroll=[];await p.emulateMedia({reducedMotion:'reduce'});let height=await p.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<height;y+=h-100){await p.evaluate(y=>scrollTo(0,y),y);await p.waitForTimeout(25);r.settledScroll.push(await p.evaluate(()=>({top:scrollY,bottom:scrollY+innerHeight})));}result.viewports.push(r);await c.close();}
 const html=fs.readFileSync(src,'utf8'),g3=fs.readFileSync(pageRoot+'/04_planning/gate3-v0.2/APP-INK_GATE3_RESPONSIVE_WIREFRAME_V0.2.html','utf8');result.shared={header:html.match(/<header[\s\S]*?<\/header>/)[0]===g3.match(/<header[\s\S]*?<\/header>/)[0],footer:html.match(/<footer[\s\S]*?<\/footer>/)[0]===g3.match(/<footer[\s\S]*?<\/footer>/)[0],behavior:html.match(/<script>[\s\S]*?<\/script>/)[0]===g3.match(/<script>[\s\S]*?<\/script>/)[0],sharedCSS:html.includes(fs.readFileSync(root+'/docs/architecture/gate3-shared-consumer-v0.2/shared-chrome.css','utf8').trim())};
 const lum=rgb=>rgb.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0),contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);result.contrast=[{pair:'functional teal / white',value:contrast([0,128,120],[255,255,255])},{pair:'functional teal / soft',value:contrast([0,128,120],[245,248,251])},{pair:'navy / white',value:contrast([6,43,91],[255,255,255])},{pair:'record label muted / white',value:contrast([93,107,125],[255,255,255])}];await b.close();fs.writeFileSync(out+'/supplement.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));})().catch(e=>{console.error(e);process.exitCode=1});
