const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const pageRoot=path.resolve(__dirname,'../..'), candidate=path.join(pageRoot,'04_planning/gate5-v0.1');
const out=__dirname; fs.mkdirSync(out,{recursive:true});
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const json=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
const checks=[]; const add=(id,pass,actual)=>checks.push({id,pass,actual});
const freeze=json(path.join(candidate,'approval_core/source-freeze.json'));
for(const x of [...freeze.dependencies,...freeze.inputs]){const b=fs.readFileSync(x.path);add('identity:'+x.relativePath,b.length===x.bytes&&sha(b)===x.sha256,{bytes:b.length,sha256:sha(b)});}
const inv=json(path.join(candidate,'approval_core/export-inventory.json'));
const records=Array.isArray(inv)?inv:(inv.captures||inv.exports||inv.assets||inv.records||[]);
add('formal-inventory-count',records.length===14,records.length);
for(const x of records){const p=path.resolve(candidate,x.relativePath||x.path);const b=fs.readFileSync(p);add('formal:'+path.basename(p),b.length===x.bytes&&sha(b)===x.sha256,{bytes:b.length,sha256:sha(b)});}
const htmlPath=freeze.entry.path;
const required=[
'Titanium Dioxide Supplier for Poland','Malaysia-origin titanium dioxide raw material for industrial procurement in Poland. Review grades for coatings, plastics and masterbatch production, or send us your application, estimated quantity and delivery requirements for a quotation.',
'Confirm the Material You Need','The products presented by TiO2 Malaysia are industrial titanium dioxide raw materials. A finished white masterbatch combines TiO2 with a polymer carrier. If you produce masterbatch, evaluate the TiO2 grade as an input to your own formulation and process.',
'Prepare Your Product Review','You do not need to know the exact grade before you start. Begin with the application information your team already knows, then compare the relevant grades on the product pages.','Coatings','Use your coating system and end use—such as decorative, construction or industrial applications—to decide which grade properties are relevant to compare on the product pages.','Plastics and masterbatch','Compare grade information against the resin, processing route and finished product, such as film, bags, pipes or fittings. Evaluate direct use in a plastic product separately from TiO2 used as an input for masterbatch production.',
'Documents for Product and Supplier Review','For a grade you are evaluating, request the TDS, SDS, COA or origin documentation your team needs for review. Select the Product Grade and document types on the request form.','A Certificate of Origin is available upon request.','If you are still deciding on a grade, explore the product pages or continue to the quotation request with “Not sure / Need help.”',
'Request a Quote for Delivery to Poland','Tell us about your current requirement, including the application, required or estimated quantity, and delivery location in Poland. Select the product or grade you are evaluating, or choose “Not sure / Need help” if you have not decided yet.','If you are considering more than one grade, add that context in Additional Requirements.','Our team will review your requirements and contact you using the details provided.'
];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});
for(const vp of [{w:1440,h:1000,d:1},{w:768,h:1000,d:1},{w:390,h:844,d:2}]){
 const ctx=await browser.newContext({viewport:{width:vp.w,height:vp.h},deviceScaleFactor:vp.d}); const p=await ctx.newPage(); const net=[],errors=[];
 await p.route(/^https?:/i,r=>{net.push(r.request().url());r.abort();}); p.on('pageerror',e=>errors.push(String(e))); await p.goto(pathToFileURL(htmlPath).href); await p.evaluate(()=>document.fonts.ready);
 const actual=await p.evaluate(()=>({text:document.body.innerText.replace(/\s+/g,' ').trim(),scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,title:document.title,description:document.querySelector('meta[name=description]')?.content,canonical:document.querySelector('link[rel=canonical]')?.href,robots:document.querySelector('meta[name=robots]')?.content,h1:document.querySelectorAll('h1').length,current:[...document.querySelectorAll('nav[aria-label="Primary navigation"] [aria-current=page],nav[aria-label="Mobile navigation"] [aria-current=page]')].map(x=>x.textContent.trim()),font:getComputedStyle(document.body).fontFamily,controls:[...document.querySelectorAll('a,button')].filter(x=>{const r=x.getBoundingClientRect();return r.width&&r.height&&getComputedStyle(x).visibility!=='hidden'}).map(x=>({t:x.textContent.trim(),w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})),order:[...document.querySelectorAll('main section')].map(x=>x.id)}));
 add(`${vp.w}:no-overflow`,actual.scrollWidth===actual.clientWidth,actual); add(`${vp.w}:h1`,actual.h1===1,actual.h1); add(`${vp.w}:content`,required.every(x=>actual.text.includes(x)),required.filter(x=>!actual.text.includes(x))); add(`${vp.w}:targets`,actual.controls.every(x=>x.w>=43.9&&x.h>=43.9),actual.controls.filter(x=>x.w<43.9||x.h<43.9)); add(`${vp.w}:meta`,actual.title==='Titanium Dioxide Supplier for Poland | TiO2 Malaysia'&&actual.description==='Compare Malaysia-origin titanium dioxide grades for coatings, plastics and masterbatch in Poland. Request product documents or submit a quotation request.'&&actual.canonical==='https://tio2malaysia.com/markets/poland/'&&actual.robots==='noindex,nofollow',actual); add(`${vp.w}:current`,actual.current.filter(x=>x==='Markets').length===2,actual.current); add(`${vp.w}:font`,/Inter/.test(actual.font),actual.font); add(`${vp.w}:network-errors`,net.length===0&&errors.length===0,{net,errors});
 const shot=await p.screenshot({fullPage:true}); const formal=records.find(x=>(x.logicalViewport?.width||x.logicalWidth||x.viewportWidth)===vp.w&&(x.state==='default'||/full-page/.test(x.relativePath||x.path))); add(`${vp.w}:independent-raster-match`,!!formal&&sha(shot)===formal.sha256,{actual:sha(shot),formal:formal?.sha256}); fs.writeFileSync(path.join(out,`root-default-${vp.w}.png`),shot);
 if(vp.w<1101){await p.getByRole('button',{name:/Menu/}).click(); add(`${vp.w}:menu-open`,await p.getByRole('button',{name:'Close'}).getAttribute('aria-expanded')==='true'&&await p.locator('main').getAttribute('inert')!==null,await p.evaluate(()=>({active:document.activeElement?.textContent?.trim(),overflow:document.body.style.overflow}))); await p.keyboard.press('Escape'); add(`${vp.w}:menu-close`,await p.getByRole('button',{name:'Menu'}).getAttribute('aria-expanded')==='false'&&await p.locator('main').getAttribute('inert')===null,await p.evaluate(()=>({active:document.activeElement?.id,overflow:document.body.style.overflow})))}
 await p.getByRole('button',{name:'Cookie Settings'}).click(); add(`${vp.w}:cookie-open`,await p.getByRole('dialog').isVisible()&&(await p.evaluate(()=>document.activeElement?.textContent?.trim()))==='Close',await p.evaluate(()=>document.activeElement?.textContent?.trim())); await p.keyboard.press('Escape'); add(`${vp.w}:cookie-close`,!(await p.getByRole('dialog').isVisible())&&(await p.evaluate(()=>document.activeElement?.id))==='cookie-trigger',await p.evaluate(()=>document.activeElement?.id));
 await ctx.close(); }
 await browser.close(); const result={reviewedAt:new Date().toISOString(),freezeId:freeze.freezeId,sourceCombination:freeze.combinedSha256,scope:'Root independent identity, content, geometry, metadata, shared overlay operation and deterministic raster check; visual assets separately opened by root.',checks,pass:checks.every(x=>x.pass),failures:checks.filter(x=>!x.pass)}; fs.writeFileSync(path.join(out,'root-verification.json'),JSON.stringify(result,null,2)+'\n'); console.log(JSON.stringify({total:checks.length,pass:result.pass,failures:result.failures},null,2)); if(!result.pass)process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
