const fs=require('fs'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const b='D:/23MySec/pages/markets/poland',old=b+'/04_planning/gate4-v0.1',src=b+'/04_planning/gate4-v0.2',out=b+'/05_review/gate4-project-control-v0.1/independent-review/rereview-v0.2';
const read=p=>fs.readFileSync(p),json=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex');
const freeze=json(src+'/approval_core/source-freeze.json'),inv=json(src+'/approval_core/export-inventory.json'),prev=json(old+'/approval_core/export-inventory.json');
const records=Object.values(freeze).filter(Array.isArray).flat().filter(x=>x.path&&x.sha256).concat(inv.captures);
const audit={freezeId:freeze.freezeId,freezeBinding:hash(src+'/approval_core/source-freeze.json')===inv.sourceFreezeSha256,records:records.map(x=>({path:x.path,actual:hash(x.path),hashMatch:hash(x.path)===x.sha256,bytesMatch:read(x.path).length===x.bytes})),inherited:prev.captures.map(x=>{const n=inv.captures.find(y=>y.relativePath===x.relativePath);return{path:n.path,oldPath:x.path,byteIdentical:read(n.path).equals(read(x.path))}}),htmlByteIdentical:read(src+'/MARKET-EU-PL_GATE4_VISUAL_SAMPLES_V0.2.html').equals(read(old+'/MARKET-EU-PL_GATE4_VISUAL_SAMPLES_V0.1.html'))};
const css=read(src+'/visual-rules.css').toString(),cssOld=read(old+'/visual-rules.css').toString();audit.cssOldPrefixUnchanged=css.startsWith(cssOld);audit.cssAppend=css.slice(cssOld.length);fs.writeFileSync(out+'/identity.json',JSON.stringify(audit,null,2));
const lum=c=>{const a=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722};
const contrast=(a,b)=>{const x=lum(a),y=lum(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
const describe=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();let n=e,bg=s.backgroundColor;while(bg==='rgba(0, 0, 0, 0)'&&n.parentElement){n=n.parentElement;bg=getComputedStyle(n).backgroundColor}return{text:e.textContent.trim(),href:e.getAttribute('href'),fg:s.color,bg,hover:e.matches(':hover'),focusVisible:e.matches(':focus-visible'),outline:[s.outlineColor,s.outlineWidth,s.outlineStyle,s.outlineOffset],box:{x:r.x,y:r.y+scrollY,width:r.width,height:r.height}}};
const selectors=['#pl-04 .body-action+.body-action a','#pl-05 .body-action+.body-action a','#pl-01 .body-action:first-of-type a','#pl-04 .body-action:first-of-type a','#pl-05 .body-action:first-of-type a','#pl-01 a[href="/products/"]','#pl-03 a[href="/products/"]','#cookie-trigger'];
const result={evidenceType:'ACTUAL_RUNTIME',widths:[],networkAttempts:[],errors:[]};
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();for(const width of[1440,768,390]){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});p.on('pageerror',e=>result.errors.push(e.message));await p.route('**/*',r=>{if(/^https?:/.test(r.request().url())){result.networkAttempts.push(r.request().url());return r.abort()}return r.continue()});
const load=async(v)=>{await p.goto('file:///'+(v===1?old:src)+'/MARKET-EU-PL_GATE4_VISUAL_SAMPLES_V0.'+v+'.html');await p.evaluate(()=>document.fonts.ready);await p.mouse.move(0,0)};
await load(1);const before={main:await p.locator('main').innerText(),boxes:await p.locator('main a').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent,href:e.getAttribute('href'),x:r.x,y:r.y+scrollY,width:r.width,height:r.height}}))};const oldHover=[];for(const s of selectors){const a=p.locator(s);await a.hover();oldHover.push(await a.evaluate(describe))}
await load(2);const after={main:await p.locator('main').innerText(),boxes:await p.locator('main a').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent,href:e.getAttribute('href'),x:r.x,y:r.y+scrollY,width:r.width,height:r.height}}))};const row={width,mainTextSame:before.main===after.main,mainTargetsGeometrySame:JSON.stringify(before.boxes)===JSON.stringify(after.boxes),scrollWidth:await p.evaluate(()=>document.documentElement.scrollWidth),controls:[]};
for(let i=0;i<selectors.length;i++){const sel=selectors[i],a=p.locator(sel);await a.hover();const hover=await a.evaluate(describe);hover.contrast=contrast(hover.fg,hover.bg);await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');const focus=await a.evaluate(describe);focus.contrast=contrast(focus.fg,focus.bg);const h=oldHover[i];row.controls.push({selector:sel,hover,focus,oldHover:h,unchangedNeighborHover:i<2?null:JSON.stringify(h)===JSON.stringify({...hover,contrast:undefined})});}
await p.locator('#cookie-trigger').press('Enter');row.cookie={opened:await p.locator('dialog').evaluate(e=>e.open),focus:await p.locator('dialog button').evaluate(describe)};await p.locator('dialog button').hover();row.cookie.closeHover=await p.locator('dialog button').evaluate(describe);await p.keyboard.press('Tab');row.cookie.policyFocus=await p.locator('dialog a').evaluate(describe);await p.keyboard.press('Tab');row.cookie.cycleBack=await p.locator('dialog button').evaluate(e=>e===document.activeElement);await p.keyboard.press('Escape');row.cookie.closed=await p.locator('dialog').evaluate(e=>!e.open);row.cookie.returned=await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement);result.widths.push(row);await p.close()}
await browser.close();fs.writeFileSync(out+'/runtime.json',JSON.stringify(result,null,2));console.log(JSON.stringify({identities:audit.records.length,identityFailures:audit.records.filter(x=>!x.hashMatch||!x.bytesMatch).length,inherited:audit.inherited.filter(x=>x.byteIdentical).length,htmlSame:audit.htmlByteIdentical,cssAppend:audit.cssAppend,runtime:result.widths.map(x=>({width:x.width,textSame:x.mainTextSame,geometrySame:x.mainTargetsGeometrySame,scrollWidth:x.scrollWidth,controls:x.controls.map(y=>({text:y.hover.text,ratio:y.hover.contrast,hover:y.hover.hover,focus:y.focus.focusVisible,neighborSame:y.unchangedNeighborHover})),cookie:x.cookie})),errors:result.errors,network:result.networkAttempts},null,2));})().catch(e=>{fs.writeFileSync(out+'/failure.txt',String(e.stack));console.error(e);process.exit(1)});
