const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root='D:/23MySec',out=__dirname;
const read=p=>fs.readFileSync(root+'/'+p,'utf8');
const {renderSharedChrome}=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs');
const mapping=read('pages/products/06_handoff/PRODUCT-000_GATE7_CMS_API_COMPONENT_MAPPING_V0.3.md');
const spec=read('pages/products/04_planning/visual-designs/PRODUCT-000_FULL_VISUAL_DESIGN_V0.13.md');
const rows=[...mapping.matchAll(/^\| (\d+) \| ((?:M-|CR-)\d+) \| `([^`]+)` \| `([^`]+)` \| ([^|]+) \| `([^`]+)` \|/gm)].map(m=>({grade:m[2],pageId:m[3],url:m[4],group:m[5].trim(),summary:m[6]}));
const steps=[...mapping.matchAll(/^\| (\d) \| ([^|]+) \| `([^`]+)` \|$/gm)].map(m=>({title:m[2].trim(),body:m[3]}));
const faqPart=spec.split('#### A6.1 Formal FAQ copy deck')[1].split('## B.')[0];
const faq=[...faqPart.matchAll(/\d\. \*\*([^*]+)\*\*\s+([^\r\n]+)/g)].map(m=>({question:m[1],answer:m[2].trim()}));
const applications={Coatings:['M-350','M-510','M-896','M-996','M-2196','M-895','M-52','M-2377'],Plastics:['M-350','M-510','M-200','M-108','M-210','M-340','M-886','M-2377'],Masterbatch:['M-510','M-200','M-108','M-210','M-340','M-886','M-2377'],'Printing Inks':['M-350','M-510','M-52','M-2377'],Paper:['M-350','M-2377'],'Specialty Materials':['CR-901']};
const data={rows,steps,faq,applications};if(rows.length!==14||steps.length!==5||faq.length!==5)throw Error('incomplete content extraction');
fs.writeFileSync(path.join(out,'content-extraction.json'),JSON.stringify(data,null,2));
const E=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const qualify='Listed grades are starting points for technical evaluation and do not guarantee suitability for a specific formulation or operating condition.';
const C=renderSharedChrome({currentPageId:'PRODUCT-000',primaryLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'../../../../brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf'});
const resultHtml=app=>applications[app].map(g=>`<div class="result"><strong>${g}</strong><a aria-label="View ${g} grade" href="${rows.find(r=>r.grade===g).url}">View Grade</a></div>`).join('');
const groups=[...new Set(rows.map(r=>r.group))];
const supports=[['Review by Application','Review grades listed for each application and continue to detailed application guidance.','Explore Applications','/applications/'],['Identify Required Documents','Review technical, quality, compliance and origin-document pathways for the applicable request.','Explore Documents','/documents/'],['Review Destination Context','Review destination-market procurement context without assuming local availability, registration or regulatory acceptance.','Explore Markets','/markets/']];
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>PRODUCT-000 Gate 3 planning</title><style>${C.style}\n${fs.readFileSync(path.join(out,'planning.css'),'utf8')}</style></head><body><a class="skip" href="#main">Skip to content</a>${C.header}<main id="main" tabindex="-1">
<div class="wrap"><nav class="crumb" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">›</span><span>Products</span></nav>
<section class="rootHero" data-component="RootPageHero" data-variant="hub-light" aria-labelledby="page-title"><div class="heroText"><p class="eyebrow">TITANIUM DIOXIDE PRODUCTS</p><h1 id="page-title">Titanium Dioxide Pigment Grades for Industrial Applications</h1><p>Explore 14 titanium dioxide pigment grades using the application selector, production-process categories or complete grade directory, then continue to individual grade pages for technical evaluation.</p><p>The portfolio includes rutile titanium dioxide pigment grades for multiple industrial applications.</p><p class="small">${qualify}</p><div class="actions"><a class="primary" href="#grade-selector">Start Grade Selection</a><a class="secondary" href="/request-a-quote/">Request a Quote</a></div></div><aside class="portfolio"><h2>14 grades. Four portfolio groups.</h2><p>Browse the complete directory by product family.</p><div class="summary">${[['6','Coatings Grades'],['5','Plastics & Masterbatch'],['2','Inks & Multi-Application'],['1','Specialty Grade']].map(x=>`<div><strong>${x[0]}</strong><span>${E(x[1])}</span></div>`).join('')}</div></aside></section></div>
<section class="band" id="grade-selector"><div class="wrap section"><p class="eyebrow">Application-first selection</p><h2>Start with Your Application</h2><p>Choose the closest application to view the grades listed for that use case.</p><div class="selector"><div><h3>Step 1 — Select an application</h3><div class="options" role="group" aria-label="Application">${[...Object.keys(applications),'Not Sure'].map((a,i)=>`<button type="button" data-app="${a}" aria-pressed="${i===0}"><span aria-hidden="true" class="check">${i===0?'✓ ':''}</span>${a}</button>`).join('')}</div></div><div><h3 id="result-heading" aria-live="polite">Grades to Review — 8 <span class="sr">for Coatings</span></h3><div id="results" class="results">${resultHtml('Coatings')}</div><p class="small">${qualify}</p></div></div><noscript><p>The guided selector is unavailable. Use the full grade directory below.</p></noscript></div></section>
<section class="wrap section" id="process"><h2>Browse by Production Process</h2><p>Use these routes when a production-process classification is part of your sourcing specification. Process classification does not determine application fit on its own.</p><div class="processCards">${['Chloride','Sulfate'].map(p=>`<article class="card" data-process="${p}"><h3>${p} Process Titanium Dioxide</h3><p>Browse grades classified under the ${p.toLowerCase()} process and continue to the relevant product pages.</p><a href="/products/${p.toLowerCase()}-process-titanium-dioxide/">Explore ${p} Grades</a></article>`).join('')}</div><div class="special"><strong>CR-901 · Vapor-phase oxidation</strong><a aria-label="View CR-901 grade" href="/products/cr-901/">View Grade</a></div></section>
<section class="band" id="all-grades"><div class="wrap section"><h2>Browse All 14 Titanium Dioxide Grades</h2><p>Portfolio groups are navigation categories. A grade may appear in more than one application result because application relationships can span multiple navigation groups.</p><div class="directory">${groups.map(g=>`<article class="group"><h3>${E(g)}</h3>${rows.filter(r=>r.group===g).map(r=>`<div class="gradeRow" data-grade="${r.grade}"><strong>${r.grade}</strong><p>${E(r.summary)}</p><a aria-label="View ${r.grade} grade" href="${r.url}">View Grade <span aria-hidden="true">→</span></a></div>`).join('')}</article>`).join('')}</div></div></section>
<section class="wrap section" id="evaluation"><h2>How to Evaluate a Titanium Dioxide Grade</h2><div class="steps">${steps.map((s,i)=>`<article class="step"><span class="number">0${i+1}</span><h3>${E(s.title)}</h3><p>${E(s.body)}</p></article>`).join('')}</div></section>
<section class="band" id="support"><div class="wrap section"><h2>Continue Your Procurement Review</h2><div class="supportCards">${supports.map((s,i)=>`<article class="card" data-support="${i}"><h3>${s[0]}</h3><p>${s[1]}</p><a href="${s[3]}">${s[2]}</a></article>`).join('')}</div></div></section>
<section class="wrap section" id="faq"><h2>Buyer Questions</h2>${faq.map((f,i)=>`<article class="question"><h3><button type="button" aria-expanded="true" aria-controls="answer-${i}">${E(f.question)}<span aria-hidden="true">−</span></button></h3><div class="answer" id="answer-${i}"><p>${E(f.answer)}</p></div></article>`).join('')}</section>
<section class="band"><div class="wrap section final"><div><h2>Request a Quote for Your Requirements</h2><p>Share your application, destination market, expected quantity and any grade you are evaluating.</p><p class="small">Quotation, availability and documentation remain subject to review.</p></div><a class="primary" href="/request-a-quote/">Request a Quote</a></div></section>
</main>${C.footer}${C.dialog}<script>${C.behavior}</script><script>const DATA=${JSON.stringify(data)};${fs.readFileSync(path.join(out,'planning.js'),'utf8')}</script></body></html>`;
fs.writeFileSync(path.join(out,'product-planning.html'),html);
console.log({rows:rows.length,steps:steps.length,faq:faq.length,source:path.join(out,'product-planning.html')});
