const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/system/404/04_planning/gate4-v0.1',source=out+'/SYS-404_GATE4_COMPLETE_VISUAL_V0.1.html';
const formal=process.argv.includes('--formal'),dest=out+(formal?'/approval_core':'/diagnostic_support/render');
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const expected={eyebrow:'404 · PAGE NOT FOUND',h1:'Let’s help you find what you need.',body:'The page you’re looking for may have moved or is no longer available. You can continue by exploring our titanium dioxide products, requesting technical documents, or contacting our team.',labels:['Explore Products','Go to Homepage','Request Documents','Contact Our Team','Request a Quote'],hrefs:['/products/','/','/request-documents/','/contact/','/request-a-quote/']};
let results=[],images=[],network=[],browser;const check=(name,ok,details)=>{results.push({name,status:ok?'PASS':'FAIL',details});if(!ok)throw Error(name+' '+JSON.stringify(details))};
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
const shot=async(p,w,state,full=false)=>{const f=dest+'/'+(formal?'SYS-404_G4_':'diagnostic-')+w+'-'+state+'.png';await p.screenshot({path:f,fullPage:full,animations:'disabled'});images.push({...id(f),logicalWidth:w,state})};
(async()=>{if(formal){const fr=JSON.parse(fs.readFileSync(out+'/freeze-record.json'));check('frozen source',fr.design_source.sha256===id(source).sha256);check('first formal export',fs.readdirSync(dest).length===0)}browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
for(const w of [1440,768,390]){const h=w===390?844:900,ctx=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1,reducedMotion:'reduce'});await ctx.route(/^https?:/,r=>{network.push(r.request().url());r.abort()});const p=await ctx.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
 const data=await p.evaluate(()=>{const q=s=>document.querySelector(s),links=[...document.querySelectorAll('.recovery nav a')],cs=x=>getComputedStyle(x);return{eyebrow:q('.eyebrow').textContent,h1:q('h1').textContent,body:q('.intro').textContent,labels:links.map(x=>x.textContent),hrefs:links.map(x=>x.getAttribute('href')),order:[...q('.recovery').children].map(x=>x.className||x.tagName),currentDesktop:document.querySelectorAll('.desktopNav [aria-current]').length,currentMobile:document.querySelectorAll('.mobileNav [aria-current]').length,forbidden:document.querySelectorAll('main form,main input,main details,main img').length,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,footer:q('footer').getBoundingClientRect().bottom+scrollY,font:document.fonts.check('16px Inter'),targets:[...document.querySelectorAll('a,button')].filter(x=>x.getBoundingClientRect().width>0).map(x=>({t:x.textContent.trim(),w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})),rects:links.map(x=>({l:x.getBoundingClientRect().left,r:x.getBoundingClientRect().right,t:x.getBoundingClientRect().top,b:x.getBoundingClientRect().bottom,w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height})),colors:links.map(x=>({color:cs(x).color,bg:cs(x).backgroundColor,border:cs(x).borderColor})),panel:{w:q('.recovery').getBoundingClientRect().width,h:q('.recovery').getBoundingClientRect().height},bodyText:q('main').innerText}});
 check(w+' exact approved copy and targets',JSON.stringify([data.eyebrow,data.h1,data.body,data.labels,data.hrefs])===JSON.stringify([expected.eyebrow,expected.h1,expected.body,expected.labels,expected.hrefs]),data);
 check(w+' fixed order and exclusions',JSON.stringify(data.order)===JSON.stringify(['eyebrow','H1','intro','primary-actions','supporting-actions'])&&data.forbidden===0,data.order);
 check(w+' zero false current',data.currentDesktop===0&&data.currentMobile===0,{desktop:data.currentDesktop,mobile:data.currentMobile});
 check(w+' full width Footer font',data.width===w&&Math.abs(data.footer-data.height)<2&&data.font,{width:data.width,height:data.height,footer:data.footer,font:data.font});
 check(w+' all visible targets 44x44',data.targets.every(x=>x.w>=44&&x.h>=44),data.targets);
 check(w+' recovery controls in viewport',data.rects.every(x=>x.l>=0&&x.r<=w&&x.w>=44&&x.h>=44),data.rects);
 check(w+' primary/supporting visual distinction',data.colors[0].bg!==data.colors[2].bg&&data.colors[1].bg!==data.colors[2].bg,data.colors);
 check(w+' balanced panel',data.panel.w<=920&&data.panel.h>380&&data.panel.h<700,data.panel);
 if(w===390){check('390 actions single column',data.rects.every(x=>x.w>290)&&data.rects.every((x,i,a)=>i===0||x.t>=a[i-1].b),data.rects)}
 check(w+' prohibited copy absent',!/(search|faq|redirect|recommended products)/i.test(data.bodyText),data.bodyText);
 await shot(p,w,'full',true);
 for(let i=0;i<5;i++){await p.locator('.recovery nav a').nth(i).click();const got=await p.evaluate(()=>window.localNavigationIntents.at(-1));check(w+' action '+(i+1),got.href===expected.hrefs[i]&&Object.keys(got.context).length===0,got)}
 if(w<1101){const b=p.locator('.menuButton');await b.click();check(w+' menu open focus inert',await p.evaluate(()=>document.activeElement.textContent==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'));await shot(p,w,'menu');await p.keyboard.press('Escape');check(w+' menu escape restore',await b.evaluate(e=>e===document.activeElement)&&await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''))}
 await p.locator('#cookie-trigger').click();check(w+' cookie open first focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await shot(p,w,'cookie');await p.keyboard.press('Shift+Tab');check(w+' cookie reverse loop',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(w+' cookie forward loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('[data-cookie-close]').click();check(w+' cookie focus return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await ctx.close()}
 const z=await browser.newPage({viewport:{width:720,height:900}});await z.goto(pathToFileURL(source).href);await ready(z);const zg=await z.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,targets:[...document.querySelectorAll('a,button')].filter(x=>x.getBoundingClientRect().width).every(x=>x.getBoundingClientRect().width>=44&&x.getBoundingClientRect().height>=44)}));check('200 percent equivalent reflow at 1440 to 720',zg.sw===zg.cw&&zg.targets,zg);await z.close();
 check('no external network',network.length===0,network);const rec={status:'PASS',mode:formal?'FORMAL':'PREFLIGHT',workset_id:'SYS-404-G4-WORKSET-20260908-01',source:id(source),browser:await browser.version(),viewports:[1440,768,390],dpr:1,evidenceTypes:['SOURCE_INSPECTION','ACTUAL_RUNTIME','LOCAL_SIMULATION','STATIC_VISUAL'],results,images,network,finishedAt:new Date().toISOString()};await browser.close();fs.writeFileSync(dest+'/runtime.json',JSON.stringify(rec,null,2)+'\n');console.log(JSON.stringify({status:'PASS',mode:rec.mode,checks:results.length,images:images.length}))})().catch(async e=>{if(browser)await browser.close();fs.writeFileSync(out+'/diagnostic_support/failure-'+Date.now()+'.json',JSON.stringify({status:'FAIL',error:e.stack,results,images},null,2));console.error(e);process.exitCode=1});
