const fs=require('fs'),crypto=require('crypto'),out='D:/23MySec/pages/resources/eu-trade/04_planning/gate4-v0.1/';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const lock=JSON.parse(fs.readFileSync(out+'render-lock.json')),assets=JSON.parse(fs.readFileSync(out+'formal-assets.json')),inputs=JSON.parse(fs.readFileSync(out+'input-index.json')),pre=JSON.parse(fs.readFileSync(out+'preflight-record.json'));
let checked=[],failures=[];function verify(i){const a=id(i.path),ok=a.bytes===i.bytes&&a.sha256===i.sha256;checked.push({path:i.path,status:ok?'MATCH':'MISMATCH'});if(!ok)failures.push({expected:i,actual:a});}
for(const i of [lock.source,...lock.dependencies,lock.inputIndex,lock.preflight,lock.renderer,...inputs.inputs])verify(i);
for(const a of assets.images){verify(a);const b=fs.readFileSync(a.path);if(b.readUInt32BE(16)!==a.physicalWidth||b.readUInt32BE(20)!==a.physicalHeight||a.physicalWidth!==a.logicalViewport.width*a.dpr||a.sourceSha256!==lock.source.sha256)failures.push({dimensionOrSource:a.path});}
if(assets.images.length!==8||assets.images.filter(x=>x.state==='full').length!==3||new Date(assets.capturedAt)<=new Date(lock.lockedAt))failures.push({captureOrderOrCount:true});
if(failures.length){fs.writeFileSync(out+'diagnostic_support/freeze-failure.json',JSON.stringify({checked,failures},null,2));throw Error('freeze identity failure')}
fs.writeFileSync(out+'capture-check.json',JSON.stringify({mode:'SELF_CHECK / CAPTURE_CHECK',executor:'/root/gate4_eu_trade_execute',checkedAt:new Date().toISOString(),source:lock.source,allFormalAssetsActuallyOpened:assets.images.map(a=>a.path),fullPageReadableRanges:pre.visualObservation.coverage,method:'Saved formal PNGs decoded and opened at readable native-width regions in memory; no persisted crop assets. Five saved state PNGs opened directly.',result:'CAPTURE_CHECK_COMPLETE',observation:'Fonts, logos, viewport/DPR, table, all module connections and Footer match INITIAL. Menu and Cookie states are correctly open, viewport-sized and complete. No capture anomaly, unexpected hover or focus. No content/behavior/geometry rerun.',machineChecks:checked.length,identityMismatches:0,dimensionMismatches:0,findings:[]},null,2));
const reports=['4A-visual-direction.md','full-page-composition.md','preflight-record.json','capture-check.json','render-lock.json','workset.json'].map(p=>id(out+p));const self=id('D:/23MySec/pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE4_EXECUTION_SELF_CHECK_V0.1.md');
fs.writeFileSync(out+'evidence-index.json',JSON.stringify({workset_id:'RES-TRADE-EU-G4-WS-01',freeze_id:'RES-TRADE-EU-G4-FREEZE-01',status:'GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW',actualAuthor:'/root/gate4_eu_trade_execute',independentReview:'NOT_PERFORMED_BY_EXECUTOR',approval_core:{source:lock.source,dependencies:lock.dependencies,inputIndex:lock.inputIndex,reports,selfCheck:self,formalAssets:assets.images},diagnostic_support:{runtime:id(out+'diagnostic_support/initial-runtime.json'),directionSample:{...id(out+'diagnostic_support/4A-390-table-predicates.png'),reason:'4A unique mobile table plus full predicates risk'},helpers:['build.cjs','initial-check.cjs','lock.cjs','render.cjs','view-asset.py','freeze.cjs'].map(p=>id(out+'diagnostic_support/'+p))},counts:{formalPNG:8,fullPagePNG:3,menuPNG:2,cookiePNG:3,diagnosticPNG:1,persistentSegmentPNG:0,duplicateFormalSet:0},evidenceTypes:['STATIC_VISUAL','ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION'],findings:[],unverified:pre.unverified},null,2));
fs.writeFileSync(out+'freeze-record.json',JSON.stringify({freeze_id:'RES-TRADE-EU-G4-FREEZE-01',workset_id:'RES-TRADE-EU-G4-WS-01',frozenAt:new Date().toISOString(),status:'GATE4_EXECUTION_COMPLETE_FROZEN',handoffStatus:'READY_FOR_GATE5_REVIEW',stageApproval:'NOT_GRANTED',source:lock.source,dependencies:lock.dependencies,inputIndex:lock.inputIndex,evidenceIndex:id(out+'evidence-index.json'),renderLock:id(out+'render-lock.json'),formalAssetCapture:id(out+'formal-assets.json'),selfCheck:self,author:'/root/gate4_eu_trade_execute',stop:'Gate4 production/self-check/freeze complete. Independent Gate5 review belongs to a different task. No Gate6 or closure.'},null,2));
const frozen=JSON.parse(fs.readFileSync(out+'freeze-record.json'));for(const i of [frozen.evidenceIndex,frozen.renderLock,frozen.formalAssetCapture,frozen.selfCheck])verify(i);const audit={status:failures.length?'FAIL':'IDENTITIES_MATCH',auditedAt:new Date().toISOString(),checks:checked.length,failures,checked,source:lock.source,inputIndex:id(out+'input-index.json'),evidenceIndex:id(out+'evidence-index.json'),freeze:id(out+'freeze-record.json'),counts:{formalPNG:8,diagnosticPNG:1},independentReview:false};fs.writeFileSync(out+'final-identity-check.json',JSON.stringify(audit,null,2));console.log(JSON.stringify({status:audit.status,checks:audit.checks,failures:failures.length,source:audit.source,inputIndex:audit.inputIndex,evidenceIndex:audit.evidenceIndex,freeze:audit.freeze,selfCheck:self}));
