const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec/',out=root+'pages/resources/eu-trade/04_planning/gate4-v0.1/',source=out+'RES-TRADE-EU_GATE4_COMPLETE_VISUAL_V0.1.html';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const expected=JSON.parse(fs.readFileSync(root+'pages/resources/eu-trade/04_planning/gate3-v0.1/diagnostic_support/expected-copy.json'));
let records=[],network=[],browser;const check=(name,ok,details)=>{records.push({name,status:ok?'PASS':'FAIL',details});if(!ok)throw Error(name)};
const restored=p=>p.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.body.style.overflow===''&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert));
(async()=>{check('B identity matches approved expected map',id(expected.source.path).sha256===expected.source.sha256);const old=fs.readFileSync(root+'pages/resources/eu-trade/04_planning/gate3-v0.1/RES-TRADE-EU_GATE3_WIREFRAME_V0.1.html','utf8'),now=fs.readFileSync(source,'utf8');check('All HTML markup and behavior unchanged from approved Gate3',old.split('</style>')[1]===now.split('</style>')[1]);check('Shared CSS exact, page-local CSS only',old.split('*{box-sizing:border-box}body')[0].trim()===now.split('*{box-sizing:border-box}body')[0].trim());
browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
for(const w of [1440,768,390]){const h=w===390?844:900,ctx=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await ctx.route(/^https?:/,r=>{network.push(r.request().url());return r.abort()});const p=await ctx.newPage();await p.goto(pathToFileURL(source).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()))});
const blocks=await p.locator('main').evaluate(e=>[...e.querySelectorAll('h1,h2,h3,p,li,th,td')].map(x=>({tag:x.tagName.toLowerCase(),text:x.textContent.replace(/\s+/g,' ').trim()})));check(w+' all ordered B blocks',JSON.stringify(blocks)===JSON.stringify(expected.blocks));
const links=await p.locator('main a').evaluateAll(as=>as.map(a=>({text:a.textContent,href:a.getAttribute('href')})));check(w+' all approved links',JSON.stringify(links)===JSON.stringify(expected.links));check(w+' fixed duty tuples',JSON.stringify(await p.locator('table tr').evaluateAll(rs=>rs.map(r=>[...r.children].map(c=>c.textContent))))===JSON.stringify(expected.tableRows));
const geom=await p.evaluate(()=>{const visible=e=>e.getBoundingClientRect().width>0;return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,footerBottom:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,font:document.fonts.check('16px Inter'),images:[...document.images].every(i=>i.complete&&i.naturalWidth>0),h1:getComputedStyle(document.querySelector('h1')).fontSize,h2:getComputedStyle(document.querySelector('main h2')).fontSize,header:document.querySelector('header').getBoundingClientRect().height,targets:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({label:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),clipped:[...document.querySelectorAll('main *')].filter(e=>getComputedStyle(e).textOverflow==='ellipsis'||['hidden','clip'].includes(getComputedStyle(e).overflowY)).map(e=>e.tagName),cells:[...document.querySelectorAll('th,td')].map(e=>({text:e.textContent,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right,scroll:e.scrollWidth,client:e.clientWidth,font:getComputedStyle(e).fontSize})),sections:[...document.querySelectorAll('main section')].map(e=>({id:e.dataset.module,y:e.getBoundingClientRect().top+scrollY,height:e.getBoundingClientRect().height})),table:document.querySelector('table').getBoundingClientRect().toJSON()}});
check(w+' font/media/full-page bounds',geom.font&&geom.images&&geom.scrollWidth===w&&Math.abs(geom.footerBottom-geom.height)<2,geom);check(w+' 44x44 targets',geom.targets.every(t=>t.w>=44&&t.h>=44));check(w+' no hidden or truncated main content',geom.clipped.length===0);check(w+' readable bounded table',geom.cells.every(c=>c.left>=0&&c.right<=w&&c.scroll<=c.client+1&&parseFloat(c.font)>=14));
check(w+' required content cardinalities',await p.evaluate(()=>document.querySelectorAll('main h1').length===1&&document.querySelectorAll('main section').length===6&&document.querySelectorAll('.module-4 ol li').length===7&&document.querySelectorAll('.module-5 ul li').length===3&&document.querySelectorAll('.module-6 ul li').length===4&&document.querySelectorAll('main form,main input,main select,main details').length===0));
check(w+' current Resources and header geometry',geom.header===(w>1100?84:64)&&await p.locator('.desktopNav [aria-current=page]').textContent()==='Resources'&&await p.locator('.mobileNav [aria-current=page]').textContent()==='Resources');
const primary=p.locator('.module-1 p:nth-last-child(2) a');await primary.hover();const hover=await primary.evaluate(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));check(w+' primary hover',hover.color==='rgb(255, 255, 255)'&&hover.bg==='rgb(6, 43, 91)',hover);await p.mouse.move(0,0);await primary.focus();await p.keyboard.press('Tab');check(w+' secondary keyboard focus',await p.locator('.module-1 p:last-child a').evaluate(e=>e===document.activeElement&&getComputedStyle(e).outlineWidth==='3px'));
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();check(w+' local link '+i,await p.evaluate(v=>localNavigationIntents.at(-1).href===v&&Object.keys(localNavigationIntents.at(-1).context).length===0,links[i].href));}await p.evaluate(()=>scrollTo(0,0));
if(w<1101){const b=p.locator('.menuButton'),m=p.locator('.mobileNav');await b.click();check(w+' menu entry isolation',await p.evaluate(()=>document.activeElement.textContent==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'));check(w+' menu targets',await m.locator('a').evaluateAll(as=>as.every(a=>a.getBoundingClientRect().width>=44&&a.getBoundingClientRect().height>=44)));await m.locator('a').last().focus();await p.keyboard.press('Tab');check(w+' menu forward cycle',await b.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(w+' menu reverse cycle',await m.locator('a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(w+' menu Escape return',await restored(p)&&await b.evaluate(e=>e===document.activeElement));await b.click();await b.click();check(w+' menu Close return',await restored(p));for(let i=0;i<8;i++){await b.click();const href=await m.locator('a').nth(i).getAttribute('href');await m.locator('a').nth(i).click();check(w+' menu link exit '+i,await restored(p)&&await p.evaluate(v=>localNavigationIntents.at(-1).href===v,href));}await b.click();await p.mouse.move(w-5,h-5);const sy=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,600);await p.waitForTimeout(100);check(w+' menu background wheel lock',sy===await p.evaluate(()=>scrollY));await p.setViewportSize({width:1200,height:h});check(w+' breakpoint close',await restored(p));await p.setViewportSize({width:w,height:h});}
await p.locator('#cookie-trigger').click();const close=p.locator('[data-cookie-close]'),policy=p.locator('.cookie-layer a');check(w+' cookie modal entry',await close.evaluate(e=>e===document.activeElement)&&await p.locator('dialog').evaluate(e=>e.matches(':modal')));check(w+' cookie bounds/targets',await p.locator('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight&&[...e.querySelectorAll('a,button')].every(a=>a.getBoundingClientRect().width>=44&&a.getBoundingClientRect().height>=44)}));await p.keyboard.press('Shift+Tab');check(w+' cookie reverse cycle',await policy.evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(w+' cookie forward cycle',await close.evaluate(e=>e===document.activeElement));await policy.click();check(w+' cookie policy intent',await p.evaluate(()=>localNavigationIntents.at(-1).href==='/cookie-policy/'));await close.click();check(w+' cookie Close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');check(w+' cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&await p.locator('dialog').evaluate(e=>!e.open));await ctx.close();}
const lum=c=>{const v=c.match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*v[0]+.7152*v[1]+.0722*v[2]};const pairs=[['334155','ffffff'],['334155','f5f8fb'],['062b5b','ffffff'],['062b5b','f5f8fb'],['ffffff','008078'],['008078','ffffff'],['ffffff','062b5b'],['ffffff','031b3a'],['d4e0eb','031b3a']].map(([fg,bg])=>({fg,bg,ratio:(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05)}));check('all used text contrast pairs >=4.5',pairs.every(x=>x.ratio>=4.5),pairs);check('no external network requested',network.length===0,network);fs.writeFileSync(out+'diagnostic_support/initial-runtime.json',JSON.stringify({mode:'SELF_CHECK / INITIAL',executor:'/root/gate4_eu_trade_execute',status:'RUNTIME_CHECK_COMPLETE_VISUAL_PENDING',source:id(source),browser:await browser.version(),render:{widths:[1440,768,390],heights:[900,900,844],dpr:1},records,evidenceTypes:['ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION'],finishedAt:new Date().toISOString()},null,2));await browser.close();console.log(JSON.stringify({checks:records.length,failures:0,source:id(source),heights:records.filter(x=>x.name.includes('font/media')).map(x=>({w:x.details.width,h:x.details.height,sections:x.details.sections}))}));
})().catch(async e=>{if(browser)await browser.close();fs.writeFileSync(out+'diagnostic_support/initial-failure-'+Date.now()+'.json',JSON.stringify({error:e.stack,records},null,2));console.error(e);process.exitCode=1});
