const fs=require('fs'),crypto=require('crypto'),root='D:/23MySec/',out=root+'pages/resources/eu-trade/04_planning/gate4-v0.1/';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const paths=[
'AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md',
'docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.7.md','agents/gate4-complete-visual/agent.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CONTRACT_V1.2.md',
'skills/brand-applied-visual-design/SKILL.md','skills/full-page-visual-composition/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/gate4-self-check.md','skills/layout-interaction-verification/references/core-risk-model.md',
'docs/architecture/GATE_WORKFLOW_V3.2.md','docs/architecture/PAGE_GATE_1_4_STANDARD_V2.2.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.4.md','docs/architecture/GATE_3_4_6_DELEGATED_CLOSURE_AUTHORITY_V1.0.md',
'docs/architecture/PAGE_REGISTRY_V0.2.md','research/keyword/11_page_keyword_master.csv','docs/page-playbooks/RESOURCE_PLAYBOOK_V0.1.md','docs/page-briefs/RES-TRADE-EU_EU_TITANIUM_DIOXIDE_TRADE_UPDATE_BRIEF_V0.1.md',
'docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','docs/architecture/GATE2_FIVE_RESOURCE_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md',
'brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','brand/visual/TIO2_MALAYSIA_PRIMARY_CTA_ACCESSIBILITY_ADDENDUM_V1.0.md','brand/logo/production/PRODUCTION_SVG_LOGO_MANIFEST_V1.0.md','docs/architecture/GLOBAL_HEADER_FOOTER_SPEC_V0.5.md','docs/architecture/GLOBAL_FOOTER_LEGAL_UTILITY_ADDENDUM_V1.0.md','docs/architecture/LEGAL_PRIVACY_NO_TERMS_TITAN_PATTERN_DECISION_V1.0.md','pages/legal-privacy/05_review/LEGAL_PRIVACY_CONV_DOC_POST_GATE9_CURRENT_AUTHORITY_MANIFEST_V1.3.md','pages/legal-privacy/05_review/SHARED-CONSENT_CURRENT_GATE9_BASELINE_MANIFEST_V1.1.md',
'pages/resources/eu-trade/RES-TRADE-EU_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md','pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE3_TO_GATE4_HANDOFF_V0.1.md','pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE3_PROJECT_CONTROL_REVIEW_V0.1.md','pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE3_PREAUTHORIZED_APPROVAL_AND_CLOSURE_V0.1.md',
'pages/resources/eu-trade/04_planning/RES-TRADE-EU_GATE2_CONTENT_SKELETON_V0.1.md','pages/resources/eu-trade/04_planning/RES-TRADE-EU_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','pages/resources/eu-trade/04_planning/RES-TRADE-EU_GATE2_CONTENT_CONTRACT_V0.2.md','pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md',
'pages/resources/eu-trade/04_planning/gate3-v0.1/RES-TRADE-EU_GATE3_WIREFRAME_V0.1.html','pages/resources/eu-trade/04_planning/gate3-v0.1/freeze-record.json','pages/resources/eu-trade/04_planning/gate3-v0.1/asset-inventory.json',
'docs/architecture/gate3-shared-consumer-v0.2/consumer-package.json','docs/architecture/gate3-shared-consumer-v0.2/shared-chrome.css','docs/architecture/gate3-shared-consumer-v0.2/shared-chrome-behavior.js','docs/architecture/gate3-shared-consumer-v0.2/shared-chrome-data.json','docs/architecture/gate3-shared-consumer-v0.2/shared-consent-data.json'];
const deps=['brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg','brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg'].map(p=>id(root+p)).concat(['dependencies/Inter-Variable.ttf','dependencies/Inter-OFL.txt'].map(p=>id(out+p)));
const source=id(out+'RES-TRADE-EU_GATE4_COMPLETE_VISUAL_V0.1.html'),inputs=paths.map(p=>id(root+p));
fs.writeFileSync(out+'input-index.json',JSON.stringify({workset_id:'RES-TRADE-EU-G4-WS-01',page_id:'RES-TRADE-EU',scope:'tio2-my',authority_manifest:root+'pages/resources/eu-trade/RES-TRADE-EU_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md',inputs,dependencies:deps,navigationOnly:['01_PROJECT_INDEX.md','00_PROJECT_STATUS.md'],authorityNote:'Current task authorizes this page Gate4 despite historical NOT_AUTHORIZED in upstream Manifest and handoff. No page facts, layout relationships or later authorization changed.'},null,2));
fs.writeFileSync(out+'workset.json',JSON.stringify({workset_id:'RES-TRADE-EU-G4-WS-01',page_id:'RES-TRADE-EU',executor:'/root/gate4_eu_trade_execute',input_index:out+'input-index.json',design_source:source.path,evidence_index:out+'evidence-index.json',authorization_scope:'User-authorized Gate4 production/self-check/freeze only; handoff to separately owned Gate5 independent visual review. No independent review, closure, Gate6 or implementation.',allowed_write_scope:[out,root+'pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE4_EXECUTION_SELF_CHECK_V0.1.md',root+'pages/resources/eu-trade/05_review/RES-TRADE-EU_GATE4_TO_GATE5_HANDOFF_V0.1.md'],direction:'VISUAL_DIRECTION_CHECKED',mode:'SELF_CHECK / INITIAL'},null,2));
const initial=JSON.parse(fs.readFileSync(out+'diagnostic_support/initial-runtime.json'));if(initial.source.sha256!==source.sha256||initial.records.some(r=>r.status!=='PASS'))throw Error('runtime not valid');
fs.writeFileSync(out+'preflight-record.json',JSON.stringify({status:'PASS_FOR_FORMAL_RENDER',executor:'/root/gate4_eu_trade_execute',checkedAt:new Date().toISOString(),source,runtime:id(out+'diagnostic_support/initial-runtime.json'),direction:id(out+'4A-visual-direction.md'),visualObservation:{method:'Transient native-width browser region viewing; no persistent segmented PNGs',coverage:[{width:1440,ranges:[[0,1800],[1600,3405],[3300,5103]]},{width:768,ranges:[[0,1900],[1800,3700],[3600,5500],[5200,5916]]},{width:390,ranges:[[0,1500],[1400,2900],[2850,4350],[4250,5750],[5650,7150],[7050,7707]]}],states:['768 Menu','390 Menu','1440 Cookie','768 Cookie','390 Cookie'],judgment:'All six modules, complete table and predicates, all seven assessment inputs, tax categories, sources/dates, owner actions and Footer actually viewed; no clipping, collision or anomalous gaps found. No media or new states invented.'},findings:[],unverified:['Native browser 200% zoom and physical touch','Other browser engines and screen readers','Live legal source refresh/TARIC and production links','Production consent storage, analytics and receiver behavior']},null,2));
fs.writeFileSync(out+'render-lock.json',JSON.stringify({lock_id:'RES-TRADE-EU-G4-LOCK-01',lockedAt:new Date().toISOString(),source,dependencies:deps,inputIndex:id(out+'input-index.json'),preflight:id(out+'preflight-record.json'),renderer:id(out+'diagnostic_support/render.cjs'),conditions:{browser:initial.browser,engine:'Chrome headless local-file',logicalWidths:[1440,768,390],logicalHeights:[900,900,844],dpr:1,font:'Inter Variable local TTF',media:'Two exact production Logo SVGs',normalState:'pointer at 0,0; blur; scroll top',menuState:'open by shared Menu action; viewport capture',cookieState:'open by Footer Cookie Settings; viewport capture',network:'No external requests'},formalAssetsExist:false},null,2));console.log(JSON.stringify({source,inputs:inputs.length,lock:id(out+'render-lock.json')}));
