const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/resources/eu-trade/04_planning/gate4-v0.1/',source=out+'RES-TRADE-EU_GATE4_COMPLETE_VISUAL_V0.1.html';
const mode=process.argv[2],width=+(process.argv[3]||390),y=+(process.argv[4]||0),height=+(process.argv[5]||1000);
const identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const ctx=await browser.newContext({viewport:{width,height:width===390?844:900},deviceScaleFactor:1});await ctx.route(/^https?:/,r=>r.abort());const p=await ctx.newPage();await p.goto(pathToFileURL(source).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(x=>x.decode()));});
if(mode==='sample'){await p.locator('table').scrollIntoViewIfNeeded();const b=await p.locator('table').boundingBox();const top=await p.evaluate(()=>document.querySelector('table').getBoundingClientRect().top+scrollY);await p.screenshot({path:out+'diagnostic_support/4A-390-table-predicates.png',fullPage:true,clip:{x:0,y:top-74,width,height:Math.min(1560,await p.locator('main').evaluate(e=>e.scrollHeight))}});console.log(JSON.stringify({source:identity(source),sample:identity(out+'diagnostic_support/4A-390-table-predicates.png')}));}
if(mode==='view'){await p.evaluate(v=>scrollTo(0,v),y);console.log((await p.screenshot({fullPage:true,clip:{x:0,y,width,height:Math.min(height,await p.evaluate(()=>document.documentElement.scrollHeight)-y)}})).toString('base64'));}
if(mode==='menu'||mode==='cookie'){await p.locator(mode==='menu'?'.menuButton':'#cookie-trigger').click();console.log((await p.screenshot()).toString('base64'));}
if(mode==='formal'){const lock=JSON.parse(fs.readFileSync(out+'render-lock.json','utf8'));if(identity(source).sha256!==lock.source.sha256)throw Error('source lock mismatch');let images=[];for(const w of [1440,768,390]){await p.setViewportSize({width:w,height:w===390?844:900});await p.goto(pathToFileURL(source).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(x=>x.decode()));});const take=async(state,fullPage)=>{const path=out+'approval_core/RES-TRADE-EU_G4_'+w+'-'+state+'.png';await p.screenshot({path,fullPage,animations:'disabled'});const z=fs.readFileSync(path);images.push({...identity(path),role:'STATIC_VISUAL',state,logicalViewport:{width:w,height:w===390?844:900},dpr:1,physicalWidth:z.readUInt32BE(16),physicalHeight:z.readUInt32BE(20),sourceSha256:lock.source.sha256});};await p.mouse.move(0,0);await p.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});await take('full',true);if(w<1101){await p.locator('.menuButton').click();await take('menu',false);await p.keyboard.press('Escape');}await p.locator('#cookie-trigger').click();await take('cookie',false);await p.keyboard.press('Escape');}fs.writeFileSync(out+'formal-assets.json',JSON.stringify({capturedAt:new Date().toISOString(),browser:await browser.version(),source:identity(source),images},null,2));console.log(JSON.stringify(images));}
await browser.close();})().catch(e=>{console.error(e);process.exitCode=1});
