import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';
const root='D:/23MySec',out=`${root}/pages/conversion/thank-you/04_planning/gate4-v0.1`;
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');const item=f=>({path:path.win32.normalize(f),bytes:fs.statSync(f).size,sha256:sha(f)});
const source=`${out}/CONV-THANK_GATE4_EDITABLE_SOURCE_V0.1.html`,preflight=`${out}/CONV-THANK_GATE4_PREFLIGHT_V0.1.json`,input=`${out}/CONV-THANK_GATE4_INPUT_INDEX_V0.1.json`,design=`${out}/CONV-THANK_GATE4_DESIGN_SOURCE_V0.1.json`;
const p=JSON.parse(fs.readFileSync(preflight,'utf8'));if(p.status!=='PASS'||p.checks.some(c=>c.status!=='PASS')||p.source.sha256!==sha(source))throw new Error('Hard preflight not complete against current source');
const old=`${root}/pages/conversion/thank-you/04_planning/gate3-v0.2/CONV-THANK_GATE3_RESPONSIVE_WIREFRAME_V0.2.html`;if(sha(old)!=='1c0b12a4b21f4eb3be2e2b9daed569c1d3f9e30752a5591127824569879a7b28')throw new Error('Approved Gate 3 V0.2 identity changed');
const inputJson=JSON.parse(fs.readFileSync(input,'utf8'));
const freeze={workset_id:'CONV-THANK-G4-WORKSET-20260908-01',freeze_id:'CONV-THANK-G4-FREEZE-20260908-01',status:'COMPLETE_VISUAL_FROZEN / DRAFT_FOR_PROJECT_CONTROL_REVIEW',executor:'/root/conv_thank_gate4_execute',source:item(source),derived_from:item(old),input_index:item(input),design_source:item(design),preflight:item(preflight),dependencies:inputJson.dependencies,render_conditions:{engine:'Google Chrome via Playwright',executable:'C:/Program Files/Google/Chrome/Application/chrome.exe',logical_viewports:[{width:1440,height:900},{width:768,height:900},{width:390,height:844}],dpr:1,reducedMotion:'reduce',network:'blocked',font:'bundled Inter variable',animations:'disabled for capture'},candidate_frozen_at:new Date().toISOString(),notes:['Gate 3 V0.2 is the only structural source; old V0.1 is excluded.','Formal capture must be generated after this record and must bind this source identity.','Local success-state simulation is not proof of a production receiver or request receipt.']};
fs.rmSync(`${out}/approval_core`,{recursive:true,force:true});fs.mkdirSync(`${out}/approval_core`,{recursive:true});fs.writeFileSync(`${out}/CONV-THANK_GATE4_FREEZE_RECORD_V0.1.json`,JSON.stringify(freeze,null,2));console.log(JSON.stringify(freeze,null,2));
