// Independent reviewer; read original candidate, write only this review directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/resources/04_planning/d32-gate3-v0.1',out=__dirname;
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const read=n=>JSON.parse(fs.readFileSync(base+'/'+n,'utf8'));
const checks=[],observations=[],supplementary=[];
const ck=(id,ok,detail)=>checks.push({id,status:ok?'PASS':'FAIL',detail});
const frozen=read('RES-000_D32_FREEZE.json'),core=read('RES-000_D32_APPROVAL_CORE.json'),inputs=read('RES-000_D32_INPUTS.json');
const entries=[...frozen.sources,frozen.inputs,frozen.preflight,...core.assets,...core.redEvidence,...inputs.authority,...inputs.dependencies,...inputs.references];
const unique=[...new Map(entries.map(e=>[e.path,e])).values()];
for(const e of unique)ck('ID:'+e.path,fs.existsSync(e.path)&&fs.statSync(e.path).size===e.bytes&&hash(e.path)===e.sha256,{bytes:e.bytes,sha256:e.sha256});
const digest=crypto.createHash('sha256').update(core.assets.map(e=>`${e.path}\t${e.bytes}\t${e.sha256}\n`).join('')).digest('hex');
ck('ID:bundle',digest===core.bundleSha256&&digest==='ddeb7bbeaa82bb4df943bd270e94b1f8235461670026e840735de284b923d9c2',digest);
ck('ID:H0',hash(base+'/RES-000_D32_GATE3.html')==='b8ba906be4fca24c9af380da4c69d0d41295b9b9520317549f04c669637f208b');
const B=fs.readFileSync(root+'/pages/resources/04_planning/RES-000_CONTENT_ARCHITECTURE_V0.3.md','utf8');
const C=fs.readFileSync(root+'/pages/resources/04_planning/RES-000_SEO_GEO_SCHEMA_CONTRACT_V0.2.md','utf8');
const between=(start,end)=>B.split(start)[1].split(end)[0];
const exact=(start,end)=>[...between(start,end).matchAll(/`([^`]+)`/g)].map(m=>m[1]).filter(s=>!s.startsWith('#'));
const permanent=[...exact('### 4.2 Hero','### 4.3 Featured'),...exact('### 4.4 Three Decision Paths','### 4.5 Latest'),...exact('### 4.6 Evidence Standards','## 5. SEO')].filter(s=>s!=='START → SOURCING / TECHNICAL EVALUATION / TRADE & MARKET'&&s!=='FAQPage'&&s!=='QAPage');
const {renderSharedChrome}=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs');
const shared=renderSharedChrome({currentPageId:'RES-000',primaryLogoSrc:pathToFileURL(root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg').href,reverseLogoSrc:pathToFileURL(root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg').href});
const html=fs.readFileSync(base+'/RES-000_D32_GATE3.html','utf8');
for(const k of ['header','footer','dialog','style','behavior'])ck('SHARED:'+k,html.includes(shared[k]),'Exact neutral V0.2 output matched, not foreign page copy');
ck('H0:no-machine-item',!/(ItemList|FAQPage|QAPage|application\/ld\+json|Non-China Titanium Dioxide Supply Guide|FIXTURE ONLY|LOCAL SIMULATION)/.test(html));
ck('C:noindex-preview',html.includes('noindex,nofollow')&&C.includes('visual draft does not authorize indexing'));
ck('H0:no-page-form',!/<form\b/i.test(html));
const {projectInventory}=require(base+'/RES-000_D32_RESOURCE_MODEL.cjs');
const now='2026-09-21',r={pageId:'REVIEW-FIXTURE',scope:'tio2-my',language:'en',mappingApproved:true,urlApproved:true,contentApproved:true,claimApproved:true,publicApproved:true,routeLive:true,url:'/resources/review-fixture/',canonical:'https://tio2products.com/resources/review-fixture/',title:'REVIEW fixture',summary:'REVIEW fixture summary',type:'guide',lastReviewed:'2026-09-20',nextReviewDue:'2026-10-20',featured:true};
const empty=p=>p.items.length===0&&p.featured.length===0&&p.latest.length===0&&p.itemList===null&&p.heroTarget==='#research-paths';
ck('MODEL:H0',empty(projectInventory([],now)));ck('MODEL:H2',projectInventory([r],now).featured.length===1&&projectInventory([r],now).latest.length===0&&projectInventory([r],now).itemList.length===1);
for(const k of ['mappingApproved','urlApproved','contentApproved','claimApproved','publicApproved','routeLive'])for(const v of [false,undefined,'true'])ck('MODEL:gate:'+k+':'+String(v),empty(projectInventory([{...r,[k]:v}],now)));
for(const [k,v] of [['scope','mytio2'],['language','pt'],['canonical','https://tio2malaysia.com'+r.url],['url','/products/'],['title',''],['summary',''],['lastReviewed','2026-12-01'],['nextReviewDue',now],['eventReviewPending',true],['type','unknown']])ck('MODEL:exclude:'+k,empty(projectInventory([{...r,[k]:v}],now)));
for(const [type,days] of [['guide',180],['technical',90],['trade',30]]){const date=new Date(now+'T00:00:00Z');date.setUTCDate(date.getUTCDate()-days);ck('MODEL:max:'+type,empty(projectInventory([{...r,type,lastReviewed:date.toISOString().slice(0,10),technicalAudit:true,nonEquivalenceAudit:true}],now)));}
const t={...r,type:'trade',freshness:'CURRENT',officialSource:true,market:'Fixture Brazil',topic:'Fixture topic',sourceName:'Fixture source',sourceUrl:'https://example.invalid/source',sourceDate:'2026-09-19',productOriginScope:'Fixture scope',statusCopy:'Reviewed fixture',factAnalysisLabel:'Fixture summary',freshnessOwner:'Fixture reviewer'};
ck('MODEL:H4',projectInventory([t],now).items.length===1);
for(const k of ['market','topic','officialSource','sourceName','sourceUrl','sourceDate','productOriginScope','statusCopy','factAnalysisLabel','freshnessOwner'])ck('MODEL:trade-atomic:'+k,empty(projectInventory([{...t,[k]:null}],now)));
for(const state of ['REVIEW_DUE','STALE_HOLD','WITHDRAWN'])ck('MODEL:H5:'+state,empty(projectInventory([{...t,freshness:state}],now)));
for(const k of ['technicalAudit','nonEquivalenceAudit'])ck('MODEL:technical:'+k,empty(projectInventory([{...r,type:'technical',technicalAudit:true,nonEquivalenceAudit:true,[k]:false}],now)));
const many=Array.from({length:5},(_,i)=>({...r,pageId:'FIXTURE-'+i,url:'/resources/review-'+i+'/',canonical:'https://tio2products.com/resources/review-'+i+'/',lastReviewed:'2026-09-'+(20-i)}));
const h3=projectInventory([...many,many[0]],now);ck('MODEL:H3-max-and-unique',h3.featured.length===3&&h3.latest.length===2&&h3.items.length===5&&new Set(h3.itemList.map(x=>x.url)).size===5);ck('MODEL:H3-order',h3.items.map(x=>x.pageId).join()==='FIXTURE-0,FIXTURE-1,FIXTURE-2,FIXTURE-3,FIXTURE-4');
supplementary.push({id:'GATE6-TYPED-DATE-HARDENING',sample:'Trade sourceDate=2026-02-30',acceptedByPlanningNotation:projectInventory([{...t,sourceDate:'2026-02-30'}],now).items.length===1,scope:'Planning predicate is not a production validation schema. Typed calendar-date validity and official-source verification must be specified/tested at Gate6/8; no actual H0 content affected.'});
(async()=>{const browser=await chromium.launch();
for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(base+'/RES-000_D32_GATE3.html').href);await page.evaluate(()=>document.fonts.ready);
const text=await page.locator('main').innerText();ck(width+':copy-from-B',permanent.every(t=>text.includes(t)),permanent.filter(t=>!text.includes(t)));
ck(width+':H2-order',(await page.locator('main h2').allTextContents()).join('|')==='Choose the right research path|How we use evidence|Buyer questions');
ck(width+':no-conditional-roots',await page.locator('#featured-resources,#latest-research,.res-resource').count()===0);
ck(width+':single-H1',await page.locator('h1').count()===1);ck(width+':title',await page.title()==='Titanium Dioxide Procurement Resources | TiO2 Malaysia');ck(width+':description',await page.locator('meta[name="description"]').getAttribute('content')===B.match(/\| Meta description \| `([^`]+)`/)[1]);
const g=await page.evaluate(()=>{const visible=e=>!!(e.getBoundingClientRect().width&&e.getBoundingClientRect().height)&&getComputedStyle(e).visibility!=='hidden';const rect=e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height});const targets=[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.innerText,...rect(e)}));const bad=[...document.querySelectorAll('main p,main h1,main h2,main h3,main a')].filter(visible).filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.x<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1||(s.overflowY==='hidden'&&e.scrollHeight>e.clientHeight+1)}).map(e=>e.innerText);const h=document.querySelector('h1'),s=getComputedStyle(h),hero=document.querySelector('[data-component="RootPageHero"]');return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,targets,bad,h1:{size:s.fontSize,weight:s.fontWeight,spacing:s.letterSpacing,lines:Math.round(h.getBoundingClientRect().height/parseFloat(s.lineHeight))},hero:{variant:hero.dataset.variant,padding:getComputedStyle(hero).padding},media:rect(document.querySelector('.res-hero-media')),header:rect(document.querySelector('header')),images:[...document.images].every(x=>x.complete&&x.naturalWidth>0)};});observations.push(g);
ck(width+':geometry',g.scrollWidth===width&&g.bad.length===0,g.bad);ck(width+':targets44',g.targets.every(t=>t.w>=44&&t.h>=44),g.targets.filter(t=>t.w<44||t.h<44));ck(width+':hero',g.hero.variant==='hub-dark'&&g.h1.size===(width===1440?'56px':width===768?'44px':'36px')&&g.h1.weight==='700'&&(width===390?g.h1.lines===4&&g.h1.spacing==='normal':g.h1.lines<=3),g.h1);ck(width+':decorative-media',width>900?g.media.h>0:g.media.h===0);ck(width+':images-font',g.images&&await page.evaluate(()=>document.fonts.check('16px Inter')));ck(width+':header',g.header.h===(width===1440?84:64));
ck(width+':nav-surfaces',await page.locator('.desktopNav [aria-current="page"]').count()===1&&await page.locator('.mobileNav [aria-current="page"]').count()===1);ck(width+':footer-legal',await page.locator('footer a[href="/privacy-policy/"]').count()===1&&await page.locator('footer a[href="/ms/privacy-policy/"]').count()===1&&await page.locator('footer a[href="/cookie-policy/"]').count()===1&&await page.locator('footer [aria-current]').count()===0);
await page.locator('.hero-action').focus();ck(width+':focus-visible',await page.locator('.hero-action').evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));await page.locator('.hero-action').click();ck(width+':action-target',new URL(page.url()).hash==='#research-paths');
if(width<1000){await page.locator('.menuButton').click();ck(width+':menu-open-focus',await page.locator('.mobileNav').isVisible()&&await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));ck(width+':menu-isolation',await page.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert));await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');ck(width+':menu-tab-loop',await page.locator('.menuButton').evaluate(e=>e===document.activeElement));await page.keyboard.press('Shift+Tab');ck(width+':menu-reverse-loop',await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');ck(width+':menu-escape-return',await page.locator('.mobileNav').isHidden()&&await page.locator('.menuButton').evaluate(e=>e===document.activeElement));await page.locator('.menuButton').click();await page.evaluate(()=>document.querySelector('.mobileNav').addEventListener('click',e=>e.preventDefault(),{once:true}));await page.locator('.mobileNav a[href="/resources/"]').click();ck(width+':menu-select-return',await page.locator('.mobileNav').isHidden()&&await page.locator('.menuButton').evaluate(e=>e===document.activeElement)&&!(await page.locator('main').evaluate(e=>e.inert)));await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:960});await page.waitForFunction(()=>document.querySelector('.mobileNav').hidden);ck(width+':menu-breakpoint',!(await page.locator('main').evaluate(e=>e.inert)));await page.setViewportSize({width,height:960});}
await page.locator('#cookie-trigger').click();ck(width+':cookie-open',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));ck(width+':cookie-inactive',(await page.locator('dialog').innerText()).includes('No optional Analytics'));await page.keyboard.press('Shift+Tab');ck(width+':cookie-reverse',await page.locator('dialog a').evaluate(e=>e===document.activeElement));await page.keyboard.press('Tab');ck(width+':cookie-loop',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await page.keyboard.press('Escape');ck(width+':cookie-return',await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));ck(width+':errors',errors.length===0,errors);await page.close();}
for(const [state,width] of [['H2',1440],['H2',390],['H4',1440],['H4',768],['H4',390],['H4',720]]){const p=await browser.newPage({viewport:{width,height:960}});await p.goto(pathToFileURL(base+'/RES-000_D32_'+state+'_LOCAL_SIMULATION.html').href);await p.evaluate(()=>document.fonts.ready);ck(state+width+':simulation-mark',(await p.locator('.res-fixture-banner').innerText()).includes('LOCAL SIMULATION'));ck(state+width+':anchor',await p.locator('.hero-action').getAttribute('href')==='#featured-resources');ck(state+width+':geometry',await p.evaluate(()=>document.documentElement.scrollWidth===innerWidth));ck(state+width+':featured-once',await p.locator('#featured-resources .res-resource').count()===1);if(state==='H2'){ck(state+width+':no-latest',await p.locator('#latest-research').count()===0);const vals=[...between('### 4.3 Featured Resources','### 4.4 Three Decision Paths').matchAll(/`([^`]+)`/g)].map(m=>m[1]).filter(t=>t!=='RES-ORIGIN');const rendered=await p.locator('#featured-resources').innerText();ck(state+width+':copy',vals.every(t=>rendered.includes(t)),vals.filter(t=>!rendered.includes(t)));}else{ck(state+width+':fields',await p.locator('[data-fixture="trade"] dt').count()===8);ck(state+width+':metadata-full',await p.locator('[data-fixture="trade"]').evaluate(el=>[...el.querySelectorAll('dt,dd,p,h3,a')].every(e=>e.scrollWidth<=e.clientWidth+1&&getComputedStyle(e).textOverflow!=='ellipsis')));}await p.close();}
const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:960}});await nojs.goto(pathToFileURL(base+'/RES-000_D32_GATE3.html').href);ck('NOJS:five-full-answers',await nojs.locator('.res-faq article').count()===5&&await nojs.locator('.res-faq p').evaluateAll(ps=>ps.every(p=>p.getBoundingClientRect().height>0)));await nojs.close();await browser.close();
const result={reviewer:'/root/about_root_d32',author:'/root/res_root_d32',mode:'INDEPENDENT_GATE3_REVIEW',time:new Date().toISOString(),candidateHtmlSha256:hash(base+'/RES-000_D32_GATE3.html'),bundleSha256:digest,uniqueIdentityFiles:unique.length,checks,observations,supplementary,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length};fs.writeFileSync(path.join(out,'independent-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL'),supplementary}));process.exitCode=result.failed?1:0;
})().catch(e=>{console.error(e);process.exit(2)});
