const fs=require('fs'),p=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const src='D:/23MySec/pages/products/04_planning/d32-gate4-v0.1',out=__dirname,sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
(async()=>{let r={review:'PRODUCT-D32-G5-IVR-01',type:'ACTUAL_RUNTIME_LOCAL_PLANNING',identity:[],views:[],actions:[]};for(const name of ['source-freeze.json']){let j=JSON.parse(fs.readFileSync(p.join(src,name)));for(const f of [j.source,...j.dependencies||[],...j.inputs||[],...j.assets||[],...j.preflight?[j.preflight]:[]])r.identity.push({path:f.path,pass:sha(f.path)===f.sha256&&fs.statSync(f.path).size===f.bytes});}const b=await chromium.launch({headless:true});r.browser=b.version();for(const w of [1440,768,390]){const q=await b.newPage({viewport:{width:w,height:1000}});await q.goto(pathToFileURL(p.join(src,'product-visual.html')).href);await q.evaluate(()=>document.fonts.ready);r.views.push(await q.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth-innerWidth,h1:getComputedStyle(document.querySelector('h1')).fontSize,spacing:getComputedStyle(document.querySelector('h1')).letterSpacing,rows:[...document.querySelectorAll('.gradeRow')].map(e=>e.innerText),faq:[...document.querySelectorAll('.answer')].map(e=>e.textContent),small:[...document.querySelectorAll('main a,main button')].filter(e=>e.getClientRects().length&&!e.closest('[hidden]')).filter(e=>e.getBoundingClientRect().width<44||e.getBoundingClientRect().height<44).map(e=>e.textContent),clipped:[...document.querySelectorAll('.gradeRow p,.step p')].filter(e=>e.getBoundingClientRect().bottom>e.parentElement.getBoundingClientRect().bottom).map(e=>e.textContent)})));
for(const a of ['Coatings','Plastics','Masterbatch','Printing Inks','Paper','Specialty Materials','Not Sure']){await q.locator(`[data-app="${a}"]`).focus();await q.keyboard.press('Enter');r.actions.push({w,a,results:await q.locator('#results').innerText(),focus:await q.evaluate(()=>document.activeElement.dataset.app)});}await q.locator('[data-app="Coatings"]').click();for(let i=0;i<5;i++){let x=q.locator('.question button').nth(i),v=await x.getAttribute('aria-expanded');await x.focus();await q.keyboard.press('Space');r.actions.push({w,faq:i,toggled:v!==await x.getAttribute('aria-expanded')});}
if(w<1101){await q.locator('.menuButton').click();await q.locator('.mobileNav a').last().focus();await q.keyboard.press('Tab');r.actions.push({w,menuWrap:await q.evaluate(()=>document.activeElement.className),inert:await q.locator('main').evaluate(e=>e.inert)});await q.keyboard.press('Escape');r.actions.push({w,escape:await q.evaluate(()=>({focus:document.activeElement.className,inert:document.querySelector('main').inert}))});await q.locator('.menuButton').click();await q.locator('.mobileNav a').first().evaluate(e=>e.addEventListener('click',v=>v.preventDefault(),{once:true}));await q.locator('.mobileNav a').first().click();r.actions.push({w,linkClose:await q.locator('.mobileNav').evaluate(e=>e.hidden)});}
await q.locator('#cookie-trigger').click();await q.keyboard.press('Shift+Tab');r.actions.push({w,cookieWrap:await q.evaluate(()=>document.activeElement.textContent)});await q.keyboard.press('Escape');r.actions.push({w,cookieReturn:await q.evaluate(()=>document.activeElement.id)});
for(const n of [2,1,0]){await q.evaluate(n=>window.planningState.routes(n,n,false),n);r.actions.push({w,type:'LOCAL_SIMULATION',n,cr:await q.locator('.special').innerText(),grid:await q.locator('.processCards').evaluate(e=>e.getBoundingClientRect().height)});}await q.evaluate(()=>window.planningState.routes(2,3,true));await q.reload();await q.evaluate(()=>document.fonts.ready);let h=await q.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<h;y+=950){await q.evaluate(y=>scrollTo(0,y),y);}await q.close();}await b.close();fs.writeFileSync(p.join(out,'observations.json'),JSON.stringify(r,null,2));console.log(JSON.stringify({identityFailures:r.identity.filter(x=>!x.pass),views:r.views.map(v=>({width:v.width,overflow:v.overflow,small:v.small,clipped:v.clipped,rows:v.rows.length,faq:v.faq.length}))}));})();



