const fs=require('fs'),crypto=require('crypto');
const root='D:/23MySec',base=root+'/pages/markets/belgium',out=base+'/04_planning/gate4-v1.0',id='MARKET-EU-BE';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),ident=p=>({path:p,bytes:fs.statSync(p).size,sha256:sha(p)}),write=(name,data)=>fs.writeFileSync(out+'/'+name,typeof data==='string'?data:JSON.stringify(data,null,2));
const old=JSON.parse(fs.readFileSync(base+'/05_review/gate4-project-control-v0.1/independent-review/input-identities.json','utf8'));const unique=[...new Map(old.records.map(r=>[r.path,r])).values()];const checked=unique.map(r=>({...ident(r.path),expectedSha256:r.expectedSha256,match:sha(r.path)===r.expectedSha256}));write('diagnostic_support/upstream-identity-recheck.json',{records:checked,differences:checked.filter(r=>!r.match)});
const manifest=base+'/'+id+'_CURRENT_GATE_BASELINE_MANIFEST_V0.6.md';fs.copyFileSync(manifest,out+'/diagnostic_support/admission-manifest-v0.6-snapshot.md');
let html=fs.readFileSync(base+'/04_planning/gate3-v0.1/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html','utf8');
const css=`
/* Belgium visual refinement; shared Chrome CSS and markup are unchanged. */
main{font-size:18px;line-height:1.65}main .breadcrumbs{color:#334155;font-size:14px;padding-top:18px;padding-bottom:18px}
main section{padding-top:64px;padding-bottom:64px}main h1{font-size:60px;line-height:1.1;letter-spacing:-.035em;max-width:990px}main h2{font-size:38px;line-height:1.2;max-width:900px}main h3{font-weight:600}
main section:first-of-type{background:#f5f8fb;border-top:0;padding-top:60px;padding-bottom:60px}main section:first-of-type .reading{border-left:4px solid #008078;padding-left:28px}main section:first-of-type p:not(.action){font-size:20px;line-height:1.65;max-width:960px}
main section:nth-of-type(2){background:#fff}main section:nth-of-type(3){background:#f5f8fb}main section:nth-of-type(4){background:#fff}main section:nth-of-type(5){background:#f5f8fb}
main .reading{max-width:1200px}main .contexts{gap:28px;margin:36px 0}main .context{padding:26px 24px;background:#fff;border:1px solid #d9e2ec;border-top:3px solid #008078;border-radius:10px;box-shadow:0 2px 6px rgb(6 43 91 / 3%)}main .context p{font-size:17px;line-height:1.65}main .context h3{font-size:24px}
main .action a{border-radius:6px;background:#fff;color:#008078}main .action a[href='/request-a-quote/']{background:#008078;color:#fff}main a:hover{color:#062b5b;text-decoration-thickness:2px}main .action a:hover{background:#f5f8fb;color:#062b5b;border-color:#062b5b}main .action a[href='/request-a-quote/']:hover{background:#062b5b;color:#fff}main .action a:focus-visible{outline:3px solid #008078;outline-offset:4px}main .action.tertiary a{font-size:16px;background:transparent;border:0}
main [data-module='BE-04']>.reading>p:nth-of-type(2){border-left:3px solid #008078;padding:12px 18px;background:#f5f8fb;color:#062b5b;font-weight:500}
main [data-module='BE-04'] p:not(.action) a{display:inline-block;vertical-align:baseline;line-height:44px;min-height:44px}main .punctuation-keep{white-space:nowrap}
main li::marker{color:#008078}main li{padding-top:7px;padding-bottom:7px}
@media(max-width:1100px){main section{padding-top:48px;padding-bottom:48px}main section:first-of-type{padding-top:44px;padding-bottom:44px}main h1{font-size:46px}main h2{font-size:32px}main .contexts{gap:18px}main .context{grid-template-columns:190px 1fr;padding:24px;gap:26px}main .context h3{font-size:23px}main section:first-of-type p:not(.action){font-size:19px}}
@media(max-width:560px){main{font-size:17px}main section{padding-top:36px;padding-bottom:36px}main .breadcrumbs{font-size:14px}main h1{font-size:36px;line-height:1.12}main h2{font-size:28px}main section:first-of-type{padding-top:32px;padding-bottom:36px}main section:first-of-type .reading{padding-left:18px}main section:first-of-type p:not(.action){font-size:18px}main .context{padding:24px 20px}main .context h3{font-size:23px}main .contexts{margin:28px 0}main .action.tertiary a{white-space:normal;text-align:left;line-height:1.5}main [data-module='BE-04']>.reading>p:nth-of-type(2){padding:12px 16px}}
`;
html=html.replace('</style>',css+'</style>').replace('<a href="/request-a-quote/">quotation request</a>.','<span class="punctuation-keep"><a href="/request-a-quote/">quotation request</a>.</span>');
write(id+'_GATE4_COMPLETE_VISUAL_V1.0.html',html);
const additions=['docs/architecture/GATE_WORKFLOW_V3.1.md','docs/architecture/PAGE_GATE_1_4_STANDARD_V2.1.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md','agents/gate4-complete-visual/agent.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CONTRACT_V1.0.md','skills/brand-applied-visual-design/SKILL.md','skills/full-page-visual-composition/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/core-risk-model.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','docs/architecture/LEGAL_PRIVACY_NO_TERMS_TITAN_PATTERN_DECISION_V1.0.md'];
write(id+'_GATE4_INPUT_INDEX_V1.0.json',{workset_id:'BE-G4-COMPLETE-20260907-01',authority_manifest:ident(manifest),upstream:checked,current_methods_and_contracts:additions.map(p=>ident(root+'/'+p)),note:'Old upstream identities preserved as historical approved combination; current Gate4 methods are independently bound.'});
write(id+'_GATE4_WORKSET_V1.0.json',{page_id:id,workset_id:'BE-G4-COMPLETE-20260907-01',authority_manifest:manifest,input_index:out+'/'+id+'_GATE4_INPUT_INDEX_V1.0.json',design_source:out+'/'+id+'_GATE4_COMPLETE_VISUAL_V1.0.html',evidence_index:out+'/'+id+'_GATE4_EVIDENCE_INDEX_V1.0.json',allowed_write_scope:base,authorization_scope:'2026-09-07 user continuation resumes PAUSED_BEFORE_FREEZE for merged Gate4 4A/4B and independent-review submission; no final user approval or Gate6 authorization.'});
console.log(JSON.stringify({source:ident(out+'/'+id+'_GATE4_COMPLETE_VISUAL_V1.0.html'),upstreamChecked:checked.length,differences:checked.filter(r=>!r.match)}));
