const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const lock=JSON.parse(fs.readFileSync(path.join(dir,'source-lock.json')));for(const x of lock.files)if(hash(x.path)!==x.sha256)throw Error('Source changed '+x.path);
const b=await chromium.launch(),p=await b.newPage({deviceScaleFactor:1}),assets=[];fs.mkdirSync(path.join(dir,'approval_core'),{recursive:true});
async function load(w,q=''){await p.setViewportSize({width:w,height:1000});await p.goto(pathToFileURL(path.join(dir,'market-visual.html')).href+q);await p.evaluate(()=>document.fonts.ready);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await p.waitForFunction(w=>innerWidth===w,w);}
async function shot(name,loc,full=false){const file=path.join(dir,'approval_core',name+'.png');await p.mouse.move(0,0);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));if(loc)await loc.screenshot({path:file});else await p.screenshot({path:file,fullPage:full});const bytes=fs.readFileSync(file);assets.push({path:file,state:name,logical_width:p.viewportSize().width,dpr:1,physical_width:bytes.readUInt32BE(16),physical_height:bytes.readUInt32BE(20),bytes:bytes.length,sha256:hash(file),source_sha256:lock.source_identity});}
for(const w of [1440,1024,768,390,320]){await load(w);await shot('FULL_'+w,null,true);const brazil=p.locator('.marketCard').filter({has:p.getByRole('heading',{name:'Brazil',exact:true})});await shot('BRAZIL_'+w,brazil);if(w===320){await p.locator('a[href="/markets/brazil/"]').focus();await p.keyboard.press('Tab');await shot('PT_KEYBOARD_FOCUS_320',brazil);}}
await load(390,'?pt=unavailable');await shot('PT_UNAVAILABLE_BRAZIL_390',p.locator('.marketCard').filter({has:p.getByRole('heading',{name:'Brazil',exact:true})}));
for(const x of lock.files)if(hash(x.path)!==x.sha256)throw Error('Source changed during capture '+x.path);
fs.writeFileSync(path.join(dir,'approval_core/asset-index.json'),JSON.stringify({renderer:await b.version(),font:'local Inter Variable',viewportHeight:1000,source_identity:lock.source_identity,assets},null,2));console.log(JSON.stringify({assets:assets.length,dimensions:assets.map(x=>({state:x.state,w:x.physical_width,h:x.physical_height}))}));await b.close();})();
