// TARGETED SELF_CHECK. Detect missing/misdirected/localized discovery, hidden graph, clipping and regressions.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,red=process.argv.includes('--red'),file=path.resolve(dir,red?'../d32-gate4-v0.2/market-visual.html':'market-visual.html');
const expected=['/markets/european-union/','/markets/germany/','/markets/italy/','/markets/spain/','/markets/poland/','/markets/netherlands/','/markets/belgium/','/markets/united-kingdom/','/markets/india/','/markets/brazil/','/pt-br/markets/brazil/'];
const checks=[],measurements=[];const test=(name,pass,actual)=>checks.push({name,pass,actual});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const b=await chromium.launch(),p=await b.newPage({deviceScaleFactor:1}),old=await b.newPage();
async function load(page,file,width,query=''){await page.setViewportSize({width,height:1000});await page.goto(pathToFileURL(file).href+query);await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.waitForFunction(w=>innerWidth===w,w=width);}
for(const w of (red?[390]:[320,340,341,374,375,390,768,1024,1440])){
 await load(p,file,w);if(!red)await load(old,path.resolve(dir,'../d32-gate4-v0.2/market-visual.html'),w);
 const d=await p.evaluate(()=>{const a=document.querySelector('a[href="/pt-br/markets/brazil/"]'),hero=document.querySelector('.rootHero'),h=document.querySelector('h1'),e=hero.querySelector('.eyebrow'),r=x=>{const z=x.getBoundingClientRect();return{x:z.x,y:z.y,w:z.width,h:z.height,right:z.right,bottom:z.bottom}};const range=document.createRange();range.selectNodeContents(e);const er=[...range.getClientRects()].filter(x=>x.width);const graph=document.querySelector('#market-destination-graph');return{pt:a?{text:a.textContent,rect:r(a),parent:a.closest('article').querySelector('h3').textContent,style:{font:getComputedStyle(a).fontSize,decoration:getComputedStyle(a).textDecorationLine,color:getComputedStyle(a).color},visible:!!a.getClientRects().length}:null,market:[...document.querySelectorAll('[data-ready-action="market"]')].map(a=>a.getAttribute('href')),questions:document.querySelectorAll('[data-question]').length,h1:h.textContent,h1Lines:Math.round(h.getBoundingClientRect().height/parseFloat(getComputedStyle(h).lineHeight)),hero:r(hero),eyebrow:{size:getComputedStyle(e).fontSize,lines:new Set(er.map(x=>Math.round(x.y))).size,text:e.textContent},overflow:document.documentElement.scrollWidth>innerWidth,heroActions:hero.querySelectorAll('a').length,alternates:document.querySelectorAll('[hreflang]').length,graph:graph?JSON.parse(graph.textContent):null,copy:[...document.querySelectorAll('[data-copy],[data-delta]')].map(x=>[x.dataset.copy||x.dataset.delta,x.textContent]),sections:[...document.querySelectorAll('main [data-module]')].map(x=>({module:x.dataset.module,w:r(x).w,h:r(x).h})),chrome:document.querySelector('.header').outerHTML+document.querySelector('.footer').outerHTML};});
 test(w+': PT link discoverable under Brazil',!!d.pt&&d.pt.visible&&d.pt.text==='Português'&&d.pt.parent==='Brazil',d.pt);
 test(w+': 10 EN plus PT ordered',JSON.stringify(d.market)===JSON.stringify(expected),d.market);
 test(w+': Hub no hreflang',d.alternates===0,d.alternates);
 test(w+': no overflow',!d.overflow,d.overflow);
 test(w+': six questions and one Hero action',d.questions===6&&d.heroActions===1,{q:d.questions,cta:d.heroActions});
 test(w+': visible ItemList parity',!!d.graph&&JSON.stringify(d.graph.itemListElement.map(x=>new URL(x.url).pathname))===JSON.stringify(expected),d.graph);
 if(d.pt){test(w+': PT legible touch target',d.pt.rect.w>=44&&d.pt.rect.h>=44&&d.pt.rect.x>=0&&d.pt.rect.right<=w&&d.pt.style.decoration.includes('underline'),d.pt);await p.locator('a[href="/markets/brazil/"]').focus();await p.keyboard.press('Tab');test(w+': keyboard enters PT after EN',await p.locator('a[href="/pt-br/markets/brazil/"]').evaluate(a=>a===document.activeElement),null);test(w+': visible focus',await p.locator('a[href="/pt-br/markets/brazil/"]').evaluate(a=>parseFloat(getComputedStyle(a).outlineWidth)>=3),null);}
 if(!red){const prev=await old.evaluate(()=>{const r=x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height});return{hero:r(document.querySelector('.rootHero')),copy:[...document.querySelectorAll('[data-copy],[data-delta]')].map(x=>[x.dataset.copy||x.dataset.delta,x.textContent]),sections:[...document.querySelectorAll('main [data-module]')].map(x=>({module:x.dataset.module,...r(x)})),chrome:document.querySelector('.header').outerHTML+document.querySelector('.footer').outerHTML};});test(w+': approved copy unchanged',JSON.stringify(d.copy)===JSON.stringify(prev.copy),null);test(w+': shared Chrome unchanged',d.chrome===prev.chrome,null);test(w+': Hero geometry unchanged',d.hero.w===prev.hero.w&&d.hero.h===prev.hero.h,d.hero);test(w+': only selector natural height changes',d.sections.every((x,i)=>x.w===prev.sections[i].w&&(x.module==='DESTINATION_SELECTOR'||x.h===prev.sections[i].h)),d.sections);test(w+': narrow eyebrow retained',d.eyebrow.lines===1&&d.eyebrow.size===(w<=340?'11px':w<=374?'12px':'14px'),d.eyebrow);if(w===320||w===1024)test(w+': H1 approved lines',d.h1Lines===(w===320?3:2),d.h1Lines);}
 measurements.push({width:w,...d,chrome:undefined,copy:undefined});
}
if(!red){for(const [query,urls] of [['?state=none',[]],['?state=eu-only',[expected[0]]],['?state=support-only',[]],['?pt=unavailable',expected.slice(0,10)]]){await load(p,file,390,query);const d=await p.evaluate(()=>({urls:[...document.querySelectorAll('[data-ready-action="market"]')].map(a=>a.getAttribute('href')),graph:document.querySelector('#market-destination-graph')?JSON.parse(document.querySelector('#market-destination-graph').textContent).itemListElement.map(x=>new URL(x.url).pathname):[],pt:!!document.querySelector('a[href="/pt-br/markets/brazil/"]'),label:document.body.textContent.includes('Português')}));test(query+': visible action scope',JSON.stringify(d.urls)===JSON.stringify(urls),d);test(query+': graph same eligible scope',JSON.stringify(d.graph)===JSON.stringify(urls),d);test(query+': no empty Portuguese label',!d.pt&&!d.label,d);}
const nj=await b.newPage({javaScriptEnabled:false,viewport:{width:390,height:1000}});await nj.goto(pathToFileURL(file).href);test('noJS: PT real anchor',await nj.locator('a[href="/pt-br/markets/brazil/"]').count()===1,null);test('noJS: graph includes PT',await nj.locator('#market-destination-graph').evaluate(e=>JSON.parse(e.textContent).itemListElement.at(-1).url)==='https://tio2malaysia.com/pt-br/markets/brazil/',null);await nj.close();}
fs.mkdirSync(path.join(dir,'diagnostic_support'),{recursive:true});const result={mode:red?'RED_BASELINE':'GREEN_CANDIDATE',source:{path:file,sha256:hash(file)},renderer:await b.version(),passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks,measurements};fs.writeFileSync(path.join(dir,'diagnostic_support',red?'red.json':'green.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>!x.pass)}));await b.close();process.exitCode=result.failed?1:0;})();
