const fs=require('fs'),path=require('path'),crypto=require('crypto');
const dir=__dirname,root=path.resolve(dir,'../../../..'),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p));
const id=p=>{p=path.resolve(dir,p);return{path:p,bytes:fs.statSync(p).size,sha256:hash(p)}},write=(p,x)=>fs.writeFileSync(path.join(dir,p),JSON.stringify(x,null,2)+'\n'),check=xs=>{for(const x of xs)if(hash(x.path)!==x.sha256)throw Error('Changed '+x.path)},unique=xs=>[...new Map(xs.map(x=>[x.path,x])).values()];
const prior=path.resolve(dir,'../d32-gate4-v0.2'),old=read(path.join(prior,'freeze.json'));check([...old.files,old.evidence_index]);
if(process.argv[2]==='prepare'){
if(fs.existsSync(path.join(dir,'source-lock.json')))throw Error('Already locked');const green=read(path.join(dir,'diagnostic_support/green.json'));if(green.failed)throw Error('Not green');
const sources=['market-visual.html','localized-relation.css','relationship-projection.js','check.cjs','capture.cjs','pack.cjs'].map(id);
const inherited=read(path.join(prior,'source-lock.json')).files.filter(x=>/planning\.(css|js)$|visual\.css$|root-narrow-projection\.css$|\.ttf$|\.svg$|shared/.test(x.path));
const inputs=['pages/markets/MARKET-000_D32_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md','pages/markets/05_review/MARKET-000_D32_GATE6_REVIEW_CHALLENGE_V0.1.md','docs/architecture/TIO2_MY_23_PAGE_PUBLICATION_CONTRACT_FINALIZATION_V1.0.md','pages/markets/brazil/MARKET-BR-PT_CURRENT_GATE_BASELINE_MANIFEST_V0.15.md','docs/page-briefs/MARKET-000_MARKETS_BRIEF_V0.1.md','pages/markets/05_review/MARKET-000_D32_GATE5_TARGETED_RECHECK_R01_V0.1.md'].map(x=>id(path.join(root,x)));
write('input-index.json',{workset_id:'MARKET-000-D32-G4-V0.3-MKT-R003',priorBundle:old.bundle_id,priorFreeze:id(path.join(prior,'freeze.json')),inputs,controllerDesign:'2026-09-21 /root approved bounded design: Portuguese discovery under Explore Brazil, underline/44px/focus, no new card/Hero CTA, no Hub hreflang, eligible ItemList after Brazil EN; no production instruction'});
write('preflight.json',{status:'PASS_FOR_TARGETED_FORMAL_RENDER',passed:green.passed,failed:green.failed,evidence:id('diagnostic_support/green.json'),source_identity:sources[0].sha256,scope:'MKT-R003 relation + nine widths, copy/Chrome/Hero/section-height inheritance, keyboard and route-simulation graph parity; existing unrelated Gate5 coverage retained',formalScope:'5 full pages + 5 Brazil cards + PT focus320 + PT unavailable390',sourceType:'PROTOTYPE_ONLY',render:'Chromium/local Inter/DPR1/font-ready/two frames'});
write('source-lock.json',{source_identity:sources[0].sha256,files:unique([...sources,...inherited,...inputs,id('input-index.json'),id('preflight.json')])});console.log('SOURCE_LOCKED');
}else if(process.argv[2]==='complete'){
if(fs.existsSync(path.join(dir,'freeze.json')))throw Error('Already frozen');const lock=read(path.join(dir,'source-lock.json'));check(lock.files);const assets=read(path.join(dir,'approval_core/asset-index.json')).assets;check(assets);
const files=unique([...lock.files,id('source-lock.json'),id('approval_core/asset-index.json'),...assets.map(x=>id(x.path)),id('response.md'),id('../../05_review/MARKET-000_D32_GATE4_GATE5_HANDOFF_V0.3.md'),id('diagnostic_support/red.json'),id('diagnostic_support/green.json'),id(path.join(prior,'freeze.json')),old.evidence_index]);
check(files);const bundle=crypto.createHash('sha256').update(files.map(x=>({p:path.relative(root,x.path).replaceAll('\\','/'),h:x.sha256})).sort((a,b)=>a.p.localeCompare(b.p)).map(x=>x.p+'\0'+x.h+'\n').join('')).digest('hex');
write('evidence-index.json',{workset_id:'MARKET-000-D32-G4-V0.3-MKT-R003',status:'CHANGES_READY_FOR_TARGETED_REVIEW',bundle_id:bundle,source_identity:lock.source_identity,formal_asset_index:id('approval_core/asset-index.json'),response:id('response.md'),prior_bundle:old.bundle_id,newFormal:assets,inheritedCoverage:'Original Gate5 V0.1 plus R01 targeted recheck; no old fullpage image relabelled as current since selector height changes'});
write('freeze.json',{time:new Date().toISOString(),status:'CHANGES_READY_FOR_TARGETED_REVIEW',bundle_id:bundle,source_identity:lock.source_identity,prior_bundle:old.bundle_id,algorithm:'SHA256 sorted D23-relative path + NUL + SHA256 + LF; evidence-index separately bound',files,evidence_index:id('evidence-index.json')});console.log(JSON.stringify({bundle,source:lock.source_identity,records:files.length+1,assets:assets.length}));
}else throw Error('prepare or complete');
