const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',base=root+'/pages/markets/netherlands',out=base+'/04_planning/gate3-v0.1',id='MARKET-EU-NL';
const neutral=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:hash(p)});
const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2));
const approved={A:base+'/04_planning/'+id+'_GATE2_CONTENT_SKELETON_V0.1.md',B:base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md',C:base+'/04_planning/'+id+'_GATE2_CONTENT_CONTRACT_V0.1.md',brief:root+'/docs/page-briefs/MARKET-EU-NL_NETHERLANDS_BRIEF_V0.2.md',review:base+'/05_review/'+id+'_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md',manifest:base+'/'+id+'_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md',authorization:root+'/docs/architecture/GATE3_EIGHT_PAGE_SERIAL_CONTROL_V1.2.md',gate2Approval:root+'/docs/architecture/GATE2_EIGHT_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md',methodBaseline:root+'/docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md'};
const expected={A:'76bea448cd9d0b9f13992902182a62f46f9462644721aa74add0defdc8028cf0',B:'05945e5609fb12ffb04e791d4f4e2c2778b25158bb81f57d05e6d518503bff72',C:'dcd67673cbb0142f5a1ed8d8eadd2a372d43ef5828472f986072cba18347c351',review:'b36b3ac41dfd459fd04e4c623bdef4906774d340d28cf2483505f65bd8ae38d2'};
for(const [k,h] of Object.entries(expected))if(hash(approved[k])!==h)throw Error('approved mismatch '+k);
const pkg=JSON.parse(fs.readFileSync(neutral+'/consumer-package.json','utf8'));
for(const f of pkg.files)if(hash(neutral+'/'+f.path)!==f.sha256)throw Error('shared mismatch '+f.path);
fs.mkdirSync(out+'/dependencies',{recursive:true});
for(const f of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(neutral+'/'+f,out+'/dependencies/'+f);
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';
const shared=require(neutral+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
const input={pageId:id,siteScope:'tio2-my',status:'DIAGNOSTIC_CANDIDATE_NOT_FROZEN',createdAt:new Date().toISOString(),approvedInputs:Object.fromEntries(Object.entries(approved).map(([k,p])=>[k,identity(p)])),sharedConsumer:{...identity(neutral+'/consumer-package.json'),version:pkg.version,currentPageId:'MARKET-000',files:pkg.files.map(f=>({...identity(neutral+'/'+f.path),role:f.role})),owners:Object.fromEntries(Object.entries(pkg.authority).map(([k,p])=>[k,identity(p)]))},dependencies:[...['Inter-Variable.ttf','Inter-OFL.txt'].map(f=>({...identity(out+'/dependencies/'+f),origin:identity(neutral+'/'+f)})),identity(primary),identity(reverse)],methods:['agents/gate3-execution/agent.md','skills/responsive-wireframe-design/SKILL.md','skills/layout-interaction-verification/SKILL.md'].map(p=>identity(root+'/'+p))};
save(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',input);
save(out+'/'+id+'_GATE3_TASK_INPUT_CARD_V0.1.md',`# ${id} Gate 3 task input card\n\nExecution role; DRAFT_FOR_PROJECT_CONTROL_REVIEW. Batch G3-8PAGE-SERIAL-01 page 3 only. Current Manifest V0.4 is the Gate 2 input pointer; serial control V1.2 supplies the later explicit Gate 3 authorization. Stop after execution handoff; controller owns approval, closure and Gate 3→4 handoff.\n\nExact paths, bytes, SHA-256, approved A V0.1 / B V0.2 / C V0.1 / Brief V0.2 / Review V0.1 and shared owners are in [input binding](${id}_GATE3_INPUT_BINDING_V0.1.json). B excluding its document-control HTML comment is the sole visible page copy. Historic draft labels and C's B V0.1 link are superseded by the exact approved combination in Manifest V0.4 and G2-8PAGE-APPROVAL-01, not by source edits.\n\nMarket procurement page, EN, /markets/netherlands/, current Markets. Fresh shared consumer V0.2 rendering with original approved production SVG paths; font and license copied as hash-identical durable snapshots. No business-page template.\n\nState matrix: 1440×900, 768×900, 390×844 at DPR 1, full pages; 768/390 open Menu; three Cookie no_optional_analytics dialogs. No page forms, selectors, FAQ, errors or success state. Links only record local intent. RFQ carries source page plus visible/editable Netherlands destination contract; DOC carries source page only. Actual receiving behavior is untested.\n\nOutput_dir: ${out}. Design report: ${out}/${id}_GATE3_DESIGN_METHOD_REPORT_V0.1.md. Self-check: ${base}/05_review/${id}_GATE3_EXECUTION_SELF_CHECK_V0.1.md. Necessary diagnostics and render helpers remain within this page. No Gate 2/shared source/other-page/root status edits.\n\nRisks: long VVVF inline attribution and limitation; three application prompts retain separate objects and order; single Grade document rule and exact COO sentence; Netherlands destination context and after-submit boundary.\n`);
save(out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md',`# ${id} responsive wireframe design method\n\nDRAFT / diagnostic work in progress. Input: task input card and binding. Applied responsive-wireframe-design V0.2 and layout-interaction-verification V0.2.\n\nNL-01 Hero → supplier/origin/context and primary RFQ, secondary Products. NL-02 → source-context introduction then distinct Coatings, Printing Inks, Plastics and Masterbatch prompts. NL-03 → neutral product review. NL-04 → document cardinality, one exact COO sentence and request/Hub actions. NL-05 → quotation prerequisites, four-item brief, after-submit and primary CTA.\n\nDesktop uses a focused reading flow with three parallel application columns. Tablet keeps body full-width and application prompts in sequential wide rows. Mobile is fully single-column, buttons remain at their owning modules. VVVF link stays inline with its source claim and limitation. No copy rewrite, media, new state or local form. Full evidence and findings will be completed after actual preflight and formal image readback.\n`);
const copy=fs.readFileSync(approved.B,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim();
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');
const chunks=copy.split(/\n\s*\n/);let content='',sec=0,inPrompts=false;
for(const c of chunks){if(c.startsWith('# ')){sec=1;content+='<section data-module="NL-01" class="hero"><div class="reading"><h1>'+inline(c.slice(2))+'</h1>';continue}
if(c.startsWith('## ')){if(inPrompts){content+='</div></div>';inPrompts=false;}content+='</div></section>';sec++;content+='<section data-module="NL-0'+sec+'"><div class="reading"><h2>'+inline(c.slice(3))+'</h2>';continue}
if(c.startsWith('### ')){if(!inPrompts){content+='<div class="prompts"><div>';inPrompts=true;}else content+='</div><div>';content+='<h3>'+inline(c.slice(4))+'</h3>';continue}
if(sec===0){content+='<nav class="breadcrumbs" aria-label="Breadcrumb">'+inline(c)+'</nav>';continue}
if(c.startsWith('- ')){content+='<ul>'+c.split('\n').map(l=>'<li>'+inline(l.slice(2))+'</li>').join('')+'</ul>';continue}
const action=/^\[[^\]]+\]\([^)]+\)$/.test(c);content+='<p'+(action?' class="action"':'')+'>'+inline(c)+'</p>';
}content+='</div></section>';
const css=`*{box-sizing:border-box}body{margin:0;background:#fff;color:#334155;font-family:Inter,Arial,sans-serif}main{font-size:18px;line-height:1.7}main .breadcrumbs{max-width:1200px;margin:auto;padding:24px 0;font-size:14px;line-height:1.8;color:#64748b}main a{color:#008078;text-underline-offset:4px;min-width:44px;min-height:44px;display:inline-flex;align-items:center}main a[href^="https:"]{display:inline;padding:14px 0}main a:focus-visible{outline:3px solid #008078;outline-offset:4px}main section{padding:64px max(32px,calc((100% - 1200px)/2));border-top:1px solid #d9e2ec}main .reading{max-width:1080px}main section:nth-of-type(even){background:#f5f8fb}main h1,main h2,main h3{color:#062b5b;line-height:1.2;margin:0 0 24px;letter-spacing:-.025em}main h1{font-size:52px;max-width:940px}main h2{font-size:34px;max-width:900px}main h3{font-size:24px;margin-bottom:14px}main p{margin:0 0 22px;max-width:900px}main .hero p:not(.action){font-size:20px;line-height:1.65;max-width:940px}main .action{display:inline-flex;vertical-align:middle;margin:8px 16px 0 0}main .action a{min-height:48px;padding:11px 20px;border:1px solid #008078;border-radius:6px;text-decoration:none;font-size:16px;font-weight:600}main .action a[href="/request-a-quote/"]{background:#008078;color:#fff}main .prompts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:32px;margin-top:36px}main .prompts>div{border-top:3px solid #c8d7e4;padding-top:24px;min-width:0}main .prompts p{font-size:17px;margin:0}main ul{max-width:900px;padding-left:24px;margin:0 0 24px}main li{padding:5px 0 5px 6px}@media(max-width:1250px){main .breadcrumbs{padding-left:32px;padding-right:32px}}@media(max-width:1100px){main section{padding:48px 32px}main h1{font-size:42px}main h2{font-size:30px}main .prompts{grid-template-columns:1fr;gap:28px}main .prompts>div{display:grid;grid-template-columns:190px 1fr;gap:26px}main .prompts h3{font-size:23px}main .hero p:not(.action){font-size:19px}}@media(max-width:560px){main{font-size:17px;line-height:1.7}main .breadcrumbs{padding:16px 20px;font-size:13px}main section{padding:36px 20px}main h1{font-size:34px}main h2{font-size:27px}main h3{font-size:23px}main .hero p:not(.action){font-size:18px}main .prompts>div{display:block}main .action{display:flex;margin:12px 0 0}main .action a{width:100%;justify-content:center}main p{margin-bottom:20px}}`;
const local=`window.__navigationIntents=[];document.addEventListener('click',event=>{const a=event.target.closest('a[href]');if(!a)return;event.preventDefault();const href=a.getAttribute('href');const context={source_page_id:'MARKET-EU-NL'};if(href==='/request-a-quote/')context.destination_country={value:'Netherlands',visible:true,editable:true};window.__navigationIntents.push({href,context:['/request-a-quote/','/request-documents/'].includes(href)?context:null,kind:'LOCAL_SIMULATION_NOT_RECEIVED'});});`;
save(out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Titanium Dioxide Supplier Netherlands | TiO2 Malaysia</title><style>${shared.style}\n${css}</style></head><body>${shared.header}<main>${content}</main>${shared.footer}${shared.dialog}<script>${shared.behavior}\n${local}</script></body></html>`);
save(out+'/diagnostic_support/build-result.json',{source:identity(out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html'),inputBinding:identity(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json'),approvedInputsVerified:true,sharedFilesVerified:true});console.log(JSON.stringify({out,source:identity(out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html')}));
