const fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const base='D:/23MySec/pages/markets/netherlands',out=base+'/04_planning/gate3-v0.1',id='MARKET-EU-NL',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:hash(p)}),save=(p,x)=>fs.writeFileSync(p,typeof x==='string'?x:JSON.stringify(x,null,2));
const binding=read(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json');const stage=process.argv[2];
const preflightPath=out+'/'+id+'_GATE3_PREFLIGHT_RECORD_V0.1.json',freezePath=out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json';
if(stage==='preflight'){
const r=read(out+'/diagnostic_support/render-r1/runtime-checks.json');if(r.failed.length||r.errors.length)throw Error('runtime failed');
for(const f of [...Object.values(binding.approvedInputs),...binding.dependencies,...binding.sharedConsumer.files,...Object.values(binding.sharedConsumer.owners),...binding.methods])if(hash(f.path)!==f.sha256)throw Error('identity mismatch '+f.path);
const visual={role:'EXECUTION_SELF_CHECK',type:'STATIC_VISUAL',time:new Date().toISOString(),source:identity(source),openedFullPages:r.images.filter(x=>x.state==='FULL'),openedStates:r.images.filter(x=>x.state!=='FULL'),openedClips:fs.readdirSync(out+'/diagnostic_support/render-r1').filter(n=>n.startsWith('clip-')).map(n=>identity(out+'/diagnostic_support/render-r1/'+n)),observations:['All five modules and Footer visible in each complete overview and overlapping native-resolution clips.','VVVF source is inline, wraps at 390, remains beside its qualified member-company sector statement.','Three application objects read left-to-right at 1440; labeled rows at 768; single column at 390.','Documents cardinality paragraphs, exact COO occurrence and alternate routes visible.','Four RFQ bullets and after-submit explanation visible; no shipping/tariff/customs promise added.','Menus show eight entries, current Markets, Close and fixed RFQ. Cookie dialog has full minimal no_optional_analytics copy and two actions.','No clipping, collisions, hidden body text or anomalous fixed blank region found. The final 390 diagnostic clip is a redundant 7px footer tail; preceding clip already covers it.'],findings:[]};save(out+'/diagnostic_support/preflight-visual-readback.json',visual);
const checks=Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks','functionalColors'].map(k=>[k,'PASS']));
save(preflightPath,{status:'PASS_FOR_FORMAL_RENDER',role:'EXECUTION_PREFLIGHT_NOT_INDEPENDENT_APPROVAL',time:new Date().toISOString(),candidate:identity(source),approvedInputs:binding.approvedInputs,dependencies:binding.dependencies,sharedConsumer:binding.sharedConsumer,inputBinding:identity(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json'),checks,formalExportsGenerated:false,evidence:[identity(out+'/diagnostic_support/render-r1/runtime-checks.json'),identity(out+'/diagnostic_support/preflight-visual-readback.json')],render:{browser:r.browser,viewports:r.viewports,dpr:1},findings:[],limitations:['Local link intent only; no receiving page/production request.','Native browser zoom, real devices and assistive technology not tested.']});
const checker='D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs';const output=cp.execFileSync(process.execPath,[checker,preflightPath],{encoding:'utf8'});save(out+'/diagnostic_support/preflight-checker-result.json',JSON.parse(output));console.log(output);
}
if(stage==='freeze'){
const p=read(preflightPath),c=read(out+'/diagnostic_support/preflight-checker-result.json');if(p.status!=='PASS_FOR_FORMAL_RENDER'||c.status!=='PASS_FOR_FORMAL_RENDER'||p.candidate.sha256!==hash(source))throw Error('No valid preflight');
if(fs.existsSync(out+'/approval_core')&&fs.readdirSync(out+'/approval_core').length)throw Error('Formal exports precede freeze');
save(freezePath,{status:'FROZEN_FOR_PROJECT_CONTROL_REVIEW',role:'EXECUTION_FREEZE_NOT_GATE_APPROVAL',frozenAt:new Date().toISOString(),source:identity(source),approvedInputs:binding.approvedInputs,sharedConsumer:binding.sharedConsumer,dependencies:binding.dependencies,preflight:identity(preflightPath),inputBinding:identity(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json'),formalExportsExistedAtFreeze:false});console.log(JSON.stringify(read(freezePath).source));
}
