const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/markets/netherlands',out=base+'/04_planning/gate3-v0.1',id='MARKET-EU-NL',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const mode=process.argv[2]||'diagnostic',dir=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/render-r1';fs.mkdirSync(dir,{recursive:true});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(p,o)=>fs.writeFileSync(p,JSON.stringify(o,null,2));
const copy=fs.readFileSync(base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'').trim();
const norm=s=>s.replace(/\s+/g,' ').trim(),plain=s=>s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/^#{1,3} /gm,'').replace(/^- /gm,'');
const expected={text:norm(plain(copy)),headings:[...copy.matchAll(/^#{1,3} (.+)$/gm)].map(x=>x[1]),links:[...copy.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(x=>({label:x[1],href:x[2]}))};
const result={role:'EXECUTION_SELF_CHECK',mode,source:{path:source,bytes:fs.statSync(source).size,sha256:sha(source)},time:new Date().toISOString(),evidenceTypes:['ACTUAL_RUNTIME','STATIC_VISUAL_PENDING','SOURCE_INSPECTION','LOCAL_SIMULATION'],checks:[],images:[],viewports:[],blockedRequests:[],errors:[]};
function check(key,value,detail){result.checks.push({key,status:value?'PASS':'FAIL',detail});}
const settle=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
async function shot(p,w,state,full=true){const filename=(mode==='formal'?id+'_GATE3_':'diag-')+w+'_'+state+'_V0.1.png';await p.screenshot({path:dir+'/'+filename,fullPage:full});result.images.push({path:dir+'/'+filename,viewport:w,state,sha256:sha(dir+'/'+filename)});}
async function controls(p,key){const targets=await p.locator('a,button').evaluateAll(nodes=>nodes.filter(e=>e.getClientRects().length&&!e.closest('[inert]')&&getComputedStyle(e).visibility!=='hidden').map(e=>{const r=e.getBoundingClientRect();return {text:e.textContent.trim(),width:r.width,height:r.height}}));check(key,targets.every(e=>e.width>=43.99&&e.height>=43.99),targets);}
(async()=>{let browser;try{
if(mode==='formal'){const f=JSON.parse(fs.readFileSync(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json','utf8'));if(f.source.sha256!==sha(source))throw Error('freeze mismatch');if(fs.readdirSync(dir).length)throw Error('formal exports already exist');}
browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});result.browser=browser.version();
for(const w of [1440,768,390]){const h=w===390?844:900,context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await context.route(/^https?:/,route=>{result.blockedRequests.push(route.request().url());return route.abort()});const p=await context.newPage();p.on('pageerror',e=>result.errors.push(e.message));await p.goto(pathToFileURL(source).href);await settle(p);
const actual=await p.locator('main').evaluate(e=>({text:e.innerText,headings:[...e.querySelectorAll('h1,h2,h3')].map(n=>n.textContent),links:[...e.querySelectorAll('a')].map(a=>({label:a.textContent,href:a.getAttribute('href')})),modules:[...e.querySelectorAll('section[data-module]')].map(s=>s.dataset.module)}));
check(w+' exact B bidirectional',norm(actual.text)===expected.text,{expected:expected.text,actual:norm(actual.text)});check(w+' headings and href order',JSON.stringify(actual.headings)===JSON.stringify(expected.headings)&&JSON.stringify(actual.links)===JSON.stringify(expected.links),actual);
check(w+' five modules',JSON.stringify(actual.modules)===JSON.stringify(['NL-01','NL-02','NL-03','NL-04','NL-05']),actual.modules);
const geo=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,header:document.querySelector('header').getBoundingClientRect().height,clipped:[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return /hidden|clip/.test(s.overflowY)&&e.scrollHeight>e.clientHeight+1}).map(e=>e.tagName),overflow:[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left<-.5||r.right>innerWidth+.5)}).map(e=>e.tagName),images:[...document.images].map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0}))}));
check(w+' geometry and assets',geo.scrollWidth===w&&geo.clipped.length===0&&geo.overflow.length===0&&geo.images.every(i=>i.loaded)&&geo.header===(w===1440?84:64),geo);result.viewports.push({width:w,height:h,fullHeight:geo.height});await controls(p,w+' full touch targets');
check(w+' page risk relationships',await p.evaluate(()=>{const s=document.querySelector('[data-module="NL-02"]'),d=document.querySelector('[data-module="NL-04"]'),q=document.querySelector('[data-module="NL-05"]');return s.querySelector('a').href==='https://www.vvvf.nl/brancheorganisatie'&&s.querySelector('a').parentElement.textContent.endsWith('they do not determine which TiO2 grade to use.')&&[...s.querySelectorAll('h3')].map(x=>x.textContent).join('|')==='Coatings|Printing Inks|Plastics and Masterbatch'&&d.textContent.split('A Certificate of Origin is available upon request.').length===2&&d.textContent.includes('form does not assign document types to those additional Grades')&&q.querySelectorAll('li').length===4&&q.textContent.includes('our team will review your requirements and contact you using the information provided.')&&document.querySelectorAll('main form,main input,main select,main details,main table').length===0}), 'VVVF scope, three distinct prompts, exact COO once, Grade mapping and four RFQ requirements');
check(w+' function colors',await p.locator('main a').evaluateAll(a=>a.every(e=>{const c=getComputedStyle(e);return c.color===(e.closest('.action')&&e.getAttribute('href')==='/request-a-quote/'?'rgb(255, 255, 255)':'rgb(0, 128, 120)')})), 'main light links Teal / filled RFQ white');
check(w+' current mapping',await p.evaluate(()=>[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].every(e=>e.textContent==='Markets')&&document.querySelectorAll('.desktopNav [aria-current]').length===1&&document.querySelectorAll('.mobileNav [aria-current]').length===1&&document.querySelectorAll('footer [aria-current]').length===0));
await shot(p,w,'FULL');if(mode!=='formal'){let n=0;for(let y=0;y<geo.height;y+=750){n++;const target=dir+'/clip-'+w+'-'+String(n).padStart(2,'0')+'.png';await p.screenshot({path:target,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,geo.height-y)}});}}
for(let i=0;i<expected.links.length;i++){const a=p.locator('main a').nth(i);await a.click();const intent=await p.evaluate(()=>window.__navigationIntents.at(-1));const href=expected.links[i].href,expectedContext=href==='/request-a-quote/'?{source_page_id:id,destination_country:{value:'Netherlands',visible:true,editable:true}}:href==='/request-documents/'?{source_page_id:id}:null;check(w+' main link '+i,intent.href===href&&JSON.stringify(intent.context)===JSON.stringify(expectedContext),intent);}
await p.evaluate(()=>scrollTo(0,0));
if(w<1101){const toggle=p.locator('.menuButton'),links=p.locator('.mobileNav a');await toggle.click();await settle(p);check(w+' menu entry',await p.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('.menuButton').textContent==='Close'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'));await controls(p,w+' menu touch targets');check(w+' menu border',await toggle.evaluate(e=>getComputedStyle(e).borderColor==='rgb(0, 128, 120)'));await shot(p,w,'MENU',false);
await links.last().focus();await p.keyboard.press('Tab');check(w+' menu forward loop',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(w+' menu reverse loop',await links.last().evaluate(e=>e===document.activeElement));await p.mouse.move(w-10,h-10);await p.mouse.wheel(0,250);await p.waitForTimeout(120);check(w+' menu body scroll lock',await p.evaluate(()=>scrollY===0));await p.keyboard.press('Escape');await settle(p);check(w+' menu escape restore',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&!document.querySelector('footer').inert&&!document.querySelector('.logoLink').inert&&!document.querySelector('.headerRfq').inert&&document.body.style.overflow===''&&document.activeElement===document.querySelector('.menuButton')));
await p.mouse.wheel(0,180);await p.waitForTimeout(120);check(w+' background scroll restored',await p.evaluate(()=>scrollY>0));await p.evaluate(()=>scrollTo(0,0));await toggle.click();await toggle.click();check(w+' Close button exit',await p.locator('.mobileNav').evaluate(e=>e.hidden));
for(let i=0;i<8;i++){await toggle.click();const href=await links.nth(i).getAttribute('href');await links.nth(i).click();await settle(p);check(w+' menu selection '+i,await p.evaluate(href=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''&&window.__navigationIntents.at(-1).href===href,href));}
await toggle.click();await p.setViewportSize({width:1440,height:h});await settle(p);check(w+' desktop breakpoint closes menu',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width:w,height:h});await settle(p);
}
const trigger=p.locator('#cookie-trigger'),close=p.locator('[data-cookie-close]'),policy=p.locator('.cookie-layer a');await trigger.click();await settle(p);check(w+' cookie first focus',await close.evaluate(e=>e===document.activeElement));await controls(p,w+' cookie touch targets');check(w+' cookie action colors',await p.locator('.cookie-actions > *').evaluateAll(es=>es.every(e=>{const c=getComputedStyle(e);return c.color==='rgb(0, 128, 120)'&&c.borderColor==='rgb(0, 128, 120)'})));await shot(p,w,'COOKIE',false);await p.keyboard.press('Shift+Tab');check(w+' cookie reverse loop',await policy.evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(w+' cookie forward loop',await close.evaluate(e=>e===document.activeElement));await policy.click();check(w+' cookie policy intent',await p.evaluate(()=>window.__navigationIntents.at(-1).href==='/cookie-policy/'));await close.click();await settle(p);check(w+' cookie close restore',await trigger.evaluate(e=>e===document.activeElement)&&await p.locator('.cookie-layer').evaluate(e=>!e.open));await trigger.click();await p.keyboard.press('Escape');await settle(p);check(w+' cookie Escape restore',await trigger.evaluate(e=>e===document.activeElement)&&await p.locator('.cookie-layer').evaluate(e=>!e.open));await context.close();
}
check('no external requests/errors',result.blockedRequests.length===0&&result.errors.length===0,{blocked:result.blockedRequests,errors:result.errors});
}catch(e){result.errors.push(e.stack);}finally{if(browser)await browser.close();result.failed=result.checks.filter(c=>c.status==='FAIL');result.status=result.failed.length||result.errors.length?'FAIL':'RUNTIME_PASS_PENDING_VISUAL';save(dir+'/runtime-checks.json',result);console.log(JSON.stringify({status:result.status,failed:result.failed.map(f=>f.key),errors:result.errors,viewports:result.viewports,images:result.images.map(i=>i.path)}));if(result.status==='FAIL')process.exitCode=1;}})();
