// Execution SELF-CHECK using layout-interaction-verification. Candidate read-only.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),assert=require('assert'),{pathToFileURL}=require('url');
const{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',out=__dirname,candidate=root+'/pages/markets/poland/04_planning/gate3-v0.1';
const source=candidate+'/MARKET-EU-PL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',copy=root+'/pages/markets/poland/04_planning/MARKET-EU-PL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md';
const norm=s=>s.replace(/\s+/g,' ').trim(),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const blocks=fs.readFileSync(copy,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim().split(/\r?\n\s*\r?\n/);
const expected={headings:blocks.filter(t=>/^#{1,3} /.test(t)).map(t=>norm(t.replace(/^#+ /,''))),paragraphs:blocks.filter(t=>!t.startsWith('#')&&!t.startsWith('[')).map(norm),links:[...blocks.join('\n').matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({label:m[1],href:m[2]}))};
const evidence={role:'EXECUTION_SELF_CHECK_NOT_INDEPENDENT_REVIEW',source,sourceSha256:hash(source),copy,copySha256:hash(copy),expected,renderer:null,widths:[],interactions:[],snapshots:[],findings:[],requests:[],errors:[]};
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});evidence.renderer=await b.version();const p=await b.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});await p.route(/^https?:/,r=>{evidence.requests.push(r.request().url());r.abort()});
const note=(id,details)=>evidence.findings.push({id,...details});
async function capture(name,clip){const f=path.join(out,name+'.png');await p.screenshot({path:f,fullPage:!!clip,...(clip?{clip}:{})});evidence.snapshots.push({path:f,sha256:hash(f),bytes:fs.statSync(f).size});}
try{for(const width of[1440,768,390]){await p.setViewportSize({width,height:1000});await p.goto(pathToFileURL(source).href);await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()))});
const actual=await p.evaluate(()=>({headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>e.textContent.replace(/\s+/g,' ').trim()),paragraphs:[...document.querySelectorAll('main p')].map(e=>e.textContent.replace(/\s+/g,' ').trim()),links:[...document.querySelectorAll('main a')].map(a=>({label:a.textContent.trim(),href:a.getAttribute('href')}))}));assert.deepEqual(actual,expected);
const geometry=await p.evaluate(()=>{const visible=e=>e.getClientRects().length&&!e.closest('[hidden], [inert]')&&getComputedStyle(e).visibility!=='hidden';const controls=[...document.querySelectorAll('a,button')].filter(visible).map(e=>({label:e.textContent.trim()||e.getAttribute('aria-label'),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));const overflow=[...document.querySelectorAll('main *,header *,footer *')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5}).map(e=>({tag:e.tagName,text:e.textContent.slice(0,70)}));return{viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,headerHeight:document.querySelector('.header').getBoundingClientRect().height,logo:{w:document.querySelector('.logo').getBoundingClientRect().width,h:document.querySelector('.logo').getBoundingClientRect().height},font:document.fonts.check('17px Inter'),controls,small:controls.filter(c=>c.w<44||c.h<44),overflow,modules:[...document.querySelectorAll('.pl-module')].map(e=>({id:e.id,y:e.offsetTop,h:e.getBoundingClientRect().height})),prohibited:[...document.querySelectorAll('main form,main table,main details,main input')].length,footerAt:document.querySelector('footer').offsetTop}});
evidence.widths.push({width,actual,geometry});if(geometry.small.length)note('PL-G3-SC-01-'+width,{severity:'IMPORTANT',location:'interactive targets',actual:geometry.small,expected:'at least 44×44'});assert.equal(geometry.scrollWidth,width);assert.deepEqual(geometry.overflow,[]);assert.equal(geometry.prohibited,0);assert.equal(geometry.headerHeight,width===1440?84:64);assert.equal(geometry.font,true);assert.equal(geometry.logo.w,width===1440?180:120);
for(let y=0,n=1;y<geometry.height;y+=750,n++){await capture('full-'+width+'-segment-'+n,{x:0,y,width,height:Math.min(850,geometry.height-y)});}
for(const a of await p.locator('main a').all()){await a.click();}const recorded=await p.evaluate(()=>window.planningNavigation);assert.deepEqual(recorded,expected.links);evidence.interactions.push({width,type:'body-link-intents',recorded,scope:'clicks intercepted locally; no destination loaded and no prefill/receipt proven'});
await p.evaluate(()=>scrollTo(0,0));if(width!==1440){await p.locator('.menuButton').click();assert.equal(await p.locator('.menuButton').textContent(),'Close');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Home');assert.equal(await p.locator('.mobileNav [aria-current=page]').textContent(),'Markets');await p.locator('main a').first().evaluate(e=>e.focus());assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Home');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Request a Quote');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await capture('menu-'+width+'-focus-close');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Menu');assert.equal(await p.locator('.mobileNav').isVisible(),false);for(let i=0;i<8;i++){await p.locator('.menuButton').click();await p.locator('.mobileNav a').nth(i).click();assert.equal(await p.locator('.mobileNav').isVisible(),false);assert.equal(await p.evaluate(()=>document.querySelector('main').inert),false);}evidence.interactions.push({width,type:'mobile-menu',result:'Opened; Home initial focus; Close label; Tab wraps across Close and eight links; background rejects focus; Escape restores Menu focus; all 8 navigation intents close menu and restore background.'});}
await p.locator('#cookie-trigger').click();assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');assert.equal(await p.locator('.cookie-layer').getAttribute('open'),'');await p.locator('main a').first().evaluate(e=>e.focus());assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Read Cookie Policy');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.textContent),'Close');await capture('cookie-'+width+'-focus-close');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'cookie-trigger');await p.locator('#cookie-trigger').click();await p.locator('.cookie-layer button').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'cookie-trigger');evidence.interactions.push({width,type:'cookie-settings',result:'Current minimal layer opened; Close focus; background rejects focus; Tab wrap; Escape/Close restores Footer trigger; no analytics choices/storage writes or production claim.'});
await p.goto(pathToFileURL(source).href);await p.locator('main .body-action a').first().focus();await capture('body-cta-focus-'+width);await p.locator('main .body-action a').first().hover();await capture('body-cta-hover-'+width);
}
// Reflow equivalent to a 1440×1000 physical desktop at 200%: 720×500 CSS px @2x.
const z=await b.newPage({viewport:{width:720,height:500},deviceScaleFactor:2,reducedMotion:'reduce'});await z.goto(pathToFileURL(source).href);await z.evaluate(()=>document.fonts.ready);const zoom=await z.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,mediaReducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches,modules:document.querySelectorAll('.pl-module').length}));assert.equal(zoom.scrollWidth,720);await z.locator('.menuButton').click();await z.screenshot({path:path.join(out,'reflow-200pct-menu-720-css-at2x.png')});await z.keyboard.press('Escape');await z.locator('#cookie-trigger').click();await z.screenshot({path:path.join(out,'reflow-200pct-cookie-720-css-at2x.png')});evidence.interactions.push({type:'200%-equivalent-reflow',physical:'1440×1000',logical:'720×500 @2x',result:zoom,limitation:'Emulated CSS viewport/reflow and pixel ratio, not browser UI zoom control or real device.'});await z.close();
assert.equal(hash(source),evidence.sourceSha256);const rendered=JSON.parse(fs.readFileSync(candidate+'/render-evidence.json','utf8'));assert.equal(rendered.sourceSha256,evidence.sourceSha256);for(const a of rendered.exports)assert.equal(hash(a.path),a.sha256);evidence.renderedIdentity=rendered.exports.map(a=>({path:a.path,sha256:hash(a.path),bytes:fs.statSync(a.path).size}));
}catch(e){evidence.errors.push(e.stack);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'measurements-and-actions.json'),JSON.stringify(evidence,null,2));await b.close();console.log(JSON.stringify({widths:evidence.widths.map(w=>({width:w.width,geometry:w.geometry})),findings:evidence.findings,errors:evidence.errors,actions:evidence.interactions.length},null,2))}})();
