const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',page=root+'/pages/resources/eu-trade',out=page+'/04_planning/gate3-v0.1',shared=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
for(const d of ['approval_core','diagnostic_support/render','dependencies'])fs.mkdirSync(out+'/'+d,{recursive:true});
if(fs.existsSync(out+'/freeze-record.json'))throw Error('Frozen; no rebuild');
const inputs=[['A','04_planning/RES-TRADE-EU_GATE2_CONTENT_SKELETON_V0.1.md','daebb10e9d26fcf622bcec6cb5fbad832279653d72dc0bc4c011ce9b0789dfa3'],['B','04_planning/RES-TRADE-EU_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','9e119c657d6eed9346ef132e0c2039a5c99327fb9087a273df689b8a2d8a8cb1'],['C','04_planning/RES-TRADE-EU_GATE2_CONTENT_CONTRACT_V0.2.md','64e46520ab226c1ec3eb16fa49a60804b8c45df16b545a7400198a90da77e49f'],['Review','05_review/RES-TRADE-EU_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md','77150dd75047552fe3cf3595f47eb4bcdbaae5c419616b1685d7dd772e2da2c1']].map(([role,p,sha])=>{const a=id(page+'/'+p);if(a.sha256!==sha)throw Error(role+' identity mismatch');return {...a,role}});
const pkg=JSON.parse(fs.readFileSync(shared+'/consumer-package.json','utf8'));const sharedFiles=pkg.files.map(f=>{const a=id(shared+'/'+f.path);if(a.sha256!==f.sha256)throw Error('package '+f.path);return {...a,role:f.role}});
const authorityPaths=['AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md','research/keyword/11_page_keyword_master.csv','docs/architecture/PAGE_REGISTRY_V0.2.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.0.md','docs/architecture/PAGE_GATE_1_5_STANDARD_V1.1.md','docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','docs/architecture/GATE2_FIVE_RESOURCE_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md','docs/architecture/GATE3_FIVE_RESOURCE_SERIAL_CONTROL_V1.1.md','docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md','agents/gate3-execution/agent.md','skills/responsive-wireframe-design/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/responsive-wireframe-design/references/preflight-freeze-evidence.md','skills/layout-interaction-verification/references/core-risk-model.md','docs/superpowers/specs/2026-09-07-gate3-to-gate4-handoff-contract-v0.1.md','docs/page-playbooks/RESOURCE_PLAYBOOK_V0.1.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','docs/page-briefs/RES-TRADE-EU_EU_TITANIUM_DIOXIDE_TRADE_UPDATE_BRIEF_V0.1.md','pages/resources/eu-trade/RES-TRADE-EU_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md','pages/resources/eu-trade/01_research/evidence/2026-09-07/RES-TRADE-EU_GATE2_FRESH_OFFICIAL_RECHECK_2026-09-07.md','pages/conversion/request-a-quote/04_planning/CONV-RFQ_CURRENT_GATE_BASELINE_MANIFEST_V2.8.md',...Object.values(pkg.authority).map(p=>p.slice(root.length+1))];
const authorities=authorityPaths.map(p=>id(root+'/'+p));
for(const f of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(shared+'/'+f,out+'/dependencies/'+f);
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',deps=[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(id);
const binding={pageId:'RES-TRADE-EU',status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',plannedUrl:'/resources/eu-titanium-dioxide-anti-dumping-duty/',siteScope:'tio2-my',currentPageId:'RES-000',approvedInputs:inputs,authorities,sharedConsumer:{...id(shared+'/consumer-package.json'),packageId:pkg.packageId,version:pkg.version},sharedFiles,dependencies:deps};save(out+'/input-binding.json',binding);
save(out+'/task-input-card.md','# RES-TRADE-EU Gate 3 task input card\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. Batch G3-5RESOURCE-SERIAL-01 page 2 only. Current Manifest V0.4; approved A V0.1, B V0.2, C V0.2 and Gate2 review V0.1 are actually hashed in input-binding.json.\n\nSix modules: dated Hero → measure/procedure → written scope/fixed-duty table → seven shipment inputs → separate tariff/VAT categories → correct owner/actions/official sources. Primary EU procurement, secondary legal source; Resources current. Neutral Shared Consumer V0.2 supplies Header/Footer/Cookie and production Logos; font/license are durable neutral-package snapshots.\n\nOutput: this gate3-v0.1 directory; execution self-check and evidence in this page 05_review. Real states are three full pages, two narrow menus and three Cookie dialogs. No page form/calculator/filter/result/FAQ.\n\nHighest risks: four producer/amount/code rows and immediately following legal-entity/invoice predicates; 2025/4 versus pending C/2026/4533; all dates; minimum 80% dry-matter/PRC scope and narrow Article 2/254 end use; Malaysia-origin statement cannot become shipment result. Design only visualizes the dated approved explanation, not a new legal recheck. C V0.2 requires 30-day/event-trigger refresh, next no later than 7 October 2026 and within two business days of relevant event, before implementation/publication.\n\nWorkflow: fresh diagnostic, actual browser and visual hard preflight, validator PASS_FOR_FORMAL_RENDER, freeze identity, first formal exports, actual readback and execution self-check. Stop for independent project-control review; no other page or Gate4.\n');
save(out+'/design-report.md','# RES-TRADE-EU design method report\n\nDESIGN_IN_PROGRESS. Applying responsive-wireframe-design V0.2 and layout-interaction-verification V0.2. Six approved modules in an editorial reading column; a semantic three-column table preserves every producer/duty/code tuple and surrounding predicates. Mobile readability must pass actual inspection before freeze.\n');
const raw=fs.readFileSync(inputs.find(a=>a.role==='B').path,'utf8');const copy=raw.split('## Buyer Clean public copy')[1].trim().replace(/^### Breadcrumb\s*/,'').replace(/^\*\*(?:Primary action:|Secondary action:)\*\*\s*/gm,'');
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');const inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');const plain=s=>s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/\*\*|`/g,'');
let html='',moduleCount=0,blocks=[],tableRows=[];
for(const block of copy.split(/\n\s*\n/)){if(/^#{1,3} /.test(block)){const m=block.match(/^(#{1,3}) (.*)$/s),level=m[1].length;if(level<3){if(moduleCount)html+='</section>';moduleCount++;html+=`<section class="module module-${moduleCount}" data-module="${moduleCount}">`;}html+=`<h${level}>${inline(m[2])}</h${level}>`;blocks.push({tag:'h'+level,text:plain(m[2])});}
else if(block.startsWith('|')){const rows=block.split('\n').filter(l=>!/^\|[- :|]+\|$/.test(l)).map(l=>l.split('|').slice(1,-1).map(x=>x.trim()));tableRows=rows.map(r=>r.map(plain));html+='<table aria-label="Fixed amounts stated in Regulation (EU) 2025/4"><thead><tr>';rows[0].forEach(t=>{html+='<th scope="col">'+inline(t)+'</th>';blocks.push({tag:'th',text:plain(t)})});html+='</tr></thead><tbody>';for(const row of rows.slice(1)){html+='<tr>';row.forEach((t,i)=>{html+='<td>'+inline(t)+'</td>';blocks.push({tag:'td',text:plain(t)})});html+='</tr>';}html+='</tbody></table>';}
else if(/^(?:- |\d\. )/.test(block)){const list=/^\d/.test(block)?'ol':'ul';html+='<'+list+'>';for(const line of block.split('\n')){const t=line.replace(/^(?:- |\d\. )/,'');html+='<li>'+inline(t)+'</li>';blocks.push({tag:'li',text:plain(t)})}html+='</'+list+'>';}
else{html+=`<p${moduleCount===0?' class="breadcrumb"':''}>${inline(block)}</p>`;blocks.push({tag:'p',text:plain(block)});}}
html+='</section>';const links=[...copy.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:m[1],href:m[2]}));save(out+'/diagnostic_support/expected-copy.json',{source:inputs.find(a=>a.role==='B'),blocks,links,tableRows,modules:moduleCount});
const chrome=require(shared+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'RES-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
const css=`*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:#0c2944;background:white}main{max-width:1200px;margin:0 auto;padding:28px 40px 64px}main .breadcrumb{font-size:14px;color:#506272;margin:0 0 30px}main .module{max-width:960px;margin:0 auto;padding:38px 0;border-bottom:1px solid #d9e2e8}main .module:first-of-type{padding-top:12px}main .module:last-child{border:0;padding-bottom:0}main h1{font-size:46px;line-height:1.16;letter-spacing:-1.4px;margin:0 0 24px}main h2{font-size:30px;line-height:1.25;letter-spacing:-.5px;margin:0 0 23px}main h3{font-size:22px;line-height:1.4;margin:26px 0 18px}main p,main li{font-size:17px;line-height:1.65;margin:0 0 18px}main ul,main ol{padding-left:27px;margin:22px 0}main li{padding-left:7px}main a{display:inline-flex;align-items:center;min-height:44px;min-width:44px;max-width:100%;color:#008078;font-weight:600;text-underline-offset:4px;overflow-wrap:anywhere}main a:focus-visible{outline:3px solid #008078;outline-offset:3px}main code{font:inherit;font-variant-numeric:tabular-nums}main table{border-collapse:collapse;table-layout:fixed;width:100%;margin:20px 0 24px;font-size:16px;line-height:1.5}main th,main td{border:1px solid #cbd8df;padding:16px;vertical-align:top;text-align:left;overflow-wrap:break-word}main th{background:#eef3f6;font-weight:600}main th:first-child{width:48%}main th:nth-child(2){width:26%}main th:nth-child(3){width:26%}main td:nth-child(2){font-variant-numeric:tabular-nums;font-weight:600}main .module-1 p:nth-last-child(2) a{padding:12px 20px;background:#008078;border:1px solid #008078;color:white;text-decoration:none}main .module-1 p:last-child a{padding:11px 20px;border:1px solid #008078;text-decoration:none}@media(max-width:1100px){main{padding:24px 32px 48px}main .module{padding:32px 0}main h1{font-size:40px}}@media(max-width:600px){main{padding:20px 20px 40px}main .breadcrumb{line-height:1.5;margin-bottom:22px}main .module{padding:30px 0}main h1{font-size:34px;letter-spacing:-.7px}main h2{font-size:27px}main h3{font-size:21px}main p,main li{font-size:16px;line-height:1.65}main li{padding-left:1px}main .module-1 a{width:100%;justify-content:center}main table{font-size:14px;line-height:1.5}main th,main td{padding:12px 8px}}`;
const behavior=`window.localNavigationIntents=[];document.addEventListener('click',event=>{const a=event.target.closest('a');if(!a)return;event.preventDefault();window.localNavigationIntents.push({href:a.getAttribute('href'),context:{},type:'LOCAL_NAVIGATION_INTENT_ONLY'});});`;
const source=out+'/RES-TRADE-EU_GATE3_WIREFRAME_V0.1.html';save(source,'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EU Titanium Dioxide Anti-Dumping Duty Update | TiO2 Malaysia</title><style>'+chrome.style+'\n'+css+'</style></head><body>'+chrome.header+'<main>'+html+'</main>'+chrome.footer+chrome.dialog+'<script>'+chrome.behavior+'\n'+behavior+'</script></body></html>');console.log(JSON.stringify({source:id(source),blocks:blocks.length,links:links.length,tableRows,modules:moduleCount},null,2));
