const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/resources/eu-trade/04_planning/gate3-v0.1',source=out+'/RES-TRADE-EU_GATE3_WIREFRAME_V0.1.html',formal=process.argv.includes('--formal'),dest=out+(formal?'/approval_core':'/diagnostic_support/render');
const identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const expected=JSON.parse(fs.readFileSync(out+'/diagnostic_support/expected-copy.json','utf8'));let results=[],images=[],network=[],browser;
const check=(name,ok,details)=>{results.push({name,status:ok?'PASS':'FAIL',details});if(!ok)throw Error(name+' '+JSON.stringify(details));};
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
const shot=async(p,w,state,full=false)=>{await ready(p);const name=(formal?'RES-TRADE-EU_G3_':'diagnostic-')+w+'-'+state+'.png',f=dest+'/'+name;await p.screenshot({path:f,fullPage:full,animations:'disabled'});images.push({...identity(f),width:w,state});};
const restored=p=>p.evaluate(()=>document.querySelector('.mobileNav').hidden&&document.body.style.overflow===''&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert));
(async()=>{if(formal){const frozen=JSON.parse(fs.readFileSync(out+'/freeze-record.json','utf8'));check('frozen identity',frozen.source.sha256===identity(source).sha256);check('no preexisting formal exports',fs.readdirSync(dest).length===0);}
browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
for(const w of [1440,768,390]){const h=w===390?844:900;const context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await context.route(/^https?:/,r=>{network.push(r.request().url());return r.abort()});const p=await context.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
const content=await p.locator('main').evaluate(e=>[...e.querySelectorAll('h1,h2,h3,p,li,th,td')].map(x=>({tag:x.tagName.toLowerCase(),text:x.textContent.replace(/\s+/g,' ').trim()})));check(w+' full ordered B content',JSON.stringify(content)===JSON.stringify(expected.blocks.map(x=>({...x,text:x.text.replace(/\s+/g,' ').trim()}))),content.length);
const links=await p.locator('main a').evaluateAll(as=>as.map(a=>({text:a.textContent,href:a.getAttribute('href')})));check(w+' all B links exact',JSON.stringify(links)===JSON.stringify(expected.links),links);
const table=await p.locator('table tr').evaluateAll(rows=>rows.map(r=>[...r.children].map(c=>c.textContent)));check(w+' exact producer duty code tuples',JSON.stringify(table)===JSON.stringify(expected.tableRows),table);
const measure=await p.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,footer:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,bodyFont:getComputedStyle(document.body).fontFamily,fontLoaded:document.fonts.check('16px Inter'),targets:[...document.querySelectorAll('a,button')].filter(e=>e.getBoundingClientRect().width>0).map(e=>({text:e.textContent,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),cells:[...document.querySelectorAll('th,td')].map(e=>({text:e.textContent,left:e.getBoundingClientRect().left,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,font:getComputedStyle(e).fontSize,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth})),clipping:[...document.querySelectorAll('main,main *')].filter(e=>['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis').map(e=>e.tagName),colors:[...document.querySelectorAll('main a')].map(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}))}));
check(w+' complete Footer geometry and Inter',measure.scrollWidth===w&&Math.abs(measure.height-measure.footer)<2&&measure.bodyFont.startsWith('Inter')&&measure.fontLoaded,measure);check(w+' 44px targets',measure.targets.every(t=>t.w>=44&&t.h>=44));check(w+' table bounded and readable',measure.cells.every(c=>c.left>=0&&c.right<=w&&c.scrollWidth<=c.clientWidth+1&&parseFloat(c.font)>=14),measure.cells);check(w+' no hidden body clipping',measure.clipping.length===0);check(w+' functional colors',measure.colors.every(c=>c.color==='rgb(0, 128, 120)'||(c.color==='rgb(255, 255, 255)'&&c.bg==='rgb(0, 128, 120)')));
const risks=await p.evaluate(()=>({modules:document.querySelectorAll('main section').length,checklist:document.querySelectorAll('.module-4 ol li').length,categories:document.querySelectorAll('.module-5 ul li').length,forms:document.querySelectorAll('main form,main select,main input,main details').length,sourceList:document.querySelectorAll('.module-6 ul li').length,scope:document.querySelector('.module-3').textContent,hero:document.querySelector('.module-1').textContent,footerDate:document.querySelector('.module-6 p:last-child').textContent}));
check(w+' six modules seven inputs three categories four sources',risks.modules===6&&risks.checklist===7&&risks.categories===3&&risks.forms===0&&risks.sourceList===4,risks);
check(w+' dated status and exact invoice entity predicates',risks.hero.includes('As checked on 7 September 2026')&&risks.scope.includes('the exact producing legal entity')&&risks.scope.includes('the exact listed entity, its company-specific code and the specified valid invoice must align')&&risks.scope.includes('Article 254')&&risks.footerDate==='Last reviewed: 7 September 2026.');
check(w+' Resources navigation current',await p.locator('.desktopNav [aria-current=page]').textContent()==='Resources');await shot(p,w,'full',true);
if(!formal){for(let y=0,i=1;y<measure.height;y+=750,i++){const f=dest+'/'+w+'-segment-'+String(i).padStart(2,'0')+'.png';await p.screenshot({path:f,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,measure.height-y)}});images.push({...identity(f),width:w,state:'readable-segment',y});}}
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();const intent=await p.evaluate(()=>localNavigationIntents.at(-1));check(w+' local body navigation '+i,intent.href===links[i].href&&Object.keys(intent.context).length===0,intent);}
await p.evaluate(()=>scrollTo(0,0));
if(w<1101){const button=p.locator('.menuButton'),menu=p.locator('.mobileNav');await button.click();check(w+' Menu entry/background',await p.evaluate(()=>document.activeElement.textContent==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'&&document.querySelector('.menuButton').textContent==='Close'));await shot(p,w,'menu');check(w+' Menu targets',await menu.locator('a').evaluateAll(as=>as.every(a=>a.getBoundingClientRect().height>=44&&a.getBoundingClientRect().width>=44)));
await menu.locator('a').last().focus();await p.keyboard.press('Tab');check(w+' Menu Tab',await button.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(w+' Menu reverse Tab',await menu.locator('a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(w+' Menu Escape restore',await restored(p)&&await button.evaluate(e=>e===document.activeElement));await button.click();await button.click();check(w+' Menu Close restore',await restored(p));
for(let i=0;i<8;i++){await button.click();const href=await menu.locator('a').nth(i).getAttribute('href');await menu.locator('a').nth(i).click();check(w+' Menu navigation exit '+i,await restored(p)&&(await p.evaluate(()=>localNavigationIntents.at(-1).href))===href);}
await button.click();const before=await p.evaluate(()=>scrollY);await p.mouse.move(w-5,h-10);await p.mouse.wheel(0,600);await p.waitForTimeout(120);check(w+' Menu wheel lock',await p.evaluate(()=>scrollY)===before);await p.setViewportSize({width:1200,height:h});check(w+' Menu breakpoint exit',await restored(p));await p.setViewportSize({width:w,height:h});}
await p.locator('#cookie-trigger').click();check(w+' Cookie initial focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await shot(p,w,'cookie');const actions=await p.locator('.cookie-actions > *').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,color:getComputedStyle(e).color,border:getComputedStyle(e).borderTopColor})));check(w+' Cookie colors/44px',actions.every(a=>a.w>=44&&a.h>=44&&a.color==='rgb(0, 128, 120)'&&a.border==='rgb(0, 128, 120)'),actions);await p.keyboard.press('Shift+Tab');check(w+' Cookie reverse loop',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(w+' Cookie loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('[data-cookie-close]').click();check(w+' Cookie Close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');check(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!(await p.locator('dialog').evaluate(e=>e.open)));await context.close();}
check('no requested external network',network.length===0,network);const record={status:'PASS',formal,source:identity(source),browser:await browser.version(),viewports:[1440,768,390],dpr:1,evidenceTypes:['ACTUAL_RUNTIME','LOCAL_SIMULATION'],results,images,network,finishedAt:new Date().toISOString()};await browser.close();fs.writeFileSync(dest+'/runtime.json',JSON.stringify(record,null,2));console.log(JSON.stringify({status:'PASS',formal,images:images.length,checks:results.length}));
})().catch(async e=>{if(browser)await browser.close();fs.writeFileSync(out+'/diagnostic_support/failure-'+Date.now()+'.json',JSON.stringify({status:'FAIL',error:e.stack,results,images,source:identity(source)},null,2));console.error(e);process.exitCode=1});
