const fs=require('fs'),crypto=require('crypto');const page='D:/23MySec/pages/resources/eu-trade',out=page+'/04_planning/gate3-v0.1',evidence=page+'/05_review/RES-TRADE-EU_GATE3_EXECUTION_EVIDENCE_V0.1';fs.mkdirSync(evidence,{recursive:true});
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});const save=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const binding=JSON.parse(fs.readFileSync(out+'/input-binding.json','utf8')),freeze=JSON.parse(fs.readFileSync(out+'/freeze-record.json','utf8')),run=JSON.parse(fs.readFileSync(out+'/approval_core/runtime.json','utf8'));
for(const a of [freeze.source,freeze.preflight,freeze.inputBinding,...binding.approvedInputs,...binding.authorities,...binding.sharedFiles,...binding.dependencies,binding.sharedConsumer])if(id(a.path).sha256!==a.sha256)throw Error('changed identity '+a.path);
const images=run.images.map(a=>{const buf=fs.readFileSync(a.path),actual=id(a.path),diagnostic=out+'/diagnostic_support/render/diagnostic-'+a.width+'-'+a.state+'.png';if(actual.sha256!==a.sha256)throw Error('image mismatch');return {...actual,width:buf.readUInt32BE(16),height:buf.readUInt32BE(20),logicalWidth:a.width,dpr:1,state:a.state,diagnosticIdentical:actual.sha256===id(diagnostic).sha256}});if(images.length!==8||images.some(i=>!i.diagnosticIdentical))throw Error('visual identity');
fs.renameSync(out+'/approval_core/runtime.json',evidence+'/formal-runtime.json');
save(evidence+'/formal-visual-observation.json',{status:'EXECUTION_VISUAL_CHECK_COMPLETE',evidenceType:'STATIC_VISUAL',executor:'Gate3 execution agent; not independent approval',source:freeze.source,actualOpenedImages:images,openedAt:new Date().toISOString(),nativeReadableCoverage:'26 original-size overlapping diagnostic segments (7 desktop/8 tablet/11 mobile; final mobile strip repeats footer bottom) actually opened to Footer. All eight formal images were separately opened and are byte-identical to diagnostic counterparts.',observations:['Three-column table remains readable on 390, every row retains producer category, EUR/kg value and code.','Entity/group distinction, invoice/code/entity conjunction, fallback and customs-check predicates remain immediately below table.','All dates, Article 2/254 limitations, seven assessment inputs and Malaysia-origin boundary visible.','Current 2025/4 explanation is dated 7 September 2026; pending procedure and future cap not represented as new current rate.','Shared Menu/Cookie complete and readable.'],unresolvedFindings:[]});
save(out+'/design-report.md',`# RES-TRADE-EU Gate 3 design method report V0.1

DRAFT_FOR_PROJECT_CONTROL_REVIEW. Gate3 execution report, not independent approval. Only RES-TRADE-EU was executed.

Frozen source: ${freeze.source.path}; ${freeze.source.bytes} bytes; SHA-256 ${freeze.source.sha256}. Freeze ${freeze.frozenAt}. The recorded hard preflight was validated PASS_FOR_FORMAL_RENDER before freeze; first formal exports followed. All eight formal PNGs were actually opened and equal their diagnostic counterparts byte-for-byte. Input-binding.json records actual approved A V0.1/B V0.2/C V0.2/review V0.1, current Manifest V0.4, method, shared and dependency hashes.

Six modules preserve B order: dated Hero → current measure/pending review → product scope and fixed-duty table → seven shipment inputs → anti-dumping/tariff/VAT distinction → correct owner and four official sources. B alone supplies page text; only editorial Breadcrumb/Primary action/Secondary action labels and Markdown syntax are removed. All 57 content blocks and 11 hrefs match the rendered order. No calculator, rate selector, FAQ, form, new legal conclusion or media was added.

The main design decision is a continuous editorial column with one semantic three-column table. The 1200px outer container has a 960px content column; tablet uses 32px gutters, mobile 20px. Body type is 17px/16px. The table keeps 48/26/26 percent columns across widths; 16px desktop/tablet and 14px mobile text, natural row heights and visible grid lines keep all four producer/amount/code tuples together. The legal-entity and invoice predicates follow immediately at full body size. Mobile does not hide fields, collapse qualifiers or convert values into isolated promotional cards. Primary EU procurement and secondary official-source actions remain visually ordered; mobile buttons span the column.

Shared Header/Footer/Menu/Cookie were freshly generated from page-neutral Shared Consumer V0.2 with Resources current (RES-000), current production SVG paths and local durable Inter/license snapshots. No business-page HTML/CSS or dependency template was read or copied. Shared owner authority remains Global Chrome V0.5, current Logo/CTA/legal/Consent contracts. Functional page links and action borders use #008078; fixed RFQ, Procurement and legal utilities follow current overrides to older Playbook wording.

responsive-wireframe-design V0.2 drove the task input card, content-to-layout mapping, table decision, actual diagnostic rendering, hard stop, source freeze and first formal export. layout-interaction-verification V0.2 drove fixed core plus EU-specific risks, browser measurement/action checks and actual full/native-readable image viewing. Their referenced resources are bound. Self-check does not confer project-control PASS.

Actual evidence: Chrome ${run.browser}, Playwright local-file rendering, DPR1 at 1440×900, 768×900 and 390×844. Runtime checked exact B blocks/hrefs/table tuples, legal-entity/invoice and date predicates, no page clipping/overflow, bounded 14px-or-larger cells, 44×44 controls, loaded Inter, Footer bottom and functional colors. All body links were clicked and recorded locally with empty context; no external request was sent. Two narrow menus were exercised for first Home focus, Tab/Shift+Tab, Escape, Close, all eight link exits, inert/scroll restoration, wheel lock and desktop breakpoint close. Three Cookie dialogs were exercised for entry, focus cycle, Close/Escape and return. Three diagnostic full overviews, 26 native-readable segments and five states were opened, followed by all eight formal images.

Four risk conclusions: (1) The hardest comparison is the duty table together with entity/invoice predicates: original column associations and complete following paragraphs are readable at all widths. (2) The most consequential actions are official verification versus EU procurement/Products/RFQ: exact hrefs and conditional commercial context are retained, no Grade or duty result is selected or sent. (3) The riskiest responsive area is the long last producer category and source/date wrapping: native 390 inspection shows full fields, four sources and every date with no truncation; the current measure and possible future cap remain separate. (4) No unresolved page Finding. One initial build-helper CommonJS variable-name collision was preserved and corrected before any candidate existed; no source revision after successful creation. No later failure was concealed.

The legal material is the approved dated explanation checked in Gate2 on 7 September 2026, not a new Gate3 legal-status verification. C V0.2 requires a maximum 30-day refresh while active, next no later than 7 October 2026, and within two business days of a new notice/amendment/result/judgment/TARIC change. Implementation/publication must satisfy that dependency; stale affected summaries/GEO/machine facts cannot continue as current. Malaysia-origin remains a commercial statement, not customs-origin or anti-dumping treatment. No shipment classification, rate, duty/VAT calculation, clearance or Article2 eligibility is determined.

Untested: native 200% browser zoom, screen readers, physical touch hardware, alternate engines; live official destinations and new source refresh; production receiver/email/prefill/storage/analytics/Cookie inventory, route/canonical/indexing/sitemap/Schema. Page forms/calculators/FAQ/result states are NOT_APPLICABLE because B has none. Evidence distinguishes ACTUAL_RUNTIME, STATIC_VISUAL, SOURCE_INSPECTION and LOCAL_SIMULATION. Project control owns independent Gate review; legal-content/future implementation owners retain freshness and deployment checks. No Gate4 or other page was started.
`);
const self=page+'/05_review/RES-TRADE-EU_GATE3_EXECUTION_SELF_CHECK_V0.1.md';save(self,`# RES-TRADE-EU Gate 3 execution self-check V0.1

DRAFT_FOR_PROJECT_CONTROL_REVIEW. Execution scope complete; unresolved required Findings: 0. This is self-check, not independent PASS or Gate closure.

Source ${freeze.source.path}; ${freeze.source.bytes} bytes; SHA-256 ${freeze.source.sha256}; frozen ${freeze.frozenAt}. Actual input/dependency identities matched again at handoff. Formal images are bound in ${out}/asset-inventory.json.

| Fixed core | Actual conclusion / evidence |
|---|---|
| Frozen identity | Approved A/B/C/review and current Manifest hashes verified; hard preflight PASS before freeze, first formal exports afterward; source unchanged. |
| Full content/relationships | Three rendered views match all 57 B content blocks, 11 hrefs and four producer/duty/code tuples in order, excluding editorial labels only. Six modules, seven assessment inputs, three tax categories and four source/date items complete. |
| Geometry | 1440/768/390 scrollWidth matches viewport; no main overflow clipping/ellipsis; Footer reaches document bottom; Inter loaded; every visible action at least 44×44. Table cells bounded, minimum 14px. |
| Shared assembly | Neutral V0.2 only; Resources current, production SVG references, exact fixed RFQ/Footer/legal/Cookie content and current functional Teal. Font/license saved durably from neutral source. |
| Overlay operations | Two menus: Home entry focus, forward/reverse loop, Close/Escape/every link/breakpoint exits, background inert and scroll restore, wheel lock. Three Cookie dialogs: entry/cycle/Close/Escape/return. |
| Actions | Every body link actually clicked into local intent log with empty context. No network requests or production success inference. RFQ remains commercial intake, not customs decision. |
| Visual coverage | Eight formal PNGs actually opened; all identical to diagnostic equivalents. Twenty-six original-size overlapping segments cover all three full-page heights through Footer; five overlay states checked. |

| EU risk | Result within approved-copy scope |
|---|---|
| Regulation/procedure/dates | PASS: dated 7 September 2026 explanation, 2025/4 publication/effect, C/2026/4533 publication/investigation period/timetable and future cap kept exact; no new rate or current-law claim introduced. |
| Table/entity/invoice | PASS: four exact tuples, 80% dry-matter PRC scope, informative CN/TARIC references; group identity insufficient, producing entity/code/valid invoice conjunction and Annex conditions/fallback preserved immediately after table. |
| Transaction limits | PASS: Article2 white graphic ink and Article254 narrow scope, seven input checklist, Malaysia-origin versus customs treatment and anti-dumping/tariff/VAT separation retained; no shipment result/calculation. |
| Sources/actions/responsive | PASS: all dates/four source items readable; EU procurement primary, legal secondary, Products neutral and RFQ conditional. Long 390 table fields wrap without loss or changed association. |

Preserved failure: diagnostic_support/build-initial-failed.cjs and build-failure.md record initial CommonJS reserved variable collision, repaired before candidate creation. No unresolved layout/content Finding; frozen source never revised.

Methods: explicitly consumed Gate3 Agent V0.2, responsive-wireframe-design V0.2 and layout-interaction-verification V0.2 with referenced preflight/core-risk resources. Actual measurements and actions: ${evidence}/formal-runtime.json. Actual visual observation: ${evidence}/formal-visual-observation.json. Mapping/choices: ${out}/design-report.md. Evidence is separated into approval_core and diagnostic_support; assertion quantity is not a cross-page score.

Untested: native 200% zoom, assistive technology, real touch/other engines, live links/source updates, production receiver/email/prefill/Cookie-storage/analytics, route/canonical/indexing/sitemap/Schema. No page form/calculator/FAQ/filter/result exists, so corresponding states are NOT_APPLICABLE. The approved legal explanation is dated, not reverified by this design exercise. Preserve C V0.2 30-day maximum/7 October 2026 next due and two-business-day event-trigger refresh before implementation/publication. Gate4 and other pages remain outside this execution.
`);
const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:'RES-TRADE-EU',source:freeze.source,freeze:id(out+'/freeze-record.json'),preflight:id(out+'/preflight-record.json'),inputBinding:id(out+'/input-binding.json'),sharedConsumer:binding.sharedConsumer,dependencies:binding.dependencies,approval_core:{images,reports:[id(out+'/task-input-card.md'),id(out+'/design-report.md'),id(self)]},diagnostic_support:{directory:out+'/diagnostic_support',runtime:id(evidence+'/formal-runtime.json'),formalVisualObservation:id(evidence+'/formal-visual-observation.json'),failureHistory:[id(out+'/diagnostic_support/build-initial-failed.cjs'),id(out+'/diagnostic_support/build-failure.md')]},unresolvedFindings:[],recordedAt:new Date().toISOString()};save(out+'/asset-inventory.json',inventory);
save(evidence+'/final-identity-check.json',{status:'IDENTITIES_MATCH',source:id(freeze.source.path),images:images.map(a=>({path:a.path,match:id(a.path).sha256===a.sha256})),reports:inventory.approval_core.reports.map(a=>({path:a.path,match:id(a.path).sha256===a.sha256})),inventory:id(out+'/asset-inventory.json')});console.log(JSON.stringify({source:freeze.source,images,reports:inventory.approval_core.reports,inventory:id(out+'/asset-inventory.json')},null,2));
