const fs=require('fs'),crypto=require('crypto'),{spawnSync}=require('child_process');const out='D:/23MySec/pages/resources/eu-trade/04_planning/gate3-v0.1';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});const save=(n,v)=>fs.writeFileSync(out+'/'+n,JSON.stringify(v,null,2)+'\n');
const binding=JSON.parse(fs.readFileSync(out+'/input-binding.json','utf8')),run=JSON.parse(fs.readFileSync(out+'/diagnostic_support/render/runtime.json','utf8'));
for(const i of [run.source,binding.sharedConsumer,...binding.approvedInputs,...binding.authorities,...binding.sharedFiles,...binding.dependencies])if(id(i.path).sha256!==i.sha256)throw Error('identity mismatch '+i.path);
if(run.status!=='PASS'||fs.readdirSync(out+'/approval_core').length)throw Error('not ready');
save('diagnostic_support/visual-observation.json',{evidenceType:'STATIC_VISUAL',executor:'Gate3 execution agent, not independent reviewer',source:run.source,openedAt:new Date().toISOString(),openedImages:run.images.map(i=>id(i.path)),coverage:'3 full overviews, 26 native readable overlapping segments (7 desktop, 8 tablet, 11 mobile, last mobile strip duplicates footer bottom), 2 menus, 3 Cookie dialogs actually opened.',observations:['Four three-column producer/EUR-per-kg/code rows stay legible at 390 with 14px text. No cell is clipped; both group scope and invoice/entity paragraphs follow immediately.','All six sections and seven assessment inputs retain reading order to four official source/date items and Last reviewed.','2025/4 status is visibly dated; C/2026/4533 future recalculation limit is separate from current rates.','No calculator, selected rate, origin result, exemption verdict or recommendation is visually introduced.','Menu and Cookie remain full and readable; no layout Finding.'],unresolvedFindings:[]});
const record={status:'PASS_FOR_FORMAL_RENDER',pageId:'RES-TRADE-EU',candidate:run.source,approvedInputs:binding.approvedInputs,authorities:binding.authorities,sharedConsumer:binding.sharedConsumer,sharedFiles:binding.sharedFiles,dependencies:binding.dependencies,formalExportsGenerated:false,checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks','functionalColor','tableTupleAndPredicateIntegrity'].map(k=>[k,'PASS'])),evidence:[id(out+'/input-binding.json'),id(out+'/diagnostic_support/render/runtime.json'),id(out+'/diagnostic_support/visual-observation.json')],evidenceTypes:['ACTUAL_RUNTIME','STATIC_VISUAL','SOURCE_INSPECTION','LOCAL_SIMULATION'],viewports:[{width:1440,height:900,dpr:1},{width:768,height:900,dpr:1},{width:390,height:844,dpr:1}],browser:run.browser,executor:'Gate3 execution agent',recordedAt:new Date().toISOString(),unresolvedFindings:[],notApplicable:'No page form, calculator, FAQ, filter, selection or result state. The only functional overlays are shared Menu and Cookie.'};save('preflight-record.json',record);
const validation=spawnSync(process.execPath,['D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs',out+'/preflight-record.json'],{encoding:'utf8'});fs.writeFileSync(out+'/diagnostic_support/preflight-checker-result.json',validation.stdout);if(validation.status!==0)throw Error(validation.stdout+validation.stderr);
const frozen={status:'FROZEN_FOR_FORMAL_RENDER',submissionStatus:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:'RES-TRADE-EU',frozenAt:new Date().toISOString(),source:run.source,inputBinding:id(out+'/input-binding.json'),approvedInputs:binding.approvedInputs,sharedConsumer:binding.sharedConsumer,sharedFiles:binding.sharedFiles,dependencies:binding.dependencies,preflight:id(out+'/preflight-record.json'),checker:id(out+'/diagnostic_support/preflight-checker-result.json'),formalExportsExistedAtFreeze:false};save('freeze-record.json',frozen);console.log(JSON.stringify({source:frozen.source,frozenAt:frozen.frozenAt,preflight:frozen.preflight},null,2));
