const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),prefix=out+'/MARKET-EU-ES_GATE3_',read=p=>JSON.parse(fs.readFileSync(p));
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));
const binding=read(prefix+'INPUT_BINDING_V0.1.json'),mode=process.argv[2];
if(mode==='preflight'){
const runtime=read(__dirname+'/candidate-v0.1-r3/runtime-checks.json');if(runtime.failures.length||runtime.errors.length||runtime.network.length)throw Error('Runtime preflight failed');
const visual={status:'EXECUTOR_STATIC_VISUAL_CHECK_COMPLETE',at:new Date().toISOString(),source:id(binding.candidate.path),coverage:'All 14 overlapping segments from Header through Footer; five menu/Cookie state images. r3 reuses 11 byte-identical viewed r2 segments; changed 390 segments 04–06 were opened again. Native-size 900px clips with 150px overlap.',findings:[{id:'ES-G3-01',type:'ACTUAL_RUNTIME',issue:'Common Explore Products was accidentally nested in Plastics & Masterbatch',resolution:'Builder scopes closing wrappers to ES-02; relation verified all widths',status:'CLOSED_IN_CANDIDATE'},{id:'ES-G3-02',type:'STATIC_VISUAL',issue:'390 auxiliary-link separator stood on its own line',resolution:'Natural inline wrapping keeps separator with preceding link; affected tail/Footers reopened',status:'CLOSED_IN_CANDIDATE'},{id:'ES-TOOL-01',type:'TEST_METHOD',issue:'CSS zoom 2 was mislabeled browser native zoom and failed desktop/390 geometry',resolution:'Original failed check retained. It is not native browser zoom; replaced with explicitly simulated desktop equivalent viewport 720x450. Native browser zoom remains untested.',status:'CORRECTED_METHOD_LIMIT_RECORDED'}],openFindings:[]};
write(__dirname+'/visual-preflight-v0.1.json',visual);
const additional=['docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','docs/page-playbooks/MARKET_PLAYBOOK_V0.1.md','docs/architecture/PAGE_GATE_1_5_STANDARD_V1.1.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','pages/conversion/request-a-quote/06_handoff/CONV-RFQ_GATE7_CMS_API_COMPONENT_MAPPING_V1.0.md','pages/conversion/06_handoff/CONV-DOC_GATE7_CMS_API_COMPONENT_FIELD_INVENTORY_V0.1.md'].map(p=>id('D:/23MySec/'+p));
const preflight={status:'PASS_FOR_FORMAL_RENDER',at:new Date().toISOString(),executor:'Gate3 execution agent; not independent project control',candidate:id(binding.candidate.path),approvedInputs:binding.inputs,additionalInputs:additional,dependencies:[...Object.values(binding.inputs),...binding.dependencies,...binding.sharedConsumer.files,...binding.sharedConsumer.owners,...additional],sharedConsumer:binding.sharedConsumer,checks:{approvedInputsMatch:'PASS',durableDependencies:'PASS',sharedConsumerNeutral:'PASS',contentRelationshipsMatch:'PASS',threeViewportsVisible:'PASS',touchTargets44:'PASS',mobileMenuExit:'PASS',applicableStates:'PASS',pageSpecificRisks:'PASS',functionalColors:'PASS'},formalExportsGenerated:false,evidence:{runtime:id(__dirname+'/candidate-v0.1-r3/runtime-checks.json'),visual:id(__dirname+'/visual-preflight-v0.1.json'),evidenceTypes:['ACTUAL_RUNTIME','STATIC_VISUAL','SOURCE_INSPECTION','LOCAL_SIMULATION']},rendering:{engine:'Installed Google Chrome / bundled Playwright; headless local file',deviceScaleFactor:1,viewports:[{width:1440,height:900},{width:768,height:900},{width:390,height:844}],network:'HTTP/S request interception and zero attempts observed'},notApplicable:['Page forms, field/submit/error states, FAQ, selectors, grade list, anchor states: absent from approved B/C'],unmeasured:['Native browser zoom; mobile hardware; assistive technology speech; cross-browser; production routing/prefill/receiver/cookies/SEO/deployment']};write(prefix+'PREFLIGHT_RECORD_V0.1.json',preflight);console.log(JSON.stringify({preflight:prefix+'PREFLIGHT_RECORD_V0.1.json',status:preflight.status}));
}
if(mode==='freeze'){
 const p=prefix+'PREFLIGHT_RECORD_V0.1.json',pre=read(p);if(pre.status!=='PASS_FOR_FORMAL_RENDER'||pre.formalExportsGenerated!==false)throw Error('Preflight not passed');
 for(const item of [pre.candidate,...pre.dependencies])if(id(item.path).sha256!==item.sha256)throw Error('Input changed '+item.path);
 if(fs.existsSync(out+'/approval_core'))throw Error('Formal directory existed before first freeze');
 const freeze={status:'FROZEN_FOR_FORMAL_RENDER',frozenAt:new Date().toISOString(),pageId:'MARKET-EU-ES',candidate:id(binding.candidate.path),approvedInputs:binding.inputs,sharedConsumer:binding.sharedConsumer,dependencies:binding.dependencies,preflight:id(p),inputBinding:id(prefix+'INPUT_BINDING_V0.1.json'),formalExportsExistedAtFreeze:false,rule:'Any source change invalidates this freeze and requires a new record and affected formal export/check.'};write(prefix+'FREEZE_RECORD_V0.1.json',freeze);console.log(JSON.stringify(freeze.candidate));
}
if(mode==='handoff'){
 const freeze=read(prefix+'FREEZE_RECORD_V0.1.json'),runtime=read(out+'/approval_core/runtime-checks.json'),diag=read(__dirname+'/candidate-v0.1-r3/runtime-checks.json');
 if(runtime.failures.length||runtime.source.sha256!==freeze.candidate.sha256)throw Error('Formal runtime mismatch');
 const review='D:/23MySec/pages/markets/spain/05_review',evidence=review+'/MARKET-EU-ES_GATE3_EXECUTION_EVIDENCE_V0.1';fs.mkdirSync(evidence,{recursive:true});
 fs.renameSync(out+'/approval_core/runtime-checks.json',evidence+'/formal-runtime-checks.json');
 const assets=runtime.assets.map(a=>{const buf=fs.readFileSync(a.path),d=diag.assets.find(n=>n.width===a.width&&n.state===a.state);return {...id(a.path),pixelWidth:buf.readUInt32BE(16),pixelHeight:buf.readUInt32BE(20),state:a.state,logicalWidth:a.width,deviceScaleFactor:1,diagnosticByteIdentical:d.sha256===id(a.path).sha256,sourceSha256:freeze.candidate.sha256,viewed:'Opened individually after formal export; full images supported by 14 overlapping native-size segments'}});
 if(assets.some(a=>!a.diagnosticByteIdentical))throw Error('Formal images differ from viewed diagnostics');
 const visual={type:'STATIC_VISUAL',at:new Date().toISOString(),status:'EXECUTOR_REVIEW_COMPLETE',formalAssets:assets,coverage:'Three full page images and five state images opened individually after freeze. Each full image is byte-identical to current diagnostic full export. Native segment coverage 1440:4, 768:4, 390:6; 900px maximum height, stride750. All content through Footer was read; no clipping/collision or unresolved visual defect.',source:freeze.candidate};write(evidence+'/formal-visual-readback.json',visual);
 const design=`# Spain Gate 3 design method report V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Date: 2026-09-07. Role: Gate3 execution, batch G3-8PAGE-SERIAL-01 / first page only. This is method execution and self-review, not independent approval.

Applied responsive-wireframe-design V0.2 and references/preflight-freeze-evidence.md: current input card → fresh neutral assembly → diagnostic hard preflight → actual image read → schema checker → freeze → first formal export. Agent V0.2 and method baseline V1.2 are bound in INPUT_BINDING. Latest serial authorization overrides historical page-local Gate3 NOT_AUTHORIZED; it grants no Gate4 activity to this executor.

| Approved module | Implemented design decision |
|---|---|
| ES-01 | H1 and Malaysia-origin/Spain destination distinction lead; primary RFQ then outlined Products. Wide readable Hero without invented image or map. |
| ES-02 | Two application groups share one section. Desktop/tablet side-by-side; mobile Coatings then Plastics & Masterbatch. Both approved plastic/masterbatch descriptive paths remain intact, and common Products sits after both groups. |
| ES-03 | Grade/document review text precedes the one approved COO request sentence; outlined Request Documents and lower-weight Hub link. No file inventory or form. |
| ES-04 | Four procurement preparation bullets, unknown-grade explanation, RFQ and exact after-submit explanation. EU overview/trade are subordinate text routes. |

B V0.2 between BUYER_COPY_START/END is the only visible main source; 6 headings, 14 ordered links and all sentences/punctuation compare in both directions at each width. Four modules remain four; no extra headings, FAQ, input/select, technical table, guarantee or grade relationship. Metadata uses C exact title/description with local noindex,nofollow. Malaysia-origin and Spain COO publication authority are inherited without broadening into every shipment, customs or tariff claims.

Fresh renderSharedChrome consumes page-neutral consumer V0.2 with currentPageId=MARKET-000 and original production SVG references; no business-page source is used as a template. CSS/behavior are embedded unchanged from the renderer, font/license are durable identical copies in dependencies. The shared package and its six owner contracts remain authoritative. Functional links/focus/outlined actions use #008078; filled primary CTA white on #008078; shared navigation follows Chrome-specific navy/white rules. Older Playbook #007F77, generic module suggestions, target-not-live hiding and origin holds are superseded by current CTA/B/C/root/publication contracts. No shared source was edited.

Actual diagnostics found ES-G3-01 (common Products wrongly nested) and ES-G3-02 (390 separator alone on line). Both were corrected before freeze, rerendered, rechecked and visually reopened; originals remain in diagnostic_support. ES-TOOL-01 records CSS zoom mislabeled native browser zoom; that method was corrected, not silently claimed passing. Desktop 720×450 is only a 200% equivalent layout simulation; native browser zoom remains untested.

Formal asset dimensions: 1440×2673, 768×2951, 390×3954; menu 768×900 / 390×844; Cookie 1440×900 / 768×900 / 390×844. Full images and all five state images were individually opened after export. Fourteen overlapping readable segments cover every body module and Footer; current formal/diagnostic full bytes match. Local runtime verifies 44px targets, keyboard focus, menu cycles/Escape/Close/all selections/body lock and restore/cross-desktop closure, Cookie cycles/Close/Escape/return and policy href. Shared behavior is actual runtime; destination navigation records remain LOCAL_SIMULATION.

Frozen HTML: ${freeze.candidate.path}; ${freeze.candidate.bytes} bytes; SHA-256 ${freeze.candidate.sha256}. Freeze date ${freeze.frozenAt}; preflight identity is in FREEZE_RECORD. ASSET_INVENTORY binds formal images, method inputs, dependencies and records. Open execution findings: none.

The hardest reading is the two application paths at 390: each explanatory sentence remains adjacent to its correct link. The hardest operation is exiting a shared overlay and resuming the page: both narrow menus and all Cookie widths were exercised. The main responsive change is two application columns to one ordered column, with shared Chrome changing independently at its owner breakpoint. Unmeasured scope: production links/receivers, destination editing and persistence, document selection, actual cookie technologies/storage, native browser zoom, physical mobile/assistive speech and non-Chrome engines. No requests, submission, deployment or Gate4 were performed.
`;
 fs.writeFileSync(prefix+'DESIGN_METHOD_REPORT_V0.1.md',design);
 const self=`# Spain Gate 3 execution self-check V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Executor: Gate3 execution agent. Date: 2026-09-07. This self-check does not grant project-control PASS, user approval or Gate closure.

Applied layout-interaction-verification V0.2 and references/core-risk-model.md, with fixed core invariants and Spain-specific risks. Applied responsive-wireframe-design V0.2 separately; its durable method report was read together with actual source, input/preflight/freeze records and rendered evidence. Coverage, not assertion totals, determines the conclusions.

| Fixed core | Evidence and conclusion |
|---|---|
| Frozen identity | SOURCE_INSPECTION: source ${freeze.candidate.bytes} bytes / ${freeze.candidate.sha256}; exact approved A/B/C and shared package hashes rechecked before freeze. Formal images bind this source, and match viewed diagnostics byte-for-byte. |
| Content/relationships | ACTUAL_RUNTIME + STATIC_VISUAL: exact B full text, 14 ordered labels/hrefs, 6 headings and 4 modules at all three widths. Two application groups; Plastics/Masterbatch paths distinct; shared Products follows both. No invented form/FAQ/select/table/grade claims. |
| Responsive geometry | ACTUAL_RUNTIME + STATIC_VISUAL: 1440/768/390 through Footer; no horizontal overflow, hidden body, clipped lines or unintended fixed gaps. Default, menu and Cookie visible targets meet 44×44. Functional main links/focus and Cookie actions use #008078. |
| Shared assembly | SOURCE_INSPECTION + ACTUAL_RUNTIME: neutral package V0.2, Markets active, original primary/reverse production SVGs, fixed RFQ, exact neutral Footer/legal/Cookie text. Font/license durable; no temporary or other-page render dependency. |
| Overlay operation | ACTUAL_RUNTIME: 768/390 open/Home focus; Tab/Shift+Tab cycles; Escape, Close and all 8 navigation choices close; inert/background wheel lock and recovery; resizing to 1440 closes. Three Cookie widths: initial focus, forward/reverse cycles, Close/Escape and Footer trigger restoration; policy click records exact href. |
| Action boundary | LOCAL_SIMULATION: all 14 B links clicked per width; exact href, no query. RFQ intent records source_page_id=MARKET-EU-ES, destination_country=Spain and editable semantic flag. Documents intent only records source_page_id, no company-country/Grade/Application/document preselection. Flags are planning intent, not a receiver API or proof of edited/persisted values. |
| Full visual coverage | STATIC_VISUAL: all 8 formal PNGs opened individually. 14 overlapping native-size segments read through Footer; changed mobile tail reopened; formal PNG hashes equal the viewed current diagnostics. |

| Spain risk | Expected and observed | Conclusion |
|---|---|---|
| Hardest reading | Coatings vs Plastics/Masterbatch retains correct prose/link mapping at 390 and both larger widths. Common Products is outside either group. | No unresolved reading finding. |
| Hardest operation | Menu/Cookie exit returns interaction to page; background restores and links record intent without navigation requests. | Local shared behavior passed; receiver behavior untested. |
| Responsive conversion | Two application columns at 1440/768 become Coatings then Plastics/Masterbatch at 390; document and RFQ reading order unchanged. | Conversion preserves approved relationships. |
| Fact/action limits | COO exact sentence once in ES-03; no every-shipment/trade inference. RFQ guidance/after-submit are prose, not page fields or success state. EU links subordinate. | No unapproved claim or local form state found. |

Preflight passed before freeze and check-preflight-record.mjs returned PASS_FOR_FORMAL_RENDER. Freeze was saved before any approval_core export. Frozen-source formal runtime completed without failures, page errors or HTTP/S request attempts. Reports and assets read back; dependencies and approved inputs retain the bound hashes.

Resolved history: ES-G3-01 common Products grouping; ES-G3-02 isolated mobile separator. Preserved in ${out}/diagnostic_support. ES-TOOL-01 CSS zoom test was an invalid native-zoom claim; failed results retained and method limitation recorded. No current unresolved execution Finding. No page forms/FAQ/selectors/anchors means those state exports are NOT_APPLICABLE per C §4, not omitted features.

Not tested: destination pages and provisional/live route resolution; RFQ Spain editability/persistence and actual receiver success/failure; document taxonomy/options/selection/receipt; backend, production optional technology or cookie/storage state; native browser zoom (only 720×450 desktop-equivalent viewport simulated), screen-reader speech, physical devices, Safari/Firefox, production SEO/canonical/schema, deployment. These are explicit downstream handoff/verification dependencies, not local success claims. No Gate4/development activity or other page work occurred.

Core directory: ${out}/approval_core. Source/report/input/freeze/preflight/inventory: ${out}. Actual formal execution JSON and visual readback: ${evidence}. Diagnostic screenshots, readable segments, helpers and failures are diagnostic_support. Total core PNGs: 8; their actual pixel dimensions, bytes and hashes are in ASSET_INVENTORY.
`;
 fs.writeFileSync(review+'/MARKET-EU-ES_GATE3_EXECUTION_SELF_CHECK_V0.1.md',self);
 const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',createdAt:new Date().toISOString(),pageId:'MARKET-EU-ES',approval_core:{source:freeze.candidate,assets,records:['TASK_INPUT_CARD','INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD','DESIGN_METHOD_REPORT'].map(s=>id(prefix+s+'_V0.1.'+(s==='TASK_INPUT_CARD'||s==='DESIGN_METHOD_REPORT'?'md':'json'))),selfCheck:id(review+'/MARKET-EU-ES_GATE3_EXECUTION_SELF_CHECK_V0.1.md'),dependencies:binding.dependencies,sharedConsumer:binding.sharedConsumer},diagnostic_support:{path:__dirname.replaceAll('\\','/'),formalRuntime:id(evidence+'/formal-runtime-checks.json'),formalVisualReadback:id(evidence+'/formal-visual-readback.json'),openFindings:[],resolved:['ES-G3-01','ES-G3-02'],methodCorrection:'ES-TOOL-01'},scope:'Planning only; independent project-control review pending; no Gate4/development'};
 write(prefix+'ASSET_INVENTORY_V0.1.json',inventory);
 console.log(JSON.stringify({source:freeze.candidate,formalAssets:assets.map(a=>({path:a.path,width:a.pixelWidth,height:a.pixelHeight,bytes:a.bytes,sha256:a.sha256})),report:prefix+'DESIGN_METHOD_REPORT_V0.1.md',selfCheck:review+'/MARKET-EU-ES_GATE3_EXECUTION_SELF_CHECK_V0.1.md',inventory:prefix+'ASSET_INVENTORY_V0.1.json'},null,2));
}
