// Independent Gate5 review harness. Candidate is read-only; output confined to this review directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/resources/04_planning/d32-gate4-v0.2',old=root+'/pages/resources/04_planning/d32-gate3-v0.1';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),json=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const checks=[],observations=[],ruleChanges=[]; const ck=(id,ok,detail)=>checks.push({id,status:ok?'PASS':'FAIL',detail});
const freeze=json(base+'/RES-000_D32_GATE4_FREEZE.json'),input=json(base+'/RES-000_D32_GATE4_INPUTS.json'),evidence=json(base+'/RES-000_D32_GATE4_EVIDENCE_INDEX.json');
const rows=freeze.files.map(r=>({path:r.path,bytes:fs.statSync(r.path).size,sha256:hash(r.path)}));
for(let i=0;i<rows.length;i++)ck('FROZEN:'+rows[i].path,JSON.stringify(rows[i])===JSON.stringify(freeze.files[i]));
const bundle=crypto.createHash('sha256').update(JSON.stringify(rows)).digest('hex');
ck('IDENTITY:bundle',bundle==='f43aa865e50c2b8fe0ba422692c3a4c26552478433397e4362675357ddc611b0'&&freeze.bundle_id===bundle,bundle);
ck('IDENTITY:freeze',hash(base+'/RES-000_D32_GATE4_FREEZE.json')==='396ebb33bbaa7053571f32bd6d40d6dc2e3fbcad38cb10e19bbff212388433b3');
for(const r of [...input.contentAuthority,...input.dependencies,...input.inheritedEvidence])ck('INPUT:'+r.path,hash(r.path)===r.sha256&&fs.statSync(r.path).size===r.bytes);
for(const r of input.currentRules){const actual=hash(r.path);if(actual!==r.sha256)ruleChanges.push({path:r.path,frozen:r.sha256,current:actual});}
ck('RULE-DRIFT:only-governance',ruleChanges.every(r=>['AGENTS.md','PROJECT_CONTEXT.md'].some(n=>r.path===root+'/'+n)),ruleChanges);
ck('EVIDENCE:counts',evidence.formal===20&&evidence.readable===16&&evidence.assets.length===36&&evidence.rejectedCaptureHistory.length===2);
for(const r of evidence.assets){const b=fs.readFileSync(r.path);ck('EVIDENCE:'+path.basename(r.path),hash(r.path)===r.sha256&&b.length===r.bytes&&b.readUInt32BE(16)===r.width&&b.readUInt32BE(20)===r.height&&hash(r.source_path)===r.source_sha256&&r.DPR===1);}
const B=fs.readFileSync(root+'/pages/resources/04_planning/RES-000_CONTENT_ARCHITECTURE_V0.3.md','utf8'),C=fs.readFileSync(root+'/pages/resources/04_planning/RES-000_SEO_GEO_SCHEMA_CONTRACT_V0.2.md','utf8');
const between=(start,end)=>B.split(start)[1].split(end)[0],exact=(start,end)=>[...between(start,end).matchAll(/`([^`]+)`/g)].map(m=>m[1]).filter(s=>!s.startsWith('#'));
const approved=[...exact('### 4.2 Hero','### 4.3 Featured'),...exact('### 4.4 Three Decision Paths','### 4.5 Latest'),...exact('### 4.6 Evidence Standards','## 5. SEO')].filter(s=>!['START → SOURCING / TECHNICAL EVALUATION / TRADE & MARKET','FAQPage','QAPage'].includes(s));
const html=fs.readFileSync(base+'/RES-000_D32_GATE4.html','utf8'),g3html=fs.readFileSync(old+'/RES-000_D32_GATE3.html','utf8');
const main=s=>s.match(/<main[\s\S]*?<\/main>/)[0];
ck('INHERIT:exact-G3-body',main(html)===main(g3html));
ck('INHERIT:G3-source',hash(old+'/RES-000_D32_GATE3.html')==='b8ba906be4fca24c9af380da4c69d0d41295b9b9520317549f04c669637f208b');
const {renderSharedChrome}=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs');
const shared=renderSharedChrome({currentPageId:'RES-000',primaryLogoSrc:pathToFileURL(root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg').href,reverseLogoSrc:pathToFileURL(root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg').href});
for(const k of ['header','footer','dialog','style','behavior'])ck('SHARED:'+k,html.includes(shared[k]));
ck('H0:no-public-inventory-machine-or-placeholder',!/(ItemList|FAQPage|QAPage|application\/ld\+json|Non-China Titanium Dioxide Supply Guide|FIXTURE ONLY|LOCAL SIMULATION|PENDING COPY)/.test(html));
ck('H0:preview-not-production',html.includes('noindex,nofollow')&&C.includes('visual draft does not authorize indexing'));
ck('H0:no-forms-analytics',!/<form\b|gtag\(|googletagmanager|localStorage|sessionStorage|document\.cookie/.test(html));
const {projectInventory}=require(old+'/RES-000_D32_RESOURCE_MODEL.cjs');
const now='2026-09-21',r={pageId:'REVIEW-FIXTURE',scope:'tio2-my',language:'en',mappingApproved:true,urlApproved:true,contentApproved:true,claimApproved:true,publicApproved:true,routeLive:true,url:'/resources/review-fixture/',canonical:'https://tio2products.com/resources/review-fixture/',title:'REVIEW fixture',summary:'REVIEW fixture summary',type:'guide',lastReviewed:'2026-09-20',nextReviewDue:'2026-10-20',featured:true};
const empty=p=>p.items.length===0&&p.featured.length===0&&p.latest.length===0&&p.itemList===null&&p.heroTarget==='#research-paths';
ck('MODEL:H0',empty(projectInventory([],now)));ck('MODEL:H2',projectInventory([r],now).featured.length===1&&projectInventory([r],now).latest.length===0);
for(const k of ['mappingApproved','urlApproved','contentApproved','claimApproved','publicApproved','routeLive'])for(const v of [false,undefined,'true'])ck('MODEL:gate:'+k+':'+String(v),empty(projectInventory([{...r,[k]:v}],now)));
for(const [k,v] of [['canonical','https://tio2malaysia.com'+r.url],['url','/products/'],['title',''],['summary',''],['lastReviewed','2026-12-01'],['nextReviewDue',now],['eventReviewPending',true],['type','unknown']])ck('MODEL:exclude:'+k,empty(projectInventory([{...r,[k]:v}],now)));
const t={...r,type:'trade',freshness:'CURRENT',officialSource:true,market:'Fixture Brazil',topic:'Fixture topic',sourceName:'Fixture source',sourceUrl:'https://example.invalid/source',sourceDate:'2026-09-19',productOriginScope:'Fixture scope',statusCopy:'Reviewed fixture',factAnalysisLabel:'Fixture summary',freshnessOwner:'Fixture reviewer'};
for(const k of ['market','topic','officialSource','sourceName','sourceUrl','sourceDate','productOriginScope','statusCopy','factAnalysisLabel','freshnessOwner'])ck('MODEL:trade-atomic:'+k,empty(projectInventory([{...t,[k]:null}],now)));
for(const state of ['REVIEW_DUE','STALE_HOLD','WITHDRAWN'])ck('MODEL:hold:'+state,empty(projectInventory([{...t,freshness:state}],now)));
for(const [type,days] of [['guide',180],['technical',90],['trade',30]]){const date=new Date(now+'T00:00:00Z');date.setUTCDate(date.getUTCDate()-days);ck('MODEL:max-age:'+type,empty(projectInventory([{...r,type,lastReviewed:date.toISOString().slice(0,10),technicalAudit:true,nonEquivalenceAudit:true}],now)));}
const heights={1440:1000,1024:1000,768:1024,390:844,320:812},expectedLines={1440:3,1024:4,768:2,390:4,320:5};
async function stable(p){await p.evaluate(async()=>{await document.fonts.ready;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});}
async function geometry(p){return p.evaluate(()=>{const visible=e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(e).visibility!=='hidden'},rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}},hero=document.querySelector('[data-component="RootPageHero"]'),h=document.querySelector('h1'),s=getComputedStyle(h),ey=document.querySelector('.hero-eyebrow'),es=getComputedStyle(ey);return{width:innerWidth,height:document.documentElement.scrollHeight,scrollWidth:document.documentElement.scrollWidth,h1:{...rect(h),lines:Math.round(h.getBoundingClientRect().height/parseFloat(s.lineHeight)),font:s.fontSize,weight:s.fontWeight},hero:{...rect(hero),padding:getComputedStyle(hero).padding,variant:hero.dataset.variant},eyebrow:{...rect(ey),font:es.fontSize,weight:es.fontWeight,letter:es.letterSpacing,color:es.color},media:rect(document.querySelector('.res-hero-media')),sections:[...document.querySelectorAll('.res-section')].map(e=>({id:e.id,paddingTop:getComputedStyle(e).paddingTop,paddingBottom:getComputedStyle(e).paddingBottom,gutter:e.querySelector('.res-container').getBoundingClientRect().x})),grids:[...document.querySelectorAll('.res-grid')].map(e=>getComputedStyle(e).gridTemplateColumns.split(' ').length),bad:[...document.querySelectorAll('main p,main h1,main h2,main h3,main a,main dt,main dd')].filter(visible).filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.x<0||r.right>innerWidth+1||e.scrollWidth>e.clientWidth+1||s.textOverflow==='ellipsis'||s.webkitLineClamp!=='none'&&s.webkitLineClamp!=='auto'||s.overflowY==='hidden'&&e.scrollHeight>e.clientHeight+1}).map(e=>e.innerText),targets:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.innerText,...rect(e)})),font:document.fonts.check('16px Inter'),images:[...document.images].every(e=>e.complete&&e.naturalWidth>0)};});}
(async()=>{const browser=await chromium.launch(),version=browser.version();
for(const width of [1440,1024,768,390,320]){const p=await browser.newPage({viewport:{width,height:heights[width]},deviceScaleFactor:1,reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(base+'/RES-000_D32_GATE4.html').href);await stable(p);const g=await geometry(p);observations.push({state:'H0',...g});
const body=await p.locator('main').innerText();ck(width+':approved-complete-copy',approved.every(t=>body.includes(t)),approved.filter(t=>!body.includes(t)));ck(width+':single-h1',await p.locator('h1').count()===1);ck(width+':h2-order',(await p.locator('main h2').allTextContents()).join('|')==='Choose the right research path|How we use evidence|Buyer questions');ck(width+':H0-atomic-zero',await p.locator('#featured-resources,#latest-research,.res-resource').count()===0&&g.sections.length===3);
ck(width+':geometry',g.scrollWidth===width&&g.bad.length===0,g.bad);ck(width+':targets',g.targets.every(t=>t.w>=44&&t.h>=44));ck(width+':H1-natural-exception',g.h1.lines===expectedLines[width]&&g.h1.weight==='700'&&await p.locator('h1 br').count()===0,g.h1);ck(width+':eyebrow',g.eyebrow.font===(width===320?'11px':'14px')&&g.eyebrow.weight==='700'&&g.eyebrow.color==='rgb(89, 193, 187)');ck(width+':CARRY01',g.sections.every(s=>s.paddingTop==='84px'&&s.paddingBottom==='76px'));ck(width+':CARRY02',width>390||g.sections.every(s=>s.gutter===16));ck(width+':columns',g.grids.every(n=>n===(width>=1024?3:1)));ck(width+':hero-media',width>900?g.media.h>0:g.media.h===0);ck(width+':fonts-images',g.font&&g.images);ck(width+':formal-height',g.height===evidence.assets.find(a=>a.state==='H0_DEFAULT'&&a.viewport.width===width).height,{height:g.height});
ck(width+':metadata',await p.title()==='Titanium Dioxide Procurement Resources | TiO2 Malaysia'&&await p.locator('meta[name="description"]').getAttribute('content')===B.match(/\| Meta description \| `([^`]+)`/)[1]);ck(width+':nav-current',await p.locator('.desktopNav [aria-current="page"]').count()===1&&await p.locator('.mobileNav [aria-current="page"]').count()===1&&await p.locator('footer [aria-current]').count()===0);ck(width+':footer-legal',await p.locator('footer a[href="/privacy-policy/"]').count()===1&&await p.locator('footer a[href="/ms/privacy-policy/"]').count()===1&&await p.locator('footer a[href="/cookie-policy/"]').count()===1&&await p.locator('a[href*="terms"]').count()===0);
await p.locator('.hero-action').focus();ck(width+':focus-visible',await p.locator('.hero-action').evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));await p.locator('.hero-action').click();ck(width+':hero-anchor',new URL(p.url()).hash==='#research-paths');
if(width<=1100){await p.locator('.menuButton').click();ck(width+':menu-open',await p.locator('.mobileNav').isVisible()&&await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));ck(width+':menu-isolation',await p.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert));await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');ck(width+':menu-loop',await p.locator('.menuButton').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');ck(width+':menu-reverse',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');ck(width+':menu-escape',await p.locator('.mobileNav').isHidden()&&await p.locator('.menuButton').evaluate(e=>e===document.activeElement));await p.locator('.menuButton').click();await p.evaluate(()=>document.querySelector('.mobileNav').addEventListener('click',e=>e.preventDefault(),{once:true}));await p.locator('.mobileNav a[href="/resources/"]').click();ck(width+':menu-select',await p.locator('.mobileNav').isHidden()&&!(await p.locator('main').evaluate(e=>e.inert)));await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:1000});await p.waitForFunction(()=>document.querySelector('.mobileNav').hidden);ck(width+':menu-breakpoint',!(await p.locator('main').evaluate(e=>e.inert)));await p.setViewportSize({width,height:heights[width]});}
await p.locator('#cookie-trigger').click();ck(width+':cookie-open',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));ck(width+':cookie-inactive',(await p.locator('dialog').innerText()).includes('No optional Analytics'));ck(width+':cookie-contained',await p.locator('dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.x>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}));await p.keyboard.press('Shift+Tab');ck(width+':cookie-reverse',await p.locator('dialog a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');ck(width+':cookie-loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');ck(width+':cookie-return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));ck(width+':no-runtime-errors',errors.length===0,errors);await p.close();}
for(const width of [340,341,360,374,375]){const p=await browser.newPage({viewport:{width,height:844}});await p.goto(pathToFileURL(base+'/RES-000_D32_GATE4.html').href);await stable(p);const g=await geometry(p);ck(width+':shared-narrow-boundary',g.eyebrow.font===(width<=340?'11px':width<=374?'12px':'14px')&&g.eyebrow.weight==='700'&&Math.abs(parseFloat(g.eyebrow.letter)/parseFloat(g.eyebrow.font)-.08)<.001&&g.scrollWidth===width&&g.bad.length===0,g.eyebrow);await p.close();}
for(const state of ['H2','H4'])for(const width of [1440,1024,768,390,320]){const p=await browser.newPage({viewport:{width,height:heights[width]}});await p.goto(pathToFileURL(base+'/RES-000_D32_'+state+'_LOCAL_SIMULATION.html').href);await stable(p);const g=await geometry(p);observations.push({state,...g});ck(state+width+':clearly-simulation',(await p.locator('.res-fixture-banner').innerText()).includes('LOCAL SIMULATION'));ck(state+width+':conditional-anchor',await p.locator('.hero-action').getAttribute('href')==='#featured-resources');ck(state+width+':one-card-no-duplicate',await p.locator('#featured-resources .res-resource').count()===1&&await p.locator('#latest-research').count()===0);ck(state+width+':geometry',g.scrollWidth===width&&g.bad.length===0,g.bad);ck(state+width+':conditional-spacing',g.sections.every(s=>s.paddingTop==='84px'&&s.paddingBottom==='76px'));ck(state+width+':full-main-copy',approved.every(t=>(state==='H2'||state==='H4')?true:t));
// H2 has one guide; H4 intentionally adds a distinct trade card in Latest.
const cardHrefs=await p.locator('.res-resource > a').evaluateAll(es=>es.map(e=>e.getAttribute('href')));
const cardCheck=checks.findLast(c=>c.id===state+width+':one-card-no-duplicate');
cardCheck.id=state+width+':conditional-card-composition';cardCheck.detail=cardHrefs;
cardCheck.status=(await p.locator('#featured-resources .res-resource').count()===1&&await p.locator('#latest-research .res-resource').count()===(state==='H2'?0:1)&&new Set(cardHrefs).size===cardHrefs.length)?'PASS':'FAIL';
const renderedMain=await p.locator('main').innerText();checks.findLast(c=>c.id===state+width+':full-main-copy').status=approved.every(t=>renderedMain.includes(t))?'PASS':'FAIL';
if(state==='H2'){const vals=exact('### 4.3 Featured Resources','### 4.4 Three Decision Paths').filter(t=>t!=='RES-ORIGIN');const rendered=await p.locator('#featured-resources').innerText();ck(state+width+':approved-feature-copy',vals.every(t=>rendered.includes(t)),vals.filter(t=>!rendered.includes(t)));}else{ck(state+width+':eight-metadata',await p.locator('[data-fixture="trade"] dt').count()===8);ck(state+width+':metadata-not-empty',await p.locator('[data-fixture="trade"] dd').evaluateAll(es=>es.every(e=>e.textContent.trim()&&e.scrollWidth<=e.clientWidth+1)));}await p.close();}
for(const width of [390,320]){const p=await browser.newPage({javaScriptEnabled:false,viewport:{width,height:844}});await p.goto(pathToFileURL(base+'/RES-000_D32_GATE4.html').href);ck('NOJS:'+width,await p.locator('.res-faq article').count()===5&&await p.locator('.res-faq p').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>0)));await p.close();}
await browser.close();for(const r of rows)ck('AFTER:'+r.path,hash(r.path)===r.sha256);const result={reviewer:'/root/about_root_d32',author:'/root/res_root_d32',mode:'INDEPENDENT_GATE5_REVIEW',time:new Date().toISOString(),browser:version,bundle,source:freeze.source_identity,freezeSha256:hash(base+'/RES-000_D32_GATE4_FREEZE.json'),checks,observations,ruleChanges,passed:checks.filter(x=>x.status==='PASS').length,failed:checks.filter(x=>x.status==='FAIL').length};fs.writeFileSync(path.join(__dirname,'independent-results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>x.status==='FAIL'),ruleChanges,bundle}));process.exitCode=result.failed?1:0;
})().catch(e=>{console.error(e);process.exit(2)});
