// Independent read-only R01 recheck. Output confined to reviewer directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',dir=root+'/pages/markets/04_planning/d32-gate4-v0.2',old=root+'/pages/markets/04_planning/d32-gate4-v0.1',checks=[],rows=[];
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),check=(id,pass,actual)=>checks.push({id,pass:!!pass,actual});
(async()=>{const f=read(dir+'/freeze.json'),prior=read(old+'/freeze.json'),lock=read(dir+'/source-lock.json'),ev=read(dir+'/evidence-index.json');
for(const x of [...f.files,f.evidence_index])check('new identity '+x.path,sha(x.path)===x.sha256&&fs.statSync(x.path).size===x.bytes,x.sha256);
check('old46 preserved',[...prior.files,prior.evidence_index].every(x=>sha(x.path)===x.sha256&&fs.statSync(x.path).size===x.bytes),prior.files.length+1);
const material=f.files.map(x=>({p:path.relative(root,x.path).replaceAll('\\','/'),h:sha(x.path)})).sort((a,b)=>a.p.localeCompare(b.p)).map(x=>x.p+'\0'+x.h+'\n').join('');check('requested bundle',crypto.createHash('sha256').update(material).digest('hex')==='811d352708f175ec47058ba2d043bfd5a9fc92492b7675a1609d2846d9051ca1',f.bundle_id);
check('source lock unchanged',lock.files.every(x=>sha(x.path)===x.sha256),lock.files.length);
check('decision identity',sha(root+'/docs/architecture/ROOT_PAGE_NARROW_VISUAL_AND_DOC_FEEDBACK_DECISION_V1.0.md')==='6ff4253b56936ccf9838f27d7532053a501de82aec99b9ab1518b38de667f1a9','ROOT-NARROW-VISUAL-20260921');
const source=fs.readFileSync(dir+'/market-visual.html','utf8'),previous=fs.readFileSync(old+'/market-visual.html','utf8');check('exact markup except stylesheet bindings',source.replace('href="../d32-gate4-v0.1/visual.css"','href="visual.css"').replace('<link rel="stylesheet" href="root-narrow-projection.css">','')===previous,'Complete markup/title/actions/JS preserved');
for(const x of [...ev.newFormal,...ev.inheritedFormal]){const b=fs.readFileSync(x.path);check('formal '+path.basename(x.path),sha(x.path)===x.sha256&&b.length===x.bytes&&b.readUInt32BE(16)===x.physical_width&&b.readUInt32BE(20)===x.physical_height&&x.dpr===1,{width:x.physical_width,height:x.physical_height});}
check('superseded scope excluded',!f.files.some(x=>x.path.includes('pre-slot-scope'))&&ev.newFormal.length===7&&ev.inheritedFormal.length===15,'7 new +15 inherited; provisional scope captures diagnostic only');
const browser=await chromium.launch({headless:true});
async function open(base,width){const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});await p.goto(pathToFileURL(base+'/market-visual.html').href);await p.evaluate(()=>document.fonts.ready);return p;}
async function snap(p){return p.evaluate(()=>{const e=document.querySelector('.heroText>.eyebrow'),s=getComputedStyle(e),r=document.createRange();r.selectNodeContents(e);const rects=[...r.getClientRects()],b=e.getBoundingClientRect(),h=document.querySelector('h1'),hs=getComputedStyle(h),all=[...document.querySelectorAll('main *')].filter(x=>x.checkVisibility());return {text:e.textContent,lines:new Set(rects.map(x=>Math.round(x.y))).size,font:s.fontSize,weight:s.fontWeight,spacing:s.letterSpacing,color:s.color,transform:s.transform,case:s.textTransform,contained:rects.every(x=>x.left>=b.left-.1&&x.right<=b.right+.1),textWidth:Math.max(...rects.map(x=>x.width)),box:b.width,overflow:document.documentElement.scrollWidth>innerWidth,h1:{text:h.textContent,size:hs.fontSize,weight:hs.fontWeight,lines:Math.round(h.getBoundingClientRect().height/parseFloat(hs.lineHeight))},padding:getComputedStyle(document.querySelector('.rootHero')).padding,secondary:getComputedStyle(document.querySelector('.heroIndex .eyebrow')).fontSize,small:[...document.querySelectorAll('a,button')].filter(x=>x.checkVisibility()).filter(x=>{const b=x.getBoundingClientRect();return b.width<44||b.height<44}).length,boxes:all.map(x=>{const b=x.getBoundingClientRect();return [x.tagName,x.id,b.x,b.y+scrollY,b.width,b.height]}),bodyStyles:[...document.querySelectorAll('main *')].filter(x=>x.checkVisibility()&&!x.closest('.rootHero')).map(x=>{const s=getComputedStyle(x);return [x.tagName,x.textContent,s.fontSize,s.lineHeight,s.color,s.padding,s.margin]})}});}
for(const width of [320,340,341,374,375,390,768,1024,1440]){const p=await open(dir,width),q=await open(old,width),a=await snap(p),b=await snap(q);rows.push({width,current:a,prior:b});
check(width+' complete single-line/containment',a.text==='Destination market navigation'&&a.lines===1&&a.contained&&!a.overflow,a);
check(width+' common token/brand',a.font===(width<=340?'11px':width<=374?'12px':b.font)&&a.weight==='700'&&Math.abs(parseFloat(a.spacing)/parseFloat(a.font)-.08)<.0001&&a.color===b.color&&a.case===b.case&&a.transform==='none',{font:a.font,spacing:a.spacing,color:a.color});
check(width+' unchanged H1/shared shell/secondary',JSON.stringify(a.h1)===JSON.stringify(b.h1)&&a.padding===b.padding&&a.secondary===b.secondary,{h1:a.h1,padding:a.padding,secondary:a.secondary});
check(width+' unchanged body styling/44targets',JSON.stringify(a.bodyStyles)===JSON.stringify(b.bodyStyles)&&a.small===0,{small:a.small});
if(width>=375)check(width+' all visible main geometry exact',JSON.stringify(a.boxes)===JSON.stringify(b.boxes),a.boxes.length);
await p.locator('.primary').focus();check(width+' focus retained',await p.locator('.primary').evaluate(e=>e.matches(':focus-visible')&&getComputedStyle(e).outlineWidth==='3px'),'visible3px');
await p.locator('.euPanel>.textAction').hover();check(width+' hover repair retained',await p.locator('.euPanel>.textAction').evaluate(e=>getComputedStyle(e).color==='rgb(0, 108, 102)'&&getComputedStyle(e).backgroundColor==='rgb(234, 247, 246)'),'5.733954:1 unchanged color pair');await p.close();await q.close();}
const p=await open(dir,320);await p.locator('.menuButton').click();check('320 menu focus/inert',await p.locator('main').evaluate(e=>e.inert)&&await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check('320 menu recovery',await p.locator('.menuButton').evaluate(e=>e===document.activeElement)&&!await p.locator('main').evaluate(e=>e.inert));await p.locator('#eu-toggle').focus();await p.keyboard.press('Enter');check('320 EU Enter',await p.locator('#eu-countries').isVisible()&&await p.locator('#eu-countries li').count()===6);await p.keyboard.press('Space');check('320 EU Space',!await p.locator('#eu-countries').isVisible());await p.locator('#cookie-trigger').click();check('320 Cookie focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check('320 Cookie recovery',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.close();
await browser.close();check('post-run candidate preservation',[...f.files,f.evidence_index].every(x=>sha(x.path)===x.sha256),'No candidate writes');const result={timestamp:new Date().toISOString(),reviewer:'/root/doc_root_d32',type:'TARGETED_INDEPENDENT_RECHECK',bundle:f.bundle_id,source:sha(dir+'/market-visual.html'),freeze_sha256:sha(dir+'/freeze.json'),new_records:f.files.length+1,checks,rows,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length};fs.writeFileSync(__dirname+'/observations.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,new_records:result.new_records,freeze:result.freeze_sha256,failures:checks.filter(x=>!x.pass),measurements:rows.map(x=>({width:x.width,font:x.current.font,lines:x.current.lines,text:x.current.textWidth,box:x.current.box}))},null,2));process.exitCode=result.failed?1:0;})();
