const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec/',base=root+'pages/resources/r706-alternative/04_planning/gate4-v0.1/',out=__dirname+'/';
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const freeze=json(base+'freeze-record.json'),index=json(base+'evidence-index.json'),input=json(base+'input-index.json');
const report={dispatch_id:'G5-9PAGE-REVIEW-20260907-01/RES-R706/INITIAL',reviewer:'/root/g5_r706',actual_author:freeze.actual_author,source:freeze.source,startedAt:new Date().toISOString(),identity:[],runtime:[],externalRequests:[]};
function identity(x){const b=fs.readFileSync(x.path),a={path:x.path,bytes:b.length,sha256:hash(b),expectedBytes:x.bytes,expectedSha256:x.sha256};a.match=a.sha256===x.sha256&&(x.bytes===undefined||a.bytes===x.bytes);if(x.physical){a.physical={width:b.readUInt32BE(16),height:b.readUInt32BE(20)};a.match=a.match&&JSON.stringify(a.physical)===JSON.stringify(x.physical)}report.identity.push(a)}
const all=[freeze.source,freeze.input_index,freeze.evidence_index,freeze.source_lock,freeze.preflight,freeze.capture_check,...freeze.formal_assets,...index.approval_core,...index.dependencies,...index.diagnostic_support,...input.inputs,...input.dependencies,...input.sharedProvenance];
for(const x of all)if(!report.identity.some(y=>y.path===x.path))identity(x);
report.freezeIdentity={bytes:fs.statSync(base+'freeze-record.json').size,sha256:hash(fs.readFileSync(base+'freeze-record.json'))};
report.methodIdentity=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE5_GATE6_ACCEPTANCE_CONTRACT_V1.0.md'].map(p=>({path:root+p,sha256:hash(fs.readFileSync(root+p))}));
const source=read(freeze.source.path),old=read(root+'pages/resources/r706-alternative/04_planning/gate3-v0.1/RES-R706_GATE3_WIREFRAME_V0.1.html');
const shared=require(root+'docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'RES-000',primaryLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg'});
report.sourceInspection={mainExactToApprovedG3:source.match(/<main>[\s\S]*?<\/main>/)[0]===old.match(/<main>[\s\S]*?<\/main>/)[0],shared:Object.fromEntries(['header','footer','dialog','style','behavior'].map(k=>[k,source.includes(shared[k])]))};
function add(width,state,data){report.runtime.push({width,state,evidenceType:'ACTUAL_RUNTIME',...data})}
(async()=>{const browser=await chromium.launch({headless:true});report.browser=browser.version();
for(const width of [1440,768,390]){const height=width===390?844:900,ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});await ctx.route(/^https?:/,route=>{report.externalRequests.push(route.request().url());return route.abort()});const page=await ctx.newPage();page.on('pageerror',e=>add(width,'error',{error:e.message}));await page.goto(pathToFileURL(freeze.source.path).href);await page.evaluate(()=>document.fonts.ready);
add(width,'default',await page.evaluate(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&!e.closest('[hidden]');const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}};const targets=[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.innerText,href:e.getAttribute('href'),...rect(e)}));const content=[...document.querySelectorAll('main h1,main h2,main h3,main p,main li')].map(e=>({tag:e.tagName,text:e.innerText,rect:rect(e),overflow:getComputedStyle(e).overflow}));return {dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,documentHeight:document.documentElement.scrollHeight,headerHeight:document.querySelector('header').getBoundingClientRect().height,font:document.fonts.check('17px Inter'),images:[...document.images].map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0})),targets,targetFailures:targets.filter(t=>t.w<43.99||t.h<43.99),content,modules:document.querySelectorAll('main section').length,hiddenNavDisplay:getComputedStyle(document.querySelector('.desktopNav')).display}}));
const anchor=page.locator('a[href="#evaluation-brief"]');await anchor.click();add(width,'anchor-click',await page.evaluate(()=>({hash:location.hash,active:document.activeElement.id,y:document.querySelector('#evaluation-brief').getBoundingClientRect().top})));await anchor.focus();await page.keyboard.press('Enter');await page.keyboard.press('Tab');add(width,'anchor-enter-next-tab',await page.evaluate(()=>({active:document.activeElement.outerHTML})));
const links=page.locator('main a:not([href^="#"])');for(let i=0;i<await links.count();i++)await links.nth(i).click();add(width,'body-link-intents',{evidenceType:'LOCAL_SIMULATION',intents:await page.evaluate(()=>window.localNavigationIntents)});
for(const s of ['.module-1 a[href="/products/"]','.module-2 a','.module-5 a','.module-6 a']){const a=page.locator(s).first();await a.hover();const hover=await a.evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));await a.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');const focus=await a.evaluate(e=>({active:document.activeElement===e,color:getComputedStyle(e).color,outline:getComputedStyle(e).outline,outlineOffset:getComputedStyle(e).outlineOffset}));add(width,'colored-state',{selector:s,hover,focus});}
if(width<1101){const toggle=page.locator('.menuButton'),menu=page.locator('.mobileNav');await toggle.focus();await page.keyboard.press('Enter');add(width,'menu-entry',await page.evaluate(()=>({active:document.activeElement.textContent,expanded:document.querySelector('.menuButton').ariaExpanded,inert:[...document.querySelectorAll('main,footer,.logoLink,.headerRfq')].map(e=>e.inert),bodyOverflow:document.body.style.overflow,targets:[...document.querySelectorAll('.mobileNav a')].map(e=>({text:e.innerText,href:e.getAttribute('href'),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}))})));
await toggle.focus();await page.keyboard.press('Shift+Tab');const reverse=await page.evaluate(()=>document.activeElement.textContent);await page.keyboard.press('Tab');const forward=await page.evaluate(()=>document.activeElement.textContent);await page.keyboard.press('Escape');add(width,'menu-cycle-escape',{reverse,forward,...await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,focusReturn:document.activeElement===document.querySelector('.menuButton'),restored:!document.querySelector('main').inert&&document.body.style.overflow===''}))});
for(let i=0;i<8;i++){await toggle.click();await menu.locator('a').nth(i).click();add(width,'menu-link-exit',{instance:i,...await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,intent:window.localNavigationIntents.at(-1),restored:!document.querySelector('main').inert}))});}
await toggle.click();await toggle.click();add(width,'menu-button-close',{closed:await menu.isHidden()});await toggle.click();await page.setViewportSize({width:1440,height});await page.waitForTimeout(60);add(width,'menu-resize-desktop',await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,inert:document.querySelector('main').inert,overflow:document.body.style.overflow,active:document.activeElement.outerHTML})));await page.setViewportSize({width,height});}
const trigger=page.locator('#cookie-trigger');await trigger.focus();await page.keyboard.press('Enter');add(width,'cookie-entry',await page.evaluate(()=>({open:document.querySelector('dialog').open,active:document.activeElement.textContent,rect:document.querySelector('dialog').getBoundingClientRect().toJSON(),scroll:document.querySelector('dialog').scrollHeight,client:document.querySelector('dialog').clientHeight})));await page.keyboard.press('Shift+Tab');const reverse=await page.evaluate(()=>document.activeElement.textContent);await page.keyboard.press('Tab');const forward=await page.evaluate(()=>document.activeElement.textContent);await page.locator('main a').first().evaluate(e=>e.focus());const backgroundBlocked=await page.evaluate(()=>document.activeElement.closest('dialog')!==null);await page.keyboard.press('Escape');await page.waitForTimeout(20);add(width,'cookie-cycle-escape',{reverse,forward,backgroundBlocked,...await page.evaluate(()=>({closed:!document.querySelector('dialog').open,focusReturn:document.activeElement.id==='cookie-trigger'}))});await trigger.click();await page.locator('dialog a').click();add(width,'cookie-policy-intent',{evidenceType:'LOCAL_SIMULATION',intent:await page.evaluate(()=>window.localNavigationIntents.at(-1))});await page.locator('[data-cookie-close]').click();await page.waitForTimeout(20);add(width,'cookie-close',await page.evaluate(()=>({closed:!document.querySelector('dialog').open,focusReturn:document.activeElement.id==='cookie-trigger'})));await ctx.close();}
const ctx=await browser.newContext({viewport:{width:720,height:450},deviceScaleFactor:2,reducedMotion:'reduce'});const page=await ctx.newPage();await page.goto(pathToFileURL(freeze.source.path).href);await page.evaluate(()=>document.fonts.ready);add(720,'effective-200-percent-reflow',{evidenceType:'LOCAL_SIMULATION',...await page.evaluate(()=>({dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,headerHeight:document.querySelector('header').getBoundingClientRect().height,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches}))});await ctx.close();await browser.close();report.finishedAt=new Date().toISOString();report.sourceUnchanged=hash(fs.readFileSync(freeze.source.path))===freeze.source.sha256;fs.writeFileSync(out+'observations.json',JSON.stringify(report,null,2));console.log(JSON.stringify({identityCount:report.identity.length,mismatches:report.identity.filter(x=>!x.match),sourceInspection:report.sourceInspection,runtimeCount:report.runtime.length,targetFailures:report.runtime.filter(x=>x.targetFailures?.length),externalRequests:report.externalRequests,sourceUnchanged:report.sourceUnchanged}));})().catch(e=>{report.failure=e.stack;fs.writeFileSync(out+'observations-failure.json',JSON.stringify(report,null,2));console.error(e);process.exit(1)});
