const fs=require('fs');const crypto=require('crypto');const sharp=require('sharp');
const root='D:/23MySec';const gate=`${root}/pages/applications/plastics/04_planning/gate4-v0.1`;const review=`${root}/pages/applications/plastics/05_review/gate4-complete-independent-v0.1`;
const inputPath=`${gate}/APP-PLAS_GATE4_INPUT_INDEX_V0.1.json`;const freezePath=`${gate}/APP-PLAS_GATE4_FREEZE_RECORD_V0.1.json`;const evidencePath=`${gate}/APP-PLAS_GATE4_EVIDENCE_INDEX_V0.1.json`;
function digest(p){const b=fs.readFileSync(p);return{bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}}
function compare(x){const exists=fs.existsSync(x.path),actual=exists?digest(x.path):null;return{path:x.path,expected:{bytes:x.bytes,sha256:x.sha256},exists,actual,exact:!!actual&&actual.bytes===x.bytes&&actual.sha256===x.sha256}}
(async()=>{const input=JSON.parse(fs.readFileSync(inputPath));const freeze=JSON.parse(fs.readFileSync(freezePath));const evidence=JSON.parse(fs.readFileSync(evidencePath));
 const inputs=input.inputs.map(compare);const images=[];for(const x of evidence.images){const c=compare(x);let meta=null;if(c.exists)meta=await sharp(x.path).metadata();const hasDeclaredDimensions=Number.isFinite(x.physical_width)&&Number.isFinite(x.physical_height);images.push({...c,declaredDimensions:hasDeclaredDimensions?[x.physical_width,x.physical_height]:null,actualDimensions:meta?[meta.width,meta.height]:null,dimensionStatus:!hasDeclaredDimensions?'NOT_DECLARED':(!!meta&&meta.width===x.physical_width&&meta.height===x.physical_height?'EXACT':'MISMATCH')});}
 const declared=[['source',freeze.source],['input_index',freeze.input_index],['workset',freeze.workset],['preflight',freeze.preflight],['runtime_verification',freeze.runtime_verification],['static_visual_readback',freeze.static_visual_readback]]
  .filter(x=>x[1]?.path&&x[1]?.sha256).map(([label,x])=>({label,...compare(x)}));
 const freeze390=freeze.renderer?.viewports?.find(x=>x.width===390),evidence390Chrome=images.filter(x=>/APP-PLAS_GATE4_390_(MENU|COOKIE)_V0\.1\.png$/.test(x.path));
 const result={audit:'APP-PLAS Gate 4 independent identity audit',workset_id:evidence.workset_id,freeze_id:evidence.freeze_id,audited_at:new Date().toISOString(),records:{input_index:{path:inputPath,...digest(inputPath)},freeze:{path:freezePath,...digest(freezePath)},evidence:{path:evidencePath,...digest(evidencePath)}},frozen_inputs:{expected:52,exact:inputs.filter(x=>x.exact).length,mismatches:inputs.filter(x=>!x.exact),checks:inputs},declared_freeze_bindings:{expected:declared.length,exact:declared.filter(x=>x.exact).length,mismatches:declared.filter(x=>!x.exact),checks:declared},freeze_renderer_consistency:{status:freeze390?.height===900&&evidence390Chrome.every(x=>x.actualDimensions?.[1]===900)?'EXACT':'MISMATCH',declared_390_viewport:freeze390,evidence_390_menu_cookie_actual_dimensions:evidence390Chrome.map(x=>({path:x.path,actualDimensions:x.actualDimensions}))},evidence_images:{expected:92,exact_identity:images.filter(x=>x.exact).length,identity_mismatches:images.filter(x=>!x.exact),declared_dimensions:images.filter(x=>x.dimensionStatus!=='NOT_DECLARED').length,exact_declared_dimensions:images.filter(x=>x.dimensionStatus==='EXACT').length,dimension_mismatches:images.filter(x=>x.dimensionStatus==='MISMATCH'),dimensions_not_declared:images.filter(x=>x.dimensionStatus==='NOT_DECLARED'),checks:images}};
 fs.writeFileSync(`${review}/identity-audit.json`,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({records:result.records,inputs:`${result.frozen_inputs.exact}/52`,inputMismatches:result.frozen_inputs.mismatches.map(x=>x.path),bindings:`${result.declared_freeze_bindings.exact}/${result.declared_freeze_bindings.expected}`,bindingMismatches:result.declared_freeze_bindings.mismatches.map(x=>x.label),freezeRendererConsistency:result.freeze_renderer_consistency,imageIdentity:`${result.evidence_images.exact_identity}/92`,identityMismatches:result.evidence_images.identity_mismatches.map(x=>x.path),declaredDimensions:`${result.evidence_images.exact_declared_dimensions}/${result.evidence_images.declared_dimensions}`,dimensionMismatches:result.evidence_images.dimension_mismatches.map(x=>({path:x.path,declared:x.declaredDimensions,actual:x.actualDimensions})),dimensionsNotDeclared:result.evidence_images.dimensions_not_declared.length},null,2));})();
