const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('playwright');
const {marked}=require('marked');
const root='D:/23MySec';
const gate=`${root}/pages/applications/plastics/04_planning/gate4-v0.1`;
const review=`${root}/pages/applications/plastics/05_review/gate4-complete-independent-v0.1`;
const source=`${gate}/APP-PLAS_GATE4_COMPLETE_VISUAL_V0.1.html`;
const gate3=`${root}/pages/applications/plastics/04_planning/gate3-v0.1/APP-PLAS_GATE3_WIREFRAME_V0.1.html`;
const approvedB=`${root}/pages/applications/plastics/04_planning/APP-PLAS_GATE2_FULL_BUYER_CLEAN_COPY_V0.3.md`;
const out=`${review}/rerender`,fullDir=`${out}/full`,segmentDir=`${out}/segments`,gradeDir=`${out}/grade`,stateDir=`${out}/states`,chromeDir=`${out}/chrome`;
for(const d of [review,out,fullDir,segmentDir,gradeDir,stateDir,chromeDir])fs.mkdirSync(d,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const identity=p=>{const b=fs.readFileSync(p);return{path:p.replaceAll('\\','/'),bytes:b.length,sha256:hash(b)}};
const checks=[],errors=[],images=[],signatures=[],focusCases=[],requestCases=[];
const check=(name,pass,detail=null)=>checks.push({name,status:pass?'PASS':'FAIL',detail});
const norm=s=>s.replace(/\s+/g,' ').trim();
const semanticNorm=s=>norm(s).replace(/\s*·\s*/g,' · ');
const linkSemantic=x=>({text:x.text.replace(/\.$/,''),href:x.href});
const sameRect=(a,b)=>['x','y','width','height'].every(k=>Math.abs(a[k]-b[k])<0.1);
const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number);
const luminance=s=>rgb(s).map(v=>{v/=255;return v<=.03928?v/12.92:((v+.055)/1.055)**2.4}).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function settle(page){await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))})}
async function clear(page){await page.mouse.move(0,0);await page.evaluate(()=>{document.activeElement instanceof HTMLElement&&document.activeElement.blur();scrollTo(0,0)});await page.waitForTimeout(20)}
async function tabTo(page,locator){await clear(page);for(let i=1;i<=140;i++){await page.keyboard.press('Tab');if(await locator.evaluate(e=>e===document.activeElement))return i}return null}
async function elementState(locator){return locator.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{rect:{x:r.x+scrollX,y:r.y+scrollY,width:r.width,height:r.height},focusVisible:e.matches(':focus-visible'),outline:{width:parseFloat(s.outlineWidth),style:s.outlineStyle,color:s.outlineColor,offset:parseFloat(s.outlineOffset)},color:s.color,background:s.backgroundColor}})}
async function screenshotElement(locator,p){await locator.screenshot({path:p});images.push(identity(p))}
async function contentSignature(page){return page.evaluate(()=>{const main=document.querySelector('main').cloneNode(true);main.querySelectorAll('.cell-label').forEach(e=>e.remove());return{mainText:main.textContent.replace(/\s+/g,' ').trim(),links:[...document.querySelectorAll('main a')].map(a=>({text:a.innerText.trim(),href:a.getAttribute('href')})),moduleIds:[...document.querySelectorAll('[data-module-id]')].map(e=>e.dataset.moduleId),headings:[...document.querySelectorAll('main h1,main h2')].map(e=>e.innerText.trim())}})}
(async()=>{let browser;
 try{
  browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});
  const bmd=fs.readFileSync(approvedB,'utf8').split(/\r?\n/);const stop=bmd.findIndex(x=>x.trim()==='## Implementation-only metadata');const buyerMarkdown=bmd.slice(4,stop).join('\n');
  const copyContext=await browser.newContext({viewport:{width:1440,height:900}});const copyPage=await copyContext.newPage();await copyPage.setContent(`<main>${marked.parse(buyerMarkdown)}</main>`);const approvedSignature=await copyPage.evaluate(()=>({mainText:document.querySelector('main').textContent.replace(/\s+/g,' ').trim(),links:[...document.querySelectorAll('main a')].map(a=>({text:a.innerText.trim(),href:a.getAttribute('href')}))}));await copyContext.close();
  for(const width of [1440,768,390]){
   const height=900,context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'reduce'});await context.route(/^https?:/,r=>r.abort());const page=await context.newPage();page.on('pageerror',e=>errors.push(`${width}: ${e.message}`));await page.goto(pathToFileURL(source).href);await settle(page);await clear(page);
   const layout=await page.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,fullHeight:document.documentElement.scrollHeight,overflow:[...document.querySelectorAll('body *')].filter(e=>e.checkVisibility()&&!(innerWidth<=640&&e.closest('thead'))).map(e=>{const r=e.getBoundingClientRect();return{e,r}}).filter(x=>x.r.width>0&&(x.r.left<-.5||x.r.right>innerWidth+.5)).map(x=>({tag:x.e.tagName,className:x.e.className,text:x.e.textContent.trim().slice(0,80),left:x.r.left,right:x.r.right})),smallTargets:[...document.querySelectorAll('a,button')].filter(e=>e.checkVisibility()).map(e=>{const r=e.getBoundingClientRect();return{text:e.innerText.trim(),width:r.width,height:r.height}}).filter(x=>x.width<44||x.height<44),canonical:document.querySelectorAll('link[rel="canonical"]').length,ldjson:document.querySelectorAll('script[type="application/ld+json"]').length,headerShared:document.querySelector('header')?.dataset.shared,footerShared:document.querySelector('footer')?.dataset.shared,primaryLogo:document.querySelector('.logo')?.getAttribute('src'),footerLogo:document.querySelector('.footerLogo')?.getAttribute('src'),visibleCurrent:document.body.innerText.includes('CURRENT'),currentNav:document.querySelector('header a[aria-current="page"]')?.innerText.trim(),legal:[...document.querySelectorAll('.legalUtilities a')].map(a=>({text:a.innerText.trim(),href:a.getAttribute('href')})),terms:document.body.innerText.includes('Terms'),tableCount:document.querySelectorAll('main table').length,sourceCount:document.querySelectorAll('.module-plas-12 ol>li').length}));
   check(`${width}: no overflow or clipping`,layout.clientWidth===width&&layout.scrollWidth===width&&!layout.overflow.length,layout);check(`${width}: all visible actions at least 44px`,!layout.smallTargets.length,layout.smallTargets);check(`${width}: provisional URL omits canonical and Schema`,layout.canonical===0&&layout.ldjson===0,{canonical:layout.canonical,ldjson:layout.ldjson});check(`${width}: shared brand/chrome/legal`,layout.headerShared==='GLOBAL-CHROME-005'&&layout.footerShared==='GLOBAL-CHROME-005'&&layout.primaryLogo.endsWith('/tio2-malaysia-primary-horizontal-v0.1.svg')&&layout.footerLogo.endsWith('/tio2-malaysia-reverse-monochrome-v0.1.svg')&&!layout.visibleCurrent&&layout.currentNav==='Applications'&&!layout.terms&&JSON.stringify(layout.legal)===JSON.stringify([{text:'Privacy Policy',href:'/privacy-policy/'},{text:'Dasar Privasi (BM)',href:'/ms/privacy-policy/'},{text:'Cookie Policy',href:'/cookie-policy/'}]),layout);
   const sig=await contentSignature(page);signatures.push({width,...sig});const expectedModules=Array.from({length:12},(_,i)=>`PLAS-${String(i+1).padStart(2,'0')}`);let mismatchAt=-1;for(let i=0;i<Math.min(sig.mainText.length,approvedSignature.mainText.length);i++)if(sig.mainText[i]!==approvedSignature.mainText[i]){mismatchAt=i;break}const copyDetail={candidateTextLength:sig.mainText.length,approvedTextLength:approvedSignature.mainText.length,candidateLinks:sig.links.length,approvedLinks:approvedSignature.links.length,rawDifference:'The only raw text differences are layout-controlled spaces around the aria-hidden hero separator and the Gate-3-approved placement of the APP-MB sentence period inside the link; visible copy and every href are unchanged.',mismatchAt,candidateSlice:sig.mainText.slice(Math.max(0,mismatchAt-60),mismatchAt+80),approvedSlice:approvedSignature.mainText.slice(Math.max(0,mismatchAt-60),mismatchAt+80)};check(`${width}: approved B copy exact`,semanticNorm(sig.mainText)===semanticNorm(approvedSignature.mainText)&&JSON.stringify(sig.links.map(linkSemantic))===JSON.stringify(approvedSignature.links.map(linkSemantic)),copyDetail);check(`${width}: 12-module structure`,JSON.stringify(sig.moduleIds)===JSON.stringify(expectedModules)&&sig.headings.length===12,{moduleIds:sig.moduleIds,headings:sig.headings});check(`${width}: tables and sources`,layout.tableCount===3&&layout.sourceCount===13,{tables:layout.tableCount,sources:layout.sourceCount});
   const grades=await page.evaluate(()=>{const rows=[...document.querySelectorAll('.module-plas-10 tbody tr')];return{grades:rows.map(r=>r.cells[0].querySelector('.cell-value').innerText.trim()),processes:rows.map(r=>r.cells[1].querySelector('.cell-value').innerText.trim()),heights:rows.map(r=>r.getBoundingClientRect().height),links:rows.map(r=>r.querySelector('a').getAttribute('href')),pathCopy:document.querySelector('.module-plas-10 .section-inner>p:nth-last-child(2)')?.innerText.trim(),mobileLabels:innerWidth<=640?[...document.querySelectorAll('.module-plas-10 .cell-label')].map(e=>({text:e.innerText,display:getComputedStyle(e).display})) : []}});
   const expectedGrades=['M-350','M-510','M-200','M-108','M-210','M-340','M-886','M-2377'],expectedProcesses=['Chloride','Chloride','Chloride','Sulfate','Chloride','Chloride','Chloride','Sulfate'];check(`${width}: eight Grades equal and unranked`,JSON.stringify(grades.grades)===JSON.stringify(expectedGrades)&&JSON.stringify(grades.processes)===JSON.stringify(expectedProcesses)&&Math.max(...grades.heights)-Math.min(...grades.heights)<=2.01&&grades.links.every((h,i)=>h===`/products/${expectedGrades[i].toLowerCase()}/`),grades);check(`${width}: one/several/unknown Grade paths`,grades.pathCopy==='Open the Grade page for a candidate you are considering, or compare the relevant pages if you have several candidates. Keep each candidate\'s trial results separate. If you do not know the Grade, continue with your application and the context you already have.',grades.pathCopy);check(`${width}: mobile Grade labels`,width>640||grades.mobileLabels.length===24&&grades.mobileLabels.every(x=>x.display!=='none'),grades.mobileLabels);
   const boundary=await page.locator('.module-plas-06').innerText();check(`${width}: APP-MB ownership boundary`,boundary.includes('If your primary task is making or qualifying a high-concentration colour masterbatch')&&boundary.includes('Carrier selection, concentrate formulation and masterbatch production qualification belong there.')&&await page.locator('.module-plas-06 a').getAttribute('href')==='/applications/titanium-dioxide-for-masterbatch/',boundary);
   const full=`${fullDir}/${width}-full.png`;await page.screenshot({path:full,fullPage:true});images.push(identity(full));const official=`${gate}/approval_core/APP-PLAS_GATE4_${width}_FULL_V0.1.png`;check(`${width}: independent full-page pixel identity`,identity(full).sha256===identity(official).sha256,{independent:identity(full),official:identity(official)});
   let segmentCount=0,segmentHashesExact=true;for(let y=0;y<layout.fullHeight;y+=750){segmentCount++;const h=Math.min(900,layout.fullHeight-y),p=`${segmentDir}/${width}-${String(segmentCount).padStart(2,'0')}.png`;await page.screenshot({path:p,fullPage:true,clip:{x:0,y,width,height:h}});images.push(identity(p));const officialSegment=`${gate}/diagnostic_support/segments/${width}-segment-${String(segmentCount).padStart(2,'0')}.png`;segmentHashesExact=segmentHashesExact&&identity(p).sha256===identity(officialSegment).sha256}check(`${width}: continuous segment coverage`,segmentCount===({1440:13,768:16,390:22}[width]),{fullHeight:layout.fullHeight,segments:segmentCount,lastStart:(segmentCount-1)*750});check(`${width}: independent segment pixel identity`,segmentHashesExact,{segments:segmentCount});
   const grade=page.locator('.module-plas-10');await grade.scrollIntoViewIfNeeded();const gb=await grade.boundingBox(),gh=Math.min(height,gb.height),gp=`${gradeDir}/${width}-grade-context.png`;await page.screenshot({path:gp,clip:{x:0,y:gb.y,width,height:gh}});images.push(identity(gp));const officialGrade=`${gate}/diagnostic_support/${width}-grade-path-context.png`;check(`${width}: Grade path capture and pixel identity`,identity(gp).sha256===identity(officialGrade).sha256,{actualDimensions:{width,height:gh},independent:identity(gp),official:identity(officialGrade)});
   const targets=[['masterbatch','.module-plas-06 a'],['m2377','.module-plas-10 a[href="/products/m-2377/"]'],['documents','.module-plas-11 a[href="/request-documents/"]']];
   for(const [slug,selector] of targets){const loc=page.locator(selector);await clear(page);await loc.scrollIntoViewIfNeeded();const normal=await elementState(loc);await screenshotElement(loc,`${stateDir}/${width}-${slug}-normal.png`);await loc.hover();const hover=await elementState(loc);await screenshotElement(loc,`${stateDir}/${width}-${slug}-hover.png`);const tabs=await tabTo(page,loc);await loc.evaluate(e=>e.scrollIntoView({block:'center'}));const focus=await elementState(loc);await screenshotElement(loc,`${stateDir}/${width}-${slug}-focus.png`);const ratio=contrast(focus.outline.color,'rgb(255,255,255)'),stateChanged=normal.color!==hover.color||normal.background!==hover.background;const ok=tabs!==null&&stateChanged&&focus.focusVisible&&focus.outline.style==='solid'&&focus.outline.width===3&&ratio>=3&&sameRect(normal.rect,hover.rect)&&sameRect(normal.rect,focus.rect);focusCases.push({width,slug,tabs,normal,hover,focus,contrastAgainstWhite:ratio});check(`${width}: ${slug} normal/hover/focus`,ok,focusCases.at(-1))}
   if(width<1101){await clear(page);await page.locator('.menuButton').click();const m1=await page.evaluate(()=>({open:!document.querySelector('.mobileNav').hidden,expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),active:document.activeElement?.innerText,mainInert:document.querySelector('main').inert,footerInert:document.querySelector('footer').inert}));const mp=`${chromeDir}/${width}-menu.png`;await page.screenshot({path:mp});images.push(identity(mp));const officialMenu=`${gate}/approval_core/APP-PLAS_GATE4_${width}_MENU_V0.1.png`;check(`${width}: independent Menu pixel identity`,identity(mp).sha256===identity(officialMenu).sha256,{independent:identity(mp),official:identity(officialMenu)});await page.keyboard.press('Shift+Tab');const backwards=await page.evaluate(()=>document.activeElement===document.querySelector('.menuButton'));await page.keyboard.press('Tab');await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');const forwards=await page.evaluate(()=>document.activeElement===document.querySelector('.menuButton'));await page.keyboard.press('Escape');const escaped=await page.evaluate(()=>document.activeElement===document.querySelector('.menuButton')&&document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&!document.querySelector('footer').inert);check(`${width}: Menu state and focus isolation`,m1.open&&m1.expanded==='true'&&m1.active==='Home'&&m1.mainInert&&m1.footerInert&&backwards&&forwards&&escaped,{m1,backwards,forwards,escaped})}
   await page.locator('#cookie-trigger').scrollIntoViewIfNeeded();await page.locator('#cookie-trigger').click();const c1=await page.evaluate(()=>({open:document.querySelector('.cookie-layer').open,modal:document.querySelector('.cookie-layer').matches(':modal'),active:document.activeElement?.innerText}));const cp=`${chromeDir}/${width}-cookie.png`;await page.screenshot({path:cp});images.push(identity(cp));const officialCookie=`${gate}/approval_core/APP-PLAS_GATE4_${width}_COOKIE_V0.1.png`;check(`${width}: independent Cookie pixel identity`,identity(cp).sha256===identity(officialCookie).sha256,{independent:identity(cp),official:identity(officialCookie)});await page.keyboard.press('Shift+Tab');const back=await page.evaluate(()=>document.activeElement?.innerText==='Read Cookie Policy');await page.keyboard.press('Tab');const forward=await page.evaluate(()=>document.activeElement?.innerText==='Close');await page.keyboard.press('Escape');const returned=await page.evaluate(()=>!document.querySelector('.cookie-layer').open&&document.activeElement===document.querySelector('#cookie-trigger'));check(`${width}: Cookie state, loop, Escape return`,c1.open&&c1.modal&&c1.active==='Close'&&back&&forward&&returned,{c1,back,forward,returned});
   await page.evaluate(()=>window.localNavigationIntents=[]);for(const href of ['/request-documents/','/request-sample/','/request-a-quote/'])await page.locator(`.module-plas-11 a[href="${href}"]`).click();const intents=await page.evaluate(()=>window.localNavigationIntents);requestCases.push({width,intents});check(`${width}: Documents/Sample/RFQ ownership`,JSON.stringify(intents)===JSON.stringify([{href:'/request-documents/',context:{sourcePage:'APP-PLAS'},type:'LOCAL_NAVIGATION_INTENT_ONLY'},{href:'/request-sample/',context:{application:'Plastics',gradeMode:'KNOWN_OR_UNKNOWN'},type:'LOCAL_NAVIGATION_INTENT_ONLY'},{href:'/request-a-quote/',context:{application:'Plastics',gradeMode:'KNOWN_LEAD_OR_NOT_SURE',additionalCandidates:'Additional Requirements'},type:'LOCAL_NAVIGATION_INTENT_ONLY'}]),intents);
   await context.close();
  }
  check('content and links stable across widths',signatures.every(s=>s.mainText===signatures[0].mainText&&JSON.stringify(s.links)===JSON.stringify(signatures[0].links)),signatures.map(s=>({width:s.width,textLength:s.mainText.length,links:s.links.length})));
  const c3=await browser.newContext({viewport:{width:1440,height:900}});await c3.route(/^https?:/,r=>r.abort());const p3=await c3.newPage();await p3.goto(pathToFileURL(gate3).href);await settle(p3);const g3sig=await contentSignature(p3);check('candidate main content equals frozen Gate 3 DOM',g3sig.mainText===signatures[0].mainText&&JSON.stringify(g3sig.links)===JSON.stringify(signatures[0].links),{text:g3sig.mainText===signatures[0].mainText,links:JSON.stringify(g3sig.links)===JSON.stringify(signatures[0].links)});await c3.close();
  const c720=await browser.newContext({viewport:{width:720,height:900},deviceScaleFactor:1});await c720.route(/^https?:/,r=>r.abort());const p720=await c720.newPage();await p720.goto(pathToFileURL(source).href);await settle(p720);const proxy=await p720.evaluate(()=>({clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('body *')].filter(e=>e.checkVisibility()).map(e=>e.getBoundingClientRect()).filter(r=>r.width>0&&(r.left<-.5||r.right>innerWidth+.5)).length,small:[...document.querySelectorAll('a,button')].filter(e=>e.checkVisibility()).map(e=>e.getBoundingClientRect()).filter(r=>r.width<44||r.height<44).length}));check('720px responsive proxy',proxy.clientWidth===720&&proxy.scrollWidth===720&&!proxy.overflow&&!proxy.small,proxy);await c720.close();
 }catch(e){errors.push(e.stack||String(e))}finally{if(browser)await browser.close();const failures=checks.filter(x=>x.status==='FAIL');const record={page_id:'APP-PLAS',workset_id:'APP-PLAS-G4-COMPLETE-20260907-01',freeze_id:'APP-PLAS-G4-FREEZE-20260907-01',role:'INDEPENDENT_PROJECT_CONTROL_REVIEW',generated_at:new Date().toISOString(),runtime:{node:process.version,chrome:'system Chrome',headless:true,dpr:1,httpNetwork:'blocked'},source:identity(source),checks,failures,errors,counts:{checks:checks.length,failures:failures.length,errors:errors.length,images:images.length,full:3,continuous_segments:51,grade_context:3,target_states:27,menu:2,cookie:3},images,focusCases,requestCases,status:failures.length||errors.length?'FAIL':'PASS'};fs.writeFileSync(`${review}/independent-runtime.json`,JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify({status:record.status,counts:record.counts,failures:failures.map(x=>x.name),errors,imageCount:images.length,source:record.source},null,2));if(failures.length||errors.length)process.exitCode=1}}
)();
