const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/markets/belgium',out=base+'/04_planning/gate4-v1.1',id='MARKET-EU-BE',source=out+'/'+id+'_GATE4_COMPLETE_VISUAL_V1.1.html',mode=process.argv[2]||'diagnostic',dir=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/render-r1';fs.mkdirSync(dir,{recursive:true});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim(),copy=fs.readFileSync(base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'').trim();
const canonical=norm(copy.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'$1').replace(/^#{1,3} /gm,'').replace(/^- /gm,'')),headings=[...copy.matchAll(/^#{1,3} (.+)$/gm)].map(m=>m[1]),links=[...copy.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({label:m[1],href:m[2]}));
const result={role:'EXECUTION_SELF_CHECK',mode,time:new Date().toISOString(),source:{path:source,bytes:fs.statSync(source).size,sha256:hash(source)},viewports:[],checks:[],images:[],blockedRequests:[],errors:[]};const check=(key,ok,detail)=>result.checks.push({key,status:ok?'PASS':'FAIL',detail});
const settle=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
async function screenshot(p,w,state,fullPage){await p.mouse.move(0,0);const buffer=await p.screenshot({fullPage});result.images.push({width:w,state,sha256:crypto.createHash('sha256').update(buffer).digest('hex')});}
async function targets(p,key){const a=await p.locator('a,button').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&!e.closest('[inert]')).map(e=>{const r=e.getBoundingClientRect();return {label:e.textContent.trim(),width:r.width,height:r.height}}));check(key,a.every(e=>e.width>=43.99&&e.height>=43.99),a);}
(async()=>{let browser;try{
if(mode==='formal'){const f=JSON.parse(fs.readFileSync(out+'/'+id+'_GATE4_FREEZE_RECORD_V1.1.json','utf8'));if(f.source.sha256!==hash(source)||fs.readdirSync(dir).length)throw Error('Freeze mismatch or existing formal assets');}
browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});result.browser=browser.version();
for(const width of [1440,768,390]){const height=width===390?844:900,context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1});await context.route(/^https?:/,route=>{result.blockedRequests.push(route.request().url());return route.abort()});const p=await context.newPage();p.on('pageerror',e=>result.errors.push(e.message));await p.goto(pathToFileURL(source).href);await settle(p);
const body=await p.locator('main').evaluate(e=>({text:e.innerText,headings:[...e.querySelectorAll('h1,h2,h3')].map(x=>x.textContent),links:[...e.querySelectorAll('a')].map(a=>({label:a.textContent,href:a.getAttribute('href')})),modules:[...e.querySelectorAll('[data-module]')].map(s=>s.dataset.module)}));check(width+' full B bidirectional',norm(body.text)===canonical,{expected:canonical,actual:norm(body.text)});check(width+' headings links modules',JSON.stringify(body.headings)===JSON.stringify(headings)&&JSON.stringify(body.links)===JSON.stringify(links)&&body.modules.join('|')==='BE-01|BE-02|BE-03|BE-04|BE-05',body);
const geometry=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,fullHeight:document.documentElement.scrollHeight,header:document.querySelector('header').getBoundingClientRect().height,overflow:[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left<-.5||r.right>innerWidth+.5)}).map(e=>e.tagName),hiddenClipping:[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return /hidden|clip/.test(s.overflowY)&&e.scrollHeight>e.clientHeight+1}).map(e=>e.tagName),images:[...document.images].map(i=>({src:i.src,loaded:i.complete&&i.naturalWidth>0}))}));result.viewports.push({width,height,fullHeight:geometry.fullHeight});check(width+' geometry',geometry.scrollWidth===width&&!geometry.overflow.length&&!geometry.hiddenClipping.length&&geometry.header===(width===1440?84:64)&&geometry.images.every(i=>i.loaded),geometry);await targets(p,width+' full 44px');
check(width+' Belgium object relationships',await p.evaluate(()=>{const qual=document.querySelector('[data-module="BE-02"]'),app=document.querySelector('[data-module="BE-03"]'),doc=document.querySelector('[data-module="BE-04"]'),rfq=document.querySelector('[data-module="BE-05"]');const cards=[...app.querySelectorAll('.context')];const next=app.querySelector('.contexts').nextElementSibling;return qual.querySelectorAll('p').length===2&&qual.textContent.includes('Liquid dispersions, laboratory reagents and finished coatings are separate purchasing categories.')&&cards.length===3&&cards.map(c=>c.querySelector('h3').textContent).join('|')==='Coatings|Plastics and Masterbatch|Import and Distribution'&&cards.every(c=>c.querySelectorAll('p').length===1)&&cards[2].textContent.includes('Use non-confidential technical criteria rather than customer formulations.')&&next.textContent.startsWith('Review the Grade listings in the Product Hub')&&!next.closest('.context')&&doc.textContent.split('A Certificate of Origin is available upon request.').length===2&&doc.textContent.includes('form does not assign document types to those additional Grades')&&doc.querySelector('a[href="/markets/european-union/"]')&&rfq.querySelectorAll('li').length===4&&rfq.textContent.includes('city, port or receiving point if known')&&rfq.textContent.includes('our team will review your requirements and contact you using the information provided.')&&!document.querySelector('main input,main select,main form,main details,main table')}),'category distinctions, three context objects, general Product review outside final object, document/EU ownership, four RFQ details');
check(width+' shared current and functional colors',await p.evaluate(()=>{const nav=[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')];return nav.length===2&&nav.every(e=>e.textContent==='Markets')&&!document.querySelector('footer [aria-current]')&&[...document.querySelectorAll('main a')].every(e=>getComputedStyle(e).color===(e.closest('.action')&&e.getAttribute('href')==='/request-a-quote/'?'rgb(255, 255, 255)':'rgb(0, 128, 120)'))}));
await screenshot(p,width,'FULL',true);
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();const intent=await p.evaluate(()=>window.__navigationIntents.at(-1));const href=links[i].href,expected=href==='/request-a-quote/'?{source_page_id:id,destination_country:{value:'Belgium',visible:true,editable:true}}:href==='/request-documents/'?{source_page_id:id}:null;check(width+' body action '+i,intent.href===href&&JSON.stringify(intent.context)===JSON.stringify(expected),intent);}
await p.evaluate(()=>scrollTo(0,0));if(width<1101){const toggle=p.locator('.menuButton'),nav=p.locator('.mobileNav a');await toggle.click();await settle(p);check(width+' menu enters and isolates',await p.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('.menuButton').textContent==='Close'&&['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert)&&document.body.style.overflow==='hidden'));await targets(p,width+' menu 44px');check(width+' menu Teal border',await toggle.evaluate(e=>getComputedStyle(e).borderColor==='rgb(0, 128, 120)'));await screenshot(p,width,'MENU',false);await nav.last().focus();await p.keyboard.press('Tab');check(width+' menu forward loop',await toggle.evaluate(e=>document.activeElement===e));await p.keyboard.press('Shift+Tab');check(width+' menu reverse loop',await nav.last().evaluate(e=>document.activeElement===e));await p.mouse.move(width-8,height-8);await p.mouse.wheel(0,250);await p.waitForTimeout(120);check(width+' locked scroll',await p.evaluate(()=>scrollY===0));await p.keyboard.press('Escape');await settle(p);check(width+' escape background focus restore',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert)&&document.body.style.overflow===''&&document.activeElement===document.querySelector('.menuButton')));await p.mouse.wheel(0,200);await p.waitForTimeout(120);check(width+' scroll restoration',await p.evaluate(()=>scrollY>0));await p.evaluate(()=>scrollTo(0,0));await toggle.click();await toggle.click();check(width+' Close exits',await p.locator('.mobileNav').evaluate(e=>e.hidden));
for(let i=0;i<8;i++){await toggle.click();const href=await nav.nth(i).getAttribute('href');await nav.nth(i).click();await settle(p);check(width+' navigation selection '+i,await p.evaluate(href=>document.querySelector('.mobileNav').hidden&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert)&&document.body.style.overflow===''&&window.__navigationIntents.at(-1).href===href,href));}
await toggle.click();await p.setViewportSize({width:1440,height});await settle(p);check(width+' cross desktop closure',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width,height});await settle(p);}
const trigger=p.locator('#cookie-trigger'),close=p.locator('[data-cookie-close]'),policy=p.locator('.cookie-layer a');await trigger.click();await settle(p);check(width+' Cookie entry',await close.evaluate(e=>document.activeElement===e));await targets(p,width+' Cookie 44px');check(width+' Cookie color',await p.locator('.cookie-actions > *').evaluateAll(es=>es.every(e=>getComputedStyle(e).color==='rgb(0, 128, 120)'&&getComputedStyle(e).borderColor==='rgb(0, 128, 120)')));await screenshot(p,width,'COOKIE',false);await p.keyboard.press('Shift+Tab');check(width+' Cookie reverse loop',await policy.evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(width+' Cookie forward loop',await close.evaluate(e=>e===document.activeElement));await policy.click();check(width+' Cookie policy href',await p.evaluate(()=>window.__navigationIntents.at(-1).href==='/cookie-policy/'));await close.click();await settle(p);check(width+' Cookie Close restore',await trigger.evaluate(e=>e===document.activeElement)&&await p.locator('.cookie-layer').evaluate(e=>!e.open));await trigger.click();await p.keyboard.press('Escape');await settle(p);check(width+' Cookie Escape restore',await trigger.evaluate(e=>e===document.activeElement)&&await p.locator('.cookie-layer').evaluate(e=>!e.open));await context.close();}
check('no external request/page errors',!result.blockedRequests.length&&!result.errors.length,{blocked:result.blockedRequests,errors:result.errors});
}catch(e){result.errors.push(e.stack);}finally{if(browser)await browser.close();result.failed=result.checks.filter(c=>c.status==='FAIL');result.status=result.failed.length||result.errors.length?'FAIL':'RUNTIME_PASS_PENDING_VISUAL';fs.writeFileSync(dir+'/runtime-checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify({status:result.status,failed:result.failed.map(c=>c.key),errors:result.errors,viewports:result.viewports,images:result.images.map(i=>i.path)}));if(result.status==='FAIL')process.exitCode=1;}})();

