const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const dir=__dirname,source=path.join(dir,'product-planning.html'),out=path.join(dir,'diagnostics');
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const browser=await chromium.launch({headless:true});const record={source,sha256:sha(source),type:'AUTHOR_SELF_CHECK',browser:browser.version(),viewports:[],operations:[]};
for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});await page.goto(pathToFileURL(source).href);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`diagnostic-${width}.png`),fullPage:true});
record.viewports.push(await page.evaluate(()=>{const vis=e=>{let r=e.getBoundingClientRect();return r.width>0&&r.height>0&&!e.closest('[hidden]')};const range=document.createRange();range.selectNodeContents(document.querySelector('h1'));return {width:innerWidth,height:document.documentElement.scrollHeight,overflow:document.documentElement.scrollWidth-innerWidth,h1Lines:new Set([...range.getClientRects()].map(r=>Math.round(r.y))).size,h1Font:getComputedStyle(document.querySelector('h1')).fontSize,smallTargets:[...document.querySelectorAll('a,button')].filter(vis).filter(e=>!e.classList.contains('skip')).map(e=>({text:e.innerText,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})).filter(r=>r.w<44||r.h<44),directory:[...document.querySelectorAll('.gradeRow')].map(e=>({grade:e.dataset.grade,summary:e.querySelector('p').textContent,summaryHeight:e.querySelector('p').getBoundingClientRect().height,height:e.getBoundingClientRect().height})),bodyOverflow:[...document.querySelectorAll('main *')].filter(vis).filter(e=>e.getBoundingClientRect().right>innerWidth+.1||e.getBoundingClientRect().left<-.1).map(e=>e.className),images:[...document.images].every(e=>e.complete&&e.naturalWidth>0),header:document.querySelector('header').getBoundingClientRect().height,groups:document.querySelectorAll('.group').length,faq:document.querySelectorAll('.answer').length}}));
for(const app of ['Coatings','Plastics','Masterbatch','Printing Inks','Paper','Specialty Materials','Not Sure']){await page.locator(`[data-app="${app}"]`).focus();await page.keyboard.press('Enter');record.operations.push({width,app,...await page.evaluate(()=>({heading:document.querySelector('#result-heading').textContent,grades:[...document.querySelectorAll('#results strong')].map(e=>e.textContent),focus:document.activeElement.dataset.app,pressed:document.activeElement.getAttribute('aria-pressed')}))});}
await page.locator('[data-app="Coatings"]').click();
for(const kind of ['empty','failure']){await page.evaluate(k=>window.planningState.selector(k),kind);record.operations.push({width,kind,type:'LOCAL_SIMULATION',text:await page.locator('#results').innerText()});}
await page.locator('[data-app="Coatings"]').click();
for(const count of [2,1,0]){await page.evaluate(n=>window.planningState.routes(n,n,true),count);record.operations.push({width,processCount:count,...await page.evaluate(()=>({cr:document.querySelector('.special').innerText,processHeight:document.querySelector('.processCards').getBoundingClientRect().height,supportHidden:document.querySelector('#support').hidden}))});}
await page.evaluate(()=>window.planningState.routes(2,3,true));
for(let i=0;i<5;i++){const b=page.locator('.question button').nth(i);await b.focus();await page.keyboard.press('Space');record.operations.push({width,faq:i,expanded:await b.getAttribute('aria-expanded'),focus:await b.evaluate(e=>e===document.activeElement)});}
if(width<1101){await page.locator('.menuButton').click();record.operations.push({width,menu:'opened',...await page.evaluate(()=>({focus:document.activeElement.textContent,inert:document.querySelector('main').inert,locked:document.body.style.overflow,current:document.querySelector('.mobileNav [aria-current]').textContent}))});await page.screenshot({path:path.join(out,`menu-${width}.png`)});await page.keyboard.press('Escape');record.operations.push({width,menu:'escape',...await page.evaluate(()=>({focus:document.activeElement.className,inert:document.querySelector('main').inert,locked:document.body.style.overflow,hidden:document.querySelector('.mobileNav').hidden}))});await page.locator('.menuButton').click();await page.locator('.mobileNav a').first().evaluate(e=>e.addEventListener('click',ev=>ev.preventDefault(),{once:true}));await page.locator('.mobileNav a').first().click();record.operations.push({width,menu:'link-close',...await page.evaluate(()=>({hidden:document.querySelector('.mobileNav').hidden,inert:document.querySelector('main').inert,focus:document.activeElement.className}))});}
await page.locator('#cookie-trigger').click();await page.keyboard.press('Shift+Tab');record.operations.push({width,cookie:'backward-wrap',focus:await page.evaluate(()=>document.activeElement.textContent)});await page.keyboard.press('Tab');await page.keyboard.press('Escape');record.operations.push({width,cookie:'escape-return',focus:await page.evaluate(()=>document.activeElement.id)});
await page.close();}fs.writeFileSync(path.join(out,'runtime.json'),JSON.stringify(record,null,2));console.log(JSON.stringify(record.viewports,null,2));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
