const fs=require('fs'),crypto=require('crypto'),path=require('path');
const root='D:/23MySec',page=root+'/pages/applications/paper',base=page+'/04_planning/gate3-v0.3',out=page+'/05_review';
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const result={reviewer:'/root/paper_gate3_review',generatedAt:new Date().toISOString(),scope:'APP-PAPER-G3-PCR-F01 targeted rereview',evidenceType:'SOURCE_INSPECTION',identities:[],timestamps:[],unchangedFromIndependentReview:[],manifestReferences:[],failures:[]};
function collect(o){if(!o||typeof o!=='object')return;if(o.path&&o.sha256){const s=fs.statSync(o.path),a={path:o.path,bytes:s.size,sha256:hash(o.path),match:hash(o.path)===o.sha256.toLowerCase()&&(o.bytes===undefined||s.size===o.bytes)};result.identities.push(a);if(!a.match)result.failures.push('identity:'+o.path);if(o.createdUtc||o.writtenUtc){const t={path:o.path,birthtime:s.birthtime.toISOString(),mtime:s.mtime.toISOString(),expectedCreated:o.createdUtc,expectedWritten:o.writtenUtc};t.match=(!o.createdUtc||t.birthtime===o.createdUtc)&&(!o.writtenUtc||t.mtime===o.writtenUtc);result.timestamps.push(t);if(!t.match)result.failures.push('time:'+o.path);}}Object.values(o).forEach(collect);}
const names=['APP-PAPER_GATE3_PREFLIGHT_RECORD_V0.4.json','APP-PAPER_GATE3_FREEZE_RECORD_V0.4.json','APP-PAPER_GATE3_ASSET_INVENTORY_V0.4.json','APP-PAPER_GATE3_CHRONOLOGY_CORRECTION_OBSERVATIONS_V0.4.json'];for(const n of names)collect(json(base+'/'+n));
const old=json(out+'/APP-PAPER_GATE3_INDEPENDENT_OBSERVATIONS_V0.1.json');
for(const x of [...new Map(old.identities.map(x=>[x.path,x])).values()]){const a={path:x.path,expected:x.sha256,actual:hash(x.path),expectedBytes:x.bytes,actualBytes:fs.statSync(x.path).size};a.match=a.expected===a.actual&&a.expectedBytes===a.actualBytes;result.unchangedFromIndependentReview.push(a);if(!a.match)result.failures.push('old identity changed:'+x.path);}
const pre=json(base+'/'+names[0]),freeze=json(base+'/'+names[1]),chrono=json(base+'/'+names[3]);
const events=chrono.originalEvents,t=Object.values(events).map(Date.parse);result.eventOrder=events;result.sequenceIncreasing=t.every((x,i)=>i===0||x>t[i-1]);if(!result.sequenceIncreasing)result.failures.push('event order');
result.correctedTimeBindings={preflight:pre.executedAt===fs.statSync(pre.supersedesForChronology.path).birthtime.toISOString(),freeze:freeze.frozenAt===fs.statSync(freeze.supersedesForChronology.path).birthtime.toISOString(),preflightCorrectionLater:Date.parse(pre.correctionGeneratedAt)>t.at(-1),freezeCorrectionLater:Date.parse(freeze.correctionGeneratedAt)>t.at(-1),retrospectivePreflight:pre.correctionSemantics==='RETROSPECTIVE_CORRECTION_OF_ORIGINAL_PREFLIGHT_EVENT',retrospectiveFreeze:freeze.correctionSemantics==='RETROSPECTIVE_CORRECTION_OF_ORIGINAL_FREEZE_EVENT'};
for(const [k,v]of Object.entries(result.correctedTimeBindings))if(!v)result.failures.push(k);
const known=new Map();function addDir(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())addDir(p);else known.set(hash(p),p);}}addDir(page);known.set(hash(root+'/docs/architecture/gate3-shared-consumer-v0.2/consumer-package.json'),root+'/docs/architecture/gate3-shared-consumer-v0.2/consumer-package.json');known.set(hash(root+'/99_workspace/gate3-v02-validation/shared-consumer-v0.2/shared-consumer-validation.json'),root+'/99_workspace/gate3-v02-validation/shared-consumer-v0.2/shared-consumer-validation.json');
for(const p of [page+'/APP-PAPER_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md',out+'/APP-PAPER_GATE3_F01_REVISION_RESPONSE_V0.1.md',out+'/APP-PAPER_GATE3_EXECUTION_SELF_CHECK_V0.4.md',out+'/APP-PAPER_GATE3_TO_GATE4_HANDOFF_DRAFT_V0.2.md',base+'/APP-PAPER_GATE3_DESIGN_METHOD_REPORT_V0.4.md']){const hashes=[...new Set(read(p).match(/\b[a-f0-9]{64}\b/gi)||[])];for(const h of hashes){const a={document:p,sha256:h.toLowerCase(),resolvesTo:known.get(h.toLowerCase())||null};result.manifestReferences.push(a);if(!a.resolvesTo)result.failures.push('unresolved reference:'+p+':'+h);}}
result.currentDocuments=names.map(n=>({path:base+'/'+n,bytes:fs.statSync(base+'/'+n).size,sha256:hash(base+'/'+n)}));result.currentDocuments.push({path:page+'/APP-PAPER_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md',bytes:fs.statSync(page+'/APP-PAPER_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md').size,sha256:hash(page+'/APP-PAPER_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md')});
result.pass=result.failures.length===0;fs.writeFileSync(out+'/APP-PAPER_GATE3_F01_REREVIEW_OBSERVATIONS_V0.1.json',JSON.stringify(result,null,2));console.log(JSON.stringify({identities:result.identities.length,uniqueIdentities:new Set(result.identities.map(x=>x.path)).size,timestamps:result.timestamps.length,unchanged:result.unchangedFromIndependentReview.length,referenceHashes:result.manifestReferences.length,pass:result.pass,failures:result.failures,currentDocuments:result.currentDocuments},null,2));
