const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),crypto=require('crypto');const {pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..'),project='D:/23MySec',entry='MARKET-EU-PL_GATE4_VISUAL_SAMPLES_V0.1.html',source=path.join(root,entry),g3=path.resolve(root,'../gate3-v0.1/MARKET-EU-PL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const norm=s=>s.replace(/\s+/g,' ').trim();const preflight=process.argv.includes('--preflight'),records=[],captures=[];
const freezePath=path.join(root,'approval_core/source-freeze.json');
const inputPaths=['AGENTS.md','PROJECT_CONTEXT.md','pages/markets/poland/MARKET-EU-PL_CURRENT_GATE_BASELINE_MANIFEST_V0.14.md','pages/markets/poland/05_review/MARKET-EU-PL_GATE4_USER_AUTHORIZATION_V0.1.md','pages/markets/poland/05_review/MARKET-EU-PL_GATE3_TO_GATE4_HANDOFF_V0.1.md','docs/page-briefs/MARKET-EU-PL_POLAND_BRIEF_V0.2.md','pages/markets/poland/04_planning/MARKET-EU-PL_GATE2_CONTENT_SKELETON_V0.2.md','pages/markets/poland/04_planning/MARKET-EU-PL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','pages/markets/poland/04_planning/MARKET-EU-PL_GATE2_CONTENT_CONTRACT_V0.4.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','brand/visual/TIO2_MALAYSIA_PRIMARY_CTA_ACCESSIBILITY_ADDENDUM_V1.0.md','docs/architecture/GLOBAL_HEADER_FOOTER_SPEC_V0.5.md','docs/architecture/GLOBAL_FOOTER_LEGAL_UTILITY_ADDENDUM_V1.0.md','brand/logo/production/PRODUCTION_SVG_LOGO_MANIFEST_V1.0.md','pages/legal-privacy/05_review/LEGAL_PRIVACY_CONV_DOC_POST_GATE9_CURRENT_AUTHORITY_MANIFEST_V1.3.md','pages/legal-privacy/05_review/SHARED-CONSENT_CURRENT_GATE9_BASELINE_MANIFEST_V1.1.md','skills/brand-applied-visual-design/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/core-risk-model.md','agents/gate4-execution/agent.md'];
const deps=[source,path.join(root,'visual-rules.css'),g3,path.resolve(root,'../gate3-v0.1/dependencies/shared-chrome-style.snapshot.css'),path.resolve(root,'../gate3-v0.1/dependencies/Inter-Variable.ttf'),path.resolve(root,'../gate3-v0.1/dependencies/shared-chrome-data.snapshot.json'),path.resolve(root,'../gate3-v0.1/dependencies/shared-legal-data.snapshot.json'),path.join(project,'brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg'),path.join(project,'brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg')];
const id=p=>({path:p.replaceAll('\\','/'),relativePath:path.relative(root,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:hash(p)});
const binding={freezeId:'PL-G4-V01-SOURCE-01',date:new Date().toISOString(),status:'SOURCE_FROZEN_AFTER_PREFLIGHT / DRAFT_FOR_PROJECT_CONTROL_REVIEW',entry:entry,dependencies:deps.map(id),inputs:inputPaths.map(p=>id(path.join(project,p)))};
function check(ok,name,details){records.push({type:'ACTUAL_RUNTIME',name,ok,details});if(!ok)throw Error(name)}
function lum(rgb){const v=rgb.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*v[0]+.7152*v[1]+.0722*v[2]}
const ratio=(a,b)=>{a=lum(a);b=lum(b);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
(async()=>{
 if(!preflight){const old=JSON.parse(fs.readFileSync(freezePath));for(const f of old.dependencies)check(hash(f.path)===f.sha256,'Frozen dependency '+f.relativePath);}
 const b=fs.readFileSync(path.join(project,inputPaths[7]),'utf8').replace(/<!--[\s\S]*?-->/g,'');const lines=b.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);const expected={headings:lines.filter(s=>s.startsWith('#')).map(s=>s.replace(/^#+ /,'')),paragraphs:lines.filter(s=>!s.startsWith('#')&&!s.startsWith('[')),links:[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:m[1],href:m[2]}))};
 const browser=await chromium.launch({channel:'chrome',headless:true});const network=[],pageErrors=[];const renderer=browser.version();
 for(const width of [1440,768,390]){
  const page=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1});await page.route(/^https?:/,r=>{network.push(r.request().url());r.abort()});page.on('pageerror',e=>pageErrors.push(e.message));await page.goto(pathToFileURL(source).href);await page.evaluate(()=>document.fonts.ready);
  const got=await page.evaluate(()=>({headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>e.textContent),paragraphs:[...document.querySelectorAll('main p')].map(e=>e.textContent),links:[...document.querySelectorAll('main a')].map(e=>({text:e.textContent,href:e.getAttribute('href')})),structure:document.querySelector('main').outerHTML,modules:[...document.querySelectorAll('main section')].map(e=>e.id)}));check(JSON.stringify(got.headings)===JSON.stringify(expected.headings)&&JSON.stringify(got.paragraphs)===JSON.stringify(expected.paragraphs)&&JSON.stringify(got.links)===JSON.stringify(expected.links),width+' exact B headings paragraphs links',got);
  const g3page=await browser.newPage();await g3page.goto(pathToFileURL(g3).href);const oldmain=await g3page.locator('main').evaluate(e=>e.outerHTML);await g3page.close();check(got.structure===oldmain,width+' unchanged Gate 3 main DOM');
  const geom=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,fonts:[...document.fonts].map(f=>({family:f.family,status:f.status})),fontCheck:document.fonts.check('17px Inter'),headerHeight:document.querySelector('header').getBoundingClientRect().height,logo:[...document.images].map(e=>({src:e.getAttribute('src'),loaded:e.complete&&e.naturalWidth>0,w:e.width,h:e.height})),controls:[...document.querySelectorAll('a,button')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {text:e.textContent.trim()||e.getAttribute('aria-label'),w:r.width,h:r.height,color:s.color,background:s.backgroundColor,border:s.borderColor}}),texts:[...document.querySelectorAll('main h1,main h2,main h3,main p')].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{text:e.textContent,w:r.width,h:r.height,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth,fontSize:s.fontSize,lineHeight:s.lineHeight,overflow:s.overflow,textOverflow:s.textOverflow}}),columns:getComputedStyle(document.querySelector('.application-paths')).gridTemplateColumns,sectionGrid:getComputedStyle(document.querySelector('.section-grid')).gridTemplateColumns,style:{body:getComputedStyle(document.body).color,heading:getComputedStyle(document.querySelector('h1')).color}}));check(geom.scrollWidth===width&&geom.controls.every(e=>e.w>=44&&e.h>=44)&&geom.logo.every(e=>e.loaded)&&geom.fontCheck,width+' geometry font assets',geom);
  const cdp=await page.context().newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const {root:droot}=await cdp.send('DOM.getDocument');const {nodeId}=await cdp.send('DOM.querySelector',{nodeId:droot.nodeId,selector:'main p'});records.push({type:'ACTUAL_RUNTIME',name:width+' actual paragraph font',details:await cdp.send('CSS.getPlatformFontsForNode',{nodeId})});
  const controls=['#pl-01 .body-action:first-of-type a','#pl-03 .body-action a','#pl-04 .body-action:last-child a','#pl-05 .body-action:last-child a','#cookie-trigger'];for(const selector of controls){const loc=page.locator(selector);await loc.scrollIntoViewIfNeeded();const hit=await loc.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return e===h||e.contains(h)});check(hit,width+' center hit '+selector)}
  const colour=await page.evaluate(()=>{const s=x=>getComputedStyle(document.querySelector(x));return {bodyWhite:[s('body').color,'rgb(255,255,255)'],bodySoft:[s('body').color,'rgb(245,248,251)'],heading:[s('h1').color,'rgb(245,248,251)'],primary:[s('#pl-01 .body-action a').color,s('#pl-01 .body-action a').backgroundColor],secondaryText:[s('#pl-01 .body-action+.body-action a').color,'rgb(245,248,251)'],outline:[s('#pl-03 .body-action a').borderColor,'rgb(255,255,255)'],footer:[s('.footer .copyright').color,s('.footer').backgroundColor],cookieText:[s('.cookie-layer p').color,s('.cookie-layer').backgroundColor],cookieLink:[s('.cookie-actions a').color,s('.cookie-layer').backgroundColor]}});const colours=Object.entries(colour).map(([name,[fg,bg]])=>({name,fg,bg,ratio:ratio(fg,bg),minimum:name==='outline'?3:4.5}));check(colours.every(c=>c.ratio>=c.minimum),width+' contrast',colours);
  async function shot(name,selector,options={}){let p=path.join(root,preflight?'diagnostic_support/preflight-'+width+'-'+name+'.png':'approval_core/'+width+'-'+name+'.png');let box;if(selector==='hero-with-header'){await page.evaluate(()=>scrollTo(0,0));box={x:0,y:0,width,height:Math.ceil(await page.locator('#pl-01').evaluate(e=>e.getBoundingClientRect().bottom))};await page.screenshot({path:p,clip:box})}else if(selector){await page.locator(selector).screenshot({path:p})}else{await page.screenshot({path:p})}let buf=fs.readFileSync(p);captures.push({...id(p),logicalViewport:{width,height:1000},physicalWidth:buf.readUInt32BE(16),physicalHeight:buf.readUInt32BE(20),scale:1,state:name,sourceFreeze:binding.freezeId,evidenceType:'STATIC_VISUAL'})}
  if(preflight){if(width===390){await shot('hero','hero-with-header');await shot('product-review','#pl-03');await shot('documents','#pl-04')}if(width===768)await shot('product-review','#pl-03')}
  else{await shot('hero','hero-with-header');await shot('product-review','#pl-03');await shot('documents','#pl-04');if(width===390){await shot('material','#pl-02');await shot('final-rfq','#pl-05');await shot('footer','.footer')}}
  await page.locator('#pl-01 .body-action a').first().hover();const hover=await page.locator('#pl-01 .body-action a').first().evaluate(e=>({background:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));check(ratio(hover.background,hover.color)>=4.5,width+' primary hover',hover);await page.mouse.move(0,0);
  await page.locator('#pl-01 .body-action a').first().focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');const focus=await page.locator('#pl-01 .body-action a').first().evaluate(e=>({focusVisible:e.matches(':focus-visible'),outline:getComputedStyle(e).outline,offset:getComputedStyle(e).outlineOffset}));check(focus.focusVisible,width+' actual primary focus',focus);if(!preflight&&width===1440)await shot('hero-focus','hero-with-header');
  for(const link of await page.locator('main a').all()){const expectedHref=await link.getAttribute('href');await link.click();const last=await page.evaluate(()=>planningNavigation.at(-1));check(last.href===expectedHref,width+' local href '+last.label,last)}
  if(width<1100){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').focus();await page.keyboard.press('Enter');const open=await page.evaluate(()=>({expanded:document.querySelector('.menuButton').getAttribute('aria-expanded'),first:document.activeElement.textContent,inert:document.querySelector('main').inert&&document.querySelector('footer').inert,scrollLock:document.body.style.overflow,nav:[...document.querySelectorAll('.mobileNav a')].map(e=>({text:e.textContent,href:e.getAttribute('href'),current:e.getAttribute('aria-current'),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}))}));check(open.expanded==='true'&&open.first==='Home'&&open.inert&&open.nav.every(e=>e.w>=44&&e.h>=44),width+' menu open',open);if(!preflight)await shot('menu-focus');await page.locator('.menuButton').focus();await page.keyboard.press('Shift+Tab');check(await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),width+' menu reverse cycle');await page.keyboard.press('Tab');check(await page.locator('.menuButton').evaluate(e=>e===document.activeElement),width+' menu forward cycle');await page.locator('main a').first().evaluate(e=>e.focus());check(await page.locator('.menuButton').evaluate(e=>e===document.activeElement),width+' menu background blocked');await page.keyboard.press('Escape');check(await page.locator('.menuButton').evaluate(e=>e===document.activeElement&&e.getAttribute('aria-expanded')==='false'),width+' menu Escape restore');await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();check(await page.locator('.mobileNav').isHidden()&&await page.locator('main').evaluate(e=>!e.inert),width+' menu selection closes');await page.locator('.menuButton').click();await page.setViewportSize({width:1200,height:1000});check(await page.locator('.mobileNav').isHidden()&&await page.locator('main').evaluate(e=>!e.inert),width+' breakpoint closes menu');await page.setViewportSize({width,height:1000})}
  await page.locator('#cookie-trigger').focus();await page.keyboard.press('Enter');check(await page.locator('.cookie-layer').evaluate(e=>e.open&&document.activeElement===e.querySelector('button')),width+' Cookie focus entry');if(!preflight)await shot('cookie-focus');await page.keyboard.press('Shift+Tab');check(await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement),width+' Cookie reverse cycle');await page.keyboard.press('Tab');check(await page.locator('.cookie-actions button').evaluate(e=>e===document.activeElement),width+' Cookie forward cycle');await page.locator('main a').first().evaluate(e=>e.focus());check(await page.locator('.cookie-actions button').evaluate(e=>e===document.activeElement),width+' Cookie background blocked');const cookieGeom=await page.locator('.cookie-layer').evaluate(e=>({height:e.getBoundingClientRect().height,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight,controls:[...e.querySelectorAll('a,button')].map(x=>({w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height}))}));check(cookieGeom.controls.every(e=>e.w>=44&&e.h>=44),width+' Cookie geometry',cookieGeom);await page.keyboard.press('Escape');check(await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),width+' Cookie Escape restore');await page.locator('#cookie-trigger').click();await page.locator('.cookie-actions button').click();check(await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),width+' Cookie close restore');
  await page.close();
 }
 await browser.close();check(network.length===0&&pageErrors.length===0,'No network or page errors',{network,pageErrors});
 fs.writeFileSync(path.join(root,'diagnostic_support',preflight?'preflight-observations.json':'runtime-observations.json'),JSON.stringify({renderer,node:process.version,date:new Date().toISOString(),freezeId:binding.freezeId,sourceBinding:binding.dependencies,records,captures},null,2));
 if(preflight)fs.writeFileSync(freezePath,JSON.stringify(binding,null,2));else fs.writeFileSync(path.join(root,'approval_core/export-inventory.json'),JSON.stringify({freezeId:binding.freezeId,sourceFreezeSha256:hash(freezePath),captures},null,2));
 console.log(JSON.stringify({stage:preflight?'preflight':'export',observations:records.length,captures:captures.length,sourceSha256:hash(source),cssSha256:hash(path.join(root,'visual-rules.css')),freeze:freezePath},null,2));
})().catch(e=>{fs.writeFileSync(path.join(root,'diagnostic_support','failure-'+Date.now()+'.json'),JSON.stringify({error:e.stack,records,captures},null,2));console.error(e);process.exitCode=1});
