const fs=require('fs'),crypto=require('crypto'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/documents/certificate-of-origin',src=base+'/04_planning/gate4-v0.2',old=base+'/04_planning/gate4-v0.1',out=__dirname,entry=src+'/DOC-COO_GATE4_VISUAL_SAMPLES_V0.2.html',read=p=>fs.readFileSync(p),j=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(read(p)).digest('hex');
const f=j(src+'/approval_core/source-freeze.json'),inv=j(src+'/approval_core/export-inventory.json'),oi=j(old+'/approval_core/export-inventory.json'),prev=j(base+'/05_review/gate4-project-control-v0.1/independent-review/runtime.json');
const html=read(entry).toString(),oldhtml=read(old+'/DOC-COO_GATE4_VISUAL_SAMPLES_V0.1.html').toString(),strip=s=>s.replaceAll(' class="officialSourceLink"','').replace('FAQ Rules of Origin.</a>','FAQ Rules of Origin</a>.').replaceAll('V0.2','V0.1');
const result={identity:{freeze:hash(src+'/approval_core/source-freeze.json'),export:hash(src+'/approval_core/export-inventory.json'),normalizedHTMLSame:strip(html)===oldhtml,sharedHeaderSame:html.split('<header')[1].split('</header>')[0]===oldhtml.split('<header')[1].split('</header>')[0],sharedFooterSame:html.split('<footer')[1].split('</footer>')[0]===oldhtml.split('<footer')[1].split('</footer>')[0],scriptsSame:html.split('<script>')[1]===oldhtml.split('<script>')[1],embeddedStylesSame:JSON.stringify([...html.matchAll(/<style>([\s\S]*?)<\/style>/g)])===JSON.stringify([...oldhtml.matchAll(/<style>([\s\S]*?)<\/style>/g)]),records:[...f.inputs,...f.dependencies,...inv.assets].map(x=>({path:x.path,match:hash(x.path)===x.sha256&&read(x.path).length===x.bytes})),images:inv.assets.map(x=>({name:x.relativePath,dimensionsMatch:read(x.path).readUInt32BE(16)===x.pixelWidth&&read(x.path).readUInt32BE(20)===x.pixelHeight,oldIdentical:oi.assets.find(a=>a.relativePath===x.relativePath)?.sha256===x.sha256}))},widths:[],network:[],errors:[]};
const copy=()=>{const n=t=>t.replace(/\s+/g,' ').trim(),arr=s=>[...document.querySelectorAll(s)].map(e=>n(e.textContent));return{headings:arr('main h1,main h2'),paragraphs:arr('main p'),list:arr('main li'),table:[...document.querySelectorAll('.evidenceTable tr')].map(tr=>[...tr.children].map(td=>{const c=td.cloneNode(true);c.querySelectorAll('.cellLabel').forEach(l=>l.remove());return n(c.textContent)})),links:[...document.querySelectorAll('main a')].map(e=>({text:n(e.textContent),href:e.getAttribute('href')}))}};
const geometry=()=>[...document.querySelectorAll('main section,main p,main h1,main h2,main table,main li,header,footer')].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return{tag:e.tagName,id:e.id,text:e.textContent.replace(/\s+/g,' ').trim(),x:r.x,y:r.y,w:r.width,h:r.height,font:s.font}});
const probe=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),q=r=>({x:r.x,y:r.y,w:r.width,h:r.height}),hit=(x,y)=>{const h=document.elementFromPoint(x,y);return h===e||e.contains(h)},surface=n=>{while(n&&getComputedStyle(n).backgroundColor==='rgba(0, 0, 0, 0)')n=n.parentElement;return n?getComputedStyle(n).backgroundColor:'rgb(255, 255, 255)'};
let denseFailures=0;const denseRegion={x:r.x+1,y:r.y+(r.height-44)/2,w:44,h:44};for(let x=0;x<44;x++)for(let y=0;y<44;y++)if(!hit(denseRegion.x+x+.5,denseRegion.y+y+.5))denseFailures++;
const edgeSamples=[];for(const fx of[.001,.01,.25,.5,.75,.99,.999])for(const fy of[.001,.01,.25,.5,.75,.99,.999])edgeSamples.push({fx,fy,hit:hit(r.x+fx*r.width,r.y+fy*r.height)});
const walker=document.createTreeWalker(e.parentElement,NodeFilter.SHOW_TEXT);let node;const neighborIssues=[];let checkedCharacters=0;const extra=e.matches(':focus-visible')?6:0;while(node=walker.nextNode()){if(e.contains(node))continue;for(let i=0;i<node.length;i++){if(!node.textContent[i].trim())continue;const range=document.createRange();range.setStart(node,i);range.setEnd(node,i+1);const a=range.getBoundingClientRect();checkedCharacters++;const overlaps=a.left<r.right+extra&&a.right>r.left-extra&&a.top<r.bottom+extra&&a.bottom>r.top-extra;const centerHits=hit(a.x+a.width/2,a.y+a.height/2);if(overlaps||centerHits)neighborIssues.push({char:node.textContent[i],rect:q(a),overlaps,centerHits})}}
return{text:e.textContent,href:e.getAttribute('href'),rect:q(r),rectCount:e.getClientRects().length,display:s.display,bg:surface(e),fg:s.color,outline:s.outline,outlineColor:s.outlineColor,focusSurface:surface(e.parentElement),hover:e.matches(':hover'),focus:e.matches(':focus-visible'),denseRegion,denseFailures,denseSamples:1936,edgeSamples,neighborIssues,checkedCharacters,clipped:r.left<0||r.right>innerWidth||r.top<0||r.bottom>innerHeight}};
const lum=c=>{const a=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722},ratio=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
async function ready(p,path=entry){await p.goto('file:///'+path);await p.evaluate(()=>document.fonts.ready)}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();for(const width of[1440,768,390]){const p=await browser.newPage({viewport:{width,height:width===390?844:900},deviceScaleFactor:1});p.on('pageerror',e=>result.errors.push(e.message));await p.route('**/*',r=>/^https?:/.test(r.request().url())?(result.network.push(r.request().url()),r.abort()):r.continue());await ready(p);const row={width,copy:await p.evaluate(copy),sourceStates:[],normalImages:[]};const expectation=prev.expectedCopy;row.rawCopyMatches=Object.fromEntries(Object.keys(expectation).map(k=>[k,JSON.stringify(row.copy[k])===JSON.stringify(expectation[k])]));row.punctuationOnlyLinkDifference=row.copy.links.every((l,i)=>l.href===expectation.links[i].href&&(l.text===expectation.links[i].text||(i===7&&l.text===expectation.links[i].text+'.')));const geom2=await p.evaluate(geometry);row.scrollWidth=await p.evaluate(()=>document.documentElement.scrollWidth);
for(const a of inv.assets.filter(x=>x.logicalViewport.width===width&&x.state==='normal')){await p.mouse.move(0,0);await p.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});row.normalImages.push({path:a.relativePath,match:Buffer.from(await p.screenshot({clip:a.clip,fullPage:true})).equals(read(a.path))})}
row.footerActual=await p.locator('footer').evaluate(e=>({focusedInside:e.contains(document.activeElement),hoveredControls:e.querySelectorAll('a:hover,button:hover').length,focusVisibleControls:e.querySelectorAll(':focus-visible').length}));
for(let i=0;i<2;i++){const a=p.locator('main a.officialSourceLink').nth(i);for(const state of['normal','hover','focus']){await p.mouse.move(0,0);await p.evaluate(()=>document.activeElement.blur());await a.scrollIntoViewIfNeeded();if(state==='hover')await a.hover();if(state==='focus'){await a.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab')};const data=await a.evaluate(probe);data.textContrast=ratio(data.fg,data.bg);data.focusContrast=ratio(data.outlineColor,data.focusSurface);const asset=inv.assets.find(x=>x.relativePath===`approval_core/${width}-coo-${i===0?'02':'06'}-source-${state}.png`);const shot=await p.screenshot({clip:asset.clip,fullPage:true});data.formalImageMatch=Buffer.from(shot).equals(read(asset.path));row.sourceStates.push({link:i,state,...data})}}
await ready(p);row.adjacentStates=[];for(const a of await p.locator('main .primary,main a[href="/products/"],#coo-05 a[href="/documents/"],footer .footerRfq,#cookie-trigger').all()){await a.hover();const hover=await a.evaluate(e=>({hover:e.matches(':hover'),fg:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor,text:e.textContent}));await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');row.adjacentStates.push({hover,focus:await a.evaluate(e=>({focus:e.matches(':focus-visible'),outline:getComputedStyle(e).outline}))})}
await ready(p);for(const a of await p.locator('main a,.headerRfq,footer .footerRfq').all())if(await a.isVisible())await a.click();row.navigation=await p.evaluate(()=>window.__navigationIntents);await p.locator('#cookie-trigger').focus();await p.keyboard.press('Enter');row.cookie={open:await p.locator('dialog').evaluate(e=>e.open),entry:await p.evaluate(()=>document.activeElement.textContent),backgroundBlocked:await p.locator('main a').first().evaluate(e=>{e.focus();return document.activeElement!==e})};await p.keyboard.press('Escape');row.cookie.returned=await p.locator('#cookie-trigger').evaluate(e=>document.activeElement===e);
if(width<1101){await p.locator('.menuButton').focus();await p.keyboard.press('Enter');row.menu={opened:await p.locator('.mobileNav').evaluate(e=>!e.hidden),inert:await p.locator('main').evaluate(e=>e.inert)};await p.locator('.mobileNav a[href="/documents/"]').focus();await p.keyboard.press('Shift+Tab');await p.keyboard.press('Tab');row.menu.documentsFocus=await p.locator('.mobileNav a[href="/documents/"]').evaluate(e=>e.matches(':focus-visible'));await p.keyboard.press('Escape');row.menu.returned=await p.locator('.menuButton').evaluate(e=>document.activeElement===e)}
await ready(p,old+'/DOC-COO_GATE4_VISUAL_SAMPLES_V0.1.html');const geom1=await p.evaluate(geometry);row.geometryDifference=geom2.map((x,i)=>({tag:x.tag,id:x.id,text:x.text.slice(0,70),dx:x.x-geom1[i].x,dy:x.y-geom1[i].y,dw:x.w-geom1[i].w,dh:x.h-geom1[i].h,fontSame:x.font===geom1[i].font})).filter(x=>x.dx||x.dy||x.dw||x.dh||!x.fontSame);
const nojs=await browser.newPage({viewport:{width,height:900},javaScriptEnabled:false});await nojs.route('**/*',r=>/^https?:/.test(r.request().url())?r.abort():r.continue());await ready(nojs);row.noJSCopySame=JSON.stringify(await nojs.evaluate(copy))===JSON.stringify(row.copy);await nojs.close();await p.close();result.widths.push(row);fs.writeFileSync(out+'/runtime.json',JSON.stringify(result,null,2));console.log(JSON.stringify({width,copy:row.rawCopyMatches,punctuationOnly:row.punctuationOnlyLinkDifference,normalImageFailures:row.normalImages.filter(x=>!x.match),source:row.sourceStates.map(x=>({link:x.link,state:x.state,w:x.rect.w,h:x.rect.h,denseFailures:x.denseFailures,edges:x.edgeSamples.filter(y=>!y.hit).length,neighborIssues:x.neighborIssues.length,focus:x.focus,hover:x.hover,image:x.formalImageMatch,contrast:x.textContrast})),cookie:row.cookie,menu:row.menu,noJS:row.noJSCopySame}));}await browser.close();fs.writeFileSync(out+'/runtime.json',JSON.stringify(result,null,2));console.log(JSON.stringify({identityCount:result.identity.records.length,failedIdentities:result.identity.records.filter(x=>!x.match),imageDimensionFailures:result.identity.images.filter(x=>!x.dimensionsMatch),normalizedHTMLSame:result.identity.normalizedHTMLSame,network:result.network,errors:result.errors}))})().catch(e=>{console.error(e);process.exit(1)});
