const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const root='D:/23MySec',base=root+'/pages/markets/india',out=base+'/04_planning/gate3-v0.1',id='MARKET-IN-001',neutral=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:hash(p)}),write=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2));
fs.mkdirSync(out+'/dependencies',{recursive:true});fs.mkdirSync(out+'/approval_core',{recursive:true});
const paths={manifest:base+'/'+id+'_CURRENT_GATE_BASELINE_MANIFEST_V0.6.md',A:base+'/04_planning/'+id+'_GATE2_CONTENT_SKELETON_V0.1.md',B:base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.1.md',C:base+'/04_planning/'+id+'_GATE2_CONTENT_CONTRACT_V0.2.md',brief:root+'/docs/page-briefs/MARKET-IN-001_INDIA_BRIEF_V0.2.md',review:base+'/05_review/'+id+'_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md',authorization:root+'/docs/architecture/GATE3_EIGHT_PAGE_SERIAL_CONTROL_V1.4.md',approval:root+'/docs/architecture/GATE2_EIGHT_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md',baseline:root+'/docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md',agent:root+'/agents/gate3-execution/agent.md',designSkill:root+'/skills/responsive-wireframe-design/SKILL.md',verificationSkill:root+'/skills/layout-interaction-verification/SKILL.md',handoff:root+'/docs/superpowers/specs/2026-09-07-gate3-to-gate4-handoff-contract-v0.1.md'};
paths.moduleCountCorrection=base+'/05_review/MARKET-IN-001_GATE2_MODULE_COUNT_ADMINISTRATIVE_CORRECTION_V0.1.md';
const approvedInputs=Object.fromEntries(Object.entries(paths).map(([k,p])=>[k,identity(p)]));
for(const [k,expected] of Object.entries({A:'0346fb09bbb4b90de4dc1af89c2fb6aacb0b005885fa731641a90c8e006e4ec9',B:'67b1c21fc2e209b4e40f28ccd3f7794eb9a33fcd84c3305a16438ec4de74ceb0',C:'7c9bd74686e5b6672428cf20f8d83826e4739b3927b9f393aa3464208a53e5b7'}))if(approvedInputs[k].sha256!==expected)throw Error('Approved '+k+' identity changed');
const pkg=JSON.parse(fs.readFileSync(neutral+'/consumer-package.json'));for(const f of pkg.files)if(hash(neutral+'/'+f.path)!==f.sha256)throw Error('Shared mismatch '+f.path);
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';
for(const name of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(neutral+'/'+name,out+'/dependencies/'+name);
const shared=require(neutral+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
const binding={createdAt:new Date().toISOString(),status:'DIAGNOSTIC_CANDIDATE_NOT_FROZEN',approvedInputs,sharedConsumer:{...identity(neutral+'/consumer-package.json'),version:pkg.version,packageId:pkg.packageId,currentPageId:'MARKET-000'},sharedFiles:pkg.files.map(f=>({...identity(neutral+'/'+f.path),role:f.role})),owners:Object.fromEntries(Object.entries(pkg.authority).map(([k,p])=>[k,identity(p)])),dependencies:[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(identity)};
write(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',binding);
write(out+'/'+id+'_GATE3_TASK_INPUT_CARD_V0.1.md',`# India Gate 3 task input card\n\nStatus: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Page MARKET-IN-001, EN /markets/india/, Market procurement landing page. Batch G3-8PAGE-SERIAL-01 item 5, authorization V1.4. Only India outputs; stop before independent project-control review and Gate4.\n\nExact approved input, method, owner and dependency identities: MARKET-IN-001_GATE3_INPUT_BINDING_V0.1.json. B V0.1 is the sole visible main copy. A V0.1 has IN-01–IN-05; preserve all five groups, count corrected by current Manifest V0.6 and administrative correction; original observation preserved in report.\n\nState matrix: 1440×900 / 768×900 / 390×844 at DPR1 full-page; menu at 768 and390; Cookie at all three. No page form, FAQ, selector or submitted result.\n\nFresh neutral consumer V0.2 with MARKET-000 and original approved Logo paths. RFQ locally records India visible/editable destination intention plus source attribution, without constructing query or preselecting other values. DOC attribution only. Real receiver behavior is untested.\n\nMethod output directory: ${out}. Design report: ${out}/${id}_GATE3_DESIGN_METHOD_REPORT_V0.1.md. Verification report: ${base}/05_review/${id}_GATE3_EXECUTION_SELF_CHECK_V0.1.md.\n\nRisk map: pigment versus finished masterbatch; three evaluation prompts; one Grade/multiple document types and supplementary context; product/documents before owner-only dated trade route; exact COO once; MT/destination quotation checklist and after-submit boundary.\n`);
write(out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md','# India Gate 3 design method report\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. Design in progress; no formal exports or preflight claim yet. Input card/binding define scope. Hero → material distinction → application review → product/origin/import information → RFQ preparation. Complete approved B retained.\n');
const markdown=fs.readFileSync(paths.B,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim(),blocks=markdown.split(/\r?\n\s*\r?\n/).map(s=>s.trim());
const esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>');
let html='<nav class="breadcrumb" aria-label="Breadcrumb">'+inline(blocks.shift())+'</nav>',sectionNumber=0;
for(let i=0;i<blocks.length;i++){const b=blocks[i];if(/^#{1,2} /.test(b)){if(sectionNumber)html+='</div></section>';sectionNumber++;const level=b.startsWith('# ')?1:2;html+=`<section class="module module-${sectionNumber}" data-module="IN-0${sectionNumber}"><div class="content"><h${level}>${inline(b.replace(/^#+ /,''))}</h${level}>`;}
else if(b.startsWith('### ')){html+='<div class="contexts">';while(blocks[i]?.startsWith('### ')){html+='<article><h3>'+inline(blocks[i].slice(4))+'</h3><p>'+inline(blocks[i+1])+'</p></article>';i+=2;}i--;html+='</div>';}
else if(b.startsWith('- '))html+='<ul>'+b.split(/\r?\n/).map(x=>'<li>'+inline(x.slice(2))+'</li>').join('')+'</ul>';
else if(/^\[[^\]]+\]\([^)]+\)$/.test(b)){html+='<div class="actions">';while(/^\[[^\]]+\]\([^)]+\)$/.test(blocks[i]||'')){let link=inline(blocks[i]);if(blocks[i].includes('](/request-a-quote/)'))link=link.replace('<a ','<a class="primary" ');html+=link;i++;}i--;html+='</div>';}
else html+='<p>'+inline(b)+'</p>';}
html+='</div></section>';
const css=`*{box-sizing:border-box}body{margin:0;background:white;font-family:Inter,Arial,sans-serif;color:#334155}main{font-size:17px;line-height:1.7}main .breadcrumb{max-width:1120px;margin:auto;padding:22px 0;color:#516174;font-size:14px}main a{color:#008078;min-width:44px;min-height:44px;display:inline-flex;align-items:center;text-underline-offset:4px}main a:focus-visible{outline:3px solid #008078;outline-offset:3px}main .module{padding:56px max(32px,calc((100% - 1120px)/2));border-top:1px solid #d9e2ec}main .module-1{background:#f3f7fa;padding-top:40px;padding-bottom:52px}main .content{max-width:100%}main h1,main h2,main h3{color:#062b5b;margin:0 0 22px;line-height:1.2}main h1{font-size:48px;max-width:900px;letter-spacing:-.025em}main h2{font-size:32px;max-width:900px}main h3{font-size:22px;margin-bottom:16px}main p{max-width:880px;margin:0 0 22px}main .module-1 p{font-size:20px;max-width:900px}main .actions{display:flex;gap:16px;flex-wrap:wrap;margin:26px 0 8px}main .actions a{border:1px solid #008078;border-radius:6px;padding:12px 20px;font-size:16px;font-weight:600;text-decoration:none;justify-content:center;line-height:1.5}main .actions .primary{background:#008078;color:#fff}main .contexts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px;margin:30px 0}main .contexts article{border-top:2px solid #cbd5e1;padding-top:24px}main .contexts p{margin:0}main ul{max-width:880px;padding-left:24px;margin:24px 0}main li{padding-left:8px;margin:12px 0}main .module-5{background:#f3f7fa}@media(max-width:1100px){main .breadcrumb{padding:18px 32px}main h1{font-size:40px}main .contexts{grid-template-columns:1fr;gap:24px}main .contexts article{display:grid;grid-template-columns:175px minmax(0,1fr);gap:24px}main .module{padding:44px 32px}}@media(max-width:560px){main{font-size:16px;line-height:1.7}main .breadcrumb{padding:16px 20px}main .module{padding:36px 20px}main h1{font-size:34px}main h2{font-size:28px}main h3{font-size:22px}main .module-1 p{font-size:18px}main .contexts article{display:block}main .actions{gap:12px}main .actions a{width:100%}}`;
const behavior=`window.localNavigation=[];document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;e.preventDefault();const href=a.getAttribute('href');let context={};if(href==='/request-a-quote/')context={source_page_id:'MARKET-IN-001',destination_country:'India',destination_context_visible_editable:true};if(href==='/request-documents/')context={source_page_id:'MARKET-IN-001'};window.localNavigation.push({href,context,evidence:'LOCAL_SIMULATION'});});`;
const source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';write(source,'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Titanium Dioxide Supplier India | TiO2 Malaysia</title><style>'+shared.style+'\n'+css+'</style></head><body>'+shared.header+'<main>'+html+'</main>'+shared.footer+shared.dialog+'<script>'+shared.behavior+'\n'+behavior+'</script></body></html>');
write(out+'/diagnostic_support/build-result.json',{source:identity(source),binding:identity(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json'),createdAt:new Date().toISOString()});console.log(JSON.stringify(identity(source)));
