const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/markets/india/04_planning/gate3-v0.1',id='MARKET-IN-001',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',formal=process.argv.includes('--formal'),dest=formal?out+'/approval_core':out+'/diagnostic_support/render';fs.mkdirSync(dest,{recursive:true});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim(),log=[],assets=[];const test=(name,value,data)=>{log.push({name,status:value?'PASS':'FAIL',data});if(!value)throw Error(name)};
const b=fs.readFileSync(out+'/../'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.1.md','utf8').replace(/<!--[\s\S]*?-->/g,'').trim(),expected=norm(b.replace(/^#{1,3} /gm,'').replace(/^- /gm,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1'));
const expectedLinks=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:m[1],href:m[2]}));
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
const save=async(p,w,h,state,full=false)=>{const filename=formal?`${id}_GATE3_${w}_${state.toUpperCase()}_V0.1.png`:`diagnostic-${w}-${state}.png`,file=dest+'/'+filename;await p.screenshot({path:file,fullPage:full});const buf=fs.readFileSync(file);assets.push({path:file,bytes:buf.length,sha256:hash(file),logicalViewport:{width:w,height:h},physicalPixels:{width:buf.readUInt32BE(16),height:buf.readUInt32BE(20)},dpr:1,state,role:formal?'approval_core':'diagnostic_support'});};
(async()=>{if(formal){const f=JSON.parse(fs.readFileSync(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json'));test('freeze source identity',hash(source)===f.source.sha256);}
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});const blocked=[];
try{for(const w of [1440,768,390]){const h=w===390?844:900,c=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await c.route(/^https?:/,r=>{blocked.push(r.request().url());r.abort()});const p=await c.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
test(w+' exact B bidirectional',norm(await p.locator('main').innerText())===expected);
test(w+' ordered links',JSON.stringify(await p.locator('main a').evaluateAll(as=>as.map(a=>({text:a.textContent,href:a.getAttribute('href')}))))===JSON.stringify(expectedLinks));
const geometry=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('a,button')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent.trim(),width:r.width,height:r.height}}),clipped:[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return ['hidden','clip'].includes(s.overflow)||s.textOverflow==='ellipsis'}).map(e=>e.tagName)}));
test(w+' geometry and 44px',geometry.scroll<=w&&geometry.targets.every(t=>t.width>=43.99&&t.height>=43.99)&&geometry.clipped.length===0,geometry);
test(w+' five modules and context relationships',await p.evaluate(()=>document.querySelectorAll('main section.module').length===5&&document.querySelectorAll('.module-3 article').length===3&&[...document.querySelectorAll('.contexts article')].every(a=>a.querySelectorAll('p').length===1)&&document.querySelector('.module-4').innerText.includes('A Certificate of Origin is available upon request.')&&document.querySelector('.module-5 li').textContent.includes('masterbatch production')));
test(w+' no invented controls',await p.locator('main form,main button,main select,main input,main details,main table').count()===0);
test(w+' shared current and functional colors',await p.evaluate(()=>[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].every(e=>e.textContent==='Markets')&&getComputedStyle(document.querySelector('main .primary')).backgroundColor==='rgb(0, 128, 120)'&&getComputedStyle(document.querySelector('main a')).color==='rgb(0, 128, 120)'));
await save(p,w,h,'full',true);
if(!formal){for(let y=0,n=1;y<geometry.height;y+=750,n++)await p.screenshot({path:dest+`/clip-${w}-${String(n).padStart(2,'0')}.png`,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,geometry.height-y)}});}
for(let i=0;i<expectedLinks.length;i++){await p.locator('main a').nth(i).click();const got=await p.evaluate(()=>window.localNavigation.at(-1)),href=expectedLinks[i].href;test(w+' main link '+i,got.href===href&&!href.includes('?')&&(href!=='/request-a-quote/'||(got.context.destination_country==='India'&&got.context.destination_context_visible_editable===true))&&(href!=='/request-documents/'||Object.keys(got.context).join()==='source_page_id'),got);}
await p.evaluate(()=>scrollTo(0,0));
if(w<1101){const toggle=p.locator('.menuButton');await toggle.click();test(w+' menu first focus',await p.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')));await save(p,w,h,'menu');
test(w+' background inert',await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert)&&document.body.style.overflow==='hidden'));
await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');test(w+' menu Tab loop',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');test(w+' menu reverse loop',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));
await p.mouse.move(w-5,h-10);await p.mouse.wheel(0,400);await p.waitForTimeout(100);test(w+' menu wheel lock',await p.evaluate(()=>scrollY===0));await p.keyboard.press('Escape');await ready(p);test(w+' Escape restore',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''&&document.activeElement===document.querySelector('.menuButton')));await p.mouse.wheel(0,300);await p.waitForTimeout(100);test(w+' wheel restored',await p.evaluate(()=>scrollY>0));await p.evaluate(()=>scrollTo(0,0));
await toggle.click();await toggle.click();test(w+' Close exit',await p.locator('.mobileNav').evaluate(e=>e.hidden));
for(let i=0;i<8;i++){await toggle.click();await p.locator('.mobileNav a').nth(i).click();test(w+' menu selection '+i,await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert)&&document.body.style.overflow===''));}
await toggle.click();await p.setViewportSize({width:1440,height:h});await ready(p);test(w+' desktop breakpoint closes',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width:w,height:h});await ready(p);}
await p.locator('#cookie-trigger').click();await ready(p);test(w+' Cookie focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await save(p,w,h,'cookie');
test(w+' Cookie target and color',await p.locator('.cookie-layer a').evaluate(e=>e.getAttribute('href')==='/cookie-policy/'&&getComputedStyle(e).color==='rgb(0, 128, 120)'&&e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44));
await p.keyboard.press('Shift+Tab');test(w+' Cookie reverse loop',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');test(w+' Cookie Tab loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('.cookie-layer a').click();test(w+' Cookie policy local target',(await p.evaluate(()=>window.localNavigation.at(-1))).href==='/cookie-policy/');await p.locator('[data-cookie-close]').click();await ready(p);test(w+' Cookie Close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');await ready(p);test(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));
await c.close();}
test('no external request',blocked.length===0,blocked);
fs.writeFileSync(dest+'/runtime.json',JSON.stringify({status:'PASS',source:{path:source,bytes:fs.statSync(source).size,sha256:hash(source)},browser:browser.version(),viewports:[1440,768,390],log,assets,blocked,generatedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({status:'PASS',assets:assets.length,source:hash(source)}));
}catch(e){fs.writeFileSync(dest+'/failure-'+Date.now()+'.json',JSON.stringify({status:'FAIL',message:e.stack,log},null,2));throw e}finally{await browser.close()}})();
