const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/applications/04_planning/gate3-v1.0',results=[],add=(id,pass,data)=>results.push({id,pass,data});
const expected=fs.readFileSync(root+'/pages/products/01_research/PRODUCT_GRADE_APPLICATION_PROCESS_MATRIX_V0.3.csv','utf8').split(/\r?\n/).slice(1).map(s=>s.split(',')).filter(a=>a[3]==='VERIFIED_FOR_PUBLIC_MAPPING').map(a=>a[2]+'|'+a[1]).sort();
const registry=Object.fromEntries(fs.readFileSync(root+'/docs/architecture/PAGE_REGISTRY_V0.2.md','utf8').split(/\r?\n/).filter(s=>s.startsWith('| ')).map(s=>s.split('|').map(s=>s.trim().replace(/`/g,''))).filter(a=>a[1]).map(a=>[a[1],a[3]]));
async function load(p,file='index'){await p.goto(pathToFileURL(base+'/'+file+'.html').href);await p.evaluate(()=>document.fonts.ready)}
(async()=>{const b=await chromium.launch({headless:true});try{
for(const w of [768,390]){const c=await b.newContext({viewport:{width:w,height:900}}),p=await c.newPage();await load(p);const errors=[];p.on('pageerror',e=>errors.push(e.message));
if(w===390){let req=0;p.on('request',()=>req++);for(const a of await p.locator('.app-local-nav a').all()){await a.focus();await p.keyboard.press('Enter');const target=await a.getAttribute('href');const data=await p.locator(target).evaluate(e=>({top:e.getBoundingClientRect().top,heading:e.querySelector('h3').textContent,open:e.querySelector('details').open}));add('closed-anchor-'+target,data.top>=0&&data.top<100&&!data.open,data)}
await p.locator('summary').first().focus();const style=await p.locator('summary').first().evaluate(e=>({outlineStyle:getComputedStyle(e).outlineStyle,outlineWidth:getComputedStyle(e).outlineWidth,outlineColor:getComputedStyle(e).outlineColor,name:e.getAttribute('aria-labelledby')}));await p.locator('summary').first().press('Enter');await p.screenshot({path:__dirname+'/390-disclosure-focus.png'});add('focus-visible',style.outlineStyle==='solid'&&style.outlineWidth==='3px'&&style.outlineColor==='rgb(0, 128, 120)',style);add('disclosure-does-not-fetch',req===0,{newRequests:req});}
await load(p);await p.locator('.menuButton').click();await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');const wrap=await p.evaluate(()=>document.activeElement.textContent);await p.keyboard.press('Shift+Tab');const reverse=await p.evaluate(()=>document.activeElement.textContent);await p.locator('.logoLink').evaluate(e=>e.focus());const focusAfterAttempt=await p.evaluate(()=>document.activeElement.textContent);add('menu-terminal-loop-'+w,wrap==='Close'&&reverse==='Request a Quote'&&focusAfterAttempt==='Request a Quote',{wrap,reverse,focusAfterAttempt});await p.keyboard.press('Escape');
await p.locator('#cookie-trigger').click();await p.locator('main .app-primary').evaluate(e=>e.focus());const dialogFocus=await p.evaluate(()=>document.activeElement.textContent);add('cookie-background-isolation-'+w,dialogFocus==='Close',{dialogFocus});if(w===390)await p.screenshot({path:__dirname+'/390-cookie-open.png'});await p.keyboard.press('Escape');
add('page-errors-'+w,errors.length===0,{errors});await c.close();}
const c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage();
for(const file of ['index','constrained','mixed','grades-only','apps-only']){await load(p,file);const data=await p.evaluate(()=>({pairs:[...document.querySelectorAll('.app-collection')].flatMap(g=>[...g.querySelectorAll('li')].map(l=>g.querySelector('h3').textContent+'|'+l.textContent)).sort(),routes:[...document.querySelectorAll('main [data-owner]')].map(a=>({owner:a.dataset.owner,href:a.getAttribute('href')})),intro:document.querySelector('.app-intro').textContent,schema:JSON.parse(document.querySelector('script[type="application/ld+json"]').textContent),ctaNames:[...document.querySelectorAll('.app-collection-action a')].map(a=>a.textContent.replace('Explore ','')),forms:document.querySelectorAll('form,input,select,textarea').length,footerCurrent:document.querySelectorAll('footer [aria-current]').length,body:document.body.innerText}));
add('matrix-'+file,JSON.stringify(data.pairs)===JSON.stringify(expected),{actual:data.pairs,expected});add('routes-'+file,data.routes.every(a=>registry[a.owner]===a.href&&!/[?#]/.test(a.href)),data.routes);
const graph=data.schema['@graph'],list=graph.find(x=>x['@type']==='ItemList');add('schema-parity-'+file,(list?list.numberOfItems:0)===data.ctaNames.length&&(!list||list.itemListElement.every((x,i)=>x.name===data.ctaNames[i]&&x.position===i+1))&&graph.every(n=>['CollectionPage','BreadcrumbList','ItemList'].includes(n['@type'])),data.schema);
const definition='Grades to Review are starting points for technical evaluation, not rankings or guarantees of suitability.';const endings={index:' Open a grade page for product information, or explore an application for guidance on what to evaluate.',mixed:' Open a grade page for product information, or explore an application for guidance on what to evaluate.',constrained:'','grades-only':' Open a grade page for product information.','apps-only':' Explore an application for guidance on what to evaluate.'};add('conditional-copy-'+file,data.intro===definition+endings[file]&&data.forms===0&&data.footerCurrent===0&&!/Coming soon|CURRENT|APP-000|source_page_id|PROVISIONAL/.test(data.body),{intro:data.intro,forms:data.forms,footerCurrent:data.footerCurrent});}
await load(p);await p.evaluate(()=>{window.__reviewClicks=[];document.addEventListener('click',e=>{let a=e.target.closest('.app-rfq');if(a){e.preventDefault();window.__reviewClicks.push({href:a.getAttribute('href'),owner:a.dataset.owner,query:location.search,hash:location.hash})}},true)});for(const a of await p.locator('.app-rfq').all())await a.click();const rfq=await p.evaluate(()=>window.__reviewClicks);add('rfq-source-only-local-navigation',rfq.length===2&&rfq.every(x=>x.href==='/request-a-quote/'&&x.owner==='CONV-RFQ'&&!x.query),{clicks:rfq,type:'LOCAL_SIMULATION',transport:'source_page_id=APP-000 remains receiver/Gate8 transport; no submission'});await c.close();
}finally{await b.close();const original=JSON.parse(fs.readFileSync(__dirname+'/observations.json'));add('final-identities-unchanged',original.identity.every(o=>crypto.createHash('sha256').update(fs.readFileSync(o.path)).digest('hex')===o.sha256),{count:original.identity.length});fs.writeFileSync(__dirname+'/final-observations.json',JSON.stringify({reviewer:'/root/app000_gate3_review',createdAt:new Date().toISOString(),results},null,2));console.log(JSON.stringify({checks:results.length,failed:results.filter(r=>!r.pass)}));}})().catch(e=>{console.error(e);process.exitCode=1});
