// Diagnostic corrections are confined to this reviewer evidence; original observations remain intact.
const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/applications/04_planning/gate3-v1.0',results=[];
const add=(id,pass,data)=>results.push({id,pass,data});
const norm=s=>s.replace(/\s+/g,' ').trim();
const B=fs.readFileSync(base+'/../APP-000_GATE2_FULL_BUYER_CLEAN_COPY_V1.0.md','utf8').replace(/\r/g,'');
const expected=norm(B.slice(B.indexOf('Home › Applications'),B.indexOf('\n---\n')).replace(/<a[^>]*><\/a>/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/^#{1,3} /gm,'').replace(/\*\*/g,'').replace(/^(?:-|\d+\.) +/gm,'').replace(/ · /g,' '));
async function load(p,s='index'){await p.goto(pathToFileURL(base+'/'+s+'.html').href);await p.evaluate(()=>document.fonts.ready)}
async function expand(p){for(const d of await p.locator('details').all())if(!await d.evaluate(e=>e.open))await d.locator('summary').click();}
function measure(){const vis=e=>e.checkVisibility({checkVisibilityCSS:true})&&(!e.closest('details:not([open])')||e.closest('summary'));return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,overflow:[...document.querySelectorAll('main *')].filter(vis).filter(e=>{let r=e.getBoundingClientRect();return r.left<0||r.right>innerWidth+.5}).map(e=>({tag:e.tagName,text:e.textContent.slice(0,80),w:e.getBoundingClientRect().width})),allOpen:[...document.querySelectorAll('details')].every(d=>d.open),total:document.querySelectorAll('.app-grades li').length};}
(async()=>{const browser=await chromium.launch({headless:true});try{
for(const w of [1440,768,390]){const c=await browser.newContext({viewport:{width:w,height:900}}),p=await c.newPage();await load(p);await expand(p);const actual=norm(await p.locator('main').innerText());add('full-copy-'+w,actual===expected,{expected,actual,correction:'Strip Markdown ordered-list markers; DOM list retains ordered semantics.'});
await p.locator('#cookie-trigger').click();await p.keyboard.press('Shift+Tab');const back=await p.evaluate(()=>document.activeElement.textContent);await p.keyboard.press('Tab');const forward=await p.evaluate(()=>document.activeElement.textContent);add('cookie-loop-'+w,back==='Read Cookie Policy'&&forward==='Close',{back,forward,correction:'Expected policy control label is Read Cookie Policy in shared-consent-data.json.'});await p.keyboard.press('Escape');
await load(p,'mixed');add('mixed-links-'+w,await p.locator('.app-grade-link').count()===10,{count:await p.locator('.app-grade-link').count(),expected:10,correction:'M-350 in four groups + M-2377 in five + CR-901 = 10 linked relationships.'});
if(w===390){for(const s of ['index','mixed']){await load(p,s);await expand(p);await p.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});const index=JSON.parse(fs.readFileSync(base+'/evidence-index.json','utf8'));const asset=index.assets.find(a=>a.scenario===(s==='index'?'full':'mixed')&&a.state==='expanded');const buf=await p.screenshot({fullPage:true});const actual=crypto.createHash('sha256').update(buf).digest('hex');add('expanded-png-'+s,actual===asset.sha256,{actual,expected:asset.sha256,correction:'Match author pointer-open state rather than keyboard focus-visible state.'});}}
await load(p);await expand(p);await p.evaluate(()=>{const sizes=[...document.querySelectorAll('main,main *')].map(e=>[e,parseFloat(getComputedStyle(e).fontSize)]);for(const [e,size]of sizes)e.style.fontSize=size*2+'px'});const m=await p.evaluate(measure);add('text-200-'+w,m.scrollWidth===w&&!m.overflow.length,m);await c.close();}
for(const w of [1440,768,390]){const c=await browser.newContext({viewport:{width:w,height:900},javaScriptEnabled:false}),p=await c.newPage();await load(p);const m=await p.evaluate(measure);add('no-js-'+w,m.allOpen&&m.total===30&&m.scrollWidth===w&&!m.overflow.length,m);await p.locator('summary').first().press('Enter');add('no-js-native-toggle-'+w,await p.locator('details').first().evaluate(e=>!e.open),{});await c.close();}
const c=await browser.newContext({viewport:{width:390,height:900}}),p=await c.newPage();await load(p);const cdp=await c.newCDPSession(p);let ax=await cdp.send('Accessibility.getFullAXTree');const before=ax.nodes.filter(n=>n.role?.value==='DisclosureTriangle');await p.locator('summary').first().press('Enter');ax=await cdp.send('Accessibility.getFullAXTree');const after=ax.nodes.filter(n=>n.role?.value==='DisclosureTriangle');add('native-disclosure-accessibility',before.length===6&&after.length===6,{before,after});await p.setViewportSize({width:720,height:450});await expand(p);const reflow=await p.evaluate(measure);add('720-reflow',reflow.scrollWidth===720&&!reflow.overflow.length,reflow);await c.close();
}finally{await browser.close();fs.writeFileSync(__dirname+'/targeted-observations.json',JSON.stringify({reviewer:'/root/app000_gate3_review',createdAt:new Date().toISOString(),results},null,2));console.log(JSON.stringify({checks:results.length,failed:results.filter(r=>!r.pass)}));}})().catch(e=>{console.error(e);process.exitCode=1});
