const fs=require('fs'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/resources/india-trade/04_planning/gate4-v0.1',outdir=__dirname;
const src=base+'/RES-TRADE-IN_GATE4_COMPLETE_VISUAL_V0.1.html';
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const identity=p=>{let b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}};
const result={dispatch_id:'G5-9PAGE-REVIEW-20260907-01/RES-TRADE-IN/INITIAL',reviewer:'/root/g5_trade_in',author:'/root/gate4_india_trade_execute',mode:'INDEPENDENT_REVIEW',scope:'INITIAL',started:new Date().toISOString(),source:identity(src),identities:[],errors:[],externalRequests:[],widths:[],checks:[]};
const check=(name,pass,detail)=>result.checks.push({name,pass,detail});
function scan(v,group){if(!v||typeof v!=='object')return;if(v.path&&v.sha256){let actual=identity(v.path);result.identities.push({group,...actual,expected_sha256:v.sha256,expected_bytes:v.bytes,match:actual.sha256.toLowerCase()===v.sha256.toLowerCase()&&(v.bytes===undefined||v.bytes===actual.bytes)});}for(const x of Object.values(v))if(typeof x==='object')scan(x,group);}
for(const f of ['input-index.json','evidence-index.json','freeze-record.json'])scan(read(base+'/'+f),f);
result.bindings=['input-index.json','evidence-index.json','freeze-record.json','formal-render.json'].map(f=>identity(base+'/'+f));
result.methods=['agents/gate5-independent-visual-review/agent.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/independent-visual-review.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.9.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','docs/architecture/GATE5_GATE6_ACCEPTANCE_CONTRACT_V1.0.md'].map(f=>identity('D:/23MySec/'+f));
result.images=read(base+'/evidence-index.json').approval_core.filter(v=>v.path.endsWith('.png')).map(v=>{let b=fs.readFileSync(v.path);return {...identity(v.path),width:b.readUInt32BE(16),height:b.readUInt32BE(20),state:v.state,dpr_record:v.dpr,match:b.readUInt32BE(16)===v.physical_width&&b.readUInt32BE(20)===v.physical_height}});
const html=fs.readFileSync(src,'utf8'),g3=fs.readFileSync('D:/23MySec/pages/resources/india-trade/04_planning/gate3-v0.1/RES-TRADE-IN_GATE3_WIREFRAME_V0.1.html','utf8');
check('Approved Gate3 body markup unchanged',html.split('<body>')[1]===g3.split('<body>')[1]);
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});result.browser=browser.version();
for(const width of [1440,768,390,720]){
 const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:1});await context.route('**/*',route=>{if(route.request().url().startsWith('file:'))return route.continue();result.externalRequests.push(route.request().url());return route.abort()});
 const page=await context.newPage();page.on('pageerror',e=>result.errors.push(e.message));await page.goto('file:///'+src);await page.evaluate(()=>document.fonts.ready);
 const row={width,evidence_type:'ACTUAL_RUNTIME',geometry:await page.evaluate(()=>{
 const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden', rect=e=>{let r=e.getBoundingClientRect();return {x:r.x,y:r.y+scrollY,width:r.width,height:r.height}};
 return {dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,headerHeight:document.querySelector('header').offsetHeight,font:document.fonts.check('18px Inter'),images:[...document.images].map(e=>({src:e.src,loaded:e.complete&&e.naturalWidth>0})),headings:[...document.querySelectorAll('main h1,main h2,main h3')].map(e=>e.textContent),modules:[...document.querySelectorAll('main section')].map(e=>({name:e.querySelector('h1,h2').textContent,rect:rect(e)})),tables:[...document.querySelectorAll('main table')].map(t=>({display:getComputedStyle(t).display,rows:[...t.querySelectorAll('tbody tr')].map(r=>[...r.children].map(e=>({text:e.textContent,label:e.dataset.label,header:document.getElementById(e.getAttribute('headers')).textContent,rect:rect(e)})))})),controls:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({text:e.textContent,href:e.getAttribute('href'),rect:rect(e)})),overflow:[...document.querySelectorAll('body *')].filter(visible).filter(e=>{let r=e.getBoundingClientRect();return r.left< -1||r.right>innerWidth+1}).map(e=>({tag:e.tagName,class:e.className,rect:rect(e)})),clipped:[...document.querySelectorAll('main p,main li,main td,main h1,main h2')].filter(e=>e.scrollHeight>e.clientHeight+2||e.scrollWidth>e.clientWidth+2).map(e=>({text:e.textContent,rect:rect(e)})),blocks:[...document.querySelectorAll('main h1,main h2,main h3,main p,main li,main th,main td')].map(e=>e.textContent.trim()),mainLinks:[...document.querySelectorAll('main a')].map(e=>({text:e.textContent,href:e.getAttribute('href')}))};})};
 check(width+' geometry',row.geometry.scrollWidth===width&&!row.geometry.overflow.length&&!row.geometry.clipped.length);
 check(width+' all controls >=44x44',row.geometry.controls.every(c=>c.rect.width>=44&&c.rect.height>=44));
 check(width+' table label relationships',row.geometry.tables.every(t=>t.rows.every(r=>r.every(c=>c.label===c.header))));
 row.actions=[];const active=()=>page.evaluate(()=>({text:document.activeElement.textContent.trim(),class:document.activeElement.className,id:document.activeElement.id,outline:getComputedStyle(document.activeElement).outline}));
 const log=async name=>row.actions.push({name,active:await active(),menu:await page.locator('.mobileNav').isVisible(),cookie:await page.locator('dialog').isVisible(),background:await page.evaluate(()=>({main:document.querySelector('main').inert,footer:document.querySelector('footer').inert,logo:document.querySelector('.logoLink').inert,rfq:document.querySelector('.headerRfq').inert,overflow:document.body.style.overflow}))});
 await page.keyboard.press('Tab');await log('first keyboard target');
 const primary=page.locator('.module-1 p:nth-of-type(3) a');await primary.hover();row.hover=await primary.evaluate(e=>({color:getComputedStyle(e).color,background:getComputedStyle(e).backgroundColor}));await primary.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await log('primary keyboard focus');
 if(width<1101){await page.locator('.menuButton').click();await log('menu enter');check(width+' menu entry',(await active()).text==='Home');await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');await log('menu forward wrap');check(width+' menu forward wrap',(await active()).class==='menuButton');await page.keyboard.press('Shift+Tab');await log('menu reverse wrap');check(width+' menu reverse wrap',(await active()).text==='Request a Quote');await page.evaluate(()=>document.querySelector('main a').focus());await log('menu background focus rejected');check(width+' background focus rejected',(await active()).text==='Request a Quote');await page.keyboard.press('Escape');await log('menu escape');check(width+' menu escape',await page.locator('.mobileNav').isHidden()&&(await active()).class==='menuButton');
 for(let i=0;i<8;i++){await page.locator('.menuButton').click();await page.locator('.mobileNav a').nth(i).click();check(width+' menu instance '+i,await page.locator('.mobileNav').isHidden());}await log('all eight menu instances selected');await page.locator('.menuButton').click();await page.locator('.menuButton').click();await log('menu close button');await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(80);await log('menu wide breakpoint');check(width+' wide breakpoint clears inert',await page.locator('.mobileNav').isHidden()&&!(await page.locator('main').evaluate(e=>e.inert)));await page.setViewportSize({width,height:900});}
 await page.locator('#cookie-trigger').focus();await page.keyboard.press('Enter');await log('cookie keyboard enter');check(width+' cookie entry',(await active()).text==='Close');await page.keyboard.press('Shift+Tab');await log('cookie reverse wrap');check(width+' cookie reverse wrap',(await active()).text==='Read Cookie Policy');await page.keyboard.press('Tab');await log('cookie forward wrap');check(width+' cookie forward wrap',(await active()).text==='Close');await page.evaluate(()=>document.querySelector('main a').focus());check(width+' modal background focus rejected',(await active()).text==='Close');await page.keyboard.press('Escape');await log('cookie escape');check(width+' cookie escape',await page.locator('dialog').isHidden()&&(await active()).id==='cookie-trigger');await page.locator('#cookie-trigger').click();await page.locator('dialog a').click();await log('cookie policy local intent');await page.locator('[data-cookie-close]').click();await log('cookie close button');check(width+' cookie close',await page.locator('dialog').isHidden()&&(await active()).id==='cookie-trigger');
 for(const a of await page.locator('main a').all())await a.click();row.intents=await page.evaluate(()=>window.localNavigationIntents);row.linksEvidenceType='LOCAL_SIMULATION';
 await page.emulateMedia({reducedMotion:'reduce'});row.reducedMotion=await page.evaluate(()=>({matches:matchMedia('(prefers-reduced-motion: reduce)').matches,animation:getComputedStyle(document.querySelector('main')).animationName}));
 result.widths.push(row);await context.close();}
 check('all width content identical',result.widths.every(w=>JSON.stringify(w.geometry.blocks)===JSON.stringify(result.widths[0].geometry.blocks)));
 check('runtime no script errors',result.errors.length===0);check('no external requests',result.externalRequests.length===0);
 result.source_after=identity(src);check('source unchanged',result.source.sha256===result.source_after.sha256);
 result.finished=new Date().toISOString();fs.writeFileSync(outdir+'/observations.json',JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify({failures:result.checks.filter(c=>!c.pass),identityMismatches:result.identities.filter(i=>!i.match),widths:result.widths.map(w=>({width:w.width,height:w.geometry.height,blocks:w.geometry.blocks.length,small:w.geometry.controls.filter(c=>c.rect.width<44||c.rect.height<44),clipped:w.geometry.clipped})),images:result.images.map(i=>({width:i.width,height:i.height,match:i.match}))},null,2));})().catch(e=>{fs.writeFileSync(outdir+'/failed-observations.json',JSON.stringify({...result,failure:String(e)},null,2));console.error(e);process.exit(1)});
