const fs=require('fs'),crypto=require('crypto');const deps='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';const {chromium}=require(deps+'playwright');
const root='D:/23MySec',base=root+'/pages/resources/india-trade/04_planning/gate4-v0.1',src=base+'/RES-TRADE-IN_GATE4_COMPLETE_VISUAL_V0.1.html',b=root+'/pages/resources/india-trade/04_planning/RES-TRADE-IN_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md';const id=p=>({path:p,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
(async()=>{const out={source:id(src),approved_B:id(b),reviewer:'/root/g5_trade_in',scope:'Resolve raw TH overflow diagnostic; independent B parse, shared assembly, state target and wheel checks, 200% effective reflow and contrast.',checks:[]},add=(name,pass,detail)=>out.checks.push({name,pass,detail});
 const {marked}=await import('file:///'+deps+'marked/lib/marked.esm.js');const md=fs.readFileSync(b,'utf8').split('\n---\n')[1];const expectedHtml=marked.parse(md);const browser=await chromium.launch({channel:'chrome',headless:true});out.browser=browser.version();const expectedPage=await browser.newPage();await expectedPage.setContent('<main>'+expectedHtml+'</main>');const get=()=>({blocks:[...document.querySelectorAll('main h1,main h2,main h3,main p,main li,main th,main td')].map(e=>e.textContent.replace(/\s+/g,' ').trim()),links:[...document.querySelectorAll('main a')].map(e=>({text:e.textContent,href:e.getAttribute('href')}))});const expected=await expectedPage.evaluate(get);await expectedPage.close();out.expectedBlockCount=expected.blocks.length;
 const html=fs.readFileSync(src,'utf8');const {renderSharedChrome}=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs');const shared=renderSharedChrome({currentPageId:'RES-000',fontSrc:'../../../../../docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf',primaryLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg'});for(const k of ['header','footer','dialog','style','behavior'])add('shared owner '+k+' exact',html.includes(shared[k]));
 for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:900}});await page.goto('file:///'+src);await page.evaluate(()=>document.fonts.ready);const actual=await page.evaluate(get);add(width+' independent B complete exact',JSON.stringify(actual)===JSON.stringify(expected),{blocks:actual.blocks.length,links:actual.links.length});
 if(width===390){const th=await page.locator('.table-2 thead').evaluate(e=>({clip:getComputedStyle(e).clipPath,overflow:getComputedStyle(e).overflow,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,scrollWidth:document.documentElement.scrollWidth,headers:[...e.querySelectorAll('th')].map(x=>({text:x.textContent,x:x.getBoundingClientRect().x,right:x.getBoundingClientRect().right}))}));out.rawOverflowResolution=th;add('390 raw TH overflow is intentional clipped accessibility header',th.clip==='inset(50%)'&&th.width===1&&th.height===1&&th.scrollWidth===390);}
 if(width<1101){await page.locator('.menuButton').focus();await page.keyboard.press('Enter');add(width+' keyboard menu entry visible focus',await page.locator('.mobileNav a').first().evaluate(e=>document.activeElement===e&&getComputedStyle(e).outlineStyle==='solid'));add(width+' menu targets',await page.locator('.mobileNav a').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)));const y=await page.evaluate(()=>scrollY);await page.mouse.move(width-8,700);await page.mouse.wheel(0,500);await page.waitForTimeout(90);add(width+' menu wheel lock',await page.evaluate(()=>scrollY)===y);await page.keyboard.press('Escape');}
 await page.locator('#cookie-trigger').click();add(width+' modal targets',await page.locator('.cookie-actions>*').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)));out['cookie'+width]=await page.locator('dialog').evaluate(e=>({width:e.offsetWidth,height:e.offsetHeight,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight}));await page.close();}
 const z=await browser.newPage({viewport:{width:720,height:450},deviceScaleFactor:2});await z.goto('file:///'+src);await z.evaluate(()=>document.fonts.ready);out.zoomEquivalent={type:'ACTUAL_RUNTIME_EFFECTIVE_VIEWPORT',equivalence:'1440x900 at 200% = 720x450 CSS viewport, DPR2; browser UI zoom/physical device not claimed',geometry:await z.evaluate(()=>({width:innerWidth,height:innerHeight,dpr:devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,clipped:[...document.querySelectorAll('main p,main li,main td')].filter(e=>e.scrollHeight>e.clientHeight+2).length}))};add('200% effective reflow',out.zoomEquivalent.geometry.scrollWidth===720&&out.zoomEquivalent.geometry.clipped===0);await z.locator('.menuButton').click();add('200% menu last item reachable',await z.locator('.mobileNav a').last().evaluate(e=>{e.scrollIntoView();return e.getBoundingClientRect().bottom<=innerHeight+1}));await z.keyboard.press('Escape');await z.locator('#cookie-trigger').click();add('200% dialog fits',await z.locator('dialog').evaluate(e=>{let r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}));await z.close();
 const lum=h=>h.match(/../g).map(x=>parseInt(x,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);out.contrast=[];for(const [fg,bg] of [['334155','FFFFFF'],['334155','F5F8FB'],['062B5B','FFFFFF'],['062B5B','F5F8FB'],['008078','FFFFFF'],['008078','F5F8FB'],['FFFFFF','062B5B'],['FFFFFF','008078'],['D4E0EB','031B3A'],['FFFFFF','031B3A']]){let ratio=(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05);out.contrast.push({fg,bg,ratio});add('contrast '+fg+'/'+bg,ratio>=4.5)}
 out.finished=new Date().toISOString();fs.writeFileSync(__dirname+'/supplement-observations.json',JSON.stringify(out,null,2));await browser.close();console.log(JSON.stringify({checks:out.checks.length,failures:out.checks.filter(c=>!c.pass),expectedBlockCount:out.expectedBlockCount,shared:out.checks.slice(0,5)},null,2));})();
