import fs from 'node:fs';
import crypto from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { chromium } from 'file:///C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const out='D:/23MySec/pages/conversion/thank-you/04_planning/gate4-v0.2';
const source=`${out}/CONV-THANK_GATE4_EDITABLE_SOURCE_V0.2.html`;
const formal=process.argv.includes('--formal');
const dest=formal?`${out}/approval_core`:`${out}/diagnostic_support`;
const resultPath=formal?`${out}/diagnostic_support/CONV-THANK_GATE4_FORMAL_RUNTIME_V0.2.json`:`${out}/CONV-THANK_GATE4_PREFLIGHT_V0.2.json`;
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const identity=file=>({path:file,bytes:fs.statSync(file).size,sha256:sha(file)});
const expected={
 quote:{eyebrow:'REQUEST RECEIVED',h1:'Thank you. We’ve received your quotation request.',body:'Our team will review the details and contact you using the information provided.',actions:[['Explore Products','/products/'],['Go to Homepage','/']]},
 documents:{eyebrow:'REQUEST RECEIVED',h1:'Thank you. We’ve received your document request.',body:'Our team will review the requested documents and contact you using the information provided.',actions:[['Return to Documents','/documents/'],['Explore Products','/products/']]},
 sample:{eyebrow:'REQUEST RECEIVED',h1:'Thank you. We’ve received your sample request.',body:'Our team will review your application and sample requirements and contact you using the information provided.',actions:[['Explore Products','/products/'],['View Applications','/applications/']]},
 direct:{eyebrow:null,h1:'How can we help?',body:'Choose the request you’d like to make, and our team will guide you through the next step.',actions:[['Request a Quote','/request-a-quote/'],['Request Documents','/request-documents/'],['Request a Sample','/request-sample/']]}
};
const checks=[];const assets=[];const blockedNetwork=[];
const check=(name,ok,detail='')=>{checks.push({name,status:ok?'PASS':'FAIL',detail});if(!ok)throw new Error(`${name}: ${JSON.stringify(detail)}`)};
const ready=async page=>page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
const shot=async(page,name,fullPage=false,role='full_page')=>{const file=`${dest}/${name}.png`;await ready(page);await page.screenshot({path:file,fullPage,animations:'disabled'});assets.push({...identity(file),role});};
const restore=page=>page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&!document.querySelector('footer').inert&&document.body.style.overflow==='');
let browser;
try{
 if(formal){const freeze=JSON.parse(fs.readFileSync(`${out}/CONV-THANK_GATE4_FREEZE_RECORD_V0.2.json`,'utf8'));check('frozen source identity',freeze.source.sha256===sha(source),freeze.source);check('formal directory empty',fs.readdirSync(dest).length===0,fs.readdirSync(dest));}
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 for(const state of Object.keys(expected))for(const width of [1440,768,390]){
  const height=width===390?844:900;const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'reduce'});await context.route(/^https?:/,route=>{blockedNetwork.push(route.request().url());return route.abort()});const page=await context.newPage();
  if(state!=='direct')await page.addInitScript(s=>sessionStorage.setItem('tio2my_thankyou_gate3_marker',JSON.stringify({type:s,acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false})),state);
  await page.goto(pathToFileURL(source).href+(state==='direct'?'':`?request=${state}`));await ready(page);
  const observed=await page.evaluate(()=>{const p=document.querySelector('[data-result-state]:not([hidden])');return{state:document.documentElement.dataset.resolvedState,visiblePanels:document.querySelectorAll('[data-result-state]:not([hidden])').length,eyebrow:p.querySelector('.successCue span:last-child')?.innerText.trim()||null,icon:p.querySelectorAll('.successIcon').length,h1:p.querySelector('h1').innerText.trim(),body:p.querySelector('p').innerText.trim(),actions:[...p.querySelectorAll('.resultAction')].map(a=>[a.innerText.trim(),a.getAttribute('href')]),text:document.querySelector('main').innerText,currentCount:document.querySelectorAll('[aria-current="page"]').length,font:document.fonts.check('16px Inter'),robots:document.querySelector('meta[name="robots"]')?.content,canonical:document.querySelector('link[rel="canonical"]')?.href}});
  check(`${state} ${width} exact state content`,observed.state===state&&observed.visiblePanels===1&&observed.eyebrow===expected[state].eyebrow&&observed.h1===expected[state].h1&&observed.body===expected[state].body&&JSON.stringify(observed.actions)===JSON.stringify(expected[state].actions),observed);
  check(`${state} ${width} cue boundary`,state==='direct'?observed.icon===0&&!observed.text.includes('REQUEST RECEIVED'):observed.icon===1&&observed.text.includes('REQUEST RECEIVED'),observed);
  check(`${state} ${width} no PII/current and head contract`,!/(john@|email address|phone|company name|request reference|CURRENT)/i.test(observed.text)&&observed.currentCount===0&&observed.font&&observed.robots==='noindex,nofollow'&&observed.canonical==='https://tio2malaysia.com/thank-you/',observed);
  const g=await page.evaluate(()=>{const doc=document.documentElement,footer=document.querySelector('footer'),panel=document.querySelector('[data-result-state]:not([hidden])');const targets=[...document.querySelectorAll('a,button')].filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&r.height>0}).map(n=>{const r=n.getBoundingClientRect();return{text:n.textContent.trim(),width:r.width,height:r.height,left:r.left,right:r.right}});const h1=getComputedStyle(panel.querySelector('h1'));const body=getComputedStyle(panel.querySelector('p'));return{scrollWidth:doc.scrollWidth,clientWidth:doc.clientWidth,scrollHeight:doc.scrollHeight,footerBottom:footer.getBoundingClientRect().bottom+scrollY,panelWidth:panel.getBoundingClientRect().width,footerOrder:[...footer.children].map(n=>n.className),legalOrder:[...footer.querySelector('.legalUtilities').children].map(n=>n.textContent.trim()),targets,h1:{color:h1.color,fontSize:h1.fontSize,lineHeight:h1.lineHeight},body:{color:body.color,fontSize:body.fontSize,lineHeight:body.lineHeight}}});
  check(`${state} ${width} complete to Footer and no overflow`,g.scrollWidth===width&&Math.abs(g.scrollHeight-g.footerBottom)<2,g);
  check(`${state} ${width} copyright-first Footer order`,JSON.stringify(g.footerOrder)===JSON.stringify(['footerGrid','copyright','legalUtilities'])&&JSON.stringify(g.legalOrder)===JSON.stringify(['Privacy Policy','Dasar Privasi (BM)','Cookie Policy','Cookie Settings']),g);
  check(`${state} ${width} controls 44 by 44`,g.targets.every(t=>t.width>=44&&t.height>=44&&t.left>=-.5&&t.right<=width+.5),g.targets.filter(t=>t.width<44||t.height<44||t.left<-.5||t.right>width+.5));
  check(`${state} ${width} brand typography`,g.h1.color==='rgb(6, 43, 91)'&&parseFloat(g.body.lineHeight)>=parseFloat(g.body.fontSize)*1.6,g);
  for(let i=0;i<expected[state].actions.length;i++){await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).focus();check(`${state} ${width} action ${i+1} focus visible`,await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).evaluate(n=>getComputedStyle(n).outlineStyle!=='none'));await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).click();const intent=await page.evaluate(()=>window.localNavigationIntents.at(-1));check(`${state} ${width} action ${i+1} target`,intent.href===expected[state].actions[i][1],intent);}
  await page.evaluate(()=>document.activeElement?.blur());
  if(formal)await shot(page,`CONV-THANK_GATE4_${state.toUpperCase()}_${width}_FULL_V0.2`,true,'full_page');
  else if((state==='quote'&&width===1440)||(state==='sample'&&width===390))await shot(page,`CONV-THANK_GATE4_4A_${state.toUpperCase()}_${width}_V0.2`,true,'4a_risk_sample');
  if(state==='direct'&&width<1101){const toggle=page.locator('.menuButton'),menu=page.locator('.mobileNav');await toggle.click();check(`${width} menu opens and isolates`,await page.evaluate(()=>document.activeElement.textContent.trim()==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'));await page.keyboard.press('Shift+Tab');check(`${width} menu reverse reaches toggle`,await toggle.evaluate(n=>n===document.activeElement));await page.keyboard.press('Shift+Tab');check(`${width} menu reverse wraps to final link`,await menu.locator('a').last().evaluate(n=>n===document.activeElement));await page.keyboard.press('Tab');check(`${width} menu forward wraps to toggle`,await toggle.evaluate(n=>n===document.activeElement));if(formal)await shot(page,`CONV-THANK_GATE4_DIRECT_${width}_MENU_V0.2`,false,'menu_open');await page.keyboard.press('Escape');check(`${width} menu Escape restores`,await restore(page)&&await toggle.evaluate(n=>n===document.activeElement));await toggle.click();await menu.locator('a').nth(1).click();check(`${width} menu selection closes`,await restore(page));}
  if(state==='direct'){await page.locator('#cookie-trigger').click();check(`${width} Cookie opens to Close`,await page.locator('[data-cookie-close]').evaluate(n=>n===document.activeElement));await page.keyboard.press('Shift+Tab');check(`${width} Cookie reverse cycle`,await page.locator('.cookie-layer a').evaluate(n=>n===document.activeElement));await page.keyboard.press('Tab');if(formal&&width===390)await shot(page,'CONV-THANK_GATE4_DIRECT_390_COOKIE_V0.2',false,'cookie_open');await page.keyboard.press('Escape');check(`${width} Cookie Escape returns focus`,await page.locator('#cookie-trigger').evaluate(n=>n===document.activeElement));}
  await context.close();
 }
 const negatives=[
  ['missing request key','',{type:'quote',acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false}],['unsupported request','?request=unsupported',{type:'quote',acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false}],['query alone','?request=quote',null],['mismatched','?request=documents',{type:'quote',acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false}],['stale','?request=sample',{type:'sample',acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:true}],['new session','?request=quote',{type:'quote',acknowledged:true,session:'different-session',successTimestamp:Date.now(),stale:false}],['not acknowledged','?request=documents',{type:'documents',acknowledged:false,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false}],['obsolete type rejected','?type=quote',{type:'quote',acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false}]
 ];
 for(const [name,query,marker] of negatives){const c=await browser.newContext({viewport:{width:390,height:844}}),p=await c.newPage();if(marker)await p.addInitScript(m=>sessionStorage.setItem('tio2my_thankyou_gate3_marker',JSON.stringify(m)),marker);await p.goto(pathToFileURL(source).href+query);await ready(p);check(`${name} resolves Direct without receipt`,await p.evaluate(()=>document.documentElement.dataset.resolvedState==='direct'&&!document.querySelector('[data-result-state="direct"]').hidden&&document.querySelectorAll('.successState:not([hidden])').length===0&&!document.querySelector('main').innerText.includes('REQUEST RECEIVED')));await c.close();}
 const zoom=await browser.newContext({viewport:{width:720,height:900},deviceScaleFactor:2}),zp=await zoom.newPage();await zp.goto(pathToFileURL(source).href);await ready(zp);check('200 percent equivalent reflow',await zp.evaluate(()=>document.documentElement.scrollWidth===720&&document.querySelector('[data-result-state="direct"] h1').innerText==='How can we help?'));await zoom.close();
 check('no network requests',blockedNetwork.length===0,blockedNetwork);
 const result={status:'PASS',phase:formal?'CAPTURE_CHECK':'HARD_PREFLIGHT_INITIAL',workset_id:'CONV-THANK-G4-WORKSET-20260908-02',executor:'/root/conv_thank_gate4_execute',source:identity(source),evidenceTypes:['ACTUAL_RUNTIME','STATIC_VISUAL','SOURCE_INSPECTION','LOCAL_SIMULATION'],browser:'Chrome / Playwright, DPR 1 (DPR 2 only for 200% equivalent reflow)',viewports:[{width:1440,height:900},{width:768,height:900},{width:390,height:844}],states:Object.keys(expected),checks,assets,blockedNetwork,findings:[],unverified:['production receiver and navigation','real session implementation','real devices and screen reader','Gate 8 CMS/SEO/Schema/scope integration'],endedAt:new Date().toISOString()};fs.writeFileSync(resultPath,JSON.stringify(result,null,2));console.log(JSON.stringify({status:'PASS',formal,checks:checks.length,assets:assets.length},null,2));
}catch(error){const fail={status:'FAIL',formal,checks,assets,blockedNetwork,error:String(error.stack||error),endedAt:new Date().toISOString()};fs.writeFileSync(`${out}/diagnostic_support/CONV-THANK_GATE4_FAILURE_${Date.now()}.json`,JSON.stringify(fail,null,2));console.error(error);process.exitCode=1;}finally{if(browser)await browser.close();}
