const fs=require('fs'),crypto=require('crypto'),path=require('path');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base='D:/23MySec/pages/markets/poland',src=base+'/04_planning/gate4-v0.1',out=base+'/05_review/gate4-project-control-v0.1/independent-review';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const freeze=JSON.parse(fs.readFileSync(src+'/approval_core/source-freeze.json')),inventory=JSON.parse(fs.readFileSync(src+'/approval_core/export-inventory.json'));
const audit=()=>[...freeze.dependencies,...freeze.inputs,...inventory.captures].map(f=>{const b=fs.readFileSync(f.path);return{path:f.path,bytes:b.length,sha256:hash(b),matches:b.length===f.bytes&&hash(b)===f.sha256,...(f.path.endsWith('.png')?{width:b.readUInt32BE(16),height:b.readUInt32BE(20),dimensionMatches:b.readUInt32BE(16)===f.physicalWidth&&b.readUInt32BE(20)===f.physicalHeight}:{})}});
const evidence={freezeId:freeze.freezeId,before:audit(),inventoryBinding:hash(fs.readFileSync(src+'/approval_core/source-freeze.json'))===inventory.sourceFreezeSha256,observations:[],errors:[],blocked:[]};
const html=fs.readFileSync(src+'/'+freeze.entry,'utf8'),g3=fs.readFileSync(base+'/04_planning/gate3-v0.1/MARKET-EU-PL_GATE3_RESPONSIVE_WIREFRAME_V0.1.html','utf8');
evidence.sourceComparison={bodyByteIdentical:html.split('<body>')[1]===g3.split('<body>')[1],mainByteIdentical:html.match(/<main>[\s\S]*?<\/main>/)[0]===g3.match(/<main>[\s\S]*?<\/main>/)[0]};
const norm=s=>s.replace(/\s+/g,' ').trim(),B=norm(fs.readFileSync(base+'/04_planning/MARKET-EU-PL_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/^#+ /gm,''));
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});evidence.renderer=await browser.version();
for(const width of [1440,768,390]){const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1});await context.route('**/*',r=>/^https?:/.test(r.request().url())?(evidence.blocked.push(r.request().url()),r.abort()):r.continue());const page=await context.newPage();page.on('pageerror',e=>evidence.errors.push(e.message));await page.goto('file:///'+src+'/'+freeze.entry);await page.evaluate(()=>document.fonts.ready);
const record=async(state,extra={})=>{const d=await page.evaluate(()=>{const visible=e=>e.getClientRects().length>0&&getComputedStyle(e).visibility!=='hidden';const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}};const current=e=>e.id||e.className||e.textContent.trim();const bg=e=>{let p=e;while(p){const c=getComputedStyle(p).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;p=p.parentElement}return 'rgb(255, 255, 255)'};const color=e=>{const s=getComputedStyle(e);return{fg:s.color,bg:bg(e),ownBg:s.backgroundColor,border:s.borderColor,borderWidth:s.borderWidth,outline:s.outline,outlineOffset:s.outlineOffset,font:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,textDecoration:s.textDecorationColor}};return{innerWidth:innerWidth,scrollWidth:document.documentElement.scrollWidth,fontFaces:[...document.fonts].map(f=>({family:f.family,status:f.status})),text:document.querySelector('main').innerText,active:current(document.activeElement),activeStyle:color(document.activeElement),menuOpen:!document.querySelector('.mobileNav').hidden,cookieOpen:document.querySelector('dialog').open,bodyOverflow:document.body.style.overflow,mainInert:document.querySelector('main').inert,footerInert:document.querySelector('footer').inert,logoInert:document.querySelector('.logoLink').inert,headerRfqInert:document.querySelector('.headerRfq').inert,header:box(document.querySelector('header')),logos:[...document.images].map(e=>({src:e.getAttribute('src'),alt:e.alt,naturalWidth:e.naturalWidth,...box(e)})),controls:[...document.querySelectorAll('a,button')].filter(visible).map(e=>({id:current(e),href:e.getAttribute('href'),text:e.textContent.trim(),inert:!!e.closest('[inert]'),...box(e),...color(e)})),texts:[...document.querySelectorAll('main h1,main h2,main h3,main p,.footer p,.cookie-layer p')].filter(visible).map(e=>({text:e.textContent,...box(e),...color(e)})),currentNavigation:[...document.querySelectorAll('[aria-current]')].map(e=>({text:e.textContent,visible:visible(e),value:e.getAttribute('aria-current')})),applicationPaths:[...document.querySelectorAll('.application-path')].map(e=>({...box(e),cursor:getComputedStyle(e).cursor})),planningNavigation:window.planningNavigation};});evidence.observations.push({width,state,type:'ACTUAL_RUNTIME',...extra,...d});return d};
const init=await record('initial');evidence.observations.push({width,state:'buyer-copy-equality',type:'SOURCE_INSPECTION+ACTUAL_RUNTIME',exactNormalized:B===norm(init.text),expected:B,actual:norm(init.text)});
await page.locator('#pl-01 a[href="/request-a-quote/"]').hover();await record('hero-primary-hover');if(width===1440)await page.locator('#pl-01').screenshot({path:out+'/1440-hero-primary-hover.png'});
await page.locator('#pl-01 a[href="/products/"]').hover();await record('hero-secondary-hover');await page.locator('#pl-03 a').hover();await record('product-secondary-hover');
await page.locator('#pl-01 a[href="/request-a-quote/"]').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await record('hero-primary-keyboard-focus');
const links=await page.locator('main a').count();for(let i=0;i<links;i++)await page.locator('main a').nth(i).click();await record('body-links-activated');
if(width<1101){await page.locator('.menuButton').focus();await page.keyboard.press('Enter');await record('menu-open-keyboard');const sequence=[];for(let i=0;i<10;i++){await page.keyboard.press('Tab');sequence.push(await page.evaluate(()=>document.activeElement.textContent.trim()))}evidence.observations.push({width,state:'menu-tab-cycle',type:'ACTUAL_RUNTIME',sequence});await page.locator('.menuButton').focus();await page.keyboard.press('Shift+Tab');await record('menu-reverse-cycle');await page.evaluate(()=>document.querySelector('main a').focus());await record('menu-background-focus-attempt');await page.keyboard.press('Escape');await record('menu-escape-closed');await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();await record('menu-link-closed');await page.locator('.menuButton').click();await page.locator('.menuButton').click();await record('menu-close-button');await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(100);await record('menu-desktop-breakpoint');await page.setViewportSize({width,height:1000});}
await page.locator('#cookie-trigger').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await record('footer-trigger-keyboard-focus');if(width===390)await page.locator('footer').screenshot({path:out+'/390-footer-keyboard-focus.png'});
await page.locator('#cookie-trigger').focus();await page.keyboard.press('Enter');await record('cookie-open');await page.keyboard.press('Shift+Tab');await record('cookie-reverse-cycle');await page.keyboard.press('Tab');await record('cookie-forward-cycle');await page.evaluate(()=>document.querySelector('main a').focus());await record('cookie-background-focus-attempt');await page.keyboard.press('Escape');await record('cookie-escape-return');await page.locator('#cookie-trigger').click();await page.locator('.cookie-actions button').click();await record('cookie-close-return');await page.locator('#cookie-trigger').click();await page.locator('.cookie-actions a').hover();await record('cookie-policy-hover');await page.locator('.cookie-actions a').click();await record('cookie-policy-intercepted');await page.keyboard.press('Escape');
await context.close();}
evidence.after=audit();fs.writeFileSync(out+'/runtime-observations.json',JSON.stringify(evidence,null,2));await browser.close();console.log(JSON.stringify({identityIssues:evidence.after.filter(x=>!x.matches||x.dimensionMatches===false),sourceComparison:evidence.sourceComparison,copyChecks:evidence.observations.filter(x=>x.state==='buyer-copy-equality').map(x=>({width:x.width,equal:x.exactNormalized})),errors:evidence.errors,blocked:evidence.blocked}));})().catch(e=>{evidence.failure={message:e.message,stack:e.stack};fs.writeFileSync(out+'/attempt-failure.json',JSON.stringify(evidence,null,2));console.error(e);process.exit(1)});
