const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/resources/r706-alternative/04_planning/gate3-v0.1',source=out+'/RES-R706_GATE3_WIREFRAME_V0.1.html',formal=process.argv.includes('--formal'),dest=out+(formal?'/approval_core':'/diagnostic_support/render');
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const expected=JSON.parse(fs.readFileSync(out+'/diagnostic_support/expected-copy.json','utf8'));let checks=[],assets=[],blocked=[];
const test=(name,ok,detail)=>{checks.push({name,status:ok?'PASS':'FAIL',detail});if(!ok)throw Error(name+' '+JSON.stringify(detail));};
const norm=s=>s.replace(/\s+/g,' ').trim();
const ready=async p=>{await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});};
const shot=async(p,name,fullPage=false)=>{const f=dest+'/'+name+'.png';await ready(p);await p.screenshot({path:f,fullPage,animations:'disabled'});assets.push({...id(f),width:(await p.viewportSize()).width,state:name});};
const restored=p=>p.evaluate(()=>!document.querySelector('main').inert&&!document.querySelector('footer').inert&&!document.querySelector('.logoLink').inert&&!document.querySelector('.headerRfq').inert&&document.body.style.overflow===''&&document.querySelector('.mobileNav').hidden);
let browser;
(async()=>{if(formal){const freeze=JSON.parse(fs.readFileSync(out+'/freeze-record.json','utf8'));test('frozen source',freeze.source.sha256===id(source).sha256);test('first formal export',fs.readdirSync(dest).length===0);}
browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
for(const w of [1440,768,390]){const h=w===390?844:900;const context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await context.route(/^https?:/,route=>{blocked.push(route.request().url());return route.abort()});const p=await context.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
const actual=await p.locator('main').evaluate(m=>[...m.querySelectorAll('h1,h2,h3,p,li')].map(e=>({tag:e.tagName.toLowerCase(),text:e.textContent.replace(/\s+/g,' ').trim()})));
test(w+' exact full ordered blocks',JSON.stringify(actual)===JSON.stringify(expected.blocks.map(b=>({...b,text:norm(b.text)}))),actual.length);
const links=await p.locator('main a').evaluateAll(as=>as.map(a=>({text:a.textContent,href:a.getAttribute('href')})));test(w+' exact ordered hrefs',JSON.stringify(links)===JSON.stringify(expected.links),links);
const geo=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,footer:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,bodyFont:getComputedStyle(document.body).fontFamily,margin:getComputedStyle(document.body).margin,loaded:document.fonts.check('16px Inter'),targets:[...document.querySelectorAll('a,button')].filter(e=>e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0).map(e=>({text:e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),mainColors:[...document.querySelectorAll('main a')].map(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}))}));
test(w+' geometry Footer and Inter',geo.scrollWidth===w&&Math.abs(geo.height-geo.footer)<2&&geo.loaded&&geo.bodyFont.startsWith('Inter')&&geo.margin==='0px',geo);
test(w+' 44px visible targets',geo.targets.every(t=>t.w>=44&&t.h>=44),geo.targets.filter(t=>t.w<44||t.h<44));test(w+' functional color',geo.mainColors.every(c=>c.color==='rgb(0, 128, 120)'||(c.color==='rgb(255, 255, 255)'&&c.bg==='rgb(0, 128, 120)')));
test(w+' Resources current and no invented form',await p.locator('.desktopNav [aria-current=page]').textContent()==='Resources'&&await p.locator('main .module').count()===6&&await p.locator('main form,main select,main input,main table,main details,main img').count()===0);
await shot(p,(formal?'RES-R706_G3_':'diagnostic-')+w+'-full',true);
if(!formal){for(let y=0,i=1;y<geo.height;y+=750,i++){const f=dest+'/'+w+'-segment-'+String(i).padStart(2,'0')+'.png';await p.screenshot({path:f,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,geo.height-y)},animations:'disabled'});assets.push({...id(f),width:w,state:'native-readable-segment',y});}}
// Every actual body navigation is locally recorded without context or requests.
for(let i=0;i<links.length;i++){if(links[i].href.startsWith('#'))continue;await p.locator('main a').nth(i).click();const nav=await p.evaluate(()=>window.localNavigationIntents.at(-1));test(w+' local href '+i,nav.href===links[i].href&&Object.keys(nav.context).length===0,nav);}
await p.evaluate(()=>scrollTo(0,0));await p.locator('a[href="#evaluation-brief"]').click();test(w+' anchor click focus',await p.evaluate(()=>document.activeElement.id==='evaluation-brief'&&Math.abs(document.activeElement.getBoundingClientRect().top-24)<2));
await p.evaluate(()=>scrollTo(0,0));await p.locator('a[href="#evaluation-brief"]').focus();await p.keyboard.press('Enter');test(w+' anchor Enter focus',await p.evaluate(()=>document.activeElement.id==='evaluation-brief'));if(!formal)await shot(p,w+'-anchor');
await p.keyboard.press('Tab');test(w+' anchor subsequent Tab source',await p.evaluate(()=>document.activeElement.getAttribute('href'))===links[4].href);
await p.goto(pathToFileURL(source).href+'#evaluation-brief');await ready(p);test(w+' direct fragment focus',await p.evaluate(()=>document.activeElement.id==='evaluation-brief'&&document.activeElement.getBoundingClientRect().top>=0&&document.activeElement.getBoundingClientRect().top<50));
await p.goto(pathToFileURL(source).href);await ready(p);
if(w<1101){const toggle=p.locator('.menuButton'),menu=p.locator('.mobileNav');await toggle.click();test(w+' Menu first Home/background',await p.evaluate(()=>document.activeElement.textContent==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'&&document.querySelector('.menuButton').textContent==='Close'));
await shot(p,(formal?'RES-R706_G3_':'diagnostic-')+w+'-menu');const mg=await menu.locator('a').evaluateAll(as=>as.map(a=>({w:a.getBoundingClientRect().width,h:a.getBoundingClientRect().height})));test(w+' Menu 44px',mg.every(g=>g.w>=44&&g.h>=44));
await menu.locator('a').last().focus();await p.keyboard.press('Tab');test(w+' Menu Tab cycle',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');test(w+' Menu reverse cycle',await menu.locator('a').last().evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');test(w+' Menu Escape restored',await restored(p)&&await toggle.evaluate(e=>e===document.activeElement));
await toggle.click();await toggle.click();test(w+' Menu Close restored',await restored(p));
for(let i=0;i<8;i++){await toggle.click();const href=await menu.locator('a').nth(i).getAttribute('href');await menu.locator('a').nth(i).click();test(w+' Menu selection '+i,await restored(p)&&(await p.evaluate(()=>window.localNavigationIntents.at(-1).href))===href);}
await toggle.click();const before=await p.evaluate(()=>scrollY);await p.mouse.move(w-5,h-10);await p.mouse.wheel(0,650);await p.waitForTimeout(120);test(w+' Menu background scroll locked',await p.evaluate(()=>scrollY)===before);await p.setViewportSize({width:1200,height:h});test(w+' Menu desktop resize restored',await restored(p));await p.setViewportSize({width:w,height:h});}
await p.locator('#cookie-trigger').click();test(w+' Cookie focus entry',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await shot(p,(formal?'RES-R706_G3_':'diagnostic-')+w+'-cookie');const cg=await p.locator('.cookie-actions a,.cookie-actions button').evaluateAll(es=>es.map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,color:getComputedStyle(e).color,border:getComputedStyle(e).borderTopColor})));test(w+' Cookie action size/color',cg.every(g=>g.w>=44&&g.h>=44&&g.color==='rgb(0, 128, 120)'&&g.border==='rgb(0, 128, 120)'),cg);
await p.keyboard.press('Shift+Tab');test(w+' Cookie reverse cycle',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');test(w+' Cookie forward cycle',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('[data-cookie-close]').click();test(w+' Cookie close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');test(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!(await p.locator('dialog').evaluate(e=>e.open)));
const nojs=await browser.newContext({viewport:{width:w,height:h},javaScriptEnabled:false});const n=await nojs.newPage();await n.goto(pathToFileURL(source).href);await n.locator('a[href="#evaluation-brief"]').click();test(w+' noJS ordinary fragment',n.url().endsWith('#evaluation-brief')&&(await n.locator('#evaluation-brief').boundingBox()).y<60);test(w+' noJS full document',await n.locator('main h1').count()===1&&await n.locator('main a').count()===8);await nojs.close();await context.close();}
test('no network requests',blocked.length===0,blocked);await browser.close();fs.writeFileSync(dest+'/runtime.json',JSON.stringify({status:'PASS',evidenceType:['ACTUAL_RUNTIME','LOCAL_SIMULATION'],source:id(source),browser:'Chrome 152 / Playwright 1.62.1, DPR 1',formal,checks,assets,blocked,endedAt:new Date().toISOString()},null,2));console.log(JSON.stringify({status:'PASS',formal,checks:checks.length,assets:assets.length}));
})().catch(async e=>{if(browser)await browser.close();const failure={status:'FAIL',error:e.stack,checks,assets,source:id(source),at:new Date().toISOString()};fs.writeFileSync(out+'/diagnostic_support/failure-'+Date.now()+'.json',JSON.stringify(failure,null,2));console.error(e);process.exitCode=1;});
