const fs=require('fs'),crypto=require('crypto');
const page='D:/23MySec/pages/resources/r706-alternative',out=page+'/04_planning/gate3-v0.1',review=page+'/05_review',evidence=review+'/RES-R706_GATE3_EXECUTION_EVIDENCE_V0.1';fs.mkdirSync(evidence,{recursive:true});
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});const write=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2)+'\n');
const binding=JSON.parse(fs.readFileSync(out+'/input-binding.json','utf8')),freeze=JSON.parse(fs.readFileSync(out+'/freeze-record.json','utf8')),runtime=JSON.parse(fs.readFileSync(out+'/approval_core/runtime.json','utf8'));
for(const a of [freeze.source,freeze.inputBinding,freeze.preflight,...binding.approvedInputs,...binding.authorityInputs,...binding.sharedFiles,...binding.dependencies,binding.sharedConsumer])if(id(a.path).sha256!==a.sha256)throw Error('changed '+a.path);
const images=runtime.assets.map(a=>{const actual=id(a.path),buf=fs.readFileSync(a.path),name=a.path.split('/').at(-1),diagnostic=out+'/diagnostic_support/render/'+name.replace('RES-R706_G3_','diagnostic-');if(actual.sha256!==a.sha256)throw Error('image changed');return {...actual,width:buf.readUInt32BE(16),height:buf.readUInt32BE(20),logicalWidth:a.width,dpr:1,state:a.state,diagnosticMatch:actual.sha256===id(diagnostic).sha256}});
if(images.length!==8||images.some(a=>!a.diagnosticMatch))throw Error('formal diagnostic pixel identity mismatch');
fs.renameSync(out+'/approval_core/runtime.json',evidence+'/formal-runtime.json');
const visual={status:'EXECUTION_VISUAL_CHECK_COMPLETE',evidenceType:'STATIC_VISUAL',reviewer:'Gate3 execution agent',source:freeze.source,actualOpenedFormalImages:images,openedAt:new Date().toISOString(),nativeReadableCoverage:'24 diagnostic segments at original pixel dimensions (7 desktop, 7 tablet, 10 mobile) plus 3 anchor focus states were actually opened. All 8 formal PNGs were separately opened and are byte-identical to corresponding diagnostic images; native-readable coverage therefore binds the same frozen pixels.',judgment:'Complete reading flow to shared Footer; no clipping, overlap or unintended equivalence/recommendation treatment; source metadata and human-review boundaries remain legible. Menu and Cookie actions remain visible.',unresolvedFindings:[]};write(evidence+'/formal-visual-observation.json',visual);
const failureFiles=fs.readdirSync(out+'/diagnostic_support').filter(n=>n.startsWith('failure-')).map(n=>id(out+'/diagnostic_support/'+n));
write(out+'/design-report.md',`# RES-R706 Gate 3 design method report V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Execution agent report, not independent approval. Page RES-R706 only; no subsequent page or Gate 4 work.

The editable source is ${freeze.source.path}, ${freeze.source.bytes} bytes, SHA-256 ${freeze.source.sha256}. Hard preflight PASS_FOR_FORMAL_RENDER was validated before freezing at ${freeze.frozenAt}; eight formal exports were first generated afterward. Exact approved and shared identities are in input-binding.json and freeze-record.json.

The six modules map directly to B V0.3: Hero; Establish the R-706 Reference; Build an R-706-Specific Evaluation Brief; Plan Tests Around the R-706 Evaluation Dimensions; Understand the Scope of the TS-6706 Announcement; Continue with a Buyer-Selected Grade. Plain breadcrumb precedes Hero. The four numbered brief items, four test groups and three downstream steps remain sequential. Editorial Breadcrumb/Primary action/Secondary action/Action labels are omitted; actual CTA copy, Official sources and Last reviewed remain. No new body copy, table, FAQ, form, Grade selector or comparison graphic.

The fresh design uses a continuous editorial column with restrained section rules, clear heading hierarchy and full-length paragraphs. A 1200px outer container carries a 920px reading column; the tablet/mobile column naturally contracts, with 32px/20px gutters and 17px/16px body text. Mobile actions span the column. Sources and dates stay in the same list items; the TS-6706 pair relationship, reported test subject and separate dry-pigment-flow context stay together. No card pair suggests equivalence. Inter is loaded from a durable neutral-package snapshot. Functional page links, focus rings and primary action use #008078 per current CTA Addendum; shared navigation retains its owner treatment.

Header/Footer/Cookie were generated only by Shared Consumer V0.2 with currentPageId=RES-000 and approved production SVG paths. No business-page source was read or copied as a template. Current Chrome V0.5, fixed RFQ, Procurement, legal utilities and no_optional_analytics override the older Playbook's conditional shared CTA/legal and color instructions. Page-level content remains exclusively approved B.

responsive-wireframe-design V0.2 was used for input-card/binding, long-copy layout, diagnostic iteration, hard preflight, freeze and evidence layering. layout-interaction-verification V0.2 was used for fixed-core plus page-specific checks, actual browser actions and full-image/native-readable inspection. Referenced method resources and their hashes are bound. Scripts provide measurements and reproduction, not independent approval.

Actual Chrome/Playwright checks covered three complete viewports, 48 ordered visible content blocks and 8 body hrefs, all visible 44px targets, Inter and Footer geometry, functional color, all body navigation intentions, anchor click/Enter/focus/next Tab/direct fragment/no-JS document links, two menus including all eight exits and cross-desktop-breakpoint restoration, and three Cookie entry/cycle/Close/Escape/return paths. Actual image review opened three overviews, 24 native-readable overlapping segments to Footer, five overlay states and three anchor focus states, then separately opened all eight formal PNGs. Formal PNG hashes equal diagnostic equivalents.

Four risk conclusions: (1) The hardest reading distinction—93 wt% minimum versus typical source values—retains its complete qualification and dated official-source list. (2) The most consequential action chain—Products, then buyer-selected Documents and ready-test-context Sample—preserves all preconditions and human-review boundaries; local href records contain empty context and make no preselection or receipt claim. (3) Narrow-screen wrapping preserves Chemours-only TS-6706/R-706 relationship and TS-6706 test subject, separating paint-system metrics from dry-pigment bulk-flow work without comparison graphics. (4) No unresolved page Finding remains. One diagnostic screenshot-helper failure (off-viewport clip without full-page capture) was preserved and fixed; source bytes never changed. No failed check is hidden.

Not tested: native browser 200% zoom, screen readers, real touch hardware or other browser engines; live destinations and official-source refresh; production receiving, email, storage/analytics deployment or Cookie inventory; route/mapping/canonical/hreflang/indexing/Schema. The candidate URL is planning identity only. Publication requires its separate mapping/freshness/implementation decisions; this Gate 3 does not make them. Evidence distinguishes ACTUAL_RUNTIME, STATIC_VISUAL, SOURCE_INSPECTION and LOCAL_SIMULATION. Follow-up owner is project control for Gate review and later authorized technical/development owners for the explicitly untested scope.
`);
const selfPath=review+'/RES-R706_GATE3_EXECUTION_SELF_CHECK_V0.1.md';
write(selfPath,`# RES-R706 Gate 3 execution self-check V0.1

Status: DRAFT_FOR_PROJECT_CONTROL_REVIEW. Outcome: execution scope complete; unresolved required Findings = 0. This is execution self-check, not project-control PASS or user approval.

Frozen source: ${freeze.source.path}
Bytes: ${freeze.source.bytes}
SHA-256: ${freeze.source.sha256}
Frozen at: ${freeze.frozenAt}

| Fixed core | Evidence and execution conclusion |
|---|---|
| Identity | Actual hashes of approved A/B/C/review, current Manifest V0.4, neutral package and dependencies matched before preflight and again before handoff. Formal source matches freeze; 8 PNG dimensions/bytes/hashes were read from actual files. |
| Content and relationships | Three rendered viewports match the approved B-derived 48-block and 8-href ordered baseline in both directions, excluding only editorial element labels. Six modules, four brief items, four test groups and three downstream steps remain complete. |
| Responsive geometry | Actual 1440/768/390 widths match scrollWidth, all visible targets meet 44×44px, Footer bottom matches document height, Inter loaded, margins and functional colors correct. Native-readable viewing found no clipping/collision/unintended gaps. |
| Shared assembly | Neutral Shared Consumer V0.2 only, Resources current, original production Logo references, fixed RFQ, exact Footer and legal/Cookie text. Durable local font/license snapshots; no temporary or business-page dependency. |
| Overlay operations | Actual two-menu Home first focus, Tab and reverse loop, Close/Escape/eight navigation selections, inert/scroll restore and cross-breakpoint close; actual three-cookie focus/cycle/Close/Escape/return. |
| Action boundaries | Anchor click/Enter moves focus to brief H2; direct fragment and no-JS links work. Every body href is recorded locally with empty context. No network requests, Grade inference, R-706 prefill or production receiving claimed. |
| Visual coverage | All eight formal images actually opened. They equal diagnostic PNGs byte-for-byte; 24 original-size segments cover full three-page heights plus three actual anchor-state images. |

| Page-specific risk | Expected / actual / conclusion |
|---|---|
| Source and numeric qualifiers | Three exact official URLs and complete publication/review dates retained. 93 wt% minimum remains distinct from typical values and separate from IKHLAS product assertions. PASS within approved-copy scope. |
| TS-6706 relationship and test subject | Only Chemours pair relationship; evaluation subject TS-6706. Paint-system dimensions and separately reported dry-pigment-flow tests remain fully visible and scoped. No transfer to IKHLAS. PASS. |
| Conditional downstream sequence | Products neutral; Documents requires one buyer-selected Grade and per-Grade document selection rules; Sample requires selected Grade/application/destination/test context and separate confirmation. All limitations retained; no selector, shortlist or result invented. PASS. |
| Independence and candidate identity | No Chemours visual imitation or logos, no recommendation/equivalence/matching. Independence and Last reviewed visible. Candidate URL does not establish route, mapping or indexing. PASS. |

Failure history: one actual diagnostic renderer-helper error was saved under diagnostic_support/failure-*.json. Corrected clip/full-page capture in the helper, then completed fresh diagnostic checks and viewing before preflight. No source revision was required. No unresolved Finding.

Method consumption: design Skill V0.2 input card → computed binding → fresh neutral candidate → actual diagnostic/browser/image preflight → validator PASS → frozen identity → first formal export. Verification Skill V0.2 fixed core plus page-specific risks, separate runtime/source/visual/local-simulation evidence, no cross-page PASS count comparison. Design rationale is in ${out}/design-report.md; measured results in ${evidence}/formal-runtime.json and actual viewing record in formal-visual-observation.json. Asset identities in ${out}/asset-inventory.json.

NOT_APPLICABLE: page forms, FAQ, comparison table, filters, result/success/failure workflow; approved B contains none. Unmeasured: native 200% browser zoom, assistive technology, real touch, alternate engines. Unverified production scope: destinations, source freshness, receiver/prefill/email, analytics/storage/Cookie deployment, route/canonical/hreflang/indexing/Schema. No Gate 4, deployment or publication authorized by this report.
`);
const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:'RES-R706',source:freeze.source,freeze:id(out+'/freeze-record.json'),preflight:id(out+'/preflight-record.json'),inputBinding:id(out+'/input-binding.json'),sharedConsumer:binding.sharedConsumer,dependencies:binding.dependencies,approval_core:{images,reports:[id(out+'/task-input-card.md'),id(out+'/design-report.md'),id(selfPath)]},diagnostic_support:{directory:out+'/diagnostic_support',runtime:id(evidence+'/formal-runtime.json'),formalVisualObservation:id(evidence+'/formal-visual-observation.json'),failureHistory:failureFiles},unresolvedFindings:[],createdAt:new Date().toISOString()};write(out+'/asset-inventory.json',inventory);
const verification={status:'IDENTITIES_READ_BACK_MATCH',source:id(freeze.source.path),images:images.map(a=>({path:a.path,match:id(a.path).sha256===a.sha256})),reportReadback:inventory.approval_core.reports.map(a=>({path:a.path,bytes:fs.readFileSync(a.path).length,match:id(a.path).sha256===a.sha256})),inventory:id(out+'/asset-inventory.json'),unresolvedFindings:[]};write(evidence+'/final-identity-check.json',verification);console.log(JSON.stringify({source:freeze.source,images:images.map(a=>({name:a.path.split('/').at(-1),width:a.width,height:a.height,bytes:a.bytes,sha256:a.sha256})),reports:inventory.approval_core.reports,inventory:id(out+'/asset-inventory.json')},null,2));
