const fs=require('fs'),crypto=require('crypto'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),sharp=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
const root='D:/23MySec/99_workspace/gate3-skill-validation-2026-09-07',cand=root+'/specimen-c',out=root+'/review-c/evidence',copy=JSON.parse(fs.readFileSync(root+'/copy.json')),manifest=JSON.parse(fs.readFileSync(cand+'/assets.json'));
const identity=f=>({bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});
const result={source:identity(cand+'/source.html'),assets:[],viewports:[],network:[]};
const equal=async(a,b)=>{const x=await sharp(a).raw().toBuffer({resolveWithObject:true}),y=await sharp(b).raw().toBuffer({resolveWithObject:true});return x.info.width===y.info.width&&x.info.height===y.info.height&&x.data.equals(y.data)};
const observe=async p=>p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,width:r.width,height:r.height}};const q=document.querySelector('#quantity'),privacy=document.querySelector('.privacy-line'),link=privacy.querySelector('a'),submit=document.querySelector('#submit');return {focus:document.activeElement.id||document.activeElement.tagName,quantity:{...rect(q),value:q.value,error:!document.querySelector('#quantity-error').hidden,aria:q.getAttribute('aria-invalid')},privacy:{...rect(privacy),scrollHeight:privacy.scrollHeight,clientHeight:privacy.clientHeight,overflow:getComputedStyle(privacy).overflow,text:privacy.innerText,inForm:!!privacy.closest('form'),link:rect(link),beforeSubmit:rect(privacy).y+rect(privacy).height<=rect(submit).y},errors:['name','email','quantity'].map(id=>({id,shown:!document.querySelector('#'+id+'-error').hidden,associated:document.querySelector('#'+id).getAttribute('aria-describedby'),text:document.querySelector('#'+id+'-error').textContent})),summary:!document.querySelector('#form-summary').hidden,success:!document.querySelector('#confirmation').hidden,successText:document.querySelector('#confirmation').textContent,values:[...document.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,value:e.value})),scrollWidth:document.documentElement.scrollWidth,width:innerWidth}});
const geometry=async p=>p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,width:r.width,height:r.height}};return {width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,records:[...document.querySelectorAll('.record')].map(e=>({name:e.querySelector('h3').textContent,values:[...e.querySelectorAll('.metric')].map(m=>{const v=m.querySelector('dd');return {metric:m.querySelector('dt').textContent,value:v.textContent,...rect(v),scrollWidth:v.scrollWidth,clientWidth:v.clientWidth,whiteSpace:getComputedStyle(v).whiteSpace,overflow:getComputedStyle(v).overflow}}),note:{text:e.querySelector('.record-note').textContent,...rect(e.querySelector('.record-note')),visible:e.querySelector('.record-note').checkVisibility()}})),sections:[...document.querySelectorAll('main>section,footer')].map(e=>({id:e.id||e.tagName,...rect(e)})),reading:[...document.querySelectorAll('#reading>article,#reading>details')].map(e=>({title:e.querySelector('h3,summary').textContent,text:e.querySelector('p').textContent,open:e.tagName==='ARTICLE'||e.open})),smallTargets:[...document.querySelectorAll('button,a,input,select,textarea,summary')].filter(e=>e.checkVisibility()).map(e=>({id:e.id,tag:e.tagName,...rect(e)})).filter(e=>e.width<44||e.height<44)};});
(async()=>{for(const asset of manifest.assets){const f=cand+'/'+asset.path,meta=await sharp(f).metadata(),actual=identity(f);result.assets.push({path:asset.path,...actual,pixelWidth:meta.width,pixelHeight:meta.height,logicalWidth:asset.logicalWidth,dpr:asset.dpr,bytesMatch:asset.bytes===actual.bytes,hashMatch:asset.sha256===actual.sha256,sourceMatch:asset.sourceSha256===result.source.sha256});}
const b=await chromium.launch({headless:true});result.browser=b.version();
for(const width of [1440,768,390]){const p=await b.newPage({viewport:{width,height:900},deviceScaleFactor:1});await p.route('**/*',r=>{if(!r.request().url().startsWith('file:')){result.network.push(r.request().url());return r.abort()}return r.continue()});await p.goto('file:///'+cand+'/source.html');const v={width,initial:await geometry(p),initialForm:await observe(p)};await p.screenshot({path:out+'/'+width+'-initial.png',fullPage:true});v.initialPixelMatch=await equal(out+'/'+width+'-initial.png',cand+'/'+width+'-initial.png');await p.locator('#comparison').screenshot({path:out+'/'+width+'-comparison.png'});await p.locator('form').screenshot({path:out+'/'+width+'-initial-form.png'});
v.contentMatches=v.initial.records.every((r,i)=>r.name===copy.records[i].name&&r.note.text===copy.notes[i]&&r.values.every((m,j)=>m.metric===copy.metrics[j]&&m.value===copy.records[i].values[j]))&&v.initial.reading.every((s,i)=>s.title===copy.sections[i].title&&s.text===copy.sections[i].text);
for(const s of await p.locator('details summary').all())await s.click();v.expanded=await geometry(p);await p.screenshot({path:out+'/'+width+'-expanded.png',fullPage:true});if(width===390)v.expandedPixelMatch=await equal(out+'/'+width+'-expanded.png',cand+'/390-expanded.png');
await p.locator('#submit').click();v.empty=await observe(p);await p.screenshot({path:out+'/'+width+'-empty.png',fullPage:true});if(width===390)v.invalidPixelMatch=await equal(out+'/'+width+'-empty.png',cand+'/390-invalid.png');await p.locator('form').screenshot({path:out+'/'+width+'-empty-form.png'});
await p.locator('#name').fill('Example Reader');await p.locator('#email').fill('invalid');await p.locator('#quantity').fill('0');await p.locator('#context').fill('Retained first line\nRetained second line');await p.locator('#record').selectOption({label:copy.records[1].name});await p.locator('#submit').click();v.invalidEmail=await observe(p);
await p.locator('#email').fill('reader@example.invalid');v.quantities=[];for(const value of ['','0','-0.25','0.001','1.25']){await p.locator('#quantity').fill(value);await p.locator('#submit').click();v.quantities.push({value,state:await observe(p)});if(value==='0.001')await p.locator('form').screenshot({path:out+'/'+width+'-positive-decimal-form.png'});}
await p.locator('#record').selectOption({label:copy.form.unsure});v.unselect=await p.locator('#record').inputValue();v.privacyClicks=[];for(const mode of ['success','invalid']){if(mode==='invalid'){await p.locator('#quantity').fill('0');await p.locator('#submit').click()}await p.locator('.privacy-line a').click();v.privacyClicks.push({mode,...await p.evaluate(()=>({hash:location.hash,visible:document.querySelector('#privacy').getBoundingClientRect().top<innerHeight}))});}
if(width===390){await p.locator('#name').fill('Example Person');await p.locator('#email').fill('example@example.invalid');await p.locator('#quantity').fill('0.5');await p.locator('#context').fill('');await p.locator('#submit').click();await p.screenshot({path:out+'/390-source-success.png',fullPage:true});v.successPixelMatch=await equal(out+'/390-source-success.png',cand+'/390-success.png');}
if(width!==1440){await p.goto('file:///'+cand+'/source.html');await p.locator('#menu').focus();await p.keyboard.press('Enter');const focus=()=>p.evaluate(()=>({id:document.activeElement.id,tag:document.activeElement.tagName,text:document.activeElement.tagName==='BODY'?'BODY':document.activeElement.textContent.trim(),inside:!!document.activeElement.closest('dialog'),hasFocus:document.hasFocus(),open:document.querySelector('dialog').open,modal:document.querySelector('dialog').matches(':modal'),expanded:document.querySelector('#menu').getAttribute('aria-expanded')}));v.menu={entry:await focus(),forward:[],backward:[]};for(let i=0;i<13;i++){await p.keyboard.press('Tab');v.menu.forward.push(await focus())}await p.locator('#close-menu').focus();for(let i=0;i<8;i++){await p.keyboard.press('Shift+Tab');v.menu.backward.push(await focus())}await p.locator('#close-menu').focus();v.menu.background=await p.evaluate(()=>{document.querySelector('#name').focus();return {active:document.activeElement.id,hit:document.elementFromPoint(5,100).tagName}});await p.mouse.click(5,100);v.menu.afterBackgroundClick=await focus();await p.keyboard.press('Escape');v.menu.escape=await focus();await p.locator('#menu').click();await p.locator('#close-menu').click();v.menu.close=await focus();v.menu.links=[];for(let i=0;i<5;i++){await p.locator('#menu').click();const a=p.locator('#menu-dialog a').nth(i),href=await a.getAttribute('href');await a.click();v.menu.links.push({href,hash:await p.evaluate(()=>location.hash),...await focus()});}await p.goto('file:///'+cand+'/source.html');await p.locator('#menu').click();await p.screenshot({path:out+'/'+width+'-menu.png'});if(width===390)v.menuPixelMatch=await equal(out+'/390-menu.png',cand+'/390-menu.png');}
result.viewports.push(v);await p.close();}
await b.close();fs.writeFileSync(out+'/observations.json',JSON.stringify(result,null,2));console.log(JSON.stringify({source:result.source,assets:result.assets,viewports:result.viewports.map(v=>({width:v.width,contentMatches:v.contentMatches,initialPixelMatch:v.initialPixelMatch,expandedPixelMatch:v.expandedPixelMatch,invalidPixelMatch:v.invalidPixelMatch,successPixelMatch:v.successPixelMatch,menuPixelMatch:v.menuPixelMatch,quantitySizes:[v.initialForm.quantity.width,v.initialForm.quantity.height],emptyFocus:v.empty.focus,emailFocus:v.invalidEmail.focus,quantities:v.quantities.map(q=>({value:q.value,success:q.state.success,focus:q.state.focus})),menu:v.menu?{forward:v.menu.forward,backward:v.menu.backward,background:v.menu.background,escape:v.menu.escape,close:v.menu.close,links:v.menu.links}:null}))},null,2));})();
