const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=__dirname, url='file:///'+path.join(root,'wireframe.html').replaceAll('\\','/');
(async()=>{
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']});
const evidence={renderer:await browser.version(),scale:1,actions:[],exports:[],networkRequests:[],failures:[]};
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
await page.route(/^https?:/,r=>{evidence.networkRequests.push(r.request().url());r.abort()});
async function open(width){await page.setViewportSize({width,height:1000});await page.goto(url);await page.evaluate(()=>document.fonts.ready);}
async function shot(name,state){const p=path.join(root,name+'.png');await page.screenshot({path:p,fullPage:true});const dimensions=await page.evaluate(()=>({width:innerWidth,height:document.documentElement.scrollHeight,scrollWidth:document.documentElement.scrollWidth}));assert(dimensions.scrollWidth<=dimensions.width);evidence.exports.push({path:p,state,...dimensions,scale:1});}
async function crops(prefix,selector){await page.evaluate(()=>scrollTo(0,0));const box=await page.locator(selector).boundingBox();let index=0;for(let y=Math.floor(box.y);y<box.y+box.height;y+=850){await page.screenshot({path:path.join(root,prefix+'-'+(++index)+'.png'),fullPage:true,clip:{x:0,y,width:page.viewportSize().width,height:Math.min(850,Math.ceil(box.y+box.height)-y)}})}}
try{
for(const width of [1440,768,390]){await open(width);await shot('initial-'+width,'initial, sections 2–6 collapsed');await page.locator('details summary').evaluateAll(nodes=>nodes.forEach(n=>n.click()));assert.equal(await page.locator('details[open]').count(),5);evidence.actions.push('Clicked all five disclosures at '+width+'; all opened in document flow.');await shot('expanded-'+width,'all six reading sections visible');if(width===390){await crops('inspect-mobile-expanded-reading','#reading');}if(width===768){await crops('inspect-tablet-comparison','#comparison');}}
await open(390);await page.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Close');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Request review');await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Close');await page.locator('#name').evaluate(e=>e.focus());assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Close');await shot('mobile-menu-390','modal mobile menu open');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Menu');assert.equal(await page.locator('dialog[open]').count(),0);await page.getByRole('button',{name:'Menu',exact:true}).click();await page.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Menu');evidence.actions.push('Mobile menu: actual open, initial Close focus, reverse/forward Tab wrap, rejected focus into underlying form, Escape close and Close button; trigger focus restored.');
await page.locator('#email').fill('invalid-address');await page.locator('#quantity').fill('0');await page.locator('#context').fill('Compare the conditioning notes for this fictional request.');await page.locator('form button').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'name');assert.equal(await page.locator('[aria-invalid=true]').count(),3);assert.equal(await page.locator('#email').inputValue(),'invalid-address');await shot('invalid-submit-390','invalid name/email/quantity with retained input');await crops('inspect-mobile-invalid','#request');evidence.actions.push('Submitted blank name, invalid email, zero quantity; saw three associated errors and summary; focus name; values retained.');
await page.locator('#name').fill('Example Reader');await page.locator('#email').fill('reader@example.test');await page.locator('#quantity').fill('-1');await page.locator('form button').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'quantity');await page.locator('#quantity').fill('0.75');await page.locator('#record').selectOption('1');await page.locator('form button').click();assert.equal(await page.locator('.success').isVisible(),true);assert.equal(await page.locator('#quantity').inputValue(),'0.75');assert.equal(await page.locator('#record').inputValue(),'1');await shot('simulated-success-390','local confirmation with retained values');await crops('inspect-mobile-success','#request');evidence.actions.push('Negative quantity rejected with quantity focus; positive decimal 0.75 accepted with invented valid email and record Beta; displayed local-only confirmation; retained all values; no network submit.');
await open(1440);await crops('inspect-desktop-hero','#overview');await crops('inspect-desktop-comparison','#comparison');await crops('inspect-desktop-form','#request');await crops('inspect-desktop-footer','#privacy');
for(const width of [1440,768,390]){await open(width);const small=await page.locator('a,button,input,select,textarea,summary').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).map(n=>({tag:n.tagName,text:n.textContent||n.id,w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})).filter(n=>n.w<44||n.h<44));assert.deepEqual(small,[]);evidence.actions.push('Measured visible interactive targets at '+width+': all at least 44 × 44 logical px.');if(width===390){await crops('inspect-mobile-hero','#overview');await crops('inspect-mobile-comparison','#comparison');await crops('inspect-mobile-footer','#privacy');await page.evaluate(()=>scrollTo(0,0));await page.getByRole('button',{name:'Menu',exact:true}).click();await page.screenshot({path:path.join(root,'inspect-mobile-menu.png')});}}
}catch(e){evidence.failures.push(e.stack);process.exitCode=1;}finally{fs.writeFileSync(path.join(root,'render-evidence.json'),JSON.stringify(evidence,null,2));await browser.close();console.log(JSON.stringify(evidence,null,2));}
})();
