const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url');const root='D:/23MySec',base=root+'/pages/markets/brazil',out=base+'/04_planning/gate3-pt-v0.1',id='MARKET-BR-PT',neutral=root+'/docs/architecture/gate3-shared-consumer-v0.2';
const identity=path=>({path,bytes:fs.statSync(path).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex')}),write=(p,v)=>fs.writeFileSync(p,typeof v==='string'?v:JSON.stringify(v,null,2));fs.mkdirSync(out+'/dependencies',{recursive:true});fs.mkdirSync(out+'/approval_core',{recursive:true});
const paths={manifest:base+'/'+id+'_CURRENT_GATE_BASELINE_MANIFEST_V0.4.md',A:base+'/04_planning/'+id+'_GATE2_CONTENT_SKELETON_V0.2.md',B:base+'/04_planning/'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md',C:base+'/04_planning/'+id+'_GATE2_CONTENT_CONTRACT_V0.2.md',review:base+'/05_review/'+id+'_GATE2_FULL_COPY_PROJECT_CONTROL_REVIEW_V0.1.md',naturalness:base+'/05_review/'+id+'_GATE2_PTBR_NATURALNESS_REREVIEW_V0.1.md',brief:root+'/docs/page-briefs/MARKET-BR-PT_BRAZIL_PORTUGUESE_BRIEF_V0.2.md',authorization:root+'/docs/architecture/GATE3_EIGHT_PAGE_SERIAL_CONTROL_V1.6.md',approval:root+'/docs/architecture/GATE2_EIGHT_PAGE_USER_APPROVAL_AND_CLOSURE_V1.0.md',baseline:root+'/docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.2.md',agent:root+'/agents/gate3-execution/agent.md',designSkill:root+'/skills/responsive-wireframe-design/SKILL.md',verificationSkill:root+'/skills/layout-interaction-verification/SKILL.md',handoff:root+'/docs/superpowers/specs/2026-09-07-gate3-to-gate4-handoff-contract-v0.1.md'};
const approvedInputs=Object.fromEntries(Object.entries(paths).map(([k,p])=>[k,identity(p)]));for(const [k,h] of Object.entries({A:'12ed2a57c781aa335ced3e181b136644ad678f03cda2da287c308cb620fbe573',B:'895054795f03b2587e8a49ab143cfb59c316ceef9df4d3a40269b8cb8bbed2cb',C:'bb75a6ce6e1e21f7a892b4322878340762182d6c9390be6f333f2c6eba1a9d47',review:'55585531f2006ed7f6e669a68a7bd4deab9367c649fbe6cc7538b094bcc611ca'}))if(approvedInputs[k].sha256!==h)throw Error('Approved identity '+k);
const pkg=JSON.parse(fs.readFileSync(neutral+'/consumer-package.json')),sharedFiles=pkg.files.map(f=>({...identity(neutral+'/'+f.path),role:f.role}));pkg.files.forEach((f,i)=>{if(f.sha256!==sharedFiles[i].sha256)throw Error('Shared identity '+f.path)});
const primary=root+'/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverse=root+'/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg';for(const n of ['Inter-Variable.ttf','Inter-OFL.txt'])fs.copyFileSync(neutral+'/'+n,out+'/dependencies/'+n);
const shared=require(neutral+'/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:pathToFileURL(primary).href,reverseLogoSrc:pathToFileURL(reverse).href,fontSrc:'dependencies/Inter-Variable.ttf'});
write(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',{status:'DIAGNOSTIC_CANDIDATE_NOT_FROZEN',at:new Date().toISOString(),approvedInputs,sharedConsumer:{...identity(neutral+'/consumer-package.json'),version:pkg.version,packageId:pkg.packageId,currentPageId:'MARKET-000'},sharedFiles,owners:Object.fromEntries(Object.entries(pkg.authority).map(([k,p])=>[k,identity(p)])),dependencies:[primary,reverse,out+'/dependencies/Inter-Variable.ttf',out+'/dependencies/Inter-OFL.txt'].map(identity),languageAssembly:{page:'pt-BR',shared:'en',note:'Only language metadata added to generated shared root elements; approved shared text/styles/behavior unchanged.'}});
write(out+'/'+id+'_GATE3_TASK_INPUT_CARD_V0.1.md',`# Brazil Portuguese Gate 3 task input card\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. MARKET-BR-PT; pt-BR; localized Market procurement page; approved planning path /pt-br/markets/brazil/ is not implemented route/canonical/hreflang. Serial G3-8PAGE-SERIAL-01 V1.6 item7 authorizes this page only. Manifest V0.4 + A/B/C V0.2, Brief V0.2, PCR V0.1 and naturalness rereview V0.1; exact hashes in input binding.\n\nBR-PT-01 Hero with one visible English-destination notice → BR-PT-02 three application triplets → BR-PT-03 Documents → BR-PT-04 dated trade owner → BR-PT-05 RFQ. B is sole main copy, including exact accents, English receiver labels and 06/09/2026. Risks: long H1/application/trade labels; document cardinality; language transition; explicit Brazil destination only, no local entity or legal outcome.\n\nNeutral Shared Consumer V0.2, MARKET-000; original approved production SVG paths. Shared copy stays English, marked lang=en; html/main pt-BR. Full1440/768/390 DPR1, Menu768/390, Cookieall3; no page forms/FAQ/selectors/results.\n\nAllowed source/report directory ${out}; design report ${out}/${id}_GATE3_DESIGN_METHOD_REPORT_V0.1.md; self-check ${base}/05_review/${id}_GATE3_EXECUTION_SELF_CHECK_V0.1.md. PT assets isolated from EN. No other business-page template. Stop for independent control review; no Sulfate/Gate4 or approval.\n`);
write(out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md','# Brazil Portuguese Gate 3 design report\n\nDRAFT_FOR_PROJECT_CONTROL_REVIEW. Input card and identity binding established. Diagnostic candidate only; no preflight or formal render claimed.\n');
const blocks=fs.readFileSync(paths.B,'utf8').replace(/<!--[\s\S]*?-->/g,'').trim().split(/\r?\n\s*\r?\n/).map(s=>s.trim()),esc=s=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const inline=s=>esc(s).replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2">$1</a>').replace(/Not sure \/ Need help|Other \/ Not sure|Additional Requirements|Product \/ Grade|Application/g,'<span lang="en">$&</span>');
let html='<nav class="breadcrumb" aria-label="Navegação estrutural">'+inline(blocks.shift())+'</nav>',section=0;
for(let i=0;i<blocks.length;i++){const s=blocks[i];if(/^#{1,2} /.test(s)){if(section)html+='</section>';section++;const h=s.startsWith('# ')?1:2;html+=`<section class="module m${section}" data-module="BR-PT-0${section}"><h${h}>${inline(s.replace(/^#+ /,''))}</h${h}>`;}
else if(s.startsWith('### ')){html+='<div class="applications">';while(blocks[i]?.startsWith('### ')){html+='<article><h3>'+inline(blocks[i].slice(4))+'</h3><p>'+inline(blocks[i+1])+'</p><div class="application-link">'+inline(blocks[i+2])+'</div></article>';i+=3;}i--;html+='</div>';}
else if(s.startsWith('- '))html+='<ul>'+s.split(/\r?\n/).map(x=>'<li>'+inline(x.slice(2))+'</li>').join('')+'</ul>';
else if(/^\[[^\]]+\]\([^)]+\)$/.test(s)){html+='<div class="actions">';while(/^\[[^\]]+\]\([^)]+\)$/.test(blocks[i]||'')){let a=inline(blocks[i]);if(blocks[i].includes('](/request-a-quote/)'))a=a.replace('<a ','<a class="primary" ');html+=a;i++;}i--;html+='</div>';}
else html+='<p'+(s==='Os links desta página levam a conteúdos e formulários disponíveis em inglês.'?' class="language-notice"':'')+'>'+inline(s)+'</p>';}
html+='</section>';
const css=`*{box-sizing:border-box}body{margin:0;color:#334155;background:#fff;font-family:Inter,Arial,sans-serif}main{font-size:17px;line-height:1.7}main .breadcrumb{max-width:1120px;margin:auto;padding:22px 0;font-size:14px}main a{display:inline-flex;align-items:center;min-width:44px;min-height:44px;color:#008078;text-underline-offset:4px}main a:focus-visible{outline:3px solid #008078;outline-offset:3px}main .module{padding:56px max(32px,calc((100% - 1120px)/2));border-top:1px solid #d9e2ec}main .m1,main .m5{background:#f3f7fa}main .m1{padding-top:40px;padding-bottom:44px}main h1,main h2,main h3{color:#062b5b;margin:0 0 22px;line-height:1.2}main h1{font-size:46px;max-width:1020px;letter-spacing:-.025em}main h2{font-size:32px;max-width:950px}main h3{font-size:22px;margin-bottom:16px}main p{max-width:880px;margin:0 0 22px}main .m1>p{font-size:20px;max-width:950px}main .m1 .language-notice{font-size:16px;margin:26px 0 0;padding:16px 0 0;border-top:1px solid #cbd5e1;max-width:950px}main .actions{display:flex;flex-wrap:wrap;gap:16px;margin:26px 0 8px}main .actions a{font-size:16px;font-weight:600;line-height:1.5;padding:12px 20px;min-height:50px;border:1px solid #008078;border-radius:6px;text-decoration:none;justify-content:center;max-width:880px}main .actions .primary{background:#008078;color:#fff}main .applications{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:28px;margin:30px 0}main .applications article{min-width:0;display:flex;flex-direction:column;border-top:2px solid #cbd5e1;padding-top:24px}main .applications p{margin-bottom:16px}main .application-link{margin-top:auto}main .application-link a{font-size:16px;font-weight:600}main ul{max-width:880px;padding-left:24px;margin:24px 0}main li{padding-left:8px;margin:12px 0}@media(max-width:1100px){main .breadcrumb{padding:18px 32px}main .module{padding:44px 32px}main h1{font-size:40px}main .applications{grid-template-columns:1fr;gap:24px}main .applications article{display:grid;grid-template-columns:175px minmax(0,1fr);gap:0 24px}main .application-link{grid-column:2}}@media(max-width:560px){main{font-size:16px;line-height:1.7}main .breadcrumb{padding:16px 20px}main .module{padding:36px 20px}main h1{font-size:34px}main h2{font-size:28px}main h3{font-size:22px}main .m1>p{font-size:18px}main .m1 .language-notice{font-size:16px}main .applications article{display:block}main .actions{gap:12px}main .actions a{width:100%}}`;
const js=`window.localNavigation=[];document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(!a)return;e.preventDefault();const href=a.getAttribute('href');let context={};if(href==='/request-a-quote/')context={source_page_id:'MARKET-BR-PT',destination_country:'Brazil',destination_context_visible_editable:true};if(href==='/request-documents/')context={source_page_id:'MARKET-BR-PT'};window.localNavigation.push({href,context,evidence:'LOCAL_SIMULATION'});});`;
const source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';write(source,'<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Fornecedor de dióxido de titânio para o Brasil | TiO2 Malaysia</title><style>'+shared.style+'\n'+css+'</style></head><body>'+shared.header.replace('<header ','<header lang="en" ')+'<main lang="pt-BR">'+html+'</main>'+shared.footer.replace('<footer ','<footer lang="en" ')+shared.dialog.replace('<dialog ','<dialog lang="en" ')+'<script>'+shared.behavior+'\n'+js+'</script></body></html>');write(out+'/diagnostic_support/build-result.json',{source:identity(source),at:new Date().toISOString()});console.log(JSON.stringify(identity(source)));
