const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out='D:/23MySec/pages/markets/brazil/04_planning/gate3-pt-v0.1',id='MARKET-BR-PT',source=out+'/'+id+'_GATE3_RESPONSIVE_WIREFRAME_V0.1.html',formal=process.argv.includes('--formal'),dest=out+(formal?'/approval_core':'/diagnostic_support/render');fs.mkdirSync(dest,{recursive:true});
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),norm=s=>s.replace(/\s+/g,' ').trim(),log=[],assets=[];function test(name,value,data){log.push({name,status:value?'PASS':'FAIL',data});if(!value)throw Error(name)}
const b=fs.readFileSync(out+'/../'+id+'_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'').trim(),expected=norm(b.replace(/^#{1,3} /gm,'').replace(/^- /gm,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1')),links=[...b.matchAll(/\[([^\]]+)\]\(([^)]+)\)/g)].map(m=>({text:m[1],href:m[2]}));
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});
const save=async(p,w,h,state)=>{const file=dest+'/'+(formal?`${id}_GATE3_${w}_${state.toUpperCase()}_V0.1.png`:`diagnostic-${w}-${state}.png`);await p.screenshot({path:file,fullPage:state==='full'});const buf=fs.readFileSync(file);assets.push({path:file,bytes:buf.length,sha256:hash(file),logicalViewport:{width:w,height:h},physicalPixels:{width:buf.readUInt32BE(16),height:buf.readUInt32BE(20)},dpr:1,state,role:formal?'approval_core':'diagnostic_support'});};
(async()=>{if(formal){const f=JSON.parse(fs.readFileSync(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json'));test('freeze hash',hash(source)===f.source.sha256)}const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking']}),external=[];
try{for(const w of [1440,768,390]){const h=w===390?844:900,c=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1});await c.route(/^https?:/,r=>{external.push(r.request().url());r.abort()});const p=await c.newPage();await p.goto(pathToFileURL(source).href);await ready(p);
test(w+' exact visible Portuguese B',norm(await p.locator('main').innerText())===expected);test(w+' ordered labels and routes',JSON.stringify(await p.locator('main a').evaluateAll(es=>es.map(e=>({text:e.textContent,href:e.getAttribute('href')}))))===JSON.stringify(links));
const geo=await p.evaluate(()=>({width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,targets:[...document.querySelectorAll('a,button')].filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent.trim(),width:r.width,height:r.height}}),clipped:[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return ['hidden','clip'].includes(s.overflow)||s.textOverflow==='ellipsis'}).length}));test(w+' geometry and 44px',geo.width<=w&&geo.clipped===0&&geo.targets.every(t=>t.width>=43.99&&t.height>=43.99),geo);
const rel=await p.evaluate(()=>({modules:[...document.querySelectorAll('main section')].map(e=>e.dataset.module),triplets:[...document.querySelectorAll('.applications article')].map(e=>({heading:e.querySelector('h3').textContent,p:e.querySelectorAll('p').length,href:e.querySelector('a').getAttribute('href')})),notice:document.querySelectorAll('.language-notice').length,noticeText:document.querySelector('.language-notice').textContent,coo:[...document.querySelectorAll('main p')].filter(e=>e.textContent==='O Certificado de Origem está disponível mediante solicitação.').length,date:document.querySelector('.m4').textContent.includes('06/09/2026'),tradeHref:document.querySelector('.m4 a').getAttribute('href'),rfqCount:document.querySelectorAll('.m5 li').length,controls:document.querySelectorAll('main input,main select,main button,main form,main details,main table').length,language:document.documentElement.lang,mainLanguage:document.querySelector('main').lang,sharedLanguages:['header','footer','dialog'].map(s=>document.querySelector(s).lang),canonical:document.querySelectorAll('link[rel=canonical],link[hreflang]').length}));
test(w+' PT relationships and language boundaries',rel.modules.join()==='BR-PT-01,BR-PT-02,BR-PT-03,BR-PT-04,BR-PT-05'&&rel.triplets.length===3&&rel.triplets.every((x,i)=>x.p===1&&x.href===['/applications/titanium-dioxide-for-coatings/','/applications/titanium-dioxide-for-plastics/','/applications/titanium-dioxide-for-masterbatch/'][i])&&rel.notice===1&&rel.noticeText==='Os links desta página levam a conteúdos e formulários disponíveis em inglês.'&&rel.coo===1&&rel.date&&rel.tradeHref==='/resources/brazil-titanium-dioxide-anti-dumping-duty/'&&rel.rfqCount===5&&rel.controls===0&&rel.language==='pt-BR'&&rel.mainLanguage==='pt-BR'&&rel.sharedLanguages.every(x=>x==='en')&&rel.canonical===0,rel);
test(w+' shared current and functional Teal',await p.evaluate(()=>[...document.querySelectorAll('.desktopNav [aria-current],.mobileNav [aria-current]')].every(e=>e.textContent==='Markets')&&getComputedStyle(document.querySelector('main a')).color==='rgb(0, 128, 120)'&&getComputedStyle(document.querySelector('main .primary')).backgroundColor==='rgb(0, 128, 120)'));
await save(p,w,h,'full');if(!formal)for(let y=0,n=1;y<geo.height;y+=750,n++)await p.screenshot({path:dest+`/clip-${w}-${String(n).padStart(2,'0')}.png`,fullPage:true,clip:{x:0,y,width:w,height:Math.min(900,geo.height-y)}});
for(let i=0;i<links.length;i++){await p.locator('main a').nth(i).click();const a=await p.evaluate(()=>window.localNavigation.at(-1)),href=links[i].href;test(w+' local main link '+i,a.href===href&&!href.includes('?')&&!href.startsWith('/pt-br/')&&(href!=='/request-a-quote/'||(a.context.source_page_id==='MARKET-BR-PT'&&a.context.destination_country==='Brazil'&&a.context.destination_context_visible_editable&&Object.keys(a.context).length===3))&&(href!=='/request-documents/'||(a.context.source_page_id==='MARKET-BR-PT'&&Object.keys(a.context).length===1)),a);}
await p.evaluate(()=>scrollTo(0,0));if(w<1101){const toggle=p.locator('.menuButton');await toggle.click();test(w+' first menu focus',await p.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement));await save(p,w,h,'menu');test(w+' inert and scroll lock',await p.evaluate(()=>['main','footer','.logoLink','.headerRfq'].every(s=>document.querySelector(s).inert)&&document.body.style.overflow==='hidden'));
await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');test(w+' forward menu loop',await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');test(w+' reverse menu loop',await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement));await p.mouse.move(w-5,h-10);await p.mouse.wheel(0,300);await p.waitForTimeout(100);test(w+' wheel locked',await p.evaluate(()=>scrollY===0));await p.keyboard.press('Escape');test(w+' Escape return and restore',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''&&document.activeElement===document.querySelector('.menuButton')));await p.mouse.wheel(0,300);await p.waitForTimeout(100);test(w+' wheel restored',await p.evaluate(()=>scrollY>0));await p.evaluate(()=>scrollTo(0,0));await toggle.click();await toggle.click();test(w+' Close exit',await p.locator('.mobileNav').evaluate(e=>e.hidden));
for(let i=0;i<8;i++){await toggle.click();await p.locator('.mobileNav a').nth(i).click();test(w+' select restores '+i,await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&['main','footer','.logoLink','.headerRfq'].every(s=>!document.querySelector(s).inert)&&document.body.style.overflow===''));}
await toggle.click();await p.setViewportSize({width:1440,height:h});await ready(p);test(w+' desktop breakpoint exit',await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.body.style.overflow===''));await p.setViewportSize({width:w,height:h});await ready(p);}
await p.locator('#cookie-trigger').click();await ready(p);test(w+' Cookie first focus',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await save(p,w,h,'cookie');test(w+' Cookie geometry and Teal',await p.locator('.cookie-actions>*').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>=44&&r.height>=44&&s.color==='rgb(0, 128, 120)'&&s.borderTopColor==='rgb(0, 128, 120)'})));
await p.keyboard.press('Shift+Tab');test(w+' Cookie reverse loop',await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');test(w+' Cookie forward loop',await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.locator('.cookie-layer a').click();test(w+' Cookie policy local',(await p.evaluate(()=>window.localNavigation.at(-1))).href==='/cookie-policy/');await p.locator('[data-cookie-close]').click();await ready(p);test(w+' Cookie close return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await p.locator('#cookie-trigger').click();await p.keyboard.press('Escape');await ready(p);test(w+' Cookie Escape return',await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement));await c.close();}
test('no external request',external.length===0,external);fs.writeFileSync(dest+'/runtime.json',JSON.stringify({status:'PASS',at:new Date().toISOString(),source:{path:source,bytes:fs.statSync(source).size,sha256:hash(source)},browser:browser.version(),log,assets},null,2));console.log(JSON.stringify({status:'PASS',source:hash(source),assets:8}));
}catch(e){fs.writeFileSync(dest+'/failure-'+Date.now()+'.json',JSON.stringify({status:'FAIL',error:e.stack,log},null,2));throw e}finally{await browser.close()}})();
