const fs=require('fs'),crypto=require('crypto');const out='D:/23MySec/pages/markets/brazil/04_planning/gate3-pt-v0.1',id='MARKET-BR-PT',review='D:/23MySec/pages/markets/brazil/05_review',evidence=review+'/'+id+'_GATE3_EXECUTION_EVIDENCE_V0.1',read=p=>JSON.parse(fs.readFileSync(p)),ident=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));fs.mkdirSync(evidence,{recursive:true});
const formalPath=evidence+'/formal-runtime.json';fs.renameSync(out+'/approval_core/runtime.json',formalPath);const r=read(formalPath),d=read(out+'/diagnostic_support/render/runtime.json'),f=read(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json'),b=read(out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json');
function verify(v){if(!v||typeof v!=='object')return;if(v.path&&v.sha256){const a=ident(v.path);if(a.sha256!==v.sha256.toLowerCase()||(v.bytes!=null&&a.bytes!==v.bytes))throw Error('Identity mismatch '+v.path)}for(const x of Object.values(v))if(typeof x==='object')verify(x)}verify(b);verify(f);verify(r.source);verify(r.assets);if(r.status!=='PASS')throw Error('Runtime failed');
const comparisons=r.assets.map(a=>({formal:ident(a.path),diagnostic:d.assets.find(x=>x.state===a.state&&x.logicalViewport.width===a.logicalViewport.width),identical:a.sha256===d.assets.find(x=>x.state===a.state&&x.logicalViewport.width===a.logicalViewport.width).sha256}));if(comparisons.some(x=>!x.identical))throw Error('Formal image changed from native-viewed diagnostic');
save(evidence+'/formal-visual-observation.json',{at:new Date().toISOString(),role:'EXECUTION_SELF_CHECK',source:f.source,actualOpenedFormalAssets:r.assets,comparisons,nativeReadableCoverage:ident(out+'/diagnostic_support/preflight-visual-observation.json'),result:'Eight formal images opened. Each has identical bytes to the corresponding diagnostic image; the 19 actually opened native clips therefore cover the unchanged formal full-page pixels. Full-page overviews supplement, not replace, native readable inspection.',unresolvedFindings:[]});
const report=out+'/'+id+'_GATE3_DESIGN_METHOD_REPORT_V0.1.md',self=review+'/'+id+'_GATE3_EXECUTION_SELF_CHECK_V0.1.md';
fs.writeFileSync(report,`# Brazil Portuguese Gate 3 design method report

DRAFT_FOR_PROJECT_CONTROL_REVIEW. MARKET-BR-PT, pt-BR, G3-8PAGE-SERIAL-01 item 7 only. This is execution output, not independent review or Gate approval. Planning path /pt-br/markets/brazil/ does not establish a live route, canonical or hreflang.

The task input card and actual input binding preceded the fresh candidate. Manifest V0.4, approved A/B/C V0.2, Brief V0.2, Gate 2 review and Portuguese naturalness rereview are bound with exact bytes/SHA-256. The unchanged common governance inputs read in this execution session were reused under the root rule. Agent V0.2 and responsive-wireframe-design V0.2 supplied the input/relationship/diagnostic/preflight/freeze method; layout-interaction-verification V0.2 supplied the separate core-and-risk self-check. Exact method identities are in the input binding.

| Approved module | Design decision and preserved relationship |
|---|---|
| BR-PT-01 | Full long Portuguese H1 and introduction; RFQ primary, Products secondary. One English-destination notice follows the actions and remains ordinary visible copy. |
| BR-PT-02 | Three complete application heading/body/action groups. Desktop columns become tablet label/body rows and mobile stacks. General product-review paragraph remains outside the last group. |
| BR-PT-03 | Grade/document conditions remain continuous prose: one selected grade, multiple document types, unknown-grade before-start option but selection before submit, and separate grade requests when individual type mapping is needed. Approved COO sentence retained once. |
| BR-PT-04 | Full dated handoff to the Brazil trade Resource, exactly 06/09/2026. No measures, rates or legal conclusions added. Long action wraps naturally on Mobile. |
| BR-PT-05 | Exact English receiving-field names remain in Portuguese context; five preparation bullets and after-submit text precede the final RFQ. No page form or result state. |

The page was generated from neutral Shared Consumer V0.2 with currentPageId=MARKET-000, not another business page. Original approved production SVGs remain direct references; the font and license have durable page-local copies with source identities. Current shared English Header/Footer/Cookie text, styles and behavior are retained. Their roots carry lang=en; html/main use pt-BR and English receiving labels carry lang=en. No unapproved shared translation was introduced. Functional main links, outline controls, focus rings and solid primary CTA use #008078 under the accessibility addendum; shared navigation retains its own contract.

The diagnostic full pages, 19 overlapping native readable clips, two menu images and three Cookie images were actually opened. Browser measurements and interactions passed before the preflight record and checker returned PASS_FOR_FORMAL_RENDER. Frozen at ${f.frozenAt}; source ${f.source.bytes} bytes, SHA-256 ${f.source.sha256}. The freeze bound approved inputs, shared files, durable dependencies and the preflight hash while approval_core was empty. Only then were eight formal PNGs first generated. All eight were opened; all match the inspected diagnostic pixels byte-for-byte. Asset inventory records full dimensions and hashes.

No design/runtime Finding or source revision occurred. One image-tool batch exceeded output context; the affected clips were subsequently reopened in smaller successful batches and were not counted before that. Detailed measurements, native clips and this tooling note are diagnostic_support. Frozen source, eight PNGs, binding/preflight/freeze, inventory and final reports are approval_core.

Unverified: production routes/canonical/hreflang/indexing/Schema, real receiving/prefill and editable Brazil destination, real mail/submission, live cookie inventory, Resource publication freshness, native 200% browser zoom, assistive-technology language pronunciation, physical touch devices and non-Chrome engines. Only local navigation intent/context was simulated; no external requests were sent. The separate execution self-check gives acceptance scope and four risk conclusions. Stop for project-control review; no Sulfate or Gate 4.
`);
fs.writeFileSync(self,`# MARKET-BR-PT Gate 3 execution self-check V0.1

DRAFT_FOR_PROJECT_CONTROL_REVIEW. Execution self-check only; not project-control PASS or user approval. Frozen source: ${f.source.path}; ${f.source.bytes} bytes; SHA-256 ${f.source.sha256}. Checked in Chrome ${r.browser}, logical 1440×900, 768×900 and 390×844, DPR 1. Formal full-page heights are 3606, 4368 and 5727 px.

| Fixed core | Actual evidence and conclusion |
|---|---|
| Frozen identity | SOURCE_INSPECTION: actual approved A/B/C/review/Brief/authorization/method/shared owner and dependency hashes checked before preflight, freeze and handoff. Formal source stayed unchanged. Freeze preceded first formal generation. PASS within this local artifact combination. |
| Content and relationships | ACTUAL_RUNTIME: normalized visible main text equals the complete approved B bidirectionally at all three widths; ordered link labels/hrefs equal B. Five modules, three application triplets, notice once, COO once, date, five RFQ bullets and no invented controls verified. STATIC_VISUAL: all copy read in native clips. PASS. |
| Responsive geometry | ACTUAL_RUNTIME: no horizontal overflow or clipping containers; all visible action targets at least 44×44. STATIC_VISUAL: all module boundaries, wrapping, actions and footer viewed without collisions or abnormal gaps. PASS. |
| Shared assembly | SOURCE_INSPECTION and ACTUAL_RUNTIME: neutral V0.2, Markets current, fixed RFQ, approved primary/reverse SVGs, legal/footer/consent inheritance, functional Teal. English shared roots with Portuguese page metadata preserve owner copy. PASS. |
| Overlay operation | ACTUAL_RUNTIME: both menus open with Home focus; forward/reverse focus loop, Esc/Close, all eight selection exits, inert/background restoration, actual wheel lock/unlock and desktop breakpoint close passed. All three Cookie dialogs: first Close focus, loop both directions, policy local href, Close/Esc return focus passed. STATIC_VISUAL: all five formal states opened. PASS. |
| Action boundary | LOCAL_SIMULATION: all main hrefs recorded without query or invented Portuguese destination. RFQ records only source_page_id=MARKET-BR-PT plus approved Brazil destination context/visible-editable requirement; Documents records source_page_id only. This is not actual receiver acceptance. No external request. PASS for local intent only. |
| Complete visual coverage | STATIC_VISUAL: eight formal assets opened; byte-identical diagnostics provide 19 actually opened overlapping native clips through footer at three widths. Formal images and source identities read back. PASS. |

Four risk conclusions:

1. Hardest reading: BR-PT-03 document cardinality and BR-PT-04 long trade wording. Native 390 clips 04–06 show every condition, exact 06/09/2026 and wrapped long action; desktop/tablet native clips preserve them. No shortening or invented legal outcome.
2. Most failure-prone operation: shared menu/Cookie exit and focus restoration. Actual keyboard, pointer, wheel and resize checks passed; all five formal state images are readable. Page input, validation/error and submission states are NOT_APPLICABLE because approved B/C provide no page form. Unknown-grade instructions remain prose; receiving-form behavior is untested.
3. Riskiest responsive conversion: the three application triplets change from columns to tablet rows and mobile stacks. Ordered titles, full paragraphs and matching application links remain attached; general product paragraph remains separate. Long Portuguese H1 and action labels wrap without truncation. The sole English-target notice and exact English receiver names stay visible; lang attributes do not prove screen-reader pronunciation.
4. Unresolved Findings: 0. Not tested: native 200% browser zoom, assistive technology, real touch hardware, other browser engines; production route/canonical/hreflang/indexing/Schema, real RFQ/Documents/prefill/editable destination and email, live consent technology inventory, and first-publication Resource freshness. Future implementation and owner verification retain these responsibilities. No claim of production readiness or trade conclusion is made.

Page-specific expectations were taken from the actual Brief/A/B/C and naturalness rereview: Malaysia origin does not imply a Brazil entity; English targets are disclosed exactly once; approved COO scope is not expanded; date belongs to the Resource; product/application/Grade selections are not preselected. Source/content/visual evidence supports these bounds. Tables, FAQ, page selectors, submission feedback and content media are NOT_APPLICABLE. No fabricated states were exported.

Evidence: formal-runtime.json and formal-visual-observation.json in ${evidence}; detailed preflight runtime, 19 clips, five states, checker result and observation in ${out}/diagnostic_support. The inventory gives all exact core file identities. No design/runtime failure occurred; an image-output context truncation was resolved by actual smaller-batch viewing and documented. No prior evidence was overwritten to hide a failure. Checks are coverage evidence, not a cross-page score. Source, reports and assets have been read/opened; submit to independent control review and stop.
`);
const records=['TASK_INPUT_CARD','INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD','DESIGN_METHOD_REPORT'].map(n=>({...ident(out+'/'+id+'_GATE3_'+n+'_V0.1.'+(['INPUT_BINDING','PREFLIGHT_RECORD','FREEZE_RECORD'].includes(n)?'json':'md')),role:'approval_core'}));records.push({...ident(self),role:'approval_core'});
const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:id,language:'pt-BR',planningPath:'/pt-br/markets/brazil/',source:{...f.source,role:'approval_core'},formalAssets:r.assets,records,sharedConsumer:b.sharedConsumer,dependencies:b.dependencies,diagnosticSupport:{design:out+'/diagnostic_support',execution:evidence},freezeAt:f.frozenAt,unresolvedFindings:[],limitations:['Local wireframe and local navigation intent only; no production route/canonical/hreflang or receiver verification.','No native 200% zoom, assistive technology, real touch device or other-engine coverage.']};save(out+'/'+id+'_GATE3_ASSET_INVENTORY_V0.1.json',inventory);verify(inventory);verify(f);verify(b);save(evidence+'/final-identity-check.json',{at:new Date().toISOString(),status:'PASS',source:f.source,formalAssetsVerified:r.assets.length,diagnosticPixelMatches:comparisons.every(x=>x.identical),reportsAndRecordsVerified:records.length,unresolvedFindings:[]});console.log(JSON.stringify({source:f.source,inventory:out+'/'+id+'_GATE3_ASSET_INVENTORY_V0.1.json',self,report,assets:r.assets.map(a=>({path:a.path,bytes:a.bytes,dimensions:a.physicalPixels}))},null,2));
