const fs=require('fs'),crypto=require('crypto'),cp=require('child_process');
const out='D:/23MySec/pages/markets/brazil/04_planning/gate3-pt-v0.1',id='MARKET-BR-PT',j=p=>JSON.parse(fs.readFileSync(p)),ident=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2));
const bindingPath=out+'/'+id+'_GATE3_INPUT_BINDING_V0.1.json',b=j(bindingPath),runtimePath=out+'/diagnostic_support/render/runtime.json',r=j(runtimePath);
function verify(v){if(!v||typeof v!=='object')return;if(v.path&&v.sha256){const a=ident(v.path);if(a.sha256!==v.sha256.toLowerCase()||(v.bytes!=null&&a.bytes!==v.bytes))throw Error('Identity changed: '+v.path)}for(const x of Object.values(v))if(typeof x==='object')verify(x)}verify(b);verify(r.source);if(r.status!=='PASS'||r.log.some(x=>x.status!=='PASS'))throw Error('Runtime failed');if(fs.readdirSync(out+'/approval_core').length)throw Error('Formal assets exist before freeze');
const visualPath=out+'/diagnostic_support/preflight-visual-observation.json',clips=fs.readdirSync(out+'/diagnostic_support/render').filter(n=>n.startsWith('clip-')).map(n=>ident(out+'/diagnostic_support/render/'+n));
save(visualPath,{at:new Date().toISOString(),observerRole:'EXECUTION_SELF_CHECK',source:r.source,status:'PASS',actualOpenedFullOverviews:r.assets.filter(a=>a.state==='full'),actualOpenedNativeClips:clips,actualOpenedStates:r.assets.filter(a=>a.state!=='full'),observations:['All five approved modules and complete footer read at 1440/768/390; 19 overlapping native clips inspected.','Portuguese long headings/actions wrap without truncation. The English-destination notice appears once and is visible after the hero actions.','Application heading/body/action relationships remain clear in desktop columns, tablet rows and mobile stacks.','Documents conditions, 06/09/2026 trade review date, RFQ five-item preparation and after-submit text are complete.','Two menu and three Cookie images opened; all actions and current Markets state visible; no invented page controls.'],unresolvedFindings:[],inspectionToolNote:'An earlier image batch exceeded tool output context; its clips were subsequently reopened in smaller batches and are included only after successful viewing.'});
const preflightPath=out+'/'+id+'_GATE3_PREFLIGHT_RECORD_V0.1.json';save(preflightPath,{status:'PASS_FOR_FORMAL_RENDER',at:new Date().toISOString(),candidate:r.source,approvedInputs:b.approvedInputs,sharedConsumer:b.sharedConsumer,sharedFiles:b.sharedFiles,dependencies:b.dependencies,checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks','functionalColors'].map(k=>[k,'PASS'])),formalExportsGenerated:false,browser:r.browser,viewports:[1440,768,390],evidenceTypes:['SOURCE_INSPECTION','ACTUAL_RUNTIME','STATIC_VISUAL','LOCAL_SIMULATION'],evidence:{runtime:ident(runtimePath),visual:ident(visualPath)},unresolvedFindings:[]});
const checker=cp.spawnSync(process.execPath,['D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs',preflightPath],{encoding:'utf8'});save(out+'/diagnostic_support/preflight-checker-result.json',{at:new Date().toISOString(),exitCode:checker.status,stdout:checker.stdout,stderr:checker.stderr});if(checker.status!==0)throw Error(checker.stdout+checker.stderr);
verify(b);verify(r.source);const frozen={status:'FROZEN',frozenAt:new Date().toISOString(),source:ident(r.source.path),approvedInputs:b.approvedInputs,sharedConsumer:b.sharedConsumer,sharedFiles:b.sharedFiles,dependencies:b.dependencies,preflight:ident(preflightPath),inputBinding:ident(bindingPath),formalExportsExistedAtFreeze:false};save(out+'/'+id+'_GATE3_FREEZE_RECORD_V0.1.json',frozen);console.log(JSON.stringify(frozen.source));
