const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});
const freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json')),ex=JSON.parse(fs.readFileSync(out+'/approval_core/export-inventory.json')),run=JSON.parse(fs.readFileSync(out+'/diagnostic_support/formal-runtime-checks.json'));
const report=out+'/DOC-COO_GATE4_VISUAL_DIRECTION_AND_METHOD_REPORT_V0.1.md',self='D:/23MySec/pages/documents/certificate-of-origin/05_review/DOC-COO_GATE4_EXECUTION_SELF_CHECK_V0.1.md';
const obs={hero:'完整Header、面包屑、长H1、两段开场、Product Hub及主请求可见。Mobile四行H1完整，无缩短。',comparison:'三类完整等权、两字段与各名称对应；Desktop三列、Tablet三记录双字段。结论与官方引文完整。','comparison-1':'Mobile标题、引导和第一类全部字段完整原生读回。','comparison-2':'Mobile第二类名称两行及When/What完整，无截断。','comparison-3':'Mobile第三类全部字段及结论/官方链接完整。','context-and-traceability':'四项编号和完整上下文均可读，Country/Region区别及单据一致性保留；下方traceability标题、两段完整。Mobile1661px原生读回。',prepare:'五项完整准备清单、未知上下文、one Grade/multiple types、提交前选Grade说明完整；主请求、人工审查限制及Hub可读。','official-source':'完整链接标签、10 October2025、5 January2026、Last reviewed7 September2026及特定订单/装运限制全部可读。',footer:'完整共享反白Logo、描述、栏目、RFQ、法律与版权；实际存在Cookie Settings白色返回焦点环。原export标normal有误，应读作Footer with returned Cookie focus。','primary-hover':'真实主请求hover增加下划线，保留白字Teal填充；周边正文清楚。','official-source-hover':'FAIL COO-G4-AUTHOR-01：真实hover浅色背景绘制覆盖前一行正文；390多行片段还彼此遮挡，不能作为合格状态。','official-source-focus':'FAIL COO-G4-AUTHOR-01：390真实keyboard焦点环穿过上下相邻正文，多行padding的外环边界不可接受。','comparison-guidance-hover':'768实际来源hover、上下结论均可定位；本图单行来源未见同等明显覆盖，但与Official Source共享inline-padding风险，需共同回归。','document-hub-focus':'Hub真实完整Teal外环，标签和邻接上下文均清楚；其下正常Official Source全文可读。','menu-focus':'Documents当前项与真实白色内侧焦点框同时可见，所有菜单项/Close/底部RFQ可读。遮住背景内容是展开菜单状态；背景inert另有运行证据。','cookie-focus':'共享Cookie标题、全文、Close和Policy完整；Close真实Teal焦点环，Mobile两按钮全宽；背景遮罩不作为前景对比面。'};
const checks=[...freeze.inputs,...freeze.dependencies,...ex.assets].map(x=>({path:x.path,bytesMatch:fs.statSync(x.path).size===x.bytes,sha256Match:sha(x.path)===x.sha256}));if(checks.some(x=>!x.bytesMatch||!x.sha256Match))throw Error('Identity drift');
const readback=ex.assets.map(x=>{const role=path.basename(x.path).replace(/^\d+-/,'').replace('.png',''),b=fs.readFileSync(x.path);if(!obs[role]||b.readUInt32BE(16)!==x.pixelWidth||b.readUInt32BE(20)!==x.pixelHeight)throw Error('Invalid readback');return{...id(x.path),sourceFreeze:freeze.freezeId,evidenceType:'STATIC_VISUAL',method:'Individually opened using tools.view_image(detail=original) after formal export; entire region actually inspected. Maximum native height1661px.',observation:obs[role],actualStateCorrection:role==='footer'?'Footer with visible returned Cookie Settings focus, not pure normal':null,pixelWidth:x.pixelWidth,pixelHeight:x.pixelHeight};});
fs.writeFileSync(out+'/diagnostic_support/visual-readback.json',JSON.stringify({date:new Date().toISOString(),observer:'gate4_design / AUTHOR',sourceFreeze:freeze.freezeId,status:'AUTHOR_VISUAL_FAIL_REQUIRES_REVISION',formal:readback,preflight:{count:7,eachActuallyOpened:true,record:'approval_core/preflight-record.json'},note:'32 formal images read, including rejected states. Automatic checks did not detect overlap. Independent review pending.'},null,2));
const findings={date:new Date().toISOString(),status:'AUTHOR_VISUAL_FAIL_REQUIRES_REVISION',sourceFreeze:freeze.freezeId,pageFindings:[{id:'COO-G4-AUTHOR-01',severity:'MAJOR',status:'OPEN',location:'#coo-02 a / #coo-06 a long inline official links',observed:'Official Source hover backgrounds cover adjacent prose at1440/768/390;390 keyboard outline crosses adjacent lines. Inherited vertical14px padding creates48px fragments inside27.2px lines.',evidence:['approval_core/1440-official-source-hover.png','approval_core/768-official-source-hover.png','approval_core/390-official-source-hover.png','approval_core/390-official-source-focus.png'],missedBy:'Preflight only visually inspected normal content. Actual contrast/target rectangles/fragment-center hit-tests cannot prove neighboring text visibility or hit-boundary isolation.',disposition:'Keep frozen V0.1 and all evidence; wait for independent review full findings, then parent-directed new version.'},{id:'COO-G4-AUTHOR-02',severity:'EVIDENCE_METADATA',status:'ERRATUM_RECORDED',location:'approval_core/{1440,768,390}-footer.png',observed:'export-inventory state normal; PNGs actually show returned Cookie Settings focus.',disposition:'Frozen export retained. visual-readback corrects actual state; these are not pure normal screenshots.'}],sharedObservations:[{id:'COO-G4-SHARED-OBS-01',observed:'Menu open -> Desktop closes/restores background but activeElement BODY.',disposition:'InheritedConsumerV0.2; no page behavior fork and no claim of visible-focus preservation on this path.'}],toolEvents:[{id:'COO-G4-TOOL-01',observed:'First five-image preflight read response exceeded tool output context.',resolution:'No observation claimed from truncated response; all seven images reopened in smaller batches before freeze.'},{id:'COO-G4-TOOL-02',observed:'Lookup of prior measure-rules.cjs path absent.',resolution:'Listed actual diagnostic directory; read measure-visual-roles.cjs and adapted tooling selectors locally.'}],preflightAutomaticErrors:run.errors.length,formalAutomaticErrors:run.errors.length,authorVisualFail:true,candidateRevisionsAfterFreeze:0,history:'G3 and Poland IR01 evidence untouched. No failed screenshot removed or overwritten.'};
fs.writeFileSync(out+'/diagnostic_support/findings-and-tool-events.json',JSON.stringify(findings,null,2));
for(const p of[report,self]){const s=fs.readFileSync(p,'utf8');if(!s.includes(freeze.freezeId)||!s.includes('AUTHOR_VISUAL_FAIL_REQUIRES_REVISION'))throw Error('Report binding/status missing');}
fs.writeFileSync(out+'/diagnostic_support/final-receipt.json',JSON.stringify({date:new Date().toISOString(),status:'AUTHOR_DELIVERY_COMPLETE_WITH_VISUAL_FAILURE / DRAFT_FOR_PROJECT_CONTROL_REVIEW',freeze:id(out+'/approval_core/source-freeze.json'),exportInventory:id(out+'/approval_core/export-inventory.json'),reportsReadBack:[id(report),id(self)],identityChecks:checks,formalAssets:ex.assets.length,formalPngsOpened:readback.length,preflightPngsOpened:7,immutableCombination:true,scope:'V0.1 failed candidate preserved. Independent review and parent-directed revision pending. No Gate5/production.'},null,2));
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);}
const inv=out+'/approval_core/asset-inventory.json',files=walk(out).filter(p=>p!==inv).map(p=>({...id(p),role:p.includes('/approval_core/')?'approval_core':p.includes('/diagnostic_support/')?'diagnostic_support':p.includes('/dependencies/')?'runtime_dependency':'source_or_direction'}));
fs.writeFileSync(inv,JSON.stringify({date:new Date().toISOString(),pageId:'DOC-COO',freezeId:freeze.freezeId,status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW / AUTHOR_VISUAL_FAIL_REQUIRES_REVISION',source:freeze.dependencies[0],freeze:id(out+'/approval_core/source-freeze.json'),exportInventory:id(out+'/approval_core/export-inventory.json'),selfCheck:id(self),files,note:'Excludes own bytes to avoid hash recursion. Frozen source/dependencies and32PNG unchanged; failures retained. Reports are author findings, not approval.'},null,2));
if(JSON.parse(fs.readFileSync(inv)).files.some(x=>sha(x.path)!==x.sha256))throw Error('Final drift');console.log(JSON.stringify({inventory:id(inv),report:id(report),selfCheck:id(self),formalPngs:readback.length,allPngs:files.filter(x=>x.path.endsWith('.png')).length,identityChecks:checks.length,files:files.length,status:'AUTHOR_VISUAL_FAIL_REQUIRES_REVISION'}));
