const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),root='D:/23MySec',mode=process.argv[2]||'preflight';
const target=out+'/DOC-COO_GATE4_VISUAL_SAMPLES_V0.1.html',g3=root+'/pages/documents/certificate-of-origin/04_planning/gate3-v0.1/DOC-COO_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const evidence=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/preflight';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});
const records=[],assets=[],errors=[],norm=s=>s.replace(/\s+/g,' ').replace(/\s+([.,;:])/g,'$1').trim();
function check(name,pass,data,type='ACTUAL_RUNTIME'){records.push({name,pass:!!pass,evidenceType:type,data});if(!pass)errors.push(name);}
const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);
const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{let x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function metrics(loc){return loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();function surface(node){while(node){let v=getComputedStyle(node).backgroundColor;if(v!=='rgba(0, 0, 0, 0)'&&v!=='transparent')return v;node=node.parentElement;}return'rgb(255, 255, 255)';}return{text:e.innerText,href:e.getAttribute('href'),fg:s.color,bg:surface(e),outline:s.outlineColor,outlineStyle:s.outlineStyle,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:surface(parseFloat(s.outlineOffset)>=0?e.parentElement:e),border:s.borderTopColor,borderWidth:parseFloat(s.borderTopWidth),font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,width:r.width,height:r.height,x:r.x,y:r.y,focus:e.matches(':focus-visible'),hover:e.matches(':hover'),textDecoration:s.textDecorationLine,background:s.backgroundColor};});}
async function keyboardFocus(page,loc){await page.mouse.move(0,0);await loc.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return loc.evaluate(e=>e===document.activeElement&&e.matches(':focus-visible'));}
async function controls(page,selector,label,w){let list=page.locator(selector);for(let i=0;i<await list.count();i++){let loc=list.nth(i);if(!await loc.isVisible())continue;await loc.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.evaluate(()=>document.activeElement.blur());let normal=await metrics(loc);let normalRatio=normal.text.trim()?contrast(normal.fg,normal.bg):null;check(`${w}/${label}/${i}/normal`,normal.width>=44&&normal.height>=44&&(!normalRatio||normalRatio>=4.5),{...normal,textContrast:normalRatio});await loc.hover();let hover=await metrics(loc);let hoverRatio=hover.text.trim()?contrast(hover.fg,hover.bg):null;check(`${w}/${label}/${i}/hover`,hover.hover&&hover.width===normal.width&&hover.height===normal.height&&(!hoverRatio||hoverRatio>=4.5),{...hover,textContrast:hoverRatio});let reached=await keyboardFocus(page,loc),focus=await metrics(loc);let focusRatio=contrast(focus.outline,focus.outlineBg);check(`${w}/${label}/${i}/keyboard`,reached&&focus.outlineWidth>=3&&focusRatio>=3,{...focus,outlineContrast:focusRatio});}}
async function shot(page,w,name,{selector,endSelector,fromTop=false,state='normal',focusSelector,hoverSelector}={}){
 let dest=evidence+'/'+w+'-'+name+'.png';if(fs.existsSync(dest))throw Error('Refuse overwrite '+dest);
 if(focusSelector)await keyboardFocus(page,page.locator(focusSelector));
 if(hoverSelector)await page.locator(hoverSelector).hover();
 let capture,clip;
 if(selector&&!focusSelector&&!hoverSelector){await page.evaluate(()=>window.scrollTo(0,0));let r=await page.locator(selector).boundingBox();let top=fromTop?0:Math.max(0,Math.floor(r.y)-8);let end=endSelector?await page.locator(endSelector).boundingBox():r;let bottom=Math.ceil(end.y+end.height)+8;let docHeight=await page.evaluate(()=>document.documentElement.scrollHeight);clip={x:0,y:top,width:w,height:Math.min(docHeight,bottom)-top};capture=await page.screenshot({path:dest,fullPage:true,clip});}
 else capture=await page.screenshot({path:dest});
 let actual=hoverSelector?await metrics(page.locator(hoverSelector)):focusSelector?await metrics(page.locator(focusSelector)):null;
 if(hoverSelector)check(`${w}/${name}/capture-hover`,actual.hover,actual);
 if(focusSelector)check(`${w}/${name}/capture-focus`,actual.focus,actual);
 assets.push({...id(dest),pixelWidth:capture.readUInt32BE(16),pixelHeight:capture.readUInt32BE(20),logicalViewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,state,region:selector||'actual viewport',clip:clip||null,sourceSha256:sha(target),sourceFreeze:mode==='formal'?'COO-G4-V01-SOURCE-01':'PREFLIGHT_NOT_FROZEN'});
}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),version=browser.version();
try{
if(mode==='formal'){let f=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json'));for(const a of [...f.inputs,...f.dependencies])check('freeze '+a.path,sha(a.path)===a.sha256&&fs.statSync(a.path).size===a.bytes,a,'SOURCE_INSPECTION');}
const original=fs.readFileSync(g3,'utf8'),candidate=fs.readFileSync(target,'utf8');
check('G3 main/script/inline style identity',['main','script','style'].every(tag=>JSON.stringify(candidate.match(new RegExp('<'+tag+'[>][\\s\\S]*?</'+tag+'>','g')))===JSON.stringify(original.match(new RegExp('<'+tag+'[>][\\s\\S]*?</'+tag+'>','g')))),{original:sha(g3),candidate:sha(target)},'SOURCE_INSPECTION');
const neutral=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'DOC-000',primaryLogoSrc:'dependencies/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'dependencies/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'dependencies/Inter-Variable.ttf'});
check('Consumer V0.2 exact assembly',['header','footer','dialog','style','behavior'].every(k=>candidate.includes(neutral[k])),{currentPageId:'DOC-000'},'SOURCE_INSPECTION');
const B=fs.readFileSync(root+'/pages/documents/certificate-of-origin/04_planning/DOC-COO_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,'');
const expected=norm(B.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#+\s*/gm,'').replace(/^[-\d.]+\s*/gm,'').replace(/^\|[- |]+\|\s*$/gm,'').replaceAll('|',' ').replaceAll('**',''));
const rowExpected=B.split('\n').filter(s=>/^\| \*\*/.test(s)).map(s=>s.split('|').slice(1,-1).map(x=>norm(x.replaceAll('**',''))));
for(const w of [1440,768,390]){let context=await browser.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage(),external=[];await context.route(/^https?:/,r=>{external.push(r.request().url());return r.abort()});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(target).href);await page.evaluate(()=>document.fonts.ready);
const actual=await page.locator('main').evaluate(e=>{let texts=[],walk=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);while(walk.nextNode())if(!walk.currentNode.parentElement.closest('.cellLabel'))texts.push(walk.currentNode.textContent);return texts.join(' ')});
check(`${w}/exact B including comparison headers`,norm(actual)===expected,{expected,actual:norm(actual)});
let layout=await page.evaluate(()=>{const rect=e=>{let r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}};return{sections:[...document.querySelectorAll('main section')].map(e=>e.id),rows:[...document.querySelectorAll('tbody tr')].map(e=>({rect:rect(e),fields:[...e.children].map(c=>({rect:rect(c),value:c.querySelector('.cellValue').textContent,label:c.querySelector('.cellLabel').textContent,labelDisplay:getComputedStyle(c.querySelector('.cellLabel')).display}))})),context:[...document.querySelectorAll('.contextList li')].map(rect),prepare:document.querySelectorAll('.prepareList li').length,scrollWidth:document.documentElement.scrollWidth,clipped:[...document.querySelectorAll('main *')].filter(e=>['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis').map(e=>e.tagName)}});
check(`${w}/six modules and lists`,JSON.stringify(layout.sections)===JSON.stringify(['coo-01','coo-02','coo-03','coo-04','coo-05','coo-06'])&&layout.context.length===4&&layout.prepare===5,layout);
check(`${w}/three evidence full pairings`,JSON.stringify(layout.rows.map(r=>r.fields.map(f=>norm(f.value))))===JSON.stringify(rowExpected),layout.rows);
check(`${w}/comparison transform`,layout.rows.every(r=>w===1440?r.fields.every(f=>f.rect.y===r.fields[0].rect.y&&f.labelDisplay==='none'):w===768?r.fields[1].rect.y===r.fields[2].rect.y&&r.fields[1].rect.x<r.fields[2].rect.x&&r.fields.every(f=>f.labelDisplay==='block'):r.fields[0].rect.y<r.fields[1].rect.y&&r.fields[1].rect.y<r.fields[2].rect.y&&r.fields.every(f=>f.labelDisplay==='block')),layout.rows);
check(`${w}/geometry`,layout.scrollWidth===w&&!layout.clipped.length&&(w===390?layout.context.every((r,i)=>i===0||r.y>layout.context[i-1].y):layout.context[0].y===layout.context[1].y&&layout.context[2].y===layout.context[3].y),layout);
check(`${w}/excluded availability and no invented UI`,!actual.includes('A Certificate of Origin is available upon request')&&await page.locator('main form,main input,main select,main img').count()===0,{});
let rows=page.locator(w===1440?'thead th':'.evidenceTable tbody th');for(let i=0;i<await rows.count();i++){let loc=rows.nth(i),m=await metrics(loc);check(`${w}/evidence band/${i}`,m.bg==='rgb(245, 248, 251)'&&contrast(m.fg,m.bg)>=4.5,{...m,textContrast:contrast(m.fg,m.bg),oldBackground:'#F0F5F8',newBackground:'#F5F8FB'});}
let cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');let doc=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'main h1'}),fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(`${w}/Inter loaded`,fonts.fonts.some(f=>f.familyName==='Inter'&&f.isCustomFont),fonts);check(`${w}/SVG loaded`,await page.locator('img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)),{});
await controls(page,'header .headerInner a,header .headerInner button,main a,footer a,footer button','normal-page',w);
for(const sel of ['#coo-02 a[href^="https:"]','#coo-06 a[href^="https:"]']){let loc=page.locator(sel);await loc.scrollIntoViewIfNeeded();let fragments=await loc.evaluate(e=>[...e.getClientRects()].map(r=>({x:r.x,y:r.y,width:r.width,height:r.height,hit:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('a')===e})));check(`${w}/${sel}/wrapped-link-fragments`,fragments.every(r=>r.width>=44&&r.height>=44&&r.hit),fragments);}
let links=page.locator('main a');for(let i=0;i<await links.count();i++){let loc=links.nth(i),href=await loc.getAttribute('href');await loc.click();let intent=await page.evaluate(()=>window.__navigationIntents.at(-1));let expectedContext=href==='/request-documents/'?{prefill:{document_types:['origin_supplier_qualification']},source_context:{page_id:'DOC-COO'}}:null;check(`${w}/local intent/${i}`,intent.href===href&&JSON.stringify(intent.context)===JSON.stringify(expectedContext)&&intent.receiverExecuted===false,intent,'LOCAL_SIMULATION');}
if(w<1101){await page.evaluate(()=>window.scrollTo(0,0));await page.locator('.menuButton').click();check(`${w}/menu entry`,await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement),{});check(`${w}/menu isolation`,await page.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'),{});await controls(page,'.menuButton,.mobileNav a','menu',w);await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let cy=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');check(`${w}/menu cycle`,cy&&await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});if(mode==='formal'){await page.evaluate(()=>window.scrollTo(0,0));await shot(page,w,'menu-focus',{focusSelector:'.mobileNav a[aria-current]',state:'Menu open; actual Documents keyboard focus'});}await page.keyboard.press('Escape');check(`${w}/menu escape`,await page.locator('.menuButton').evaluate(e=>e===document.activeElement)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();check(`${w}/menu selection`,await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});let change=await page.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,restored:!document.querySelector('main').inert,focus:document.activeElement.tagName}));check(`${w}/desktop breakpoint`,change.closed&&change.restored,change);await page.setViewportSize({width:w,height:w===390?844:900});}
await page.locator('#cookie-trigger').click();check(`${w}/cookie entry`,await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(page,'.cookie-actions>*','cookie',w);await page.locator('[data-cookie-close]').focus();await page.keyboard.press('Shift+Tab');let cy=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');check(`${w}/cookie cycle`,cy&&await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await page.locator('main .primary').first().evaluate(e=>e.focus());check(`${w}/cookie modal isolation`,await page.locator('dialog').evaluate(e=>e.contains(document.activeElement)),{});if(mode==='formal')await shot(page,w,'cookie-focus',{focusSelector:'[data-cookie-close]',state:'Cookie open; actual Close keyboard focus'});await page.keyboard.press('Escape');check(`${w}/cookie escape`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();check(`${w}/cookie Close return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),{});
await page.evaluate(()=>document.activeElement.blur());await page.mouse.move(0,0);
const regions=[['hero','#coo-01',null,true],['context-and-traceability','#coo-03','#coo-04'],['prepare','#coo-05'],['official-source','#coo-06'],['footer','footer']];
if(w===390)regions.splice(1,0,['comparison-1','#coo-02','tbody tr:nth-child(1)'],['comparison-2','tbody tr:nth-child(2)'],['comparison-3','tbody tr:nth-child(3)','#coo-02>p:last-child']);else regions.splice(1,0,['comparison','#coo-02']);
for(const [name,selector,endSelector,fromTop]of regions){if(mode==='formal'||name==='comparison'||w===390&&['comparison-1','comparison-2','comparison-3','official-source','prepare'].includes(name))await shot(page,w,name,{selector,endSelector,fromTop});}
if(mode==='formal'){await page.locator('#coo-06').scrollIntoViewIfNeeded();await shot(page,w,'official-source-hover',{hoverSelector:'#coo-06 a',state:'Actual long official source hover; both source dates/review/limit in normal source region'});if(w===1440){await page.locator('#coo-01 .primary').scrollIntoViewIfNeeded();await shot(page,w,'primary-hover',{hoverSelector:'#coo-01 .primary',state:'Actual Request Origin Documentation hover'});}if(w===768){await page.locator('#coo-02>p:last-child').scrollIntoViewIfNeeded();await shot(page,w,'comparison-guidance-hover',{hoverSelector:'#coo-02 a',state:'Actual general guidance source hover; comparison limitation retained'});}if(w===390){await page.locator('#coo-06').scrollIntoViewIfNeeded();await shot(page,w,'official-source-focus',{focusSelector:'#coo-06 a',state:'Actual multi-line official source keyboard focus'});await page.locator('#coo-05>a,#coo-05>p:last-child').last().scrollIntoViewIfNeeded();await shot(page,w,'document-hub-focus',{focusSelector:'#coo-05 a[href="/documents/"]',state:'Actual supporting Document Hub keyboard focus'});}}
check(`${w}/no external requests`,external.length===0,{external});await context.close();}
}catch(e){errors.push(e.stack);}await browser.close();const data={date:new Date().toISOString(),mode,source:id(target),runtime:{node:process.version,chrome:version,playwright:'1.62.1',headless:true,scale:1,externalRequestsAllowed:false},records,errors,assets,scope:'DOC-COO Gate4 local samples and actual interactions; origin type prefill is local intent, no receiver validation'};fs.writeFileSync(out+'/diagnostic_support/'+mode+'-runtime-checks.json',JSON.stringify(data,null,2));if(mode==='formal')fs.writeFileSync(out+'/approval_core/export-inventory.json',JSON.stringify({freezeId:'COO-G4-V01-SOURCE-01',date:new Date().toISOString(),assets},null,2));console.log(JSON.stringify({mode,records:records.length,errors,assets:assets.map(a=>({path:a.relativePath,width:a.pixelWidth,height:a.pixelHeight}))}));if(errors.length)process.exitCode=1;})();
