import fs from 'fs';
import crypto from 'crypto';
import { pathToFileURL } from 'url';
import { chromium } from 'file:///C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';

const root='D:/23MySec';
const oldBase=`${root}/pages/conversion/thank-you/04_planning/gate4-v0.1`;
const base=`${root}/pages/conversion/thank-you/04_planning/gate4-v0.2`;
const oldSource=`${oldBase}/CONV-THANK_GATE4_EDITABLE_SOURCE_V0.1.html`;
const source=`${base}/CONV-THANK_GATE4_EDITABLE_SOURCE_V0.2.html`;
const evidencePath=`${base}/CONV-THANK_GATE4_EVIDENCE_INDEX_V0.2.json`;
const output=`${root}/pages/conversion/thank-you/05_review/gate5-independent-v0.1/targeted-runtime-observation-v0.2.json`;
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const identity=p=>({path:p,bytes:fs.statSync(p).size,sha256:sha(p)});
const pngSize=p=>{const b=fs.readFileSync(p);if(b.toString('ascii',1,4)!=='PNG')throw Error(`not PNG: ${p}`);return{width:b.readUInt32BE(16),height:b.readUInt32BE(20)}};
const stateSpec={
  quote:{h1:'Thank you. We’ve received your quotation request.',body:'Our team will review the details and contact you using the information provided.',labels:['Explore Products','Go to Homepage'],hrefs:['/products/','/'],success:true},
  documents:{h1:'Thank you. We’ve received your document request.',body:'Our team will review the requested documents and contact you using the information provided.',labels:['Return to Documents','Explore Products'],hrefs:['/documents/','/products/'],success:true},
  sample:{h1:'Thank you. We’ve received your sample request.',body:'Our team will review your application and sample requirements and contact you using the information provided.',labels:['Explore Products','View Applications'],hrefs:['/products/','/applications/'],success:true},
  direct:{h1:'How can we help?',body:'Choose the request you’d like to make, and our team will guide you through the next step.',labels:['Request a Quote','Request Documents','Request a Sample'],hrefs:['/request-a-quote/','/request-documents/','/request-sample/'],success:false}
};
const checks=[];
const check=(name,ok,detail,evidenceType='ACTUAL_RUNTIME')=>checks.push({name,status:ok?'PASS':'FAIL',evidenceType,detail});
const marker=state=>({type:state,acknowledged:true,session:'gate3-local-simulation',successTimestamp:Date.now(),stale:false});
const ready=p=>p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))});
const footerOld='<nav class="legalUtilities" aria-label="Legal and privacy navigation"><a href="/privacy-policy/">Privacy Policy</a><a href="/ms/privacy-policy/">Dasar Privasi (BM)</a><a href="/cookie-policy/">Cookie Policy</a><button id="cookie-trigger" type="button">Cookie Settings</button></nav><p class="copyright">© 2026 TiO2 Malaysia.</p>';
const footerNew='<p class="copyright">© 2026 TiO2 Malaysia.</p><nav class="legalUtilities" aria-label="Legal and privacy navigation"><a href="/privacy-policy/">Privacy Policy</a><a href="/ms/privacy-policy/">Dasar Privasi (BM)</a><a href="/cookie-policy/">Cookie Policy</a><button id="cookie-trigger" type="button">Cookie Settings</button></nav>';

let browser;
try{
  const evidence=JSON.parse(fs.readFileSync(evidencePath));
  check('bundle identity',evidence.bundle_id==='CONV-THANK-G4-BUNDLE-20260908-02',evidence.bundle_id,'SOURCE_INSPECTION');
  check('source identity',sha(source)==='5487a2d5bcc8528b8e01b18b10b9bc78bd67e2fa693833313f16ee0e94a7e8fd',identity(source),'SOURCE_INSPECTION');
  check('author and lifecycle',evidence.executor==='/root/conv_thank_gate4_execute'&&evidence.lifecycle==='DRAFT_FOR_PROJECT_CONTROL_REVIEW',{executor:evidence.executor,lifecycle:evidence.lifecycle},'SOURCE_INSPECTION');
  const oldText=fs.readFileSync(oldSource,'utf8'),newText=fs.readFileSync(source,'utf8');
  check('source delta limited to Footer copyright-first node move',oldText.includes(footerOld)&&newText.includes(footerNew)&&oldText.replace(footerOld,footerNew)===newText,{oldSource:identity(oldSource),newSource:identity(source)},'SOURCE_INSPECTION');
  const assets=evidence.approval_core.assets;
  const assetAudit=assets.map(a=>{const exists=fs.existsSync(a.path);const size=exists?pngSize(a.path):{};return{path:a.path,exists,bytes:exists?fs.statSync(a.path).size:null,expectedBytes:a.bytes,sha256:exists?sha(a.path):null,expectedSha256:a.sha256,width:size.width,height:size.height,expectedPhysical:a.physicalSize,sourceSha256:a.sourceSha256}});
  check('15 approval-core files present and bound',assets.length===15&&assetAudit.every(a=>a.exists&&a.bytes===a.expectedBytes&&a.sha256===a.expectedSha256&&a.sourceSha256===sha(source)),assetAudit,'SOURCE_INSPECTION');
  check('formal PNG physical dimensions',assetAudit.every(a=>a.width===a.expectedPhysical[0]&&a.height===a.expectedPhysical[1]),assetAudit,'SOURCE_INSPECTION');
  const menuPairs=[['390','CONV-THANK_GATE4_DIRECT_390_MENU'],['768','CONV-THANK_GATE4_DIRECT_768_MENU']].map(([width,stem])=>{const old=`${oldBase}/approval_core/${stem}_V0.1.png`,fresh=`${base}/approval_core/${stem}_V0.2.png`;return{width,old:identity(old),fresh:identity(fresh),byteIdentical:fs.readFileSync(old).equals(fs.readFileSync(fresh))}});
  check('two recaptured Menu assets byte-identical to V0.1',menuPairs.every(x=>x.byteIdentical),menuPairs,'SOURCE_INSPECTION');

  browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
  const blocked=[];
  for(const state of Object.keys(stateSpec))for(const width of [1440,768,390]){
    const height=width===390?844:900, context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'reduce',colorScheme:'light'});
    await context.route(/^https?:/,r=>{blocked.push(r.request().url());r.abort()});
    const page=await context.newPage();
    if(state!=='direct')await page.addInitScript(m=>sessionStorage.setItem('tio2my_thankyou_gate3_marker',JSON.stringify(m)),marker(state));
    await page.goto(pathToFileURL(source).href+(state==='direct'?'':`?request=${state}`));await ready(page);
    const snap=await page.evaluate(()=>{const visible=[...document.querySelectorAll('[data-result-state]')].filter(e=>!e.hidden),panel=visible[0],actions=panel?[...panel.querySelectorAll('.resultAction')]:[],targets=[...document.querySelectorAll('a,button')].filter(e=>e.getBoundingClientRect().width>0).map(e=>{const r=e.getBoundingClientRect();return{text:e.textContent.trim(),width:r.width,height:r.height,left:r.left,right:r.right,top:r.top,bottom:r.bottom}});const copyright=document.querySelector('.copyright'),legal=document.querySelector('.legalUtilities'),cr=copyright.getBoundingClientRect(),lr=legal.getBoundingClientRect();return{resolved:document.documentElement.dataset.resolvedState,visibleCount:visible.length,h1:panel?.querySelector('h1')?.textContent,body:panel?.querySelector('p')?.textContent,labels:actions.map(e=>e.textContent),hrefs:actions.map(e=>e.getAttribute('href')),successCue:panel?.querySelectorAll('.successCue').length||0,received:panel?.innerText.includes('REQUEST RECEIVED')||false,successIcon:panel?.querySelectorAll('.successIcon').length||0,allHiddenPanels:[...document.querySelectorAll('[data-result-state]')].filter(e=>e.hidden).length,ariaCurrent:document.querySelectorAll('[aria-current]').length,forbidden:document.querySelectorAll('main form,main input,main textarea,main details,main img,main video').length,scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,scrollHeight:document.documentElement.scrollHeight,footerBottom:document.querySelector('footer').getBoundingClientRect().bottom+scrollY,targets,actionRects:actions.map(e=>{const r=e.getBoundingClientRect();return{left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}}),footerChildren:[...document.querySelector('footer').children].map(e=>e.className||e.tagName),copyrightBeforeLegalVisual:cr.top<lr.top,legalLabels:[...legal.children].map(e=>e.textContent.trim()),legalHrefs:[...legal.querySelectorAll('a')].map(e=>e.getAttribute('href')),head:{title:document.title,robots:document.querySelector('meta[name=robots]')?.content,canonical:document.querySelector('link[rel=canonical]')?.href,schema:document.querySelectorAll('script[type="application/ld+json"]').length},bodyText:document.body.innerText,font:document.fonts.check('16px Inter'),result:window.gate4ResultState};});
    const spec=stateSpec[state];
    check(`${state} ${width} exact mutually-exclusive content`,snap.resolved===state&&snap.visibleCount===1&&snap.allHiddenPanels===3&&snap.h1===spec.h1&&snap.body===spec.body&&JSON.stringify(snap.labels)===JSON.stringify(spec.labels)&&JSON.stringify(snap.hrefs)===JSON.stringify(spec.hrefs),snap);
    check(`${state} ${width} receipt cue boundary`,spec.success?(snap.successCue===1&&snap.successIcon===1&&snap.received):(snap.successCue===0&&snap.successIcon===0&&!snap.received),{successCue:snap.successCue,successIcon:snap.successIcon,received:snap.received});
    check(`${state} ${width} Footer DOM and visual order copyright-first`,JSON.stringify(snap.footerChildren)===JSON.stringify(['footerGrid','copyright','legalUtilities'])&&snap.copyrightBeforeLegalVisual,{footerChildren:snap.footerChildren,copyrightBeforeLegalVisual:snap.copyrightBeforeLegalVisual});
    check(`${state} ${width} Footer legal labels and routes`,JSON.stringify(snap.legalLabels)===JSON.stringify(['Privacy Policy','Dasar Privasi (BM)','Cookie Policy','Cookie Settings'])&&JSON.stringify(snap.legalHrefs)===JSON.stringify(['/privacy-policy/','/ms/privacy-policy/','/cookie-policy/']),{labels:snap.legalLabels,hrefs:snap.legalHrefs});
    check(`${state} ${width} geometry targets and exclusions`,snap.scrollWidth===snap.clientWidth&&Math.abs(snap.footerBottom-snap.scrollHeight)<2&&snap.targets.every(t=>t.width>=44&&t.height>=44&&t.left>=0&&t.right<=width)&&snap.ariaCurrent===0&&snap.forbidden===0&&snap.font,{scrollWidth:snap.scrollWidth,clientWidth:snap.clientWidth,scrollHeight:snap.scrollHeight,footerBottom:snap.footerBottom,targets:snap.targets,ariaCurrent:snap.ariaCurrent,forbidden:snap.forbidden,font:snap.font});
    check(`${state} ${width} head contract`,snap.head.title==='Thank You | TiO2 Malaysia'&&snap.head.robots==='noindex,nofollow'&&snap.head.canonical==='https://tio2malaysia.com/thank-you/'&&snap.head.schema===0,snap.head,'SOURCE_INSPECTION');
    check(`${state} ${width} local-only receipt representation`,snap.result?.state===state&&snap.result?.evidenceType==='LOCAL_SIMULATION'&&snap.result?.productionReceiptProven===false,snap.result,'LOCAL_SIMULATION');
    check(`${state} ${width} no PII or reference projection`,!/(request number|reference number|@|phone|company name|successfully submitted)/i.test(`${snap.h1}\n${snap.body}\n${snap.labels.join('\n')}`),snap.bodyText,'SOURCE_INSPECTION');
    for(let i=0;i<spec.labels.length;i++){await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).focus();const outline=await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).evaluate(e=>({style:getComputedStyle(e).outlineStyle,width:getComputedStyle(e).outlineWidth,color:getComputedStyle(e).outlineColor}));check(`${state} ${width} action ${i+1} focus visible`,outline.style!=='none'&&parseFloat(outline.width)>=3,outline);await page.locator('[data-result-state]:not([hidden]) .resultAction').nth(i).click();const intent=await page.evaluate(()=>window.localNavigationIntents.at(-1));check(`${state} ${width} action ${i+1} target`,intent?.href===spec.hrefs[i],intent,'LOCAL_SIMULATION');}
    if(width===390)check(`${state} 390 actions stack without collision`,snap.actionRects.every(r=>r.width>=300&&r.left>=0&&r.right<=390)&&snap.actionRects.every((r,i,a)=>i===0||r.top>=a[i-1].bottom),snap.actionRects);
    await context.close();
  }
  for(const [name,query,m] of [['missing request','',marker('quote')],['unsupported request','?request=unsupported',marker('quote')],['query alone','?request=quote',null],['mismatched','?request=documents',marker('quote')],['stale','?request=sample',{...marker('sample'),stale:true}],['new session','?request=quote',{...marker('quote'),session:'different-session'}],['not acknowledged','?request=documents',{...marker('documents'),acknowledged:false}],['obsolete type rejected','?type=quote',marker('quote')]]){const c=await browser.newContext({viewport:{width:390,height:844}}),p=await c.newPage();if(m)await p.addInitScript(x=>sessionStorage.setItem('tio2my_thankyou_gate3_marker',JSON.stringify(x)),m);await p.goto(pathToFileURL(source).href+query);await ready(p);const got=await p.evaluate(()=>({state:document.documentElement.dataset.resolvedState,visible:[...document.querySelectorAll('[data-result-state]:not([hidden])')].map(e=>e.dataset.resultState),received:document.querySelector('main').innerText.includes('REQUEST RECEIVED')}));check(`${name} resolves Direct without receipt`,got.state==='direct'&&JSON.stringify(got.visible)===JSON.stringify(['direct'])&&!got.received,got,'LOCAL_SIMULATION');await c.close()}
  for(const width of [768,390]){const c=await browser.newContext({viewport:{width,height:width===390?844:900}}),p=await c.newPage();await p.goto(pathToFileURL(source).href);await ready(p);const toggle=p.locator('.menuButton');await toggle.click();check(`${width} Menu opens focuses and isolates`,await p.evaluate(()=>document.activeElement?.textContent.trim()==='Home'&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'));await p.keyboard.press('Shift+Tab');check(`${width} Menu reverse reaches toggle`,await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(`${width} Menu reverse wraps to last`,await p.evaluate(()=>document.activeElement?.textContent.trim()==='Request a Quote'));await p.keyboard.press('Tab');check(`${width} Menu forward wraps to toggle`,await toggle.evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(`${width} Menu Escape restores`,await toggle.evaluate(e=>e===document.activeElement)&&await p.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&!document.querySelector('footer').inert&&document.body.style.overflow===''));await c.close()}
  for(const width of [1440,768,390]){const c=await browser.newContext({viewport:{width,height:width===390?844:900}}),p=await c.newPage();await p.goto(pathToFileURL(source).href);await ready(p);await p.locator('#cookie-trigger').click();check(`${width} Cookie opens to Close`,await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Shift+Tab');check(`${width} Cookie reverse loop`,await p.locator('.cookie-layer a').evaluate(e=>e===document.activeElement));await p.keyboard.press('Tab');check(`${width} Cookie forward loop`,await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement));await p.keyboard.press('Escape');check(`${width} Cookie Escape returns focus`,await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&await p.locator('.cookie-layer').evaluate(e=>!e.open));await c.close()}
  const z=await browser.newContext({viewport:{width:720,height:900},deviceScaleFactor:2,reducedMotion:'reduce'}),zp=await z.newPage();await zp.goto(pathToFileURL(source).href);await ready(zp);const zoom=await zp.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,targets:[...document.querySelectorAll('a,button')].filter(e=>e.getBoundingClientRect().width>0).every(e=>e.getBoundingClientRect().width>=44&&e.getBoundingClientRect().height>=44)}));check('200 percent equivalent reflow',zoom.scrollWidth===zoom.clientWidth&&zoom.targets,zoom);await z.close();
  check('no network requests',blocked.length===0,blocked);
  const failures=checks.filter(c=>c.status==='FAIL');
  const record={dispatch_id:'G5-CONVTHANK-REREVIEW-20260908-02',page_id:'CONV-THANK',review_stage:'GATE5_INDEPENDENT_VISUAL_REVIEW',mode:'TARGETED_RECHECK',reviewer:'/root/sys404_gate5_review',author:'/root/conv_thank_gate4_execute',independent:true,bundle_id:evidence.bundle_id,source_identity:identity(source),inherited_review_report:`${root}/pages/conversion/thank-you/05_review/gate5-independent-v0.1/CONV-THANK_GATE5_INDEPENDENT_VISUAL_REVIEW_V0.1.md`,formal_assets_opened_by_reviewer:assets.map(a=>a.path),changed_formal_assets_reviewed:13,unchanged_menu_assets_hash_verified:2,new_persistent_screenshots:0,screenshot_trigger:'NONE',checks,failures:failures.length,finding_status:failures.length?'OPEN':'CONVTHANK-G5-IR-F01=CLOSED',required_findings:failures.length,result:failures.length?'CHANGES_REQUIRED':'REVIEW_PASS',lifecycle:failures.length?'DRAFT_FOR_PROJECT_CONTROL_REVIEW':'PROJECT_CONTROL_REVIEW_PASS',limits:['Production receiver, real session implementation, live navigation/analytics, CMS/SEO/scope integration, real-device and screen-reader verification remain downstream.'],finished_at:new Date().toISOString()};fs.writeFileSync(output,JSON.stringify(record,null,2)+'\n');console.log(JSON.stringify({result:record.result,lifecycle:record.lifecycle,checks:checks.length,failures:failures.length,output}));if(failures.length)process.exitCode=1;
}catch(error){fs.writeFileSync(output,JSON.stringify({result:'FAILED',error:error.stack},null,2)+'\n');console.error(error);process.exitCode=1}finally{if(browser)await browser.close()}
