const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',dir=path.join(root,'pages/markets/04_planning/d32-gate3-v0.1'),out=__dirname;
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const checks=[],observations=[]; const check=(id,ok,detail)=>checks.push({id,pass:!!ok,detail});
const before=new Map();function identity(x,kind){const actual=sha(x.path);before.set(x.path,actual);check(kind+':'+path.basename(x.path),actual===x.sha256&&fs.statSync(x.path).size===x.bytes,{actual,expected:x.sha256});}
const freeze=json(path.join(dir,'freeze.json')),inputs=json(path.join(dir,'input-identities.json')),assets=json(path.join(dir,'approval_core/asset-index.json'));
for(const x of freeze.sources)identity(x,'source'); for(const x of [...inputs.inputs,...inputs.dependencies])identity(x,'input');for(const x of assets.assets)identity(x,'formal');
const material=freeze.sources.map(x=>({path:path.relative(root,x.path).replaceAll('\\','/'),sha256:sha(x.path)})).sort((a,b)=>a.path.localeCompare(b.path)).map(x=>x.path+'\0'+x.sha256+'\n').join('');
const bundle=crypto.createHash('sha256').update(material).digest('hex');check('submitted-bundle',bundle==='f2c25e99b6b7958ddfb7c6e7f2888decd07c5a6aaa9223b2099ed66a6d3219b9',bundle);
const source=read(path.join(dir,'market-planning.html')),approved=read(path.join(root,'pages/markets/04_planning/MARKET-000_CONTENT_ARCHITECTURE_V0.1.md'));
const blocks=[...approved.split('## 5.')[0].matchAll(/```text\s*\n([\s\S]*?)```/g)].map(x=>x[1].trim().replace(/\s+/g,' '));
const questions=[...approved.matchAll(/#### Q([1-6])\. (.+)\r?\n/g)].map(x=>x[2].trim());
const expectedRoutes=['european-union','germany','italy','spain','poland','netherlands','belgium','united-kingdom','india','brazil'].map(x=>'/markets/'+x+'/');
const support=['/products/','/applications/','/documents/','/resources/'];
check('no-public-held-schema-hreflang',!/<script[^>]+ld\+json|hreflang=|\/pt-br\/|trade-updates\/|M-996|M-2377|M-2196/.test(source));
(async()=>{const browser=await chromium.launch({headless:true}); const errors=[];
for(const width of [1440,768,390]){const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(path.join(dir,'market-planning.html')).href);await page.evaluate(()=>document.fonts.ready);
const state=await page.evaluate(()=>({h1:[...document.querySelectorAll('h1')].map(e=>e.textContent),modules:[...document.querySelectorAll('[data-module]')].map(e=>e.dataset.module),copy:[...document.querySelectorAll('[data-copy]')].map(e=>({i:+e.dataset.copy,text:e.textContent.replace(/\s+/g,' ').trim()})),qa:[...document.querySelectorAll('[data-question] h3')].map(e=>e.textContent),routes:[...document.querySelectorAll('[data-ready-action]')].map(e=>e.getAttribute('href')),body:document.querySelector('main').innerText,overflow:document.documentElement.scrollWidth>innerWidth,heroLinks:[...document.querySelectorAll('.rootHero a')].map(e=>e.getAttribute('href')),targets:[...document.querySelectorAll('a,button')].filter(e=>e.getClientRects().length).map(e=>({text:e.textContent.trim(),w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),headings:[...document.querySelectorAll('main h1,main h2,main h3,main h4')].map(e=>({text:e.textContent,level:+e.tagName.slice(1)})),height:document.documentElement.scrollHeight}));observations.push({width,...state});
// Compare approved semantic text: article blocks contain distinct heading/body children and separately approved CTA children.
state.copy=await page.locator('[data-copy]').evaluateAll(es=>es.map(e=>({i:+e.dataset.copy,text:(e.tagName==='ARTICLE'?[...e.querySelectorAll('h3,p')].map(n=>n.textContent).join(' '):e.textContent).replace(/\s+/g,' ').trim()})));
check(width+':no-overflow',!state.overflow);check(width+':one-approved-h1',JSON.stringify(state.h1)===JSON.stringify(['Choose Your Destination Market']));check(width+':module-order',state.modules.join('|')==='HERO|DESTINATION_SELECTOR|MARKET_CHOICE_GUIDE|PROCUREMENT_PATHS|TRADE_BOUNDARY|BUYER_QUESTIONS');check(width+':six-questions',JSON.stringify(state.qa)===JSON.stringify(questions));check(width+':all-fourteen-routes',JSON.stringify(state.routes)===JSON.stringify([...expectedRoutes,...support]));check(width+':single-hero-action',JSON.stringify(state.heroLinks)==='["#destination-selector"]');check(width+':touch-targets',state.targets.every(x=>x.w>=44&&x.h>=44),state.targets.filter(x=>x.w<44||x.h<44));check(width+':clean-body',!(/\bCURRENT\b|PROVISIONAL|NOT_VERIFIED|\bowner\b|\bworkflow\b|\bGate\b|Coming soon|Request a Quote|Ready to discuss a destination market|How is quotation handled/.test(state.body.replace('CURRENT INFORMATION',''))));check(width+':brazil-approved-delta',state.body.includes('Use the Brazil path when your next procurement questions need a Brazil-specific market context.'));check(width+':all-tagged-copy-exact',state.copy.every(x=>blocks[x.i]===x.text),state.copy.filter(x=>blocks[x.i]!==x.text));
const countries=page.locator('#eu-countries');check(width+':eu-default',await countries.isVisible()=== (width>=768));
if(width<768){await page.locator('#eu-toggle').focus();await page.keyboard.press('Enter');check('390:eu-enter',await countries.isVisible());check('390:eu-six',await countries.locator('a').count()===6);await page.keyboard.press('Space');check('390:eu-space',!(await countries.isVisible()));}
await page.locator('.primary').click();check(width+':local-anchor',new URL(page.url()).hash==='#destination-selector');
if(width<1101){await page.locator('.menuButton').click();check(width+':menu-open',await page.locator('.mobileNav').isVisible());check(width+':menu-background-inert',await page.locator('main').evaluate(e=>e.inert));check(width+':menu-first-focus',await page.evaluate(()=>document.activeElement.textContent.trim())==='Home');await page.keyboard.press('Escape');check(width+':menu-escape-return',await page.locator('.menuButton').evaluate(e=>document.activeElement===e)&&!await page.locator('main').evaluate(e=>e.inert));await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:1000});await page.waitForFunction(()=>!document.querySelector('main').inert);check(width+':breakpoint-closes',!await page.locator('.mobileNav').isVisible());await page.setViewportSize({width,height:1000});}
await page.locator('#cookie-trigger').click();check(width+':cookie-open',await page.locator('dialog').evaluate(e=>e.open));await page.keyboard.press('Escape');check(width+':cookie-return',await page.locator('#cookie-trigger').evaluate(e=>document.activeElement===e));check(width+':no-console-errors',errors.length===0,errors);
await context.close();}
for(const [mode,expected] of [['none',[]],['eu-only',[expectedRoutes[0]]],['support-only',support]]){const page=await browser.newPage({viewport:{width:390,height:1000}});await page.goto(pathToFileURL(path.join(dir,'market-planning.html')).href+'?state='+mode);await page.evaluate(()=>document.fonts.ready);const routes=await page.locator('[data-ready-action]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));check(mode+':atomic-route-simulation',JSON.stringify(routes)===JSON.stringify(expected),routes);check(mode+':countries-readable',await page.locator('.plainCountry').count()===6);check(mode+':rfq-stays',await page.locator('header a[href*="request-a-quote"],footer a[href*="request-a-quote"]').count()>=2);check(mode+':no-overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(mode+':no-internal-label',!(/NOT_VERIFIED|PROVISIONAL|Coming soon/.test(await page.locator('body').innerText())));await page.close();}
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:1000}});const np=await nojs.newPage();await np.goto(pathToFileURL(path.join(dir,'market-planning.html')).href);check('nojs:all-country-links-visible',await np.locator('#eu-countries').isVisible()&&await np.locator('#eu-countries a').count()===6);check('nojs:six-answers',await np.locator('[data-question]').count()===6);await nojs.close();
const stress=await browser.newPage({viewport:{width:390,height:1000},reducedMotion:'reduce'});await stress.goto(pathToFileURL(path.join(dir,'market-planning.html')).href);await stress.addStyleTag({content:'main p{font-size:200%!important}'});check('200-percent-body:no-overflow',await stress.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await stress.close();
for(const width of [768,390]){const p=await browser.newPage({viewport:{width,height:1000}});await p.goto(pathToFileURL(path.join(dir,'market-planning.html')).href);await p.locator('.menuButton').click();await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');check(width+':full-menu-forward-loop',await p.locator('.menuButton').evaluate(e=>document.activeElement===e));await p.keyboard.press('Shift+Tab');check(width+':full-menu-reverse-loop',await p.locator('.mobileNav a').last().evaluate(e=>document.activeElement===e));await p.locator('.mobileNav').evaluate(e=>e.addEventListener('click',event=>event.preventDefault(),{once:true}));await p.locator('.mobileNav a').first().click();check(width+':menu-selection-restores',await p.locator('.mobileNav').evaluate(e=>e.hidden)&&!await p.locator('main').evaluate(e=>e.inert));await p.locator('#cookie-trigger').click();check(width+':cookie-initial-close',await p.locator('[data-cookie-close]').evaluate(e=>document.activeElement===e));await p.keyboard.press('Shift+Tab');check(width+':cookie-reverse-loop',await p.locator('.cookie-layer a').evaluate(e=>document.activeElement===e));await p.keyboard.press('Tab');check(width+':cookie-forward-loop',await p.locator('[data-cookie-close]').evaluate(e=>document.activeElement===e));await p.locator('[data-cookie-close]').click();check(width+':cookie-close-return',await p.locator('#cookie-trigger').evaluate(e=>document.activeElement===e));await p.close();}
// Reviewer-owned readable state crops; never replace the author's formal exports.
for(const mode of ['none','eu-only','support-only']){const p=await browser.newPage({viewport:{width:390,height:1000}});await p.goto(pathToFileURL(path.join(dir,'market-planning.html')).href+'?state='+mode);await p.evaluate(()=>document.fonts.ready);await p.locator('#eu-toggle').click();await p.locator('.euPanel').screenshot({path:path.join(out,mode+'-eu.png')});await p.locator('[data-module="PROCUREMENT_PATHS"]').screenshot({path:path.join(out,mode+'-support.png')});await p.close();}
await browser.close();for(const [p,h] of before)check('read-only:'+path.basename(p),sha(p)===h);
const result={reviewer:'/root/doc_root_d32',timestamp:new Date().toISOString(),candidate_bundle:bundle,html_sha256:sha(path.join(dir,'market-planning.html')),evidence_types:['SOURCE_INSPECTION','ACTUAL_RUNTIME','LOCAL_SIMULATION'],passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass).length,checks,observations};fs.writeFileSync(path.join(out,'observations.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(x=>!x.pass)}));process.exitCode=result.failed?1:0;})().catch(e=>{console.error(e);process.exitCode=2});
