const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),candidate=path.join(root,'design-v1'),out=path.join(__dirname,'evidence');
const copy=JSON.parse(fs.readFileSync(path.join(root,'copy.json'),'utf8'));
const names=['wireframe.html',...[1440,768,390].flatMap(w=>[`initial-${w}.png`,`expanded-${w}.png`]),'mobile-menu-390.png','invalid-submit-390.png','simulated-success-390.png'];
const identities=names.map(n=>{const b=fs.readFileSync(path.join(candidate,n));return {path:path.join(candidate,n),bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex'),...(n.endsWith('.png')?{width:b.readUInt32BE(16),height:b.readUInt32BE(20)}:{})}});
fs.writeFileSync(path.join(out,'identities.json'),JSON.stringify(identities,null,2));
async function measure(p){return p.evaluate(()=>{const info=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {tag:e.tagName,id:e.id,text:e.textContent.trim().slice(0,100),x:r.x,y:r.y+scrollY,w:r.width,h:r.height,cw:e.clientWidth,sw:e.scrollWidth,ch:e.clientHeight,sh:e.scrollHeight,overflow:s.overflow}};const visible=e=>e.getClientRects().length>0;const targets=[...document.querySelectorAll('a,button,input,select,textarea,summary')].filter(visible).map(info);const content=[...document.querySelectorAll('h1,h2,h3,p,dt,dd,label,summary')].filter(visible).map(info);return {viewport:innerWidth,pageWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,smallTargets:targets.filter(x=>x.w<44||x.h<44),targets,clippingCandidates:content.filter(x=>x.sw>x.cw+1||x.sh>x.ch+1),records:[...document.querySelectorAll('.record')].map(info),requestY:document.querySelector('#request').getBoundingClientRect().y+scrollY,privacy:info(document.querySelector('.privacy-line')),select:info(document.querySelector('select'))}})}
(async()=>{
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});const url='file:///'+path.join(candidate,'wireframe.html').replaceAll('\\','/');
const d={runtime:browser.version(),views:[],actions:{},network:[]};await page.route('**/*',r=>{if(r.request().url().startsWith('file:'))return r.continue();d.network.push(r.request().url());return r.abort()});
for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});await page.goto(url);const initial=await measure(page);await page.screenshot({path:path.join(out,`runtime-initial-${width}.png`),fullPage:true});for(const s of await page.locator('summary').all())await s.click();const expanded=await measure(page);await page.screenshot({path:path.join(out,`runtime-expanded-${width}.png`),fullPage:true});d.views.push({width,initial,expanded,openCount:await page.locator('details[open]').count()})}
d.copy=await page.evaluate(c=>{const txt=s=>document.querySelector(s).textContent;const rows=[...document.querySelectorAll('.record')];const actual={hero:{title:txt('h1'),text:txt('#overview p'),cta:txt('#overview a')},comparisonTitle:txt('#comparison h2'),records:rows.map(e=>({name:e.querySelector('h3').textContent,values:[...e.querySelectorAll('dd')].map(x=>x.textContent)})),metrics:[...rows[0].querySelectorAll('dt')].map(x=>x.textContent),notes:rows.map(e=>e.querySelector('.note').textContent),readingTitle:txt('#reading h2'),sections:[...document.querySelectorAll('.reading-first,details')].map(e=>({title:e.querySelector('h3,summary').textContent,text:e.querySelector('p').textContent})),privacy:{title:txt('#privacy h2'),text:txt('#privacy p')},footer:txt('footer strong')};const results=Object.keys(actual).map(k=>({key:k,equal:JSON.stringify(actual[k])===JSON.stringify(c[k])}));const fields={title:txt('#request h2'),intro:txt('#request .intro'),name:txt('[for=name]'),email:txt('[for=email]'),quantity:txt('[for=quantity]'),record:txt('[for=record]'),unsure:txt('option[value=""]'),context:txt('[for=context]'),submit:txt('[type=submit]'),errorSummary:txt('.error-summary'),nameError:txt('#name-error'),emailError:txt('#email-error'),quantityError:txt('#quantity-error'),success:txt('.success')};return {results,form:Object.entries(fields).map(([k,v])=>({key:k,equal:v===c.form[k]})),privacyExact:txt('.privacy-line')===c.form.privacyPrefix+c.form.privacyLink+c.form.privacySuffix,nav:[...document.querySelectorAll('a')].map(e=>({text:e.textContent,href:e.getAttribute('href'),targetExists:!!document.querySelector(e.getAttribute('href'))}))}},copy);
// Keyboard disclosure collapse/reopen from expanded state.
const first=page.locator('summary').first();await first.focus();await page.keyboard.press('Enter');const collapsed=await page.locator('details').first().evaluate(e=>e.open);await page.keyboard.press('Space');d.actions.disclosure={afterEnter:collapsed,afterSpace:await page.locator('details').first().evaluate(e=>e.open)};
await page.locator('.menu-trigger').click();const menu={open:await page.locator('dialog').evaluate(e=>({modal:e.matches(':modal'),focus:document.activeElement.className}))};
menu.tab=[];for(let i=0;i<8;i++){await page.keyboard.press('Tab');menu.tab.push(await page.evaluate(()=>({text:document.activeElement.textContent.trim(),inside:!!document.activeElement.closest('dialog')})))}
await page.locator('.close-menu').focus();await page.keyboard.press('Shift+Tab');menu.reverse=await page.evaluate(()=>({text:document.activeElement.textContent,inside:!!document.activeElement.closest('dialog')}));await page.locator('#name').evaluate(e=>e.focus());menu.backgroundFocusAttempt=await page.evaluate(()=>({id:document.activeElement.id,inside:!!document.activeElement.closest('dialog')}));await page.keyboard.press('Escape');menu.escape=await page.evaluate(()=>({open:document.querySelector('dialog').open,focus:document.activeElement.className}));
await page.locator('.menu-trigger').click();await page.locator('.close-menu').click();menu.close=await page.evaluate(()=>({open:document.querySelector('dialog').open,focus:document.activeElement.className}));
await page.locator('.menu-trigger').click();await page.locator('dialog a[href="#comparison"]').click();menu.link=await page.evaluate(()=>({hash:location.hash,open:document.querySelector('dialog').open,focus:document.activeElement.className}));d.actions.menu=menu;
// Submit through actual local controls with invented details only.
await page.locator('#context').fill('Invented multiline context.\nKeep this text when returning to a record.');await page.locator('[type=submit]').click();
const state=()=>page.evaluate(()=>({focus:document.activeElement.id,summary:!document.querySelector('.error-summary').hidden,success:!document.querySelector('.success').hidden,values:[...document.querySelectorAll('input,select,textarea')].map(e=>({id:e.id,value:e.value,invalid:e.getAttribute('aria-invalid'),description:e.getAttribute('aria-describedby')})),errors:[...document.querySelectorAll('.error')].filter(e=>!e.hidden).map(e=>e.textContent)}));
d.actions.empty=await state();await page.locator('form').screenshot({path:path.join(out,'invalid-form.png')});
await page.locator('#name').fill('   ');await page.locator('[type=submit]').click();d.actions.whitespaceName=await state();await page.locator('#name').fill('Example Reader');await page.locator('#email').fill('wrong');await page.locator('[type=submit]').click();d.actions.badEmail=await state();await page.locator('#email').fill('reader@example.invalid');
d.actions.quantity=[];for(const value of ['0','-2','0.001']){await page.locator('#quantity').fill(value);await page.locator('[type=submit]').click();d.actions.quantity.push({value,...await state()})}
await page.locator('#record').selectOption('1');await page.locator('[type=submit]').click();d.actions.success=await state();await page.locator('form').screenshot({path:path.join(out,'success-form.png')});await page.locator('#record').selectOption('');d.actions.optionalReset=await page.locator('#record').inputValue();
await page.locator('.privacy-line a').click();d.actions.privacyAnchor=await page.evaluate(()=>({hash:location.hash,scrollY}));await page.locator('#overview a').click();d.actions.cta=await page.evaluate(()=>({hash:location.hash,scrollY,context:document.querySelector('#context').value}));
await page.goto(url);await page.locator('.menu-trigger').click();await page.screenshot({path:path.join(out,'runtime-mobile-menu-390.png'),fullPage:true});
fs.writeFileSync(path.join(out,'observations.json'),JSON.stringify(d,null,2));console.log(JSON.stringify({identities,runtime:d.runtime,copy:d.copy,views:d.views.map(v=>({width:v.width,initialHeight:v.initial.height,expandedHeight:v.expanded.height,smallTargets:v.initial.smallTargets,clippingCandidates:v.initial.clippingCandidates,openCount:v.openCount})),actions:d.actions,network:d.network},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
