const fs=require('fs'),path=require('path'),crypto=require('crypto');const root=__dirname;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const runtime=JSON.parse(fs.readFileSync(path.join(root,'evidence/runtime.json'),'utf8'));
const external=['D:/23MySec/99_workspace/gate4-method-validation-2026-09-07/input.md','D:/23MySec/skills/brand-applied-visual-design/SKILL.md','D:/23MySec/brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','D:/23MySec/brand/visual/TIO2_MALAYSIA_PRIMARY_CTA_ACCESSIBILITY_ADDENDUM_V1.0.md','D:/23MySec/99_workspace/gate4-method-validation-2026-09-07/input-assets/Inter-Variable.ttf'];
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):[path.join(dir,e.name)]);
const assets=walk(root).filter(p=>!['report.md','asset-inventory.json'].includes(path.basename(p))).map(p=>{const rel=path.relative(root,p).replaceAll('\\','/'),b=fs.readFileSync(p),exp=runtime.exports.find(e=>e.path===rel);return {path:rel,role:exp?'rendered visual evidence':rel.endsWith('.ttf')?'bundled font':rel.startsWith('evidence/')?'raw runtime observation':rel.endsWith('.cjs')?'local evidence tooling':'editable visual source',sourceVersion:'design-v1',sourceIdentity:exp?runtime.sourceFiles:rel.endsWith('.ttf')?external[4]:'original exercise authoring',logicalWidth:exp?.logicalViewport.width??null,physicalWidth:exp?.physicalWidth??null,physicalHeight:exp?.physicalHeight??null,scale:exp?.scale??null,state:exp?.state??'source / not a raster state',bytes:b.length,sha256:sha(b)}});
const externalInputs=external.map(p=>{const b=fs.readFileSync(p);return {path:p,bytes:b.length,sha256:sha(b)}});
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),svg=html.match(/<svg[\s\S]*?<\/svg>/)[0];
const inventory={version:'design-v1',reportSelfHashExcluded:true,inventorySelfHashExcluded:true,previewEntry:'index.html',relativePreviewDependencies:['styles.css','app.js','assets/Inter-Variable.ttf'],externalInputs,embeddedAssets:[{path:'index.html#illustration svg',role:'original redundant comparison diagram',sourceIdentity:'original inline SVG in index.html, viewBox 0 0 300 210',logicalWidth:300,physicalWidth:null,scale:null,state:'media-present',bytes:Buffer.byteLength(svg),sha256:sha(Buffer.from(svg))}],renderer:{chrome:runtime.renderer,playwright:runtime.playwrightVersion,node:runtime.node,packages:'C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules',network:'file URLs, no HTTP(S) requests recorded'},assets};
fs.writeFileSync(path.join(root,'asset-inventory.json'),JSON.stringify(inventory,null,2));
const check=JSON.parse(fs.readFileSync(path.join(root,'asset-inventory.json'),'utf8'));for(const a of check.assets){if(sha(fs.readFileSync(path.join(root,a.path)))!==a.sha256)throw Error('Hash mismatch '+a.path)}
for(const s of runtime.sourceFiles)if(sha(fs.readFileSync(path.join(root,s.path)))!==s.sha256)throw Error('Export source mismatch '+s.path);
console.log(JSON.stringify({assets:check.assets.length,pngs:check.assets.filter(a=>a.path.endsWith('.png')).length,hashesVerified:true,sourceCombination:runtime.sourceFiles},null,2));
