const fs=require('fs'),crypto=require('crypto'),{spawnSync}=require('child_process');
const out='D:/23MySec/pages/resources/brazil-trade/04_planning/gate3-v0.1';
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const binding=read(out+'/input-binding.json'),runtime=read(out+'/diagnostic_support/render/runtime.json');
for(const v of [...binding.approvedInputs,...binding.authorities,...binding.sharedFiles,...binding.dependencies,binding.sharedConsumer,runtime.source,...runtime.images]){const actual=id(v.path);if(actual.sha256!==v.sha256||actual.bytes!==v.bytes)throw Error('Binding drift: '+v.path)}
if(runtime.status!=='PASS'||runtime.results.some(r=>r.status!=='PASS')||fs.readdirSync(out+'/approval_core').length)throw Error('Preflight prerequisites failed');
const visual={status:'EXECUTION_VISUAL_SELF_CHECK_PASS',reviewedAt:new Date().toISOString(),source:runtime.source,method:'Actual view_image inspection of all three full-page overviews, 38 native readable overlapping clips (1440:10,768:11,390:17), and five menu/Cookie state images. All 46 images opened; no inference from export success alone.',coverage:runtime.images,observations:['All eight modules through Footer visible at every width; no truncation or hidden body blocks.','Four exact-entity duty bands retain USD/t and China-origin combined producer/exporter context; long LB names wrap within the correct record.','Mobile labeled table records preserve each original header-cell relationship; timeline dates remain attached to official event and meaning.','Anatase and cumulative Ex-001 thresholds, 802/850 relationship and Siegwerk caveat stay separate and readable.','Public-interest procedure versus outcome, Malaysia-origin limitation, buyer action owners and all official sources with review date remain legible.','Menu and Cookie controls fit both narrow widths; Cookie actions use teal borders/text and focus state is visible.'],unresolvedFindings:[]};
save(out+'/diagnostic_support/visual-preflight.json',visual);
const preflight={pageId:binding.pageId,status:'PASS_FOR_FORMAL_RENDER',checkedAt:new Date().toISOString(),role:'EXECUTION_SELF_CHECK_NOT_INDEPENDENT_APPROVAL',candidate:runtime.source,checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks'].map(k=>[k,'PASS'])),dependencies:binding.dependencies,sharedConsumer:binding.sharedConsumer,approvedInputs:binding.approvedInputs,inputBinding:id(out+'/input-binding.json'),runtimeEvidence:id(out+'/diagnostic_support/render/runtime.json'),visualEvidence:id(out+'/diagnostic_support/visual-preflight.json'),evidenceTypes:['SOURCE_INSPECTION','ACTUAL_RUNTIME','ACTUAL_IMAGE_INSPECTION','LOCAL_SIMULATION'],formalExportsGenerated:false,limitations:['Local navigation intention only; external receivers and production consent/storage not exercised.','No new live legal research; approved dated explanation and refresh dependency preserved.'],unresolvedRequiredFindings:[]};
save(out+'/preflight-record.json',preflight);
const result=spawnSync(process.execPath,['D:/23MySec/skills/responsive-wireframe-design/scripts/check-preflight-record.mjs',out+'/preflight-record.json'],{encoding:'utf8'});
fs.writeFileSync(out+'/diagnostic_support/preflight-validator.json',result.stdout);if(result.status!==0)throw Error(result.stderr||result.stdout);
const frozen={pageId:binding.pageId,status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',frozenAt:new Date().toISOString(),source:id(runtime.source.path),inputBinding:id(out+'/input-binding.json'),approvedInputs:binding.approvedInputs,authorities:binding.authorities,sharedConsumer:binding.sharedConsumer,sharedFiles:binding.sharedFiles,dependencies:binding.dependencies,preflight:id(out+'/preflight-record.json'),validator:id(out+'/diagnostic_support/preflight-validator.json'),formalExportsExistedAtFreeze:false,role:'GATE3_EXECUTION_ONLY',unresolvedFindings:[]};
if(fs.existsSync(out+'/freeze-record.json'))throw Error('Already frozen');save(out+'/freeze-record.json',frozen);
fs.appendFileSync(out+'/diagnostic_support/input-binding-failure-01.md','\nResolution — 2026-09-07: project control confirmed an administrative SHA transcription omission in the old Manifest/dispatch; approved B was unchanged. Current Manifest V0.5 and serial control V1.5 correct the expected SHA to bb83adeb1a2a21ee7b7c4d854d569d5b73ba6a9fc75421a387fe9eeded5b6c5f. Fresh build recomputed and matched A/B/C/Review, created the first candidate only after success, and actual runtime plus visual preflight passed. Original failed build preserved as build-input-failed.cjs. Input failure closed; no source repair or prior candidate PASS inherited.\n');
console.log(JSON.stringify({status:preflight.status,source:frozen.source,frozenAt:frozen.frozenAt}));
