const fs=require('fs'),path=require('path'),crypto=require('crypto'),out=path.resolve(__dirname,'..').replaceAll('\\','/'),page=out.split('/04_planning/')[0];
const id=p=>({path:p,bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const report=out+'/PRODUCT-PROC-SU_GATE4_VISUAL_AND_EXECUTION_REPORT_V0.1.md',selfcheck=page+'/05_review/PRODUCT-PROC-SU_GATE4_EXECUTION_SELF_CHECK_V0.1.md',manifest=page+'/PRODUCT-PROC-SU_CURRENT_GATE_BASELINE_MANIFEST_V0.7_DRAFT.md';
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(d+'/'+e.name):[d+'/'+e.name]);}
const excluded=new Set([out+'/approval_core/asset-inventory.json',out+'/evidence_index.json',out+'/diagnostic_support/final-receipt.json']);
const files=[...walk(out).filter(p=>!excluded.has(p)),selfcheck,manifest].map(id);
fs.writeFileSync(out+'/approval_core/asset-inventory.json',JSON.stringify({workset_id:'SU-G4-COMPLETE-V01',freeze_id:'SU-G4-COMPLETE-V01-F01',scope:'All page workset files plus selfcheck and proposed Manifest. Includes historical/failed diagnostics, not an approval of each asset.',files},null,2));
const evidence={workset_id:'SU-G4-COMPLETE-V01',freeze_id:'SU-G4-COMPLETE-V01-F01',status:'COMPLETE_VISUAL_FROZEN / DRAFT_FOR_PROJECT_CONTROL_REVIEW',sourceFreeze:id(out+'/approval_core/source-freeze.json'),inputIndex:id(out+'/input_index.json'),exportInventory:id(out+'/approval_core/export-inventory.json'),assetInventory:id(out+'/approval_core/asset-inventory.json'),report:id(report),selfcheck:id(selfcheck),candidateManifest:id(manifest),direction:id(out+'/4A-direction-check.json'),evidence:[{type:'SOURCE_INSPECTION',path:out+'/diagnostic_support/formal-r1-checks.json',scope:'Exact upstream main/scripts/style, shared slots, B text and frozen input identities'},{type:'ACTUAL_RUNTIME',path:out+'/diagnostic_support/formal-r1-checks.json',scope:'Actual local viewport geometry, fonts, normal/hover/keyboard, fragments, menu/cookie and anchor'},{type:'ACTUAL_RUNTIME',path:out+'/diagnostic_support/additional-checks.json',scope:'Source neighbor-glyph hit tests and text inset; measured geometry delta'},{type:'STATIC_VISUAL',path:out+'/diagnostic_support/visual-readback.json',scope:'18 formal PNGs opened; 18 original-scale complete-page segments opened; overview limitation explicit'},{type:'LOCAL_SIMULATION',path:out+'/diagnostic_support/formal-r1-checks.json',scope:'Outbound navigation intents only; no receiver'},{type:'LOCAL_SIMULATION',path:out+'/diagnostic_support/additional-checks.json',scope:'200% equivalent reflow; not native zoom'}],history:[out+'/diagnostic_support/4a-r1',out+'/diagnostic_support/4a-r1-checks.json',out+'/diagnostic_support/collection-failure.md'],pending:['Final independent review','User approval','Native zoom, real devices, other engines and assistive technology','Production routes, receiver/prefill persistence and consent technology','External-source freshness'],stop:'Frozen HTML/CSS/dependencies/images are immutable. No Gate6 or production work authorized.'};
fs.writeFileSync(out+'/evidence_index.json',JSON.stringify(evidence,null,2));
const freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json')),exp=JSON.parse(fs.readFileSync(out+'/approval_core/export-inventory.json'));
const checks=[...freeze.inputs,...freeze.dependencies,...exp.core,...exp.readableSupport,...files,id(out+'/approval_core/asset-inventory.json'),id(out+'/evidence_index.json')].map(i=>({path:i.path,pass:id(i.path).sha256===i.sha256&&id(i.path).bytes===i.bytes}));
const errors=checks.filter(c=>!c.pass),receipt={workset_id:evidence.workset_id,freeze_id:evidence.freeze_id,at:new Date().toISOString(),checks,errors,deliverables:[report,selfcheck,manifest,out+'/evidence_index.json',out+'/approval_core/source-freeze.json',out+'/approval_core/export-inventory.json',out+'/approval_core/asset-inventory.json'].map(id)};
fs.writeFileSync(out+'/diagnostic_support/final-receipt.json',JSON.stringify(receipt,null,2));console.log(JSON.stringify({checks:checks.length,errors,deliverables:receipt.deliverables}));if(errors.length)process.exitCode=1;
