const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=path.resolve(__dirname,'..').replaceAll('\\','/'),root='D:/23MySec',mode=process.argv[2]||'preflight',run=process.argv[3]||'r1';
const target=out+'/PRODUCT-PROC-SU_GATE4_COMPLETE_VISUAL_V0.1.html',g3=root+'/pages/products/sulfate-process/04_planning/gate3-v0.1/PRODUCT-PROC-SU_GATE3_RESPONSIVE_WIREFRAME_V0.1.html';
const dest=mode==='formal'?out+'/approval_core':out+'/diagnostic_support/'+mode+'-'+run;
fs.mkdirSync(dest,{recursive:true});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),id=p=>({path:p,bytes:fs.statSync(p).size,sha256:sha(p)}),records=[],assets=[],errors=[];
function check(name,pass,data={},type='ACTUAL_RUNTIME'){records.push({name,pass:!!pass,data,evidenceType:type});if(!pass)errors.push(name);}
const norm=s=>s.replace(/\s+/g,' ').replace(/\s+([.,;:])/g,'$1').trim();
const lum=s=>s.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,b,i)=>a+b*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>(Math.max(lum(a),lum(b))+.05)/(Math.min(lum(a),lum(b))+.05);
async function metrics(loc){return loc.evaluate(e=>{let s=getComputedStyle(e),r=e.getBoundingClientRect();function bg(n){while(n){let c=getComputedStyle(n).backgroundColor;if(c!=='rgba(0, 0, 0, 0)'&&c!=='transparent')return c;n=n.parentElement}return'rgb(255, 255, 255)'}return{text:e.innerText,href:e.getAttribute('href'),width:r.width,height:r.height,x:r.x,y:r.y,font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,fg:s.color,bg:bg(e),outline:s.outlineColor,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:bg(parseFloat(s.outlineOffset)>=0?e.parentElement:e),focus:e.matches(':focus-visible'),hover:e.matches(':hover')}})}
async function focus(page,loc){await page.mouse.move(0,0);await loc.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return loc.evaluate(e=>e===document.activeElement&&e.matches(':focus-visible'))}
async function clean(page){await page.waitForTimeout(50);await page.evaluate(()=>document.activeElement.blur());await page.mouse.move(0,0);await page.waitForTimeout(30)}
async function capture(page,w,name,opts={}){const file=dest+'/'+w+'-'+name+'.png';if(fs.existsSync(file))throw Error('Refuse overwrite '+file);if(!opts.state)await clean(page);let clip=opts.clip;if(opts.selector){await page.evaluate(()=>scrollTo(0,0));const r=await page.locator(opts.selector).boundingBox();clip={x:0,y:Math.max(0,Math.floor(r.y)-8),width:w,height:Math.ceil(r.height)+16};}
const buf=await page.screenshot({path:file,fullPage:!!opts.full||!!clip,clip});const state=await page.evaluate(()=>({active:document.activeElement.tagName,focused:[...document.querySelectorAll('a:focus-visible,button:focus-visible')].map(e=>e.textContent),hovered:[...document.querySelectorAll('a:hover,button:hover')].map(e=>e.textContent)}));if(!opts.state)check(w+'/'+name+'/clean capture',state.focused.length===0&&state.hovered.length===0,state);assets.push({...id(file),pixelWidth:buf.readUInt32BE(16),pixelHeight:buf.readUInt32BE(20),viewport:{width:w,height:w===390?844:900},dpr:1,state:opts.state||'normal',region:opts.selector||opts.region||(opts.full?'full page':'viewport'),clip:clip||null,sourceSha256:sha(target),cssSha256:sha(out+'/visual-direction.css'),evidenceType:'STATIC_VISUAL',observedCaptureState:state});}
async function controls(page,selector,w,label){const all=page.locator(selector);for(let i=0;i<await all.count();i++){const e=all.nth(i);if(!await e.isVisible())continue;await e.scrollIntoViewIfNeeded();await clean(page);const n=await metrics(e),c=n.text.trim()?contrast(n.fg,n.bg):99;check(`${w}/${label}/${i}/normal`,n.width>=44&&n.height>=44&&c>=4.5,{...n,contrast:c});await e.hover();let h=await metrics(e),hc=h.text.trim()?contrast(h.fg,h.bg):99;check(`${w}/${label}/${i}/hover`,h.hover&&hc>=4.5&&h.width===n.width&&h.height===n.height,{...h,contrast:hc});let reach=await focus(page,e),f=await metrics(e),fc=contrast(f.outline,f.outlineBg);check(`${w}/${label}/${i}/keyboard`,reach&&f.outlineWidth>=3&&fc>=3,{...f,contrast:fc});}}
async function sourceProbe(page,w){const a=page.locator('.m2 p>a');for(const s of ['normal','hover','focus']){await a.scrollIntoViewIfNeeded();await clean(page);if(s==='hover')await a.hover();if(s==='focus')await focus(page,a);let m=await metrics(a);const hit=await a.evaluate(e=>{const r=e.getBoundingClientRect(),same=(x,y)=>{let t=document.elementFromPoint(x,y);return t===e||e.contains(t)},bad=[];for(let y=0;y<44;y++)for(let x=0;x<44;x++){let px=r.x+(r.width-44)/2+x+.5,py=r.y+(r.height-44)/2+y+.5;if(!same(px,py))bad.push([px,py]);}const edge=[];for(const x of [.5,r.width/2,r.width-.5])for(const y of [.5,r.height/2,r.height-.5])if(!same(r.x+x,r.y+y))edge.push([x,y]);const n=e.nextSibling,range=document.createRange();range.setStart(n,0);range.setEnd(n,1);const p=range.getBoundingClientRect();const nextHit=document.elementFromPoint(p.x+p.width/2,p.y+p.height/2);const rs=getComputedStyle(e);return{continuousPixels:1936,misses:bad.length,edgeMisses:edge,rect:r.toJSON(),period:p.toJSON(),periodOwnHit:nextHit===e||e.contains(nextHit),periodGap:p.x-r.right,periodSameLine:p.y>=r.y&&p.bottom<=r.bottom,focusInset:rs.outlineOffset,clientRects:e.getClientRects().length}});check(`${w}/FTC/${s}/continuous hit`,m.width>=44&&m.height>=44&&!hit.misses&&!hit.edgeMisses.length&&!hit.periodOwnHit,hit);check(`${w}/FTC/${s}/contrast state`,contrast(m.fg,m.bg)>=4.5&&(s!=='focus'||m.focus)&&(s!=='hover'||m.hover),m);if(mode==='4a'||mode==='formal'&&s!=='normal')await capture(page,w,'ftc-'+s,{selector:'.m2 p:has(>a)',state:s==='normal'?undefined:'actual '+s});}}
// Fragmented inline source link: validate each painted line, not its union bounding box.
async function sourceProbe(page,w){const a=page.locator('.m2 p>a');for(const s of ['normal','hover','focus']){await a.evaluate(e=>e.scrollIntoView({block:'center'}));await clean(page);if(s==='hover')await a.hover();if(s==='focus')await focus(page,a);let m=await metrics(a);const hit=await a.evaluate(e=>{const rects=[...e.getClientRects()],same=(x,y)=>{let t=document.elementFromPoint(x,y);return t===e||e.contains(t)},fragments=rects.map(r=>{let misses=0,edgeMisses=[];for(let y=0;y<44;y++)for(let x=0;x<44;x++)if(!same(r.x+(r.width-44)/2+x+.5,r.y+(r.height-44)/2+y+.5))misses++;for(const x of [.5,r.width/2,r.width-.5])for(const y of [.5,r.height/2,r.height-.5])if(!same(r.x+x,r.y+y))edgeMisses.push([x,y]);return{rect:r.toJSON(),misses,edgeMisses}});const n=e.nextSibling,range=document.createRange();range.setStart(n,0);range.setEnd(n,1);const p=range.getBoundingClientRect(),last=rects.at(-1);return{fragments,period:p.toJSON(),periodOwnHit:same(p.x+p.width/2,p.y+p.height/2),periodGap:p.x-last.right,periodSameLine:p.y>=last.y&&p.bottom<=last.bottom,continuousPixelsPerFragment:1936}});check(`${w}/FTC/${s}/fragment continuous hit`,hit.fragments.every(f=>f.rect.width>=44&&f.rect.height>=44&&!f.misses&&!f.edgeMisses.length)&&!hit.periodOwnHit,hit);check(`${w}/FTC/${s}/natural period`,Math.abs(hit.periodGap)<.1&&hit.periodSameLine,hit);check(`${w}/FTC/${s}/contrast state`,contrast(m.fg,m.bg)>=4.5&&(s!=='focus'||m.focus)&&(s!=='hover'||m.hover),m);if(mode==='4a'||mode==='formal'&&s!=='normal'){await page.evaluate(()=>scrollTo(0,0));if(s==='hover')await a.hover();if(s==='focus')await focus(page,a);let r=await page.locator('.m2 p:has(>a)').boundingBox(),sy=await page.evaluate(()=>scrollY);await capture(page,w,'ftc-'+s,{clip:{x:0,y:Math.floor(r.y+sy)-8,width:w,height:Math.ceil(r.height)+16},state:s==='normal'?undefined:'actual '+s,region:'FTC source paragraph'});let after=await metrics(a);check(`${w}/FTC/${s}/capture state`,s==='normal'?!after.focus&&!after.hover:s==='focus'?after.focus:after.hover,after);}}}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const original=fs.readFileSync(g3,'utf8'),html=fs.readFileSync(target,'utf8');check('unchanged G3 main and scripts',['main','script','style'].every(t=>JSON.stringify(original.match(new RegExp('<'+t+'[>][\\s\\S]*?</'+t+'>','g')))===JSON.stringify(html.match(new RegExp('<'+t+'[>][\\s\\S]*?</'+t+'>','g')))),{},'SOURCE_INSPECTION');
const shared=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'PRODUCT-000',fontSrc:'dependencies/Inter-Variable.ttf',primaryLogoSrc:'dependencies/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'dependencies/tio2-malaysia-reverse-monochrome-v0.1.svg'});check('shared owner exact assembly',['header','footer','dialog','style','behavior'].every(k=>html.includes(shared[k])),{},'SOURCE_INSPECTION');
let B=fs.readFileSync(root+'/pages/products/sulfate-process/04_planning/PRODUCT-PROC-SU_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').split('## Buyer Clean public copy')[1];const expected=norm(B.replace(/^### (Breadcrumb|Hero)\s*$/gm,'').replace(/<a[^>]*><\/a>/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#+\s*/gm,'').replace(/\*\*/g,''));
if(mode==='formal'){const f=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json'));for(const item of [...f.inputs,...f.dependencies])check('freeze '+item.path,sha(item.path)===item.sha256,item,'SOURCE_INSPECTION');}
for(const w of [1440,768,390]){const context=await browser.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage(),requests=[];await context.route(/^https?:/,r=>{requests.push(r.request().url());return r.abort()});page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(target).href);await page.evaluate(()=>document.fonts.ready);await sourceProbe(page,w);
if(mode==='4a'){await capture(page,w,'grade-direction',{selector:'.m3'});await context.close();continue;}
const actual=await page.locator('main').evaluate(e=>{let w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode.textContent);return a.join(' ')});check(w+'/complete B',norm(actual)===expected,{actual:norm(actual),expected});
const geometry=await page.evaluate(()=>{const box=e=>e.getBoundingClientRect().toJSON();return{width:document.documentElement.scrollWidth,header:box(document.querySelector('header')),modules:[...document.querySelectorAll('main section')].map(e=>({class:e.className,rect:box(e)})),grades:[...document.querySelectorAll('.grades article')].map(e=>({text:e.querySelector('h3').textContent,rect:box(e),h:box(e.querySelector('h3')),p:box(e.querySelector('p')),a:box(e.querySelector('a'))})),evaluations:[...document.querySelectorAll('.evaluation article')].map(e=>({title:e.querySelector('h3').textContent,rect:box(e),h:box(e.querySelector('h3')),p:box(e.querySelector('p'))})),clipped:[...document.querySelectorAll('main *')].filter(e=>['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis').map(e=>e.tagName),mediaForms:document.querySelectorAll('main img,main form,main input,main select').length,images:[...document.images].map(e=>({loaded:e.complete&&e.naturalWidth>0,src:e.getAttribute('src')})),fonts:document.fonts.check('17px Inter')}});
check(w+'/layout',geometry.width===w&&geometry.modules.length===5&&!geometry.clipped.length&&geometry.mediaForms===0&&geometry.header.height===(w===1440?84:64),geometry);
check(w+'/five Grade relationships',JSON.stringify(geometry.grades.map(g=>g.text))===JSON.stringify(['M-996','M-2196','M-108','M-52','M-2377'])&&geometry.grades.every(g=>w===1440?g.h.x<g.p.x&&g.p.x<g.a.x:w===768?g.h.x<g.p.x&&g.a.y>=g.p.bottom:g.h.y<g.p.y&&g.p.y<g.a.y),geometry.grades);
check(w+'/evaluation relationships',geometry.evaluations.length===3&&geometry.evaluations.every(g=>w===390?g.h.y<g.p.y:g.h.x<g.p.x),geometry.evaluations);check(w+'/loaded assets',geometry.fonts&&geometry.images.every(e=>e.loaded),geometry.images);
const cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');let dom=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'main h1'}),fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(w+'/actual Inter',fonts.fonts.some(f=>f.familyName.includes('Inter')&&f.isCustomFont),fonts);
await controls(page,'header a,header button,main a,footer a,footer button',w,'page');
const links=page.locator('a');for(let i=0;i<await links.count();i++){let a=links.nth(i);if(!await a.isVisible())continue;const href=await a.getAttribute('href');await a.click();if(href==='#sulfate-grades'){const anchor=await page.locator('#sulfate-grades').evaluate(e=>({active:e===document.activeElement,top:e.getBoundingClientRect().y,hash:location.hash}));check(w+'/anchor click focus',anchor.active&&anchor.hash==='#sulfate-grades'&&anchor.top>=0,anchor);}else{let intent=await page.evaluate(()=>window.localNavigation.at(-1));check(w+'/outbound '+i,intent.href===href&&JSON.stringify(intent.context)===JSON.stringify(['/request-a-quote/','/request-documents/'].includes(href)?{source_page_id:'PRODUCT-PROC-SU'}:{}),intent,'LOCAL_SIMULATION');}}
await page.evaluate(()=>scrollTo(0,0));await focus(page,page.locator('a[href="#sulfate-grades"]'));await page.keyboard.press('Enter');check(w+'/anchor keyboard',await page.locator('#sulfate-grades').evaluate(e=>e===document.activeElement),{});
if(w<1101){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();check(w+'/menu entry isolation',await page.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'),{});await controls(page,'.menuButton,.mobileNav a',w,'menu');await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');let cy=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');check(w+'/menu focus cycle',cy&&await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});if(mode==='formal'){await page.evaluate(()=>scrollTo(0,0));await focus(page,page.locator('.mobileNav a[aria-current]'));await capture(page,w,'menu',{state:'actual Products keyboard focus'});}await page.keyboard.press('Escape');check(w+'/menu Escape',await page.locator('.menuButton').evaluate(e=>e===document.activeElement)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/products/"]').click();check(w+'/menu selection close',await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});check(w+'/menu breakpoint',await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert),{});await page.setViewportSize({width:w,height:w===390?844:900});}
await page.locator('#cookie-trigger').click();check(w+'/Cookie entry',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(page,'.cookie-actions>*',w,'cookie');await page.locator('[data-cookie-close]').focus();await page.keyboard.press('Shift+Tab');let cycle=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');check(w+'/Cookie cycle',cycle&&await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await page.locator('main a').first().evaluate(e=>e.focus());check(w+'/Cookie isolation',await page.locator('dialog').evaluate(e=>e.contains(document.activeElement)),{});if(mode==='formal'){await focus(page,page.locator('[data-cookie-close]'));await capture(page,w,'cookie',{state:'actual Close keyboard focus'});}await page.keyboard.press('Escape');await page.waitForTimeout(50);check(w+'/Cookie Escape',await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();await page.waitForTimeout(50);check(w+'/Cookie Close',await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),{});
await page.evaluate(()=>scrollTo(0,0));await capture(page,w,'full',{full:true});
// Native, overlapping full-page scan; no shrink-to-fit text evidence.
const height=await page.evaluate(()=>document.documentElement.scrollHeight);if(mode!=='formal')for(let top=0,i=1;top<height;top+=800,i++){await capture(page,w,'readable-'+String(i).padStart(2,'0'),{clip:{x:0,y:top,width:w,height:Math.min(900,height-top)},region:'continuous full-page scan y='+top});}
if(mode==='formal'){for(const [name,sel,state] of [['hero-hover','.m1 .actions a:first-child','hover'],['rfq-focus','.m5 .actions a','focus'],['grade-focus','.grades article:nth-child(3) a','focus'],['comparison-hover','.evaluation article:last-child a','hover']]){if(w!==390&&name==='grade-focus'||w!==768&&name==='comparison-hover'||w!==1440&&['hero-hover','rfq-focus'].includes(name))continue;const a=page.locator(sel);await a.scrollIntoViewIfNeeded();await clean(page);if(state==='hover')await a.hover();else await focus(page,a);await capture(page,w,name,{state:'actual '+state});}}
check(w+'/no external fetch',!requests.length,{requests});await context.close();
}
if(mode!=='4a'){for(const js of [true,false]){const c=await browser.newContext({viewport:{width:390,height:844},javaScriptEnabled:js}),p=await c.newPage();await p.goto(pathToFileURL(target).href+'#sulfate-grades');const h=await p.locator('#sulfate-grades').boundingBox();check('direct fragment js='+js,h.y>=0&&h.y<100,{rect:h});await c.close();}}
}catch(e){errors.push(e.stack)}await browser.close();let result={workset_id:'SU-G4-COMPLETE-V01',mode,run,at:new Date().toISOString(),source:id(target),css:id(out+'/visual-direction.css'),runtime:{chrome:browser.version(),node:process.version,playwright:'1.62.1',headless:true,externalRequestsAllowed:false},records,errors,assets};fs.writeFileSync(out+'/diagnostic_support/'+mode+'-'+run+'-checks.json',JSON.stringify(result,null,2));console.log(JSON.stringify({mode,records:records.length,errors,images:assets.length}));if(errors.length)process.exitCode=1;})();
