// Independent, read-only candidate audit. Only writes this reviewer directory.
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/documents/04_planning/',old=base+'d32-gate4-v0.1',now=base+'d32-gate4-v0.2';
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const checks=[],states=[],comparisons=[],identities=[];const check=(id,pass,actual)=>checks.push({id,pass:!!pass,actual});
const bind=(r,group)=>{const actual={bytes:fs.statSync(r.path).size,sha256:hash(r.path)},pass=actual.bytes===r.bytes&&actual.sha256===r.sha256;identities.push({group,path:r.path,pass,actual});return pass;};
const f=json(now+'/freeze-return.json'),o=json(old+'/freeze.json'),snapshot=json(now+'/freeze.json'),lock=json(now+'/source-lock.json'),ei=json(now+'/evidence-index.json');
for(const [group,rows] of [['return',f.files],['snapshot',snapshot.files],['old',o.files],['lock',[...lock.sources,...lock.dependencies]]])check(group+'_identities',rows.map(r=>bind(r,group)).every(Boolean),rows.length);
for(const [name,obj] of [['return',f],['snapshot',snapshot],['old',o]])check(name+'_digest',crypto.createHash('sha256').update(JSON.stringify(obj.files)).digest('hex')===obj.bundle_id,obj.bundle_id);
check('expected_return_bundle',f.bundle_id==='bd12263d164a68b97f0095b311f2dc092f5662342d7c4ebc7f4a53589c010ed9');
check('expected_return_freeze',hash(now+'/freeze-return.json')==='5db8a438c1f60776d53e243a9223075415e07b50c7965582ad5dff325b76f722');
check('old_74_members',o.files.length===74);
for(const filename of ['DOC-000_D32_structure.html','DOC-000_D32_behavior.js'])check('identical_'+filename,hash(old+'/'+filename)===hash(now+'/'+filename),hash(now+'/'+filename));
const oldcss=read(old+'/DOC-000_D32_structure.css'),newcss=read(now+'/DOC-000_D32_structure.css');
const delta=newcss.slice(oldcss.length);check('exact_one_CSS_delta',newcss.startsWith(oldcss)&&delta.trim()==='/* D23 design-only feedback reservation; ROOT-NARROW-VISUAL-20260921 §4. */\n@media(max-width:340px){.doc-selector #grade-error{min-height:3.3em}}',delta);
const decision=root+'/docs/architecture/ROOT_PAGE_NARROW_VISUAL_AND_DOC_FEEDBACK_DECISION_V1.0.md';check('approval_exact',hash(decision)==='6ff4253b56936ccf9838f27d7532053a501de82aec99b9ab1518b38de667f1a9'&&read(decision).includes('仅 320px 允许自然四行')&&read(decision).includes('预留两行空间'));
const arrays=Object.entries(ei).filter(([k,v])=>Array.isArray(v)&&v.every(r=>r.path));
for(const [group,rows] of arrays){for(const r of rows){const b=fs.readFileSync(r.path);check('asset_'+path.basename(r.path),bind(r,group)&&b.readUInt32BE(16)===r.width&&b.readUInt32BE(20)===r.height&&r.dpr===1,{group,path:r.path,width:r.width,height:r.height});}}
const grades=['M-350','M-510','M-896','M-996','M-2196','M-895','M-200','M-108','M-210','M-340','M-886','M-52','M-2377','CR-901'];
async function geometry(p){return p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y+scrollY,w:r.width,h:r.height}};const b=document.querySelector('#continue-request'),e=document.querySelector('#grade-error'),s=document.querySelector('#product-grade'),h=document.querySelector('h1'),hs=getComputedStyle(h);return{button:rect(b),error:{...rect(e),text:e.textContent,font:getComputedStyle(e).fontSize,lineHeight:getComputedStyle(e).lineHeight,color:getComputedStyle(e).color,clipped:e.scrollWidth>e.clientWidth||e.scrollHeight>e.clientHeight},focus:document.activeElement.id,invalid:s.getAttribute('aria-invalid'),associated:s.getAttribute('aria-describedby').split(' ').includes('grade-error'),href:b.getAttribute('href'),confirmation:document.querySelector('#grade-selected').textContent,overflow:document.documentElement.scrollWidth>innerWidth,faq:document.querySelector('#faq-question-2').getAttribute('aria-expanded'),h1:{...rect(h),text:h.textContent,size:hs.fontSize,weight:hs.fontWeight,lines:Math.round(h.getBoundingClientRect().height/parseFloat(hs.lineHeight))}}});}
async function full(p){return p.evaluate(()=>[...document.querySelectorAll('main,main *')].map((e,i)=>{const r=e.getBoundingClientRect();return{i,tag:e.tagName,id:e.id,text:e.children.length?'':e.textContent,x:r.x,y:r.y+scrollY,w:r.width,h:r.height}}));}
(async()=>{const browser=await chromium.launch({headless:true});for(const width of [1440,1024,768,390,341,340,320]){
const p=await browser.newPage({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(now+'/DOC-000_D32_structure.html').href);await p.evaluate(()=>document.fonts.ready);const currentFull=await full(p),url=p.url();
await p.locator('#faq-question-2').click();const samples=[{state:'initial',...await geometry(p)}];await p.locator('#continue-request').focus();await p.keyboard.press('Enter');samples.push({state:'error',...await geometry(p)});await p.locator('#product-grade').selectOption('M-2196');samples.push({state:'selected',...await geometry(p)});await p.locator('#product-grade').selectOption('');samples.push({state:'cleared',...await geometry(p)});
check(width+'_stable_four_states',samples.every(s=>s.button.y===samples[0].button.y&&s.button.x===samples[0].button.x),samples.map(s=>({state:s.state,y:s.button.y,errorHeight:s.error.h})));
const err=samples[1];check(width+'_error_semantics',err.error.text==='Select a product grade to continue.'&&err.focus==='product-grade'&&err.invalid==='true'&&err.associated&&p.url()===url,err);
check(width+'_feedback_font_color',samples.every(s=>s.error.font==='14px'&&s.error.lineHeight==='23.1px'&&s.error.color==='rgb(180, 35, 24)'),samples[0].error);
check(width+'_no_clipping_overlap_small_target',samples.every(s=>!s.overflow&&!s.error.clipped&&s.error.y+s.error.h<=s.button.y&&s.button.w>=44&&s.button.h>=44));
check(width+'_selected_and_clear',samples[2].confirmation==='Selected product grade: M-2196'&&samples[2].href==='/request-documents/?product=M-2196'&&samples[3].error.text===''&&samples[3].invalid===null&&samples[3].href==='#grade-selector');
check(width+'_unrelated_FAQ_retained',samples.every(s=>s.faq==='true'));
for(const grade of grades){await p.locator('#product-grade').selectOption(grade);check(width+'_route_'+grade,await p.locator('#continue-request').getAttribute('href')==='/request-documents/?product='+grade&&await p.locator('#closing-action').getAttribute('href')==='/request-documents/?product='+grade);}
check(width+'_H1_unchanged',samples[0].h1.text==='Documents for Product & Supplier Qualification'&&samples[0].h1.weight==='700'&&(width!==320||samples[0].h1.size==='36px'&&samples[0].h1.lines===4),samples[0].h1);
await p.locator('#product-grade').selectOption('');await p.locator('#closing-action').focus();await p.keyboard.press('Enter');check(width+'_closing_focus_no_nav',p.url()===url&&await p.locator('#product-grade').evaluate(e=>e===document.activeElement));check(width+'_runtime_clean',errors.length===0,errors);
await p.goto(pathToFileURL(old+'/DOC-000_D32_structure.html').href);await p.evaluate(()=>document.fonts.ready);const oldFull=await full(p),changes=currentFull.map((r,i)=>({new:r,old:oldFull[i]})).filter(r=>JSON.stringify(r.new)!==JSON.stringify(r.old));comparisons.push({width,changes});
if(width>340)check(width+'_whole_main_unchanged',changes.length===0,changes.length);else{const delta=46.1875-24;check(width+'_bounded_feedback_flow_delta',changes.every(({new:n,old:o})=>n.tag===o.tag&&n.text===o.text&&n.x===o.x&&n.w===o.w&&[0,delta].some(d=>Math.abs(n.y-o.y-d)<.1)&&[0,delta].some(d=>Math.abs(n.h-o.h-d)<.1)),changes);}
states.push({width,samples});await p.close();}
await browser.close();check('candidate_still_readonly',f.files.every(r=>hash(r.path)===r.sha256));
const result={reviewer:'/root/res_root_d32',type:'TARGETED_INDEPENDENT_REVIEW',timestamp:new Date().toISOString(),bundle:f.bundle_id,freezeSha256:hash(now+'/freeze-return.json'),evidenceGroups:arrays.map(([k,v])=>({group:k,count:v.length})),checks,states,comparisons,identities,passed:checks.filter(c=>c.pass).length,failed:checks.filter(c=>!c.pass).length};fs.writeFileSync(__dirname+'/observations.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:result.passed,failed:result.failed,failures:checks.filter(c=>!c.pass),identityRows:identities.length,evidenceGroups:result.evidenceGroups},null,2));process.exitCode=result.failed?1:0;})().catch(e=>{console.error(e);process.exitCode=2});
