const fs=require('fs'),path=require('path'),crypto=require('crypto');const out=path.resolve(__dirname,'..').replaceAll('\\','/'),root='D:/23MySec',page=root+'/pages/markets/netherlands',g3=page+'/04_planning/gate3-v0.1';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)}),destination=out+'/approval_core/source-freeze.json';if(fs.existsSync(destination))throw Error('Already frozen');
const es=JSON.parse(fs.readFileSync(root+'/pages/markets/spain/04_planning/gate4-v0.1/approval_core/source-freeze.json'));const common=es.inputs.filter(x=>!x.path.includes('/spain/')&&!x.path.includes('MARKET-EU-ES'));for(const x of common){const expected=x.path.endsWith('/GATE4_EIGHT_PAGE_SERIAL_CONTROL_V1.0.md')?'2c6e8746c68cc5d40f14eacc1a67d9053a4fec554f8b8f2f4ae6a1af0d15a63c':x.sha256;if(sha(x.path)!==expected)throw Error('Common input changed '+x.path);}
const G3=JSON.parse(fs.readFileSync(g3+'/MARKET-EU-NL_GATE3_FREEZE_RECORD_V0.1.json'));function identities(x){if(!x||typeof x!=='object')return[];return [...(x.path&&x.sha256?[x]:[]),...Object.values(x).flatMap(identities)];}for(const x of identities(G3))if(sha(x.path)!==x.sha256)throw Error('G3 identity changed '+x.path);
const additions=[page+'/MARKET-EU-NL_CURRENT_GATE_BASELINE_MANIFEST_V0.6.md',page+'/MARKET-EU-NL_CURRENT_GATE_BASELINE_MANIFEST_V0.5.md',...Object.values(G3.approvedInputs).slice(0,4).map(x=>x.path),...['GATE3_TO_GATE4_HANDOFF','GATE3_PROJECT_CONTROL_REVIEW','GATE3_PREAUTHORIZED_APPROVAL_AND_CLOSURE'].map(x=>page+'/05_review/MARKET-EU-NL_'+x+'_V0.1.md'),...['RESPONSIVE_WIREFRAME_V0.1.html','FREEZE_RECORD_V0.1.json','ASSET_INVENTORY_V0.1.json','INPUT_BINDING_V0.1.json'].map(x=>g3+'/MARKET-EU-NL_GATE3_'+x),...fs.readdirSync(g3+'/approval_core').filter(x=>x.endsWith('.png')).map(x=>g3+'/approval_core/'+x)];
const inputs=[...new Set([...common.map(x=>x.path),...additions])].map(id),target=out+'/MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html',checks=JSON.parse(fs.readFileSync(out+'/diagnostic_support/preflight-runtime-checks.json')),probe=JSON.parse(fs.readFileSync(out+'/diagnostic_support/preflight-source-probe.json'));if(checks.errors.length||probe.errors.length||checks.source.sha256!==sha(target)||probe.source.sha256!==sha(target))throw Error('Preflight failure/source drift');
const dependencies=['MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html','visual-direction.css',...fs.readdirSync(out+'/dependencies').map(x=>'dependencies/'+x)].map(x=>id(out+'/'+x));
const pics=fs.readdirSync(out+'/diagnostic_support/preflight').filter(x=>x.endsWith('.png')).map(x=>({...id(out+'/diagnostic_support/preflight/'+x),viewed:'Actually opened tools.view_image original before freeze',observation:x.includes('source-')?'Named actual state, full paragraph, exact link text and neighbors readable; continuous hit rectangle verified separately.':x.includes('footer')?'All Footer content readable, no visible focus or hover residual; runtime capture asserted BODY/no focus-visible/hover.':'Complete native region read; application/grade document distinctions retained.'}));if(pics.length!==37)throw Error('Unexpected preflight assets');
fs.writeFileSync(out+'/approval_core/preflight-record.json',JSON.stringify({date:new Date().toISOString(),status:'AUTHOR_PREFLIGHT_PASS / INDEPENDENT_REVIEW_PENDING',dependencies,runtime:id(out+'/diagnostic_support/preflight-runtime-checks.json'),sourceProbe:id(out+'/diagnostic_support/preflight-source-probe.json'),observations:pics,failedAttempt:'diagnostic_support/attempt-01 preserves initial CSS,37 PNG and failed logs; three complete-B failures were whitespace comparator defects, other inline geometry failures were actual and fixed before freeze.',limits:'G3 full screenshots viewed only as overview; current37 region/state screenshots read at native size. Desktop Chrome local sample only.'},null,2));
fs.writeFileSync(destination,JSON.stringify({freezeId:'NL-G4-V01-SOURCE-01',date:new Date().toISOString(),status:'SOURCE_FROZEN_AFTER_AUTHOR_PREFLIGHT / DRAFT_FOR_PROJECT_CONTROL_REVIEW',entry:'MARKET-EU-NL_GATE4_VISUAL_SAMPLES_V0.1.html',dependencies,inputs,preflight:id(out+'/approval_core/preflight-record.json'),scope:'Own Netherlands G3 derived visual sample, only Gate4. Stable ManifestV0.6 and batch authorization included; dynamic Status/Index/Progress excluded. Frozen source/dependencies immutable.'},null,2));console.log(JSON.stringify({freeze:id(destination),source:dependencies[0],css:dependencies[1],inputs:inputs.length,pngs:pics.length}));
