import fs from 'node:fs';import crypto from 'node:crypto';
const out='D:/23MySec/pages/conversion/thank-you/04_planning/gate3-v0.1',review='D:/23MySec/pages/conversion/thank-you/05_review';
const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');const item=(f,r)=>({...(r?{role:r}:{}),path:f,bytes:fs.statSync(f).size,sha256:hash(f)});
const pngSize=f=>{const b=fs.readFileSync(f);if(b.toString('ascii',1,4)!=='PNG')throw new Error(`Not PNG ${f}`);return{width:b.readUInt32BE(16),height:b.readUInt32BE(20)}};
const source=item(`${out}/CONV-THANK_GATE3_RESPONSIVE_WIREFRAME_V0.1.html`);const freeze=JSON.parse(fs.readFileSync(`${out}/freeze-record.json`,'utf8'));if(source.sha256!==freeze.source.sha256)throw new Error('Frozen source changed');const formalRuntime=JSON.parse(fs.readFileSync(`${out}/diagnostic_support/formal-runtime.json`,'utf8'));if(formalRuntime.status!=='PASS'||formalRuntime.source.sha256!==source.sha256||formalRuntime.checks.some(c=>c.status!=='PASS'))throw new Error('Formal runtime invalid');
const imageFiles=fs.readdirSync(`${out}/approval_core`).filter(f=>f.endsWith('.png')).sort();if(imageFiles.length!==15)throw new Error(`Expected 15 formal images, got ${imageFiles.length}`);const images=imageFiles.map(name=>{const f=`${out}/approval_core/${name}`,size=pngSize(f),m=name.match(/_(1440|768|390)_/);return{...item(f),...size,logicalWidth:Number(m?.[1]),dpr:1,state:name.includes('_MENU_')?'menu-open':name.includes('_COOKIE_')?'cookie-open':name.match(/GATE3_([^_]+)_/)?.[1].toLowerCase()+'-full'}});
const observation={status:'PASS',pageId:'CONV-THANK',evidenceType:'STATIC_VISUAL',frozenSource:source,inspectedFormalImages:images,manualRepresentativeInspection:['CONV-THANK_GATE3_DOCUMENTS_1440_FULL_V0.1.png','CONV-THANK_GATE3_QUOTE_390_FULL_V0.1.png','CONV-THANK_GATE3_DIRECT_390_MENU_V0.1.png','CONV-THANK_GATE3_DIRECT_390_COOKIE_V0.1.png'],observations:['All four state families and three required widths are present and bind the frozen source.','Representative original images were opened after formal export: Documents desktop, Quote mobile, Direct mobile menu and Direct mobile Cookie dialog.','Success content remains text plus icon; Direct contains no receipt cue.','Mobile action groups are single-column, complete and unobstructed.','The shared Footer closes every full page; Menu and Cookie overlays retain a clear exit.'],unresolvedFindings:[],recordedAt:new Date().toISOString()};fs.writeFileSync(`${out}/diagnostic_support/formal-visual-observation.json`,JSON.stringify(observation,null,2));
const reports=[`${out}/task-input-card.md`,`${out}/design-report.md`,`${review}/CONV-THANK_GATE3_EXECUTION_SELF_CHECK_V0.1.md`].map(f=>item(f));
const inventory={status:'DRAFT_FOR_PROJECT_CONTROL_REVIEW',pageId:'CONV-THANK',source,freeze:item(`${out}/freeze-record.json`),preflight:item(`${out}/preflight-record.json`),inputBinding:item(`${out}/input-binding.json`),sharedConsumer:freeze.sharedConsumer,dependencies:freeze.dependencies,approval_core:{images,reports},diagnostic_support:{directory:`${out}/diagnostic_support`,preflightRuntime:item(`${out}/diagnostic_support/runtime.json`),formalRuntime:item(`${out}/diagnostic_support/formal-runtime.json`),preflightVisualObservation:item(`${out}/diagnostic_support/visual-observation.json`),formalVisualObservation:item(`${out}/diagnostic_support/formal-visual-observation.json`),preflightChecker:item(`${out}/diagnostic_support/preflight-checker-result.json`),failureHistory:fs.readdirSync(`${out}/diagnostic_support`).filter(f=>f.startsWith('failure-')).map(f=>item(`${out}/diagnostic_support/${f}`))},unresolvedFindings:[],createdAt:new Date().toISOString()};fs.writeFileSync(`${out}/asset-inventory.json`,JSON.stringify(inventory,null,2));console.log(JSON.stringify({source,formalImages:images.length,reports:reports.length,inventory:item(`${out}/asset-inventory.json`),formalRuntime:item(`${out}/diagnostic_support/formal-runtime.json`),formalVisual:item(`${out}/diagnostic_support/formal-visual-observation.json`)},null,2));
