const fs=require('fs'),crypto=require('crypto');
const out='D:/23MySec/pages/applications/coatings/04_planning/gate4-v0.1';
const actual=p=>{const b=fs.readFileSync(p);return{bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')}};
const failures=[];let checked=0;
const verify=(label,x)=>{checked++;if(!fs.existsSync(x.path)){failures.push(label+': missing');return}const a=actual(x.path);if(a.bytes!==x.bytes||a.sha256!==x.sha256)failures.push(label+': identity mismatch')};
const freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json','utf8'));
[...freeze.inputs,...freeze.dependencies,...Object.values(freeze.bound)].forEach((x,i)=>verify('freeze-'+i,x));
const formal=JSON.parse(fs.readFileSync(out+'/diagnostic_support/formal-runtime-checks.json','utf8'));
if(formal.summary.checks!==720||formal.summary.passed!==720||formal.summary.failed!==0||formal.errors.length||formal.assets.length!==48)failures.push('formal summary');
formal.assets.forEach((x,i)=>verify('formal-asset-'+i,x));
const inventory=JSON.parse(fs.readFileSync(out+'/approval_core/asset-inventory.json','utf8'));
if(inventory.approvalCore.length!==14||inventory.readableSegments.length!==34||inventory.counts.exported!==48)failures.push('asset inventory counts');
[...inventory.approvalCore,...inventory.readableSegments].forEach((x,i)=>verify('inventory-asset-'+i,x));
const evidence=JSON.parse(fs.readFileSync(out+'/evidence_index.json','utf8'));
['candidate','visualLayer','sourceFreeze','inputIndex','direction','preflight','formalRuntime','exportInventory','assetInventory','formalVisualReadback','report','selfcheck','candidateManifest','independentReviewEntry'].forEach(k=>verify('evidence-'+k,evidence[k]));
if(evidence.workset_id!=='COAT-G4-COMPLETE-V01'||evidence.freeze_id!=='COAT-G4-COMPLETE-V01-F01'||evidence.counts.formalChecks!==720||evidence.counts.formalAssets!==48)failures.push('evidence summary');
const receipt=JSON.parse(fs.readFileSync(out+'/diagnostic_support/final-receipt.json','utf8'));verify('receipt-workset',receipt.workset);verify('receipt-evidence',receipt.evidenceIndex);
const result={at:new Date().toISOString(),status:failures.length?'FAIL':'PASS',identityChecks:checked,failures,workset:receipt.workset,evidenceIndex:receipt.evidenceIndex,candidate:receipt.candidate,freeze:receipt.freeze,formal:{checks:formal.summary.checks,passed:formal.summary.passed,failed:formal.summary.failed,assets:formal.assets.length}};
console.log(JSON.stringify(result,null,2));
if(failures.length)process.exitCode=1;
