const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const mods='C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(mods+'/playwright');
const {marked}=require(mods+'/marked');
const sharp=require(mods+'/sharp');
const root='D:/23MySec',out=path.resolve(__dirname,'..').replaceAll('\\','/');
const target=out+'/APP-COAT_GATE4_COMPLETE_VISUAL_V0.1.html';
const g3=root+'/pages/applications/coatings/04_planning/gate3-v0.3/APP-COAT_GATE3_RESPONSIVE_WIREFRAME_V0.3.html';
const copy=root+'/pages/applications/coatings/04_planning/APP-COAT_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md';
const mode=process.argv[2]||'4a';
const formal=mode==='formal';
const evidence=formal?out+'/approval_core':out+'/diagnostic_support/'+mode;
const segments=formal?out+'/diagnostic_support/readable-segments':evidence+'/readable-segments';
fs.mkdirSync(evidence,{recursive:true});fs.mkdirSync(segments,{recursive:true});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const id=p=>({path:p,relativePath:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)});
const norm=s=>s.replace(/\s+/g,' ').trim();
const records=[],assets=[],errors=[];
function check(name,pass,data={},type='ACTUAL_RUNTIME'){records.push({name,pass:!!pass,evidenceType:type,data});if(!pass)errors.push(name);}
if(formal){
 const freeze=JSON.parse(fs.readFileSync(out+'/approval_core/source-freeze.json','utf8'));
 const frozen=[...freeze.inputs,...freeze.dependencies,...Object.values(freeze.bound)];
 for(const f of frozen){const exists=fs.existsSync(f.path),actual=exists?id(f.path):null;check(`freeze/${path.relative(root,f.path).replaceAll('\\','/')}`,exists&&actual.bytes===f.bytes&&actual.sha256===f.sha256,{expected:f,actual},'SOURCE_IDENTITY')}
 check('freeze/id',freeze.freeze_id==='COAT-G4-COMPLETE-V01-F01'&&freeze.workset_id==='COAT-G4-COMPLETE-V01',{freeze_id:freeze.freeze_id,workset_id:freeze.workset_id},'SOURCE_IDENTITY');
}
const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number);
const lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>{const x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function metrics(loc){return loc.evaluate(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();function surface(n){while(n){const v=getComputedStyle(n).backgroundColor;if(v!=='rgba(0, 0, 0, 0)'&&v!=='transparent')return v;n=n.parentElement}return'rgb(255, 255, 255)'}return{text:(e.innerText||e.textContent||'').trim(),href:e.getAttribute('href'),fg:s.color,bg:surface(e),outline:s.outlineColor,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:surface(parseFloat(s.outlineOffset)>=0?e.parentElement:e),width:r.width,height:r.height,x:r.x,y:r.y,focus:e.matches(':focus-visible'),hover:e.matches(':hover'),display:s.display,font:s.fontFamily,fontSize:s.fontSize,lineHeight:s.lineHeight,background:s.backgroundColor,textDecoration:s.textDecorationLine}})}
async function keyboardFocus(page,loc){await page.mouse.move(0,0);await loc.focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');return loc.evaluate(e=>e===document.activeElement&&e.matches(':focus-visible'))}
async function controls(page,selector,label,w){const list=page.locator(selector);for(let i=0;i<await list.count();i++){const loc=list.nth(i);if(!await loc.isVisible())continue;await loc.scrollIntoViewIfNeeded();await page.mouse.move(0,0);await page.evaluate(()=>document.activeElement?.blur());const normal=await metrics(loc),tr=normal.text?contrast(normal.fg,normal.bg):99;check(`${w}/${label}/${i}/normal`,normal.width>=43.9&&normal.height>=43.9&&tr>=4.5,{...normal,textContrast:tr});await loc.hover();const hover=await metrics(loc),hr=hover.text?contrast(hover.fg,hover.bg):99;check(`${w}/${label}/${i}/hover`,hover.hover&&Math.abs(hover.width-normal.width)<.1&&Math.abs(hover.height-normal.height)<.1&&hr>=4.5,{...hover,textContrast:hr});const reached=await keyboardFocus(page,loc),focus=await metrics(loc),fr=contrast(focus.outline,focus.outlineBg);check(`${w}/${label}/${i}/keyboard-focus`,reached&&focus.outlineWidth>=3&&fr>=3,{...focus,outlineContrast:fr})}}
async function stateShot(page,w,name,{focus,hover,state}){if(focus){await page.locator(focus).scrollIntoViewIfNeeded();await keyboardFocus(page,page.locator(focus));}if(hover){await page.locator(hover).scrollIntoViewIfNeeded();await page.locator(hover).hover();}const p=evidence+`/${w}-${name}.png`;const b=await page.screenshot({path:p});const m=focus?await metrics(page.locator(focus)):hover?await metrics(page.locator(hover)):null;check(`${w}/${name}/captured-state`,focus?m.focus:m.hover,m);assets.push({...id(p),pixelWidth:b.readUInt32BE(16),pixelHeight:b.readUInt32BE(20),viewport:{width:w,height:w===390?844:1000},state})}
async function regionShot(page,w,name,selector){await page.evaluate(sel=>{const e=document.querySelector(sel);scrollTo(0,Math.max(0,e.getBoundingClientRect().top+scrollY-18))},selector);await page.evaluate(()=>document.activeElement?.blur());await page.mouse.move(0,0);const p=evidence+`/${w}-${name}.png`;const b=await page.screenshot({path:p});assets.push({...id(p),pixelWidth:b.readUInt32BE(16),pixelHeight:b.readUInt32BE(20),viewport:{width:w,height:w===390?844:1000},state:'normal readable viewport from start of '+selector})}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const chrome=browser.version();
try{
 const original=fs.readFileSync(g3,'utf8'),candidate=fs.readFileSync(target,'utf8');
 check('source/G3-main-exact',candidate.match(/<main>[\s\S]*?<\/main>/)[0]===original.match(/<main>[\s\S]*?<\/main>/)[0],{g3:sha(g3),candidate:sha(target)},'SOURCE_INSPECTION');
 const localizedCandidate=candidate.replaceAll('dependencies/Inter-Variable.ttf','file:///D:/23MySec/docs/architecture/gate3-shared-consumer-v0.2/Inter-Variable.ttf');
 check('source/G3-inline-style-and-behavior-exact',JSON.stringify(localizedCandidate.match(/<style>[\s\S]*?<\/style>/g))===JSON.stringify(original.match(/<style>[\s\S]*?<\/style>/g))&&JSON.stringify(candidate.match(/<script>[\s\S]*?<\/script>/g))===JSON.stringify(original.match(/<script>[\s\S]*?<\/script>/g)),{},'SOURCE_INSPECTION');
 const shared=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'APP-000',primaryLogoSrc:'dependencies/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'dependencies/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'dependencies/Inter-Variable.ttf'});
 check('source/shared-consumer-v0.2-exact',['header','footer','dialog','style','behavior'].every(k=>candidate.includes(shared[k])),{package:'TIO2MY-GATE3-SHARED-CONSUMER-002'},'SOURCE_INSPECTION');
 check('source/page-style-main-scoped',!fs.readFileSync(out+'/visual-direction.css','utf8').match(/(^|\n)\s*(\.header|\.footer|\.mobileNav|\.cookie-layer)/),{},'SOURCE_INSPECTION');
 check('source/no-terms-no-cross-scope',!candidate.includes('/terms-of-use/')&&!/tiovar|mytio2/i.test(candidate),{},'SOURCE_INSPECTION');
 const buyer=fs.readFileSync(copy,'utf8').match(/<!-- BUYER_COPY_START -->([\s\S]*?)<!-- BUYER_COPY_END -->/)[1].trim();
 const expectedHtml=marked.parse(buyer);
 for(const w of [1440,768,390]){
  const h=w===390?844:1000,context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:1,reducedMotion:'reduce'}),page=await context.newPage();
  const pageErrors=[],external=[];page.on('pageerror',e=>pageErrors.push(e.message));await context.route(/^https?:/,r=>{external.push(r.request().url());return r.abort()});
  await page.goto(pathToFileURL(target).href,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);
  await page.evaluate(()=>{window.__navigationIntents=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href');if(!href?.startsWith('#')){e.preventDefault();window.__navigationIntents.push({text:a.textContent.trim(),href})}},true)});
  const expected=await page.evaluate(html=>{const d=document.createElement('div');d.innerHTML=html;return{text:d.innerText,links:[...d.querySelectorAll('a')].map(a=>({text:a.textContent.trim(),href:a.getAttribute('href')}))}},expectedHtml);
  const renderedText=await page.locator('main').innerText(),renderedLinks=await page.locator('main a').evaluateAll(as=>as.map(a=>({text:a.textContent.trim(),href:a.getAttribute('href')})));
  check(`${w}/approved-B-visible-text`,norm(renderedText)===norm(expected.text),{expectedSha:crypto.createHash('sha256').update(norm(expected.text)).digest('hex'),renderedSha:crypto.createHash('sha256').update(norm(renderedText)).digest('hex')});
  const expectedLinks=[{text:'Home',href:'/'},{text:'Applications',href:'/applications/'},...expected.links.filter(x=>x.href)];
  check(`${w}/approved-B-link-labels-targets`,JSON.stringify(renderedLinks)===JSON.stringify(expectedLinks),{expected:expectedLinks,rendered:renderedLinks});
  const geom=await page.evaluate(()=>{const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};const rect=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom}};const sections=[...document.querySelectorAll('main section')];const bad=[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return vis(e)&&(r.left<-.5||r.right>innerWidth+.5)}).map(e=>e.outerHTML.slice(0,100));const clip=[...document.querySelectorAll('main *')].filter(e=>{const s=getComputedStyle(e);return s.textOverflow==='ellipsis'||(s.webkitLineClamp!=='none'&&s.webkitLineClamp!=='0')}).map(e=>e.outerHTML.slice(0,100));return{pageWidth:document.documentElement.scrollWidth,viewport:innerWidth,pageHeight:document.documentElement.scrollHeight,h1:[...document.querySelectorAll('main h1')].map(e=>e.textContent.trim()),h2:[...document.querySelectorAll('main h2')].map(e=>e.textContent.trim()),modules:sections.map(e=>({id:e.id,className:e.className,heading:e.querySelector('h1,h2')?.textContent.trim(),rect:rect(e)})),endpoints:[...document.querySelectorAll('.endpoint-table tbody tr')].map(e=>({text:e.innerText,rect:rect(e)})),grades:[...document.querySelectorAll('.grades tbody tr')].map(e=>({name:e.cells[0].textContent.trim(),process:e.cells[1].textContent.trim(),href:e.querySelector('a').getAttribute('href'),rect:rect(e)})),requests:[...document.querySelectorAll('.requestCard')].map(e=>({heading:e.querySelector('h3').textContent.trim(),href:e.querySelector('a').getAttribute('href'),rect:rect(e)})),sources:document.querySelectorAll('.sources ol>li').length,sourceLinks:document.querySelectorAll('.sources a[href^="http"]').length,bad,clip,visibleCurrentText:[...document.querySelectorAll('body *')].filter(e=>vis(e)&&e.children.length===0&&e.textContent.trim()==='CURRENT').length,current:{desktop:[...document.querySelectorAll('.desktopNav [aria-current="page"]')].map(e=>e.textContent.trim()),mobile:[...document.querySelectorAll('.mobileNav [aria-current="page"]')].map(e=>e.textContent.trim())},footerOrder:[...document.querySelector('footer').children].map(e=>e.className),logos:[...document.images].map(e=>({src:e.getAttribute('src'),loaded:e.complete&&e.naturalWidth>0}))}});
  check(`${w}/identity-and-ten-part-order`,geom.h1.length===1&&geom.modules.length===10&&geom.h2.length===9&&JSON.stringify(geom.h2)===JSON.stringify(['Define the coating before comparing the Grade','Read optical results in the prepared film','Keep dispersion, rheology and appearance separate','Use surface-treatment information to frame durability questions','Compare every endpoint on a declared basis','Compare cost only at an equal technical endpoint','Grades to Review','Prepare the next request','Technical sources']),geom);
  check(`${w}/five-endpoints-eight-equal-grades`,geom.endpoints.length===5&&JSON.stringify(geom.grades.map(g=>g.name))===JSON.stringify(['M-350','M-510','M-896','M-996','M-2196','M-895','M-52','M-2377'])&&geom.grades.filter(g=>g.process==='Chloride process').length===4&&geom.grades.filter(g=>g.process==='Sulfate process').length===4,{endpoints:geom.endpoints,grades:geom.grades});
  const gradeLayout=w===1440?geom.grades.every((g,i,a)=>i===0||Math.abs(g.rect.width-a[0].rect.width)<.1):w===768?geom.grades.every((g,i,a)=>i<2||Math.abs(g.rect.x-a[i%2].rect.x)<.1):geom.grades.every((g,i,a)=>i===0||Math.abs(g.rect.x-a[0].rect.x)<.1&&g.rect.y>a[i-1].rect.y);
  const endpointLayout=w===1440?geom.endpoints.every((g,i,a)=>i===0||Math.abs(g.rect.width-a[0].rect.width)<.1):w===768?geom.endpoints.every((g,i,a)=>i<2||Math.abs(g.rect.x-a[i%2].rect.x)<.1):geom.endpoints.every((g,i,a)=>i===0||Math.abs(g.rect.x-a[0].rect.x)<.1&&g.rect.y>a[i-1].rect.y);
  const requestLayout=w===1440?geom.requests.every(r=>Math.abs(r.rect.y-geom.requests[0].rect.y)<.1&&Math.abs(r.rect.width-geom.requests[0].rect.width)<.1):geom.requests.every((r,i,a)=>i===0||r.rect.y>a[i-1].rect.y);
  check(`${w}/responsive-relationships`,gradeLayout&&endpointLayout&&requestLayout&&geom.requests.length===3,{gradeLayout,endpointLayout,requestLayout,requests:geom.requests});
  check(`${w}/overflow-clipping-continuity`,geom.pageWidth===w&&!geom.bad.length&&!geom.clip.length&&geom.modules.every((m,i,a)=>i===0||Math.abs(m.rect.y-a[i-1].rect.bottom)<1),geom);
  check(`${w}/shared-current-logo-legal`,geom.visibleCurrentText===0&&geom.current.desktop.join()==='Applications'&&geom.current.mobile.join()==='Applications'&&geom.logos.every(x=>x.loaded)&&JSON.stringify(geom.footerOrder)===JSON.stringify(['footerGrid','legalUtilities','copyright']),geom);
  const cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'main h1'}),fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(`${w}/custom-Inter-loaded`,fonts.fonts.some(f=>f.familyName==='Inter'&&f.isCustomFont),fonts);
  await controls(page,'header .headerInner a,header .headerInner button,main a,footer a,footer button','page-controls',w);
  for(let i=0;i<await page.locator('main a').count();i++){const loc=page.locator('main a').nth(i),href=await loc.getAttribute('href');if(href.startsWith('#')){await loc.click();check(`${w}/main-link-${i}`,await page.evaluate(h=>location.hash===h,href),{href,hash:await page.evaluate(()=>location.hash)});await page.evaluate(()=>history.replaceState(null,'',location.pathname));}else{await loc.click();const intent=await page.evaluate(()=>window.__navigationIntents.at(-1));check(`${w}/main-link-${i}`,intent?.href===href,{href,intent},'LOCAL_SIMULATION')}}
  if(mode.startsWith('4a')){
    if(w===1440){await regionShot(page,w,'hero-direction','.hero');await regionShot(page,w,'endpoint-direction','.endpoint-table');await regionShot(page,w,'grades-direction','.grades');await regionShot(page,w,'request-direction','.request')}
    if(w===390){await regionShot(page,w,'hero-direction','.hero');await regionShot(page,w,'endpoint-direction','.endpoint-table');await regionShot(page,w,'grades-direction','.grades');await regionShot(page,w,'request-direction','.request')}
  }
  if(mode.startsWith('preflight')||formal){
    await page.goto(pathToFileURL(target).href,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>{scrollTo(0,0);document.activeElement?.blur()});await page.mouse.move(0,0);
    const fullPath=evidence+`/${w}-full.png`,pageHeight=await page.evaluate(()=>document.documentElement.scrollHeight),segmentHeight=1200,count=Math.ceil(pageHeight/segmentHeight),parts=[];
    for(let i=0;i<count;i++){const top=i*segmentHeight,height=Math.min(segmentHeight,pageHeight-top),p=segments+`/${w}-readable-${String(i+1).padStart(2,'0')}.png`;await page.setViewportSize({width:w,height});await page.evaluate(y=>scrollTo(0,y),top);const b=await page.screenshot({path:p});parts.push({input:b,top,left:0});assets.push({...id(p),pixelWidth:w,pixelHeight:height,viewport:{width:w,height},state:`continuous readable live-scroll segment ${i+1}/${count}`,segment:{index:i+1,count,top,height}})}
    await sharp({create:{width:w,height:pageHeight,channels:3,background:'#ffffff'}}).composite(parts).png().toFile(fullPath);const full=fs.readFileSync(fullPath);assets.push({...id(fullPath),pixelWidth:w,pixelHeight:pageHeight,viewport:{width:w,height:h},state:'normal complete page assembled losslessly from continuous document clips after clean reload; no target, hover or focus'});
    await page.setViewportSize({width:w,height:h});await page.evaluate(()=>scrollTo(0,0));
    await page.evaluate(()=>{window.__navigationIntents=[];document.addEventListener('click',e=>{const a=e.target.closest('a');if(!a)return;const href=a.getAttribute('href');if(!href?.startsWith('#')){e.preventDefault();window.__navigationIntents.push({text:a.textContent.trim(),href})}},true)});
  }
  if(w<1101){await page.evaluate(()=>scrollTo(0,0));await page.locator('.menuButton').click();check(`${w}/menu-open-first-focus-isolation`,await page.locator('.mobileNav a').first().evaluate(e=>e===document.activeElement)&&await page.evaluate(()=>document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'),{});await controls(page,'.menuButton,.mobileNav a','menu-controls',w);await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');const fwd=await page.locator('.menuButton').evaluate(e=>e===document.activeElement);await page.keyboard.press('Shift+Tab');check(`${w}/menu-two-way-focus-loop`,fwd&&await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});if(formal)await stateShot(page,w,'menu-focus',{focus:'.mobileNav a[aria-current="page"]',state:'Menu open; keyboard focus Applications current item'});await page.keyboard.press('Escape');check(`${w}/menu-Escape-return`,await page.locator('.menuButton').evaluate(e=>e===document.activeElement&&e.textContent==='Menu')&&await page.locator('main').evaluate(e=>!e.inert),{});for(let i=0;i<await page.locator('.mobileNav a').count();i++){await page.locator('.menuButton').click();await page.locator('.mobileNav a').nth(i).click();check(`${w}/menu-selection-${i}`,await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{})}await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:1000});check(`${w}/menu-breakpoint-close`,await page.locator('.mobileNav').evaluate(e=>e.hidden)&&await page.locator('main').evaluate(e=>!e.inert),{});await page.setViewportSize({width:w,height:h})}
  await page.locator('#cookie-trigger').click();check(`${w}/cookie-open-first-focus`,await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(page,'.cookie-actions>*','cookie-controls',w);await page.locator('[data-cookie-close]').focus();await page.keyboard.press('Shift+Tab');const cc=await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await page.keyboard.press('Tab');check(`${w}/cookie-two-way-focus-loop`,cc&&await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await page.locator('main a').first().evaluate(e=>e.focus());check(`${w}/cookie-native-modal-isolation`,await page.locator('dialog').evaluate(e=>e.contains(document.activeElement)),{});if(formal)await stateShot(page,w,'cookie-focus',{focus:'[data-cookie-close]',state:'Cookie Settings open; keyboard focus Close'});await page.keyboard.press('Escape');check(`${w}/cookie-Escape-return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});await page.locator('#cookie-trigger').click();await page.locator('[data-cookie-close]').click();check(`${w}/cookie-Close-return`,await page.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await page.locator('dialog').evaluate(e=>e.open),{});
  if(formal){
   if(w===1440){await stateShot(page,w,'hero-primary-hover',{hover:'.hero .primaryAction',state:'actual Hero primary hover'});await stateShot(page,w,'documents-focus',{focus:'.requestCard a[href="/request-documents/"]',state:'actual keyboard focus on Documents owner path'})}
   if(w===768){await stateShot(page,w,'grade-focus',{focus:'.grades a[href="/products/m-996/"]',state:'actual keyboard focus on neutral Grade path'});await stateShot(page,w,'sample-hover',{hover:'.requestCard a[href="/request-sample/"]',state:'actual Sample owner hover'})}
   if(w===390){await stateShot(page,w,'source-focus',{focus:'.sources li:first-child a[href^="http"]',state:'actual keyboard focus on long external source'});await stateShot(page,w,'rfq-hover',{hover:'.requestCard a[href="/request-a-quote/"]',state:'actual RFQ owner hover'})}
  }
  check(`${w}/no-runtime-errors-or-remote-requests`,pageErrors.length===0&&external.length===0,{pageErrors,external});await context.close();
 }
 // A documented 1440-at-200%-equivalent reflow probe: 720 CSS px, not native zoom.
 const z=await browser.newPage({viewport:{width:720,height:1000},deviceScaleFactor:1});await z.goto(pathToFileURL(target).href);await z.evaluate(()=>document.fonts.ready);const zm=await z.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,viewport:innerWidth,modules:document.querySelectorAll('main section').length,grades:document.querySelectorAll('.grades tbody tr').length,under44:[...document.querySelectorAll('a,button')].filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return s.display!=='none'&&r.width>0&&r.height>0&&(r.width<43.9||r.height<43.9)}).map(e=>e.textContent.trim())}));check('720/200%-equivalent-reflow',zm.scrollWidth===720&&zm.modules===10&&zm.grades===8&&!zm.under44.length,zm,'LOCAL_SIMULATION');await z.close();
}catch(e){errors.push(e.stack)}await browser.close();
const result={date:new Date().toISOString(),mode,worksetId:'COAT-G4-COMPLETE-V01',source:id(target),runtime:{node:process.version,chrome,headless:true,deviceScaleFactor:1,externalRequestsAllowed:false},records,errors,assets,summary:{checks:records.length,passed:records.filter(x=>x.pass).length,failed:records.filter(x=>!x.pass).length},limits:['Local headless Chrome only.','720 CSS px is a reflow proxy for 1440 at 200%; it is not native browser zoom.','Navigation clicks are local intent simulation; no production receiver or external source availability is proved.']};
const resultPath=out+'/diagnostic_support/'+mode+'-runtime-checks.json';fs.writeFileSync(resultPath,JSON.stringify(result,null,2));
if(formal)fs.writeFileSync(out+'/approval_core/export-inventory.json',JSON.stringify({date:new Date().toISOString(),worksetId:'COAT-G4-COMPLETE-V01',freezeId:'COAT-G4-COMPLETE-V01-F01',source:id(target),assets},null,2));
console.log(JSON.stringify({mode,summary:result.summary,errors,assets:assets.length,source:result.source}));if(errors.length)process.exitCode=1;
})();
