const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base=path.resolve(__dirname,'..'),root='D:/23MySec',source=base+'/RES-CHEMOURS_GATE4_COMPLETE_VISUAL_V0.1.html';
const identity=p=>({path:p.replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const mode=process.argv[2],records=[];
const check=(name,pass,detail)=>{records.push({name,pass,detail});};
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function load(w,h=900){await page.setViewportSize({width:w,height:h});await page.goto(pathToFileURL(source).href);await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);}
if(mode==='view'){await load(Number(process.argv[3]),Number(process.argv[4]||900));await page.evaluate(y=>scrollTo(0,y),Number(process.argv[5]||0));if(process.argv[6]==='menu')await page.locator('.menuButton').click();if(process.argv[6]==='cookie')await page.locator('#cookie-trigger').click();if(process.argv[6]==='focus'){await page.locator('main .primary').first().focus();}console.log((await page.screenshot({type:'jpeg',quality:75})).toString('base64'));await browser.close();return;}
if(mode==='direction'){
 for(const [w,sel,name] of [[1440,'.header','hero-exact'],[768,'.sectionNumber-3','brief'],[390,'.sectionNumber-5','actions-independence']]){await load(w,w===390?1320:1000);if(sel!=='.header')await page.locator(sel).scrollIntoViewIfNeeded();await page.screenshot({path:base+'/diagnostic_support/4A-'+w+'-'+name+'.png'});}
 console.log('4A samples saved');await browser.close();return;
}
if(mode==='initial'){
 const g3=fs.readFileSync(root+'/pages/resources/chemours-alternatives/04_planning/gate3-v0.1/RES-CHEMOURS_GATE3_RESPONSIVE_WIREFRAME_V0.2.html','utf8'),html=fs.readFileSync(source,'utf8');
 check('approved body and shared script unchanged',html.split('</head>')[1]===g3.split('</head>')[1],null);
 const sharedCSS=g3.match(/<style>([\s\S]*?)\n\*\{box-sizing/)[1];check('shared CSS unchanged',html.includes(sharedCSS),null);
 for(const w of [1440,768,390]){await load(w);const geometry=await page.evaluate(()=>{
 const visible=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>0&&r.height>0&&s.visibility!=='hidden'&&!e.closest('[hidden],dialog:not([open])');};
 const controls=[...document.querySelectorAll('a,button')].filter(visible).map(e=>{const r=e.getBoundingClientRect();return{label:e.textContent.trim()||e.getAttribute('aria-label'),width:r.width,height:r.height};});
 const overflow=[...document.querySelectorAll('main *')].filter(visible).filter(e=>{const r=e.getBoundingClientRect();return r.left<-.1||r.right>innerWidth+.1||e.scrollWidth>e.clientWidth+1;}).map(e=>e.outerHTML.slice(0,100));
 const textClips=[];const walk=document.createTreeWalker(document.querySelector('main'),NodeFilter.SHOW_TEXT);while(walk.nextNode()){const n=walk.currentNode;if(!n.textContent.trim())continue;const range=document.createRange();range.selectNodeContents(n);for(const r of range.getClientRects()){if(r.left<-.1||r.right>innerWidth+.1)textClips.push(n.textContent.trim());}}
 const hidden=[...document.querySelectorAll('main p,main li,main h1,main h2,main h3')].filter(e=>!visible(e)).map(e=>e.textContent);
 return{width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,header:document.querySelector('.header').getBoundingClientRect().height,briefColumns:getComputedStyle(document.querySelector('.brief-list')).gridTemplateColumns,actionsDisplay:getComputedStyle(document.querySelector('.sectionNumber-5')).display,controls,overflow,textClips,hidden,font:document.fonts.check('18px Inter'),images:[...document.images].map(e=>({loaded:e.complete&&e.naturalWidth>0,src:e.src})),text:document.querySelector('main').innerText,sections:document.querySelectorAll('main section').length};});
 check(w+' complete geometry/assets',geometry.scrollWidth===w&&!geometry.overflow.length&&!geometry.textClips.length&&!geometry.hidden.length&&geometry.font&&geometry.images.every(i=>i.loaded)&&geometry.sections===6,geometry);
 check(w+' all visible controls at least 44x44',geometry.controls.every(c=>c.width>=43.99&&c.height>=43.99),geometry.controls.filter(c=>c.width<43.99||c.height<43.99));
 check(w+' header geometry',geometry.header===(w===1440?84:64),geometry.header);
 const hrefs=await page.locator('main a').evaluateAll(es=>es.map(e=>e.getAttribute('href')));check(w+' page actions/source targets',JSON.stringify(hrefs)===JSON.stringify(['/','/resources/','/products/','https://www.tipure.com/en/products','https://www.tipure.com/en/products/coatings','/products/','/request-documents/']),hrefs);
 for(const link of await page.locator('main a').all())await link.click();check(w+' actual clicks recorded without prefill',await page.evaluate(()=>__navigationIntents.length===7&&__navigationIntents.every(i=>!i.href.includes('?'))),await page.evaluate(()=>__navigationIntents));
 if(w<1100){await page.locator('.menuButton').click();check(w+' menu open and background isolation',await page.evaluate(()=>!document.querySelector('.mobileNav').hidden&&document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.body.style.overflow==='hidden'),null);
 await page.locator('.mobileNav a').last().focus();await page.keyboard.press('Tab');check(w+' menu focus loop forward',await page.locator('.menuButton').evaluate(e=>e===document.activeElement),null);await page.keyboard.press('Shift+Tab');check(w+' menu focus loop reverse',await page.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),null);
 await page.keyboard.press('Escape');check(w+' menu Escape restore',await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert&&document.activeElement===document.querySelector('.menuButton')),null);
 await page.locator('.menuButton').click();await page.locator('.mobileNav a[href="/resources/"]').click();check(w+' menu selection close',await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert),null);
 await page.locator('.menuButton').click();await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(60);check(w+' desktop transition closes menu',await page.evaluate(()=>document.querySelector('.mobileNav').hidden&&!document.querySelector('main').inert),null);await page.setViewportSize({width:w,height:900});}
 await page.locator('#cookie-trigger').click();check(w+' cookie entry/focus and modal background',await page.evaluate(()=>document.querySelector('dialog').open&&document.activeElement===document.querySelector('[data-cookie-close]')&&document.querySelector('dialog').matches(':modal')),null);
 await page.keyboard.press('Shift+Tab');check(w+' cookie reverse loop',await page.locator('.cookie-actions a').evaluate(e=>e===document.activeElement),null);await page.keyboard.press('Tab');check(w+' cookie forward loop',await page.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),null);
 const cookieTargets=await page.locator('.cookie-actions > *').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();const s=getComputedStyle(e);return{width:r.width,height:r.height,color:s.color,border:s.borderColor};}));check(w+' cookie target geometry and functional color',cookieTargets.every(t=>t.width>=44&&t.height>=44&&t.color==='rgb(0, 128, 120)'&&t.border==='rgb(0, 128, 120)'),cookieTargets);
 await page.locator('[data-cookie-close]').click();check(w+' cookie Close restore',await page.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement===document.querySelector('#cookie-trigger')),null);
 await page.locator('#cookie-trigger').click();await page.keyboard.press('Escape');check(w+' cookie Escape restore',await page.evaluate(()=>!document.querySelector('dialog').open&&document.activeElement===document.querySelector('#cookie-trigger')),null);
 }
 await load(390);const cta=page.locator('main .primary').first();await cta.hover();const hover=await cta.evaluate(e=>({bg:getComputedStyle(e).backgroundColor,color:getComputedStyle(e).color}));check('primary hover navy/white',hover.bg==='rgb(6, 43, 91)'&&hover.color==='rgb(255, 255, 255)',hover);await page.mouse.move(0,0);await cta.focus();const focus=await cta.evaluate(e=>({color:getComputedStyle(e).outlineColor,width:getComputedStyle(e).outlineWidth}));check('primary keyboard focus visible functional teal',focus.color==='rgb(0, 128, 120)'&&focus.width==='3px',focus);
 const b=fs.readFileSync(root+'/pages/resources/chemours-alternatives/04_planning/RES-CHEMOURS_GATE2_FULL_BUYER_CLEAN_COPY_V0.3.md','utf8');const lines=b.replace(/<!--[\s\S]*?-->/g,'').split(/\r?\n/).map(l=>l.replace(/^#{1,3} /,'').replace(/^\d\. \*\*/,'**').replace(/\*\*/g,'').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').trim()).filter(Boolean);const text=await page.locator('main').innerText();const norm=s=>s.replace(/\s+/g,' ').trim();check('all approved B lines visible in runtime text',lines.every(l=>norm(text).includes(norm(l))),lines.filter(l=>!norm(text).includes(norm(l))));
 check('no runtime errors',errors.length===0,errors);
 const result={mode:'SELF_CHECK_INITIAL',workset_id:'RESCH-G4-WS-01',actual_author:'/root/gate4_chemours_execute',source:identity(source),renderer:await browser.version(),captured_at:new Date().toISOString(),records,failed:records.filter(r=>!r.pass).length,visual_scan:'PENDING_ACTUAL_READABLE_REVIEW',status:'AWAITING_VISUAL_SCAN'};fs.writeFileSync(base+'/diagnostic_support/initial-observations.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({checks:records.length,failed:records.filter(r=>!r.pass)},null,2));
}
if(mode==='formal'){const lock=JSON.parse(fs.readFileSync(base+'/preflight-lock.json'));if(lock.source.sha256!==identity(source).sha256||lock.status!=='PASS_FOR_FORMAL_RENDER')throw new Error('Preflight lock invalid');const assets=[];for(const w of [1440,768,390]){await load(w);await page.evaluate(()=>{document.activeElement.blur();scrollTo(0,0)});let p=base+'/approval_core/RES-CHEMOURS_GATE4_'+w+'_FULL_V0.1.png';await page.screenshot({path:p,fullPage:true});assets.push({...identity(p),role:'full_page',logical_width:w,dpr:1,physical_width:w,physical_height:await page.evaluate(()=>document.documentElement.scrollHeight),state:'default'});
 if(w<1100){await page.locator('.menuButton').click();await page.keyboard.press('Shift+Tab');await page.keyboard.press('Tab');p=base+'/approval_core/RES-CHEMOURS_GATE4_'+w+'_MENU_V0.1.png';await page.screenshot({path:p});assets.push({...identity(p),role:'menu_state',logical_width:w,dpr:1,physical_width:w,physical_height:900,state:'menu_open_home_keyboard_focus'});await page.keyboard.press('Escape');}
 await page.locator('#cookie-trigger').click();await page.keyboard.press('Tab');await page.keyboard.press('Tab');p=base+'/approval_core/RES-CHEMOURS_GATE4_'+w+'_COOKIE_V0.1.png';await page.screenshot({path:p});assets.push({...identity(p),role:'cookie_state',logical_width:w,dpr:1,physical_width:w,physical_height:900,state:'cookie_open_close_keyboard_focus'});}
 fs.writeFileSync(base+'/formal-capture.json',JSON.stringify({workset_id:'RESCH-G4-WS-01',source:identity(source),renderer:await browser.version(),viewport_heights:900,device_scale_factor:1,assets},null,2)+'\n');console.log(JSON.stringify(assets,null,2));}
await browser.close();})();
