const fs=require('fs'),path=require('path'),crypto=require('crypto');const base=path.resolve(__dirname,'..');
const id=p=>({path:p.replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')});
const write=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n');
const lock=JSON.parse(fs.readFileSync(base+'/preflight-lock.json')),capture=JSON.parse(fs.readFileSync(base+'/formal-capture.json')),inputs=JSON.parse(fs.readFileSync(base+'/input_index.json'));
const review=path.resolve(base,'../../05_review');
const check=p=>{const a=id(p.path);if(a.sha256!==p.sha256||a.bytes!==p.bytes)throw Error('Identity mismatch '+p.path);};
[lock.source,lock.input_index,...lock.dependencies,...inputs.inputs,...capture.assets].forEach(check);
for(const a of capture.assets){const b=fs.readFileSync(a.path);if(b.readUInt32BE(16)!==a.physical_width||b.readUInt32BE(20)!==a.physical_height)throw Error('PNG dimension mismatch');}
const captureCheck={mode:'CAPTURE_CHECK',actual_author:'/root/gate4_chemours_execute',source:lock.source,preflight_lock:id(base+'/preflight-lock.json'),formal_capture:id(base+'/formal-capture.json'),assets_opened:capture.assets.map(a=>a.path),readable_file_views:{1440:[[0,1600],[1450,3050]],768:[[0,1400],[1300,2700],[2600,3701]],390:[[0,1500],[1400,2900],[2800,4300],[4200,4549]]},result:'PASS',observations:'All 8 exact PNGs opened; full-page images read at actual readable scale through transient in-memory crops. Font, logos, widths, source correspondence, complete footer and declared Home/Close keyboard-focus states confirmed. No saved crop files, no source changes, no recapture, no repeated full behavior/geometry/content test.',findings:[]};write(base+'/capture-check.json',captureCheck);
const diagFiles=fs.readdirSync(base+'/diagnostic_support').filter(f=>fs.statSync(base+'/diagnostic_support/'+f).isFile()).map(f=>({...id(base+'/diagnostic_support/'+f),evidence_type:f.endsWith('.png')?'STATIC_VISUAL':'SOURCE_INSPECTION_OR_RUNTIME_RECORD'}));
const index={workset_id:'RESCH-G4-WS-01',freeze_id:'RESCH-G4-FREEZE-01',page_id:'RES-CHEMOURS',actual_author:'/root/gate4_chemours_execute',status:'GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW',input_index:lock.input_index,design_source:lock.source,dependencies:lock.dependencies,approval_core:[...capture.assets.map(a=>({...a,evidence_type:'STATIC_VISUAL'})),...['visual-method-report.md','preflight-lock.json','formal-capture.json','capture-check.json'].map(f=>id(base+'/'+f)),id(review+'/RES-CHEMOURS_GATE4_EXECUTION_SELF_CHECK_V0.1.md'),id(review+'/RES-CHEMOURS_GATE4_TO_GATE5_HANDOFF_V0.1.md')],diagnostic_support:diagFiles,counts:{formal_png:8,full_page_png:3,menu_png:2,cookie_png:3,direction_diagnostic_png:3,persisted_preflight_full_png:0,persisted_segment_png:0},evidence_classes:{STATIC_VISUAL:'PNG and actual readable reviews',ACTUAL_RUNTIME:'initial-observations.json geometry, local Menu/Cookie and focus behavior',SOURCE_INSPECTION:'identity and exact upstream body/shared preservation',LOCAL_SIMULATION:'intercepted local outbound navigation intents; no receiver tested'},findings:[],freeze_record_path:base.replaceAll('\\','/')+'/freeze-record.json',machine_verification_path:base.replaceAll('\\','/')+'/machine-verification.json',limits:['No independent review or Gate closure','No production receiver/consent/storage or browser UI zoom/screen-reader/real-device QA','No mapping/indexing/source freshness/live link claim']};write(base+'/evidence_index.json',index);
const freeze={freeze_id:'RESCH-G4-FREEZE-01',workset_id:'RESCH-G4-WS-01',page_id:'RES-CHEMOURS',actual_author:'/root/gate4_chemours_execute',frozen_at:new Date().toISOString(),status:'GATE4_EXECUTION_COMPLETE_FROZEN / READY_FOR_GATE5_REVIEW',checkpoint_4a:'VISUAL_DIRECTION_CHECKED',checkpoint_4b:'COMPLETE_VISUAL_FROZEN',gate_approval:'NOT_PERFORMED',independent_review:'NOT_PERFORMED; separate Gate5 task',source:lock.source,input_index:lock.input_index,evidence_index:id(base+'/evidence_index.json'),preflight_lock:id(base+'/preflight-lock.json'),capture_check:id(base+'/capture-check.json'),dependencies:lock.dependencies,render_conditions:lock.render_conditions,formal_assets:capture.assets,remaining_execution_findings:0,machine_verification_path:base.replaceAll('\\','/')+'/machine-verification.json',authority_note:'Input identities bind approved content/methods. Root Status and Index excluded. authorization-at-start.md snapshots G4-REMAINING-8-EXEC-01; later batch progress changes do not alter this page authority.'};write(base+'/freeze-record.json',freeze);
const receipts=[freeze.source,freeze.input_index,freeze.evidence_index,freeze.preflight_lock,freeze.capture_check,...freeze.dependencies,...freeze.formal_assets,...index.approval_core,...index.diagnostic_support,...inputs.inputs];receipts.forEach(check);
const report={workset_id:freeze.workset_id,freeze_id:freeze.freeze_id,checked_at:new Date().toISOString(),type:'MACHINE_IDENTITY_VALIDATION',result:'PASS',reference_checks:receipts.length,unique_paths:new Set(receipts.map(x=>x.path)).size,identity_mismatches:0,missing_files:0,png_dimension_checks:8,png_dimension_mismatches:0,formal_asset_count:8,diagnostic_png_count:3,source:id(lock.source.path),input_index:id(base+'/input_index.json'),evidence_index:id(base+'/evidence_index.json'),freeze_record:id(base+'/freeze-record.json'),self_check:id(review+'/RES-CHEMOURS_GATE4_EXECUTION_SELF_CHECK_V0.1.md'),handoff:id(review+'/RES-CHEMOURS_GATE4_TO_GATE5_HANDOFF_V0.1.md'),note:'Machine identity receipt only; does not claim independent visual review or approval.'};write(base+'/machine-verification.json',report);console.log(JSON.stringify(report,null,2));
