const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=__dirname,root=path.resolve(out,'../../../..'),old=path.join(root,'pages/about-contact/04_planning/d32-gate3-v0.2');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const entry=p=>({path:path.resolve(p).replaceAll('\\','/'),relativePath:path.relative(root,path.resolve(p)).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:hash(p)});
const digest=es=>crypto.createHash('sha256').update(es.map(e=>e.relativePath+' '+e.sha256+'\n').sort().join('')).digest('hex');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8')),write=(n,v)=>fs.writeFileSync(path.join(out,n),JSON.stringify(v,null,2)+'\n');
const sources=()=>['ABOUT-001_D32_GATE4.html','about.css','about.js','build.cjs','shared-snapshot.css','shared-snapshot.js','media-projection.css','verify.cjs','capture.cjs','identity.cjs','ABOUT-001_D32_GATE4_WORKSET_V0.1.md'].map(n=>entry(path.join(out,n)));
const mode=process.argv[2];
function validate(es){for(const e of es)if(hash(e.path)!==e.sha256||fs.statSync(e.path).size!==e.bytes)throw Error('Identity changed '+e.path);}
if(mode==='inputs'){
 const b=read(path.join(old,'bundle-manifest.json')),f=read(path.join(old,'freeze.json'));validate(b.approvalCore);validate(f.sources);if(digest(b.approvalCore)!=='9cf732bd510f78e0f74edd7b6725baad9391fdb609e17a1a009e79baa3925883'||digest(f.sources)!=='f3168de74bc8f22d452f16c3601774aa68b3ded29a8b71e26931eb4a5a42e690')throw Error('Inherited aggregate mismatch');
 const inherited=read(path.join(old,'input-identities.json'));
 const omit=['01_PROJECT_INDEX.md','AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md'];
 const inputPaths=inherited.inputs.map(e=>e.relativePath).filter(p=>!omit.includes(p)&&!/(GATE_WORKFLOW|PAGE_GATE_1_4_STANDARD|PROJECT_GOVERNANCE_DETAILS|GATE3_AGENT|GATE3_PRODUCTION|gate3-to-gate4|agents\/gate3|skills\/)/.test(p));
 const current=['AGENTS.md','PROJECT_CONTEXT.md','02_DIRECTORY_GUIDE.md','docs/architecture/GATE_WORKFLOW_V3.4.md','docs/architecture/PAGE_GATE_1_4_STANDARD_V2.4.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.5.md','docs/architecture/GATE3_GATE4_MERGE_DECISION_V1.0.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.11.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CONTRACT_V1.4.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.1.md','agents/gate4-complete-visual/agent.md','skills/responsive-wireframe-design/SKILL.md','skills/brand-applied-visual-design/SKILL.md','skills/full-page-visual-composition/SKILL.md','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/gate4-self-check.md','skills/layout-interaction-verification/references/core-risk-model.md','pages/about-contact/ABOUT-001_D32_CURRENT_GATE_BASELINE_MANIFEST_V0.1.md','pages/about-contact/05_review/ABOUT-001_D32_GATE3_CONTROLLER_CLOSURE_V0.1.md','pages/about-contact/05_review/ABOUT-001_D32_GATE3_TO_GATE4_HANDOFF_V0.1.md','pages/about-contact/05_review/ABOUT-001_D32_GATE3_INDEPENDENT_REVIEW_V0.1.md'];
 current.push('docs/architecture/ROOT_PAGE_NARROW_VISUAL_AND_DOC_FEEDBACK_DECISION_V1.0.md','docs/architecture/STATIC_NEXTJS_SINGLE_SITE_AND_GOOGLE_INDEXING_DECISION_V1.0.md');
 const inputs=[...new Set([...inputPaths,...current])].map(p=>entry(path.join(root,p))),dependencies=inherited.dependencies.map(e=>entry(e.path));
 write('input-index.json',{worksetId:'ABOUT-001-D32-G4-001',inputs,dependencies,inputSetSha256:digest(inputs),navigationOnly:entry(path.join(root,'01_PROJECT_INDEX.md')),inheritedGate3:{bundle:b.bundleSha256,source:f.sourceSetSha256,verifiedCore:b.approvalCore.length,verifiedSources:f.sources.length,sourceReferences:[entry(path.join(old,'bundle-manifest.json')),entry(path.join(old,'freeze.json'))]},rulings:{origin:'https://tio2products.com',consent:'no_optional_analytics',hero:'corporate-light PROTOTYPE_ONLY slots; 390 four-line approved',content:'latest approved source-map strings; public disclosure remains removed'}});console.log(JSON.stringify({inputs:inputs.length,dependencies:dependencies.length,inputSetSha256:digest(inputs),inheritedCore:b.approvalCore.length}));
}else if(mode==='lock'){
 if(fs.existsSync(path.join(out,'source-lock.json')))throw Error('Frozen lock exists; additive revision required');
 if(fs.readFileSync(path.join(out,'ABOUT-001_D32_GATE4_WORKSET_V0.1.md'),'utf8').includes('HERO_LINE_CONTRACT_DECISION_PENDING'))throw Error('Hero line contract still pending');
 const i=read(path.join(out,'input-index.json')),t=read(path.join(out,'diagnostic/final-green.json'));validate([...i.inputs,...i.dependencies]);if(t.checks.some(c=>c.status!=='PASS'))throw Error('Self-check not green');
 const src=sources();write('preflight.json',{status:'PASS_FOR_FORMAL_RENDER',mode:'SELF_CHECK',checks:t.checks.length,test:entry(path.join(out,'diagnostic/final-green.json')),sourceSetSha256:digest(src),formalExportsGenerated:false,actor:'/root/about_root_d32'});
 write('source-lock.json',{worksetId:'ABOUT-001-D32-G4-001',status:'SOURCE_LOCKED_FOR_FORMAL_CAPTURE',sourceSetSha256:digest(src),sources:src,dependencies:[...i.inputs,...i.dependencies,entry(path.join(out,'input-index.json')),entry(path.join(out,'preflight.json'))],render:{viewports:[1440,1024,768,390,320],height:960,dpr:1,readiness:'fonts.ready + two animation frames',font:'Inter bundled neutral consumerV0.2'},time:new Date().toISOString()});console.log(JSON.stringify({sourceSetSha256:digest(src),sources:src.length}));
}else if(mode==='bundle'){
 if(fs.existsSync(path.join(out,'bundle.json')))throw Error('Bundle exists; additive revision required');const lock=read(path.join(out,'source-lock.json'));validate([...lock.sources,...lock.dependencies]);
 const observation=read(path.join(out,'capture-check.json'));if(observation.status!=='PASS')throw Error('Capture check not complete');
 const records=read(path.join(out,'formal/capture-records.json')).records;const images=records.map(r=>{const e=entry(r.file),b=fs.readFileSync(r.file);return{...e,...r,width:b.readUInt32BE(16),height:b.readUInt32BE(20)}});if(images.length!==15)throw Error('15 formal captures required');
 write('evidence-index.json',{worksetId:lock.worksetId,sourceSetSha256:lock.sourceSetSha256,images,actualRuntime:entry(path.join(out,'diagnostic/final-green.json')),captureCheck:entry(path.join(out,'capture-check.json')),diagnosticSupport:{red:['diagnostic/visual-red.json','diagnostic/eyebrow-red.json'],readableSections:'diagnostic/visual/',inherited:'Gate3 exact source and independently accepted coverage per workset'}});
 const core=[...lock.sources,...images,...['source-lock.json','input-index.json','preflight.json','evidence-index.json','capture-check.json','formal/capture-records.json','diagnostic/final-green.json'].map(n=>entry(path.join(out,n)))];
 write('freeze.json',{worksetId:lock.worksetId,status:'COMPLETE_VISUAL_FROZEN / READY_FOR_GATE5_INDEPENDENT_REVIEW',sourceIdentity:lock.sourceSetSha256,htmlSha256:hash(path.join(out,'ABOUT-001_D32_GATE4.html')),core,bundleSha256:digest(core),actor:'/root/about_root_d32',reviewer:'/root/market_root_d32',independentReview:'PENDING',gate4Approval:'NOT_APPROVED',time:new Date().toISOString()});
 write('bundle.json',{worksetId:lock.worksetId,status:'READY_FOR_GATE5_INDEPENDENT_REVIEW',sourceIdentity:lock.sourceSetSha256,bundleSha256:digest(core),freeze:entry(path.join(out,'freeze.json')),algorithm:'SHA256(sorted relativePath + space + sha256 + LF); manifest excluded; freeze references core',evidenceIndex:entry(path.join(out,'evidence-index.json'))});console.log(JSON.stringify({source:lock.sourceSetSha256,bundle:digest(core),freeze:hash(path.join(out,'freeze.json')),formalImages:images.length}));
}else if(mode==='verify'){
 const b=read(path.join(out,'bundle.json')),f=read(path.join(out,'freeze.json')),l=read(path.join(out,'source-lock.json'));validate([...f.core,...l.dependencies,b.freeze,b.evidenceIndex]);if(digest(f.core)!==b.bundleSha256||digest(l.sources)!==b.sourceIdentity)throw Error('Aggregate mismatch');console.log(JSON.stringify({status:'PASS',core:f.core.length,dependencies:l.dependencies.length,bundle:b.bundleSha256,source:b.sourceIdentity,freeze:b.freeze.sha256}));
}else throw Error('Use inputs|lock|bundle|verify');
