const fs=require('fs'),path=require('path'),crypto=require('crypto'),{pathToFileURL}=require('url');
const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/markets/belgium/04_planning/gate4-v1.0',out=__dirname.replaceAll('\\','/');
const target=base+'/MARKET-EU-BE_GATE4_COMPLETE_VISUAL_V1.0.html',prefix=base+'/MARKET-EU-BE_GATE4_';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),id=p=>({path:p,bytes:fs.statSync(p).size,sha256:hash(fs.readFileSync(p))}),read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const records=[],errors=[],check=(name,pass,data,kind='ACTUAL_LOCAL_RUNTIME')=>{records.push({name,pass:!!pass,kind,data});if(!pass)errors.push(name)},norm=s=>s.replace(/\s+/g,' ').replace(/\s+([.,;:])/g,'$1').trim();
const bindings=[];function walk(x,origin){if(!x||typeof x!=='object')return;if(x.path&&x.sha256)bindings.push({origin,...x});Object.values(x).forEach(y=>{if(typeof y==='object')walk(y,origin)});}
const freeze=read(prefix+'FREEZE_RECORD_V1.0.json'),inputs=read(prefix+'INPUT_INDEX_V1.0.json'),evidence=read(prefix+'EVIDENCE_INDEX_V1.0.json'),workset=read(prefix+'WORKSET_V1.0.json');
for(const[n,x]of Object.entries({freeze,inputs,evidence}))walk(x,n);
const unique=[...new Map(bindings.map(x=>[x.path+'|'+x.sha256,x])).values()].map(x=>{let actual=id(x.path);return{...x,actual,match:x.sha256===actual.sha256&&(x.bytes===undefined||x.bytes===actual.bytes)}});
check('all frozen/input/evidence identities',unique.every(x=>x.match),{records:unique.length,mismatches:unique.filter(x=>!x.match)},'INDEPENDENT_SOURCE_HASH');
check('workset and freeze IDs',workset.workset_id==='BE-G4-COMPLETE-20260907-01'&&freeze.freeze_id==='BE-G4-FREEZE-20260907-01',{workset,freeze_id:freeze.freeze_id},'SOURCE_INSPECTION');
const source=fs.readFileSync(target,'utf8');
const shared=require(root+'/docs/architecture/gate3-shared-consumer-v0.2/render-shared-chrome.cjs').renderSharedChrome({currentPageId:'MARKET-000',primaryLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg',reverseLogoSrc:'file:///D:/23MySec/brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',fontSrc:'dependencies/Inter-Variable.ttf'});
check('shared owner exact assembly',['header','footer','dialog','style','behavior'].every(k=>source.includes(shared[k])),Object.fromEntries(['header','footer','dialog','style','behavior'].map(k=>[k,source.includes(shared[k])])),'SOURCE_INSPECTION');
const B=fs.readFileSync(root+'/pages/markets/belgium/04_planning/MARKET-EU-BE_GATE2_FULL_BUYER_CLEAN_COPY_V0.2.md','utf8').replace(/<!--[\s\S]*?-->/g,''),expected=norm(B.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^#+\s*/gm,'').replace(/^-\s*/gm,''));
const expectedLinks=[...B.matchAll(/\[([^\]]+)\]\(([^)]*)\)/g)].map(x=>({text:x[1],href:x[2]}));
const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number),lum=a=>a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0),contrast=(a,b)=>{let x=lum(rgb(a)),y=lum(rgb(b));return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)};
async function measure(loc){return loc.evaluate(e=>{let s=getComputedStyle(e),r=e.getBoundingClientRect();const bg=e=>{while(e){let b=getComputedStyle(e).backgroundColor;if(b!=='rgba(0, 0, 0, 0)'&&b!=='transparent')return b;e=e.parentElement;}return'rgb(255, 255, 255)'};return{text:e.innerText,href:e.getAttribute('href'),width:r.width,height:r.height,fg:s.color,bg:bg(e),outline:s.outlineColor,outlineWidth:parseFloat(s.outlineWidth),outlineOffset:parseFloat(s.outlineOffset),outlineBg:bg(e.parentElement),focus:e.matches(':focus-visible'),hover:e.matches(':hover')}})}
async function controls(p,selector,label,w){const all=p.locator(selector);for(let i=0;i<await all.count();i++){const a=all.nth(i);if(!await a.isVisible())continue;await a.scrollIntoViewIfNeeded();await p.mouse.move(0,0);await p.evaluate(()=>document.activeElement.blur());const n=await measure(a);check(`${w}/${label}/${i}/size-text`,n.width>=44&&n.height>=44&&(!n.text.trim()||contrast(n.fg,n.bg)>=4.5),{...n,ratio:n.text.trim()?contrast(n.fg,n.bg):null});await a.hover();const h=await measure(a);check(`${w}/${label}/${i}/hover`,h.hover&&h.width===n.width&&h.height===n.height&&(!h.text.trim()||contrast(h.fg,h.bg)>=4.5),h);await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');const f=await measure(a);check(`${w}/${label}/${i}/keyboard-focus`,f.focus&&f.outlineWidth>=3&&contrast(f.outline,f.outlineBg)>=3,{...f,outlineContrast:contrast(f.outline,f.outlineBg)});}}
const shots=[],focusCollisions=[];
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const w of[1440,768,390]){const height=w===390?844:900,context=await browser.newContext({viewport:{width:w,height},deviceScaleFactor:1}),p=await context.newPage(),external=[];await context.route(/^https?:/,r=>{external.push(r.request().url());return r.abort()});p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(target).href);await p.evaluate(()=>document.fonts.ready);
const actual=await p.locator('main').evaluate(e=>{let walker=document.createTreeWalker(e,NodeFilter.SHOW_TEXT),a=[];while(walker.nextNode())a.push(walker.currentNode.textContent);return a.join(' ')});check(`${w}/exact B`,norm(actual)===expected,{actual:norm(actual),expected});
const links=await p.locator('main a').evaluateAll(es=>es.map(e=>({text:e.textContent,href:e.getAttribute('href')})));check(`${w}/exact B links`,JSON.stringify(links)===JSON.stringify(expectedLinks),{actual:links,expected:expectedLinks});
const layout=await p.evaluate(()=>{const box=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}};return{lang:document.documentElement.lang,modules:[...document.querySelectorAll('main section')].map(e=>({id:e.dataset.module,rect:box(e)})),headings:[...document.querySelectorAll('main h1,main h2')].map(e=>({tag:e.tagName,text:e.textContent})),contexts:[...document.querySelectorAll('.context')].map(e=>({title:e.querySelector('h3').textContent,rect:box(e),heading:box(e.querySelector('h3')),paragraph:box(e.querySelector('p'))})),coo:(document.querySelector('main').textContent.match(/A Certificate of Origin is available upon request\./g)||[]).length,items:document.querySelectorAll('[data-module="BE-05"] li').length,width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,forbidden:document.querySelectorAll('main form,main input,main img,main select,[hreflang]').length,clip:[...document.querySelectorAll('main *')].filter(e=>['hidden','clip'].includes(getComputedStyle(e).overflowY)||getComputedStyle(e).textOverflow==='ellipsis').map(e=>e.outerHTML.slice(0,120)),logos:[...document.images].map(e=>({src:e.src,loaded:e.complete&&e.naturalWidth>0}))}});
check(`${w}/structure-language-facts`,layout.lang==='en'&&JSON.stringify(layout.modules.map(x=>x.id))===JSON.stringify(['BE-01','BE-02','BE-03','BE-04','BE-05'])&&layout.headings.filter(x=>x.tag==='H1').length===1&&layout.coo===1&&layout.items===4&&!layout.forbidden,layout);
check(`${w}/contexts responsive`,JSON.stringify(layout.contexts.map(x=>x.title))===JSON.stringify(['Coatings','Plastics and Masterbatch','Import and Distribution'])&&layout.contexts.every((x,i)=>w===1440?x.rect.y===layout.contexts[0].rect.y&&(!i||x.rect.x>layout.contexts[i-1].rect.x):w===768?x.heading.y===x.paragraph.y&&x.heading.x<x.paragraph.x&&(!i||x.rect.y>layout.contexts[i-1].rect.y):x.heading.y<x.paragraph.y&&(!i||x.rect.y>layout.contexts[i-1].rect.y)),layout.contexts);
check(`${w}/overflow-clipping-continuity`,layout.width===w&&!layout.clip.length&&layout.modules.every((x,i)=>!i||Math.abs(x.rect.y-layout.modules[i-1].rect.y-layout.modules[i-1].rect.height)<1),layout);
check(`${w}/logos-loaded`,layout.logos.every(x=>x.loaded),layout.logos);
const cdp=await context.newCDPSession(p);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const doc=await cdp.send('DOM.getDocument'),node=await cdp.send('DOM.querySelector',{nodeId:doc.root.nodeId,selector:'main h1'}),fonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check(`${w}/real Inter`,fonts.fonts.some(f=>f.familyName.includes('Inter')&&f.isCustomFont),fonts);
const full=await p.screenshot({fullPage:true}),indexed=evidence.images.find(x=>x.path.includes('_'+w+'_FULL_'));check(`${w}/whole page reproduction`,hash(full)===indexed.sha256,{actual:hash(full),indexed:indexed.sha256,bytes:full.length,height:layout.height});
await controls(p,'header a,header button,main a,footer a,footer button','page',w);
const inline=p.locator('[data-module="BE-04"] p:not(.action) a');for(let i=0;i<await inline.count();i++){let a=inline.nth(i);await p.mouse.move(0,0);await a.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');await a.evaluate(e=>e.scrollIntoView({block:'center'}));const collision=await a.evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),o=parseFloat(s.outlineOffset),t=parseFloat(s.outlineWidth),bands=[{x:r.left-o-t,y:r.top-o-t,w:t,h:r.height+2*(o+t)},{x:r.right+o,y:r.top-o-t,w:t,h:r.height+2*(o+t)},{x:r.left-o,y:r.top-o-t,w:r.width+2*o,h:t},{x:r.left-o,y:r.bottom+o,w:r.width+2*o,h:t}],root=e.closest('p'),walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),hits=[];while(walker.nextNode()){const n=walker.currentNode;if(e.contains(n))continue;for(let i=0;i<n.length;i++){if(!n.textContent[i].trim())continue;const rg=document.createRange();rg.setStart(n,i);rg.setEnd(n,i+1);for(const c of rg.getClientRects())if(bands.some(b=>c.right>b.x&&c.left<b.x+b.w&&c.bottom>b.y&&c.top<b.y+b.h))hits.push({character:n.textContent[i],text:n.textContent,rect:{x:c.x,y:c.y,width:c.width,height:c.height}})}}return{text:e.textContent,outline:{offset:o,width:t},bands,hits,focused:e.matches(':focus-visible'),rect:{x:r.x,y:r.y,width:r.width,height:r.height}}});const file=out+`/inline-focus-${w}-${i}.png`;await p.screenshot({path:file});shots.push(id(file));focusCollisions.push({width:w,...collision,evidence:file});check(`${w}/inline focus clearance/${i}`,collision.focused&&!collision.hits.length,collision);}
for(let i=0;i<await p.locator('a').count();i++){let a=p.locator('a').nth(i);if(!await a.isVisible())continue;await a.click();const href=await a.getAttribute('href'),intent=await p.evaluate(()=>window.__navigationIntents.at(-1)),context=href==='/request-a-quote/'?{source_page_id:'MARKET-EU-BE',destination_country:{value:'Belgium',visible:true,editable:true}}:href==='/request-documents/'?{source_page_id:'MARKET-EU-BE'}:null;check(`${w}/navigation/${i}`,intent.href===href&&intent.kind==='LOCAL_SIMULATION_NOT_RECEIVED'&&JSON.stringify(intent.context)===JSON.stringify(context),intent,'LOCAL_SIMULATION_NOT_RECEIVED');}
if(w<1101){await p.evaluate(()=>scrollTo(0,0));await p.locator('.menuButton').click();check(`${w}/menu initial and isolation`,await p.evaluate(()=>document.activeElement===document.querySelector('.mobileNav a')&&document.querySelector('main').inert&&document.querySelector('footer').inert&&document.querySelector('.logoLink').inert&&document.querySelector('.headerRfq').inert&&document.body.style.overflow==='hidden'),{});await controls(p,'.menuButton,.mobileNav a','menu',w);await p.locator('.mobileNav a').last().focus();await p.keyboard.press('Tab');let a=await p.locator('.menuButton').evaluate(e=>e===document.activeElement);await p.keyboard.press('Shift+Tab');check(`${w}/menu tab cycle`,a&&await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});await p.locator('main a').first().evaluate(e=>e.focus());check(`${w}/menu background focus rejection`,await p.locator('.mobileNav a').last().evaluate(e=>e===document.activeElement),{});await p.keyboard.press('Escape');check(`${w}/menu Escape`,await p.locator('.menuButton').evaluate(e=>e===document.activeElement)&&await p.locator('main').evaluate(e=>!e.inert),{});await p.locator('.menuButton').click();await p.locator('.menuButton').click();check(`${w}/menu Close`,await p.locator('.mobileNav').evaluate(e=>e.hidden),{});await p.locator('.menuButton').click();await p.locator('.mobileNav a[href="/products/"]').click();check(`${w}/menu selection`,await p.locator('.mobileNav').evaluate(e=>e.hidden)&&await p.locator('main').evaluate(e=>!e.inert),{});await p.locator('.menuButton').click();await p.setViewportSize({width:1440,height:900});const r=await p.evaluate(()=>({closed:document.querySelector('.mobileNav').hidden,restored:!document.querySelector('main').inert,active:document.activeElement.tagName}));check(`${w}/desktop breakpoint`,r.closed&&r.restored,r);await p.setViewportSize({width:w,height});}
await p.locator('#cookie-trigger').click();check(`${w}/cookie first focus`,await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await controls(p,'.cookie-actions>*','cookie',w);await p.locator('[data-cookie-close]').focus();await p.keyboard.press('Shift+Tab');let cycle=await p.locator('.cookie-actions a').evaluate(e=>e===document.activeElement);await p.keyboard.press('Tab');check(`${w}/cookie tab cycle`,cycle&&await p.locator('[data-cookie-close]').evaluate(e=>e===document.activeElement),{});await p.locator('main a').first().evaluate(e=>e.focus());check(`${w}/cookie native modal`,await p.locator('dialog').evaluate(e=>e.contains(document.activeElement)),{});await p.keyboard.press('Escape');check(`${w}/cookie Escape return`,await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement)&&!await p.locator('dialog').evaluate(e=>e.open),{});await p.locator('#cookie-trigger').click();await p.locator('[data-cookie-close]').click();check(`${w}/cookie Close return`,await p.locator('#cookie-trigger').evaluate(e=>e===document.activeElement),{});check(`${w}/no remote requests`,!external.length,external);await context.close();}
const nojs=await browser.newContext({javaScriptEnabled:false}),p=await nojs.newPage();await p.goto(pathToFileURL(target).href);const text=await p.locator('main').evaluate(e=>{const w=document.createTreeWalker(e,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode.textContent);return a.join(' ')});check('noJS full B retained',norm(text)===expected,{});await nojs.close();
}catch(e){errors.push(e.stack)}finally{await browser.close();const after=unique.map(x=>({...id(x.path),unchanged:id(x.path).sha256===x.actual.sha256}));const result={reviewer:'Independent subagent /root/gate4_nl_complete; did not author Belgium candidate',date:new Date().toISOString(),workset_id:workset.workset_id,freeze_id:freeze.freeze_id,runtime:{node:process.version,chrome:browser.version(),headless:true,deviceScaleFactor:1},records,errors,focusCollisions,shots,identity:{unique,after,allUnchanged:after.every(x=>x.unchanged)},candidateEvidenceCount:evidence.images.length};fs.writeFileSync(out+'/independent-runtime-and-identity.json',JSON.stringify(result,null,2));console.log(JSON.stringify({records:records.length,errors,identityRecords:unique.length,unchanged:result.identity.allUnchanged,focusCollisions:focusCollisions.map(x=>({width:x.width,text:x.text,hits:x.hits.map(h=>h.character)})),result:id(out+'/independent-runtime-and-identity.json')}));}})();
