const fs=require('fs'),crypto=require('crypto'),{pathToFileURL}=require('url'),{chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root='D:/23MySec',base=root+'/pages/markets/belgium/04_planning/gate4-v1.0',out=__dirname,target=base+'/MARKET-EU-BE_GATE4_COMPLETE_VISUAL_V1.0.html',hash=b=>crypto.createHash('sha256').update(b).digest('hex'),id=p=>({path:p,sha256:hash(fs.readFileSync(p)),bytes:fs.statSync(p).size}),read=p=>JSON.parse(fs.readFileSync(p,'utf8')),records=[],check=(name,pass,data)=>records.push({name,pass:!!pass,data});
const prior=read(root+'/pages/markets/netherlands/04_planning/gate4-complete-v0.1/input-index.json');
const commonReadReuse=prior.inputs.filter(x=>!x.path.includes('/netherlands/')).map(x=>({...x,current:id(x.path),identityUnchanged:id(x.path).sha256===x.sha256}));check('common documents previously fully read by this reviewer unchanged',commonReadReuse.every(x=>x.identityUnchanged),commonReadReuse);
const receipt=read(base+'/diagnostic_support/final-delivery-readback.json');for(const a of receipt.deliverables)check('final delivery '+a.path,a.sha256===id(a.path).sha256&&a.bytes===id(a.path).bytes,{expected:a,actual:id(a.path)});
const evidence=read(base+'/MARKET-EU-BE_GATE4_EVIDENCE_INDEX_V1.0.json');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});for(const w of[1440,768,390]){const c=await b.newContext({viewport:{width:w,height:w===390?844:900},deviceScaleFactor:1}),p=await c.newPage();await c.route(/^https?:/,r=>r.abort());await p.goto(pathToFileURL(target).href);await p.evaluate(()=>document.fonts.ready);const h=await p.evaluate(()=>document.documentElement.scrollHeight),coverage=[];for(let y=0,n=1;y<h;y+=750,n++){const clip={x:0,y,width:w,height:Math.min(900,h-y)},buffer=await p.screenshot({fullPage:true,clip}),a=evidence.images.find(x=>x.path.endsWith(`clip-${w}-${String(n).padStart(2,'0')}.png`));check(`${w}/segment ${n} reproduction`,hash(buffer)===a.sha256,{path:a.path,clip,actualSha256:hash(buffer),expectedSha256:a.sha256});coverage.push({start:y,end:y+clip.height})}check(`${w}/continuous readable coverage`,coverage[0].start===0&&coverage.at(-1).end===h&&coverage.every((r,i)=>!i||r.start<=coverage[i-1].end),coverage);
if(w<1101){await p.evaluate(()=>scrollTo(0,0));await p.locator('.menuButton').click();await p.mouse.move(w-10,800);await p.mouse.wheel(0,250);await p.waitForTimeout(120);check(`${w}/wheel scroll locked`,await p.evaluate(()=>scrollY===0),{});await p.keyboard.press('Escape');await p.mouse.wheel(0,250);await p.waitForTimeout(120);check(`${w}/wheel scroll restored`,await p.evaluate(()=>scrollY>0),{});for(let i=0;i<8;i++){await p.evaluate(()=>scrollTo(0,0));await p.locator('.menuButton').click();let a=p.locator('.mobileNav a').nth(i),href=await a.getAttribute('href');await a.click();let intent=await p.evaluate(()=>window.__navigationIntents.at(-1));check(`${w}/menu selection ${i}`,intent.href===href&&await p.locator('.mobileNav').evaluate(e=>e.hidden)&&await p.locator('main').evaluate(e=>!e.inert),{href,intent})}}
await c.close()}await b.close();const result={date:new Date().toISOString(),records,errors:records.filter(x=>!x.pass),openedImages:evidence.images.map(x=>({...id(x.path),reviewerOpened:true,note:x.path.includes('_FULL_')?'Overview plus separately read complete continuous clips':'Original pixel size visual inspection'})),openedOwnFocusImages:[1440,768,390].flatMap(w=>[0,1].map(i=>({...id(out+`/inline-focus-${w}-${i}.png`),reviewerOpened:true}))),limitations:['All operations local Chrome/headless; navigation is not production receiver proof.','Range character boxes are conservative; required collision is also visually confirmed, not inferred from range alone.']};fs.writeFileSync(out+'/supplement-and-visual-readback.json',JSON.stringify(result,null,2));console.log(JSON.stringify({records:records.length,errors:result.errors,opened:evidence.images.length,commonReadReuse:commonReadReuse.length,result:id(out+'/supplement-and-visual-readback.json')}));})();
