const fs=require('fs'),path=require('path');const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const out=__dirname,formal=process.argv.includes('--formal');
(async()=>{if(formal){const f=JSON.parse(fs.readFileSync(path.join(out,'freeze.json'),'utf8'));for(const e of [...f.sources,...f.dependencies]){const hash=require('crypto').createHash('sha256').update(fs.readFileSync(e.path)).digest('hex');if(hash!==e.sha256)throw Error('Frozen identity changed: '+e.path);}}
const browser=await chromium.launch(),page=await browser.newPage();const url=require('url').pathToFileURL(path.join(out,'ABOUT-001_D32_GATE3.html')).href;
const folder=path.join(out,formal?'formal':'diagnostic/segments');fs.mkdirSync(folder,{recursive:true});
async function ready(){await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
for(const width of [1440,768,390]){await page.setViewportSize({width,height:960});await page.goto(url);await ready();if(!formal)await page.setViewportSize({width,height:await page.evaluate(()=>document.documentElement.scrollHeight)});
if(formal)await page.screenshot({path:path.join(folder,`ABOUT-001_D32_GATE3_FULL_${width}.png`),fullPage:true});
else {const groups=width===1440?[['.about-breadcrumb','#who'],['#why','#what'],['#markets','#applications'],['#how','#documentation'],['#company','.footer']]:[['.about-breadcrumb','.about-hero'],['#who','#who'],['#why','#what'],['#markets','#markets'],['#applications','#how'],['#documentation','.footer']];for(let i=0;i<groups.length;i++){const [a,b]=groups[i];const box=await page.evaluate(([a,b])=>{const x=document.querySelector(a).getBoundingClientRect(),y=document.querySelector(b).getBoundingClientRect();return {x:0,y:Math.max(0,Math.floor(x.top+scrollY)),width:innerWidth,height:Math.floor(y.bottom-x.top)};},[a,b]);await page.screenshot({path:path.join(folder,`${width}-${i+1}.png`),clip:box,fullPage:true});}}
if(formal&&width<1000){await page.locator('.menuButton').click();await ready();await page.screenshot({path:path.join(folder,`ABOUT-001_D32_GATE3_MENU_${width}.png`)});}
}
if(formal){await page.setViewportSize({width:390,height:960});for(const state of ['partial','restricted']){await page.goto(url+'?evidence='+state);await ready();await page.screenshot({path:path.join(folder,`ABOUT-001_D32_GATE3_${state.toUpperCase()}_390.png`),fullPage:true});}await page.goto(url);await page.locator('#cookie-trigger').click();await ready();await page.screenshot({path:path.join(folder,'ABOUT-001_D32_GATE3_COOKIE_390.png')});}
await browser.close();console.log(formal?'Formal captures complete':'Segment captures complete');})();
