const fs=require('fs'),path=require('path'),crypto=require('crypto');
const out=__dirname,root=path.resolve(out,'../../../..');
const rel=p=>path.relative(root,p).replaceAll('\\','/');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const entry=p=>{p=path.resolve(p);return {path:p.replaceAll('\\','/'),relativePath:rel(p),bytes:fs.statSync(p).size,sha256:hash(p)}};
const digest=es=>crypto.createHash('sha256').update(es.map(e=>e.relativePath+' '+e.sha256+'\n').sort().join('')).digest('hex');
const write=(name,data)=>fs.writeFileSync(path.join(out,name),JSON.stringify(data,null,2)+'\n');
const read=name=>JSON.parse(fs.readFileSync(path.join(out,name),'utf8'));
const inputPaths=[
'AGENTS.md','PROJECT_CONTEXT.md','01_PROJECT_INDEX.md','02_DIRECTORY_GUIDE.md',
'docs/superpowers/plans/2026-09-21-four-root-pages-d32-gate3-gate9.md',
'docs/architecture/GATE_WORKFLOW_V3.3.md','docs/architecture/PAGE_GATE_1_4_STANDARD_V2.3.md','docs/architecture/PROJECT_GOVERNANCE_DETAILS_V1.4.md','docs/architecture/GATE3_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.14.md','docs/architecture/GATE3_PRODUCTION_BOUNDARY_STANDARD_V1.1.md','docs/architecture/GATE3_CROSS_PAGE_CONSISTENCY_DECISION_V1.0.md','docs/architecture/GATE_3_4_6_DELEGATED_CLOSURE_AUTHORITY_V1.0.md','docs/architecture/DEVELOPMENT_OWNER_D32_SWITCH_DECISION_V1.0.md',
'docs/superpowers/specs/2026-09-20-gate3-to-gate4-handoff-contract-v0.5.md',
'agents/gate3-execution/agent.md','skills/responsive-wireframe-design/SKILL.md','skills/responsive-wireframe-design/references/preflight-freeze-evidence.md','skills/responsive-wireframe-design/scripts/check-preflight-record.mjs','skills/layout-interaction-verification/SKILL.md','skills/layout-interaction-verification/references/gate3-structure-scope.md','skills/layout-interaction-verification/references/core-risk-model.md',
'docs/architecture/PAGE_REGISTRY_V0.2.md','research/keyword/11_page_keyword_master.csv','docs/page-playbooks/README.md','docs/page-briefs/ABOUT-001_ABOUT_TIO2_MALAYSIA_BRIEF_V0.6.md',
'docs/architecture/EVIDENCE_GAP_USER_DECISION_REGISTER_V1.8.md','docs/architecture/MALAYSIA_ORIGIN_SITE_WIDE_PUBLICATION_AUTHORITY_V1.0.md','docs/architecture/TIO2_MY_23_PAGE_PUBLICATION_CONTRACT_FINALIZATION_V1.0.md',
'pages/about-contact/00_governance/ABOUT-001_GATE0_GATE2_USER_APPROVAL_2026-09-01.md','pages/about-contact/00_governance/ABOUT-001_PCR02_USER_DECISIONS_2026-09-01.md','pages/about-contact/02_content/ABOUT-001_GATE2_CONTENT_ARCHITECTURE_COPY_V0.1.md','pages/about-contact/05_review/ABOUT-001_GATE5_CURRENT_VISUAL_MANIFEST_V0.3.md','pages/about-contact/06_handoff/ABOUT-001_GATE7_MANIFEST_V0.2.md','pages/about-contact/06_handoff/ABOUT-001_GATE7_CONTENT_SEO_GEO_SCHEMA_SOURCE_MAP_V0.1.md','pages/about-contact/06_handoff/ABOUT-001_GATE7_CONTENT_SEO_GEO_SCHEMA_SOURCE_MAP_V0.2.md','pages/about-contact/06_handoff/ABOUT-001_GATE7_MEDIA_ASSET_HANDOFF_V0.1.md','pages/about-contact/05_review/ABOUT-001_GATE7_PROJECT_CONTROL_CLOSURE_V0.1.md','pages/about-contact/05_review/ABOUT-001_GATE9_PROJECT_CONTROL_CLOSURE_V0.1.md',
'pages/about-contact/04_visual/ABOUT-001_ROOT_PAGE_HERO_GATE4_BINDING_V1.0.md','pages/about-contact/04_visual/ABOUT-001_ROOT_PAGE_HERO_GATE4_BINDING_V1.1.md',
'docs/architecture/ROOT_PAGE_HERO_SHARED_COMPONENT_SPEC_V1.0.md','docs/architecture/ROOT_PAGE_HERO_OPEN_WHITE_SURFACE_ADDENDUM_V1.0.md','docs/architecture/ROOT_PAGE_HERO_SEVEN_PAGE_APPROVED_BASELINE_MANIFEST_V1.0.md','docs/architecture/ROOT_PAGE_HERO_SEVEN_PAGE_CURRENT_GATE6_MANIFEST_V1.0.md','docs/architecture/ROOT_PAGE_HERO_SEVEN_PAGE_CURRENT_GATE9_MANIFEST_V1.2.md',
'docs/architecture/GLOBAL_HEADER_FOOTER_SPEC_V0.5.md','docs/architecture/GLOBAL_FOOTER_LEGAL_UTILITY_ADDENDUM_V1.0.md','brand/visual/TiO2_Malaysia_Visual_Standard_V1.0.md','brand/visual/TIO2_MALAYSIA_PRIMARY_CTA_ACCESSIBILITY_ADDENDUM_V1.0.md','brand/logo/production/PRODUCTION_SVG_LOGO_MANIFEST_V1.0.md',
'pages/home/HOME-001_CURRENT_GATE_BASELINE_MANIFEST_V1.12.md','pages/home/06_handoff/HOME-001_D32_GATE8_COMPLETION_INTAKE_V1.0.md','pages/home/07_qa/HOME-001_GATE9_CURRENT_IMPLEMENTATION_MANIFEST_V0.2.md'
];
const shared='docs/architecture/gate3-shared-consumer-v0.2/';
const deps=[...fs.readdirSync(path.join(root,shared)).filter(x=>fs.statSync(path.join(root,shared,x)).isFile()).map(x=>shared+x),
'brand/logo/candidates/v0.1/tio2-malaysia-primary-horizontal-v0.1.svg','brand/logo/candidates/v0.1/tio2-malaysia-reverse-monochrome-v0.1.svg',
'pages/about-contact/04_visual/visual-designs/about-root-page-hero-v1.0/about-root-page-hero-preview-v1.0.html',
'pages/about-contact/04_visual/pcr02_assets/ABOUT-001_G6_PCR02_DESKTOP_1440_MINIMAL_EDIT_V0.3.png'].map(x=>entry(path.join(root,x)));
const sourceNames=['ABOUT-001_D32_GATE3.html','about.css','about.js','build.cjs','verify.cjs','capture.cjs','identity.cjs','shared-snapshot.css','shared-snapshot.js','media-projection.css','ABOUT-001_D32_GATE3_DESIGN_AND_SELF_CHECK_V0.1.md'];
const mode=process.argv[2];
if(mode==='preflight'){
 if(fs.existsSync(path.join(out,'freeze.json')))throw Error('Existing freeze: do not rewrite');
 const inputs=inputPaths.map(x=>entry(path.join(root,x)));write('input-identities.json',{id:'ABOUT-001-D32-G3-INPUT-001',createdAt:new Date().toISOString(),actor:'/root/about_root_d32',inputs,dependencies:deps,inputSetSha256:digest(inputs),rulings:{source:'controller messages + progress.md; content summarized in design report; live ledger not runtime dependency',chrome:'V0.5',sharedConsumer:'V0.2',hero:'corporate-light PROTOTYPE_ONLY slots',origin:'https://tio2products.com',consent:'no_optional_analytics',aboutPublicSourceBlock:'removed by latest approved chain; retain internal provenance only'}});
 const tests=read('diagnostic/final-green.json');if(tests.checks.some(x=>x.status!=='PASS')||tests.checks.length!==303)throw Error('Checks not green');
 const sources=sourceNames.map(x=>entry(path.join(out,x)));const checks=Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks'].map(k=>[k,'PASS']));
 write('preflight.json',{id:'ABOUT-001-D32-G3-PREFLIGHT-001',status:'PASS_FOR_FORMAL_RENDER',actor:'/root/about_root_d32',createdAt:new Date().toISOString(),candidate:entry(path.join(out,sourceNames[0])),dependencies:[...inputs,...deps,...sources.slice(1),entry(path.join(out,'input-identities.json'))],checks,sharedConsumer:{path:path.join(root,shared,'SHARED_GLOBAL_CHROME_GATE3_CONSUMER_MANIFEST_V0.2.md').replaceAll('\\','/'),sha256:hash(path.join(root,shared,'SHARED_GLOBAL_CHROME_GATE3_CONSUMER_MANIFEST_V0.2.md')),inheritance:'SOURCE_INSPECTION only; full local menu and Cookie behavior reverified at applicable widths; no foreign runtime pass substituted'},formalExportsGenerated:false,viewports:[{width:1440,height:960},{width:768,height:960},{width:390,height:960}],browser:'Playwright Chromium headless; Windows; bundled dependency',evidenceTypes:['ACTUAL_RUNTIME','SOURCE_INSPECTION','LOCAL_SIMULATION','INHERITED_REFERENCE'],evidence:{authorTests:entry(path.join(out,'diagnostic/final-green.json')),designReport:entry(path.join(out,sourceNames.at(-1))),diagnosticDirectory:rel(path.join(out,'diagnostic')),visualInspection:'All 17 readable diagnostic segments plus actual desktop footer viewport inspected; complete three-width content and states'},openBlockingFindings:[]});
 console.log('Preflight and input identities generated; run independent preflight checker before freeze.');
}else if(mode==='freeze'){
 if(fs.existsSync(path.join(out,'freeze.json')))throw Error('Existing freeze: do not rewrite');
 const p=read('preflight.json');for(const e of [p.candidate,...p.dependencies])if(hash(e.path)!==e.sha256)throw Error('Preflight mismatch '+e.path);
 const sources=sourceNames.map(x=>entry(path.join(out,x))),inputs=read('input-identities.json');
 write('freeze.json',{id:'ABOUT-001-D32-G3-FREEZE-001',status:'FROZEN_FOR_INDEPENDENT_GATE3_REVIEW_NOT_APPROVED',createdAt:new Date().toISOString(),actor:'/root/about_root_d32',sourceSetSha256:digest(sources),htmlSha256:sources[0].sha256,sources,dependencies:[...inputs.inputs,...inputs.dependencies],inputCard:entry(path.join(out,'input-identities.json')),preflight:entry(path.join(out,'preflight.json')),sharedConsumerVersion:'V0.2',formalExportsGeneratedAtFreeze:false,hashAlgorithm:'SHA-256; aggregate = sorted relativePath + space + sha256 + LF, UTF-8'});console.log(JSON.stringify({sourceSetSha256:digest(sources),htmlSha256:sources[0].sha256}));
}else if(mode==='bundle'){
 const freeze=read('freeze.json');for(const e of [...freeze.sources,...freeze.dependencies,freeze.inputCard,freeze.preflight])if(hash(e.path)!==e.sha256)throw Error('Freeze changed '+e.path);
 const images=fs.readdirSync(path.join(out,'formal')).filter(n=>n.endsWith('.png')).sort().map(n=>{const e=entry(path.join(out,'formal',n)),b=fs.readFileSync(e.path);return {...e,width:b.readUInt32BE(16),height:b.readUInt32BE(20),evidenceType:n.includes('PARTIAL')||n.includes('RESTRICTED')?'LOCAL_SIMULATION':'ACTUAL_RUNTIME'}});
 if(images.length!==8)throw Error('Expected eight formal PNGs');write('asset-manifest.json',{id:'ABOUT-001-D32-G3-ASSETS-001',freeze:entry(path.join(out,'freeze.json')),logicalViewportHeight:960,images,diagnosticSupport:'diagnostic/; not approval assets'});
 const core=[...freeze.sources,...images,...['input-identities.json','preflight.json','freeze.json','asset-manifest.json','diagnostic/final-green.json','formal-verification.json'].map(n=>entry(path.join(out,n)))];
 write('bundle-manifest.json',{id:'ABOUT-001-D32-G3-BUNDLE-001',status:'READY_FOR_INDEPENDENT_GATE3_REVIEW',createdAt:new Date().toISOString(),actor:'/root/about_root_d32',reviewer:'/root/market_root_d32',sourceSetSha256:freeze.sourceSetSha256,htmlSha256:freeze.htmlSha256,bundleSha256:digest(core),hashAlgorithm:'SHA-256; aggregate = sorted relativePath + space + sha256 + LF, UTF-8; this manifest excluded from its own hash',approvalCore:core,diagnosticSupport:{directory:'diagnostic/',red:['red.json','relationship-red.json'],notApprovalEvidence:['initial.json','second.json','green.json','segments/']},independentReview:'PENDING',gate3Closure:'NOT_CLOSED'});console.log(JSON.stringify({sourceSetSha256:freeze.sourceSetSha256,htmlSha256:freeze.htmlSha256,bundleSha256:digest(core),formalImages:images.length,sourceCount:freeze.sources.length,dependencyCount:freeze.dependencies.length}));
}else throw Error('Use preflight, freeze or bundle');
