const fs=require('fs'),path=require('path'),crypto=require('crypto');const {pathToFileURL}=require('url');const {chromium}=require('C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const dir=__dirname,formal=process.argv.includes('--formal'),samples=process.argv.includes('--samples'),out=path.join(dir,formal?'approval_core':samples?'diagnostic_support/4A':'diagnostic_support/readable');fs.mkdirSync(out,{recursive:true});const hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
(async()=>{if(formal){const lock=JSON.parse(fs.readFileSync(path.join(dir,'source-lock.json')));for(const r of lock.files)if(hash(r.path)!==r.sha256)throw Error('changed source '+r.path)}const browser=await chromium.launch({headless:true}),page=await browser.newPage({deviceScaleFactor:1}),assets=[];
async function shot(name,{fullPage=false,locator}={}){const file=path.join(out,name+'.png');await page.mouse.move(0,0);if(locator)await page.locator(locator).screenshot({path:file});else await page.screenshot({path:file,fullPage});const bytes=fs.readFileSync(file);assets.push({path:file,bytes:bytes.length,sha256:hash(file),logical_width:page.viewportSize().width,physical_width:bytes.readUInt32BE(16),physical_height:bytes.readUInt32BE(20),dpr:1,state:name});}
async function goto(width,state='full'){await page.setViewportSize({width,height:formal||samples?1000:1600});await page.goto(pathToFileURL(path.join(dir,'market-visual.html')).href+'?state='+state);await page.evaluate(()=>document.fonts.ready);await page.mouse.move(0,0);}
if(samples){for(const w of [1440,768,320]){await goto(w);await shot('4A_HERO_'+w,{locator:'.rootHero'});if(w===1440||w===320){if(w===320)await page.locator('#eu-toggle').click();await page.locator('.primary').evaluate(e=>e.blur());await shot('4A_DESTINATIONS_'+w,{locator:'#destination-selector'});}}}
else for(const w of [1440,1024,768,390,320]){await goto(w);if(formal){await shot('MARKET-000_D32_G4_FULL_'+w,{fullPage:true});if(w===768||w===390){await page.locator('.menuButton').click();await shot('MARKET-000_D32_G4_MENU_'+w);await page.keyboard.press('Escape');}if(w===390||w===320){await page.locator('#cookie-trigger').click();await shot('MARKET-000_D32_G4_COOKIE_'+w);await page.keyboard.press('Escape');}if(w===390){await page.locator('#eu-toggle').click();await page.locator('.euPanel').scrollIntoViewIfNeeded();await page.locator('#eu-toggle').evaluate(e=>e.blur());await shot('MARKET-000_D32_G4_EU_EXPANDED_390');await page.locator('.primary').focus();await page.keyboard.press('Tab');await page.keyboard.press('Shift+Tab');await shot('MARKET-000_D32_G4_PRIMARY_FOCUS_390');await page.locator('#eu-toggle').focus();await page.keyboard.press('Tab');await shot('MARKET-000_D32_G4_COUNTRY_FOCUS_390');}if(w===1440){await page.locator('.primary').hover();const file=path.join(out,'MARKET-000_D32_G4_PRIMARY_HOVER_1440.png');await page.screenshot({path:file});const b=fs.readFileSync(file);assets.push({path:file,bytes:b.length,sha256:hash(file),logical_width:w,physical_width:w,physical_height:1000,dpr:1,state:'primary hover'});}}
else {if(w<768)await page.locator('#eu-toggle').click();await page.evaluate(()=>document.activeElement.blur());const height=await page.locator('body').evaluate(e=>e.scrollHeight);for(let y=0;y<height;y+=1500){await page.evaluate(y=>scrollTo(0,y),y);await shot(w+'-'+y);}}}
if(formal){for(const state of ['none','eu-only','support-only']){await goto(390,state);await page.locator('#eu-toggle').click();await page.evaluate(()=>document.activeElement.blur());await shot('MARKET-000_D32_G4_ROUTE_'+state.toUpperCase()+'_390',{fullPage:true});}}
fs.writeFileSync(path.join(out,'asset-index.json'),JSON.stringify({timestamp:new Date().toISOString(),renderer:await browser.version(),evidence_types:['STATIC_VISUAL','LOCAL_SIMULATION'],source_sha256:hash(path.join(dir,'market-visual.html')),assets},null,2));console.log(JSON.stringify({formal,samples,assets:assets.length,out}));await browser.close()})();
