const fs=require('fs'),path=require('path'),crypto=require('crypto');const dir=__dirname,root=path.resolve(dir,'../../../..'),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),id=f=>{const p=path.resolve(dir,f);return {path:p,bytes:fs.statSync(p).size,sha256:hash(p)}};const write=(n,v)=>fs.writeFileSync(path.join(dir,n),JSON.stringify(v,null,2));const stage=process.argv[2];
if(stage==='prepare'){
if(fs.existsSync(path.join(dir,'source-lock.json')))throw Error('source already locked');const runtime=JSON.parse(fs.readFileSync(path.join(dir,'diagnostic_support/runtime.json')));if(runtime.failed!==0||runtime.passed!==141)throw Error('Runtime not green');
const g3=JSON.parse(fs.readFileSync(path.resolve(dir,'../d32-gate3-v0.1/input-identities.json')));const needed=['../../MARKET-000_D32_CURRENT_GATE_BASELINE_MANIFEST_V0.2.md','../../05_review/MARKET-000_D32_GATE3_TO_GATE4_HANDOFF_V0.1.md','../../05_review/MARKET-000_D32_GATE3_CONTROLLER_CLOSURE_V0.1.md','../../05_review/MARKET-000_D32_GATE3_INDEPENDENT_REVIEW_V0.1.md','../d32-gate3-v0.1/freeze.json','../d32-gate3-v0.1/market-planning.html','../d32-gate3-v0.1/planning.css','../d32-gate3-v0.1/planning.js','../d32-gate3-v0.1/content-map.json'].map(id);
for(const f of ['docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CURRENT_BASELINE_MANIFEST_V1.10.md','agents/gate4-complete-visual/agent.md','docs/architecture/GATE4_COMPLETE_VISUAL_AGENT_SKILL_CONTRACT_V1.3.md','skills/brand-applied-visual-design/SKILL.md','skills/full-page-visual-composition/SKILL.md','skills/layout-interaction-verification/references/gate4-self-check.md','docs/architecture/GATE4_GATE5_VISUAL_HANDOFF_CONTRACT_V1.0.md','pages/products/PRODUCT-000_D32_CURRENT_GATE_BASELINE_MANIFEST_V0.1.md','pages/applications/APP-000_D32_CURRENT_GATE_BASELINE_MANIFEST_V0.3.md','pages/home/07_qa/HOME-001_D32_GATE9_VISUAL_INTERACTION_REVIEW_V0.1.md'])needed.push(id(path.join(root,f)));
const inputs=[...new Map([...g3.inputs.map(r=>id(r.path)),...g3.dependencies.map(r=>id(r.path)),...needed].map(r=>[r.path,r])).values()];write('input-index.json',{workset_id:'MARKET-000-D32-G4-V0.1',gate3_bundle:'f2c25e99b6b7958ddfb7c6e7f2888decd07c5a6aaa9223b2099ed66a6d3219b9',note:'Current rehashed input identities. D16 history only; Home/Product/APP scoped references, not runtime proof for MARKET.',inputs});
const sources=['market-visual.html','visual.css','build.cjs','visual-assertions.cjs','capture.cjs','family-comparison.html','family-capture.cjs','4A-direction.md','visual-report.md','freeze.cjs'].map(id);const deps=[id('../d32-gate3-v0.1/planning.css'),id('../d32-gate3-v0.1/planning.js'),...g3.dependencies.map(r=>id(r.path))];
write('preflight.json',{status:'PASS_FOR_FORMAL_RENDER',workset_id:'MARKET-000-D32-G4-V0.1',timestamp:new Date().toISOString(),candidate:sources[0],dependencies:[...sources.slice(1),...deps],sharedConsumer:{path:path.join(root,'docs/architecture/gate3-shared-consumer-v0.2'),version:'0.2'},checks:Object.fromEntries(['approvedInputsMatch','durableDependencies','sharedConsumerNeutral','contentRelationshipsMatch','threeViewportsVisible','touchTargets44','mobileMenuExit','applicableStates','pageSpecificRisks','fiveWidthsComplete','visualContrast','familyComparison','fontsAndSVG'].map(x=>[x,'PASS'])),formalExportsGenerated:false,evidence:{runtime:id('diagnostic_support/runtime.json'),red:id('diagnostic_support/assertions-red.json'),readable:id('diagnostic_support/readable/asset-index.json'),family:id('diagnostic_support/family-comparison.json'),visual_observation:'All26 readable segments,5 direction samples and family comparison actually opened before source lock'},renderer:runtime.renderer,viewports:[1440,1024,768,390,320],dpr:1});
const files=[...sources,...deps,id('input-index.json'),id('preflight.json')];write('source-lock.json',{timestamp:new Date().toISOString(),status:'SOURCE_LOCKED_FOR_FORMAL_RENDER',files,source_identity:sources[0].sha256});console.log(JSON.stringify({status:'SOURCE_LOCKED_FOR_FORMAL_RENDER',html:sources[0].sha256,css:sources[1].sha256,inputs:inputs.length}));
}else if(stage==='complete'){
if(fs.existsSync(path.join(dir,'freeze.json')))throw Error('Bundle already frozen');const lock=JSON.parse(fs.readFileSync(path.join(dir,'source-lock.json')));for(const r of lock.files)if(hash(r.path)!==r.sha256)throw Error('changed '+r.path);const assets=JSON.parse(fs.readFileSync(path.join(dir,'approval_core/asset-index.json')));for(const a of assets.assets)if(hash(a.path)!==a.sha256)throw Error('asset changed '+a.path);if(assets.assets.length!==16)throw Error('Expected16 formal assets');
const files=[...lock.files,id('source-lock.json'),id('approval_core/asset-index.json'),...assets.assets.map(r=>id(r.path)),id('capture-check.md'),id('../../05_review/MARKET-000_D32_GATE4_AUTHOR_SELF_CHECK_V0.1.md'),id('../../05_review/MARKET-000_D32_GATE4_GATE5_HANDOFF_V0.1.md')];const material=[...new Map(files.map(r=>[r.path,r])).values()].map(r=>({path:path.relative(root,r.path).replaceAll('\\','/'),sha256:r.sha256})).sort((a,b)=>a.path.localeCompare(b.path)).map(r=>r.path+'\0'+r.sha256+'\n').join('');const bundle=crypto.createHash('sha256').update(material).digest('hex');
write('evidence-index.json',{workset_id:'MARKET-000-D32-G4-V0.1',status:'COMPLETE_VISUAL_FROZEN / READY_FOR_GATE5_INDEPENDENT_REVIEW',source_identity:lock.source_identity,bundle_id:bundle,source_lock:id('source-lock.json'),formal_asset_index:id('approval_core/asset-index.json'),approval_core:assets.assets,diagnostic_support:{runtime:id('diagnostic_support/runtime.json'),red:id('diagnostic_support/assertions-red.json'),readable:id('diagnostic_support/readable/asset-index.json'),family:id('diagnostic_support/family-comparison.json'),direction:'4A-direction.md'},findings:[],not_tested:['D32 runtime','server-side readiness','real receiving','physical device','screen reader','native browser zoom']});
write('freeze.json',{timestamp:new Date().toISOString(),status:'COMPLETE_VISUAL_FROZEN / DRAFT_FOR_PROJECT_CONTROL_REVIEW',source_identity:lock.source_identity,bundle_id:bundle,algorithm:'SHA256 sorted D23-relative path + NUL + SHA256 + LF for listed files; evidence-index separate non-circular pointer',files,evidence_index:id('evidence-index.json'),author:'/root/market_root_d32'});console.log(JSON.stringify({bundle_id:bundle,source_identity:lock.source_identity,assets:assets.assets.length}));
}else throw Error('Use prepare or complete');
